using System.IO;

public class AAHBFGFDINE : AOKAOIHEKIH
{
	public AAHBFGFDINE(byte[] MOPCLEEGDFB)
		: base(MOPCLEEGDFB)
	{
	}

	public AAHBFGFDINE(Stream KOAGMLLMNLB)
		: base(KOAGMLLMNLB)
	{
	}

	internal override KOGPLMALOEH NOMAAAMBLJI(DIKEJAHBNGH IJFDHDOHBEF)
	{
		return new OONKDNOAIKK(IJFDHDOHBEF.GDPLKNIEGDB());
	}

	internal override CDHAHIDPGBP NDJFAPHNLGJ(DIKEJAHBNGH IJFDHDOHBEF)
	{
		return new PIBKMEGHMOC(IJFDHDOHBEF.GDPLKNIEGDB());
	}
}
