using System.Collections;
using System.Collections.Generic;

public interface AFKEOGBFCBE : NGBFPFEHHNG
{
	List<string> KCGKBOHNIPE { get; set; }

	OBDIBELBBEO ONMBHGAEFAP { get; }

	OBDIBELBBEO BEHNDIMGDKM { get; }

	bool NABMKHFPEJE { get; }

	void DIOELAHNLKJ(JFEIHACOLNL MBEMNOCDDBC);

	POBPBLILLLP LACFMMKMGIO();

	int[] JJABFAMPIIB();

	byte[] CPIOFBAJBGI();

	IDictionary BHNEJODLNJI();

	void OFBJOJNMMKO(OBDIBELBBEO AJPODMLJDIC);

	void AGBLBIICBDC(byte[] OEPIOANFJDF);

	void GHMPCEPDDAB(int MCBKAEMNHAF);

	void NMBKKHBCEKJ(byte IFNHDMDCLHE);

	void BEAKIHMNDJG(IDictionary LJDFGPJGHFH);

	void BIMLMGADCAL(IList FNAIBLIAKCB);

	HMPLNBAPPNE CNJBDCLEKNL();

	HFLDELFJCEE DNHBFEBDMPF();

	IList BBJOJOFIFCO();

	void COOBDCPKGBF(GDAIELDPMAD PIPDHBFKMLP);
}
