using Spine;

public class AIHPPKDLPLG : FPOBLOBNHGG
{
	public const int JMPDFJHAGOA = 5;

	protected const int AMJGBMFEPLB = -5;

	protected const int DGDAHGJMLDC = -4;

	protected const int AKBCENGCHLC = -3;

	protected const int EOHKIJCGNNH = -2;

	protected const int BCJOFFNPHEC = -1;

	protected const int GOEFJMNOBHA = 1;

	protected const int HBGOKILMBJG = 2;

	protected const int FPKDKHJKEEF = 3;

	protected const int JEHECJGFJEB = 4;

	internal int PBPEMFGPGFC;

	internal float[] ENBKHCNKHCC;

	public int ONPPEPBHGCK
	{
		get
		{
			return PBPEMFGPGFC;
		}
		set
		{
			PBPEMFGPGFC = value;
		}
	}

	public float[] IKOJIGLMFNG
	{
		get
		{
			return ENBKHCNKHCC;
		}
		set
		{
			ENBKHCNKHCC = value;
		}
	}

	public override int ODHLEJHEBGD
	{
		get
		{
			return 83886080 + PBPEMFGPGFC;
		}
	}

	public AIHPPKDLPLG(int IJKENLLBMOJ)
		: base(IJKENLLBMOJ)
	{
		ENBKHCNKHCC = new float[IJKENLLBMOJ * 5];
	}

	public void BCEFHMIKFDC(int JHFDIBIBCPH, float HFLODNLEGFL, float GPGDCCMECGF, float HJMBDGKAOBP, float BCIHLCMFAEK, float MNIMEAMHNMI)
	{
		JHFDIBIBCPH *= 5;
		ENBKHCNKHCC[JHFDIBIBCPH] = HFLODNLEGFL;
		ENBKHCNKHCC[JHFDIBIBCPH + 1] = GPGDCCMECGF;
		ENBKHCNKHCC[JHFDIBIBCPH + 2] = HJMBDGKAOBP;
		ENBKHCNKHCC[JHFDIBIBCPH + 3] = BCIHLCMFAEK;
		ENBKHCNKHCC[JHFDIBIBCPH + 4] = MNIMEAMHNMI;
	}

	public override void FCHLOGCODOA(GCJKICAPOFL GDNININLMFD, float CGICCPOKJHB, float HFLODNLEGFL, ExposedList<DCBJAMHBAJB> ELMIMIMBNHP, float KBKMPEOMABI, BFCFMFBHBCH IFKBABBBDJM, ODPDBCNBOAK AJLDJAHHGOJ)
	{
		LBBAMMPJKDA lBBAMMPJKDA = GDNININLMFD.MAKCMFCFDLP.Items[PBPEMFGPGFC];
		float[] eNBKHCNKHCC = ENBKHCNKHCC;
		if (HFLODNLEGFL < eNBKHCNKHCC[0])
		{
			HMGLMNHOBHA mBBPBGHKLJM = lBBAMMPJKDA.MBBPBGHKLJM;
			switch (IFKBABBBDJM)
			{
			case BFCFMFBHBCH.Setup:
				lBBAMMPJKDA.GPGDCCMECGF = mBBPBGHKLJM.GPGDCCMECGF;
				lBBAMMPJKDA.HJMBDGKAOBP = mBBPBGHKLJM.HJMBDGKAOBP;
				lBBAMMPJKDA.BCIHLCMFAEK = mBBPBGHKLJM.BCIHLCMFAEK;
				lBBAMMPJKDA.MNIMEAMHNMI = mBBPBGHKLJM.MNIMEAMHNMI;
				break;
			case BFCFMFBHBCH.Current:
				lBBAMMPJKDA.GPGDCCMECGF += (lBBAMMPJKDA.GPGDCCMECGF - mBBPBGHKLJM.GPGDCCMECGF) * KBKMPEOMABI;
				lBBAMMPJKDA.HJMBDGKAOBP += (lBBAMMPJKDA.HJMBDGKAOBP - mBBPBGHKLJM.HJMBDGKAOBP) * KBKMPEOMABI;
				lBBAMMPJKDA.BCIHLCMFAEK += (lBBAMMPJKDA.BCIHLCMFAEK - mBBPBGHKLJM.BCIHLCMFAEK) * KBKMPEOMABI;
				lBBAMMPJKDA.MNIMEAMHNMI += (lBBAMMPJKDA.MNIMEAMHNMI - mBBPBGHKLJM.MNIMEAMHNMI) * KBKMPEOMABI;
				break;
			}
			return;
		}
		float num2;
		float num3;
		float num4;
		float num5;
		if (HFLODNLEGFL >= eNBKHCNKHCC[eNBKHCNKHCC.Length - 5])
		{
			int num = eNBKHCNKHCC.Length;
			num2 = eNBKHCNKHCC[num + -4];
			num3 = eNBKHCNKHCC[num + -3];
			num4 = eNBKHCNKHCC[num + -2];
			num5 = eNBKHCNKHCC[num + -1];
		}
		else
		{
			int num6 = GNGKKPOGGGM.EIAMMDBFDFO(eNBKHCNKHCC, HFLODNLEGFL, 5);
			num2 = eNBKHCNKHCC[num6 + -4];
			num3 = eNBKHCNKHCC[num6 + -3];
			num4 = eNBKHCNKHCC[num6 + -2];
			num5 = eNBKHCNKHCC[num6 + -1];
			float num7 = eNBKHCNKHCC[num6];
			float num8 = IFMKHGLKEMB(num6 / 5 - 1, 1f - (HFLODNLEGFL - num7) / (eNBKHCNKHCC[num6 + -5] - num7));
			num2 += (eNBKHCNKHCC[num6 + 1] - num2) * num8;
			num3 += (eNBKHCNKHCC[num6 + 2] - num3) * num8;
			num4 += (eNBKHCNKHCC[num6 + 3] - num4) * num8;
			num5 += (eNBKHCNKHCC[num6 + 4] - num5) * num8;
		}
		if (KBKMPEOMABI == 1f)
		{
			lBBAMMPJKDA.GPGDCCMECGF = num2;
			lBBAMMPJKDA.HJMBDGKAOBP = num3;
			lBBAMMPJKDA.BCIHLCMFAEK = num4;
			lBBAMMPJKDA.MNIMEAMHNMI = num5;
			return;
		}
		float gPGDCCMECGF;
		float hJMBDGKAOBP;
		float bCIHLCMFAEK;
		float mNIMEAMHNMI;
		if (IFKBABBBDJM == BFCFMFBHBCH.Setup)
		{
			gPGDCCMECGF = lBBAMMPJKDA.MBBPBGHKLJM.GPGDCCMECGF;
			hJMBDGKAOBP = lBBAMMPJKDA.MBBPBGHKLJM.HJMBDGKAOBP;
			bCIHLCMFAEK = lBBAMMPJKDA.MBBPBGHKLJM.BCIHLCMFAEK;
			mNIMEAMHNMI = lBBAMMPJKDA.MBBPBGHKLJM.MNIMEAMHNMI;
		}
		else
		{
			gPGDCCMECGF = lBBAMMPJKDA.GPGDCCMECGF;
			hJMBDGKAOBP = lBBAMMPJKDA.HJMBDGKAOBP;
			bCIHLCMFAEK = lBBAMMPJKDA.BCIHLCMFAEK;
			mNIMEAMHNMI = lBBAMMPJKDA.MNIMEAMHNMI;
		}
		lBBAMMPJKDA.GPGDCCMECGF = gPGDCCMECGF + (num2 - gPGDCCMECGF) * KBKMPEOMABI;
		lBBAMMPJKDA.HJMBDGKAOBP = hJMBDGKAOBP + (num3 - hJMBDGKAOBP) * KBKMPEOMABI;
		lBBAMMPJKDA.BCIHLCMFAEK = bCIHLCMFAEK + (num4 - bCIHLCMFAEK) * KBKMPEOMABI;
		lBBAMMPJKDA.MNIMEAMHNMI = mNIMEAMHNMI + (num5 - mNIMEAMHNMI) * KBKMPEOMABI;
	}
}
