using Org.BouncyCastle.Math;

internal class AJGCHNBEMAE
{
	internal static readonly uint[] MBIJHANOCOC = new uint[6] { 4294962743u, 4294967294u, 4294967295u, 4294967295u, 4294967295u, 4294967295u };

	internal static readonly uint[] PKABKFGEMBB = new uint[12]
	{
		20729809u, 9106u, 1u, 0u, 0u, 0u, 4294958190u, 4294967293u, 4294967295u, 4294967295u,
		4294967295u, 4294967295u
	};

	private static readonly uint[] BPGLGHCLMCD = new uint[8] { 4274237487u, 4294958189u, 4294967294u, 4294967295u, 4294967295u, 4294967295u, 9105u, 2u };

	private const uint AEEBNAHFLBN = uint.MaxValue;

	private const uint PFEOKJIFAME = uint.MaxValue;

	private const uint BIFDMIEAMDM = 4553u;

	public static void JEACJNAKLDJ(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		if (PHEKPHCPKLA.JEACJNAKLDJ(AMFCENFNAJJ, CNLILOEEBOJ, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[5] == uint.MaxValue && PHEKPHCPKLA.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(6, 4553u, IGNEOOOFEMO);
		}
	}

	public static void KGBEKKMEBCN(uint[] HGHHJPDIMCI, uint[] IKEIELCEKPD, uint[] JMNJPLAGDDJ)
	{
		if ((BCMDHIIJKJE.JEACJNAKLDJ(12, HGHHJPDIMCI, IKEIELCEKPD, JMNJPLAGDDJ) != 0 || (JMNJPLAGDDJ[11] == uint.MaxValue && BCMDHIIJKJE.CHCGDEIGIIA(12, JMNJPLAGDDJ, PKABKFGEMBB))) && BCMDHIIJKJE.MAALDEFJPJA(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.DKCBNAFCCMF(12, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void AOAINNMNBHC(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (BCMDHIIJKJE.CKIHMFAAHLM(6, AMFCENFNAJJ, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[5] == uint.MaxValue && PHEKPHCPKLA.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(6, 4553u, IGNEOOOFEMO);
		}
	}

	public static uint[] HFENNGHNFLF(BigInteger AMFCENFNAJJ)
	{
		uint[] array = PHEKPHCPKLA.HFENNGHNFLF(AMFCENFNAJJ);
		if (array[5] == uint.MaxValue && PHEKPHCPKLA.CHCGDEIGIIA(array, MBIJHANOCOC))
		{
			PHEKPHCPKLA.DKAMAFLMHEJ(MBIJHANOCOC, array);
		}
		return array;
	}

	public static void CBGFKBFBIFD(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if ((AMFCENFNAJJ[0] & 1) == 0)
		{
			BCMDHIIJKJE.POFAGJIFAIH(6, AMFCENFNAJJ, 0u, IGNEOOOFEMO);
			return;
		}
		uint fMFABAKPMLB = PHEKPHCPKLA.JEACJNAKLDJ(AMFCENFNAJJ, MBIJHANOCOC, IGNEOOOFEMO);
		BCMDHIIJKJE.POFAGJIFAIH(6, IGNEOOOFEMO, fMFABAKPMLB);
	}

	public static void IBJBIGNPNEM(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = PHEKPHCPKLA.DCPJKFEDHOJ();
		PHEKPHCPKLA.BMEIFJDODCF(AMFCENFNAJJ, CNLILOEEBOJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
	}

	public static void OMJFFHEIEFH(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] JMNJPLAGDDJ)
	{
		if ((PHEKPHCPKLA.HHMEIAJHDJM(AMFCENFNAJJ, CNLILOEEBOJ, JMNJPLAGDDJ) != 0 || (JMNJPLAGDDJ[11] == uint.MaxValue && BCMDHIIJKJE.CHCGDEIGIIA(12, JMNJPLAGDDJ, PKABKFGEMBB))) && BCMDHIIJKJE.MAALDEFJPJA(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.DKCBNAFCCMF(12, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void BHKOFHMDACN(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (PHEKPHCPKLA.EJJHHCOFAAI(AMFCENFNAJJ))
		{
			PHEKPHCPKLA.KEOKCFDNHPP(IGNEOOOFEMO);
		}
		else
		{
			PHEKPHCPKLA.EAEONHFLEEN(MBIJHANOCOC, AMFCENFNAJJ, IGNEOOOFEMO);
		}
	}

	public static void BKCHMGKFECM(uint[] HGHHJPDIMCI, uint[] IGNEOOOFEMO)
	{
		ulong cNLILOEEBOJ = PHEKPHCPKLA.FGMIACGNJLN(4553u, HGHHJPDIMCI, 6, HGHHJPDIMCI, 0, IGNEOOOFEMO, 0);
		if (PHEKPHCPKLA.CDNAAKLGHLD(4553u, cNLILOEEBOJ, IGNEOOOFEMO, 0) != 0 || (IGNEOOOFEMO[5] == uint.MaxValue && PHEKPHCPKLA.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(6, 4553u, IGNEOOOFEMO);
		}
	}

	public static void KKIGIOINLCI(uint AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if ((AMFCENFNAJJ != 0 && PHEKPHCPKLA.KDGIJAIDNND(4553u, AMFCENFNAJJ, IGNEOOOFEMO, 0) != 0) || (IGNEOOOFEMO[5] == uint.MaxValue && PHEKPHCPKLA.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(6, 4553u, IGNEOOOFEMO);
		}
	}

	public static void MIOEHGDPGAG(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = PHEKPHCPKLA.DCPJKFEDHOJ();
		PHEKPHCPKLA.MIOEHGDPGAG(AMFCENFNAJJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
	}

	public static void OIEFGPHNOFN(uint[] AMFCENFNAJJ, int IDHLPOFDLKJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = PHEKPHCPKLA.DCPJKFEDHOJ();
		PHEKPHCPKLA.MIOEHGDPGAG(AMFCENFNAJJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
		while (--IDHLPOFDLKJ > 0)
		{
			PHEKPHCPKLA.MIOEHGDPGAG(IGNEOOOFEMO, array);
			BKCHMGKFECM(array, IGNEOOOFEMO);
		}
	}

	public static void FBGIHKPECCO(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		if (PHEKPHCPKLA.EAEONHFLEEN(AMFCENFNAJJ, CNLILOEEBOJ, IGNEOOOFEMO) != 0)
		{
			BCMDHIIJKJE.KGIMHKMDCKA(6, 4553u, IGNEOOOFEMO);
		}
	}

	public static void OIKFFIIOCPO(uint[] HGHHJPDIMCI, uint[] IKEIELCEKPD, uint[] JMNJPLAGDDJ)
	{
		if (BCMDHIIJKJE.EAEONHFLEEN(12, HGHHJPDIMCI, IKEIELCEKPD, JMNJPLAGDDJ) != 0 && BCMDHIIJKJE.DKAMAFLMHEJ(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.MEJBLKJLLNK(12, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void LLGLJBDLBOP(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (BCMDHIIJKJE.FKEFFJALNJM(6, AMFCENFNAJJ, 0u, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[5] == uint.MaxValue && PHEKPHCPKLA.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(6, 4553u, IGNEOOOFEMO);
		}
	}
}
