using Org.BouncyCastle.Math;

internal class AMEIPDBNOGO
{
	internal static readonly uint[] MBIJHANOCOC = new uint[17]
	{
		4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u,
		4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 511u
	};

	private const int CJELIEINMAD = 511;

	public static void JEACJNAKLDJ(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		uint num = BCMDHIIJKJE.JEACJNAKLDJ(16, AMFCENFNAJJ, CNLILOEEBOJ, IGNEOOOFEMO) + AMFCENFNAJJ[16] + CNLILOEEBOJ[16];
		if (num > 511 || (num == 511 && BCMDHIIJKJE.HIPMIOOIEJO(16, IGNEOOOFEMO, MBIJHANOCOC)))
		{
			num += BCMDHIIJKJE.CKIHMFAAHLM(16, IGNEOOOFEMO);
			num &= 0x1FFu;
		}
		IGNEOOOFEMO[16] = num;
	}

	public static void AOAINNMNBHC(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		uint num = BCMDHIIJKJE.CKIHMFAAHLM(16, AMFCENFNAJJ, IGNEOOOFEMO) + AMFCENFNAJJ[16];
		if (num > 511 || (num == 511 && BCMDHIIJKJE.HIPMIOOIEJO(16, IGNEOOOFEMO, MBIJHANOCOC)))
		{
			num += BCMDHIIJKJE.CKIHMFAAHLM(16, IGNEOOOFEMO);
			num &= 0x1FFu;
		}
		IGNEOOOFEMO[16] = num;
	}

	public static uint[] HFENNGHNFLF(BigInteger AMFCENFNAJJ)
	{
		uint[] array = BCMDHIIJKJE.HFENNGHNFLF(521, AMFCENFNAJJ);
		if (BCMDHIIJKJE.HIPMIOOIEJO(17, array, MBIJHANOCOC))
		{
			BCMDHIIJKJE.KEOKCFDNHPP(17, array);
		}
		return array;
	}

	public static void CBGFKBFBIFD(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		uint num = AMFCENFNAJJ[16];
		uint num2 = BCMDHIIJKJE.POFAGJIFAIH(16, AMFCENFNAJJ, num, IGNEOOOFEMO);
		IGNEOOOFEMO[16] = (num >> 1) | (num2 >> 23);
	}

	public static void IBJBIGNPNEM(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = BCMDHIIJKJE.PLIFFMMBNPM(33);
		NEIMDHAFMNO(AMFCENFNAJJ, CNLILOEEBOJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
	}

	public static void BHKOFHMDACN(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (BCMDHIIJKJE.EJJHHCOFAAI(17, AMFCENFNAJJ))
		{
			BCMDHIIJKJE.KEOKCFDNHPP(17, IGNEOOOFEMO);
		}
		else
		{
			BCMDHIIJKJE.EAEONHFLEEN(17, MBIJHANOCOC, AMFCENFNAJJ, IGNEOOOFEMO);
		}
	}

	public static void BKCHMGKFECM(uint[] HGHHJPDIMCI, uint[] IGNEOOOFEMO)
	{
		uint num = HGHHJPDIMCI[32];
		uint num2 = BCMDHIIJKJE.HKHBMKOABPB(16, HGHHJPDIMCI, 16, 9, num, IGNEOOOFEMO, 0) >> 23;
		num2 += num >> 9;
		num2 += BCMDHIIJKJE.MAALDEFJPJA(16, HGHHJPDIMCI, IGNEOOOFEMO);
		if (num2 > 511 || (num2 == 511 && BCMDHIIJKJE.HIPMIOOIEJO(16, IGNEOOOFEMO, MBIJHANOCOC)))
		{
			num2 += BCMDHIIJKJE.CKIHMFAAHLM(16, IGNEOOOFEMO);
			num2 &= 0x1FFu;
		}
		IGNEOOOFEMO[16] = num2;
	}

	public static void LJNDDEIFKPD(uint[] IGNEOOOFEMO)
	{
		uint num = IGNEOOOFEMO[16];
		uint num2 = BCMDHIIJKJE.GEDBFLNFIHI(16, num >> 9, IGNEOOOFEMO) + (num & 0x1FF);
		if (num2 > 511 || (num2 == 511 && BCMDHIIJKJE.HIPMIOOIEJO(16, IGNEOOOFEMO, MBIJHANOCOC)))
		{
			num2 += BCMDHIIJKJE.CKIHMFAAHLM(16, IGNEOOOFEMO);
			num2 &= 0x1FFu;
		}
		IGNEOOOFEMO[16] = num2;
	}

	public static void MIOEHGDPGAG(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = BCMDHIIJKJE.PLIFFMMBNPM(33);
		MMBGDFPOOKF(AMFCENFNAJJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
	}

	public static void OIEFGPHNOFN(uint[] AMFCENFNAJJ, int IDHLPOFDLKJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = BCMDHIIJKJE.PLIFFMMBNPM(33);
		MMBGDFPOOKF(AMFCENFNAJJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
		while (--IDHLPOFDLKJ > 0)
		{
			MMBGDFPOOKF(IGNEOOOFEMO, array);
			BKCHMGKFECM(array, IGNEOOOFEMO);
		}
	}

	public static void FBGIHKPECCO(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		int num = BCMDHIIJKJE.EAEONHFLEEN(16, AMFCENFNAJJ, CNLILOEEBOJ, IGNEOOOFEMO) + (int)(AMFCENFNAJJ[16] - CNLILOEEBOJ[16]);
		if (num < 0)
		{
			num += BCMDHIIJKJE.KJFCLPNALMG(16, IGNEOOOFEMO);
			num &= 0x1FF;
		}
		IGNEOOOFEMO[16] = (uint)num;
	}

	public static void LLGLJBDLBOP(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		uint num = AMFCENFNAJJ[16];
		uint num2 = BCMDHIIJKJE.FKEFFJALNJM(16, AMFCENFNAJJ, num << 23, IGNEOOOFEMO) | (num << 1);
		IGNEOOOFEMO[16] = num2 & 0x1FFu;
	}

	protected static void NEIMDHAFMNO(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] JMNJPLAGDDJ)
	{
		CLKJLHBLJAH.BMEIFJDODCF(AMFCENFNAJJ, CNLILOEEBOJ, JMNJPLAGDDJ);
		uint num = AMFCENFNAJJ[16];
		uint num2 = CNLILOEEBOJ[16];
		JMNJPLAGDDJ[32] = BCMDHIIJKJE.ACPCGFGJIHE(16, num, CNLILOEEBOJ, num2, AMFCENFNAJJ, JMNJPLAGDDJ, 16) + num * num2;
	}

	protected static void MMBGDFPOOKF(uint[] AMFCENFNAJJ, uint[] JMNJPLAGDDJ)
	{
		CLKJLHBLJAH.MIOEHGDPGAG(AMFCENFNAJJ, JMNJPLAGDDJ);
		uint num = AMFCENFNAJJ[16];
		JMNJPLAGDDJ[32] = BCMDHIIJKJE.HAFIKHOEMNC(16, num << 1, AMFCENFNAJJ, 0, JMNJPLAGDDJ, 16) + num * num;
	}
}
