public interface AMNDAOFCJPG
{
	string KFKMEPMEBND { get; }

	void DIOELAHNLKJ(bool MAEALKEJALK, IGMAJHKIIPK IJJHBEECMBP);

	int BDIGGHEPIIP();

	int ACLDAECDPFN(int HAPPHECIDKJ);

	int MIMJCMAODEK(int HAPPHECIDKJ);

	byte[] HBCJNPGKMDP(byte MOPCLEEGDFB);

	int HBCJNPGKMDP(byte MOPCLEEGDFB, byte[] BILGCJNPJGJ, int EMAKNGBIFDC);

	byte[] POCAGALIPAI(byte[] MOPCLEEGDFB);

	byte[] POCAGALIPAI(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int EOFAGACBNFP);

	int POCAGALIPAI(byte[] MOPCLEEGDFB, byte[] BILGCJNPJGJ, int EMAKNGBIFDC);

	int POCAGALIPAI(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int EOFAGACBNFP, byte[] BILGCJNPJGJ, int EMAKNGBIFDC);

	byte[] LCNOFBMOHHM();

	byte[] LCNOFBMOHHM(byte[] MOPCLEEGDFB);

	byte[] LCNOFBMOHHM(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int EOFAGACBNFP);

	int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC);

	int LCNOFBMOHHM(byte[] MOPCLEEGDFB, byte[] BILGCJNPJGJ, int EMAKNGBIFDC);

	int LCNOFBMOHHM(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int EOFAGACBNFP, byte[] BILGCJNPJGJ, int EMAKNGBIFDC);

	void OMOKOKFNBKI();
}
