using System.Collections;

public class BBLDODBKNIN
{
	public static IEnumerable IBDKONGLAHK
	{
		get
		{
			IList list = LHFGHNFJIKM.PPPFFFBMGML();
			FKHLBMJPCIM.OJCDNLBIAPD(list, HDALFJFBFCF.IBDKONGLAHK);
			FKHLBMJPCIM.OJCDNLBIAPD(list, HGIJNPOCIFN.IBDKONGLAHK);
			FKHLBMJPCIM.OJCDNLBIAPD(list, IFMGMOAKJAD.IBDKONGLAHK);
			FKHLBMJPCIM.OJCDNLBIAPD(list, FJJFOEELLJJ.IBDKONGLAHK);
			FKHLBMJPCIM.OJCDNLBIAPD(list, OAGIJKBMDEP.IBDKONGLAHK);
			return list;
		}
	}

	public static JMLDNPGFBDA KJOGHMPFOHL(string IOCMOCCFALN)
	{
		JMLDNPGFBDA jMLDNPGFBDA = HDALFJFBFCF.KJOGHMPFOHL(IOCMOCCFALN);
		if (jMLDNPGFBDA == null)
		{
			jMLDNPGFBDA = HGIJNPOCIFN.KJOGHMPFOHL(IOCMOCCFALN);
		}
		if (jMLDNPGFBDA == null)
		{
			jMLDNPGFBDA = IFMGMOAKJAD.KJOGHMPFOHL(IOCMOCCFALN);
		}
		if (jMLDNPGFBDA == null)
		{
			jMLDNPGFBDA = FJJFOEELLJJ.KJOGHMPFOHL(IOCMOCCFALN);
		}
		if (jMLDNPGFBDA == null)
		{
			jMLDNPGFBDA = OAGIJKBMDEP.KJOGHMPFOHL(IOCMOCCFALN);
		}
		return jMLDNPGFBDA;
	}

	public static string CILJKDELPFP(KLKJHFKJLEM GDFLIKNMBCL)
	{
		string text = HDALFJFBFCF.CILJKDELPFP(GDFLIKNMBCL);
		if (text == null)
		{
			text = HGIJNPOCIFN.CILJKDELPFP(GDFLIKNMBCL);
		}
		if (text == null)
		{
			text = IFMGMOAKJAD.CILJKDELPFP(GDFLIKNMBCL);
		}
		if (text == null)
		{
			text = FJJFOEELLJJ.CILJKDELPFP(GDFLIKNMBCL);
		}
		if (text == null)
		{
			text = OAGIJKBMDEP.CILJKDELPFP(GDFLIKNMBCL);
		}
		return text;
	}

	public static KLKJHFKJLEM MAKKKJHMAHH(string IOCMOCCFALN)
	{
		KLKJHFKJLEM kLKJHFKJLEM = HDALFJFBFCF.MAKKKJHMAHH(IOCMOCCFALN);
		if (kLKJHFKJLEM == null)
		{
			kLKJHFKJLEM = HGIJNPOCIFN.MAKKKJHMAHH(IOCMOCCFALN);
		}
		if (kLKJHFKJLEM == null)
		{
			kLKJHFKJLEM = IFMGMOAKJAD.MAKKKJHMAHH(IOCMOCCFALN);
		}
		if (kLKJHFKJLEM == null)
		{
			kLKJHFKJLEM = FJJFOEELLJJ.MAKKKJHMAHH(IOCMOCCFALN);
		}
		if (kLKJHFKJLEM == null)
		{
			kLKJHFKJLEM = OAGIJKBMDEP.MAKKKJHMAHH(IOCMOCCFALN);
		}
		return kLKJHFKJLEM;
	}

	public static JMLDNPGFBDA BHLONOMMIGE(KLKJHFKJLEM GDFLIKNMBCL)
	{
		JMLDNPGFBDA jMLDNPGFBDA = HDALFJFBFCF.BHLONOMMIGE(GDFLIKNMBCL);
		if (jMLDNPGFBDA == null)
		{
			jMLDNPGFBDA = HGIJNPOCIFN.BHLONOMMIGE(GDFLIKNMBCL);
		}
		if (jMLDNPGFBDA == null)
		{
			jMLDNPGFBDA = FJJFOEELLJJ.BHLONOMMIGE(GDFLIKNMBCL);
		}
		if (jMLDNPGFBDA == null)
		{
			jMLDNPGFBDA = OAGIJKBMDEP.BHLONOMMIGE(GDFLIKNMBCL);
		}
		return jMLDNPGFBDA;
	}
}
