using System;
using UnityEngine;

public static class BBMMGLCAFJG
{
	public static OAMNGFLKEFI BNKOCCCOFMO(this OAMNGFLKEFI AACCPLMFDIE, bool CANENDBIPLL)
	{
		MKEALIMJCFJ mKEALIMJCFJ = AACCPLMFDIE as MKEALIMJCFJ;
		if (mKEALIMJCFJ != null)
		{
			return mKEALIMJCFJ.BNKOCCCOFMO();
		}
		MGCLDKAFCIB mGCLDKAFCIB = AACCPLMFDIE as MGCLDKAFCIB;
		if (mGCLDKAFCIB != null)
		{
			return (!CANENDBIPLL) ? mGCLDKAFCIB.BNKOCCCOFMO() : mGCLDKAFCIB.OHGDCEOOGEI();
		}
		KBLNEHAAAJK kBLNEHAAAJK = AACCPLMFDIE as KBLNEHAAAJK;
		if (kBLNEHAAAJK != null)
		{
			return kBLNEHAAAJK.BNKOCCCOFMO();
		}
		GMLCOKFENFN gMLCOKFENFN = AACCPLMFDIE as GMLCOKFENFN;
		if (gMLCOKFENFN != null)
		{
			return gMLCOKFENFN.BNKOCCCOFMO();
		}
		ENIPPOEKJPA eNIPPOEKJPA = AACCPLMFDIE as ENIPPOEKJPA;
		if (eNIPPOEKJPA != null)
		{
			return eNIPPOEKJPA.BNKOCCCOFMO();
		}
		ACEGNBDLKEG aCEGNBDLKEG = AACCPLMFDIE as ACEGNBDLKEG;
		if (aCEGNBDLKEG != null)
		{
			return aCEGNBDLKEG.BNKOCCCOFMO();
		}
		return null;
	}

	public static MKEALIMJCFJ BNKOCCCOFMO(this MKEALIMJCFJ AACCPLMFDIE)
	{
		MKEALIMJCFJ mKEALIMJCFJ = new MKEALIMJCFJ(AACCPLMFDIE.PNGPLGHKFDI + "clone");
		mKEALIMJCFJ.AMFCENFNAJJ = AACCPLMFDIE.AMFCENFNAJJ;
		mKEALIMJCFJ.CNLILOEEBOJ = AACCPLMFDIE.CNLILOEEBOJ;
		mKEALIMJCFJ.ODLHFMOPCHL = AACCPLMFDIE.ODLHFMOPCHL;
		mKEALIMJCFJ.IAFNPOKEFMB = AACCPLMFDIE.IAFNPOKEFMB;
		mKEALIMJCFJ.GFMCPIJHIGD = AACCPLMFDIE.GFMCPIJHIGD;
		mKEALIMJCFJ.HHHMOGOKFHF = AACCPLMFDIE.HHHMOGOKFHF;
		mKEALIMJCFJ.JKNPBEOPMPK = AACCPLMFDIE.JKNPBEOPMPK;
		mKEALIMJCFJ.GPGDCCMECGF = AACCPLMFDIE.GPGDCCMECGF;
		mKEALIMJCFJ.HJMBDGKAOBP = AACCPLMFDIE.HJMBDGKAOBP;
		mKEALIMJCFJ.BCIHLCMFAEK = AACCPLMFDIE.BCIHLCMFAEK;
		mKEALIMJCFJ.MNIMEAMHNMI = AACCPLMFDIE.MNIMEAMHNMI;
		mKEALIMJCFJ.MJCBDBIDMGF = AACCPLMFDIE.MJCBDBIDMGF;
		mKEALIMJCFJ.HIPOEPNPBPO = AACCPLMFDIE.HIPOEPNPBPO;
		mKEALIMJCFJ.MBHOIJFNKPO = AACCPLMFDIE.MBHOIJFNKPO;
		mKEALIMJCFJ.JGEIMMGNNFN = AACCPLMFDIE.JGEIMMGNNFN;
		mKEALIMJCFJ.ECJFPIOKKGN = AACCPLMFDIE.ECJFPIOKKGN;
		mKEALIMJCFJ.MJCEICPLJKP = AACCPLMFDIE.MJCEICPLJKP;
		mKEALIMJCFJ.LBNLLJNGJHP = AACCPLMFDIE.LBNLLJNGJHP;
		mKEALIMJCFJ.HLMKOMNGAMA = AACCPLMFDIE.HLMKOMNGAMA;
		mKEALIMJCFJ.NDIFGLEBDLE = AACCPLMFDIE.NDIFGLEBDLE.Clone() as float[];
		mKEALIMJCFJ.IBNDGNOIEEF = AACCPLMFDIE.IBNDGNOIEEF.Clone() as float[];
		return mKEALIMJCFJ;
	}

	public static ACEGNBDLKEG BNKOCCCOFMO(this ACEGNBDLKEG AACCPLMFDIE)
	{
		ACEGNBDLKEG aCEGNBDLKEG = new ACEGNBDLKEG(AACCPLMFDIE.PNGPLGHKFDI);
		aCEGNBDLKEG.BGKHIDKDGAC = AACCPLMFDIE.BGKHIDKDGAC;
		ACEGNBDLKEG aCEGNBDLKEG2 = aCEGNBDLKEG;
		HOMEODNDLLA(AACCPLMFDIE, aCEGNBDLKEG2);
		return aCEGNBDLKEG2;
	}

	public static ENIPPOEKJPA BNKOCCCOFMO(this ENIPPOEKJPA AACCPLMFDIE)
	{
		ENIPPOEKJPA eNIPPOEKJPA = new ENIPPOEKJPA(AACCPLMFDIE.PNGPLGHKFDI);
		eNIPPOEKJPA.ODLHFMOPCHL = AACCPLMFDIE.ODLHFMOPCHL;
		eNIPPOEKJPA.AMFCENFNAJJ = AACCPLMFDIE.AMFCENFNAJJ;
		eNIPPOEKJPA.CNLILOEEBOJ = AACCPLMFDIE.CNLILOEEBOJ;
		return eNIPPOEKJPA;
	}

	public static KBLNEHAAAJK BNKOCCCOFMO(this KBLNEHAAAJK AACCPLMFDIE)
	{
		KBLNEHAAAJK kBLNEHAAAJK = new KBLNEHAAAJK(AACCPLMFDIE.PNGPLGHKFDI);
		HOMEODNDLLA(AACCPLMFDIE, kBLNEHAAAJK);
		return kBLNEHAAAJK;
	}

	public static MGCLDKAFCIB OHGDCEOOGEI(this MGCLDKAFCIB AACCPLMFDIE, bool HMGOODNADED = true)
	{
		return AACCPLMFDIE.COCIGNBKMNH(AACCPLMFDIE.PNGPLGHKFDI, AACCPLMFDIE.HIPOEPNPBPO as FCPKAKFLFEG, HMGOODNADED);
	}

	public static MGCLDKAFCIB BNKOCCCOFMO(this MGCLDKAFCIB AACCPLMFDIE)
	{
		MGCLDKAFCIB mGCLDKAFCIB = new MGCLDKAFCIB(AACCPLMFDIE.PNGPLGHKFDI);
		mGCLDKAFCIB.GPGDCCMECGF = AACCPLMFDIE.GPGDCCMECGF;
		mGCLDKAFCIB.HJMBDGKAOBP = AACCPLMFDIE.HJMBDGKAOBP;
		mGCLDKAFCIB.BCIHLCMFAEK = AACCPLMFDIE.BCIHLCMFAEK;
		mGCLDKAFCIB.MNIMEAMHNMI = AACCPLMFDIE.MNIMEAMHNMI;
		mGCLDKAFCIB.HMGOODNADED = AACCPLMFDIE.HMGOODNADED;
		mGCLDKAFCIB.MJCBDBIDMGF = AACCPLMFDIE.MJCBDBIDMGF;
		mGCLDKAFCIB.HIPOEPNPBPO = AACCPLMFDIE.HIPOEPNPBPO;
		mGCLDKAFCIB.MBHOIJFNKPO = AACCPLMFDIE.MBHOIJFNKPO;
		mGCLDKAFCIB.JGEIMMGNNFN = AACCPLMFDIE.JGEIMMGNNFN;
		mGCLDKAFCIB.ECJFPIOKKGN = AACCPLMFDIE.ECJFPIOKKGN;
		mGCLDKAFCIB.MJCEICPLJKP = AACCPLMFDIE.MJCEICPLJKP;
		mGCLDKAFCIB.LBNLLJNGJHP = AACCPLMFDIE.LBNLLJNGJHP;
		mGCLDKAFCIB.HLMKOMNGAMA = AACCPLMFDIE.HLMKOMNGAMA;
		mGCLDKAFCIB.AMPGPNLBJKC = AACCPLMFDIE.AMPGPNLBJKC;
		mGCLDKAFCIB.INFIMLAEHGL = AACCPLMFDIE.INFIMLAEHGL;
		mGCLDKAFCIB.GGHFMMGLANA = AACCPLMFDIE.GGHFMMGLANA;
		mGCLDKAFCIB.HDCMGPKKCEJ = AACCPLMFDIE.HDCMGPKKCEJ;
		mGCLDKAFCIB.GCNJNMPFNJC = AACCPLMFDIE.GCNJNMPFNJC;
		mGCLDKAFCIB.NDIFGLEBDLE = AACCPLMFDIE.NDIFGLEBDLE.Clone() as float[];
		MGCLDKAFCIB mGCLDKAFCIB2 = mGCLDKAFCIB;
		if (AACCPLMFDIE.EJEBCFHLAFF != null)
		{
			mGCLDKAFCIB2.EJEBCFHLAFF = AACCPLMFDIE.EJEBCFHLAFF;
		}
		else
		{
			HOMEODNDLLA(AACCPLMFDIE, mGCLDKAFCIB2);
			mGCLDKAFCIB2.OJKLIMMHOEH = AACCPLMFDIE.OJKLIMMHOEH.Clone() as float[];
			mGCLDKAFCIB2.NPDGLMEOKIO = AACCPLMFDIE.NPDGLMEOKIO.Clone() as int[];
			mGCLDKAFCIB2.DCPJBPJHJJK = AACCPLMFDIE.DCPJBPJHJJK;
			mGCLDKAFCIB2.PEMDNNKKDPG = ((AACCPLMFDIE.PEMDNNKKDPG != null) ? (AACCPLMFDIE.PEMDNNKKDPG.Clone() as int[]) : null);
			mGCLDKAFCIB2.EMFKAPJMDCC = AACCPLMFDIE.EMFKAPJMDCC;
			mGCLDKAFCIB2.FHAMOHDEGMK = AACCPLMFDIE.FHAMOHDEGMK;
		}
		return mGCLDKAFCIB2;
	}

	public static GMLCOKFENFN BNKOCCCOFMO(this GMLCOKFENFN AACCPLMFDIE)
	{
		GMLCOKFENFN gMLCOKFENFN = new GMLCOKFENFN(AACCPLMFDIE.PNGPLGHKFDI);
		gMLCOKFENFN.BFGGGEPJGOI = AACCPLMFDIE.BFGGGEPJGOI.Clone() as float[];
		gMLCOKFENFN.MBEOPLHLANP = AACCPLMFDIE.MBEOPLHLANP;
		gMLCOKFENFN.IKJCHJGJKGH = AACCPLMFDIE.IKJCHJGJKGH;
		GMLCOKFENFN gMLCOKFENFN2 = gMLCOKFENFN;
		HOMEODNDLLA(AACCPLMFDIE, gMLCOKFENFN2);
		return gMLCOKFENFN2;
	}

	private static void HOMEODNDLLA(LJPHFIKMDHN ENICBMKPJJK, LJPHFIKMDHN EAHMJBBOJKC)
	{
		EAHMJBBOJKC.MCCBDCEJDBC = ENICBMKPJJK.MCCBDCEJDBC;
		if (ENICBMKPJJK.LIKIOBHLHHF != null)
		{
			EAHMJBBOJKC.LIKIOBHLHHF = ENICBMKPJJK.LIKIOBHLHHF.Clone() as int[];
		}
		if (ENICBMKPJJK.FHBFCAEGPOH != null)
		{
			EAHMJBBOJKC.FHBFCAEGPOH = ENICBMKPJJK.FHBFCAEGPOH.Clone() as float[];
		}
	}

	public static MGCLDKAFCIB COCIGNBKMNH(this MGCLDKAFCIB AACCPLMFDIE, string IAHKDJIGEDH, FCPKAKFLFEG PMKKIEFBKAK, bool HMGOODNADED = true)
	{
		if (PMKKIEFBKAK == null)
		{
			throw new ArgumentNullException("region");
		}
		if (AACCPLMFDIE.EJEBCFHLAFF != null)
		{
			AACCPLMFDIE = AACCPLMFDIE.EJEBCFHLAFF;
		}
		MGCLDKAFCIB mGCLDKAFCIB = new MGCLDKAFCIB(IAHKDJIGEDH);
		mGCLDKAFCIB.HJJKKGEMFOM(PMKKIEFBKAK, false);
		mGCLDKAFCIB.MJCBDBIDMGF = IAHKDJIGEDH;
		mGCLDKAFCIB.GPGDCCMECGF = 1f;
		mGCLDKAFCIB.HJMBDGKAOBP = 1f;
		mGCLDKAFCIB.BCIHLCMFAEK = 1f;
		mGCLDKAFCIB.MNIMEAMHNMI = 1f;
		mGCLDKAFCIB.HMGOODNADED = HMGOODNADED;
		mGCLDKAFCIB.EJEBCFHLAFF = AACCPLMFDIE;
		mGCLDKAFCIB.IFAIOMLBIAD();
		return mGCLDKAFCIB;
	}

	public static MGCLDKAFCIB COCIGNBKMNH(this MGCLDKAFCIB AACCPLMFDIE, Sprite MJOJAOIHCIO, Shader BLCFLFHNKFG, bool HMGOODNADED = true, Material DMOJCHBFADP = null)
	{
		Material material = new Material(BLCFLFHNKFG);
		if (DMOJCHBFADP != null)
		{
			material.CopyPropertiesFromMaterial(DMOJCHBFADP);
			material.shaderKeywords = DMOJCHBFADP.shaderKeywords;
		}
		return AACCPLMFDIE.COCIGNBKMNH(MJOJAOIHCIO.name, MJOJAOIHCIO.PKGKHHABACE(), HMGOODNADED);
	}

	public static MGCLDKAFCIB COCIGNBKMNH(this MGCLDKAFCIB AACCPLMFDIE, Sprite MJOJAOIHCIO, Material DMOJCHBFADP, bool HMGOODNADED = true)
	{
		return AACCPLMFDIE.COCIGNBKMNH(MJOJAOIHCIO, DMOJCHBFADP.shader, HMGOODNADED, DMOJCHBFADP);
	}

	public static OAMNGFLKEFI HLGNEIDODHP(this OAMNGFLKEFI AACCPLMFDIE, Sprite MJOJAOIHCIO, Material NJIFHGPKPFH, bool KNMFPNBEHMH = true, bool NEELPGFBPKJ = true, bool EOMOLKCMLEF = false)
	{
		FCPKAKFLFEG mHPAIBOCCBP = ((!KNMFPNBEHMH) ? MJOJAOIHCIO.PKGKHHABACE() : MJOJAOIHCIO.JOEMHKMEGJF(NJIFHGPKPFH));
		return AACCPLMFDIE.HLGNEIDODHP(mHPAIBOCCBP, NEELPGFBPKJ, EOMOLKCMLEF, 1f / MJOJAOIHCIO.pixelsPerUnit);
	}

	public static OAMNGFLKEFI HLGNEIDODHP(this OAMNGFLKEFI AACCPLMFDIE, FCPKAKFLFEG MHPAIBOCCBP, bool NEELPGFBPKJ = true, bool EOMOLKCMLEF = false, float HJLOCAEAFMJ = 0.01f)
	{
		MKEALIMJCFJ mKEALIMJCFJ = AACCPLMFDIE as MKEALIMJCFJ;
		if (mKEALIMJCFJ != null)
		{
			MKEALIMJCFJ mKEALIMJCFJ2 = mKEALIMJCFJ.BNKOCCCOFMO();
			mKEALIMJCFJ2.HJJKKGEMFOM(MHPAIBOCCBP, false);
			if (!EOMOLKCMLEF)
			{
				mKEALIMJCFJ2.HHHMOGOKFHF = (float)MHPAIBOCCBP.HHHMOGOKFHF * HJLOCAEAFMJ;
				mKEALIMJCFJ2.JKNPBEOPMPK = (float)MHPAIBOCCBP.JKNPBEOPMPK * HJLOCAEAFMJ;
			}
			mKEALIMJCFJ2.MNIMJDFOILP();
			return mKEALIMJCFJ2;
		}
		MGCLDKAFCIB mGCLDKAFCIB = AACCPLMFDIE as MGCLDKAFCIB;
		if (mGCLDKAFCIB != null)
		{
			MGCLDKAFCIB mGCLDKAFCIB2 = ((!NEELPGFBPKJ) ? mGCLDKAFCIB.BNKOCCCOFMO() : mGCLDKAFCIB.OHGDCEOOGEI(NEELPGFBPKJ));
			mGCLDKAFCIB2.HJJKKGEMFOM(MHPAIBOCCBP);
			return mGCLDKAFCIB2;
		}
		return AACCPLMFDIE.BNKOCCCOFMO(true);
	}
}
