using System;
using Org.BouncyCastle.Crypto;
using Org.BouncyCastle.Math;

public class BHLOIMJIIIK
{
	private readonly DOGLMBOAGOG NGCBGBKJCGB;

	private readonly GOHBAGFNIAI KFBFENOJNHL;

	private readonly PHFBFDEAHMD LGMMFPHDIMH;

	private readonly EIFKCBHBLFB IEDPBFAFGGJ;

	private readonly byte[] PHJBCPDPIHJ;

	private bool MAEALKEJALK;

	private IGMAJHKIIPK PDACJCDCBDB;

	private IGMAJHKIIPK FBBHGDODPHK;

	private NNAHJJGNIIC BOFHHECPKNF;

	public BHLOIMJIIIK(DOGLMBOAGOG NGCBGBKJCGB, GOHBAGFNIAI KFBFENOJNHL, PHFBFDEAHMD LGMMFPHDIMH)
	{
		this.NGCBGBKJCGB = NGCBGBKJCGB;
		this.KFBFENOJNHL = KFBFENOJNHL;
		this.LGMMFPHDIMH = LGMMFPHDIMH;
		PHJBCPDPIHJ = new byte[LGMMFPHDIMH.BKGLOJPPBIG()];
	}

	public BHLOIMJIIIK(DOGLMBOAGOG NGCBGBKJCGB, GOHBAGFNIAI KFBFENOJNHL, PHFBFDEAHMD LGMMFPHDIMH, EIFKCBHBLFB IEDPBFAFGGJ)
	{
		this.NGCBGBKJCGB = NGCBGBKJCGB;
		this.KFBFENOJNHL = KFBFENOJNHL;
		this.LGMMFPHDIMH = LGMMFPHDIMH;
		PHJBCPDPIHJ = new byte[LGMMFPHDIMH.BKGLOJPPBIG()];
		this.IEDPBFAFGGJ = IEDPBFAFGGJ;
	}

	public virtual void DIOELAHNLKJ(bool MAEALKEJALK, IGMAJHKIIPK NNAIDJJLDCB, IGMAJHKIIPK FKMMKIMHHAB, IGMAJHKIIPK MBJGFKDEEJA)
	{
		this.MAEALKEJALK = MAEALKEJALK;
		PDACJCDCBDB = NNAIDJJLDCB;
		FBBHGDODPHK = FKMMKIMHHAB;
		BOFHHECPKNF = (NNAHJJGNIIC)MBJGFKDEEJA;
	}

	private byte[] GFKALHGNIOJ(byte[] GPNOGEOOEJJ, int ELICNEDIBGB, int DBGBBFPPDCE, byte[] IGNEOOOFEMO)
	{
		byte[] array = null;
		JEMNCGMEABF jEMNCGMEABF = null;
		FHDKFGOIPDL fHDKFGOIPDL = new FHDKFGOIPDL(IGNEOOOFEMO, BOFHHECPKNF.PBCNALIDMMF());
		int num = BOFHHECPKNF.KGCAHBEHKIH;
		KFBFENOJNHL.DIOELAHNLKJ(fHDKFGOIPDL);
		if (DBGBBFPPDCE < LGMMFPHDIMH.BKGLOJPPBIG())
		{
			throw new InvalidCipherTextException("Length of input must be greater than the MAC");
		}
		DBGBBFPPDCE -= LGMMFPHDIMH.BKGLOJPPBIG();
		if (IEDPBFAFGGJ == null)
		{
			byte[] array2 = LMINNBIJIEH(fHDKFGOIPDL, DBGBBFPPDCE + num / 8);
			array = new byte[DBGBBFPPDCE];
			for (int i = 0; i != DBGBBFPPDCE; i++)
			{
				array[i] = (byte)(GPNOGEOOEJJ[ELICNEDIBGB + i] ^ array2[i]);
			}
			jEMNCGMEABF = new JEMNCGMEABF(array2, DBGBBFPPDCE, num / 8);
		}
		else
		{
			int num2 = ((KMCNKHJCJHP)BOFHHECPKNF).JJPIAOFDOCL;
			byte[] iKNCPEPOKGJ = LMINNBIJIEH(fHDKFGOIPDL, num2 / 8 + num / 8);
			IEDPBFAFGGJ.DIOELAHNLKJ(false, new JEMNCGMEABF(iKNCPEPOKGJ, 0, num2 / 8));
			array = IEDPBFAFGGJ.LCNOFBMOHHM(GPNOGEOOEJJ, ELICNEDIBGB, DBGBBFPPDCE);
			jEMNCGMEABF = new JEMNCGMEABF(iKNCPEPOKGJ, num2 / 8, num / 8);
		}
		byte[] array3 = BOFHHECPKNF.NNPDMELDBKK();
		LGMMFPHDIMH.DIOELAHNLKJ(jEMNCGMEABF);
		LGMMFPHDIMH.GONEEEFEDGF(GPNOGEOOEJJ, ELICNEDIBGB, DBGBBFPPDCE);
		LGMMFPHDIMH.GONEEEFEDGF(array3, 0, array3.Length);
		LGMMFPHDIMH.LCNOFBMOHHM(PHJBCPDPIHJ, 0);
		ELICNEDIBGB += DBGBBFPPDCE;
		byte[] mNIMEAMHNMI = NOGCEBKPPJE.EHLHBAMJLNI(GPNOGEOOEJJ, ELICNEDIBGB, ELICNEDIBGB + PHJBCPDPIHJ.Length);
		if (!NOGCEBKPPJE.PBBFCJBKJEN(mNIMEAMHNMI, PHJBCPDPIHJ))
		{
			throw new InvalidCipherTextException("Invalid MAC.");
		}
		return array;
	}

	private byte[] HDOLNBOHAJA(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int DBGBBFPPDCE, byte[] IGNEOOOFEMO)
	{
		byte[] array = null;
		JEMNCGMEABF jEMNCGMEABF = null;
		FHDKFGOIPDL eAABLGDBILH = new FHDKFGOIPDL(IGNEOOOFEMO, BOFHHECPKNF.PBCNALIDMMF());
		int num = 0;
		int num2 = BOFHHECPKNF.KGCAHBEHKIH;
		if (IEDPBFAFGGJ == null)
		{
			byte[] array2 = LMINNBIJIEH(eAABLGDBILH, DBGBBFPPDCE + num2 / 8);
			array = new byte[DBGBBFPPDCE + LGMMFPHDIMH.BKGLOJPPBIG()];
			num = DBGBBFPPDCE;
			for (int i = 0; i != DBGBBFPPDCE; i++)
			{
				array[i] = (byte)(MOPCLEEGDFB[ELICNEDIBGB + i] ^ array2[i]);
			}
			jEMNCGMEABF = new JEMNCGMEABF(array2, DBGBBFPPDCE, num2 / 8);
		}
		else
		{
			int num3 = ((KMCNKHJCJHP)BOFHHECPKNF).JJPIAOFDOCL;
			byte[] iKNCPEPOKGJ = LMINNBIJIEH(eAABLGDBILH, num3 / 8 + num2 / 8);
			IEDPBFAFGGJ.DIOELAHNLKJ(true, new JEMNCGMEABF(iKNCPEPOKGJ, 0, num3 / 8));
			num = IEDPBFAFGGJ.ACLDAECDPFN(DBGBBFPPDCE);
			byte[] array3 = new byte[num];
			int num4 = IEDPBFAFGGJ.POCAGALIPAI(MOPCLEEGDFB, ELICNEDIBGB, DBGBBFPPDCE, array3, 0);
			num4 += IEDPBFAFGGJ.LCNOFBMOHHM(array3, num4);
			array = new byte[num4 + LGMMFPHDIMH.BKGLOJPPBIG()];
			num = num4;
			Array.Copy(array3, 0, array, 0, num4);
			jEMNCGMEABF = new JEMNCGMEABF(iKNCPEPOKGJ, num3 / 8, num2 / 8);
		}
		byte[] array4 = BOFHHECPKNF.NNPDMELDBKK();
		LGMMFPHDIMH.DIOELAHNLKJ(jEMNCGMEABF);
		LGMMFPHDIMH.GONEEEFEDGF(array, 0, num);
		LGMMFPHDIMH.GONEEEFEDGF(array4, 0, array4.Length);
		LGMMFPHDIMH.LCNOFBMOHHM(array, num);
		return array;
	}

	private byte[] LMINNBIJIEH(FHDKFGOIPDL EAABLGDBILH, int EOFAGACBNFP)
	{
		byte[] array = new byte[EOFAGACBNFP];
		KFBFENOJNHL.DIOELAHNLKJ(EAABLGDBILH);
		KFBFENOJNHL.IOIODJEBIMJ(array, 0, array.Length);
		return array;
	}

	public virtual byte[] DPACJDFHLKB(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int DBGBBFPPDCE)
	{
		NGCBGBKJCGB.DIOELAHNLKJ(PDACJCDCBDB);
		BigInteger iDHLPOFDLKJ = NGCBGBKJCGB.CFEKCGNAKCD(FBBHGDODPHK);
		byte[] array = ODBELJAHGIG.HOGKINKACAF(NGCBGBKJCGB.BGGKNJOAMKN(), iDHLPOFDLKJ);
		try
		{
			return (!MAEALKEJALK) ? GFKALHGNIOJ(MOPCLEEGDFB, ELICNEDIBGB, DBGBBFPPDCE, array) : HDOLNBOHAJA(MOPCLEEGDFB, ELICNEDIBGB, DBGBBFPPDCE, array);
		}
		finally
		{
			Array.Clear(array, 0, array.Length);
		}
	}
}
