using System.Collections;

internal class BJMIIIEBPNP
{
	private static readonly OIONBALGCNP COABPJMBBDI;

	private static readonly IDictionary NCLCMMGJEBI;

	private static readonly IDictionary ANOKLIOALNN;

	private static readonly LKBPEOBFKMJ NENOIAHBILD;

	static BJMIIIEBPNP()
	{
		COABPJMBBDI = HLAKNNHGPNP.GABGKBAKHDP;
		NCLCMMGJEBI = LHFGHNFJIKM.JBEOCJEMGCE();
		ANOKLIOALNN = LHFGHNFJIKM.JBEOCJEMGCE();
		NENOIAHBILD = new DMAOKHPCPIA();
		NCLCMMGJEBI.Add("MD2WITHRSAENCRYPTION", NLPPJKFFBON.IOAJGDJJEOD);
		NCLCMMGJEBI.Add("MD2WITHRSA", NLPPJKFFBON.IOAJGDJJEOD);
		NCLCMMGJEBI.Add("MD5WITHRSAENCRYPTION", NLPPJKFFBON.PMNPHGFIJKB);
		NCLCMMGJEBI.Add("MD5WITHRSA", NLPPJKFFBON.PMNPHGFIJKB);
		NCLCMMGJEBI.Add("SHA1WITHRSAENCRYPTION", NLPPJKFFBON.HHJOGJKDABE);
		NCLCMMGJEBI.Add("SHA1WITHRSA", NLPPJKFFBON.HHJOGJKDABE);
		NCLCMMGJEBI.Add("SHA224WITHRSAENCRYPTION", NLPPJKFFBON.PJFNBLDALME);
		NCLCMMGJEBI.Add("SHA224WITHRSA", NLPPJKFFBON.PJFNBLDALME);
		NCLCMMGJEBI.Add("SHA256WITHRSAENCRYPTION", NLPPJKFFBON.OAIONFDMHJG);
		NCLCMMGJEBI.Add("SHA256WITHRSA", NLPPJKFFBON.OAIONFDMHJG);
		NCLCMMGJEBI.Add("SHA384WITHRSAENCRYPTION", NLPPJKFFBON.DCHKOPOOPDP);
		NCLCMMGJEBI.Add("SHA384WITHRSA", NLPPJKFFBON.DCHKOPOOPDP);
		NCLCMMGJEBI.Add("SHA512WITHRSAENCRYPTION", NLPPJKFFBON.ACLCPAOCHDL);
		NCLCMMGJEBI.Add("SHA512WITHRSA", NLPPJKFFBON.ACLCPAOCHDL);
		NCLCMMGJEBI.Add("SHA1WITHRSAANDMGF1", NLPPJKFFBON.NLKEIILLMGF);
		NCLCMMGJEBI.Add("SHA224WITHRSAANDMGF1", NLPPJKFFBON.NLKEIILLMGF);
		NCLCMMGJEBI.Add("SHA256WITHRSAANDMGF1", NLPPJKFFBON.NLKEIILLMGF);
		NCLCMMGJEBI.Add("SHA384WITHRSAANDMGF1", NLPPJKFFBON.NLKEIILLMGF);
		NCLCMMGJEBI.Add("SHA512WITHRSAANDMGF1", NLPPJKFFBON.NLKEIILLMGF);
		NCLCMMGJEBI.Add("RIPEMD160WITHRSAENCRYPTION", HECJIGBIHCA.FPONNNCJMMA);
		NCLCMMGJEBI.Add("RIPEMD160WITHRSA", HECJIGBIHCA.FPONNNCJMMA);
		NCLCMMGJEBI.Add("RIPEMD128WITHRSAENCRYPTION", HECJIGBIHCA.DJLLMMGNGHO);
		NCLCMMGJEBI.Add("RIPEMD128WITHRSA", HECJIGBIHCA.DJLLMMGNGHO);
		NCLCMMGJEBI.Add("RIPEMD256WITHRSAENCRYPTION", HECJIGBIHCA.HOGNOMEIEPE);
		NCLCMMGJEBI.Add("RIPEMD256WITHRSA", HECJIGBIHCA.HOGNOMEIEPE);
		NCLCMMGJEBI.Add("SHA1WITHDSA", JJFMEBLGJEP.CGJLNBCIAHE);
		NCLCMMGJEBI.Add("DSAWITHSHA1", JJFMEBLGJEP.CGJLNBCIAHE);
		NCLCMMGJEBI.Add("SHA224WITHDSA", HHKLFIFJNFO.FIDJHIJHIJB);
		NCLCMMGJEBI.Add("SHA256WITHDSA", HHKLFIFJNFO.GHJPDHPHJCG);
		NCLCMMGJEBI.Add("SHA384WITHDSA", HHKLFIFJNFO.DFGLNGHMBBM);
		NCLCMMGJEBI.Add("SHA512WITHDSA", HHKLFIFJNFO.LAGABLOADKP);
		NCLCMMGJEBI.Add("SHA1WITHECDSA", JJFMEBLGJEP.MKGMLCOCCPL);
		NCLCMMGJEBI.Add("ECDSAWITHSHA1", JJFMEBLGJEP.MKGMLCOCCPL);
		NCLCMMGJEBI.Add("SHA224WITHECDSA", JJFMEBLGJEP.KICHODOIAMD);
		NCLCMMGJEBI.Add("SHA256WITHECDSA", JJFMEBLGJEP.EGLFGAJEAPJ);
		NCLCMMGJEBI.Add("SHA384WITHECDSA", JJFMEBLGJEP.AACDLNGKGGH);
		NCLCMMGJEBI.Add("SHA512WITHECDSA", JJFMEBLGJEP.CGLPLAKDEOP);
		NCLCMMGJEBI.Add("GOST3411WITHGOST3410", FNOHIHFMAMN.NPBGKJFALDM);
		NCLCMMGJEBI.Add("GOST3411WITHGOST3410-94", FNOHIHFMAMN.NPBGKJFALDM);
		NCLCMMGJEBI.Add("GOST3411WITHECGOST3410", FNOHIHFMAMN.LEOPAFAFMPJ);
		NCLCMMGJEBI.Add("GOST3411WITHECGOST3410-2001", FNOHIHFMAMN.LEOPAFAFMPJ);
		NCLCMMGJEBI.Add("GOST3411WITHGOST3410-2001", FNOHIHFMAMN.LEOPAFAFMPJ);
		NENOIAHBILD.JEACJNAKLDJ(JJFMEBLGJEP.MKGMLCOCCPL);
		NENOIAHBILD.JEACJNAKLDJ(JJFMEBLGJEP.KICHODOIAMD);
		NENOIAHBILD.JEACJNAKLDJ(JJFMEBLGJEP.EGLFGAJEAPJ);
		NENOIAHBILD.JEACJNAKLDJ(JJFMEBLGJEP.AACDLNGKGGH);
		NENOIAHBILD.JEACJNAKLDJ(JJFMEBLGJEP.CGLPLAKDEOP);
		NENOIAHBILD.JEACJNAKLDJ(JJFMEBLGJEP.CGJLNBCIAHE);
		NENOIAHBILD.JEACJNAKLDJ(HHKLFIFJNFO.FIDJHIJHIJB);
		NENOIAHBILD.JEACJNAKLDJ(HHKLFIFJNFO.GHJPDHPHJCG);
		NENOIAHBILD.JEACJNAKLDJ(HHKLFIFJNFO.DFGLNGHMBBM);
		NENOIAHBILD.JEACJNAKLDJ(HHKLFIFJNFO.LAGABLOADKP);
		NENOIAHBILD.JEACJNAKLDJ(FNOHIHFMAMN.NPBGKJFALDM);
		NENOIAHBILD.JEACJNAKLDJ(FNOHIHFMAMN.LEOPAFAFMPJ);
		COCECKPDIKC hCJCLCALJKC = new COCECKPDIKC(POLLKACILDK.MEBPJCLMCDA, HLAKNNHGPNP.GABGKBAKHDP);
		ANOKLIOALNN.Add("SHA1WITHRSAANDMGF1", LOGGALEPNGI(hCJCLCALJKC, 20));
		COCECKPDIKC hCJCLCALJKC2 = new COCECKPDIKC(HHKLFIFJNFO.NGAKIGLLNMJ, HLAKNNHGPNP.GABGKBAKHDP);
		ANOKLIOALNN.Add("SHA224WITHRSAANDMGF1", LOGGALEPNGI(hCJCLCALJKC2, 28));
		COCECKPDIKC hCJCLCALJKC3 = new COCECKPDIKC(HHKLFIFJNFO.OKLEKJJIGME, HLAKNNHGPNP.GABGKBAKHDP);
		ANOKLIOALNN.Add("SHA256WITHRSAANDMGF1", LOGGALEPNGI(hCJCLCALJKC3, 32));
		COCECKPDIKC hCJCLCALJKC4 = new COCECKPDIKC(HHKLFIFJNFO.EJIHFCHFMLO, HLAKNNHGPNP.GABGKBAKHDP);
		ANOKLIOALNN.Add("SHA384WITHRSAANDMGF1", LOGGALEPNGI(hCJCLCALJKC4, 48));
		COCECKPDIKC hCJCLCALJKC5 = new COCECKPDIKC(HHKLFIFJNFO.HBLLHCKNOKB, HLAKNNHGPNP.GABGKBAKHDP);
		ANOKLIOALNN.Add("SHA512WITHRSAANDMGF1", LOGGALEPNGI(hCJCLCALJKC5, 64));
	}

	private static string OMINPDECNNB(KLKJHFKJLEM FANIKGJBMBA)
	{
		if (NLPPJKFFBON.HCEBKEDMKGI.Equals(FANIKGJBMBA))
		{
			return "MD5";
		}
		if (POLLKACILDK.MEBPJCLMCDA.Equals(FANIKGJBMBA))
		{
			return "SHA1";
		}
		if (HHKLFIFJNFO.NGAKIGLLNMJ.Equals(FANIKGJBMBA))
		{
			return "SHA224";
		}
		if (HHKLFIFJNFO.OKLEKJJIGME.Equals(FANIKGJBMBA))
		{
			return "SHA256";
		}
		if (HHKLFIFJNFO.EJIHFCHFMLO.Equals(FANIKGJBMBA))
		{
			return "SHA384";
		}
		if (HHKLFIFJNFO.HBLLHCKNOKB.Equals(FANIKGJBMBA))
		{
			return "SHA512";
		}
		if (HECJIGBIHCA.KCPONBGBCIG.Equals(FANIKGJBMBA))
		{
			return "RIPEMD128";
		}
		if (HECJIGBIHCA.LNJCFFFDBMO.Equals(FANIKGJBMBA))
		{
			return "RIPEMD160";
		}
		if (HECJIGBIHCA.AEIDPDDECDO.Equals(FANIKGJBMBA))
		{
			return "RIPEMD256";
		}
		if (FNOHIHFMAMN.EPDBPJHHJIP.Equals(FANIKGJBMBA))
		{
			return "GOST3411";
		}
		return FANIKGJBMBA.EEFMIHDPJPG;
	}

	internal static string PPPAACNJBIC(COCECKPDIKC COJGMAHIJHF)
	{
		LNKPCJLANAO lNKPCJLANAO = COJGMAHIJHF.KPJHHAAOFOH;
		if (lNKPCJLANAO != null && !COABPJMBBDI.Equals(lNKPCJLANAO))
		{
			if (COJGMAHIJHF.GOFDFGBGLFC.Equals(NLPPJKFFBON.NLKEIILLMGF))
			{
				LHCALAMFAOK lHCALAMFAOK = LHCALAMFAOK.BJLJCGFMFOO(lNKPCJLANAO);
				return OMINPDECNNB(lHCALAMFAOK.FDOJDCLKKIP.GOFDFGBGLFC) + "withRSAandMGF1";
			}
			if (COJGMAHIJHF.GOFDFGBGLFC.Equals(JJFMEBLGJEP.GOEPMLIFLFH))
			{
				ALLINHNNNJN aLLINHNNNJN = ALLINHNNNJN.BJLJCGFMFOO(lNKPCJLANAO);
				return OMINPDECNNB((KLKJHFKJLEM)aLLINHNNNJN.ECNCPJGHBIG(0)) + "withECDSA";
			}
		}
		return COJGMAHIJHF.GOFDFGBGLFC.EEFMIHDPJPG;
	}

	private static LHCALAMFAOK LOGGALEPNGI(COCECKPDIKC HCJCLCALJKC, int IIGHBBKIIDH)
	{
		return new LHCALAMFAOK(HCJCLCALJKC, new COCECKPDIKC(NLPPJKFFBON.NKBNJIMIGJP, HCJCLCALJKC), new GLFDIPNOLKN(IIGHBBKIIDH), new GLFDIPNOLKN(1));
	}

	internal static KLKJHFKJLEM ANENONPLLFP(string BFLMFCKDKDM)
	{
		BFLMFCKDKDM = LHFGHNFJIKM.OGLCLCODHJI(BFLMFCKDKDM);
		if (NCLCMMGJEBI.Contains(BFLMFCKDKDM))
		{
			return (KLKJHFKJLEM)NCLCMMGJEBI[BFLMFCKDKDM];
		}
		return new KLKJHFKJLEM(BFLMFCKDKDM);
	}

	internal static COCECKPDIKC KCFCOMCMHOE(KLKJHFKJLEM PGJDDDOKOJO, string BFLMFCKDKDM)
	{
		if (NENOIAHBILD.KMDACNACKII(PGJDDDOKOJO))
		{
			return new COCECKPDIKC(PGJDDDOKOJO);
		}
		BFLMFCKDKDM = LHFGHNFJIKM.OGLCLCODHJI(BFLMFCKDKDM);
		if (ANOKLIOALNN.Contains(BFLMFCKDKDM))
		{
			return new COCECKPDIKC(PGJDDDOKOJO, (LNKPCJLANAO)ANOKLIOALNN[BFLMFCKDKDM]);
		}
		return new COCECKPDIKC(PGJDDDOKOJO, HLAKNNHGPNP.GABGKBAKHDP);
	}

	internal static IEnumerable DCELAAHMIKB()
	{
		return new FLJIAKGGJBO(NCLCMMGJEBI.Keys);
	}
}
