using Org.BouncyCastle.Math;

public class BMIMOOLAJAL : HAEJCOAFOIJ
{
	private const int ADCMMDCAFID = 4;

	protected readonly BigInteger DDLFDFEOHAH;

	protected readonly BigInteger MMJCPBFANCC;

	protected readonly KGHPPAOAMAH IAALHPOGFAN;

	public virtual BigInteger FNPELDEHJKL
	{
		get
		{
			return DDLFDFEOHAH;
		}
	}

	public override JGAFKLGGBGF EFOLNCNGADB
	{
		get
		{
			return IAALHPOGFAN;
		}
	}

	public override int PJNLBAHOKGC
	{
		get
		{
			return DDLFDFEOHAH.BitLength;
		}
	}

	public BMIMOOLAJAL(BigInteger OKDPJHOEPBJ, BigInteger MNIMEAMHNMI, BigInteger BCIHLCMFAEK)
		: this(OKDPJHOEPBJ, MNIMEAMHNMI, BCIHLCMFAEK, null, null)
	{
	}

	public BMIMOOLAJAL(BigInteger OKDPJHOEPBJ, BigInteger MNIMEAMHNMI, BigInteger BCIHLCMFAEK, BigInteger CMAJLIAELDP, BigInteger GHOBJLLGPOE)
		: base(OKDPJHOEPBJ)
	{
		DDLFDFEOHAH = OKDPJHOEPBJ;
		MMJCPBFANCC = NJEIAFKPJFE.GGBBFNDKLPA(OKDPJHOEPBJ);
		IAALHPOGFAN = new KGHPPAOAMAH(this, null, null);
		CFJANGMBPML = HFENNGHNFLF(MNIMEAMHNMI);
		MPDGCILOEML = HFENNGHNFLF(BCIHLCMFAEK);
		NNGLKCDBIBE = CMAJLIAELDP;
		LDKJJAOPAAP = GHOBJLLGPOE;
		NHKGIJJFPEK = 4;
	}

	protected BMIMOOLAJAL(BigInteger OKDPJHOEPBJ, BigInteger GPGDCCMECGF, KBINBLGGLNE MNIMEAMHNMI, KBINBLGGLNE BCIHLCMFAEK)
		: this(OKDPJHOEPBJ, GPGDCCMECGF, MNIMEAMHNMI, BCIHLCMFAEK, null, null)
	{
	}

	protected BMIMOOLAJAL(BigInteger OKDPJHOEPBJ, BigInteger GPGDCCMECGF, KBINBLGGLNE MNIMEAMHNMI, KBINBLGGLNE BCIHLCMFAEK, BigInteger CMAJLIAELDP, BigInteger GHOBJLLGPOE)
		: base(OKDPJHOEPBJ)
	{
		DDLFDFEOHAH = OKDPJHOEPBJ;
		MMJCPBFANCC = GPGDCCMECGF;
		IAALHPOGFAN = new KGHPPAOAMAH(this, null, null);
		CFJANGMBPML = MNIMEAMHNMI;
		MPDGCILOEML = BCIHLCMFAEK;
		NNGLKCDBIBE = CMAJLIAELDP;
		LDKJJAOPAAP = GHOBJLLGPOE;
		NHKGIJJFPEK = 4;
	}

	protected override BHPIABAGAPB LNLMICLEEPK()
	{
		return new BMIMOOLAJAL(DDLFDFEOHAH, MMJCPBFANCC, CFJANGMBPML, MPDGCILOEML, NNGLKCDBIBE, LDKJJAOPAAP);
	}

	public override bool ELIMDCKLHCJ(int FOOJPIGHMKH)
	{
		switch (FOOJPIGHMKH)
		{
		case 0:
		case 1:
		case 2:
		case 4:
			return true;
		default:
			return false;
		}
	}

	public override KBINBLGGLNE HFENNGHNFLF(BigInteger AMFCENFNAJJ)
	{
		return new NJEIAFKPJFE(DDLFDFEOHAH, MMJCPBFANCC, AMFCENFNAJJ);
	}

	protected internal override JGAFKLGGBGF IMOPAOHAOAN(KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
	{
		return new KGHPPAOAMAH(this, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG);
	}

	protected internal override JGAFKLGGBGF IMOPAOHAOAN(KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
	{
		return new KGHPPAOAMAH(this, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG);
	}

	public override JGAFKLGGBGF PHDNPDCNJJA(JGAFKLGGBGF HPHBDNBJPHB)
	{
		if (this != HPHBDNBJPHB.ECFGFKNLLGH && DHBHKHGFIKI == 2 && !HPHBDNBJPHB.IFCDKFANPBO)
		{
			switch (HPHBDNBJPHB.ECFGFKNLLGH.DHBHKHGFIKI)
			{
			case 2:
			case 3:
			case 4:
				return new KGHPPAOAMAH(this, HFENNGHNFLF(HPHBDNBJPHB.NBPANDNEJGI.DOJBPIFPALJ()), HFENNGHNFLF(HPHBDNBJPHB.FIJLKLCHMGH.DOJBPIFPALJ()), new KBINBLGGLNE[1] { HFENNGHNFLF(HPHBDNBJPHB.NOIPJPPAFOH(0).DOJBPIFPALJ()) }, HPHBDNBJPHB.BPGGHHMMCCB);
			}
		}
		return base.PHDNPDCNJJA(HPHBDNBJPHB);
	}
}
