using Spine;

public class BNODOKNKNDG : FPOBLOBNHGG
{
	public const int JMPDFJHAGOA = 5;

	private const int AMJGBMFEPLB = -5;

	private const int NHNFFOOGFEJ = -4;

	private const int FEMHKDMOBHO = -3;

	private const int BNHPCGEPBOJ = -2;

	private const int AIBPKDEANHF = -1;

	private const int HIDGDOABAAF = 1;

	private const int CCCOFDMBHCJ = 2;

	private const int NJCHCNKGNFB = 3;

	private const int JEGCEHHIKHO = 4;

	internal int JEJEFHFBHAJ;

	internal float[] ENBKHCNKHCC;

	public int CLOECPDNCOF
	{
		get
		{
			return JEJEFHFBHAJ;
		}
		set
		{
			JEJEFHFBHAJ = value;
		}
	}

	public float[] IKOJIGLMFNG
	{
		get
		{
			return ENBKHCNKHCC;
		}
		set
		{
			ENBKHCNKHCC = value;
		}
	}

	public override int ODHLEJHEBGD
	{
		get
		{
			return 167772160 + JEJEFHFBHAJ;
		}
	}

	public BNODOKNKNDG(int IJKENLLBMOJ)
		: base(IJKENLLBMOJ)
	{
		ENBKHCNKHCC = new float[IJKENLLBMOJ * 5];
	}

	public void BCEFHMIKFDC(int JHFDIBIBCPH, float HFLODNLEGFL, float OIBAIJIPGOM, float DHNKOEMONHP, float DLEIMBNDMOF, float OKJBKNEPKPN)
	{
		JHFDIBIBCPH *= 5;
		ENBKHCNKHCC[JHFDIBIBCPH] = HFLODNLEGFL;
		ENBKHCNKHCC[JHFDIBIBCPH + 1] = OIBAIJIPGOM;
		ENBKHCNKHCC[JHFDIBIBCPH + 2] = DHNKOEMONHP;
		ENBKHCNKHCC[JHFDIBIBCPH + 3] = DLEIMBNDMOF;
		ENBKHCNKHCC[JHFDIBIBCPH + 4] = OKJBKNEPKPN;
	}

	public override void FCHLOGCODOA(GCJKICAPOFL GDNININLMFD, float CGICCPOKJHB, float HFLODNLEGFL, ExposedList<DCBJAMHBAJB> ELMIMIMBNHP, float KBKMPEOMABI, BFCFMFBHBCH IFKBABBBDJM, ODPDBCNBOAK AJLDJAHHGOJ)
	{
		DLKMEPPLCGM dLKMEPPLCGM = GDNININLMFD.FOANDHFONAA.Items[JEJEFHFBHAJ];
		float[] eNBKHCNKHCC = ENBKHCNKHCC;
		if (HFLODNLEGFL < eNBKHCNKHCC[0])
		{
			MNNBOEPCJGP mBBPBGHKLJM = dLKMEPPLCGM.MBBPBGHKLJM;
			switch (IFKBABBBDJM)
			{
			case BFCFMFBHBCH.Setup:
				dLKMEPPLCGM.OIBAIJIPGOM = mBBPBGHKLJM.OIBAIJIPGOM;
				dLKMEPPLCGM.DHNKOEMONHP = mBBPBGHKLJM.DHNKOEMONHP;
				dLKMEPPLCGM.DLEIMBNDMOF = mBBPBGHKLJM.DLEIMBNDMOF;
				dLKMEPPLCGM.OKJBKNEPKPN = mBBPBGHKLJM.OKJBKNEPKPN;
				break;
			case BFCFMFBHBCH.Current:
				dLKMEPPLCGM.OIBAIJIPGOM += (mBBPBGHKLJM.OIBAIJIPGOM - dLKMEPPLCGM.OIBAIJIPGOM) * KBKMPEOMABI;
				dLKMEPPLCGM.DHNKOEMONHP += (mBBPBGHKLJM.DHNKOEMONHP - dLKMEPPLCGM.DHNKOEMONHP) * KBKMPEOMABI;
				dLKMEPPLCGM.DLEIMBNDMOF += (mBBPBGHKLJM.DLEIMBNDMOF - dLKMEPPLCGM.DLEIMBNDMOF) * KBKMPEOMABI;
				dLKMEPPLCGM.OKJBKNEPKPN += (mBBPBGHKLJM.OKJBKNEPKPN - dLKMEPPLCGM.OKJBKNEPKPN) * KBKMPEOMABI;
				break;
			}
			return;
		}
		float num2;
		float num3;
		float num4;
		float num5;
		if (HFLODNLEGFL >= eNBKHCNKHCC[eNBKHCNKHCC.Length - 5])
		{
			int num = eNBKHCNKHCC.Length;
			num2 = eNBKHCNKHCC[num + -4];
			num3 = eNBKHCNKHCC[num + -3];
			num4 = eNBKHCNKHCC[num + -2];
			num5 = eNBKHCNKHCC[num + -1];
		}
		else
		{
			int num6 = GNGKKPOGGGM.EIAMMDBFDFO(eNBKHCNKHCC, HFLODNLEGFL, 5);
			num2 = eNBKHCNKHCC[num6 + -4];
			num3 = eNBKHCNKHCC[num6 + -3];
			num4 = eNBKHCNKHCC[num6 + -2];
			num5 = eNBKHCNKHCC[num6 + -1];
			float num7 = eNBKHCNKHCC[num6];
			float num8 = IFMKHGLKEMB(num6 / 5 - 1, 1f - (HFLODNLEGFL - num7) / (eNBKHCNKHCC[num6 + -5] - num7));
			num2 += (eNBKHCNKHCC[num6 + 1] - num2) * num8;
			num3 += (eNBKHCNKHCC[num6 + 2] - num3) * num8;
			num4 += (eNBKHCNKHCC[num6 + 3] - num4) * num8;
			num5 += (eNBKHCNKHCC[num6 + 4] - num5) * num8;
		}
		if (IFKBABBBDJM == BFCFMFBHBCH.Setup)
		{
			MNNBOEPCJGP mBBPBGHKLJM2 = dLKMEPPLCGM.MBBPBGHKLJM;
			dLKMEPPLCGM.OIBAIJIPGOM = mBBPBGHKLJM2.OIBAIJIPGOM + (num2 - mBBPBGHKLJM2.OIBAIJIPGOM) * KBKMPEOMABI;
			dLKMEPPLCGM.DHNKOEMONHP = mBBPBGHKLJM2.DHNKOEMONHP + (num3 - mBBPBGHKLJM2.DHNKOEMONHP) * KBKMPEOMABI;
			dLKMEPPLCGM.DLEIMBNDMOF = mBBPBGHKLJM2.DLEIMBNDMOF + (num4 - mBBPBGHKLJM2.DLEIMBNDMOF) * KBKMPEOMABI;
			dLKMEPPLCGM.OKJBKNEPKPN = mBBPBGHKLJM2.OKJBKNEPKPN + (num5 - mBBPBGHKLJM2.OKJBKNEPKPN) * KBKMPEOMABI;
		}
		else
		{
			dLKMEPPLCGM.OIBAIJIPGOM += (num2 - dLKMEPPLCGM.OIBAIJIPGOM) * KBKMPEOMABI;
			dLKMEPPLCGM.DHNKOEMONHP += (num3 - dLKMEPPLCGM.DHNKOEMONHP) * KBKMPEOMABI;
			dLKMEPPLCGM.DLEIMBNDMOF += (num4 - dLKMEPPLCGM.DLEIMBNDMOF) * KBKMPEOMABI;
			dLKMEPPLCGM.OKJBKNEPKPN += (num5 - dLKMEPPLCGM.OKJBKNEPKPN) * KBKMPEOMABI;
		}
	}
}
