using System;

internal class CDMOHJJNDAO : OMOBJNLGOBO
{
	public CDMOHJJNDAO(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public CDMOHJJNDAO(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal CDMOHJJNDAO(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new CDMOHJJNDAO(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		CKOLPCINKAN cKOLPCINKAN = (CKOLPCINKAN)base.NBPANDNEJGI;
		CKOLPCINKAN cKOLPCINKAN2 = (CKOLPCINKAN)base.FIJLKLCHMGH;
		CKOLPCINKAN cKOLPCINKAN3 = (CKOLPCINKAN)BCIHLCMFAEK.NBPANDNEJGI;
		CKOLPCINKAN cKOLPCINKAN4 = (CKOLPCINKAN)BCIHLCMFAEK.FIJLKLCHMGH;
		CKOLPCINKAN cKOLPCINKAN5 = (CKOLPCINKAN)base.LAMGGDKLPJH[0];
		CKOLPCINKAN cKOLPCINKAN6 = (CKOLPCINKAN)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = BCMDHIIJKJE.PLIFFMMBNPM(17);
		uint[] array2 = BCMDHIIJKJE.PLIFFMMBNPM(17);
		uint[] array3 = BCMDHIIJKJE.PLIFFMMBNPM(17);
		uint[] array4 = BCMDHIIJKJE.PLIFFMMBNPM(17);
		bool flag = cKOLPCINKAN5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = cKOLPCINKAN3.AMFCENFNAJJ;
			array6 = cKOLPCINKAN4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			AMEIPDBNOGO.MIOEHGDPGAG(cKOLPCINKAN5.AMFCENFNAJJ, array6);
			array5 = array2;
			AMEIPDBNOGO.IBJBIGNPNEM(array6, cKOLPCINKAN3.AMFCENFNAJJ, array5);
			AMEIPDBNOGO.IBJBIGNPNEM(array6, cKOLPCINKAN5.AMFCENFNAJJ, array6);
			AMEIPDBNOGO.IBJBIGNPNEM(array6, cKOLPCINKAN4.AMFCENFNAJJ, array6);
		}
		bool flag2 = cKOLPCINKAN6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = cKOLPCINKAN.AMFCENFNAJJ;
			array8 = cKOLPCINKAN2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			AMEIPDBNOGO.MIOEHGDPGAG(cKOLPCINKAN6.AMFCENFNAJJ, array8);
			array7 = array;
			AMEIPDBNOGO.IBJBIGNPNEM(array8, cKOLPCINKAN.AMFCENFNAJJ, array7);
			AMEIPDBNOGO.IBJBIGNPNEM(array8, cKOLPCINKAN6.AMFCENFNAJJ, array8);
			AMEIPDBNOGO.IBJBIGNPNEM(array8, cKOLPCINKAN2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = BCMDHIIJKJE.PLIFFMMBNPM(17);
		AMEIPDBNOGO.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		AMEIPDBNOGO.FBGIHKPECCO(array8, array6, array10);
		if (BCMDHIIJKJE.EJJHHCOFAAI(17, array9))
		{
			if (BCMDHIIJKJE.EJJHHCOFAAI(17, array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		AMEIPDBNOGO.MIOEHGDPGAG(array9, array11);
		uint[] array12 = BCMDHIIJKJE.PLIFFMMBNPM(17);
		AMEIPDBNOGO.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		AMEIPDBNOGO.IBJBIGNPNEM(array11, array7, array13);
		AMEIPDBNOGO.IBJBIGNPNEM(array8, array12, array);
		CKOLPCINKAN cKOLPCINKAN7 = new CKOLPCINKAN(array4);
		AMEIPDBNOGO.MIOEHGDPGAG(array10, cKOLPCINKAN7.AMFCENFNAJJ);
		AMEIPDBNOGO.JEACJNAKLDJ(cKOLPCINKAN7.AMFCENFNAJJ, array12, cKOLPCINKAN7.AMFCENFNAJJ);
		AMEIPDBNOGO.FBGIHKPECCO(cKOLPCINKAN7.AMFCENFNAJJ, array13, cKOLPCINKAN7.AMFCENFNAJJ);
		AMEIPDBNOGO.FBGIHKPECCO(cKOLPCINKAN7.AMFCENFNAJJ, array13, cKOLPCINKAN7.AMFCENFNAJJ);
		CKOLPCINKAN cKOLPCINKAN8 = new CKOLPCINKAN(array12);
		AMEIPDBNOGO.FBGIHKPECCO(array13, cKOLPCINKAN7.AMFCENFNAJJ, cKOLPCINKAN8.AMFCENFNAJJ);
		AMEIPDBNOGO.IBJBIGNPNEM(cKOLPCINKAN8.AMFCENFNAJJ, array10, array2);
		AMEIPDBNOGO.FBGIHKPECCO(array2, array, cKOLPCINKAN8.AMFCENFNAJJ);
		CKOLPCINKAN cKOLPCINKAN9 = new CKOLPCINKAN(array9);
		if (!flag)
		{
			AMEIPDBNOGO.IBJBIGNPNEM(cKOLPCINKAN9.AMFCENFNAJJ, cKOLPCINKAN5.AMFCENFNAJJ, cKOLPCINKAN9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			AMEIPDBNOGO.IBJBIGNPNEM(cKOLPCINKAN9.AMFCENFNAJJ, cKOLPCINKAN6.AMFCENFNAJJ, cKOLPCINKAN9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { cKOLPCINKAN9 };
		return new CDMOHJJNDAO(bHPIABAGAPB, cKOLPCINKAN7, cKOLPCINKAN8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		CKOLPCINKAN cKOLPCINKAN = (CKOLPCINKAN)base.FIJLKLCHMGH;
		if (cKOLPCINKAN.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		CKOLPCINKAN cKOLPCINKAN2 = (CKOLPCINKAN)base.NBPANDNEJGI;
		CKOLPCINKAN cKOLPCINKAN3 = (CKOLPCINKAN)base.LAMGGDKLPJH[0];
		uint[] array = BCMDHIIJKJE.PLIFFMMBNPM(17);
		uint[] array2 = BCMDHIIJKJE.PLIFFMMBNPM(17);
		uint[] array3 = BCMDHIIJKJE.PLIFFMMBNPM(17);
		AMEIPDBNOGO.MIOEHGDPGAG(cKOLPCINKAN.AMFCENFNAJJ, array3);
		uint[] array4 = BCMDHIIJKJE.PLIFFMMBNPM(17);
		AMEIPDBNOGO.MIOEHGDPGAG(array3, array4);
		bool flag = cKOLPCINKAN3.EOJCHPEGABD;
		uint[] array5 = cKOLPCINKAN3.AMFCENFNAJJ;
		if (!flag)
		{
			array5 = array2;
			AMEIPDBNOGO.MIOEHGDPGAG(cKOLPCINKAN3.AMFCENFNAJJ, array5);
		}
		AMEIPDBNOGO.FBGIHKPECCO(cKOLPCINKAN2.AMFCENFNAJJ, array5, array);
		uint[] array6 = array2;
		AMEIPDBNOGO.JEACJNAKLDJ(cKOLPCINKAN2.AMFCENFNAJJ, array5, array6);
		AMEIPDBNOGO.IBJBIGNPNEM(array6, array, array6);
		BCMDHIIJKJE.FIBDFFPCDGC(17, array6, array6, array6);
		AMEIPDBNOGO.LJNDDEIFKPD(array6);
		uint[] array7 = array3;
		AMEIPDBNOGO.IBJBIGNPNEM(array3, cKOLPCINKAN2.AMFCENFNAJJ, array7);
		BCMDHIIJKJE.BJPLEKMGBJA(17, array7, 2, 0u);
		AMEIPDBNOGO.LJNDDEIFKPD(array7);
		BCMDHIIJKJE.BJPLEKMGBJA(17, array4, 3, 0u, array);
		AMEIPDBNOGO.LJNDDEIFKPD(array);
		CKOLPCINKAN cKOLPCINKAN4 = new CKOLPCINKAN(array4);
		AMEIPDBNOGO.MIOEHGDPGAG(array6, cKOLPCINKAN4.AMFCENFNAJJ);
		AMEIPDBNOGO.FBGIHKPECCO(cKOLPCINKAN4.AMFCENFNAJJ, array7, cKOLPCINKAN4.AMFCENFNAJJ);
		AMEIPDBNOGO.FBGIHKPECCO(cKOLPCINKAN4.AMFCENFNAJJ, array7, cKOLPCINKAN4.AMFCENFNAJJ);
		CKOLPCINKAN cKOLPCINKAN5 = new CKOLPCINKAN(array7);
		AMEIPDBNOGO.FBGIHKPECCO(array7, cKOLPCINKAN4.AMFCENFNAJJ, cKOLPCINKAN5.AMFCENFNAJJ);
		AMEIPDBNOGO.IBJBIGNPNEM(cKOLPCINKAN5.AMFCENFNAJJ, array6, cKOLPCINKAN5.AMFCENFNAJJ);
		AMEIPDBNOGO.FBGIHKPECCO(cKOLPCINKAN5.AMFCENFNAJJ, array, cKOLPCINKAN5.AMFCENFNAJJ);
		CKOLPCINKAN cKOLPCINKAN6 = new CKOLPCINKAN(array6);
		AMEIPDBNOGO.LLGLJBDLBOP(cKOLPCINKAN.AMFCENFNAJJ, cKOLPCINKAN6.AMFCENFNAJJ);
		if (!flag)
		{
			AMEIPDBNOGO.IBJBIGNPNEM(cKOLPCINKAN6.AMFCENFNAJJ, cKOLPCINKAN3.AMFCENFNAJJ, cKOLPCINKAN6.AMFCENFNAJJ);
		}
		return new CDMOHJJNDAO(bHPIABAGAPB, cKOLPCINKAN4, cKOLPCINKAN5, new KBINBLGGLNE[1] { cKOLPCINKAN6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new CDMOHJJNDAO(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
