public class CFMJBFILJCB : PJGIGKJFGFI
{
	public CFMJBFILJCB(byte[] GFPBBLPMOOL)
		: base(GFPBBLPMOOL)
	{
	}

	public CFMJBFILJCB(LNKPCJLANAO NEMEKIOEOLC)
		: base(NEMEKIOEOLC)
	{
	}

	internal override void LMDBBPLCJDM(JBLJHINPLMC NMHOOGAGLOA)
	{
		NMHOOGAGLOA.AGNEJPEMPAP(4, GFPBBLPMOOL);
	}

	internal static void LMDBBPLCJDM(JBLJHINPLMC NMHOOGAGLOA, byte[] DIPNEDDIHBK, int IBNDGNOIEEF, int EOFAGACBNFP)
	{
		NMHOOGAGLOA.AGNEJPEMPAP(4, DIPNEDDIHBK, IBNDGNOIEEF, EOFAGACBNFP);
	}
}
