using System;
using Org.BouncyCastle.Math;

public class CGAMCAFJLGJ : LNKPCJLANAO
{
	private readonly KLKJHFKJLEM BDKFNEDHAOJ;

	private readonly EDOEBJJFOBM IJJHBEECMBP;

	public KLKJHFKJLEM BOKHDKMEAED
	{
		get
		{
			return BDKFNEDHAOJ;
		}
	}

	public EDOEBJJFOBM KPJHHAAOFOH
	{
		get
		{
			return IJJHBEECMBP;
		}
	}

	public CGAMCAFJLGJ(BigInteger FEFIGOGJCCO)
	{
		BDKFNEDHAOJ = JJFMEBLGJEP.FCKODOMMAFF;
		IJJHBEECMBP = new GLFDIPNOLKN(FEFIGOGJCCO);
	}

	public CGAMCAFJLGJ(int CEKMAJAHNAG, int KDFFDKFCDKK)
		: this(CEKMAJAHNAG, KDFFDKFCDKK, 0, 0)
	{
	}

	public CGAMCAFJLGJ(int CEKMAJAHNAG, int KDFFDKFCDKK, int FKOBMEPIABG, int KHNDCPCHOEM)
	{
		BDKFNEDHAOJ = JJFMEBLGJEP.IOCHGCOMCGG;
		DLDBGGDLOOO dLDBGGDLOOO = new DLDBGGDLOOO(new GLFDIPNOLKN(CEKMAJAHNAG));
		if (FKOBMEPIABG == 0)
		{
			if (KHNDCPCHOEM != 0)
			{
				throw new ArgumentException("inconsistent k values");
			}
			dLDBGGDLOOO.JEACJNAKLDJ(JJFMEBLGJEP.OILAJONOOJC, new GLFDIPNOLKN(KDFFDKFCDKK));
		}
		else
		{
			if (FKOBMEPIABG <= KDFFDKFCDKK || KHNDCPCHOEM <= FKOBMEPIABG)
			{
				throw new ArgumentException("inconsistent k values");
			}
			dLDBGGDLOOO.JEACJNAKLDJ(JJFMEBLGJEP.EDBKIIPIICC, new KOGPLMALOEH(new GLFDIPNOLKN(KDFFDKFCDKK), new GLFDIPNOLKN(FKOBMEPIABG), new GLFDIPNOLKN(KHNDCPCHOEM)));
		}
		IJJHBEECMBP = new KOGPLMALOEH(dLDBGGDLOOO);
	}

	private CGAMCAFJLGJ(ALLINHNNNJN MIABODPHOIP)
	{
		BDKFNEDHAOJ = KLKJHFKJLEM.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(0));
		IJJHBEECMBP = MIABODPHOIP.ECNCPJGHBIG(1).IIHKEACDNID();
	}

	public static CGAMCAFJLGJ BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC is CGAMCAFJLGJ)
		{
			return (CGAMCAFJLGJ)NEMEKIOEOLC;
		}
		if (NEMEKIOEOLC == null)
		{
			return null;
		}
		return new CGAMCAFJLGJ(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC));
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		return new KOGPLMALOEH(BDKFNEDHAOJ, IJJHBEECMBP);
	}
}
