public class CIBIHNOLONH : FJMKMKNJKOI
{
	public CIBIHNOLONH(byte[] MBBPBGHKLJM, int FOIHIFLKIPF)
		: base(MBBPBGHKLJM, FOIHIFLKIPF)
	{
	}

	public CIBIHNOLONH(byte[] MBBPBGHKLJM)
		: base(MBBPBGHKLJM)
	{
	}

	public CIBIHNOLONH(int LBGGCEGLKBD)
		: base(LBGGCEGLKBD)
	{
	}

	public CIBIHNOLONH(LNKPCJLANAO NEMEKIOEOLC)
		: base(NEMEKIOEOLC)
	{
	}

	internal override void LMDBBPLCJDM(JBLJHINPLMC NMHOOGAGLOA)
	{
		if (NMHOOGAGLOA is KDNENBIPFBJ || NMHOOGAGLOA is OPNGAMEJCPK)
		{
			NMHOOGAGLOA.AGNEJPEMPAP(3, (byte)GNBLFGJPAJF, PCECPIAMFEN);
		}
		else
		{
			base.LMDBBPLCJDM(NMHOOGAGLOA);
		}
	}
}
