internal abstract class CLKJLHBLJAH
{
	public static void BMEIFJDODCF(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] JMNJPLAGDDJ)
	{
		AKOICJCJNFB.BMEIFJDODCF(AMFCENFNAJJ, CNLILOEEBOJ, JMNJPLAGDDJ);
		AKOICJCJNFB.BMEIFJDODCF(AMFCENFNAJJ, 8, CNLILOEEBOJ, 8, JMNJPLAGDDJ, 16);
		uint num = AKOICJCJNFB.HFHBOBLBLDH(JMNJPLAGDDJ, 8, JMNJPLAGDDJ, 16);
		uint eFEEMAAFCMH = num + AKOICJCJNFB.MAALDEFJPJA(JMNJPLAGDDJ, 0, JMNJPLAGDDJ, 8, 0u);
		num += AKOICJCJNFB.MAALDEFJPJA(JMNJPLAGDDJ, 24, JMNJPLAGDDJ, 16, eFEEMAAFCMH);
		uint[] array = AKOICJCJNFB.PLIFFMMBNPM();
		uint[] array2 = AKOICJCJNFB.PLIFFMMBNPM();
		bool flag = AKOICJCJNFB.COOLFBDPHEO(AMFCENFNAJJ, 8, AMFCENFNAJJ, 0, array, 0) != AKOICJCJNFB.COOLFBDPHEO(CNLILOEEBOJ, 8, CNLILOEEBOJ, 0, array2, 0);
		uint[] array3 = AKOICJCJNFB.DCPJKFEDHOJ();
		AKOICJCJNFB.BMEIFJDODCF(array, array2, array3);
		num += (uint)((!flag) ? BCMDHIIJKJE.DKAMAFLMHEJ(16, array3, 0, JMNJPLAGDDJ, 8) : ((int)BCMDHIIJKJE.MAALDEFJPJA(16, array3, 0, JMNJPLAGDDJ, 8)));
		BCMDHIIJKJE.HNPBCAPBDGJ(32, num, JMNJPLAGDDJ, 24);
	}

	public static void MIOEHGDPGAG(uint[] AMFCENFNAJJ, uint[] JMNJPLAGDDJ)
	{
		AKOICJCJNFB.MIOEHGDPGAG(AMFCENFNAJJ, JMNJPLAGDDJ);
		AKOICJCJNFB.MIOEHGDPGAG(AMFCENFNAJJ, 8, JMNJPLAGDDJ, 16);
		uint num = AKOICJCJNFB.HFHBOBLBLDH(JMNJPLAGDDJ, 8, JMNJPLAGDDJ, 16);
		uint eFEEMAAFCMH = num + AKOICJCJNFB.MAALDEFJPJA(JMNJPLAGDDJ, 0, JMNJPLAGDDJ, 8, 0u);
		num += AKOICJCJNFB.MAALDEFJPJA(JMNJPLAGDDJ, 24, JMNJPLAGDDJ, 16, eFEEMAAFCMH);
		uint[] array = AKOICJCJNFB.PLIFFMMBNPM();
		AKOICJCJNFB.COOLFBDPHEO(AMFCENFNAJJ, 8, AMFCENFNAJJ, 0, array, 0);
		uint[] array2 = AKOICJCJNFB.DCPJKFEDHOJ();
		AKOICJCJNFB.MIOEHGDPGAG(array, array2);
		num += (uint)BCMDHIIJKJE.DKAMAFLMHEJ(16, array2, 0, JMNJPLAGDDJ, 8);
		BCMDHIIJKJE.HNPBCAPBDGJ(32, num, JMNJPLAGDDJ, 24);
	}
}
