public static class CNCPCJFNBJB
{
	public static bool LGOKFILDDDD(this NAAHKHPBAPA HBBIFNLDKPO)
	{
		return HBBIFNLDKPO == NAAHKHPBAPA.Hammer || HBBIFNLDKPO == NAAHKHPBAPA.Anvil || HBBIFNLDKPO == NAAHKHPBAPA.BoxingGlove || HBBIFNLDKPO == NAAHKHPBAPA.Dice;
	}

	public static bool MCMDJCBFENO(this NAAHKHPBAPA HBBIFNLDKPO)
	{
		return HBBIFNLDKPO == NAAHKHPBAPA.Bomb || HBBIFNLDKPO == NAAHKHPBAPA.Rocket || HBBIFNLDKPO == NAAHKHPBAPA.DiscoBall;
	}
}
