public class COBAFBMKAJE : KCBOLLFKMGG
{
	private readonly COCECKPDIKC LGAAPLFEPMG;

	private readonly COEMJAGOFJJ ECPKCNOAOAJ;

	public object IDLLMGBMDGB
	{
		get
		{
			return LGAAPLFEPMG;
		}
	}

	public COBAFBMKAJE(string ADLMOHOLCGL, COEMJAGOFJJ ECPKCNOAOAJ)
	{
		KLKJHFKJLEM pGJDDDOKOJO = BJMIIIEBPNP.ANENONPLLFP(ADLMOHOLCGL);
		this.ECPKCNOAOAJ = ECPKCNOAOAJ;
		LGAAPLFEPMG = BJMIIIEBPNP.KCFCOMCMHOE(pGJDDDOKOJO, ADLMOHOLCGL);
	}

	public COBAFBMKAJE(COCECKPDIKC ADLMOHOLCGL, COEMJAGOFJJ ECPKCNOAOAJ)
	{
		this.ECPKCNOAOAJ = ECPKCNOAOAJ;
		LGAAPLFEPMG = ADLMOHOLCGL;
	}

	public DPGEGPIMHCH GBNGIELMFLJ()
	{
		OHPHNNNHCOO oHPHNNNHCOO = FLMLLBCHPNI.OOLDLJODJGM(BJMIIIEBPNP.PPPAACNJBIC(LGAAPLFEPMG));
		oHPHNNNHCOO.DIOELAHNLKJ(false, ECPKCNOAOAJ);
		return new ADCEGLFCOJF(oHPHNNNHCOO);
	}
}
