using System;

public class CONJOCHPANG : EEBNPONHKOK
{
	private const int IOCOCGHMNGB = 16;

	private int OLFEOHKKGIP;

	private int NAHACOBOKIM;

	private int MPNNHCHGEGL;

	private int AJBHIPPAFIJ;

	private int[] CBPFFIBINEH = new int[16];

	private int ABBPDEOGNFE;

	public override string KFKMEPMEBND
	{
		get
		{
			return "RIPEMD128";
		}
	}

	public CONJOCHPANG()
	{
		OMOKOKFNBKI();
	}

	public CONJOCHPANG(CONJOCHPANG LLIEHCKNJEM)
		: base(LLIEHCKNJEM)
	{
		AKBPCECABIO(LLIEHCKNJEM);
	}

	private void AKBPCECABIO(CONJOCHPANG LLIEHCKNJEM)
	{
		AKBPCECABIO((EEBNPONHKOK)LLIEHCKNJEM);
		OLFEOHKKGIP = LLIEHCKNJEM.OLFEOHKKGIP;
		NAHACOBOKIM = LLIEHCKNJEM.NAHACOBOKIM;
		MPNNHCHGEGL = LLIEHCKNJEM.MPNNHCHGEGL;
		AJBHIPPAFIJ = LLIEHCKNJEM.AJBHIPPAFIJ;
		Array.Copy(LLIEHCKNJEM.CBPFFIBINEH, 0, CBPFFIBINEH, 0, LLIEHCKNJEM.CBPFFIBINEH.Length);
		ABBPDEOGNFE = LLIEHCKNJEM.ABBPDEOGNFE;
	}

	public override int EEMLLAMENHO()
	{
		return 16;
	}

	internal override void ICKIHAABCPI(byte[] MOPCLEEGDFB, int ELICNEDIBGB)
	{
		CBPFFIBINEH[ABBPDEOGNFE++] = (MOPCLEEGDFB[ELICNEDIBGB] & 0xFF) | ((MOPCLEEGDFB[ELICNEDIBGB + 1] & 0xFF) << 8) | ((MOPCLEEGDFB[ELICNEDIBGB + 2] & 0xFF) << 16) | ((MOPCLEEGDFB[ELICNEDIBGB + 3] & 0xFF) << 24);
		if (ABBPDEOGNFE == 16)
		{
			DPACJDFHLKB();
		}
	}

	internal override void IIENDLEDGMC(long EAJFCEBGGIG)
	{
		if (ABBPDEOGNFE > 14)
		{
			DPACJDFHLKB();
		}
		CBPFFIBINEH[14] = (int)(EAJFCEBGGIG & 0xFFFFFFFFu);
		CBPFFIBINEH[15] = (int)((ulong)EAJFCEBGGIG >> 32);
	}

	private void DKLAJHNFBJM(int BKKMJAIKJAL, byte[] NGAGMIIBGKA, int EMAKNGBIFDC)
	{
		NGAGMIIBGKA[EMAKNGBIFDC] = (byte)BKKMJAIKJAL;
		NGAGMIIBGKA[EMAKNGBIFDC + 1] = (byte)((uint)BKKMJAIKJAL >> 8);
		NGAGMIIBGKA[EMAKNGBIFDC + 2] = (byte)((uint)BKKMJAIKJAL >> 16);
		NGAGMIIBGKA[EMAKNGBIFDC + 3] = (byte)((uint)BKKMJAIKJAL >> 24);
	}

	public override int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		OJILOEAPDCL();
		DKLAJHNFBJM(OLFEOHKKGIP, BILGCJNPJGJ, EMAKNGBIFDC);
		DKLAJHNFBJM(NAHACOBOKIM, BILGCJNPJGJ, EMAKNGBIFDC + 4);
		DKLAJHNFBJM(MPNNHCHGEGL, BILGCJNPJGJ, EMAKNGBIFDC + 8);
		DKLAJHNFBJM(AJBHIPPAFIJ, BILGCJNPJGJ, EMAKNGBIFDC + 12);
		OMOKOKFNBKI();
		return 16;
	}

	public override void OMOKOKFNBKI()
	{
		base.OMOKOKFNBKI();
		OLFEOHKKGIP = 1732584193;
		NAHACOBOKIM = -271733879;
		MPNNHCHGEGL = -1732584194;
		AJBHIPPAFIJ = 271733878;
		ABBPDEOGNFE = 0;
		for (int i = 0; i != CBPFFIBINEH.Length; i++)
		{
			CBPFFIBINEH[i] = 0;
		}
	}

	private int CKFFNPFNMMM(int AMFCENFNAJJ, int IDHLPOFDLKJ)
	{
		return (AMFCENFNAJJ << IDHLPOFDLKJ) | (int)((uint)AMFCENFNAJJ >> 32 - IDHLPOFDLKJ);
	}

	private int HBFJAOFJIFP(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return AMFCENFNAJJ ^ CNLILOEEBOJ ^ IGNEOOOFEMO;
	}

	private int IKKGCFMJODC(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return (AMFCENFNAJJ & CNLILOEEBOJ) | (~AMFCENFNAJJ & IGNEOOOFEMO);
	}

	private int HJEBNCKAABK(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return (AMFCENFNAJJ | ~CNLILOEEBOJ) ^ IGNEOOOFEMO;
	}

	private int LJFNDAMNFAC(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return (AMFCENFNAJJ & IGNEOOOFEMO) | (CNLILOEEBOJ & ~IGNEOOOFEMO);
	}

	private int HBFJAOFJIFP(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + HBFJAOFJIFP(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ, IBBBMACIBGK);
	}

	private int IKKGCFMJODC(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + IKKGCFMJODC(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + 1518500249, IBBBMACIBGK);
	}

	private int HJEBNCKAABK(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + HJEBNCKAABK(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + 1859775393, IBBBMACIBGK);
	}

	private int LJFNDAMNFAC(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + LJFNDAMNFAC(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + -1894007588, IBBBMACIBGK);
	}

	private int NPCEFGPCCLG(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + HBFJAOFJIFP(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ, IBBBMACIBGK);
	}

	private int PNOFCEHBIDI(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + IKKGCFMJODC(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + 1836072691, IBBBMACIBGK);
	}

	private int MCFNGOIJBHD(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + HJEBNCKAABK(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + 1548603684, IBBBMACIBGK);
	}

	private int PPPBJLPMJPG(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + LJFNDAMNFAC(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + 1352829926, IBBBMACIBGK);
	}

	internal override void DPACJDFHLKB()
	{
		int oLFEOHKKGIP;
		int mNIMEAMHNMI = (oLFEOHKKGIP = OLFEOHKKGIP);
		int nAHACOBOKIM;
		int num = (nAHACOBOKIM = NAHACOBOKIM);
		int mPNNHCHGEGL;
		int num2 = (mPNNHCHGEGL = MPNNHCHGEGL);
		int aJBHIPPAFIJ;
		int num3 = (aJBHIPPAFIJ = AJBHIPPAFIJ);
		mNIMEAMHNMI = HBFJAOFJIFP(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[0], 11);
		num3 = HBFJAOFJIFP(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[1], 14);
		num2 = HBFJAOFJIFP(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[2], 15);
		num = HBFJAOFJIFP(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[3], 12);
		mNIMEAMHNMI = HBFJAOFJIFP(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[4], 5);
		num3 = HBFJAOFJIFP(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[5], 8);
		num2 = HBFJAOFJIFP(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[6], 7);
		num = HBFJAOFJIFP(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[7], 9);
		mNIMEAMHNMI = HBFJAOFJIFP(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[8], 11);
		num3 = HBFJAOFJIFP(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[9], 13);
		num2 = HBFJAOFJIFP(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[10], 14);
		num = HBFJAOFJIFP(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[11], 15);
		mNIMEAMHNMI = HBFJAOFJIFP(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[12], 6);
		num3 = HBFJAOFJIFP(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[13], 7);
		num2 = HBFJAOFJIFP(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[14], 9);
		num = HBFJAOFJIFP(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[15], 8);
		mNIMEAMHNMI = IKKGCFMJODC(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[7], 7);
		num3 = IKKGCFMJODC(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[4], 6);
		num2 = IKKGCFMJODC(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[13], 8);
		num = IKKGCFMJODC(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[1], 13);
		mNIMEAMHNMI = IKKGCFMJODC(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[10], 11);
		num3 = IKKGCFMJODC(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[6], 9);
		num2 = IKKGCFMJODC(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[15], 7);
		num = IKKGCFMJODC(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[3], 15);
		mNIMEAMHNMI = IKKGCFMJODC(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[12], 7);
		num3 = IKKGCFMJODC(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[0], 12);
		num2 = IKKGCFMJODC(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[9], 15);
		num = IKKGCFMJODC(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[5], 9);
		mNIMEAMHNMI = IKKGCFMJODC(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[2], 11);
		num3 = IKKGCFMJODC(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[14], 7);
		num2 = IKKGCFMJODC(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[11], 13);
		num = IKKGCFMJODC(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[8], 12);
		mNIMEAMHNMI = HJEBNCKAABK(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[3], 11);
		num3 = HJEBNCKAABK(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[10], 13);
		num2 = HJEBNCKAABK(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[14], 6);
		num = HJEBNCKAABK(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[4], 7);
		mNIMEAMHNMI = HJEBNCKAABK(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[9], 14);
		num3 = HJEBNCKAABK(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[15], 9);
		num2 = HJEBNCKAABK(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[8], 13);
		num = HJEBNCKAABK(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[1], 15);
		mNIMEAMHNMI = HJEBNCKAABK(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[2], 14);
		num3 = HJEBNCKAABK(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[7], 8);
		num2 = HJEBNCKAABK(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[0], 13);
		num = HJEBNCKAABK(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[6], 6);
		mNIMEAMHNMI = HJEBNCKAABK(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[13], 5);
		num3 = HJEBNCKAABK(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[11], 12);
		num2 = HJEBNCKAABK(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[5], 7);
		num = HJEBNCKAABK(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[12], 5);
		mNIMEAMHNMI = LJFNDAMNFAC(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[1], 11);
		num3 = LJFNDAMNFAC(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[9], 12);
		num2 = LJFNDAMNFAC(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[11], 14);
		num = LJFNDAMNFAC(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[10], 15);
		mNIMEAMHNMI = LJFNDAMNFAC(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[0], 14);
		num3 = LJFNDAMNFAC(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[8], 15);
		num2 = LJFNDAMNFAC(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[12], 9);
		num = LJFNDAMNFAC(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[4], 8);
		mNIMEAMHNMI = LJFNDAMNFAC(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[13], 9);
		num3 = LJFNDAMNFAC(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[3], 14);
		num2 = LJFNDAMNFAC(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[7], 5);
		num = LJFNDAMNFAC(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[15], 6);
		mNIMEAMHNMI = LJFNDAMNFAC(mNIMEAMHNMI, num, num2, num3, CBPFFIBINEH[14], 8);
		num3 = LJFNDAMNFAC(num3, mNIMEAMHNMI, num, num2, CBPFFIBINEH[5], 6);
		num2 = LJFNDAMNFAC(num2, num3, mNIMEAMHNMI, num, CBPFFIBINEH[6], 5);
		num = LJFNDAMNFAC(num, num2, num3, mNIMEAMHNMI, CBPFFIBINEH[2], 12);
		oLFEOHKKGIP = PPPBJLPMJPG(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[5], 8);
		aJBHIPPAFIJ = PPPBJLPMJPG(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[14], 9);
		mPNNHCHGEGL = PPPBJLPMJPG(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[7], 9);
		nAHACOBOKIM = PPPBJLPMJPG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[0], 11);
		oLFEOHKKGIP = PPPBJLPMJPG(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[9], 13);
		aJBHIPPAFIJ = PPPBJLPMJPG(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[2], 15);
		mPNNHCHGEGL = PPPBJLPMJPG(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[11], 15);
		nAHACOBOKIM = PPPBJLPMJPG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[4], 5);
		oLFEOHKKGIP = PPPBJLPMJPG(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[13], 7);
		aJBHIPPAFIJ = PPPBJLPMJPG(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[6], 7);
		mPNNHCHGEGL = PPPBJLPMJPG(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[15], 8);
		nAHACOBOKIM = PPPBJLPMJPG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[8], 11);
		oLFEOHKKGIP = PPPBJLPMJPG(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[1], 14);
		aJBHIPPAFIJ = PPPBJLPMJPG(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[10], 14);
		mPNNHCHGEGL = PPPBJLPMJPG(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[3], 12);
		nAHACOBOKIM = PPPBJLPMJPG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[12], 6);
		oLFEOHKKGIP = MCFNGOIJBHD(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[6], 9);
		aJBHIPPAFIJ = MCFNGOIJBHD(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[11], 13);
		mPNNHCHGEGL = MCFNGOIJBHD(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[3], 15);
		nAHACOBOKIM = MCFNGOIJBHD(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[7], 7);
		oLFEOHKKGIP = MCFNGOIJBHD(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[0], 12);
		aJBHIPPAFIJ = MCFNGOIJBHD(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[13], 8);
		mPNNHCHGEGL = MCFNGOIJBHD(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[5], 9);
		nAHACOBOKIM = MCFNGOIJBHD(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[10], 11);
		oLFEOHKKGIP = MCFNGOIJBHD(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[14], 7);
		aJBHIPPAFIJ = MCFNGOIJBHD(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[15], 7);
		mPNNHCHGEGL = MCFNGOIJBHD(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[8], 12);
		nAHACOBOKIM = MCFNGOIJBHD(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[12], 7);
		oLFEOHKKGIP = MCFNGOIJBHD(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[4], 6);
		aJBHIPPAFIJ = MCFNGOIJBHD(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[9], 15);
		mPNNHCHGEGL = MCFNGOIJBHD(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[1], 13);
		nAHACOBOKIM = MCFNGOIJBHD(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[2], 11);
		oLFEOHKKGIP = PNOFCEHBIDI(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[15], 9);
		aJBHIPPAFIJ = PNOFCEHBIDI(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[5], 7);
		mPNNHCHGEGL = PNOFCEHBIDI(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[1], 15);
		nAHACOBOKIM = PNOFCEHBIDI(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[3], 11);
		oLFEOHKKGIP = PNOFCEHBIDI(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[7], 8);
		aJBHIPPAFIJ = PNOFCEHBIDI(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[14], 6);
		mPNNHCHGEGL = PNOFCEHBIDI(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[6], 6);
		nAHACOBOKIM = PNOFCEHBIDI(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[9], 14);
		oLFEOHKKGIP = PNOFCEHBIDI(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[11], 12);
		aJBHIPPAFIJ = PNOFCEHBIDI(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[8], 13);
		mPNNHCHGEGL = PNOFCEHBIDI(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[12], 5);
		nAHACOBOKIM = PNOFCEHBIDI(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[2], 14);
		oLFEOHKKGIP = PNOFCEHBIDI(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[10], 13);
		aJBHIPPAFIJ = PNOFCEHBIDI(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[0], 13);
		mPNNHCHGEGL = PNOFCEHBIDI(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[4], 7);
		nAHACOBOKIM = PNOFCEHBIDI(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[13], 5);
		oLFEOHKKGIP = NPCEFGPCCLG(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[8], 15);
		aJBHIPPAFIJ = NPCEFGPCCLG(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[6], 5);
		mPNNHCHGEGL = NPCEFGPCCLG(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[4], 8);
		nAHACOBOKIM = NPCEFGPCCLG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[1], 11);
		oLFEOHKKGIP = NPCEFGPCCLG(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[3], 14);
		aJBHIPPAFIJ = NPCEFGPCCLG(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[11], 14);
		mPNNHCHGEGL = NPCEFGPCCLG(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[15], 6);
		nAHACOBOKIM = NPCEFGPCCLG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[0], 14);
		oLFEOHKKGIP = NPCEFGPCCLG(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[5], 6);
		aJBHIPPAFIJ = NPCEFGPCCLG(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[12], 9);
		mPNNHCHGEGL = NPCEFGPCCLG(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[2], 12);
		nAHACOBOKIM = NPCEFGPCCLG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[13], 9);
		oLFEOHKKGIP = NPCEFGPCCLG(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[9], 12);
		aJBHIPPAFIJ = NPCEFGPCCLG(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[7], 5);
		mPNNHCHGEGL = NPCEFGPCCLG(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[10], 15);
		nAHACOBOKIM = NPCEFGPCCLG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[14], 8);
		aJBHIPPAFIJ += num2 + NAHACOBOKIM;
		NAHACOBOKIM = MPNNHCHGEGL + num3 + oLFEOHKKGIP;
		MPNNHCHGEGL = AJBHIPPAFIJ + mNIMEAMHNMI + nAHACOBOKIM;
		AJBHIPPAFIJ = OLFEOHKKGIP + num + mPNNHCHGEGL;
		OLFEOHKKGIP = aJBHIPPAFIJ;
		ABBPDEOGNFE = 0;
		for (int i = 0; i != CBPFFIBINEH.Length; i++)
		{
			CBPFFIBINEH[i] = 0;
		}
	}

	public override MIPBJNJHNGA FDCFKGAEJFF()
	{
		return new CONJOCHPANG(this);
	}

	public override void OMOKOKFNBKI(MIPBJNJHNGA CJHEIBNHNNE)
	{
		CONJOCHPANG lLIEHCKNJEM = (CONJOCHPANG)CJHEIBNHNNE;
		AKBPCECABIO(lLIEHCKNJEM);
	}
}
