using Spine;

public class CPCLJAHCDGN : FPOBLOBNHGG
{
	public const int JMPDFJHAGOA = 3;

	protected const int AMJGBMFEPLB = -3;

	protected const int FDLHLEJMKGA = -2;

	protected const int MPGDKPGCPNC = -1;

	protected const int CBPFFIBINEH = 1;

	protected const int MOAGLBJDKKL = 2;

	internal int DHJJGGGLNNH;

	internal float[] ENBKHCNKHCC;

	public int LLCDBBPCAND
	{
		get
		{
			return DHJJGGGLNNH;
		}
		set
		{
			DHJJGGGLNNH = value;
		}
	}

	public float[] IKOJIGLMFNG
	{
		get
		{
			return ENBKHCNKHCC;
		}
		set
		{
			ENBKHCNKHCC = value;
		}
	}

	public override int ODHLEJHEBGD
	{
		get
		{
			return 16777216 + DHJJGGGLNNH;
		}
	}

	public CPCLJAHCDGN(int IJKENLLBMOJ)
		: base(IJKENLLBMOJ)
	{
		ENBKHCNKHCC = new float[IJKENLLBMOJ * 3];
	}

	public void BCEFHMIKFDC(int JHFDIBIBCPH, float HFLODNLEGFL, float AMFCENFNAJJ, float CNLILOEEBOJ)
	{
		JHFDIBIBCPH *= 3;
		ENBKHCNKHCC[JHFDIBIBCPH] = HFLODNLEGFL;
		ENBKHCNKHCC[JHFDIBIBCPH + 1] = AMFCENFNAJJ;
		ENBKHCNKHCC[JHFDIBIBCPH + 2] = CNLILOEEBOJ;
	}

	public override void FCHLOGCODOA(GCJKICAPOFL GDNININLMFD, float CGICCPOKJHB, float HFLODNLEGFL, ExposedList<DCBJAMHBAJB> ELMIMIMBNHP, float KBKMPEOMABI, BFCFMFBHBCH IFKBABBBDJM, ODPDBCNBOAK AJLDJAHHGOJ)
	{
		NBKCFDOMAPI nBKCFDOMAPI = GDNININLMFD.LIKIOBHLHHF.Items[DHJJGGGLNNH];
		float[] eNBKHCNKHCC = ENBKHCNKHCC;
		if (HFLODNLEGFL < eNBKHCNKHCC[0])
		{
			switch (IFKBABBBDJM)
			{
			case BFCFMFBHBCH.Setup:
				nBKCFDOMAPI.AMFCENFNAJJ = nBKCFDOMAPI.MBBPBGHKLJM.AMFCENFNAJJ;
				nBKCFDOMAPI.CNLILOEEBOJ = nBKCFDOMAPI.MBBPBGHKLJM.CNLILOEEBOJ;
				break;
			case BFCFMFBHBCH.Current:
				nBKCFDOMAPI.AMFCENFNAJJ += (nBKCFDOMAPI.MBBPBGHKLJM.AMFCENFNAJJ - nBKCFDOMAPI.AMFCENFNAJJ) * KBKMPEOMABI;
				nBKCFDOMAPI.CNLILOEEBOJ += (nBKCFDOMAPI.MBBPBGHKLJM.CNLILOEEBOJ - nBKCFDOMAPI.CNLILOEEBOJ) * KBKMPEOMABI;
				break;
			}
			return;
		}
		float num;
		float num2;
		if (HFLODNLEGFL >= eNBKHCNKHCC[eNBKHCNKHCC.Length - 3])
		{
			num = eNBKHCNKHCC[eNBKHCNKHCC.Length + -2];
			num2 = eNBKHCNKHCC[eNBKHCNKHCC.Length + -1];
		}
		else
		{
			int num3 = GNGKKPOGGGM.EIAMMDBFDFO(eNBKHCNKHCC, HFLODNLEGFL, 3);
			num = eNBKHCNKHCC[num3 + -2];
			num2 = eNBKHCNKHCC[num3 + -1];
			float num4 = eNBKHCNKHCC[num3];
			float num5 = IFMKHGLKEMB(num3 / 3 - 1, 1f - (HFLODNLEGFL - num4) / (eNBKHCNKHCC[num3 + -3] - num4));
			num += (eNBKHCNKHCC[num3 + 1] - num) * num5;
			num2 += (eNBKHCNKHCC[num3 + 2] - num2) * num5;
		}
		if (IFKBABBBDJM == BFCFMFBHBCH.Setup)
		{
			nBKCFDOMAPI.AMFCENFNAJJ = nBKCFDOMAPI.MBBPBGHKLJM.AMFCENFNAJJ + num * KBKMPEOMABI;
			nBKCFDOMAPI.CNLILOEEBOJ = nBKCFDOMAPI.MBBPBGHKLJM.CNLILOEEBOJ + num2 * KBKMPEOMABI;
		}
		else
		{
			nBKCFDOMAPI.AMFCENFNAJJ += (nBKCFDOMAPI.MBBPBGHKLJM.AMFCENFNAJJ + num - nBKCFDOMAPI.AMFCENFNAJJ) * KBKMPEOMABI;
			nBKCFDOMAPI.CNLILOEEBOJ += (nBKCFDOMAPI.MBBPBGHKLJM.CNLILOEEBOJ + num2 - nBKCFDOMAPI.CNLILOEEBOJ) * KBKMPEOMABI;
		}
	}
}
