using System.IO;

public interface CPPGAJFHILC
{
	int LMDBBPLCJDM(byte[] MBBPBGHKLJM, int JBAJPGIAPFF, int EOFAGACBNFP, Stream OMCALCLJPOD);

	int ILOALOLANOL(byte[] MBBPBGHKLJM, int JBAJPGIAPFF, int EOFAGACBNFP, Stream OMCALCLJPOD);

	int DMJOJHFDLJE(string MBBPBGHKLJM, Stream OMCALCLJPOD);
}
