using System.Collections;
using System.IO;

public class DDDFEMJOONH : AKBAHAJEILE
{
	protected IAJODODPMMG AIFOKDNIJLN;

	public DDDFEMJOONH(int EBOOFBMGNDI, IList GMLLEBDADDP, int[] KJAHHLKPNIN, byte[] PFFOEKELMAF, byte[] IJDNPGHLBID)
		: base(EBOOFBMGNDI, GMLLEBDADDP, KJAHHLKPNIN, PFFOEKELMAF, IJDNPGHLBID)
	{
	}

	public override void OPECIECMFCD(OPCLIKBOHJP BGFNAKMFCHD)
	{
		if (!(BGFNAKMFCHD is IAJODODPMMG))
		{
			throw new DEIDBCPPCMB(80);
		}
		BGLKKBMEEEK(BGFNAKMFCHD.BIBHHNBEJJM);
		AIFOKDNIJLN = (IAJODODPMMG)BGFNAKMFCHD;
	}

	public override byte[] DMJCNEDKPEA()
	{
		DANGFIDLKOF dANGFIDLKOF = new DANGFIDLKOF();
		GCHEOMCMMIF = NKCEMDBADJF.KGOGEEJBEBL(COOBIGONLDK.KMLKPFPCFLA, AJMLOOJHBBO, HLPGDFLIDKC, dANGFIDLKOF);
		FBMKOGABPFL fBMKOGABPFL = KINEBFNENMB.CBMIGMCGDJL(COOBIGONLDK, AIFOKDNIJLN);
		BJLAMONNNDD bJLAMONNNDD = KINEBFNENMB.KNADNPDKLGD(fBMKOGABPFL);
		PDCALMCFKGD pDCALMCFKGD = COOBIGONLDK.HFMNBFOAPOP;
		bJLAMONNNDD.GONEEEFEDGF(pDCALMCFKGD.NIMMIFGHCAF, 0, pDCALMCFKGD.NIMMIFGHCAF.Length);
		bJLAMONNNDD.GONEEEFEDGF(pDCALMCFKGD.BKHHFBJJBAB, 0, pDCALMCFKGD.BKHHFBJJBAB.Length);
		dANGFIDLKOF.CHOLLICODBI(bJLAMONNNDD);
		byte[] aIELCDIFLFB = KDDIIEMIPKF.LCNOFBMOHHM(bJLAMONNNDD);
		byte[] pINNJBGMGOA = AIFOKDNIJLN.NPDKOKDCPAF(aIELCDIFLFB);
		NKOAICPNEJH nKOAICPNEJH = new NKOAICPNEJH(fBMKOGABPFL, pINNJBGMGOA);
		nKOAICPNEJH.LMDBBPLCJDM(dANGFIDLKOF);
		return dANGFIDLKOF.ToArray();
	}

	public override void OJGCPPFDPBN(Stream MOPCLEEGDFB)
	{
		PDCALMCFKGD bOHAELIJHGF = COOBIGONLDK.HFMNBFOAPOP;
		HPMACIICIKB hPMACIICIKB = new HPMACIICIKB();
		Stream mOPCLEEGDFB = new DKLELFJMFAA(MOPCLEEGDFB, hPMACIICIKB);
		MJDENGGDLMJ pGMJCMEMKIE = NKCEMDBADJF.BIENEPAPMJN(AJMLOOJHBBO, HLPGDFLIDKC, mOPCLEEGDFB);
		byte[] nJPMJNHGDNE = KINEBFNENMB.IEIMBOADGLL(mOPCLEEGDFB);
		NKOAICPNEJH nKOAICPNEJH = MNPNCAOHANP(MOPCLEEGDFB);
		OHPHNNNHCOO oHPHNNNHCOO = CKCBBLBAFJA(PJMPLLIKCCG, nKOAICPNEJH.GOFDFGBGLFC, bOHAELIJHGF);
		hPMACIICIKB.CNOKJEIHKJI(oHPHNNNHCOO);
		if (!oHPHNNNHCOO.HLJBBONKPDG(nKOAICPNEJH.ACMDKLDPDLB))
		{
			throw new DEIDBCPPCMB(51);
		}
		DNEOPOFKIEF = NKCEMDBADJF.LKAJBJKHDNC(NKCEMDBADJF.CLFHBFJPMGE(HLPGDFLIDKC, pGMJCMEMKIE, nJPMJNHGDNE));
	}

	public override void JNMIHCPINHE(OOKLBMMBONO FJLPCHOBGAM)
	{
		byte[] array = FJLPCHOBGAM.JBMMCGPHNBP;
		foreach (byte b in array)
		{
			if (b != 1 && b != 2 && b != 64)
			{
				throw new DEIDBCPPCMB(47);
			}
		}
	}

	public override void FBGFHDOCEOO(OPCLIKBOHJP CLBMIAJGDMO)
	{
		if (CLBMIAJGDMO is IAJODODPMMG)
		{
			return;
		}
		throw new DEIDBCPPCMB(80);
	}

	protected virtual OHPHNNNHCOO CKCBBLBAFJA(EKFAMINKCJP HCJGAPBFJEB, FBMKOGABPFL ADLMOHOLCGL, PDCALMCFKGD BOHAELIJHGF)
	{
		OHPHNNNHCOO oHPHNNNHCOO = HCJGAPBFJEB.OPKHBIHFBMM(ADLMOHOLCGL, CAACNJEGLIP);
		oHPHNNNHCOO.GONEEEFEDGF(BOHAELIJHGF.NIMMIFGHCAF, 0, BOHAELIJHGF.NIMMIFGHCAF.Length);
		oHPHNNNHCOO.GONEEEFEDGF(BOHAELIJHGF.BKHHFBJJBAB, 0, BOHAELIJHGF.BKHHFBJJBAB.Length);
		return oHPHNNNHCOO;
	}
}
