using System;
using Org.BouncyCastle.Math;

public class DEBNMAAEBAP : LNKPCJLANAO
{
	internal readonly GLFDIPNOLKN HPHBDNBJPHB;

	internal readonly GLFDIPNOLKN OKDPJHOEPBJ;

	internal readonly GLFDIPNOLKN HJMBDGKAOBP;

	public BigInteger MBIJHANOCOC
	{
		get
		{
			return HPHBDNBJPHB.DMPHAJNKNKB;
		}
	}

	public BigInteger FNPELDEHJKL
	{
		get
		{
			return OKDPJHOEPBJ.DMPHAJNKNKB;
		}
	}

	public BigInteger HBGOKILMBJG
	{
		get
		{
			return HJMBDGKAOBP.DMPHAJNKNKB;
		}
	}

	public DEBNMAAEBAP(BigInteger HPHBDNBJPHB, BigInteger OKDPJHOEPBJ, BigInteger HJMBDGKAOBP)
	{
		this.HPHBDNBJPHB = new GLFDIPNOLKN(HPHBDNBJPHB);
		this.OKDPJHOEPBJ = new GLFDIPNOLKN(OKDPJHOEPBJ);
		this.HJMBDGKAOBP = new GLFDIPNOLKN(HJMBDGKAOBP);
	}

	private DEBNMAAEBAP(ALLINHNNNJN MIABODPHOIP)
	{
		if (MIABODPHOIP.GMCGMPEEHJP != 3)
		{
			throw new ArgumentException("Bad sequence size: " + MIABODPHOIP.GMCGMPEEHJP, "seq");
		}
		HPHBDNBJPHB = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(0));
		OKDPJHOEPBJ = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(1));
		HJMBDGKAOBP = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(2));
	}

	public static DEBNMAAEBAP BJLJCGFMFOO(PAANMJLACEF NEMEKIOEOLC, bool DHGLJHFEJFL)
	{
		return BJLJCGFMFOO(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC, DHGLJHFEJFL));
	}

	public static DEBNMAAEBAP BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC == null || NEMEKIOEOLC is DEBNMAAEBAP)
		{
			return (DEBNMAAEBAP)NEMEKIOEOLC;
		}
		if (NEMEKIOEOLC is ALLINHNNNJN)
		{
			return new DEBNMAAEBAP((ALLINHNNNJN)NEMEKIOEOLC);
		}
		throw new ArgumentException("Invalid DsaParameter: " + LHFGHNFJIKM.JKHOEKAOLPM(NEMEKIOEOLC));
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		return new KOGPLMALOEH(HPHBDNBJPHB, OKDPJHOEPBJ, HJMBDGKAOBP);
	}
}
