using System.Collections;
using Org.BouncyCastle.Security;

public sealed class DEOKPGHGOPK
{
	private static readonly IDictionary NCLCMMGJEBI;

	private DEOKPGHGOPK()
	{
	}

	static DEOKPGHGOPK()
	{
		NCLCMMGJEBI = LHFGHNFJIKM.JBEOCJEMGCE();
		NCLCMMGJEBI[CDJKIICCIIF.DBHLLCIIFDE.EEFMIHDPJPG] = "HMAC-MD5";
		NCLCMMGJEBI[CDJKIICCIIF.LLBGOHKCLGA.EEFMIHDPJPG] = "HMAC-RIPEMD160";
		NCLCMMGJEBI[CDJKIICCIIF.AFFLINCOFAN.EEFMIHDPJPG] = "HMAC-SHA1";
		NCLCMMGJEBI[CDJKIICCIIF.FOJMHODPNOD.EEFMIHDPJPG] = "HMAC-TIGER";
		NCLCMMGJEBI[NLPPJKFFBON.AICOAGPOAAF.EEFMIHDPJPG] = "HMAC-SHA1";
		NCLCMMGJEBI[NLPPJKFFBON.BGMLBCKBKGB.EEFMIHDPJPG] = "HMAC-SHA224";
		NCLCMMGJEBI[NLPPJKFFBON.KMNFAGOHJJN.EEFMIHDPJPG] = "HMAC-SHA256";
		NCLCMMGJEBI[NLPPJKFFBON.CPJKKDJHFEP.EEFMIHDPJPG] = "HMAC-SHA384";
		NCLCMMGJEBI[NLPPJKFFBON.LNIGDGKBIFL.EEFMIHDPJPG] = "HMAC-SHA512";
		NCLCMMGJEBI["DES"] = "DESMAC";
		NCLCMMGJEBI["DES/CFB8"] = "DESMAC/CFB8";
		NCLCMMGJEBI["DES64"] = "DESMAC64";
		NCLCMMGJEBI["DESEDE"] = "DESEDEMAC";
		NCLCMMGJEBI[NLPPJKFFBON.OGBEMHELJNK.EEFMIHDPJPG] = "DESEDEMAC";
		NCLCMMGJEBI["DESEDE/CFB8"] = "DESEDEMAC/CFB8";
		NCLCMMGJEBI["DESISO9797MAC"] = "DESWITHISO9797";
		NCLCMMGJEBI["DESEDE64"] = "DESEDEMAC64";
		NCLCMMGJEBI["DESEDE64WITHISO7816-4PADDING"] = "DESEDEMAC64WITHISO7816-4PADDING";
		NCLCMMGJEBI["DESEDEISO9797ALG1MACWITHISO7816-4PADDING"] = "DESEDEMAC64WITHISO7816-4PADDING";
		NCLCMMGJEBI["DESEDEISO9797ALG1WITHISO7816-4PADDING"] = "DESEDEMAC64WITHISO7816-4PADDING";
		NCLCMMGJEBI["ISO9797ALG3"] = "ISO9797ALG3MAC";
		NCLCMMGJEBI["ISO9797ALG3MACWITHISO7816-4PADDING"] = "ISO9797ALG3WITHISO7816-4PADDING";
		NCLCMMGJEBI["SKIPJACK"] = "SKIPJACKMAC";
		NCLCMMGJEBI["SKIPJACK/CFB8"] = "SKIPJACKMAC/CFB8";
		NCLCMMGJEBI["IDEA"] = "IDEAMAC";
		NCLCMMGJEBI["IDEA/CFB8"] = "IDEAMAC/CFB8";
		NCLCMMGJEBI["RC2"] = "RC2MAC";
		NCLCMMGJEBI["RC2/CFB8"] = "RC2MAC/CFB8";
		NCLCMMGJEBI["RC5"] = "RC5MAC";
		NCLCMMGJEBI["RC5/CFB8"] = "RC5MAC/CFB8";
		NCLCMMGJEBI["GOST28147"] = "GOST28147MAC";
		NCLCMMGJEBI["VMPC"] = "VMPCMAC";
		NCLCMMGJEBI["VMPC-MAC"] = "VMPCMAC";
		NCLCMMGJEBI["SIPHASH"] = "SIPHASH-2-4";
		NCLCMMGJEBI["PBEWITHHMACSHA"] = "PBEWITHHMACSHA1";
		NCLCMMGJEBI["1.3.14.3.2.26"] = "PBEWITHHMACSHA1";
	}

	public static PHFBFDEAHMD JIDMPJJAOOI(KLKJHFKJLEM BDKFNEDHAOJ)
	{
		return JIDMPJJAOOI(BDKFNEDHAOJ.EEFMIHDPJPG);
	}

	public static PHFBFDEAHMD JIDMPJJAOOI(string ADLMOHOLCGL)
	{
		string text = LHFGHNFJIKM.OGLCLCODHJI(ADLMOHOLCGL);
		string text2 = (string)NCLCMMGJEBI[text];
		if (text2 == null)
		{
			text2 = text;
		}
		if (LHFGHNFJIKM.GNEPOHDBAEJ(text2, "PBEWITH"))
		{
			text2 = text2.Substring("PBEWITH".Length);
		}
		if (LHFGHNFJIKM.GNEPOHDBAEJ(text2, "HMAC"))
		{
			string aDLMOHOLCGL = ((!LHFGHNFJIKM.GNEPOHDBAEJ(text2, "HMAC-") && !LHFGHNFJIKM.GNEPOHDBAEJ(text2, "HMAC/")) ? text2.Substring(4) : text2.Substring(5));
			return new PGNLPNFKAPJ(KDDIIEMIPKF.GANMELFOOMP(aDLMOHOLCGL));
		}
		switch (text2)
		{
		case "AESCMAC":
			return new CLBBJPFKCMF(new DNMGFOKAGHE());
		case "DESMAC":
			return new GDNPKPCHNBE(new HDNPEKKELBE());
		case "DESMAC/CFB8":
			return new PCMHCLDEELO(new HDNPEKKELBE());
		case "DESMAC64":
			return new GDNPKPCHNBE(new HDNPEKKELBE(), 64);
		case "DESEDECMAC":
			return new CLBBJPFKCMF(new KAMMIHKEGPK());
		case "DESEDEMAC":
			return new GDNPKPCHNBE(new KAMMIHKEGPK());
		case "DESEDEMAC/CFB8":
			return new PCMHCLDEELO(new KAMMIHKEGPK());
		case "DESEDEMAC64":
			return new GDNPKPCHNBE(new KAMMIHKEGPK(), 64);
		case "DESEDEMAC64WITHISO7816-4PADDING":
			return new GDNPKPCHNBE(new KAMMIHKEGPK(), 64, new HCKOBAHHNFD());
		case "DESWITHISO9797":
		case "ISO9797ALG3MAC":
			return new MFHLBDKHOAM(new HDNPEKKELBE());
		case "ISO9797ALG3WITHISO7816-4PADDING":
			return new MFHLBDKHOAM(new HDNPEKKELBE(), new HCKOBAHHNFD());
		case "SKIPJACKMAC":
			return new GDNPKPCHNBE(new OCEJEDDPLOE());
		case "SKIPJACKMAC/CFB8":
			return new PCMHCLDEELO(new OCEJEDDPLOE());
		case "IDEAMAC":
			return new GDNPKPCHNBE(new EMABOFELCJN());
		case "IDEAMAC/CFB8":
			return new PCMHCLDEELO(new EMABOFELCJN());
		case "RC2MAC":
			return new GDNPKPCHNBE(new IBGFIJHNBAL());
		case "RC2MAC/CFB8":
			return new PCMHCLDEELO(new IBGFIJHNBAL());
		case "RC5MAC":
			return new GDNPKPCHNBE(new FMFNPJJEPBF());
		case "RC5MAC/CFB8":
			return new PCMHCLDEELO(new FMFNPJJEPBF());
		case "GOST28147MAC":
			return new JAPCELIIFGK();
		case "VMPCMAC":
			return new LBGLBLFLLJH();
		case "SIPHASH-2-4":
			return new INDJEDECBHE();
		default:
			throw new SecurityUtilityException("Mac " + text2 + " not recognised.");
		}
	}

	public static string JDOPPMEGEMC(KLKJHFKJLEM GDFLIKNMBCL)
	{
		return (string)NCLCMMGJEBI[GDFLIKNMBCL.EEFMIHDPJPG];
	}

	public static byte[] OFLKIODCBJJ(string ADLMOHOLCGL, IGMAJHKIIPK CILGMABNHOH, byte[] MOPCLEEGDFB)
	{
		PHFBFDEAHMD pHFBFDEAHMD = JIDMPJJAOOI(ADLMOHOLCGL);
		pHFBFDEAHMD.DIOELAHNLKJ(CILGMABNHOH);
		pHFBFDEAHMD.GONEEEFEDGF(MOPCLEEGDFB, 0, MOPCLEEGDFB.Length);
		return LCNOFBMOHHM(pHFBFDEAHMD);
	}

	public static byte[] LCNOFBMOHHM(PHFBFDEAHMD LGMMFPHDIMH)
	{
		byte[] array = new byte[LGMMFPHDIMH.BKGLOJPPBIG()];
		LGMMFPHDIMH.LCNOFBMOHHM(array, 0);
		return array;
	}

	public static byte[] LCNOFBMOHHM(PHFBFDEAHMD LGMMFPHDIMH, byte[] MOPCLEEGDFB)
	{
		LGMMFPHDIMH.GONEEEFEDGF(MOPCLEEGDFB, 0, MOPCLEEGDFB.Length);
		return LCNOFBMOHHM(LGMMFPHDIMH);
	}
}
