public interface DGCIOOEELCP
{
	string KFKMEPMEBND { get; }

	void DIOELAHNLKJ(bool MAEALKEJALK, IGMAJHKIIPK IJJHBEECMBP);

	int IBGFCPAGGON();

	int JOKDJPBGMFH();

	byte[] DPACJDFHLKB(byte[] HMFPNMDMONK, int ELICNEDIBGB, int DBGBBFPPDCE);
}
