public interface DGEFIMEIGKH
{
	void GNDAGDEMKDE(FMFLAPIFIED OEFCOJLNCKP);

	void PJMFDACDFKP(string KHAHOPFFEJO);

	void NBFDLBLONIF(string KHAHOPFFEJO);

	void JMBAINJBOEI(string KHAHOPFFEJO);

	void PKKHKAPFLGD(string KHAHOPFFEJO);

	void GPGAKDGANKF(string KHAHOPFFEJO);
}
