public class DHAJAHAODOK : LNKPCJLANAO
{
	private readonly KLKJHFKJLEM JAFLHIJPFKD;

	private readonly LNKPCJLANAO HOMONAAFMFH;

	public KLKJHFKJLEM AFIGOPJOKOL
	{
		get
		{
			return JAFLHIJPFKD;
		}
	}

	public LNKPCJLANAO IFLICJGCCNM
	{
		get
		{
			return HOMONAAFMFH;
		}
	}

	private DHAJAHAODOK(ALLINHNNNJN MIABODPHOIP)
	{
		JAFLHIJPFKD = (KLKJHFKJLEM)MIABODPHOIP.ECNCPJGHBIG(0);
		if (MIABODPHOIP.GMCGMPEEHJP > 1)
		{
			HOMONAAFMFH = ((PAANMJLACEF)MIABODPHOIP.ECNCPJGHBIG(1)).NFMFKPLPLLH();
		}
	}

	public DHAJAHAODOK(KLKJHFKJLEM JAFLHIJPFKD, LNKPCJLANAO HOMONAAFMFH)
	{
		this.JAFLHIJPFKD = JAFLHIJPFKD;
		this.HOMONAAFMFH = HOMONAAFMFH;
	}

	public static DHAJAHAODOK BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC == null)
		{
			return null;
		}
		DHAJAHAODOK dHAJAHAODOK = NEMEKIOEOLC as DHAJAHAODOK;
		if (dHAJAHAODOK != null)
		{
			return dHAJAHAODOK;
		}
		return new DHAJAHAODOK(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC));
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		DLDBGGDLOOO dLDBGGDLOOO = new DLDBGGDLOOO(JAFLHIJPFKD);
		if (HOMONAAFMFH != null)
		{
			dLDBGGDLOOO.JEACJNAKLDJ(new FOGPHMBLIMH(0, HOMONAAFMFH));
		}
		return new KBOHOKHJFBA(dLDBGGDLOOO);
	}
}
