using System.Collections.Generic;

public class DIAELPNNMEH
{
	public string NKKEKBHCFFF { get; set; }

	public string HKCNCCIAMEL { get; set; }

	public string BCJMJBCPCML { get; set; }

	public Dictionary<string, object> GGBPDOGFIJM { get; set; }

	public DIAELPNNMEH()
	{
	}

	public DIAELPNNMEH(Dictionary<string, string> KGOFCAIACFB)
	{
		if (KGOFCAIACFB != null)
		{
			NKKEKBHCFFF = FMKNBJCOMGF.NMLBPNNMFLP(KGOFCAIACFB, FMKNBJCOMGF.IKIHDNHNJMH);
			HKCNCCIAMEL = FMKNBJCOMGF.NMLBPNNMFLP(KGOFCAIACFB, FMKNBJCOMGF.LIDJAANKHHG);
			BCJMJBCPCML = FMKNBJCOMGF.NMLBPNNMFLP(KGOFCAIACFB, FMKNBJCOMGF.NMCEFJHKBMH);
			string lGMNAIAFHAH = FMKNBJCOMGF.NMLBPNNMFLP(KGOFCAIACFB, FMKNBJCOMGF.GLHPCCFHMGA);
			DPKJGBCDECA dPKJGBCDECA = EDFILMGHHDD.DHCLOMIANOE(lGMNAIAFHAH);
			if (DPKJGBCDECA.BLPPLFIKFPN(dPKJGBCDECA, null) && DPKJGBCDECA.BLPPLFIKFPN(dPKJGBCDECA.JPIHKOGIKHA, null))
			{
				GGBPDOGFIJM = new Dictionary<string, object>();
				FMKNBJCOMGF.LMHFPJICNLH(dPKJGBCDECA.JPIHKOGIKHA, GGBPDOGFIJM);
			}
		}
	}

	public DIAELPNNMEH(string HDGFMHEHJBG)
	{
		DPKJGBCDECA dPKJGBCDECA = EDFILMGHHDD.DHCLOMIANOE(HDGFMHEHJBG);
		if (!DPKJGBCDECA.OCAFFLHPIMM(dPKJGBCDECA, null))
		{
			NKKEKBHCFFF = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.IKIHDNHNJMH);
			HKCNCCIAMEL = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.LIDJAANKHHG);
			BCJMJBCPCML = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.NMCEFJHKBMH);
			DPKJGBCDECA dPKJGBCDECA2 = dPKJGBCDECA.ECNCPJGHBIG(FMKNBJCOMGF.GLHPCCFHMGA);
			if (!DPKJGBCDECA.OCAFFLHPIMM(dPKJGBCDECA2, null) && !DPKJGBCDECA.OCAFFLHPIMM(dPKJGBCDECA2.JPIHKOGIKHA, null))
			{
				GGBPDOGFIJM = new Dictionary<string, object>();
				FMKNBJCOMGF.LMHFPJICNLH(dPKJGBCDECA2.JPIHKOGIKHA, GGBPDOGFIJM);
			}
		}
	}

	public void IMMACHKDLEC(string IPBFAAFEJBC)
	{
		DPKJGBCDECA dPKJGBCDECA = EDFILMGHHDD.DHCLOMIANOE(IPBFAAFEJBC);
		if (!DPKJGBCDECA.OCAFFLHPIMM(dPKJGBCDECA, null))
		{
			GGBPDOGFIJM = new Dictionary<string, object>();
			FMKNBJCOMGF.LMHFPJICNLH(dPKJGBCDECA.JPIHKOGIKHA, GGBPDOGFIJM);
		}
	}

	public string ACGHBPBADDG()
	{
		return FMKNBJCOMGF.DPJGPBJKFJA(GGBPDOGFIJM);
	}
}
