using Org.BouncyCastle.Math;

internal class DILDIHBGDAG
{
	internal static readonly uint[] MBIJHANOCOC = new uint[7] { 4294960493u, 4294967294u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u };

	internal static readonly uint[] PKABKFGEMBB = new uint[14]
	{
		46280809u, 13606u, 1u, 0u, 0u, 0u, 0u, 4294953690u, 4294967293u, 4294967295u,
		4294967295u, 4294967295u, 4294967295u, 4294967295u
	};

	private static readonly uint[] BPGLGHCLMCD = new uint[9] { 4248686487u, 4294953689u, 4294967294u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 13605u, 2u };

	private const uint IMGACIMJBPO = uint.MaxValue;

	private const uint PPBCBABHIBL = uint.MaxValue;

	private const uint BIFDMIEAMDM = 6803u;

	public static void JEACJNAKLDJ(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		if (MADOAPNPCCB.JEACJNAKLDJ(AMFCENFNAJJ, CNLILOEEBOJ, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[6] == uint.MaxValue && MADOAPNPCCB.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(7, 6803u, IGNEOOOFEMO);
		}
	}

	public static void KGBEKKMEBCN(uint[] HGHHJPDIMCI, uint[] IKEIELCEKPD, uint[] JMNJPLAGDDJ)
	{
		if ((BCMDHIIJKJE.JEACJNAKLDJ(14, HGHHJPDIMCI, IKEIELCEKPD, JMNJPLAGDDJ) != 0 || (JMNJPLAGDDJ[13] == uint.MaxValue && BCMDHIIJKJE.CHCGDEIGIIA(14, JMNJPLAGDDJ, PKABKFGEMBB))) && BCMDHIIJKJE.MAALDEFJPJA(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.DKCBNAFCCMF(14, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void AOAINNMNBHC(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (BCMDHIIJKJE.CKIHMFAAHLM(7, AMFCENFNAJJ, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[6] == uint.MaxValue && MADOAPNPCCB.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(7, 6803u, IGNEOOOFEMO);
		}
	}

	public static uint[] HFENNGHNFLF(BigInteger AMFCENFNAJJ)
	{
		uint[] array = MADOAPNPCCB.HFENNGHNFLF(AMFCENFNAJJ);
		if (array[6] == uint.MaxValue && MADOAPNPCCB.CHCGDEIGIIA(array, MBIJHANOCOC))
		{
			MADOAPNPCCB.DKAMAFLMHEJ(MBIJHANOCOC, array);
		}
		return array;
	}

	public static void CBGFKBFBIFD(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if ((AMFCENFNAJJ[0] & 1) == 0)
		{
			BCMDHIIJKJE.POFAGJIFAIH(7, AMFCENFNAJJ, 0u, IGNEOOOFEMO);
			return;
		}
		uint fMFABAKPMLB = MADOAPNPCCB.JEACJNAKLDJ(AMFCENFNAJJ, MBIJHANOCOC, IGNEOOOFEMO);
		BCMDHIIJKJE.POFAGJIFAIH(7, IGNEOOOFEMO, fMFABAKPMLB);
	}

	public static void IBJBIGNPNEM(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = MADOAPNPCCB.DCPJKFEDHOJ();
		MADOAPNPCCB.BMEIFJDODCF(AMFCENFNAJJ, CNLILOEEBOJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
	}

	public static void OMJFFHEIEFH(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] JMNJPLAGDDJ)
	{
		if ((MADOAPNPCCB.HHMEIAJHDJM(AMFCENFNAJJ, CNLILOEEBOJ, JMNJPLAGDDJ) != 0 || (JMNJPLAGDDJ[13] == uint.MaxValue && BCMDHIIJKJE.CHCGDEIGIIA(14, JMNJPLAGDDJ, PKABKFGEMBB))) && BCMDHIIJKJE.MAALDEFJPJA(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.DKCBNAFCCMF(14, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void BHKOFHMDACN(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (MADOAPNPCCB.EJJHHCOFAAI(AMFCENFNAJJ))
		{
			MADOAPNPCCB.KEOKCFDNHPP(IGNEOOOFEMO);
		}
		else
		{
			MADOAPNPCCB.EAEONHFLEEN(MBIJHANOCOC, AMFCENFNAJJ, IGNEOOOFEMO);
		}
	}

	public static void BKCHMGKFECM(uint[] HGHHJPDIMCI, uint[] IGNEOOOFEMO)
	{
		ulong cNLILOEEBOJ = MADOAPNPCCB.FGMIACGNJLN(6803u, HGHHJPDIMCI, 7, HGHHJPDIMCI, 0, IGNEOOOFEMO, 0);
		if (MADOAPNPCCB.CDNAAKLGHLD(6803u, cNLILOEEBOJ, IGNEOOOFEMO, 0) != 0 || (IGNEOOOFEMO[6] == uint.MaxValue && MADOAPNPCCB.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(7, 6803u, IGNEOOOFEMO);
		}
	}

	public static void KKIGIOINLCI(uint AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if ((AMFCENFNAJJ != 0 && MADOAPNPCCB.KDGIJAIDNND(6803u, AMFCENFNAJJ, IGNEOOOFEMO, 0) != 0) || (IGNEOOOFEMO[6] == uint.MaxValue && MADOAPNPCCB.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(7, 6803u, IGNEOOOFEMO);
		}
	}

	public static void MIOEHGDPGAG(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = MADOAPNPCCB.DCPJKFEDHOJ();
		MADOAPNPCCB.MIOEHGDPGAG(AMFCENFNAJJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
	}

	public static void OIEFGPHNOFN(uint[] AMFCENFNAJJ, int IDHLPOFDLKJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = MADOAPNPCCB.DCPJKFEDHOJ();
		MADOAPNPCCB.MIOEHGDPGAG(AMFCENFNAJJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
		while (--IDHLPOFDLKJ > 0)
		{
			MADOAPNPCCB.MIOEHGDPGAG(IGNEOOOFEMO, array);
			BKCHMGKFECM(array, IGNEOOOFEMO);
		}
	}

	public static void FBGIHKPECCO(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		if (MADOAPNPCCB.EAEONHFLEEN(AMFCENFNAJJ, CNLILOEEBOJ, IGNEOOOFEMO) != 0)
		{
			BCMDHIIJKJE.KGIMHKMDCKA(7, 6803u, IGNEOOOFEMO);
		}
	}

	public static void OIKFFIIOCPO(uint[] HGHHJPDIMCI, uint[] IKEIELCEKPD, uint[] JMNJPLAGDDJ)
	{
		if (BCMDHIIJKJE.EAEONHFLEEN(14, HGHHJPDIMCI, IKEIELCEKPD, JMNJPLAGDDJ) != 0 && BCMDHIIJKJE.DKAMAFLMHEJ(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.MEJBLKJLLNK(14, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void LLGLJBDLBOP(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (BCMDHIIJKJE.FKEFFJALNJM(7, AMFCENFNAJJ, 0u, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[6] == uint.MaxValue && MADOAPNPCCB.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(7, 6803u, IGNEOOOFEMO);
		}
	}
}
