using System;
using Org.BouncyCastle.Math;

public abstract class DJABAMMOHPF : BHPIABAGAPB
{
	private BigInteger[] BBHFBHMLHPN;

	public virtual bool FNJONABMLNB
	{
		get
		{
			return NNGLKCDBIBE != null && LDKJJAOPAAP != null && MPDGCILOEML.EOJCHPEGABD && (CFJANGMBPML.EJJHHCOFAAI || CFJANGMBPML.EOJCHPEGABD);
		}
	}

	protected DJABAMMOHPF(int CEKMAJAHNAG, int KDFFDKFCDKK, int FKOBMEPIABG, int KHNDCPCHOEM)
		: base(OHJGCPPFBDO(CEKMAJAHNAG, KDFFDKFCDKK, FKOBMEPIABG, KHNDCPCHOEM))
	{
	}

	public static BigInteger NFKPBIPAALO(int CEKMAJAHNAG, int[] APIJJGNJKNF, BigInteger AMFCENFNAJJ)
	{
		return new IOPFKLMMOOP(AMFCENFNAJJ).DDENLEMHHAM(CEKMAJAHNAG, APIJJGNJKNF).DOJBPIFPALJ();
	}

	private static AGBPCEHDLOH OHJGCPPFBDO(int CEKMAJAHNAG, int KDFFDKFCDKK, int FKOBMEPIABG, int KHNDCPCHOEM)
	{
		if (KDFFDKFCDKK == 0)
		{
			throw new ArgumentException("k1 must be > 0");
		}
		if (FKOBMEPIABG == 0)
		{
			if (KHNDCPCHOEM != 0)
			{
				throw new ArgumentException("k3 must be 0 if k2 == 0");
			}
			return FGALCADFLCL.AKPPBGAEPAL(new int[3] { 0, KDFFDKFCDKK, CEKMAJAHNAG });
		}
		if (FKOBMEPIABG <= KDFFDKFCDKK)
		{
			throw new ArgumentException("k2 must be > k1");
		}
		if (KHNDCPCHOEM <= FKOBMEPIABG)
		{
			throw new ArgumentException("k3 must be > k2");
		}
		return FGALCADFLCL.AKPPBGAEPAL(new int[5] { 0, KDFFDKFCDKK, FKOBMEPIABG, KHNDCPCHOEM, CEKMAJAHNAG });
	}

	public override bool DBFKLCPIHOI(BigInteger AMFCENFNAJJ)
	{
		return AMFCENFNAJJ != null && AMFCENFNAJJ.SignValue >= 0 && AMFCENFNAJJ.BitLength <= PJNLBAHOKGC;
	}

	public override JGAFKLGGBGF IIDKCEOFIBH(BigInteger AMFCENFNAJJ, BigInteger CNLILOEEBOJ, bool HPGABKNMEAG)
	{
		KBINBLGGLNE kBINBLGGLNE = HFENNGHNFLF(AMFCENFNAJJ);
		KBINBLGGLNE kBINBLGGLNE2 = HFENNGHNFLF(CNLILOEEBOJ);
		int num = DHBHKHGFIKI;
		if (num == 5 || num == 6)
		{
			if (kBINBLGGLNE.EJJHHCOFAAI)
			{
				if (!kBINBLGGLNE2.MIOEHGDPGAG().KIFDKLPDKMD(FPKDKHJKEEF))
				{
					throw new ArgumentException();
				}
			}
			else
			{
				kBINBLGGLNE2 = kBINBLGGLNE2.MCPDGENJCDB(kBINBLGGLNE).JEACJNAKLDJ(kBINBLGGLNE);
			}
		}
		return IMOPAOHAOAN(kBINBLGGLNE, kBINBLGGLNE2, HPGABKNMEAG);
	}

	protected override JGAFKLGGBGF FMLLIJEENJJ(int ICNNEMMNLHC, BigInteger JCJOMANHEBB)
	{
		KBINBLGGLNE kBINBLGGLNE = HFENNGHNFLF(JCJOMANHEBB);
		KBINBLGGLNE kBINBLGGLNE2 = null;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			kBINBLGGLNE2 = FPKDKHJKEEF.PAEDNKEIDOM();
		}
		else
		{
			KBINBLGGLNE iFGAEKDPMJG = kBINBLGGLNE.MIOEHGDPGAG().LEIECFOMCNL().IBJBIGNPNEM(FPKDKHJKEEF)
				.JEACJNAKLDJ(JEHECJGFJEB)
				.JEACJNAKLDJ(kBINBLGGLNE);
			KBINBLGGLNE kBINBLGGLNE3 = FCDLDKBFPMB(iFGAEKDPMJG);
			if (kBINBLGGLNE3 != null)
			{
				if (kBINBLGGLNE3.OFGNPBCCHAA() != (ICNNEMMNLHC == 1))
				{
					kBINBLGGLNE3 = kBINBLGGLNE3.AOAINNMNBHC();
				}
				int num = DHBHKHGFIKI;
				kBINBLGGLNE2 = ((num != 5 && num != 6) ? kBINBLGGLNE3.IBJBIGNPNEM(kBINBLGGLNE) : kBINBLGGLNE3.JEACJNAKLDJ(kBINBLGGLNE));
			}
		}
		if (kBINBLGGLNE2 == null)
		{
			throw new ArgumentException("Invalid point compression");
		}
		return IMOPAOHAOAN(kBINBLGGLNE, kBINBLGGLNE2, true);
	}

	private KBINBLGGLNE FCDLDKBFPMB(KBINBLGGLNE IFGAEKDPMJG)
	{
		if (IFGAEKDPMJG.EJJHHCOFAAI)
		{
			return IFGAEKDPMJG;
		}
		KBINBLGGLNE kBINBLGGLNE = HFENNGHNFLF(BigInteger.Zero);
		int num = PJNLBAHOKGC;
		KBINBLGGLNE kBINBLGGLNE2;
		KBINBLGGLNE kBINBLGGLNE5;
		do
		{
			KBINBLGGLNE bCIHLCMFAEK = HFENNGHNFLF(BigInteger.HHFOMHMDAKH(num));
			kBINBLGGLNE2 = kBINBLGGLNE;
			KBINBLGGLNE kBINBLGGLNE3 = IFGAEKDPMJG;
			for (int i = 1; i < num; i++)
			{
				KBINBLGGLNE kBINBLGGLNE4 = kBINBLGGLNE3.MIOEHGDPGAG();
				kBINBLGGLNE2 = kBINBLGGLNE2.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE4.IBJBIGNPNEM(bCIHLCMFAEK));
				kBINBLGGLNE3 = kBINBLGGLNE4.JEACJNAKLDJ(IFGAEKDPMJG);
			}
			if (!kBINBLGGLNE3.EJJHHCOFAAI)
			{
				return null;
			}
			kBINBLGGLNE5 = kBINBLGGLNE2.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE2);
		}
		while (kBINBLGGLNE5.EJJHHCOFAAI);
		return kBINBLGGLNE2;
	}

	internal virtual BigInteger[] GIFOICAMFFP()
	{
		if (BBHFBHMLHPN == null)
		{
			lock (this)
			{
				if (BBHFBHMLHPN == null)
				{
					BBHFBHMLHPN = NNAJFEGEGMI.GIFOICAMFFP(this);
				}
			}
		}
		return BBHFBHMLHPN;
	}
}
