public class DJBJCHEAMKF : HPBPDALECOG
{
	private readonly CLBPDHGBHML IJJHBEECMBP;

	public CLBPDHGBHML KPJHHAAOFOH
	{
		get
		{
			return IJJHBEECMBP;
		}
	}

	public DJBJCHEAMKF(FBIJJFGLKMK GECCLOFELEC, CLBPDHGBHML IJJHBEECMBP)
		: base(GECCLOFELEC, APFAHJCEOBO(IJJHBEECMBP))
	{
		this.IJJHBEECMBP = IJJHBEECMBP;
	}

	internal static int APFAHJCEOBO(CLBPDHGBHML IJJHBEECMBP)
	{
		return (IJJHBEECMBP.NBFDOJDLKOG == 0) ? IJJHBEECMBP.MBIJHANOCOC.BitLength : IJJHBEECMBP.NBFDOJDLKOG;
	}
}
