public abstract class DJCFGMFFILH
{
	protected EDOEBJJFOBM PNEEBHLAADI(string PLEGDJKNGEM, int IBNDGNOIEEF)
	{
		string mBBPBGHKLJM = PLEGDJKNGEM.Substring(IBNDGNOIEEF);
		return EDOEBJJFOBM.HPDCKMOPEMM(DCDJMDOEKHC.ILOALOLANOL(mBBPBGHKLJM));
	}

	protected bool GAEJLNDKOLC(string GFPBBLPMOOL)
	{
		return JLGEDJAOAIJ.NOCNDAGADMM(GFPBBLPMOOL);
	}

	public abstract EDOEBJJFOBM KCGBGKNFEHK(KLKJHFKJLEM GDFLIKNMBCL, string EDDNOJDPMCF);
}
