using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

public class DKBEJLGEAOA : MGAOAPKCDHP
{
	[CompilerGenerated]
	private sealed class EPLEDJOLOPO
	{
		internal long GPJDJCGDJDC;

		internal void AGFNGEFDHLA(AKGIJAMHMNA IBBBMACIBGK)
		{
			if (IBBBMACIBGK.KEMNAAPNAPA != GPJDJCGDJDC)
			{
				IBBBMACIBGK.KEMNAAPNAPA = GPJDJCGDJDC;
				IBBBMACIBGK.KFBCFDALGBB = 0L;
			}
		}
	}

	public long EEFMIHDPJPG;

	public string PNGPLGHKFDI;

	public string MMONLGJNACB;

	public string NKOHDLBCJBK;

	public long GMCGMPEEHJP;

	public long AFPDGDAEENM;

	public long KOPMPMIFHNF;

	public string FGPGOGEKDAM;

	public bool IHLIGFJLDLJ;

	public Dictionary<long, AKGIJAMHMNA> HOINIMJNGFK;

	public Dictionary<long, NBBAAJENFFN> MCDNAIGOMAK;

	public long KEMNAAPNAPA;

	public int PDHFJLNGDOL;

	public long AKNLLPAHFOK;

	[CompilerGenerated]
	private static Func<AKGIJAMHMNA, long> EBCOMJBLIPP;

	public DKBEJLGEAOA(Dictionary<string, object> EAPGOBAJLJE)
	{
		EEFMIHDPJPG = MGAOAPKCDHP.EICLJDHEHHP("id", EAPGOBAJLJE, 0L);
		PNGPLGHKFDI = MGAOAPKCDHP.JDANMONKNGD("name", EAPGOBAJLJE);
		MMONLGJNACB = MGAOAPKCDHP.JDANMONKNGD("desc", EAPGOBAJLJE);
		NKOHDLBCJBK = MGAOAPKCDHP.JDANMONKNGD("country", EAPGOBAJLJE);
		GMCGMPEEHJP = MGAOAPKCDHP.EICLJDHEHHP("count", EAPGOBAJLJE, 0L);
		AFPDGDAEENM = MGAOAPKCDHP.EICLJDHEHHP("manager", EAPGOBAJLJE, 0L);
		KOPMPMIFHNF = MGAOAPKCDHP.EICLJDHEHHP("level", EAPGOBAJLJE, 0L);
		FGPGOGEKDAM = MGAOAPKCDHP.JDANMONKNGD("badge", EAPGOBAJLJE);
		IHLIGFJLDLJ = MGAOAPKCDHP.EICLJDHEHHP("closed", EAPGOBAJLJE, 0L) == 1;
		KEMNAAPNAPA = MGAOAPKCDHP.EICLJDHEHHP("helpWeek", EAPGOBAJLJE, 0L);
		HOINIMJNGFK = MGAOAPKCDHP.EFEKGCOJIFA("loadedUsers", EAPGOBAJLJE);
		List<AKGIJAMHMNA> list = new List<AKGIJAMHMNA>(HOINIMJNGFK.Values);
		long GPJDJCGDJDC = list.Max((AKGIJAMHMNA IBBBMACIBGK) => IBBBMACIBGK.KEMNAAPNAPA);
		list.ForEach(delegate(AKGIJAMHMNA IBBBMACIBGK)
		{
			if (IBBBMACIBGK.KEMNAAPNAPA != GPJDJCGDJDC)
			{
				IBBBMACIBGK.KEMNAAPNAPA = GPJDJCGDJDC;
				IBBBMACIBGK.KFBCFDALGBB = 0L;
			}
		});
		MCDNAIGOMAK = MGAOAPKCDHP.ACFBICEMOOF("loadedHelps", EAPGOBAJLJE);
		AKNLLPAHFOK = MGAOAPKCDHP.EICLJDHEHHP("helpCount", EAPGOBAJLJE, 0L);
	}

	public void BHBHEIAPLMK(long BPKJLGJDFKG)
	{
		HOINIMJNGFK.Remove(BPKJLGJDFKG);
	}

	public override string ToString()
	{
		return string.Format("Team:  Id: {0}, Name: {1}, Desc: {2}, Country: {3}, Count: {4}, Manager: {5}, Level: {6}, Badge: {7}, Closed: {8}, HelpWeek {9}", EEFMIHDPJPG, PNGPLGHKFDI, MMONLGJNACB, NKOHDLBCJBK, GMCGMPEEHJP, AFPDGDAEENM, KOPMPMIFHNF, FGPGOGEKDAM, IHLIGFJLDLJ, KEMNAAPNAPA);
	}

	[CompilerGenerated]
	private static long CONIMPFMNEN(AKGIJAMHMNA IBBBMACIBGK)
	{
		return IBBBMACIBGK.KEMNAAPNAPA;
	}
}
