using Spine;

public class DKEAHBHKOLB : FPOBLOBNHGG
{
	public const int JMPDFJHAGOA = 3;

	private const int AMJGBMFEPLB = -3;

	private const int NHNFFOOGFEJ = -2;

	private const int FEMHKDMOBHO = -1;

	private const int HIDGDOABAAF = 1;

	private const int CCCOFDMBHCJ = 2;

	internal int CFOGCDKFLIH;

	internal float[] ENBKHCNKHCC;

	public int IEJCFPCBKCA
	{
		get
		{
			return CFOGCDKFLIH;
		}
		set
		{
			CFOGCDKFLIH = value;
		}
	}

	public float[] IKOJIGLMFNG
	{
		get
		{
			return ENBKHCNKHCC;
		}
		set
		{
			ENBKHCNKHCC = value;
		}
	}

	public override int ODHLEJHEBGD
	{
		get
		{
			return 218103808 + CFOGCDKFLIH;
		}
	}

	public DKEAHBHKOLB(int IJKENLLBMOJ)
		: base(IJKENLLBMOJ)
	{
		ENBKHCNKHCC = new float[IJKENLLBMOJ * 3];
	}

	public void BCEFHMIKFDC(int JHFDIBIBCPH, float HFLODNLEGFL, float OIBAIJIPGOM, float DHNKOEMONHP)
	{
		JHFDIBIBCPH *= 3;
		ENBKHCNKHCC[JHFDIBIBCPH] = HFLODNLEGFL;
		ENBKHCNKHCC[JHFDIBIBCPH + 1] = OIBAIJIPGOM;
		ENBKHCNKHCC[JHFDIBIBCPH + 2] = DHNKOEMONHP;
	}

	public override void FCHLOGCODOA(GCJKICAPOFL GDNININLMFD, float CGICCPOKJHB, float HFLODNLEGFL, ExposedList<DCBJAMHBAJB> ELMIMIMBNHP, float KBKMPEOMABI, BFCFMFBHBCH IFKBABBBDJM, ODPDBCNBOAK AJLDJAHHGOJ)
	{
		KNKKDGIBGLM kNKKDGIBGLM = GDNININLMFD.NDOOCKKIMHO.Items[CFOGCDKFLIH];
		float[] eNBKHCNKHCC = ENBKHCNKHCC;
		if (HFLODNLEGFL < eNBKHCNKHCC[0])
		{
			switch (IFKBABBBDJM)
			{
			case BFCFMFBHBCH.Setup:
				kNKKDGIBGLM.OIBAIJIPGOM = kNKKDGIBGLM.MBBPBGHKLJM.OIBAIJIPGOM;
				kNKKDGIBGLM.DHNKOEMONHP = kNKKDGIBGLM.MBBPBGHKLJM.DHNKOEMONHP;
				break;
			case BFCFMFBHBCH.Current:
				kNKKDGIBGLM.OIBAIJIPGOM += (kNKKDGIBGLM.MBBPBGHKLJM.OIBAIJIPGOM - kNKKDGIBGLM.OIBAIJIPGOM) * KBKMPEOMABI;
				kNKKDGIBGLM.DHNKOEMONHP += (kNKKDGIBGLM.MBBPBGHKLJM.DHNKOEMONHP - kNKKDGIBGLM.DHNKOEMONHP) * KBKMPEOMABI;
				break;
			}
			return;
		}
		float num;
		float num2;
		if (HFLODNLEGFL >= eNBKHCNKHCC[eNBKHCNKHCC.Length - 3])
		{
			num = eNBKHCNKHCC[eNBKHCNKHCC.Length + -2];
			num2 = eNBKHCNKHCC[eNBKHCNKHCC.Length + -1];
		}
		else
		{
			int num3 = GNGKKPOGGGM.EIAMMDBFDFO(eNBKHCNKHCC, HFLODNLEGFL, 3);
			num = eNBKHCNKHCC[num3 + -2];
			num2 = eNBKHCNKHCC[num3 + -1];
			float num4 = eNBKHCNKHCC[num3];
			float num5 = IFMKHGLKEMB(num3 / 3 - 1, 1f - (HFLODNLEGFL - num4) / (eNBKHCNKHCC[num3 + -3] - num4));
			num += (eNBKHCNKHCC[num3 + 1] - num) * num5;
			num2 += (eNBKHCNKHCC[num3 + 2] - num2) * num5;
		}
		if (IFKBABBBDJM == BFCFMFBHBCH.Setup)
		{
			kNKKDGIBGLM.OIBAIJIPGOM = kNKKDGIBGLM.MBBPBGHKLJM.OIBAIJIPGOM + (num - kNKKDGIBGLM.MBBPBGHKLJM.OIBAIJIPGOM) * KBKMPEOMABI;
			kNKKDGIBGLM.DHNKOEMONHP = kNKKDGIBGLM.MBBPBGHKLJM.DHNKOEMONHP + (num2 - kNKKDGIBGLM.MBBPBGHKLJM.DHNKOEMONHP) * KBKMPEOMABI;
		}
		else
		{
			kNKKDGIBGLM.OIBAIJIPGOM += (num - kNKKDGIBGLM.OIBAIJIPGOM) * KBKMPEOMABI;
			kNKKDGIBGLM.DHNKOEMONHP += (num2 - kNKKDGIBGLM.DHNKOEMONHP) * KBKMPEOMABI;
		}
	}
}
