using System;
using Spine;

public class DKOKKMLGGJI : FPOBLOBNHGG
{
	public const int JMPDFJHAGOA = 8;

	protected const int AMJGBMFEPLB = -8;

	protected const int DGDAHGJMLDC = -7;

	protected const int AKBCENGCHLC = -6;

	protected const int EOHKIJCGNNH = -5;

	protected const int BCJOFFNPHEC = -4;

	protected const int HIPOBENDCFA = -3;

	protected const int DCNAMEJBLBA = -2;

	protected const int OGNJBFNEACI = -1;

	protected const int GOEFJMNOBHA = 1;

	protected const int HBGOKILMBJG = 2;

	protected const int FPKDKHJKEEF = 3;

	protected const int JEHECJGFJEB = 4;

	protected const int HNHLEKDNBDN = 5;

	protected const int ACBLCPEFOMO = 6;

	protected const int IBFEPDEPOKB = 7;

	internal float[] ENBKHCNKHCC;

	internal int PBPEMFGPGFC;

	public float[] IKOJIGLMFNG
	{
		get
		{
			return ENBKHCNKHCC;
		}
	}

	public int ONPPEPBHGCK
	{
		get
		{
			return PBPEMFGPGFC;
		}
		set
		{
			if (value < 0)
			{
				throw new ArgumentOutOfRangeException("index must be >= 0.");
			}
			PBPEMFGPGFC = value;
		}
	}

	public override int ODHLEJHEBGD
	{
		get
		{
			return 234881024 + PBPEMFGPGFC;
		}
	}

	public DKOKKMLGGJI(int IJKENLLBMOJ)
		: base(IJKENLLBMOJ)
	{
		ENBKHCNKHCC = new float[IJKENLLBMOJ * 8];
	}

	public void BCEFHMIKFDC(int JHFDIBIBCPH, float HFLODNLEGFL, float GPGDCCMECGF, float HJMBDGKAOBP, float BCIHLCMFAEK, float MNIMEAMHNMI, float FHPFAEDHEGG, float AONHFIBNFLD, float DLGDBCBCIED)
	{
		JHFDIBIBCPH *= 8;
		ENBKHCNKHCC[JHFDIBIBCPH] = HFLODNLEGFL;
		ENBKHCNKHCC[JHFDIBIBCPH + 1] = GPGDCCMECGF;
		ENBKHCNKHCC[JHFDIBIBCPH + 2] = HJMBDGKAOBP;
		ENBKHCNKHCC[JHFDIBIBCPH + 3] = BCIHLCMFAEK;
		ENBKHCNKHCC[JHFDIBIBCPH + 4] = MNIMEAMHNMI;
		ENBKHCNKHCC[JHFDIBIBCPH + 5] = FHPFAEDHEGG;
		ENBKHCNKHCC[JHFDIBIBCPH + 6] = AONHFIBNFLD;
		ENBKHCNKHCC[JHFDIBIBCPH + 7] = DLGDBCBCIED;
	}

	public override void FCHLOGCODOA(GCJKICAPOFL GDNININLMFD, float CGICCPOKJHB, float HFLODNLEGFL, ExposedList<DCBJAMHBAJB> ELMIMIMBNHP, float KBKMPEOMABI, BFCFMFBHBCH IFKBABBBDJM, ODPDBCNBOAK AJLDJAHHGOJ)
	{
		LBBAMMPJKDA lBBAMMPJKDA = GDNININLMFD.MAKCMFCFDLP.Items[PBPEMFGPGFC];
		float[] eNBKHCNKHCC = ENBKHCNKHCC;
		if (HFLODNLEGFL < eNBKHCNKHCC[0])
		{
			HMGLMNHOBHA mBBPBGHKLJM = lBBAMMPJKDA.MBBPBGHKLJM;
			switch (IFKBABBBDJM)
			{
			case BFCFMFBHBCH.Setup:
				lBBAMMPJKDA.GPGDCCMECGF = mBBPBGHKLJM.GPGDCCMECGF;
				lBBAMMPJKDA.HJMBDGKAOBP = mBBPBGHKLJM.HJMBDGKAOBP;
				lBBAMMPJKDA.BCIHLCMFAEK = mBBPBGHKLJM.BCIHLCMFAEK;
				lBBAMMPJKDA.MNIMEAMHNMI = mBBPBGHKLJM.MNIMEAMHNMI;
				lBBAMMPJKDA.FHPFAEDHEGG = mBBPBGHKLJM.FHPFAEDHEGG;
				lBBAMMPJKDA.AONHFIBNFLD = mBBPBGHKLJM.AONHFIBNFLD;
				lBBAMMPJKDA.DLGDBCBCIED = mBBPBGHKLJM.DLGDBCBCIED;
				break;
			case BFCFMFBHBCH.Current:
				lBBAMMPJKDA.GPGDCCMECGF += (lBBAMMPJKDA.GPGDCCMECGF - mBBPBGHKLJM.GPGDCCMECGF) * KBKMPEOMABI;
				lBBAMMPJKDA.HJMBDGKAOBP += (lBBAMMPJKDA.HJMBDGKAOBP - mBBPBGHKLJM.HJMBDGKAOBP) * KBKMPEOMABI;
				lBBAMMPJKDA.BCIHLCMFAEK += (lBBAMMPJKDA.BCIHLCMFAEK - mBBPBGHKLJM.BCIHLCMFAEK) * KBKMPEOMABI;
				lBBAMMPJKDA.MNIMEAMHNMI += (lBBAMMPJKDA.MNIMEAMHNMI - mBBPBGHKLJM.MNIMEAMHNMI) * KBKMPEOMABI;
				lBBAMMPJKDA.FHPFAEDHEGG += (lBBAMMPJKDA.FHPFAEDHEGG - mBBPBGHKLJM.FHPFAEDHEGG) * KBKMPEOMABI;
				lBBAMMPJKDA.AONHFIBNFLD += (lBBAMMPJKDA.AONHFIBNFLD - mBBPBGHKLJM.AONHFIBNFLD) * KBKMPEOMABI;
				lBBAMMPJKDA.DLGDBCBCIED += (lBBAMMPJKDA.DLGDBCBCIED - mBBPBGHKLJM.DLGDBCBCIED) * KBKMPEOMABI;
				break;
			}
			return;
		}
		float num2;
		float num3;
		float num4;
		float num5;
		float num6;
		float num7;
		float num8;
		if (HFLODNLEGFL >= eNBKHCNKHCC[eNBKHCNKHCC.Length - 8])
		{
			int num = eNBKHCNKHCC.Length;
			num2 = eNBKHCNKHCC[num + -7];
			num3 = eNBKHCNKHCC[num + -6];
			num4 = eNBKHCNKHCC[num + -5];
			num5 = eNBKHCNKHCC[num + -4];
			num6 = eNBKHCNKHCC[num + -3];
			num7 = eNBKHCNKHCC[num + -2];
			num8 = eNBKHCNKHCC[num + -1];
		}
		else
		{
			int num9 = GNGKKPOGGGM.EIAMMDBFDFO(eNBKHCNKHCC, HFLODNLEGFL, 8);
			num2 = eNBKHCNKHCC[num9 + -7];
			num3 = eNBKHCNKHCC[num9 + -6];
			num4 = eNBKHCNKHCC[num9 + -5];
			num5 = eNBKHCNKHCC[num9 + -4];
			num6 = eNBKHCNKHCC[num9 + -3];
			num7 = eNBKHCNKHCC[num9 + -2];
			num8 = eNBKHCNKHCC[num9 + -1];
			float num10 = eNBKHCNKHCC[num9];
			float num11 = IFMKHGLKEMB(num9 / 8 - 1, 1f - (HFLODNLEGFL - num10) / (eNBKHCNKHCC[num9 + -8] - num10));
			num2 += (eNBKHCNKHCC[num9 + 1] - num2) * num11;
			num3 += (eNBKHCNKHCC[num9 + 2] - num3) * num11;
			num4 += (eNBKHCNKHCC[num9 + 3] - num4) * num11;
			num5 += (eNBKHCNKHCC[num9 + 4] - num5) * num11;
			num6 += (eNBKHCNKHCC[num9 + 5] - num6) * num11;
			num7 += (eNBKHCNKHCC[num9 + 6] - num7) * num11;
			num8 += (eNBKHCNKHCC[num9 + 7] - num8) * num11;
		}
		if (KBKMPEOMABI == 1f)
		{
			lBBAMMPJKDA.GPGDCCMECGF = num2;
			lBBAMMPJKDA.HJMBDGKAOBP = num3;
			lBBAMMPJKDA.BCIHLCMFAEK = num4;
			lBBAMMPJKDA.MNIMEAMHNMI = num5;
			lBBAMMPJKDA.FHPFAEDHEGG = num6;
			lBBAMMPJKDA.AONHFIBNFLD = num7;
			lBBAMMPJKDA.DLGDBCBCIED = num8;
			return;
		}
		float gPGDCCMECGF;
		float hJMBDGKAOBP;
		float bCIHLCMFAEK;
		float mNIMEAMHNMI;
		float fHPFAEDHEGG;
		float aONHFIBNFLD;
		float dLGDBCBCIED;
		if (IFKBABBBDJM == BFCFMFBHBCH.Setup)
		{
			gPGDCCMECGF = lBBAMMPJKDA.MBBPBGHKLJM.GPGDCCMECGF;
			hJMBDGKAOBP = lBBAMMPJKDA.MBBPBGHKLJM.HJMBDGKAOBP;
			bCIHLCMFAEK = lBBAMMPJKDA.MBBPBGHKLJM.BCIHLCMFAEK;
			mNIMEAMHNMI = lBBAMMPJKDA.MBBPBGHKLJM.MNIMEAMHNMI;
			fHPFAEDHEGG = lBBAMMPJKDA.MBBPBGHKLJM.FHPFAEDHEGG;
			aONHFIBNFLD = lBBAMMPJKDA.MBBPBGHKLJM.AONHFIBNFLD;
			dLGDBCBCIED = lBBAMMPJKDA.MBBPBGHKLJM.DLGDBCBCIED;
		}
		else
		{
			gPGDCCMECGF = lBBAMMPJKDA.GPGDCCMECGF;
			hJMBDGKAOBP = lBBAMMPJKDA.HJMBDGKAOBP;
			bCIHLCMFAEK = lBBAMMPJKDA.BCIHLCMFAEK;
			mNIMEAMHNMI = lBBAMMPJKDA.MNIMEAMHNMI;
			fHPFAEDHEGG = lBBAMMPJKDA.FHPFAEDHEGG;
			aONHFIBNFLD = lBBAMMPJKDA.AONHFIBNFLD;
			dLGDBCBCIED = lBBAMMPJKDA.DLGDBCBCIED;
		}
		lBBAMMPJKDA.GPGDCCMECGF = gPGDCCMECGF + (num2 - gPGDCCMECGF) * KBKMPEOMABI;
		lBBAMMPJKDA.HJMBDGKAOBP = hJMBDGKAOBP + (num3 - hJMBDGKAOBP) * KBKMPEOMABI;
		lBBAMMPJKDA.BCIHLCMFAEK = bCIHLCMFAEK + (num4 - bCIHLCMFAEK) * KBKMPEOMABI;
		lBBAMMPJKDA.MNIMEAMHNMI = mNIMEAMHNMI + (num5 - mNIMEAMHNMI) * KBKMPEOMABI;
		lBBAMMPJKDA.FHPFAEDHEGG = fHPFAEDHEGG + (num6 - fHPFAEDHEGG) * KBKMPEOMABI;
		lBBAMMPJKDA.AONHFIBNFLD = aONHFIBNFLD + (num7 - aONHFIBNFLD) * KBKMPEOMABI;
		lBBAMMPJKDA.DLGDBCBCIED = dLGDBCBCIED + (num8 - dLGDBCBCIED) * KBKMPEOMABI;
	}
}
