public class DNKGIMHJLAD : NADPOFCHCON
{
	public DNKGIMHJLAD(IKDMCJPBBIH KAGBOIDKAED, GBJNCLLOCJB KFNJHBPIHOI)
		: base(KAGBOIDKAED, KFNJHBPIHOI)
	{
	}

	public override void JLECFJEAFCD()
	{
		AAPMDEEMEMM.LLOONDAAAEK();
	}
}
