public class DOKOCOIBGMK : HPBPDALECOG
{
	private readonly CFBBJKGJFPE IJJHBEECMBP;

	public CFBBJKGJFPE KPJHHAAOFOH
	{
		get
		{
			return IJJHBEECMBP;
		}
	}

	public DOKOCOIBGMK(FBIJJFGLKMK GECCLOFELEC, CFBBJKGJFPE IJJHBEECMBP)
		: base(GECCLOFELEC, APFAHJCEOBO(IJJHBEECMBP))
	{
		this.IJJHBEECMBP = IJJHBEECMBP;
	}

	internal static int APFAHJCEOBO(CFBBJKGJFPE IJJHBEECMBP)
	{
		return (IJJHBEECMBP.NBFDOJDLKOG == 0) ? IJJHBEECMBP.MBIJHANOCOC.BitLength : IJJHBEECMBP.NBFDOJDLKOG;
	}
}
