using System;

internal class DOMJIBIBDDP : OMOBJNLGOBO
{
	public DOMJIBIBDDP(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public DOMJIBIBDDP(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal DOMJIBIBDDP(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new DOMJIBIBDDP(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		IKBHHNIGFHL iKBHHNIGFHL = (IKBHHNIGFHL)base.NBPANDNEJGI;
		IKBHHNIGFHL iKBHHNIGFHL2 = (IKBHHNIGFHL)base.FIJLKLCHMGH;
		IKBHHNIGFHL iKBHHNIGFHL3 = (IKBHHNIGFHL)BCIHLCMFAEK.NBPANDNEJGI;
		IKBHHNIGFHL iKBHHNIGFHL4 = (IKBHHNIGFHL)BCIHLCMFAEK.FIJLKLCHMGH;
		IKBHHNIGFHL iKBHHNIGFHL5 = (IKBHHNIGFHL)base.LAMGGDKLPJH[0];
		IKBHHNIGFHL iKBHHNIGFHL6 = (IKBHHNIGFHL)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = MADOAPNPCCB.DCPJKFEDHOJ();
		uint[] array2 = MADOAPNPCCB.PLIFFMMBNPM();
		uint[] array3 = MADOAPNPCCB.PLIFFMMBNPM();
		uint[] array4 = MADOAPNPCCB.PLIFFMMBNPM();
		bool flag = iKBHHNIGFHL5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = iKBHHNIGFHL3.AMFCENFNAJJ;
			array6 = iKBHHNIGFHL4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			ADLDIDKJJFG.MIOEHGDPGAG(iKBHHNIGFHL5.AMFCENFNAJJ, array6);
			array5 = array2;
			ADLDIDKJJFG.IBJBIGNPNEM(array6, iKBHHNIGFHL3.AMFCENFNAJJ, array5);
			ADLDIDKJJFG.IBJBIGNPNEM(array6, iKBHHNIGFHL5.AMFCENFNAJJ, array6);
			ADLDIDKJJFG.IBJBIGNPNEM(array6, iKBHHNIGFHL4.AMFCENFNAJJ, array6);
		}
		bool flag2 = iKBHHNIGFHL6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = iKBHHNIGFHL.AMFCENFNAJJ;
			array8 = iKBHHNIGFHL2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			ADLDIDKJJFG.MIOEHGDPGAG(iKBHHNIGFHL6.AMFCENFNAJJ, array8);
			array7 = array;
			ADLDIDKJJFG.IBJBIGNPNEM(array8, iKBHHNIGFHL.AMFCENFNAJJ, array7);
			ADLDIDKJJFG.IBJBIGNPNEM(array8, iKBHHNIGFHL6.AMFCENFNAJJ, array8);
			ADLDIDKJJFG.IBJBIGNPNEM(array8, iKBHHNIGFHL2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		ADLDIDKJJFG.FBGIHKPECCO(array8, array6, array10);
		if (MADOAPNPCCB.EJJHHCOFAAI(array9))
		{
			if (MADOAPNPCCB.EJJHHCOFAAI(array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		ADLDIDKJJFG.MIOEHGDPGAG(array9, array11);
		uint[] array12 = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		ADLDIDKJJFG.IBJBIGNPNEM(array11, array7, array13);
		ADLDIDKJJFG.BHKOFHMDACN(array12, array12);
		MADOAPNPCCB.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = MADOAPNPCCB.FIBDFFPCDGC(array13, array13, array12);
		ADLDIDKJJFG.KKIGIOINLCI(aMFCENFNAJJ, array12);
		IKBHHNIGFHL iKBHHNIGFHL7 = new IKBHHNIGFHL(array4);
		ADLDIDKJJFG.MIOEHGDPGAG(array10, iKBHHNIGFHL7.AMFCENFNAJJ);
		ADLDIDKJJFG.FBGIHKPECCO(iKBHHNIGFHL7.AMFCENFNAJJ, array12, iKBHHNIGFHL7.AMFCENFNAJJ);
		IKBHHNIGFHL iKBHHNIGFHL8 = new IKBHHNIGFHL(array12);
		ADLDIDKJJFG.FBGIHKPECCO(array13, iKBHHNIGFHL7.AMFCENFNAJJ, iKBHHNIGFHL8.AMFCENFNAJJ);
		ADLDIDKJJFG.OMJFFHEIEFH(iKBHHNIGFHL8.AMFCENFNAJJ, array10, array);
		ADLDIDKJJFG.BKCHMGKFECM(array, iKBHHNIGFHL8.AMFCENFNAJJ);
		IKBHHNIGFHL iKBHHNIGFHL9 = new IKBHHNIGFHL(array9);
		if (!flag)
		{
			ADLDIDKJJFG.IBJBIGNPNEM(iKBHHNIGFHL9.AMFCENFNAJJ, iKBHHNIGFHL5.AMFCENFNAJJ, iKBHHNIGFHL9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			ADLDIDKJJFG.IBJBIGNPNEM(iKBHHNIGFHL9.AMFCENFNAJJ, iKBHHNIGFHL6.AMFCENFNAJJ, iKBHHNIGFHL9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { iKBHHNIGFHL9 };
		return new DOMJIBIBDDP(bHPIABAGAPB, iKBHHNIGFHL7, iKBHHNIGFHL8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		IKBHHNIGFHL iKBHHNIGFHL = (IKBHHNIGFHL)base.FIJLKLCHMGH;
		if (iKBHHNIGFHL.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		IKBHHNIGFHL iKBHHNIGFHL2 = (IKBHHNIGFHL)base.NBPANDNEJGI;
		IKBHHNIGFHL iKBHHNIGFHL3 = (IKBHHNIGFHL)base.LAMGGDKLPJH[0];
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		uint[] array2 = MADOAPNPCCB.PLIFFMMBNPM();
		uint[] array3 = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.MIOEHGDPGAG(iKBHHNIGFHL.AMFCENFNAJJ, array3);
		uint[] array4 = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.MIOEHGDPGAG(array3, array4);
		bool flag = iKBHHNIGFHL3.EOJCHPEGABD;
		uint[] array5 = iKBHHNIGFHL3.AMFCENFNAJJ;
		if (!flag)
		{
			array5 = array2;
			ADLDIDKJJFG.MIOEHGDPGAG(iKBHHNIGFHL3.AMFCENFNAJJ, array5);
		}
		ADLDIDKJJFG.FBGIHKPECCO(iKBHHNIGFHL2.AMFCENFNAJJ, array5, array);
		uint[] array6 = array2;
		ADLDIDKJJFG.JEACJNAKLDJ(iKBHHNIGFHL2.AMFCENFNAJJ, array5, array6);
		ADLDIDKJJFG.IBJBIGNPNEM(array6, array, array6);
		uint aMFCENFNAJJ = MADOAPNPCCB.FIBDFFPCDGC(array6, array6, array6);
		ADLDIDKJJFG.KKIGIOINLCI(aMFCENFNAJJ, array6);
		uint[] array7 = array3;
		ADLDIDKJJFG.IBJBIGNPNEM(array3, iKBHHNIGFHL2.AMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(7, array7, 2, 0u);
		ADLDIDKJJFG.KKIGIOINLCI(aMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(7, array4, 3, 0u, array);
		ADLDIDKJJFG.KKIGIOINLCI(aMFCENFNAJJ, array);
		IKBHHNIGFHL iKBHHNIGFHL4 = new IKBHHNIGFHL(array4);
		ADLDIDKJJFG.MIOEHGDPGAG(array6, iKBHHNIGFHL4.AMFCENFNAJJ);
		ADLDIDKJJFG.FBGIHKPECCO(iKBHHNIGFHL4.AMFCENFNAJJ, array7, iKBHHNIGFHL4.AMFCENFNAJJ);
		ADLDIDKJJFG.FBGIHKPECCO(iKBHHNIGFHL4.AMFCENFNAJJ, array7, iKBHHNIGFHL4.AMFCENFNAJJ);
		IKBHHNIGFHL iKBHHNIGFHL5 = new IKBHHNIGFHL(array7);
		ADLDIDKJJFG.FBGIHKPECCO(array7, iKBHHNIGFHL4.AMFCENFNAJJ, iKBHHNIGFHL5.AMFCENFNAJJ);
		ADLDIDKJJFG.IBJBIGNPNEM(iKBHHNIGFHL5.AMFCENFNAJJ, array6, iKBHHNIGFHL5.AMFCENFNAJJ);
		ADLDIDKJJFG.FBGIHKPECCO(iKBHHNIGFHL5.AMFCENFNAJJ, array, iKBHHNIGFHL5.AMFCENFNAJJ);
		IKBHHNIGFHL iKBHHNIGFHL6 = new IKBHHNIGFHL(array6);
		ADLDIDKJJFG.LLGLJBDLBOP(iKBHHNIGFHL.AMFCENFNAJJ, iKBHHNIGFHL6.AMFCENFNAJJ);
		if (!flag)
		{
			ADLDIDKJJFG.IBJBIGNPNEM(iKBHHNIGFHL6.AMFCENFNAJJ, iKBHHNIGFHL3.AMFCENFNAJJ, iKBHHNIGFHL6.AMFCENFNAJJ);
		}
		return new DOMJIBIBDDP(bHPIABAGAPB, iKBHHNIGFHL4, iKBHHNIGFHL5, new KBINBLGGLNE[1] { iKBHHNIGFHL6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new DOMJIBIBDDP(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
