public class EBIOFEGJMGL : PHFBFDEAHMD
{
	private const byte PEKPLCOIMDB = 54;

	private const byte GKBCGMLIJCF = 92;

	internal static readonly byte[] HDBEHGHJLCE = COGJFAFIEOD(54, 48);

	internal static readonly byte[] NBKPLNHFBOH = COGJFAFIEOD(92, 48);

	private readonly BJLAMONNNDD HABFKBCEIBN;

	private readonly int HLGAKLOKMFG;

	private byte[] JPCIJINDHIH;

	public virtual string KFKMEPMEBND
	{
		get
		{
			return HABFKBCEIBN.KFKMEPMEBND + "/SSL3MAC";
		}
	}

	public EBIOFEGJMGL(BJLAMONNNDD HABFKBCEIBN)
	{
		this.HABFKBCEIBN = HABFKBCEIBN;
		if (HABFKBCEIBN.EEMLLAMENHO() == 20)
		{
			HLGAKLOKMFG = 40;
		}
		else
		{
			HLGAKLOKMFG = 48;
		}
	}

	public virtual void DIOELAHNLKJ(IGMAJHKIIPK IJJHBEECMBP)
	{
		JPCIJINDHIH = NOGCEBKPPJE.IKBFGGABMKP(((JEMNCGMEABF)IJJHBEECMBP).MEGBFHFMBFI());
		OMOKOKFNBKI();
	}

	public virtual int BKGLOJPPBIG()
	{
		return HABFKBCEIBN.EEMLLAMENHO();
	}

	public virtual void BPAJGOINFNL(byte MOPCLEEGDFB)
	{
		HABFKBCEIBN.BPAJGOINFNL(MOPCLEEGDFB);
	}

	public virtual void GONEEEFEDGF(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int NBEDPKHALCN)
	{
		HABFKBCEIBN.GONEEEFEDGF(MOPCLEEGDFB, ELICNEDIBGB, NBEDPKHALCN);
	}

	public virtual int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		byte[] array = new byte[HABFKBCEIBN.EEMLLAMENHO()];
		HABFKBCEIBN.LCNOFBMOHHM(array, 0);
		HABFKBCEIBN.GONEEEFEDGF(JPCIJINDHIH, 0, JPCIJINDHIH.Length);
		HABFKBCEIBN.GONEEEFEDGF(NBKPLNHFBOH, 0, HLGAKLOKMFG);
		HABFKBCEIBN.GONEEEFEDGF(array, 0, array.Length);
		int result = HABFKBCEIBN.LCNOFBMOHHM(BILGCJNPJGJ, EMAKNGBIFDC);
		OMOKOKFNBKI();
		return result;
	}

	public virtual void OMOKOKFNBKI()
	{
		HABFKBCEIBN.OMOKOKFNBKI();
		HABFKBCEIBN.GONEEEFEDGF(JPCIJINDHIH, 0, JPCIJINDHIH.Length);
		HABFKBCEIBN.GONEEEFEDGF(HDBEHGHJLCE, 0, HLGAKLOKMFG);
	}

	private static byte[] COGJFAFIEOD(byte BCIHLCMFAEK, int ENMLICFLHAO)
	{
		byte[] array = new byte[ENMLICFLHAO];
		NOGCEBKPPJE.MEBLOMPDLEJ(array, BCIHLCMFAEK);
		return array;
	}
}
