using System;
using Org.BouncyCastle.Math;

public class EBMGIDBMGJP : LNKPCJLANAO
{
	private readonly BHPIABAGAPB NINILENHPHE;

	private readonly byte[] HJBOEOOLOOE;

	private readonly KLKJHFKJLEM PBMJCPKNDCL;

	public BHPIABAGAPB ECFGFKNLLGH
	{
		get
		{
			return NINILENHPHE;
		}
	}

	public EBMGIDBMGJP(BHPIABAGAPB NINILENHPHE)
		: this(NINILENHPHE, null)
	{
	}

	public EBMGIDBMGJP(BHPIABAGAPB NINILENHPHE, byte[] HJBOEOOLOOE)
	{
		if (NINILENHPHE == null)
		{
			throw new ArgumentNullException("curve");
		}
		this.NINILENHPHE = NINILENHPHE;
		this.HJBOEOOLOOE = NOGCEBKPPJE.IKBFGGABMKP(HJBOEOOLOOE);
		if (KHJLHEJBLOA.FNAAANIPFOP(NINILENHPHE))
		{
			PBMJCPKNDCL = JJFMEBLGJEP.FCKODOMMAFF;
			return;
		}
		if (KHJLHEJBLOA.BDGICGJIGPF(NINILENHPHE))
		{
			PBMJCPKNDCL = JJFMEBLGJEP.IOCHGCOMCGG;
			return;
		}
		throw new ArgumentException("This type of ECCurve is not implemented");
	}

	public EBMGIDBMGJP(CGAMCAFJLGJ NINOABCHAHL, ALLINHNNNJN MIABODPHOIP)
	{
		if (NINOABCHAHL == null)
		{
			throw new ArgumentNullException("fieldID");
		}
		if (MIABODPHOIP == null)
		{
			throw new ArgumentNullException("seq");
		}
		PBMJCPKNDCL = NINOABCHAHL.BOKHDKMEAED;
		if (PBMJCPKNDCL.Equals(JJFMEBLGJEP.FCKODOMMAFF))
		{
			BigInteger bigInteger = ((GLFDIPNOLKN)NINOABCHAHL.KPJHHAAOFOH).JBGOANMLBFA;
			JFOKJMPGMEJ jFOKJMPGMEJ = new JFOKJMPGMEJ(bigInteger, (PJGIGKJFGFI)MIABODPHOIP.ECNCPJGHBIG(0));
			JFOKJMPGMEJ jFOKJMPGMEJ2 = new JFOKJMPGMEJ(bigInteger, (PJGIGKJFGFI)MIABODPHOIP.ECNCPJGHBIG(1));
			NINILENHPHE = new BMIMOOLAJAL(bigInteger, jFOKJMPGMEJ.JBGOANMLBFA.DOJBPIFPALJ(), jFOKJMPGMEJ2.JBGOANMLBFA.DOJBPIFPALJ());
		}
		else if (PBMJCPKNDCL.Equals(JJFMEBLGJEP.IOCHGCOMCGG))
		{
			KOGPLMALOEH kOGPLMALOEH = (KOGPLMALOEH)NINOABCHAHL.KPJHHAAOFOH;
			int intValue = ((GLFDIPNOLKN)((ALLINHNNNJN)kOGPLMALOEH).ECNCPJGHBIG(0)).JBGOANMLBFA.IntValue;
			KLKJHFKJLEM kLKJHFKJLEM = (KLKJHFKJLEM)((ALLINHNNNJN)kOGPLMALOEH).ECNCPJGHBIG(1);
			int num = 0;
			int fKOBMEPIABG = 0;
			int kHNDCPCHOEM = 0;
			if (kLKJHFKJLEM.Equals(JJFMEBLGJEP.OILAJONOOJC))
			{
				num = ((GLFDIPNOLKN)((ALLINHNNNJN)kOGPLMALOEH).ECNCPJGHBIG(2)).JBGOANMLBFA.IntValue;
			}
			else
			{
				KOGPLMALOEH kOGPLMALOEH2 = (KOGPLMALOEH)((ALLINHNNNJN)kOGPLMALOEH).ECNCPJGHBIG(2);
				num = ((GLFDIPNOLKN)((ALLINHNNNJN)kOGPLMALOEH2).ECNCPJGHBIG(0)).JBGOANMLBFA.IntValue;
				fKOBMEPIABG = ((GLFDIPNOLKN)((ALLINHNNNJN)kOGPLMALOEH2).ECNCPJGHBIG(1)).JBGOANMLBFA.IntValue;
				kHNDCPCHOEM = ((GLFDIPNOLKN)((ALLINHNNNJN)kOGPLMALOEH2).ECNCPJGHBIG(2)).JBGOANMLBFA.IntValue;
			}
			JFOKJMPGMEJ jFOKJMPGMEJ3 = new JFOKJMPGMEJ(intValue, num, fKOBMEPIABG, kHNDCPCHOEM, (PJGIGKJFGFI)MIABODPHOIP.ECNCPJGHBIG(0));
			JFOKJMPGMEJ jFOKJMPGMEJ4 = new JFOKJMPGMEJ(intValue, num, fKOBMEPIABG, kHNDCPCHOEM, (PJGIGKJFGFI)MIABODPHOIP.ECNCPJGHBIG(1));
			NINILENHPHE = new NCGHMJPCCLD(intValue, num, fKOBMEPIABG, kHNDCPCHOEM, jFOKJMPGMEJ3.JBGOANMLBFA.DOJBPIFPALJ(), jFOKJMPGMEJ4.JBGOANMLBFA.DOJBPIFPALJ());
		}
		if (MIABODPHOIP.GMCGMPEEHJP == 3)
		{
			HJBOEOOLOOE = ((FJMKMKNJKOI)MIABODPHOIP.ECNCPJGHBIG(2)).MIBPLNJNEGA();
		}
	}

	public byte[] GKBBKKNGJAK()
	{
		return NOGCEBKPPJE.IKBFGGABMKP(HJBOEOOLOOE);
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		DLDBGGDLOOO dLDBGGDLOOO = new DLDBGGDLOOO();
		if (PBMJCPKNDCL.Equals(JJFMEBLGJEP.FCKODOMMAFF) || PBMJCPKNDCL.Equals(JJFMEBLGJEP.IOCHGCOMCGG))
		{
			dLDBGGDLOOO.JEACJNAKLDJ(new JFOKJMPGMEJ(NINILENHPHE.JEHECJGFJEB).IIHKEACDNID());
			dLDBGGDLOOO.JEACJNAKLDJ(new JFOKJMPGMEJ(NINILENHPHE.FPKDKHJKEEF).IIHKEACDNID());
		}
		if (HJBOEOOLOOE != null)
		{
			dLDBGGDLOOO.JEACJNAKLDJ(new FJMKMKNJKOI(HJBOEOOLOOE));
		}
		return new KOGPLMALOEH(dLDBGGDLOOO);
	}
}
