using System;

internal class EBPDFEFDDIN : OMOBJNLGOBO
{
	public EBPDFEFDDIN(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public EBPDFEFDDIN(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal EBPDFEFDDIN(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new EBPDFEFDDIN(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		OHEGFFKFNFP oHEGFFKFNFP = (OHEGFFKFNFP)base.NBPANDNEJGI;
		OHEGFFKFNFP oHEGFFKFNFP2 = (OHEGFFKFNFP)base.FIJLKLCHMGH;
		OHEGFFKFNFP oHEGFFKFNFP3 = (OHEGFFKFNFP)BCIHLCMFAEK.NBPANDNEJGI;
		OHEGFFKFNFP oHEGFFKFNFP4 = (OHEGFFKFNFP)BCIHLCMFAEK.FIJLKLCHMGH;
		OHEGFFKFNFP oHEGFFKFNFP5 = (OHEGFFKFNFP)base.LAMGGDKLPJH[0];
		OHEGFFKFNFP oHEGFFKFNFP6 = (OHEGFFKFNFP)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = PHEKPHCPKLA.DCPJKFEDHOJ();
		uint[] array2 = PHEKPHCPKLA.PLIFFMMBNPM();
		uint[] array3 = PHEKPHCPKLA.PLIFFMMBNPM();
		uint[] array4 = PHEKPHCPKLA.PLIFFMMBNPM();
		bool flag = oHEGFFKFNFP5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = oHEGFFKFNFP3.AMFCENFNAJJ;
			array6 = oHEGFFKFNFP4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			OGEODCDNDPA.MIOEHGDPGAG(oHEGFFKFNFP5.AMFCENFNAJJ, array6);
			array5 = array2;
			OGEODCDNDPA.IBJBIGNPNEM(array6, oHEGFFKFNFP3.AMFCENFNAJJ, array5);
			OGEODCDNDPA.IBJBIGNPNEM(array6, oHEGFFKFNFP5.AMFCENFNAJJ, array6);
			OGEODCDNDPA.IBJBIGNPNEM(array6, oHEGFFKFNFP4.AMFCENFNAJJ, array6);
		}
		bool flag2 = oHEGFFKFNFP6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = oHEGFFKFNFP.AMFCENFNAJJ;
			array8 = oHEGFFKFNFP2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			OGEODCDNDPA.MIOEHGDPGAG(oHEGFFKFNFP6.AMFCENFNAJJ, array8);
			array7 = array;
			OGEODCDNDPA.IBJBIGNPNEM(array8, oHEGFFKFNFP.AMFCENFNAJJ, array7);
			OGEODCDNDPA.IBJBIGNPNEM(array8, oHEGFFKFNFP6.AMFCENFNAJJ, array8);
			OGEODCDNDPA.IBJBIGNPNEM(array8, oHEGFFKFNFP2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = PHEKPHCPKLA.PLIFFMMBNPM();
		OGEODCDNDPA.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		OGEODCDNDPA.FBGIHKPECCO(array8, array6, array10);
		if (PHEKPHCPKLA.EJJHHCOFAAI(array9))
		{
			if (PHEKPHCPKLA.EJJHHCOFAAI(array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		OGEODCDNDPA.MIOEHGDPGAG(array9, array11);
		uint[] array12 = PHEKPHCPKLA.PLIFFMMBNPM();
		OGEODCDNDPA.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		OGEODCDNDPA.IBJBIGNPNEM(array11, array7, array13);
		OGEODCDNDPA.BHKOFHMDACN(array12, array12);
		PHEKPHCPKLA.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = PHEKPHCPKLA.FIBDFFPCDGC(array13, array13, array12);
		OGEODCDNDPA.KKIGIOINLCI(aMFCENFNAJJ, array12);
		OHEGFFKFNFP oHEGFFKFNFP7 = new OHEGFFKFNFP(array4);
		OGEODCDNDPA.MIOEHGDPGAG(array10, oHEGFFKFNFP7.AMFCENFNAJJ);
		OGEODCDNDPA.FBGIHKPECCO(oHEGFFKFNFP7.AMFCENFNAJJ, array12, oHEGFFKFNFP7.AMFCENFNAJJ);
		OHEGFFKFNFP oHEGFFKFNFP8 = new OHEGFFKFNFP(array12);
		OGEODCDNDPA.FBGIHKPECCO(array13, oHEGFFKFNFP7.AMFCENFNAJJ, oHEGFFKFNFP8.AMFCENFNAJJ);
		OGEODCDNDPA.OMJFFHEIEFH(oHEGFFKFNFP8.AMFCENFNAJJ, array10, array);
		OGEODCDNDPA.BKCHMGKFECM(array, oHEGFFKFNFP8.AMFCENFNAJJ);
		OHEGFFKFNFP oHEGFFKFNFP9 = new OHEGFFKFNFP(array9);
		if (!flag)
		{
			OGEODCDNDPA.IBJBIGNPNEM(oHEGFFKFNFP9.AMFCENFNAJJ, oHEGFFKFNFP5.AMFCENFNAJJ, oHEGFFKFNFP9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			OGEODCDNDPA.IBJBIGNPNEM(oHEGFFKFNFP9.AMFCENFNAJJ, oHEGFFKFNFP6.AMFCENFNAJJ, oHEGFFKFNFP9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { oHEGFFKFNFP9 };
		return new EBPDFEFDDIN(bHPIABAGAPB, oHEGFFKFNFP7, oHEGFFKFNFP8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		OHEGFFKFNFP oHEGFFKFNFP = (OHEGFFKFNFP)base.FIJLKLCHMGH;
		if (oHEGFFKFNFP.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		OHEGFFKFNFP oHEGFFKFNFP2 = (OHEGFFKFNFP)base.NBPANDNEJGI;
		OHEGFFKFNFP oHEGFFKFNFP3 = (OHEGFFKFNFP)base.LAMGGDKLPJH[0];
		uint[] array = PHEKPHCPKLA.PLIFFMMBNPM();
		uint[] array2 = PHEKPHCPKLA.PLIFFMMBNPM();
		uint[] array3 = PHEKPHCPKLA.PLIFFMMBNPM();
		OGEODCDNDPA.MIOEHGDPGAG(oHEGFFKFNFP.AMFCENFNAJJ, array3);
		uint[] array4 = PHEKPHCPKLA.PLIFFMMBNPM();
		OGEODCDNDPA.MIOEHGDPGAG(array3, array4);
		bool flag = oHEGFFKFNFP3.EOJCHPEGABD;
		uint[] array5 = oHEGFFKFNFP3.AMFCENFNAJJ;
		if (!flag)
		{
			array5 = array2;
			OGEODCDNDPA.MIOEHGDPGAG(oHEGFFKFNFP3.AMFCENFNAJJ, array5);
		}
		OGEODCDNDPA.FBGIHKPECCO(oHEGFFKFNFP2.AMFCENFNAJJ, array5, array);
		uint[] array6 = array2;
		OGEODCDNDPA.JEACJNAKLDJ(oHEGFFKFNFP2.AMFCENFNAJJ, array5, array6);
		OGEODCDNDPA.IBJBIGNPNEM(array6, array, array6);
		uint aMFCENFNAJJ = PHEKPHCPKLA.FIBDFFPCDGC(array6, array6, array6);
		OGEODCDNDPA.KKIGIOINLCI(aMFCENFNAJJ, array6);
		uint[] array7 = array3;
		OGEODCDNDPA.IBJBIGNPNEM(array3, oHEGFFKFNFP2.AMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(6, array7, 2, 0u);
		OGEODCDNDPA.KKIGIOINLCI(aMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(6, array4, 3, 0u, array);
		OGEODCDNDPA.KKIGIOINLCI(aMFCENFNAJJ, array);
		OHEGFFKFNFP oHEGFFKFNFP4 = new OHEGFFKFNFP(array4);
		OGEODCDNDPA.MIOEHGDPGAG(array6, oHEGFFKFNFP4.AMFCENFNAJJ);
		OGEODCDNDPA.FBGIHKPECCO(oHEGFFKFNFP4.AMFCENFNAJJ, array7, oHEGFFKFNFP4.AMFCENFNAJJ);
		OGEODCDNDPA.FBGIHKPECCO(oHEGFFKFNFP4.AMFCENFNAJJ, array7, oHEGFFKFNFP4.AMFCENFNAJJ);
		OHEGFFKFNFP oHEGFFKFNFP5 = new OHEGFFKFNFP(array7);
		OGEODCDNDPA.FBGIHKPECCO(array7, oHEGFFKFNFP4.AMFCENFNAJJ, oHEGFFKFNFP5.AMFCENFNAJJ);
		OGEODCDNDPA.IBJBIGNPNEM(oHEGFFKFNFP5.AMFCENFNAJJ, array6, oHEGFFKFNFP5.AMFCENFNAJJ);
		OGEODCDNDPA.FBGIHKPECCO(oHEGFFKFNFP5.AMFCENFNAJJ, array, oHEGFFKFNFP5.AMFCENFNAJJ);
		OHEGFFKFNFP oHEGFFKFNFP6 = new OHEGFFKFNFP(array6);
		OGEODCDNDPA.LLGLJBDLBOP(oHEGFFKFNFP.AMFCENFNAJJ, oHEGFFKFNFP6.AMFCENFNAJJ);
		if (!flag)
		{
			OGEODCDNDPA.IBJBIGNPNEM(oHEGFFKFNFP6.AMFCENFNAJJ, oHEGFFKFNFP3.AMFCENFNAJJ, oHEGFFKFNFP6.AMFCENFNAJJ);
		}
		return new EBPDFEFDDIN(bHPIABAGAPB, oHEGFFKFNFP4, oHEGFFKFNFP5, new KBINBLGGLNE[1] { oHEGFFKFNFP6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new EBPDFEFDDIN(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
