public interface EDENIAPLFEN
{
	MKEALIMJCFJ HNCBJFIPJNP(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN, string LCCKDPIBKPJ);

	MGCLDKAFCIB MPDDHGBKGCP(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN, string LCCKDPIBKPJ);

	KBLNEHAAAJK KMGJEJLCPLE(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN);

	GMLCOKFENFN HAOODEOAMHH(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN);

	ENIPPOEKJPA NJIHKIHEHKL(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN);

	ACEGNBDLKEG HLKKDHKIPOC(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN);
}
