using System;
using Org.BouncyCastle.Crypto;

public class EEOENLPCPJK : JMPFLJGHAIM
{
	private byte[] INPOFIMEPGC;

	private byte[] AMPAGEAOPEO;

	private byte[] CIPOFOGBLKP;

	private readonly JMPFLJGHAIM IEDPBFAFGGJ;

	private readonly int NONHELBCKCH;

	private int ENMLICFLHAO;

	private bool MAEALKEJALK;

	public string KFKMEPMEBND
	{
		get
		{
			return IEDPBFAFGGJ.KFKMEPMEBND + "/OpenPGPCFB";
		}
	}

	public bool ABNLKPDCGEF
	{
		get
		{
			return true;
		}
	}

	public EEOENLPCPJK(JMPFLJGHAIM IEDPBFAFGGJ)
	{
		this.IEDPBFAFGGJ = IEDPBFAFGGJ;
		NONHELBCKCH = IEDPBFAFGGJ.BDIGGHEPIIP();
		INPOFIMEPGC = new byte[NONHELBCKCH];
		AMPAGEAOPEO = new byte[NONHELBCKCH];
		CIPOFOGBLKP = new byte[NONHELBCKCH];
	}

	public JMPFLJGHAIM GBHNDFALCDC()
	{
		return IEDPBFAFGGJ;
	}

	public int BDIGGHEPIIP()
	{
		return IEDPBFAFGGJ.BDIGGHEPIIP();
	}

	public int DPACJDFHLKB(byte[] MOPCLEEGDFB, int ELICNEDIBGB, byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		return (!MAEALKEJALK) ? GFKALHGNIOJ(MOPCLEEGDFB, ELICNEDIBGB, BILGCJNPJGJ, EMAKNGBIFDC) : HDOLNBOHAJA(MOPCLEEGDFB, ELICNEDIBGB, BILGCJNPJGJ, EMAKNGBIFDC);
	}

	public void OMOKOKFNBKI()
	{
		ENMLICFLHAO = 0;
		Array.Copy(INPOFIMEPGC, 0, AMPAGEAOPEO, 0, AMPAGEAOPEO.Length);
		IEDPBFAFGGJ.OMOKOKFNBKI();
	}

	public void DIOELAHNLKJ(bool MAEALKEJALK, IGMAJHKIIPK IJJHBEECMBP)
	{
		this.MAEALKEJALK = MAEALKEJALK;
		if (IJJHBEECMBP is CHCELGDKEJG)
		{
			CHCELGDKEJG cHCELGDKEJG = (CHCELGDKEJG)IJJHBEECMBP;
			byte[] array = cHCELGDKEJG.OLAEDCABKDH();
			if (array.Length < INPOFIMEPGC.Length)
			{
				Array.Copy(array, 0, INPOFIMEPGC, INPOFIMEPGC.Length - array.Length, array.Length);
				for (int i = 0; i < INPOFIMEPGC.Length - array.Length; i++)
				{
					INPOFIMEPGC[i] = 0;
				}
			}
			else
			{
				Array.Copy(array, 0, INPOFIMEPGC, 0, INPOFIMEPGC.Length);
			}
			IJJHBEECMBP = cHCELGDKEJG.KPJHHAAOFOH;
		}
		OMOKOKFNBKI();
		IEDPBFAFGGJ.DIOELAHNLKJ(true, IJJHBEECMBP);
	}

	private byte DOOJIGOOKGH(byte MBBPBGHKLJM, int LPHMHEIJJLO)
	{
		return (byte)(CIPOFOGBLKP[LPHMHEIJJLO] ^ MBBPBGHKLJM);
	}

	private int HDOLNBOHAJA(byte[] MOPCLEEGDFB, int ELICNEDIBGB, byte[] NGAGMIIBGKA, int EMAKNGBIFDC)
	{
		if (ELICNEDIBGB + NONHELBCKCH > MOPCLEEGDFB.Length)
		{
			throw new DataLengthException("input buffer too short");
		}
		if (EMAKNGBIFDC + NONHELBCKCH > NGAGMIIBGKA.Length)
		{
			throw new DataLengthException("output buffer too short");
		}
		if (ENMLICFLHAO > NONHELBCKCH)
		{
			AMPAGEAOPEO[NONHELBCKCH - 2] = (NGAGMIIBGKA[EMAKNGBIFDC] = DOOJIGOOKGH(MOPCLEEGDFB[ELICNEDIBGB], NONHELBCKCH - 2));
			AMPAGEAOPEO[NONHELBCKCH - 1] = (NGAGMIIBGKA[EMAKNGBIFDC + 1] = DOOJIGOOKGH(MOPCLEEGDFB[ELICNEDIBGB + 1], NONHELBCKCH - 1));
			IEDPBFAFGGJ.DPACJDFHLKB(AMPAGEAOPEO, 0, CIPOFOGBLKP, 0);
			for (int i = 2; i < NONHELBCKCH; i++)
			{
				AMPAGEAOPEO[i - 2] = (NGAGMIIBGKA[EMAKNGBIFDC + i] = DOOJIGOOKGH(MOPCLEEGDFB[ELICNEDIBGB + i], i - 2));
			}
		}
		else if (ENMLICFLHAO == 0)
		{
			IEDPBFAFGGJ.DPACJDFHLKB(AMPAGEAOPEO, 0, CIPOFOGBLKP, 0);
			for (int j = 0; j < NONHELBCKCH; j++)
			{
				AMPAGEAOPEO[j] = (NGAGMIIBGKA[EMAKNGBIFDC + j] = DOOJIGOOKGH(MOPCLEEGDFB[ELICNEDIBGB + j], j));
			}
			ENMLICFLHAO += NONHELBCKCH;
		}
		else if (ENMLICFLHAO == NONHELBCKCH)
		{
			IEDPBFAFGGJ.DPACJDFHLKB(AMPAGEAOPEO, 0, CIPOFOGBLKP, 0);
			NGAGMIIBGKA[EMAKNGBIFDC] = DOOJIGOOKGH(MOPCLEEGDFB[ELICNEDIBGB], 0);
			NGAGMIIBGKA[EMAKNGBIFDC + 1] = DOOJIGOOKGH(MOPCLEEGDFB[ELICNEDIBGB + 1], 1);
			Array.Copy(AMPAGEAOPEO, 2, AMPAGEAOPEO, 0, NONHELBCKCH - 2);
			Array.Copy(NGAGMIIBGKA, EMAKNGBIFDC, AMPAGEAOPEO, NONHELBCKCH - 2, 2);
			IEDPBFAFGGJ.DPACJDFHLKB(AMPAGEAOPEO, 0, CIPOFOGBLKP, 0);
			for (int k = 2; k < NONHELBCKCH; k++)
			{
				AMPAGEAOPEO[k - 2] = (NGAGMIIBGKA[EMAKNGBIFDC + k] = DOOJIGOOKGH(MOPCLEEGDFB[ELICNEDIBGB + k], k - 2));
			}
			ENMLICFLHAO += NONHELBCKCH;
		}
		return NONHELBCKCH;
	}

	private int GFKALHGNIOJ(byte[] MOPCLEEGDFB, int ELICNEDIBGB, byte[] NGAGMIIBGKA, int EMAKNGBIFDC)
	{
		if (ELICNEDIBGB + NONHELBCKCH > MOPCLEEGDFB.Length)
		{
			throw new DataLengthException("input buffer too short");
		}
		if (EMAKNGBIFDC + NONHELBCKCH > NGAGMIIBGKA.Length)
		{
			throw new DataLengthException("output buffer too short");
		}
		if (ENMLICFLHAO > NONHELBCKCH)
		{
			byte b = MOPCLEEGDFB[ELICNEDIBGB];
			AMPAGEAOPEO[NONHELBCKCH - 2] = b;
			NGAGMIIBGKA[EMAKNGBIFDC] = DOOJIGOOKGH(b, NONHELBCKCH - 2);
			b = MOPCLEEGDFB[ELICNEDIBGB + 1];
			AMPAGEAOPEO[NONHELBCKCH - 1] = b;
			NGAGMIIBGKA[EMAKNGBIFDC + 1] = DOOJIGOOKGH(b, NONHELBCKCH - 1);
			IEDPBFAFGGJ.DPACJDFHLKB(AMPAGEAOPEO, 0, CIPOFOGBLKP, 0);
			for (int i = 2; i < NONHELBCKCH; i++)
			{
				b = MOPCLEEGDFB[ELICNEDIBGB + i];
				AMPAGEAOPEO[i - 2] = b;
				NGAGMIIBGKA[EMAKNGBIFDC + i] = DOOJIGOOKGH(b, i - 2);
			}
		}
		else if (ENMLICFLHAO == 0)
		{
			IEDPBFAFGGJ.DPACJDFHLKB(AMPAGEAOPEO, 0, CIPOFOGBLKP, 0);
			for (int j = 0; j < NONHELBCKCH; j++)
			{
				AMPAGEAOPEO[j] = MOPCLEEGDFB[ELICNEDIBGB + j];
				NGAGMIIBGKA[j] = DOOJIGOOKGH(MOPCLEEGDFB[ELICNEDIBGB + j], j);
			}
			ENMLICFLHAO += NONHELBCKCH;
		}
		else if (ENMLICFLHAO == NONHELBCKCH)
		{
			IEDPBFAFGGJ.DPACJDFHLKB(AMPAGEAOPEO, 0, CIPOFOGBLKP, 0);
			byte b2 = MOPCLEEGDFB[ELICNEDIBGB];
			byte b3 = MOPCLEEGDFB[ELICNEDIBGB + 1];
			NGAGMIIBGKA[EMAKNGBIFDC] = DOOJIGOOKGH(b2, 0);
			NGAGMIIBGKA[EMAKNGBIFDC + 1] = DOOJIGOOKGH(b3, 1);
			Array.Copy(AMPAGEAOPEO, 2, AMPAGEAOPEO, 0, NONHELBCKCH - 2);
			AMPAGEAOPEO[NONHELBCKCH - 2] = b2;
			AMPAGEAOPEO[NONHELBCKCH - 1] = b3;
			IEDPBFAFGGJ.DPACJDFHLKB(AMPAGEAOPEO, 0, CIPOFOGBLKP, 0);
			for (int k = 2; k < NONHELBCKCH; k++)
			{
				byte b4 = MOPCLEEGDFB[ELICNEDIBGB + k];
				AMPAGEAOPEO[k - 2] = b4;
				NGAGMIIBGKA[EMAKNGBIFDC + k] = DOOJIGOOKGH(b4, k - 2);
			}
			ENMLICFLHAO += NONHELBCKCH;
		}
		return NONHELBCKCH;
	}
}
