using System.Collections;
using System.IO;

public class EFENHHBJKEL : ABFMEJBCEFO
{
	protected IAJODODPMMG AIFOKDNIJLN;

	public EFENHHBJKEL(int EBOOFBMGNDI, IList GMLLEBDADDP, CLBPDHGBHML FIIGKOBJLJF)
		: base(EBOOFBMGNDI, GMLLEBDADDP, FIIGKOBJLJF)
	{
	}

	public override void OPECIECMFCD(OPCLIKBOHJP BGFNAKMFCHD)
	{
		if (!(BGFNAKMFCHD is IAJODODPMMG))
		{
			throw new DEIDBCPPCMB(80);
		}
		BGLKKBMEEEK(BGFNAKMFCHD.BIBHHNBEJJM);
		AIFOKDNIJLN = (IAJODODPMMG)BGFNAKMFCHD;
	}

	public override byte[] DMJCNEDKPEA()
	{
		if (FKADCPDDCJD == null)
		{
			throw new DEIDBCPPCMB(80);
		}
		DANGFIDLKOF dANGFIDLKOF = new DANGFIDLKOF();
		NDIOOHBIMGN = DBBCMLDCNPN.KGOGEEJBEBL(COOBIGONLDK.KMLKPFPCFLA, FKADCPDDCJD, dANGFIDLKOF);
		FBMKOGABPFL fBMKOGABPFL = KINEBFNENMB.CBMIGMCGDJL(COOBIGONLDK, AIFOKDNIJLN);
		BJLAMONNNDD bJLAMONNNDD = KINEBFNENMB.KNADNPDKLGD(fBMKOGABPFL);
		PDCALMCFKGD pDCALMCFKGD = COOBIGONLDK.HFMNBFOAPOP;
		bJLAMONNNDD.GONEEEFEDGF(pDCALMCFKGD.NIMMIFGHCAF, 0, pDCALMCFKGD.NIMMIFGHCAF.Length);
		bJLAMONNNDD.GONEEEFEDGF(pDCALMCFKGD.BKHHFBJJBAB, 0, pDCALMCFKGD.BKHHFBJJBAB.Length);
		dANGFIDLKOF.CHOLLICODBI(bJLAMONNNDD);
		byte[] aIELCDIFLFB = KDDIIEMIPKF.LCNOFBMOHHM(bJLAMONNNDD);
		byte[] pINNJBGMGOA = AIFOKDNIJLN.NPDKOKDCPAF(aIELCDIFLFB);
		NKOAICPNEJH nKOAICPNEJH = new NKOAICPNEJH(fBMKOGABPFL, pINNJBGMGOA);
		nKOAICPNEJH.LMDBBPLCJDM(dANGFIDLKOF);
		return dANGFIDLKOF.ToArray();
	}

	public override void OJGCPPFDPBN(Stream MOPCLEEGDFB)
	{
		PDCALMCFKGD bOHAELIJHGF = COOBIGONLDK.HFMNBFOAPOP;
		HPMACIICIKB hPMACIICIKB = new HPMACIICIKB();
		Stream mOPCLEEGDFB = new DKLELFJMFAA(MOPCLEEGDFB, hPMACIICIKB);
		FICAEDDJBEN fICAEDDJBEN = FICAEDDJBEN.DHCLOMIANOE(mOPCLEEGDFB);
		NKOAICPNEJH nKOAICPNEJH = MNPNCAOHANP(MOPCLEEGDFB);
		OHPHNNNHCOO oHPHNNNHCOO = CKCBBLBAFJA(PJMPLLIKCCG, nKOAICPNEJH.GOFDFGBGLFC, bOHAELIJHGF);
		hPMACIICIKB.CNOKJEIHKJI(oHPHNNNHCOO);
		if (!oHPHNNNHCOO.HLJBBONKPDG(nKOAICPNEJH.ACMDKLDPDLB))
		{
			throw new DEIDBCPPCMB(51);
		}
		HKCLMCFFABJ = DBBCMLDCNPN.BJEGIOHKNMM(fICAEDDJBEN.OIDHEOJEMJF);
		FKADCPDDCJD = IBLKJLFKPBE(HKCLMCFFABJ.KPJHHAAOFOH);
	}

	protected virtual OHPHNNNHCOO CKCBBLBAFJA(EKFAMINKCJP HCJGAPBFJEB, FBMKOGABPFL ADLMOHOLCGL, PDCALMCFKGD BOHAELIJHGF)
	{
		OHPHNNNHCOO oHPHNNNHCOO = HCJGAPBFJEB.OPKHBIHFBMM(ADLMOHOLCGL, CAACNJEGLIP);
		oHPHNNNHCOO.GONEEEFEDGF(BOHAELIJHGF.NIMMIFGHCAF, 0, BOHAELIJHGF.NIMMIFGHCAF.Length);
		oHPHNNNHCOO.GONEEEFEDGF(BOHAELIJHGF.BKHHFBJJBAB, 0, BOHAELIJHGF.BKHHFBJJBAB.Length);
		return oHPHNNNHCOO;
	}
}
