using System;
using UnityEngine;

public static class EGGDFFGPOAJ
{
	[Obsolete]
	public static MKEALIMJCFJ BAMMJEFEGED(this GCJKICAPOFL GDNININLMFD, string NFKHLLDFHKO, Sprite MJOJAOIHCIO, string MECNBBKOAPL = "Spine/Skeleton", bool PFGDLFPJMBA = true, float ODLHFMOPCHL = 0f)
	{
		return GDNININLMFD.BAMMJEFEGED(NFKHLLDFHKO, MJOJAOIHCIO, Shader.Find(MECNBBKOAPL), PFGDLFPJMBA, ODLHFMOPCHL);
	}

	[Obsolete]
	public static MKEALIMJCFJ LOJPGHPDFOE(this KGMHJGFNPFC DCMDAJJBNAI, string NFKHLLDFHKO, Sprite MJOJAOIHCIO, string COKOMFOMBBA = "", string MECNBBKOAPL = "Spine/Skeleton", bool PFGDLFPJMBA = true, float ODLHFMOPCHL = 0f)
	{
		return DCMDAJJBNAI.LOJPGHPDFOE(NFKHLLDFHKO, MJOJAOIHCIO, COKOMFOMBBA, Shader.Find(MECNBBKOAPL), PFGDLFPJMBA, ODLHFMOPCHL);
	}

	[Obsolete]
	public static MKEALIMJCFJ BAMMJEFEGED(this GCJKICAPOFL GDNININLMFD, string NFKHLLDFHKO, Sprite MJOJAOIHCIO, Shader BLCFLFHNKFG, bool PFGDLFPJMBA, float ODLHFMOPCHL = 0f)
	{
		MKEALIMJCFJ mKEALIMJCFJ;
		if (PFGDLFPJMBA)
		{
			mKEALIMJCFJ = MJOJAOIHCIO.GCAIEFLKMON(BLCFLFHNKFG, TextureFormat.RGBA32, false, null, ODLHFMOPCHL);
		}
		else
		{
			mKEALIMJCFJ = MJOJAOIHCIO.GBANGNAEBAH(new Material(BLCFLFHNKFG), ODLHFMOPCHL);
		}
		MKEALIMJCFJ mKEALIMJCFJ2 = mKEALIMJCFJ;
		GDNININLMFD.MEKLNNENPDK(NFKHLLDFHKO).AIKFOHCPLKG = mKEALIMJCFJ2;
		return mKEALIMJCFJ2;
	}

	[Obsolete]
	public static MKEALIMJCFJ LOJPGHPDFOE(this KGMHJGFNPFC DCMDAJJBNAI, string NFKHLLDFHKO, Sprite MJOJAOIHCIO, string COKOMFOMBBA, Shader BLCFLFHNKFG, bool PFGDLFPJMBA, float ODLHFMOPCHL = 0f)
	{
		MKEALIMJCFJ mKEALIMJCFJ;
		if (PFGDLFPJMBA)
		{
			mKEALIMJCFJ = MJOJAOIHCIO.GCAIEFLKMON(BLCFLFHNKFG, TextureFormat.RGBA32, false, null, ODLHFMOPCHL);
		}
		else
		{
			mKEALIMJCFJ = MJOJAOIHCIO.GBANGNAEBAH(new Material(BLCFLFHNKFG), ODLHFMOPCHL);
		}
		MKEALIMJCFJ mKEALIMJCFJ2 = mKEALIMJCFJ;
		int pBPEMFGPGFC = DCMDAJJBNAI.IBOGMECEHLD(NFKHLLDFHKO);
		JPAALKCPGNB jPAALKCPGNB = DCMDAJJBNAI.NAKPPHNCJOC;
		if (COKOMFOMBBA != string.Empty)
		{
			jPAALKCPGNB = DCMDAJJBNAI.COONIJFPADF(COKOMFOMBBA);
		}
		jPAALKCPGNB.DJJIHPJOEBF(pBPEMFGPGFC, mKEALIMJCFJ2.PNGPLGHKFDI, mKEALIMJCFJ2);
		return mKEALIMJCFJ2;
	}
}
