public static class EILLLGLODPC
{
	public static string MJKNGNJKHFG(this int BDKFNEDHAOJ)
	{
		switch (BDKFNEDHAOJ)
		{
		case 1:
			return "yellowcubegoal";
		case 2:
			return "redcubegoal";
		case 3:
			return "bluecubegoal";
		case 4:
			return "greencubegoal";
		case 5:
			return "purplecubegoal";
		case 6:
			return "orangecubegoal";
		case 61:
			return "bubblegoal";
		case 104:
		case 105:
		case 106:
		case 107:
		case 108:
		case 109:
			return "colorballoongoal";
		case 41:
		case 42:
		case 43:
		case 44:
		case 45:
			return "duckgoal";
		case 121:
			return "giantduckgoal";
		case 72:
			return "giantpinatagoal";
		case 69:
			return "cangoal";
		case 136:
		case 138:
		case 161:
		case 163:
		case 165:
		case 167:
		case 169:
			return "sodagoal";
		case 103:
			return "carrotgoal";
		case 65:
		case 66:
		case 67:
			return "crategoal";
		case 93:
		case 94:
			return "bubblegoal";
		case 74:
		case 75:
			return "balloongoal";
		case 110:
		case 111:
		case 112:
		case 113:
		case 114:
		case 115:
		case 124:
		case 125:
		case 126:
		case 127:
		case 128:
		case 129:
		case 130:
		case 131:
		case 132:
		case 133:
		case 134:
		case 135:
			return "colorcrategoal";
		case 63:
			return "balloongoal";
		case 91:
			return "watermelongoal";
		case 71:
			return "easteregggoal";
		case 62:
			return "pinatagoal";
		case 123:
			return "jellygoal";
		case 64:
			return "lightbulbgoal";
		case 90:
			return "oystergoal";
		case 92:
			return "metalcrategoal";
		case 95:
			return "honeygoal";
		case 96:
		case 97:
			return "diamondgoal";
		case 98:
			return "billboardgoal";
		case 99:
			return "stonegoal";
		case 76:
			return "soapgoal";
		case 77:
			return "molegoal";
		case 78:
			return "penguingoal";
		case 54:
			return "birdgoal";
		case 55:
		case 56:
		case 57:
		case 58:
		case 59:
		case 60:
			return "potiongoal";
		case 51:
			return "ufogoal";
		case 48:
			return "hanoigoal";
		case 47:
			return "giftgoal";
		case 80:
			return "coconutgoal";
		case 68:
			return "ivygoal";
		case 35:
		case 36:
		case 37:
		case 38:
		case 39:
		case 40:
			return "vasegoal";
		case 34:
			return "chaingoal";
		case 179:
			return "washergoal";
		case 281:
		case 284:
		case 287:
		case 290:
		case 293:
			return "tubegoal";
		case 193:
			return "loggoal";
		case 120:
			return "potgoal";
		case 32:
			return "goldgoal";
		case 140:
			return "elixirgoal";
		default:
			return string.Empty;
		}
	}
}
