using System;

public class EJJALOKPAKK : LNKPCJLANAO
{
	private KLKJHFKJLEM DHNJFHPNJLM;

	private KLKJHFKJLEM LLODPDNFMAJ;

	private KLKJHFKJLEM KAGMKMPKBAL;

	public KLKJHFKJLEM LMJPMDMLPNH
	{
		get
		{
			return DHNJFHPNJLM;
		}
	}

	public KLKJHFKJLEM NMOPCALFIDG
	{
		get
		{
			return LLODPDNFMAJ;
		}
	}

	public KLKJHFKJLEM CMOPFOEELDE
	{
		get
		{
			return KAGMKMPKBAL;
		}
	}

	public EJJALOKPAKK(KLKJHFKJLEM DHNJFHPNJLM, KLKJHFKJLEM LLODPDNFMAJ)
		: this(DHNJFHPNJLM, LLODPDNFMAJ, null)
	{
	}

	public EJJALOKPAKK(KLKJHFKJLEM DHNJFHPNJLM, KLKJHFKJLEM LLODPDNFMAJ, KLKJHFKJLEM KAGMKMPKBAL)
	{
		if (DHNJFHPNJLM == null)
		{
			throw new ArgumentNullException("publicKeyParamSet");
		}
		if (LLODPDNFMAJ == null)
		{
			throw new ArgumentNullException("digestParamSet");
		}
		this.DHNJFHPNJLM = DHNJFHPNJLM;
		this.LLODPDNFMAJ = LLODPDNFMAJ;
		this.KAGMKMPKBAL = KAGMKMPKBAL;
	}

	public EJJALOKPAKK(ALLINHNNNJN MIABODPHOIP)
	{
		DHNJFHPNJLM = (KLKJHFKJLEM)MIABODPHOIP.ECNCPJGHBIG(0);
		LLODPDNFMAJ = (KLKJHFKJLEM)MIABODPHOIP.ECNCPJGHBIG(1);
		if (MIABODPHOIP.GMCGMPEEHJP > 2)
		{
			KAGMKMPKBAL = (KLKJHFKJLEM)MIABODPHOIP.ECNCPJGHBIG(2);
		}
	}

	public static EJJALOKPAKK BJLJCGFMFOO(PAANMJLACEF NEMEKIOEOLC, bool DHGLJHFEJFL)
	{
		return BJLJCGFMFOO(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC, DHGLJHFEJFL));
	}

	public static EJJALOKPAKK BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC == null || NEMEKIOEOLC is EJJALOKPAKK)
		{
			return (EJJALOKPAKK)NEMEKIOEOLC;
		}
		if (NEMEKIOEOLC is ALLINHNNNJN)
		{
			return new EJJALOKPAKK((ALLINHNNNJN)NEMEKIOEOLC);
		}
		throw new ArgumentException("Invalid GOST3410Parameter: " + LHFGHNFJIKM.JKHOEKAOLPM(NEMEKIOEOLC));
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		DLDBGGDLOOO dLDBGGDLOOO = new DLDBGGDLOOO(DHNJFHPNJLM, LLODPDNFMAJ);
		if (KAGMKMPKBAL != null)
		{
			dLDBGGDLOOO.JEACJNAKLDJ(KAGMKMPKBAL);
		}
		return new KOGPLMALOEH(dLDBGGDLOOO);
	}
}
