using System;

public abstract class EJLHHPBLEMF : JDPBBBGMMMP
{
	protected EJLHHPBLEMF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
	}

	protected EJLHHPBLEMF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override bool MMFMOOHIGNJ()
	{
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE3 = bHPIABAGAPB.JEHECJGFJEB;
		KBINBLGGLNE kBINBLGGLNE4 = bHPIABAGAPB.FPKDKHJKEEF;
		int num = bHPIABAGAPB.DHBHKHGFIKI;
		KBINBLGGLNE kBINBLGGLNE7;
		KBINBLGGLNE kBINBLGGLNE6;
		if (num == 6)
		{
			KBINBLGGLNE kBINBLGGLNE5 = base.LAMGGDKLPJH[0];
			bool flag = kBINBLGGLNE5.EOJCHPEGABD;
			if (kBINBLGGLNE.EJJHHCOFAAI)
			{
				kBINBLGGLNE6 = kBINBLGGLNE2.MIOEHGDPGAG();
				kBINBLGGLNE7 = kBINBLGGLNE4;
				if (!flag)
				{
					KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE5.MIOEHGDPGAG();
					kBINBLGGLNE7 = kBINBLGGLNE7.IBJBIGNPNEM(bCIHLCMFAEK);
				}
			}
			else
			{
				KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE2;
				KBINBLGGLNE kBINBLGGLNE9 = kBINBLGGLNE.MIOEHGDPGAG();
				if (flag)
				{
					kBINBLGGLNE6 = kBINBLGGLNE8.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE8).JEACJNAKLDJ(kBINBLGGLNE3);
					kBINBLGGLNE7 = kBINBLGGLNE9.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE4);
				}
				else
				{
					KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE5.MIOEHGDPGAG();
					KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE10.MIOEHGDPGAG();
					kBINBLGGLNE6 = kBINBLGGLNE8.JEACJNAKLDJ(kBINBLGGLNE5).CIDGMJAFLHM(kBINBLGGLNE8, kBINBLGGLNE3, kBINBLGGLNE10);
					kBINBLGGLNE7 = kBINBLGGLNE9.FGLCIBKKKFF(kBINBLGGLNE4, cNLILOEEBOJ);
				}
				kBINBLGGLNE6 = kBINBLGGLNE6.IBJBIGNPNEM(kBINBLGGLNE9);
			}
		}
		else
		{
			kBINBLGGLNE6 = kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE).IBJBIGNPNEM(kBINBLGGLNE2);
			switch (num)
			{
			case 1:
			{
				KBINBLGGLNE kBINBLGGLNE11 = base.LAMGGDKLPJH[0];
				if (!kBINBLGGLNE11.EOJCHPEGABD)
				{
					KBINBLGGLNE bCIHLCMFAEK2 = kBINBLGGLNE11.MIOEHGDPGAG();
					KBINBLGGLNE bCIHLCMFAEK3 = kBINBLGGLNE11.IBJBIGNPNEM(bCIHLCMFAEK2);
					kBINBLGGLNE6 = kBINBLGGLNE6.IBJBIGNPNEM(kBINBLGGLNE11);
					kBINBLGGLNE3 = kBINBLGGLNE3.IBJBIGNPNEM(kBINBLGGLNE11);
					kBINBLGGLNE4 = kBINBLGGLNE4.IBJBIGNPNEM(bCIHLCMFAEK3);
				}
				break;
			}
			default:
				throw new InvalidOperationException("unsupported coordinate system");
			case 0:
				break;
			}
			kBINBLGGLNE7 = kBINBLGGLNE.JEACJNAKLDJ(kBINBLGGLNE3).IBJBIGNPNEM(kBINBLGGLNE.MIOEHGDPGAG()).JEACJNAKLDJ(kBINBLGGLNE4);
		}
		return kBINBLGGLNE6.KIFDKLPDKMD(kBINBLGGLNE7);
	}

	public override JGAFKLGGBGF FLDLCFHBMEA(KBINBLGGLNE HJLOCAEAFMJ)
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		switch (FMBBJLCHHDI)
		{
		case 5:
		{
			KBINBLGGLNE kBINBLGGLNE5 = base.NBPANDNEJGI;
			KBINBLGGLNE kBINBLGGLNE6 = base.FIJLKLCHMGH;
			KBINBLGGLNE bCIHLCMFAEK2 = kBINBLGGLNE5.IBJBIGNPNEM(HJLOCAEAFMJ);
			KBINBLGGLNE cNLILOEEBOJ2 = kBINBLGGLNE6.JEACJNAKLDJ(kBINBLGGLNE5).MCPDGENJCDB(HJLOCAEAFMJ).JEACJNAKLDJ(bCIHLCMFAEK2);
			return ECFGFKNLLGH.IMOPAOHAOAN(kBINBLGGLNE5, cNLILOEEBOJ2, base.LAMGGDKLPJH, base.BPGGHHMMCCB);
		}
		case 6:
		{
			KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
			KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE.IBJBIGNPNEM(HJLOCAEAFMJ.MIOEHGDPGAG());
			KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE).JEACJNAKLDJ(bCIHLCMFAEK);
			KBINBLGGLNE kBINBLGGLNE4 = kBINBLGGLNE3.IBJBIGNPNEM(HJLOCAEAFMJ);
			return ECFGFKNLLGH.IMOPAOHAOAN(kBINBLGGLNE, cNLILOEEBOJ, new KBINBLGGLNE[1] { kBINBLGGLNE4 }, base.BPGGHHMMCCB);
		}
		default:
			return base.FLDLCFHBMEA(HJLOCAEAFMJ);
		}
	}

	public override JGAFKLGGBGF DEFAMIAKKGM(KBINBLGGLNE HJLOCAEAFMJ)
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		int num = FMBBJLCHHDI;
		if (num == 5 || num == 6)
		{
			KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE).IBJBIGNPNEM(HJLOCAEAFMJ).JEACJNAKLDJ(kBINBLGGLNE);
			return ECFGFKNLLGH.IMOPAOHAOAN(kBINBLGGLNE, cNLILOEEBOJ, base.LAMGGDKLPJH, base.BPGGHHMMCCB);
		}
		return base.DEFAMIAKKGM(HJLOCAEAFMJ);
	}

	public override JGAFKLGGBGF FBGIHKPECCO(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		return JEACJNAKLDJ(BCIHLCMFAEK.BHKOFHMDACN());
	}

	public virtual EJLHHPBLEMF MHEOOOAHMCC()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		int num = bHPIABAGAPB.DHBHKHGFIKI;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		switch (num)
		{
		case 0:
		case 5:
		{
			KBINBLGGLNE kBINBLGGLNE4 = base.FIJLKLCHMGH;
			return (EJLHHPBLEMF)bHPIABAGAPB.IMOPAOHAOAN(kBINBLGGLNE.MIOEHGDPGAG(), kBINBLGGLNE4.MIOEHGDPGAG(), base.BPGGHHMMCCB);
		}
		case 1:
		case 6:
		{
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
			return (EJLHHPBLEMF)bHPIABAGAPB.IMOPAOHAOAN(kBINBLGGLNE.MIOEHGDPGAG(), kBINBLGGLNE2.MIOEHGDPGAG(), new KBINBLGGLNE[1] { kBINBLGGLNE3.MIOEHGDPGAG() }, base.BPGGHHMMCCB);
		}
		default:
			throw new InvalidOperationException("unsupported coordinate system");
		}
	}

	public virtual EJLHHPBLEMF HHBAGDLPLMK(int DELAPGFJHAP)
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		int num = bHPIABAGAPB.DHBHKHGFIKI;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		switch (num)
		{
		case 0:
		case 5:
		{
			KBINBLGGLNE kBINBLGGLNE4 = base.FIJLKLCHMGH;
			return (EJLHHPBLEMF)bHPIABAGAPB.IMOPAOHAOAN(kBINBLGGLNE.LHPDNIJHMIA(DELAPGFJHAP), kBINBLGGLNE4.LHPDNIJHMIA(DELAPGFJHAP), base.BPGGHHMMCCB);
		}
		case 1:
		case 6:
		{
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
			return (EJLHHPBLEMF)bHPIABAGAPB.IMOPAOHAOAN(kBINBLGGLNE.LHPDNIJHMIA(DELAPGFJHAP), kBINBLGGLNE2.LHPDNIJHMIA(DELAPGFJHAP), new KBINBLGGLNE[1] { kBINBLGGLNE3.LHPDNIJHMIA(DELAPGFJHAP) }, base.BPGGHHMMCCB);
		}
		default:
			throw new InvalidOperationException("unsupported coordinate system");
		}
	}
}
