public interface EKFAMINKCJP
{
	void DIOELAHNLKJ(CGDEGBGOKJO MBEMNOCDDBC);

	byte[] MKEBGONJHED(COEMJAGOFJJ JMNLHNOGILL, byte[] DCJNMBCPFFL);

	byte[] MKEBGONJHED(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ JMNLHNOGILL, byte[] AIELCDIFLFB);

	bool JNKONIDOPKE(byte[] DIJNMJINHIL, COEMJAGOFJJ ECPKCNOAOAJ, byte[] DCJNMBCPFFL);

	bool JNKONIDOPKE(FBMKOGABPFL ADLMOHOLCGL, byte[] DIJNMJINHIL, COEMJAGOFJJ ECPKCNOAOAJ, byte[] AIELCDIFLFB);

	OHPHNNNHCOO GBJMMNPHHNN(COEMJAGOFJJ JMNLHNOGILL);

	OHPHNNNHCOO GBJMMNPHHNN(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ JMNLHNOGILL);

	OHPHNNNHCOO OPKHBIHFBMM(COEMJAGOFJJ ECPKCNOAOAJ);

	OHPHNNNHCOO OPKHBIHFBMM(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ ECPKCNOAOAJ);

	bool GNODDNDEEMI(COEMJAGOFJJ ECPKCNOAOAJ);
}
