using System;

public class ELABOMJGNNG : LNKPCJLANAO
{
	private readonly JMPONGHEGOK FFIEFFCCBNM;

	private readonly CHNGNKJDNDE ACDEOJHPLHB;

	public JMPONGHEGOK NFFNAJHHCOA
	{
		get
		{
			return FFIEFFCCBNM;
		}
	}

	public CHNGNKJDNDE EJOJJNHDNDL
	{
		get
		{
			return ACDEOJHPLHB;
		}
	}

	public ELABOMJGNNG(JMPONGHEGOK FFIEFFCCBNM, CHNGNKJDNDE ACDEOJHPLHB)
	{
		if (FFIEFFCCBNM == null)
		{
			throw new ArgumentNullException("responseStatus");
		}
		this.FFIEFFCCBNM = FFIEFFCCBNM;
		this.ACDEOJHPLHB = ACDEOJHPLHB;
	}

	private ELABOMJGNNG(ALLINHNNNJN MIABODPHOIP)
	{
		FFIEFFCCBNM = new JMPONGHEGOK(DLICBBHNDFH.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(0)));
		if (MIABODPHOIP.GMCGMPEEHJP == 2)
		{
			ACDEOJHPLHB = CHNGNKJDNDE.BJLJCGFMFOO((PAANMJLACEF)MIABODPHOIP.ECNCPJGHBIG(1), true);
		}
	}

	public static ELABOMJGNNG BJLJCGFMFOO(PAANMJLACEF NEMEKIOEOLC, bool DHGLJHFEJFL)
	{
		return BJLJCGFMFOO(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC, DHGLJHFEJFL));
	}

	public static ELABOMJGNNG BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC == null || NEMEKIOEOLC is ELABOMJGNNG)
		{
			return (ELABOMJGNNG)NEMEKIOEOLC;
		}
		if (NEMEKIOEOLC is ALLINHNNNJN)
		{
			return new ELABOMJGNNG((ALLINHNNNJN)NEMEKIOEOLC);
		}
		throw new ArgumentException("unknown object in factory: " + LHFGHNFJIKM.JKHOEKAOLPM(NEMEKIOEOLC), "obj");
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		DLDBGGDLOOO dLDBGGDLOOO = new DLDBGGDLOOO(FFIEFFCCBNM);
		if (ACDEOJHPLHB != null)
		{
			dLDBGGDLOOO.JEACJNAKLDJ(new JIHIOOKBBLB(true, 0, ACDEOJHPLHB));
		}
		return new KOGPLMALOEH(dLDBGGDLOOO);
	}
}
