public interface ELGNLPAGPNI
{
	string FKBFIEIHPOB { get; }

	void DIOELAHNLKJ(FBIJJFGLKMK GECCLOFELEC);

	int MDNFIGPPOFC(byte[] MOPCLEEGDFB, int ELICNEDIBGB);

	int HIEMLFAHLFO(byte[] MOPCLEEGDFB);
}
