public interface ENDHCNJKMOL
{
	void GMFBMHLENMN(byte[] HJBOEOOLOOE);

	void GMFBMHLENMN(long HJBOEOOLOOE);

	void GOADFPHGDJG(byte[] DIPNEDDIHBK);

	void GOADFPHGDJG(byte[] DIPNEDDIHBK, int EHGOOEHDNMM, int NBEDPKHALCN);
}
