using System;

public class ENNJDNNBHPM : OHPHNNNHCOO
{
	public const byte CJEMBIDPFHM = 188;

	private readonly BJLAMONNNDD KCBCJIKBIPJ;

	private readonly BJLAMONNNDD LCOLDHJDDJC;

	private readonly BJLAMONNNDD HDILOJEEJMD;

	private readonly DGCIOOEELCP IEDPBFAFGGJ;

	private FBIJJFGLKMK GECCLOFELEC;

	private int MBLEFHKDJLO;

	private int HKMLPJIIJKN;

	private int KIANHAHHEGN;

	private bool CGGCHAGCOAB;

	private int JCIOBGKEDJE;

	private byte[] FPPIFEACFOK;

	private byte[] CLJLEJDBFKN;

	private byte[] OJEJPICFOOJ;

	private byte EHGIDJJNLAM;

	public virtual string KFKMEPMEBND
	{
		get
		{
			return HDILOJEEJMD.KFKMEPMEBND + "withRSAandMGF1";
		}
	}

	public ENNJDNNBHPM(DGCIOOEELCP IEDPBFAFGGJ, BJLAMONNNDD HABFKBCEIBN)
		: this(IEDPBFAFGGJ, HABFKBCEIBN, HABFKBCEIBN.EEMLLAMENHO())
	{
	}

	public ENNJDNNBHPM(DGCIOOEELCP IEDPBFAFGGJ, BJLAMONNNDD HABFKBCEIBN, int OGPGBDAMJPJ)
		: this(IEDPBFAFGGJ, HABFKBCEIBN, OGPGBDAMJPJ, 188)
	{
	}

	public ENNJDNNBHPM(DGCIOOEELCP IEDPBFAFGGJ, BJLAMONNNDD HABFKBCEIBN, byte[] FPPIFEACFOK)
		: this(IEDPBFAFGGJ, HABFKBCEIBN, HABFKBCEIBN, HABFKBCEIBN, FPPIFEACFOK.Length, FPPIFEACFOK, 188)
	{
	}

	public ENNJDNNBHPM(DGCIOOEELCP IEDPBFAFGGJ, BJLAMONNNDD BAGFEAPMCII, BJLAMONNNDD HDILOJEEJMD, int OGPGBDAMJPJ)
		: this(IEDPBFAFGGJ, BAGFEAPMCII, HDILOJEEJMD, OGPGBDAMJPJ, 188)
	{
	}

	public ENNJDNNBHPM(DGCIOOEELCP IEDPBFAFGGJ, BJLAMONNNDD BAGFEAPMCII, BJLAMONNNDD HDILOJEEJMD, byte[] FPPIFEACFOK)
		: this(IEDPBFAFGGJ, BAGFEAPMCII, BAGFEAPMCII, HDILOJEEJMD, FPPIFEACFOK.Length, FPPIFEACFOK, 188)
	{
	}

	public ENNJDNNBHPM(DGCIOOEELCP IEDPBFAFGGJ, BJLAMONNNDD HABFKBCEIBN, int OGPGBDAMJPJ, byte EHGIDJJNLAM)
		: this(IEDPBFAFGGJ, HABFKBCEIBN, HABFKBCEIBN, OGPGBDAMJPJ, 188)
	{
	}

	public ENNJDNNBHPM(DGCIOOEELCP IEDPBFAFGGJ, BJLAMONNNDD BAGFEAPMCII, BJLAMONNNDD HDILOJEEJMD, int OGPGBDAMJPJ, byte EHGIDJJNLAM)
		: this(IEDPBFAFGGJ, BAGFEAPMCII, BAGFEAPMCII, HDILOJEEJMD, OGPGBDAMJPJ, null, EHGIDJJNLAM)
	{
	}

	private ENNJDNNBHPM(DGCIOOEELCP IEDPBFAFGGJ, BJLAMONNNDD KCBCJIKBIPJ, BJLAMONNNDD LCOLDHJDDJC, BJLAMONNNDD HDILOJEEJMD, int OGPGBDAMJPJ, byte[] FPPIFEACFOK, byte EHGIDJJNLAM)
	{
		this.IEDPBFAFGGJ = IEDPBFAFGGJ;
		this.KCBCJIKBIPJ = KCBCJIKBIPJ;
		this.LCOLDHJDDJC = LCOLDHJDDJC;
		this.HDILOJEEJMD = HDILOJEEJMD;
		MBLEFHKDJLO = LCOLDHJDDJC.EEMLLAMENHO();
		HKMLPJIIJKN = HDILOJEEJMD.EEMLLAMENHO();
		KIANHAHHEGN = OGPGBDAMJPJ;
		CGGCHAGCOAB = FPPIFEACFOK != null;
		if (CGGCHAGCOAB)
		{
			this.FPPIFEACFOK = FPPIFEACFOK;
		}
		else
		{
			this.FPPIFEACFOK = new byte[OGPGBDAMJPJ];
		}
		CLJLEJDBFKN = new byte[8 + OGPGBDAMJPJ + MBLEFHKDJLO];
		this.EHGIDJJNLAM = EHGIDJJNLAM;
	}

	public static ENNJDNNBHPM CIIEDPIEFEJ(DGCIOOEELCP IEDPBFAFGGJ, BJLAMONNNDD HABFKBCEIBN)
	{
		return new ENNJDNNBHPM(IEDPBFAFGGJ, new OHAOIPKCMFC(), HABFKBCEIBN, HABFKBCEIBN, HABFKBCEIBN.EEMLLAMENHO(), null, 188);
	}

	public static ENNJDNNBHPM CIIEDPIEFEJ(DGCIOOEELCP IEDPBFAFGGJ, BJLAMONNNDD BAGFEAPMCII, BJLAMONNNDD HDILOJEEJMD, int OGPGBDAMJPJ, byte EHGIDJJNLAM)
	{
		return new ENNJDNNBHPM(IEDPBFAFGGJ, new OHAOIPKCMFC(), BAGFEAPMCII, HDILOJEEJMD, OGPGBDAMJPJ, null, EHGIDJJNLAM);
	}

	public virtual void DIOELAHNLKJ(bool KGPBDABMHKH, IGMAJHKIIPK IJJHBEECMBP)
	{
		if (IJJHBEECMBP is MDAKJDOFCEP)
		{
			MDAKJDOFCEP mDAKJDOFCEP = (MDAKJDOFCEP)IJJHBEECMBP;
			IJJHBEECMBP = mDAKJDOFCEP.KPJHHAAOFOH;
			GECCLOFELEC = mDAKJDOFCEP.IPFKDIJBGIM;
		}
		else if (KGPBDABMHKH)
		{
			GECCLOFELEC = new FBIJJFGLKMK();
		}
		IEDPBFAFGGJ.DIOELAHNLKJ(KGPBDABMHKH, IJJHBEECMBP);
		PLGGNEJEIIP pLGGNEJEIIP = ((!(IJJHBEECMBP is COGKEFIDDGF)) ? ((PLGGNEJEIIP)IJJHBEECMBP) : ((COGKEFIDDGF)IJJHBEECMBP).OIDHEOJEMJF);
		JCIOBGKEDJE = pLGGNEJEIIP.FILOMPHGFKD.BitLength - 1;
		if (JCIOBGKEDJE < 8 * MBLEFHKDJLO + 8 * KIANHAHHEGN + 9)
		{
			throw new ArgumentException("key too small for specified hash and salt lengths");
		}
		OJEJPICFOOJ = new byte[(JCIOBGKEDJE + 7) / 8];
	}

	private void JKBFMHJLGDI(byte[] OJEJPICFOOJ)
	{
		Array.Clear(OJEJPICFOOJ, 0, OJEJPICFOOJ.Length);
	}

	public virtual void BPAJGOINFNL(byte MOPCLEEGDFB)
	{
		KCBCJIKBIPJ.BPAJGOINFNL(MOPCLEEGDFB);
	}

	public virtual void GONEEEFEDGF(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int EOFAGACBNFP)
	{
		KCBCJIKBIPJ.GONEEEFEDGF(MOPCLEEGDFB, ELICNEDIBGB, EOFAGACBNFP);
	}

	public virtual void OMOKOKFNBKI()
	{
		KCBCJIKBIPJ.OMOKOKFNBKI();
	}

	public virtual byte[] HMJHAKCMGHC()
	{
		KCBCJIKBIPJ.LCNOFBMOHHM(CLJLEJDBFKN, CLJLEJDBFKN.Length - MBLEFHKDJLO - KIANHAHHEGN);
		if (KIANHAHHEGN != 0)
		{
			if (!CGGCHAGCOAB)
			{
				GECCLOFELEC.NextBytes(FPPIFEACFOK);
			}
			FPPIFEACFOK.CopyTo(CLJLEJDBFKN, CLJLEJDBFKN.Length - KIANHAHHEGN);
		}
		byte[] array = new byte[MBLEFHKDJLO];
		LCOLDHJDDJC.GONEEEFEDGF(CLJLEJDBFKN, 0, CLJLEJDBFKN.Length);
		LCOLDHJDDJC.LCNOFBMOHHM(array, 0);
		OJEJPICFOOJ[OJEJPICFOOJ.Length - KIANHAHHEGN - 1 - MBLEFHKDJLO - 1] = 1;
		FPPIFEACFOK.CopyTo(OJEJPICFOOJ, OJEJPICFOOJ.Length - KIANHAHHEGN - MBLEFHKDJLO - 1);
		byte[] array2 = JFBIEBKCCLD(array, 0, array.Length, OJEJPICFOOJ.Length - MBLEFHKDJLO - 1);
		for (int i = 0; i != array2.Length; i++)
		{
			OJEJPICFOOJ[i] ^= array2[i];
		}
		OJEJPICFOOJ[0] &= (byte)(255 >> OJEJPICFOOJ.Length * 8 - JCIOBGKEDJE);
		array.CopyTo(OJEJPICFOOJ, OJEJPICFOOJ.Length - MBLEFHKDJLO - 1);
		OJEJPICFOOJ[OJEJPICFOOJ.Length - 1] = EHGIDJJNLAM;
		byte[] result = IEDPBFAFGGJ.DPACJDFHLKB(OJEJPICFOOJ, 0, OJEJPICFOOJ.Length);
		JKBFMHJLGDI(OJEJPICFOOJ);
		return result;
	}

	public virtual bool HLJBBONKPDG(byte[] PINNJBGMGOA)
	{
		KCBCJIKBIPJ.LCNOFBMOHHM(CLJLEJDBFKN, CLJLEJDBFKN.Length - MBLEFHKDJLO - KIANHAHHEGN);
		byte[] array = IEDPBFAFGGJ.DPACJDFHLKB(PINNJBGMGOA, 0, PINNJBGMGOA.Length);
		array.CopyTo(OJEJPICFOOJ, OJEJPICFOOJ.Length - array.Length);
		if (OJEJPICFOOJ[OJEJPICFOOJ.Length - 1] != EHGIDJJNLAM)
		{
			JKBFMHJLGDI(OJEJPICFOOJ);
			return false;
		}
		byte[] array2 = JFBIEBKCCLD(OJEJPICFOOJ, OJEJPICFOOJ.Length - MBLEFHKDJLO - 1, MBLEFHKDJLO, OJEJPICFOOJ.Length - MBLEFHKDJLO - 1);
		for (int i = 0; i != array2.Length; i++)
		{
			OJEJPICFOOJ[i] ^= array2[i];
		}
		OJEJPICFOOJ[0] &= (byte)(255 >> OJEJPICFOOJ.Length * 8 - JCIOBGKEDJE);
		for (int j = 0; j != OJEJPICFOOJ.Length - MBLEFHKDJLO - KIANHAHHEGN - 2; j++)
		{
			if (OJEJPICFOOJ[j] != 0)
			{
				JKBFMHJLGDI(OJEJPICFOOJ);
				return false;
			}
		}
		if (OJEJPICFOOJ[OJEJPICFOOJ.Length - MBLEFHKDJLO - KIANHAHHEGN - 2] != 1)
		{
			JKBFMHJLGDI(OJEJPICFOOJ);
			return false;
		}
		if (CGGCHAGCOAB)
		{
			Array.Copy(FPPIFEACFOK, 0, CLJLEJDBFKN, CLJLEJDBFKN.Length - KIANHAHHEGN, KIANHAHHEGN);
		}
		else
		{
			Array.Copy(OJEJPICFOOJ, OJEJPICFOOJ.Length - KIANHAHHEGN - MBLEFHKDJLO - 1, CLJLEJDBFKN, CLJLEJDBFKN.Length - KIANHAHHEGN, KIANHAHHEGN);
		}
		LCOLDHJDDJC.GONEEEFEDGF(CLJLEJDBFKN, 0, CLJLEJDBFKN.Length);
		LCOLDHJDDJC.LCNOFBMOHHM(CLJLEJDBFKN, CLJLEJDBFKN.Length - MBLEFHKDJLO);
		int num = OJEJPICFOOJ.Length - MBLEFHKDJLO - 1;
		for (int k = CLJLEJDBFKN.Length - MBLEFHKDJLO; k != CLJLEJDBFKN.Length; k++)
		{
			if ((OJEJPICFOOJ[num] ^ CLJLEJDBFKN[k]) != 0)
			{
				JKBFMHJLGDI(CLJLEJDBFKN);
				JKBFMHJLGDI(OJEJPICFOOJ);
				return false;
			}
			num++;
		}
		JKBFMHJLGDI(CLJLEJDBFKN);
		JKBFMHJLGDI(OJEJPICFOOJ);
		return true;
	}

	private void IMOMLPKFALE(int PLCFEOMGCFK, byte[] ELHJELHHEFJ)
	{
		ELHJELHHEFJ[0] = (byte)((uint)PLCFEOMGCFK >> 24);
		ELHJELHHEFJ[1] = (byte)((uint)PLCFEOMGCFK >> 16);
		ELHJELHHEFJ[2] = (byte)((uint)PLCFEOMGCFK >> 8);
		ELHJELHHEFJ[3] = (byte)((uint)PLCFEOMGCFK >> 0);
	}

	private byte[] JFBIEBKCCLD(byte[] NMLDCCMBKAD, int NDAAKFPMLOL, int DIDEHKCMHBA, int EOFAGACBNFP)
	{
		byte[] array = new byte[EOFAGACBNFP];
		byte[] array2 = new byte[HKMLPJIIJKN];
		byte[] array3 = new byte[4];
		int i = 0;
		HDILOJEEJMD.OMOKOKFNBKI();
		for (; i < EOFAGACBNFP / HKMLPJIIJKN; i++)
		{
			IMOMLPKFALE(i, array3);
			HDILOJEEJMD.GONEEEFEDGF(NMLDCCMBKAD, NDAAKFPMLOL, DIDEHKCMHBA);
			HDILOJEEJMD.GONEEEFEDGF(array3, 0, array3.Length);
			HDILOJEEJMD.LCNOFBMOHHM(array2, 0);
			array2.CopyTo(array, i * HKMLPJIIJKN);
		}
		if (i * HKMLPJIIJKN < EOFAGACBNFP)
		{
			IMOMLPKFALE(i, array3);
			HDILOJEEJMD.GONEEEFEDGF(NMLDCCMBKAD, NDAAKFPMLOL, DIDEHKCMHBA);
			HDILOJEEJMD.GONEEEFEDGF(array3, 0, array3.Length);
			HDILOJEEJMD.LCNOFBMOHHM(array2, 0);
			Array.Copy(array2, 0, array, i * HKMLPJIIJKN, array.Length - i * HKMLPJIIJKN);
		}
		return array;
	}
}
