using System.Collections.Generic;
using Assets.Scripts.GamePlayScene.Mechanics;
using UnityEngine;

public static class EOIJMLHFJMH
{
	private static readonly List<List<Vector2>> AHPBBKNJEBO;

	static EOIJMLHFJMH()
	{
		AHPBBKNJEBO = new List<List<Vector2>>();
		List<Vector2> list;
		AHPBBKNJEBO.Add(list = new List<Vector2>());
		list.Add(new Vector2(-1f, -1f));
		list.Add(new Vector2(-1f, 0f));
		list.Add(new Vector2(-1f, 1f));
		list.Add(new Vector2(0f, -1f));
		list.Add(new Vector2(0f, 1f));
		list.Add(new Vector2(1f, -1f));
		list.Add(new Vector2(1f, 0f));
		list.Add(new Vector2(1f, 1f));
		AHPBBKNJEBO.Add(list = new List<Vector2>());
		list.Add(new Vector2(-2f, -1f));
		list.Add(new Vector2(-2f, 0f));
		list.Add(new Vector2(-2f, 1f));
		list.Add(new Vector2(-1f, -2f));
		list.Add(new Vector2(-1f, 2f));
		list.Add(new Vector2(0f, -2f));
		list.Add(new Vector2(0f, 2f));
		list.Add(new Vector2(1f, -2f));
		list.Add(new Vector2(1f, 2f));
		list.Add(new Vector2(2f, -1f));
		list.Add(new Vector2(2f, 0f));
		list.Add(new Vector2(2f, 1f));
		AHPBBKNJEBO.Add(list = new List<Vector2>());
		list.Add(new Vector2(-3f, -1f));
		list.Add(new Vector2(-3f, 0f));
		list.Add(new Vector2(-3f, 1f));
		list.Add(new Vector2(-2f, -2f));
		list.Add(new Vector2(-2f, 2f));
		list.Add(new Vector2(-1f, -3f));
		list.Add(new Vector2(-1f, 3f));
		list.Add(new Vector2(0f, -3f));
		list.Add(new Vector2(0f, 3f));
		list.Add(new Vector2(1f, -3f));
		list.Add(new Vector2(1f, 3f));
		list.Add(new Vector2(2f, -2f));
		list.Add(new Vector2(2f, 2f));
		list.Add(new Vector2(3f, -1f));
		list.Add(new Vector2(3f, 0f));
		list.Add(new Vector2(3f, 1f));
		AHPBBKNJEBO.Add(list = new List<Vector2>());
		list.Add(new Vector2(-4f, -1f));
		list.Add(new Vector2(-4f, 0f));
		list.Add(new Vector2(-4f, 1f));
		list.Add(new Vector2(-3f, -3f));
		list.Add(new Vector2(-3f, -2f));
		list.Add(new Vector2(-3f, 2f));
		list.Add(new Vector2(-3f, 3f));
		list.Add(new Vector2(-2f, -3f));
		list.Add(new Vector2(-2f, 3f));
		list.Add(new Vector2(-1f, -4f));
		list.Add(new Vector2(-1f, 4f));
		list.Add(new Vector2(0f, -4f));
		list.Add(new Vector2(0f, 4f));
		list.Add(new Vector2(1f, -4f));
		list.Add(new Vector2(1f, 4f));
		list.Add(new Vector2(2f, -3f));
		list.Add(new Vector2(2f, 3f));
		list.Add(new Vector2(3f, -3f));
		list.Add(new Vector2(3f, -2f));
		list.Add(new Vector2(3f, 2f));
		list.Add(new Vector2(3f, 3f));
		list.Add(new Vector2(4f, -1f));
		list.Add(new Vector2(4f, 0f));
		list.Add(new Vector2(4f, 1f));
		AHPBBKNJEBO.Add(list = new List<Vector2>());
		list.Add(new Vector2(-5f, -2f));
		list.Add(new Vector2(-5f, -1f));
		list.Add(new Vector2(-5f, 0f));
		list.Add(new Vector2(-5f, 1f));
		list.Add(new Vector2(-5f, 2f));
		list.Add(new Vector2(-4f, -3f));
		list.Add(new Vector2(-4f, -2f));
		list.Add(new Vector2(-4f, 2f));
		list.Add(new Vector2(-4f, 3f));
		list.Add(new Vector2(-3f, -4f));
		list.Add(new Vector2(-3f, 4f));
		list.Add(new Vector2(-2f, -5f));
		list.Add(new Vector2(-2f, -4f));
		list.Add(new Vector2(-2f, 4f));
		list.Add(new Vector2(-2f, 5f));
		list.Add(new Vector2(-1f, -5f));
		list.Add(new Vector2(-1f, 5f));
		list.Add(new Vector2(0f, -5f));
		list.Add(new Vector2(0f, 5f));
		list.Add(new Vector2(1f, -5f));
		list.Add(new Vector2(1f, 5f));
		list.Add(new Vector2(2f, -5f));
		list.Add(new Vector2(2f, -4f));
		list.Add(new Vector2(2f, 4f));
		list.Add(new Vector2(2f, 5f));
		list.Add(new Vector2(3f, -4f));
		list.Add(new Vector2(3f, 4f));
		list.Add(new Vector2(4f, -3f));
		list.Add(new Vector2(4f, -2f));
		list.Add(new Vector2(4f, 2f));
		list.Add(new Vector2(4f, 3f));
		list.Add(new Vector2(5f, -2f));
		list.Add(new Vector2(5f, -1f));
		list.Add(new Vector2(5f, 0f));
		list.Add(new Vector2(5f, 1f));
		list.Add(new Vector2(5f, 2f));
		AHPBBKNJEBO.Add(list = new List<Vector2>());
		list.Add(new Vector2(-6f, -2f));
		list.Add(new Vector2(-6f, -1f));
		list.Add(new Vector2(-6f, 0f));
		list.Add(new Vector2(-6f, 1f));
		list.Add(new Vector2(-6f, 2f));
		list.Add(new Vector2(-5f, -4f));
		list.Add(new Vector2(-5f, -3f));
		list.Add(new Vector2(-5f, 3f));
		list.Add(new Vector2(-5f, 4f));
		list.Add(new Vector2(-4f, -5f));
		list.Add(new Vector2(-4f, -4f));
		list.Add(new Vector2(-4f, 4f));
		list.Add(new Vector2(-4f, 5f));
		list.Add(new Vector2(-3f, -5f));
		list.Add(new Vector2(-3f, 5f));
		list.Add(new Vector2(-2f, -6f));
		list.Add(new Vector2(-2f, 6f));
		list.Add(new Vector2(-1f, -6f));
		list.Add(new Vector2(-1f, 6f));
		list.Add(new Vector2(0f, -6f));
		list.Add(new Vector2(0f, 6f));
		list.Add(new Vector2(1f, -6f));
		list.Add(new Vector2(1f, 6f));
		list.Add(new Vector2(2f, -6f));
		list.Add(new Vector2(2f, 6f));
		list.Add(new Vector2(3f, -5f));
		list.Add(new Vector2(3f, 5f));
		list.Add(new Vector2(4f, -5f));
		list.Add(new Vector2(4f, -4f));
		list.Add(new Vector2(4f, 4f));
		list.Add(new Vector2(4f, 5f));
		list.Add(new Vector2(5f, -4f));
		list.Add(new Vector2(5f, -3f));
		list.Add(new Vector2(5f, 3f));
		list.Add(new Vector2(5f, 4f));
		list.Add(new Vector2(6f, -2f));
		list.Add(new Vector2(6f, -1f));
		list.Add(new Vector2(6f, 0f));
		list.Add(new Vector2(6f, 1f));
		list.Add(new Vector2(6f, 2f));
		AHPBBKNJEBO.Add(list = new List<Vector2>());
		list.Add(new Vector2(-7f, -2f));
		list.Add(new Vector2(-7f, -1f));
		list.Add(new Vector2(-7f, 0f));
		list.Add(new Vector2(-7f, 1f));
		list.Add(new Vector2(-7f, 2f));
		list.Add(new Vector2(-6f, -4f));
		list.Add(new Vector2(-6f, -3f));
		list.Add(new Vector2(-6f, 3f));
		list.Add(new Vector2(-6f, 4f));
		list.Add(new Vector2(-5f, -5f));
		list.Add(new Vector2(-5f, 5f));
		list.Add(new Vector2(-4f, -6f));
		list.Add(new Vector2(-4f, 6f));
		list.Add(new Vector2(-3f, -6f));
		list.Add(new Vector2(-3f, 6f));
		list.Add(new Vector2(-2f, -7f));
		list.Add(new Vector2(-2f, 7f));
		list.Add(new Vector2(-1f, -7f));
		list.Add(new Vector2(-1f, 7f));
		list.Add(new Vector2(0f, -7f));
		list.Add(new Vector2(0f, 7f));
		list.Add(new Vector2(1f, -7f));
		list.Add(new Vector2(1f, 7f));
		list.Add(new Vector2(2f, -7f));
		list.Add(new Vector2(2f, 7f));
		list.Add(new Vector2(3f, -6f));
		list.Add(new Vector2(3f, 6f));
		list.Add(new Vector2(4f, -6f));
		list.Add(new Vector2(4f, 6f));
		list.Add(new Vector2(5f, -5f));
		list.Add(new Vector2(5f, 5f));
		list.Add(new Vector2(6f, -4f));
		list.Add(new Vector2(6f, -3f));
		list.Add(new Vector2(6f, 3f));
		list.Add(new Vector2(6f, 4f));
		list.Add(new Vector2(7f, -2f));
		list.Add(new Vector2(7f, -1f));
		list.Add(new Vector2(7f, 0f));
		list.Add(new Vector2(7f, 1f));
		list.Add(new Vector2(7f, 2f));
		AHPBBKNJEBO.Add(list = new List<Vector2>());
		list.Add(new Vector2(-8f, -2f));
		list.Add(new Vector2(-8f, -1f));
		list.Add(new Vector2(-8f, 0f));
		list.Add(new Vector2(-8f, 1f));
		list.Add(new Vector2(-8f, 2f));
		list.Add(new Vector2(-7f, -4f));
		list.Add(new Vector2(-7f, -3f));
		list.Add(new Vector2(-7f, 3f));
		list.Add(new Vector2(-7f, 4f));
		list.Add(new Vector2(-6f, -5f));
		list.Add(new Vector2(-6f, 5f));
		list.Add(new Vector2(-5f, -6f));
		list.Add(new Vector2(-5f, 6f));
		list.Add(new Vector2(-4f, -7f));
		list.Add(new Vector2(-4f, 7f));
		list.Add(new Vector2(-3f, -7f));
		list.Add(new Vector2(-3f, 7f));
		list.Add(new Vector2(-2f, -8f));
		list.Add(new Vector2(-2f, 8f));
		list.Add(new Vector2(-1f, -8f));
		list.Add(new Vector2(-1f, 8f));
		list.Add(new Vector2(0f, -8f));
		list.Add(new Vector2(0f, 8f));
		list.Add(new Vector2(1f, -8f));
		list.Add(new Vector2(1f, 8f));
		list.Add(new Vector2(2f, -8f));
		list.Add(new Vector2(2f, 8f));
		list.Add(new Vector2(3f, -7f));
		list.Add(new Vector2(3f, 7f));
		list.Add(new Vector2(4f, -7f));
		list.Add(new Vector2(4f, 7f));
		list.Add(new Vector2(5f, -6f));
		list.Add(new Vector2(5f, 6f));
		list.Add(new Vector2(6f, -5f));
		list.Add(new Vector2(6f, 5f));
		list.Add(new Vector2(7f, -4f));
		list.Add(new Vector2(7f, -3f));
		list.Add(new Vector2(7f, 3f));
		list.Add(new Vector2(7f, 4f));
		list.Add(new Vector2(8f, -2f));
		list.Add(new Vector2(8f, -1f));
		list.Add(new Vector2(8f, 0f));
		list.Add(new Vector2(8f, 1f));
		list.Add(new Vector2(8f, 2f));
		AHPBBKNJEBO.Add(list = new List<Vector2>());
		list.Add(new Vector2(-8f, -4f));
		list.Add(new Vector2(-8f, -3f));
		list.Add(new Vector2(-8f, 3f));
		list.Add(new Vector2(-8f, 4f));
		list.Add(new Vector2(-7f, -6f));
		list.Add(new Vector2(-7f, -5f));
		list.Add(new Vector2(-7f, 5f));
		list.Add(new Vector2(-7f, 6f));
		list.Add(new Vector2(-6f, -7f));
		list.Add(new Vector2(-6f, -6f));
		list.Add(new Vector2(-6f, 6f));
		list.Add(new Vector2(-6f, 7f));
		list.Add(new Vector2(-5f, -7f));
		list.Add(new Vector2(-5f, 7f));
		list.Add(new Vector2(-4f, -8f));
		list.Add(new Vector2(-4f, 8f));
		list.Add(new Vector2(-3f, -8f));
		list.Add(new Vector2(-3f, 8f));
		list.Add(new Vector2(3f, -8f));
		list.Add(new Vector2(3f, 8f));
		list.Add(new Vector2(4f, -8f));
		list.Add(new Vector2(4f, 8f));
		list.Add(new Vector2(5f, -7f));
		list.Add(new Vector2(5f, 7f));
		list.Add(new Vector2(6f, -7f));
		list.Add(new Vector2(6f, -6f));
		list.Add(new Vector2(6f, 6f));
		list.Add(new Vector2(6f, 7f));
		list.Add(new Vector2(7f, -6f));
		list.Add(new Vector2(7f, -5f));
		list.Add(new Vector2(7f, 5f));
		list.Add(new Vector2(7f, 6f));
		list.Add(new Vector2(8f, -4f));
		list.Add(new Vector2(8f, -3f));
		list.Add(new Vector2(8f, 3f));
		list.Add(new Vector2(8f, 4f));
		AHPBBKNJEBO.Add(list = new List<Vector2>());
		list.Add(new Vector2(-8f, -8f));
		list.Add(new Vector2(-8f, -7f));
		list.Add(new Vector2(-8f, -6f));
		list.Add(new Vector2(-8f, -5f));
		list.Add(new Vector2(-8f, 5f));
		list.Add(new Vector2(-8f, 6f));
		list.Add(new Vector2(-8f, 7f));
		list.Add(new Vector2(-8f, 8f));
		list.Add(new Vector2(-7f, -8f));
		list.Add(new Vector2(-7f, -7f));
		list.Add(new Vector2(-7f, 7f));
		list.Add(new Vector2(-7f, 8f));
		list.Add(new Vector2(-6f, -8f));
		list.Add(new Vector2(-6f, 8f));
		list.Add(new Vector2(-5f, -8f));
		list.Add(new Vector2(-5f, 8f));
		list.Add(new Vector2(5f, -8f));
		list.Add(new Vector2(5f, 8f));
		list.Add(new Vector2(6f, -8f));
		list.Add(new Vector2(6f, 8f));
		list.Add(new Vector2(7f, -8f));
		list.Add(new Vector2(7f, -7f));
		list.Add(new Vector2(7f, 7f));
		list.Add(new Vector2(7f, 8f));
		list.Add(new Vector2(8f, -8f));
		list.Add(new Vector2(8f, -7f));
		list.Add(new Vector2(8f, -6f));
		list.Add(new Vector2(8f, -5f));
		list.Add(new Vector2(8f, 5f));
		list.Add(new Vector2(8f, 6f));
		list.Add(new Vector2(8f, 7f));
		list.Add(new Vector2(8f, 8f));
	}

	public static Dictionary<int, HashSet<Cell>> HMDAOHPIADP(this CFOIPDKEFMM GOAELFDHDGD, Cell MOGKDGNCGCG)
	{
		Dictionary<int, HashSet<Cell>> dictionary = new Dictionary<int, HashSet<Cell>>();
		for (int i = 0; i < AHPBBKNJEBO.Count; i++)
		{
			HashSet<Cell> hashSet = new HashSet<Cell>();
			List<Vector2> list = AHPBBKNJEBO[i];
			for (int j = 0; j < list.Count; j++)
			{
				Vector2 vector = list[j];
				int num = MOGKDGNCGCG.X + (int)vector.x;
				int num2 = MOGKDGNCGCG.Y + (int)vector.y;
				if (num < GOAELFDHDGD.EMFKAPJMDCC && num2 < GOAELFDHDGD.FHAMOHDEGMK && num >= 0 && num2 >= 0)
				{
					Cell cell = GOAELFDHDGD.ECNCPJGHBIG(num, num2);
					if (cell != null)
					{
						hashSet.Add(cell);
					}
				}
			}
			if (hashSet.Count > 0)
			{
				dictionary.Add(i, hashSet);
			}
		}
		return dictionary;
	}
}
