using System;

public class EOOFPENODOF : JMPFLJGHAIM
{
	private const int EAKPLNPDHHF = 16;

	private static readonly uint[] FNDFJANMAGF = new uint[4];

	private static readonly uint[] AGONMCHACLP = new uint[17]
	{
		128u, 27u, 54u, 108u, 216u, 171u, 77u, 154u, 47u, 94u,
		188u, 99u, 198u, 151u, 53u, 106u, 212u
	};

	private uint[] BGEDKGLJIGM = new uint[4];

	private uint[] AHOOKAFPJFI = new uint[4];

	private uint[] NBKBCDBIEAN = new uint[4];

	private bool MOBILIJAIEK;

	private bool FPNNDLKJION;

	public virtual string KFKMEPMEBND
	{
		get
		{
			return "Noekeon";
		}
	}

	public virtual bool ABNLKPDCGEF
	{
		get
		{
			return false;
		}
	}

	public EOOFPENODOF()
	{
		MOBILIJAIEK = false;
	}

	public virtual int BDIGGHEPIIP()
	{
		return 16;
	}

	public virtual void DIOELAHNLKJ(bool MAEALKEJALK, IGMAJHKIIPK IJJHBEECMBP)
	{
		if (!(IJJHBEECMBP is JEMNCGMEABF))
		{
			throw new ArgumentException("Invalid parameters passed to Noekeon init - " + LHFGHNFJIKM.JKHOEKAOLPM(IJJHBEECMBP), "parameters");
		}
		FPNNDLKJION = MAEALKEJALK;
		MOBILIJAIEK = true;
		JEMNCGMEABF jEMNCGMEABF = (JEMNCGMEABF)IJJHBEECMBP;
		LHCPMMKLJGA(jEMNCGMEABF.MEGBFHFMBFI());
	}

	public virtual int DPACJDFHLKB(byte[] MOPCLEEGDFB, int ELICNEDIBGB, byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		if (!MOBILIJAIEK)
		{
			throw new InvalidOperationException(KFKMEPMEBND + " not initialised");
		}
		AJLDFGNHDCA.OONDALLFPOP(MOPCLEEGDFB, ELICNEDIBGB, 16, "input buffer too short");
		AJLDFGNHDCA.KLPNFGNKNKB(BILGCJNPJGJ, EMAKNGBIFDC, 16, "output buffer too short");
		return (!FPNNDLKJION) ? BJOOOKJMPLL(MOPCLEEGDFB, ELICNEDIBGB, BILGCJNPJGJ, EMAKNGBIFDC) : PGBGJCGKNCC(MOPCLEEGDFB, ELICNEDIBGB, BILGCJNPJGJ, EMAKNGBIFDC);
	}

	public virtual void OMOKOKFNBKI()
	{
	}

	private void LHCPMMKLJGA(byte[] IKNCPEPOKGJ)
	{
		AHOOKAFPJFI[0] = PGOKFBKEOAB.EFODDMAJNOA(IKNCPEPOKGJ, 0);
		AHOOKAFPJFI[1] = PGOKFBKEOAB.EFODDMAJNOA(IKNCPEPOKGJ, 4);
		AHOOKAFPJFI[2] = PGOKFBKEOAB.EFODDMAJNOA(IKNCPEPOKGJ, 8);
		AHOOKAFPJFI[3] = PGOKFBKEOAB.EFODDMAJNOA(IKNCPEPOKGJ, 12);
	}

	private int PGBGJCGKNCC(byte[] MOPCLEEGDFB, int ELICNEDIBGB, byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		BGEDKGLJIGM[0] = PGOKFBKEOAB.EFODDMAJNOA(MOPCLEEGDFB, ELICNEDIBGB);
		BGEDKGLJIGM[1] = PGOKFBKEOAB.EFODDMAJNOA(MOPCLEEGDFB, ELICNEDIBGB + 4);
		BGEDKGLJIGM[2] = PGOKFBKEOAB.EFODDMAJNOA(MOPCLEEGDFB, ELICNEDIBGB + 8);
		BGEDKGLJIGM[3] = PGOKFBKEOAB.EFODDMAJNOA(MOPCLEEGDFB, ELICNEDIBGB + 12);
		int i;
		for (i = 0; i < 16; i++)
		{
			BGEDKGLJIGM[0] ^= AGONMCHACLP[i];
			LHBPGHFDPPL(BGEDKGLJIGM, AHOOKAFPJFI);
			CCPGGGNLEDI(BGEDKGLJIGM);
			FGPIAEIILEL(BGEDKGLJIGM);
			KJAPCDOLIHE(BGEDKGLJIGM);
		}
		BGEDKGLJIGM[0] ^= AGONMCHACLP[i];
		LHBPGHFDPPL(BGEDKGLJIGM, AHOOKAFPJFI);
		PGOKFBKEOAB.MPMAFPANDLC(BGEDKGLJIGM[0], BILGCJNPJGJ, EMAKNGBIFDC);
		PGOKFBKEOAB.MPMAFPANDLC(BGEDKGLJIGM[1], BILGCJNPJGJ, EMAKNGBIFDC + 4);
		PGOKFBKEOAB.MPMAFPANDLC(BGEDKGLJIGM[2], BILGCJNPJGJ, EMAKNGBIFDC + 8);
		PGOKFBKEOAB.MPMAFPANDLC(BGEDKGLJIGM[3], BILGCJNPJGJ, EMAKNGBIFDC + 12);
		return 16;
	}

	private int BJOOOKJMPLL(byte[] MOPCLEEGDFB, int ELICNEDIBGB, byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		BGEDKGLJIGM[0] = PGOKFBKEOAB.EFODDMAJNOA(MOPCLEEGDFB, ELICNEDIBGB);
		BGEDKGLJIGM[1] = PGOKFBKEOAB.EFODDMAJNOA(MOPCLEEGDFB, ELICNEDIBGB + 4);
		BGEDKGLJIGM[2] = PGOKFBKEOAB.EFODDMAJNOA(MOPCLEEGDFB, ELICNEDIBGB + 8);
		BGEDKGLJIGM[3] = PGOKFBKEOAB.EFODDMAJNOA(MOPCLEEGDFB, ELICNEDIBGB + 12);
		Array.Copy(AHOOKAFPJFI, 0, NBKBCDBIEAN, 0, AHOOKAFPJFI.Length);
		LHBPGHFDPPL(NBKBCDBIEAN, FNDFJANMAGF);
		int num;
		for (num = 16; num > 0; num--)
		{
			LHBPGHFDPPL(BGEDKGLJIGM, NBKBCDBIEAN);
			BGEDKGLJIGM[0] ^= AGONMCHACLP[num];
			CCPGGGNLEDI(BGEDKGLJIGM);
			FGPIAEIILEL(BGEDKGLJIGM);
			KJAPCDOLIHE(BGEDKGLJIGM);
		}
		LHBPGHFDPPL(BGEDKGLJIGM, NBKBCDBIEAN);
		BGEDKGLJIGM[0] ^= AGONMCHACLP[num];
		PGOKFBKEOAB.MPMAFPANDLC(BGEDKGLJIGM[0], BILGCJNPJGJ, EMAKNGBIFDC);
		PGOKFBKEOAB.MPMAFPANDLC(BGEDKGLJIGM[1], BILGCJNPJGJ, EMAKNGBIFDC + 4);
		PGOKFBKEOAB.MPMAFPANDLC(BGEDKGLJIGM[2], BILGCJNPJGJ, EMAKNGBIFDC + 8);
		PGOKFBKEOAB.MPMAFPANDLC(BGEDKGLJIGM[3], BILGCJNPJGJ, EMAKNGBIFDC + 12);
		return 16;
	}

	private void FGPIAEIILEL(uint[] MNIMEAMHNMI)
	{
		MNIMEAMHNMI[1] ^= ~MNIMEAMHNMI[3] & ~MNIMEAMHNMI[2];
		MNIMEAMHNMI[0] ^= MNIMEAMHNMI[2] & MNIMEAMHNMI[1];
		uint num = MNIMEAMHNMI[3];
		MNIMEAMHNMI[3] = MNIMEAMHNMI[0];
		MNIMEAMHNMI[0] = num;
		MNIMEAMHNMI[2] ^= MNIMEAMHNMI[0] ^ MNIMEAMHNMI[1] ^ MNIMEAMHNMI[3];
		MNIMEAMHNMI[1] ^= ~MNIMEAMHNMI[3] & ~MNIMEAMHNMI[2];
		MNIMEAMHNMI[0] ^= MNIMEAMHNMI[2] & MNIMEAMHNMI[1];
	}

	private void LHBPGHFDPPL(uint[] MNIMEAMHNMI, uint[] BENKLGPHLGI)
	{
		uint num = MNIMEAMHNMI[0] ^ MNIMEAMHNMI[2];
		num ^= AJPHDJCGFNI(num, 8) ^ AJPHDJCGFNI(num, 24);
		MNIMEAMHNMI[1] ^= num;
		MNIMEAMHNMI[3] ^= num;
		for (int i = 0; i < 4; i++)
		{
			MNIMEAMHNMI[i] ^= BENKLGPHLGI[i];
		}
		num = MNIMEAMHNMI[1] ^ MNIMEAMHNMI[3];
		num ^= AJPHDJCGFNI(num, 8) ^ AJPHDJCGFNI(num, 24);
		MNIMEAMHNMI[0] ^= num;
		MNIMEAMHNMI[2] ^= num;
	}

	private void CCPGGGNLEDI(uint[] MNIMEAMHNMI)
	{
		MNIMEAMHNMI[1] = AJPHDJCGFNI(MNIMEAMHNMI[1], 1);
		MNIMEAMHNMI[2] = AJPHDJCGFNI(MNIMEAMHNMI[2], 5);
		MNIMEAMHNMI[3] = AJPHDJCGFNI(MNIMEAMHNMI[3], 2);
	}

	private void KJAPCDOLIHE(uint[] MNIMEAMHNMI)
	{
		MNIMEAMHNMI[1] = AJPHDJCGFNI(MNIMEAMHNMI[1], 31);
		MNIMEAMHNMI[2] = AJPHDJCGFNI(MNIMEAMHNMI[2], 27);
		MNIMEAMHNMI[3] = AJPHDJCGFNI(MNIMEAMHNMI[3], 30);
	}

	private uint AJPHDJCGFNI(uint AMFCENFNAJJ, int CNLILOEEBOJ)
	{
		return (AMFCENFNAJJ << CNLILOEEBOJ) | (AMFCENFNAJJ >> 32 - CNLILOEEBOJ);
	}
}
