using System;

internal class EPGHIOHIPIF : OMOBJNLGOBO
{
	public EPGHIOHIPIF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public EPGHIOHIPIF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal EPGHIOHIPIF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new EPGHIOHIPIF(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override KBINBLGGLNE NOIPJPPAFOH(int EHJNMODJEAN)
	{
		if (EHJNMODJEAN == 1)
		{
			return EIOKKHLHIEC();
		}
		return base.NOIPJPPAFOH(EHJNMODJEAN);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		NOHBGLDOCHE nOHBGLDOCHE = (NOHBGLDOCHE)base.NBPANDNEJGI;
		NOHBGLDOCHE nOHBGLDOCHE2 = (NOHBGLDOCHE)base.FIJLKLCHMGH;
		NOHBGLDOCHE nOHBGLDOCHE3 = (NOHBGLDOCHE)base.LAMGGDKLPJH[0];
		NOHBGLDOCHE nOHBGLDOCHE4 = (NOHBGLDOCHE)BCIHLCMFAEK.NBPANDNEJGI;
		NOHBGLDOCHE nOHBGLDOCHE5 = (NOHBGLDOCHE)BCIHLCMFAEK.FIJLKLCHMGH;
		NOHBGLDOCHE nOHBGLDOCHE6 = (NOHBGLDOCHE)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = AKOICJCJNFB.DCPJKFEDHOJ();
		uint[] array2 = AKOICJCJNFB.PLIFFMMBNPM();
		uint[] array3 = AKOICJCJNFB.PLIFFMMBNPM();
		uint[] array4 = AKOICJCJNFB.PLIFFMMBNPM();
		bool flag = nOHBGLDOCHE3.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = nOHBGLDOCHE4.AMFCENFNAJJ;
			array6 = nOHBGLDOCHE5.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			ACMDHOEGCJN.MIOEHGDPGAG(nOHBGLDOCHE3.AMFCENFNAJJ, array6);
			array5 = array2;
			ACMDHOEGCJN.IBJBIGNPNEM(array6, nOHBGLDOCHE4.AMFCENFNAJJ, array5);
			ACMDHOEGCJN.IBJBIGNPNEM(array6, nOHBGLDOCHE3.AMFCENFNAJJ, array6);
			ACMDHOEGCJN.IBJBIGNPNEM(array6, nOHBGLDOCHE5.AMFCENFNAJJ, array6);
		}
		bool flag2 = nOHBGLDOCHE6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = nOHBGLDOCHE.AMFCENFNAJJ;
			array8 = nOHBGLDOCHE2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			ACMDHOEGCJN.MIOEHGDPGAG(nOHBGLDOCHE6.AMFCENFNAJJ, array8);
			array7 = array;
			ACMDHOEGCJN.IBJBIGNPNEM(array8, nOHBGLDOCHE.AMFCENFNAJJ, array7);
			ACMDHOEGCJN.IBJBIGNPNEM(array8, nOHBGLDOCHE6.AMFCENFNAJJ, array8);
			ACMDHOEGCJN.IBJBIGNPNEM(array8, nOHBGLDOCHE2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = AKOICJCJNFB.PLIFFMMBNPM();
		ACMDHOEGCJN.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		ACMDHOEGCJN.FBGIHKPECCO(array8, array6, array10);
		if (AKOICJCJNFB.EJJHHCOFAAI(array9))
		{
			if (AKOICJCJNFB.EJJHHCOFAAI(array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = AKOICJCJNFB.PLIFFMMBNPM();
		ACMDHOEGCJN.MIOEHGDPGAG(array9, array11);
		uint[] array12 = AKOICJCJNFB.PLIFFMMBNPM();
		ACMDHOEGCJN.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		ACMDHOEGCJN.IBJBIGNPNEM(array11, array7, array13);
		ACMDHOEGCJN.BHKOFHMDACN(array12, array12);
		AKOICJCJNFB.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = AKOICJCJNFB.FIBDFFPCDGC(array13, array13, array12);
		ACMDHOEGCJN.FKHEIAHGNBA(aMFCENFNAJJ, array12);
		NOHBGLDOCHE nOHBGLDOCHE7 = new NOHBGLDOCHE(array4);
		ACMDHOEGCJN.MIOEHGDPGAG(array10, nOHBGLDOCHE7.AMFCENFNAJJ);
		ACMDHOEGCJN.FBGIHKPECCO(nOHBGLDOCHE7.AMFCENFNAJJ, array12, nOHBGLDOCHE7.AMFCENFNAJJ);
		NOHBGLDOCHE nOHBGLDOCHE8 = new NOHBGLDOCHE(array12);
		ACMDHOEGCJN.FBGIHKPECCO(array13, nOHBGLDOCHE7.AMFCENFNAJJ, nOHBGLDOCHE8.AMFCENFNAJJ);
		ACMDHOEGCJN.OMJFFHEIEFH(nOHBGLDOCHE8.AMFCENFNAJJ, array10, array);
		ACMDHOEGCJN.BKCHMGKFECM(array, nOHBGLDOCHE8.AMFCENFNAJJ);
		NOHBGLDOCHE nOHBGLDOCHE9 = new NOHBGLDOCHE(array9);
		if (!flag)
		{
			ACMDHOEGCJN.IBJBIGNPNEM(nOHBGLDOCHE9.AMFCENFNAJJ, nOHBGLDOCHE3.AMFCENFNAJJ, nOHBGLDOCHE9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			ACMDHOEGCJN.IBJBIGNPNEM(nOHBGLDOCHE9.AMFCENFNAJJ, nOHBGLDOCHE6.AMFCENFNAJJ, nOHBGLDOCHE9.AMFCENFNAJJ);
		}
		uint[] pIBCPKOKPGO = ((!flag || !flag2) ? null : array11);
		NOHBGLDOCHE nOHBGLDOCHE10 = GDIHGMBCMBE(nOHBGLDOCHE9, pIBCPKOKPGO);
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[2] { nOHBGLDOCHE9, nOHBGLDOCHE10 };
		return new EPGHIOHIPIF(bHPIABAGAPB, nOHBGLDOCHE7, nOHBGLDOCHE8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		return MGBLBPAGEPC(true);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return MGBLBPAGEPC(false).JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return MGBLBPAGEPC(false).JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new EPGHIOHIPIF(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}

	protected virtual NOHBGLDOCHE GDIHGMBCMBE(NOHBGLDOCHE NMLDCCMBKAD, uint[] PIBCPKOKPGO)
	{
		NOHBGLDOCHE nOHBGLDOCHE = (NOHBGLDOCHE)ECFGFKNLLGH.JEHECJGFJEB;
		if (NMLDCCMBKAD.EOJCHPEGABD)
		{
			return nOHBGLDOCHE;
		}
		NOHBGLDOCHE nOHBGLDOCHE2 = new NOHBGLDOCHE();
		if (PIBCPKOKPGO == null)
		{
			PIBCPKOKPGO = nOHBGLDOCHE2.AMFCENFNAJJ;
			ACMDHOEGCJN.MIOEHGDPGAG(NMLDCCMBKAD.AMFCENFNAJJ, PIBCPKOKPGO);
		}
		ACMDHOEGCJN.MIOEHGDPGAG(PIBCPKOKPGO, nOHBGLDOCHE2.AMFCENFNAJJ);
		ACMDHOEGCJN.IBJBIGNPNEM(nOHBGLDOCHE2.AMFCENFNAJJ, nOHBGLDOCHE.AMFCENFNAJJ, nOHBGLDOCHE2.AMFCENFNAJJ);
		return nOHBGLDOCHE2;
	}

	protected virtual NOHBGLDOCHE EIOKKHLHIEC()
	{
		KBINBLGGLNE[] array = base.LAMGGDKLPJH;
		NOHBGLDOCHE nOHBGLDOCHE = (NOHBGLDOCHE)array[1];
		if (nOHBGLDOCHE == null)
		{
			nOHBGLDOCHE = (NOHBGLDOCHE)(array[1] = GDIHGMBCMBE((NOHBGLDOCHE)array[0], null));
		}
		return nOHBGLDOCHE;
	}

	protected virtual EPGHIOHIPIF MGBLBPAGEPC(bool OHBCHOJPLJE)
	{
		NOHBGLDOCHE nOHBGLDOCHE = (NOHBGLDOCHE)base.NBPANDNEJGI;
		NOHBGLDOCHE nOHBGLDOCHE2 = (NOHBGLDOCHE)base.FIJLKLCHMGH;
		NOHBGLDOCHE nOHBGLDOCHE3 = (NOHBGLDOCHE)base.LAMGGDKLPJH[0];
		NOHBGLDOCHE nOHBGLDOCHE4 = EIOKKHLHIEC();
		uint[] array = AKOICJCJNFB.PLIFFMMBNPM();
		ACMDHOEGCJN.MIOEHGDPGAG(nOHBGLDOCHE.AMFCENFNAJJ, array);
		uint num = AKOICJCJNFB.FIBDFFPCDGC(array, array, array);
		num += AKOICJCJNFB.MAALDEFJPJA(nOHBGLDOCHE4.AMFCENFNAJJ, array);
		ACMDHOEGCJN.FKHEIAHGNBA(num, array);
		uint[] array2 = AKOICJCJNFB.PLIFFMMBNPM();
		ACMDHOEGCJN.LLGLJBDLBOP(nOHBGLDOCHE2.AMFCENFNAJJ, array2);
		uint[] array3 = AKOICJCJNFB.PLIFFMMBNPM();
		ACMDHOEGCJN.IBJBIGNPNEM(array2, nOHBGLDOCHE2.AMFCENFNAJJ, array3);
		uint[] array4 = AKOICJCJNFB.PLIFFMMBNPM();
		ACMDHOEGCJN.IBJBIGNPNEM(array3, nOHBGLDOCHE.AMFCENFNAJJ, array4);
		ACMDHOEGCJN.LLGLJBDLBOP(array4, array4);
		uint[] array5 = AKOICJCJNFB.PLIFFMMBNPM();
		ACMDHOEGCJN.MIOEHGDPGAG(array3, array5);
		ACMDHOEGCJN.LLGLJBDLBOP(array5, array5);
		NOHBGLDOCHE nOHBGLDOCHE5 = new NOHBGLDOCHE(array3);
		ACMDHOEGCJN.MIOEHGDPGAG(array, nOHBGLDOCHE5.AMFCENFNAJJ);
		ACMDHOEGCJN.FBGIHKPECCO(nOHBGLDOCHE5.AMFCENFNAJJ, array4, nOHBGLDOCHE5.AMFCENFNAJJ);
		ACMDHOEGCJN.FBGIHKPECCO(nOHBGLDOCHE5.AMFCENFNAJJ, array4, nOHBGLDOCHE5.AMFCENFNAJJ);
		NOHBGLDOCHE nOHBGLDOCHE6 = new NOHBGLDOCHE(array4);
		ACMDHOEGCJN.FBGIHKPECCO(array4, nOHBGLDOCHE5.AMFCENFNAJJ, nOHBGLDOCHE6.AMFCENFNAJJ);
		ACMDHOEGCJN.IBJBIGNPNEM(nOHBGLDOCHE6.AMFCENFNAJJ, array, nOHBGLDOCHE6.AMFCENFNAJJ);
		ACMDHOEGCJN.FBGIHKPECCO(nOHBGLDOCHE6.AMFCENFNAJJ, array5, nOHBGLDOCHE6.AMFCENFNAJJ);
		NOHBGLDOCHE nOHBGLDOCHE7 = new NOHBGLDOCHE(array2);
		if (!AKOICJCJNFB.EOJCHPEGABD(nOHBGLDOCHE3.AMFCENFNAJJ))
		{
			ACMDHOEGCJN.IBJBIGNPNEM(nOHBGLDOCHE7.AMFCENFNAJJ, nOHBGLDOCHE3.AMFCENFNAJJ, nOHBGLDOCHE7.AMFCENFNAJJ);
		}
		NOHBGLDOCHE nOHBGLDOCHE8 = null;
		if (OHBCHOJPLJE)
		{
			nOHBGLDOCHE8 = new NOHBGLDOCHE(array5);
			ACMDHOEGCJN.IBJBIGNPNEM(nOHBGLDOCHE8.AMFCENFNAJJ, nOHBGLDOCHE4.AMFCENFNAJJ, nOHBGLDOCHE8.AMFCENFNAJJ);
			ACMDHOEGCJN.LLGLJBDLBOP(nOHBGLDOCHE8.AMFCENFNAJJ, nOHBGLDOCHE8.AMFCENFNAJJ);
		}
		return new EPGHIOHIPIF(ECFGFKNLLGH, nOHBGLDOCHE5, nOHBGLDOCHE6, new KBINBLGGLNE[2] { nOHBGLDOCHE7, nOHBGLDOCHE8 }, base.BPGGHHMMCCB);
	}
}
