using System.Collections.Generic;

public class EPJLEKACDBC
{
	public string PJOHFCIOMDA { get; set; }

	public string LKGJHPGEONH { get; set; }

	public string GHNGJPDEKMJ { get; set; }

	public string FFCCMNJHFCB { get; set; }

	public string BDBPLJLNDMO { get; set; }

	public string CJJFCOAOOME { get; set; }

	public string MHJFGFFKMDN { get; set; }

	public string CDIJADNMACH { get; set; }

	public EPJLEKACDBC()
	{
	}

	public EPJLEKACDBC(string HDGFMHEHJBG)
	{
		DPKJGBCDECA dPKJGBCDECA = EDFILMGHHDD.DHCLOMIANOE(HDGFMHEHJBG);
		if (!DPKJGBCDECA.OCAFFLHPIMM(dPKJGBCDECA, null))
		{
			MHJFGFFKMDN = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.JNAJIAIFPFO);
			CDIJADNMACH = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.CKIGHBBPIBO);
			LKGJHPGEONH = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.ICEALDCHDDP);
			FFCCMNJHFCB = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.LAAJOJGGLBP);
			GHNGJPDEKMJ = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.LMMHMOKHGHC);
			BDBPLJLNDMO = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.HNEOICBLBNP);
			CJJFCOAOOME = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.JEGJCNKCDKF);
			PJOHFCIOMDA = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.IKIHDNHNJMH);
		}
	}

	public EPJLEKACDBC(Dictionary<string, string> KCBCGIKKMEK)
	{
		if (KCBCGIKKMEK != null)
		{
			MHJFGFFKMDN = NMLBPNNMFLP(KCBCGIKKMEK, FMKNBJCOMGF.JNAJIAIFPFO);
			CDIJADNMACH = NMLBPNNMFLP(KCBCGIKKMEK, FMKNBJCOMGF.CKIGHBBPIBO);
			LKGJHPGEONH = NMLBPNNMFLP(KCBCGIKKMEK, FMKNBJCOMGF.ICEALDCHDDP);
			FFCCMNJHFCB = NMLBPNNMFLP(KCBCGIKKMEK, FMKNBJCOMGF.LAAJOJGGLBP);
			GHNGJPDEKMJ = NMLBPNNMFLP(KCBCGIKKMEK, FMKNBJCOMGF.LMMHMOKHGHC);
			BDBPLJLNDMO = NMLBPNNMFLP(KCBCGIKKMEK, FMKNBJCOMGF.HNEOICBLBNP);
			CJJFCOAOOME = NMLBPNNMFLP(KCBCGIKKMEK, FMKNBJCOMGF.JEGJCNKCDKF);
			PJOHFCIOMDA = NMLBPNNMFLP(KCBCGIKKMEK, FMKNBJCOMGF.IKIHDNHNJMH);
		}
	}

	private static string NMLBPNNMFLP(Dictionary<string, string> GJEEEBEKEJI, string IKNCPEPOKGJ)
	{
		string value;
		if (GJEEEBEKEJI.TryGetValue(IKNCPEPOKGJ, out value))
		{
			return value;
		}
		return null;
	}
}
