public class EPOKPEIHHJG : LNKPCJLANAO
{
	private readonly PJGIGKJFGFI NJPMJNHGDNE;

	private BHPIABAGAPB FMFABAKPMLB;

	private JGAFKLGGBGF HPHBDNBJPHB;

	public JGAFKLGGBGF NCJHDEHECDN
	{
		get
		{
			if (HPHBDNBJPHB == null)
			{
				HPHBDNBJPHB = FMFABAKPMLB.BJBGPDHADCH(NJPMJNHGDNE.KLHNEKMCKKI()).MIHJHLFLHNA();
			}
			return HPHBDNBJPHB;
		}
	}

	public bool MKJNJJOHGHP
	{
		get
		{
			byte[] array = NJPMJNHGDNE.KLHNEKMCKKI();
			return array != null && array.Length > 0 && (array[0] == 2 || array[0] == 3);
		}
	}

	public EPOKPEIHHJG(JGAFKLGGBGF HPHBDNBJPHB)
		: this(HPHBDNBJPHB, false)
	{
	}

	public EPOKPEIHHJG(JGAFKLGGBGF HPHBDNBJPHB, bool BDKLBMAKEIN)
	{
		this.HPHBDNBJPHB = HPHBDNBJPHB.MIHJHLFLHNA();
		NJPMJNHGDNE = new CFMJBFILJCB(HPHBDNBJPHB.PPCPBIEGJKM(BDKLBMAKEIN));
	}

	public EPOKPEIHHJG(BHPIABAGAPB FMFABAKPMLB, byte[] NJPMJNHGDNE)
	{
		this.FMFABAKPMLB = FMFABAKPMLB;
		this.NJPMJNHGDNE = new CFMJBFILJCB(NOGCEBKPPJE.IKBFGGABMKP(NJPMJNHGDNE));
	}

	public EPOKPEIHHJG(BHPIABAGAPB FMFABAKPMLB, PJGIGKJFGFI IBBBMACIBGK)
		: this(FMFABAKPMLB, IBBBMACIBGK.KLHNEKMCKKI())
	{
	}

	public byte[] POMIGOECLPF()
	{
		return NOGCEBKPPJE.IKBFGGABMKP(NJPMJNHGDNE.KLHNEKMCKKI());
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		return NJPMJNHGDNE;
	}
}
