public interface FBDOIFENBIA
{
	int HDBJPKNJFPG();

	int IAPCCDCEFOF();

	int GFKEODOLHMN(byte[] GHPCHPOHELF, int JBAJPGIAPFF, int NBEDPKHALCN, int IMOHIFKOHID);

	void IINKCBOCHBG(byte[] GHPCHPOHELF, int JBAJPGIAPFF, int NBEDPKHALCN);

	void NKKOEHGDNKD();
}
