public class FHJAHPNDEOK : HPBPDALECOG
{
	private readonly JEHNKJOKBGF IJJHBEECMBP;

	public JEHNKJOKBGF KPJHHAAOFOH
	{
		get
		{
			return IJJHBEECMBP;
		}
	}

	public FHJAHPNDEOK(FBIJJFGLKMK GECCLOFELEC, JEHNKJOKBGF IJJHBEECMBP)
		: base(GECCLOFELEC, IJJHBEECMBP.MBIJHANOCOC.BitLength - 1)
	{
		this.IJJHBEECMBP = IJJHBEECMBP;
	}
}
