using System;
using System.IO;
using Org.BouncyCastle.Math;

public class FICAEDDJBEN
{
	protected readonly GBBNCENGABI MPBHBPPHONA;

	public virtual GBBNCENGABI OIDHEOJEMJF
	{
		get
		{
			return MPBHBPPHONA;
		}
	}

	public FICAEDDJBEN(GBBNCENGABI ECPKCNOAOAJ)
	{
		if (ECPKCNOAOAJ == null)
		{
			throw new ArgumentNullException("publicKey");
		}
		MPBHBPPHONA = ECPKCNOAOAJ;
	}

	public virtual void LMDBBPLCJDM(Stream BILGCJNPJGJ)
	{
		CLBPDHGBHML cLBPDHGBHML = MPBHBPPHONA.KPJHHAAOFOH;
		BigInteger aMFCENFNAJJ = MPBHBPPHONA.MOAGLBJDKKL;
		DBBCMLDCNPN.OIILCOMFOME(cLBPDHGBHML.MBIJHANOCOC, BILGCJNPJGJ);
		DBBCMLDCNPN.OIILCOMFOME(cLBPDHGBHML.HBGOKILMBJG, BILGCJNPJGJ);
		DBBCMLDCNPN.OIILCOMFOME(aMFCENFNAJJ, BILGCJNPJGJ);
	}

	public static FICAEDDJBEN DHCLOMIANOE(Stream MOPCLEEGDFB)
	{
		BigInteger hPHBDNBJPHB = DBBCMLDCNPN.EEMLKMCJOAA(MOPCLEEGDFB);
		BigInteger hJMBDGKAOBP = DBBCMLDCNPN.EEMLKMCJOAA(MOPCLEEGDFB);
		BigInteger cNLILOEEBOJ = DBBCMLDCNPN.EEMLKMCJOAA(MOPCLEEGDFB);
		return new FICAEDDJBEN(DBBCMLDCNPN.BJEGIOHKNMM(new GBBNCENGABI(cNLILOEEBOJ, new CLBPDHGBHML(hPHBDNBJPHB, hJMBDGKAOBP))));
	}
}
