using Org.BouncyCastle.Math;

internal class FKAFCHAAOMJ
{
	internal static readonly uint[] MBIJHANOCOC = new uint[5] { 2147483647u, 4294967295u, 4294967295u, 4294967295u, 4294967295u };

	internal static readonly uint[] PKABKFGEMBB = new uint[10] { 1u, 1073741825u, 0u, 0u, 0u, 4294967294u, 4294967294u, 4294967295u, 4294967295u, 4294967295u };

	private static readonly uint[] BPGLGHCLMCD = new uint[7] { 4294967295u, 3221225470u, 4294967295u, 4294967295u, 4294967295u, 1u, 1u };

	private const uint DJOLNOGFHEH = uint.MaxValue;

	private const uint BKCJCGANEHK = uint.MaxValue;

	private const uint PLDONAKICFO = 2147483649u;

	public static void JEACJNAKLDJ(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		if (EJJGNFBFKIJ.JEACJNAKLDJ(AMFCENFNAJJ, CNLILOEEBOJ, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[4] == uint.MaxValue && EJJGNFBFKIJ.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.GEDBFLNFIHI(5, 2147483649u, IGNEOOOFEMO);
		}
	}

	public static void KGBEKKMEBCN(uint[] HGHHJPDIMCI, uint[] IKEIELCEKPD, uint[] JMNJPLAGDDJ)
	{
		if ((BCMDHIIJKJE.JEACJNAKLDJ(10, HGHHJPDIMCI, IKEIELCEKPD, JMNJPLAGDDJ) != 0 || (JMNJPLAGDDJ[9] == uint.MaxValue && BCMDHIIJKJE.CHCGDEIGIIA(10, JMNJPLAGDDJ, PKABKFGEMBB))) && BCMDHIIJKJE.MAALDEFJPJA(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.DKCBNAFCCMF(10, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void AOAINNMNBHC(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (BCMDHIIJKJE.CKIHMFAAHLM(5, AMFCENFNAJJ, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[4] == uint.MaxValue && EJJGNFBFKIJ.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.GEDBFLNFIHI(5, 2147483649u, IGNEOOOFEMO);
		}
	}

	public static uint[] HFENNGHNFLF(BigInteger AMFCENFNAJJ)
	{
		uint[] array = EJJGNFBFKIJ.HFENNGHNFLF(AMFCENFNAJJ);
		if (array[4] == uint.MaxValue && EJJGNFBFKIJ.CHCGDEIGIIA(array, MBIJHANOCOC))
		{
			EJJGNFBFKIJ.DKAMAFLMHEJ(MBIJHANOCOC, array);
		}
		return array;
	}

	public static void CBGFKBFBIFD(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if ((AMFCENFNAJJ[0] & 1) == 0)
		{
			BCMDHIIJKJE.POFAGJIFAIH(5, AMFCENFNAJJ, 0u, IGNEOOOFEMO);
			return;
		}
		uint fMFABAKPMLB = EJJGNFBFKIJ.JEACJNAKLDJ(AMFCENFNAJJ, MBIJHANOCOC, IGNEOOOFEMO);
		BCMDHIIJKJE.POFAGJIFAIH(5, IGNEOOOFEMO, fMFABAKPMLB);
	}

	public static void IBJBIGNPNEM(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = EJJGNFBFKIJ.DCPJKFEDHOJ();
		EJJGNFBFKIJ.BMEIFJDODCF(AMFCENFNAJJ, CNLILOEEBOJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
	}

	public static void OMJFFHEIEFH(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] JMNJPLAGDDJ)
	{
		if ((EJJGNFBFKIJ.HHMEIAJHDJM(AMFCENFNAJJ, CNLILOEEBOJ, JMNJPLAGDDJ) != 0 || (JMNJPLAGDDJ[9] == uint.MaxValue && BCMDHIIJKJE.CHCGDEIGIIA(10, JMNJPLAGDDJ, PKABKFGEMBB))) && BCMDHIIJKJE.MAALDEFJPJA(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.DKCBNAFCCMF(10, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void BHKOFHMDACN(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (EJJGNFBFKIJ.EJJHHCOFAAI(AMFCENFNAJJ))
		{
			EJJGNFBFKIJ.KEOKCFDNHPP(IGNEOOOFEMO);
		}
		else
		{
			EJJGNFBFKIJ.EAEONHFLEEN(MBIJHANOCOC, AMFCENFNAJJ, IGNEOOOFEMO);
		}
	}

	public static void BKCHMGKFECM(uint[] HGHHJPDIMCI, uint[] IGNEOOOFEMO)
	{
		ulong num = HGHHJPDIMCI[5];
		ulong num2 = HGHHJPDIMCI[6];
		ulong num3 = HGHHJPDIMCI[7];
		ulong num4 = HGHHJPDIMCI[8];
		ulong num5 = HGHHJPDIMCI[9];
		ulong num6 = 0uL;
		num6 += HGHHJPDIMCI[0] + num + (num << 31);
		IGNEOOOFEMO[0] = (uint)num6;
		num6 >>= 32;
		num6 += HGHHJPDIMCI[1] + num2 + (num2 << 31);
		IGNEOOOFEMO[1] = (uint)num6;
		num6 >>= 32;
		num6 += HGHHJPDIMCI[2] + num3 + (num3 << 31);
		IGNEOOOFEMO[2] = (uint)num6;
		num6 >>= 32;
		num6 += HGHHJPDIMCI[3] + num4 + (num4 << 31);
		IGNEOOOFEMO[3] = (uint)num6;
		num6 >>= 32;
		num6 += HGHHJPDIMCI[4] + num5 + (num5 << 31);
		IGNEOOOFEMO[4] = (uint)num6;
		num6 >>= 32;
		KKIGIOINLCI((uint)num6, IGNEOOOFEMO);
	}

	public static void KKIGIOINLCI(uint AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if ((AMFCENFNAJJ != 0 && EJJGNFBFKIJ.DHNHBEHAKGG(2147483649u, AMFCENFNAJJ, IGNEOOOFEMO, 0) != 0) || (IGNEOOOFEMO[4] == uint.MaxValue && EJJGNFBFKIJ.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.GEDBFLNFIHI(5, 2147483649u, IGNEOOOFEMO);
		}
	}

	public static void MIOEHGDPGAG(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = EJJGNFBFKIJ.DCPJKFEDHOJ();
		EJJGNFBFKIJ.MIOEHGDPGAG(AMFCENFNAJJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
	}

	public static void OIEFGPHNOFN(uint[] AMFCENFNAJJ, int IDHLPOFDLKJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = EJJGNFBFKIJ.DCPJKFEDHOJ();
		EJJGNFBFKIJ.MIOEHGDPGAG(AMFCENFNAJJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
		while (--IDHLPOFDLKJ > 0)
		{
			EJJGNFBFKIJ.MIOEHGDPGAG(IGNEOOOFEMO, array);
			BKCHMGKFECM(array, IGNEOOOFEMO);
		}
	}

	public static void FBGIHKPECCO(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		if (EJJGNFBFKIJ.EAEONHFLEEN(AMFCENFNAJJ, CNLILOEEBOJ, IGNEOOOFEMO) != 0)
		{
			BCMDHIIJKJE.DDKHLCMFEPM(5, 2147483649u, IGNEOOOFEMO);
		}
	}

	public static void OIKFFIIOCPO(uint[] HGHHJPDIMCI, uint[] IKEIELCEKPD, uint[] JMNJPLAGDDJ)
	{
		if (BCMDHIIJKJE.EAEONHFLEEN(10, HGHHJPDIMCI, IKEIELCEKPD, JMNJPLAGDDJ) != 0 && BCMDHIIJKJE.DKAMAFLMHEJ(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.MEJBLKJLLNK(10, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void LLGLJBDLBOP(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (BCMDHIIJKJE.FKEFFJALNJM(5, AMFCENFNAJJ, 0u, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[4] == uint.MaxValue && EJJGNFBFKIJ.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.GEDBFLNFIHI(5, 2147483649u, IGNEOOOFEMO);
		}
	}
}
