using ToonSocial;

public class FKPMKEKODPC
{
	public BGMENKMNLCH ENGNFGGKODK;

	public SocialHelper IPCAELIMIBN;

	public int DEIDLKIBDOB;

	public FKPMKEKODPC(BGMENKMNLCH IBGOMPLHAFP, SocialHelper BHCIBOMDAIE, int AFGFJNOIBKD)
	{
		ENGNFGGKODK = IBGOMPLHAFP;
		IPCAELIMIBN = BHCIBOMDAIE;
		DEIDLKIBDOB = AFGFJNOIBKD;
	}
}
