using System;
using System.Collections;
using Org.BouncyCastle.Security;

public sealed class FLMLLBCHPNI
{
	internal static readonly IDictionary NCLCMMGJEBI;

	internal static readonly IDictionary MJNANGPLADC;

	public static ICollection BHDMAEHKBEP
	{
		get
		{
			return MJNANGPLADC.Keys;
		}
	}

	private FLMLLBCHPNI()
	{
	}

	static FLMLLBCHPNI()
	{
		NCLCMMGJEBI = LHFGHNFJIKM.JBEOCJEMGCE();
		MJNANGPLADC = LHFGHNFJIKM.JBEOCJEMGCE();
		NCLCMMGJEBI["MD2WITHRSA"] = "MD2withRSA";
		NCLCMMGJEBI["MD2WITHRSAENCRYPTION"] = "MD2withRSA";
		NCLCMMGJEBI[NLPPJKFFBON.IOAJGDJJEOD.EEFMIHDPJPG] = "MD2withRSA";
		NCLCMMGJEBI["MD4WITHRSA"] = "MD4withRSA";
		NCLCMMGJEBI["MD4WITHRSAENCRYPTION"] = "MD4withRSA";
		NCLCMMGJEBI[NLPPJKFFBON.OICNHJDHIDM.EEFMIHDPJPG] = "MD4withRSA";
		NCLCMMGJEBI["MD5WITHRSA"] = "MD5withRSA";
		NCLCMMGJEBI["MD5WITHRSAENCRYPTION"] = "MD5withRSA";
		NCLCMMGJEBI[NLPPJKFFBON.PMNPHGFIJKB.EEFMIHDPJPG] = "MD5withRSA";
		NCLCMMGJEBI["SHA1WITHRSA"] = "SHA-1withRSA";
		NCLCMMGJEBI["SHA1WITHRSAENCRYPTION"] = "SHA-1withRSA";
		NCLCMMGJEBI[NLPPJKFFBON.HHJOGJKDABE.EEFMIHDPJPG] = "SHA-1withRSA";
		NCLCMMGJEBI["SHA-1WITHRSA"] = "SHA-1withRSA";
		NCLCMMGJEBI["SHA224WITHRSA"] = "SHA-224withRSA";
		NCLCMMGJEBI["SHA224WITHRSAENCRYPTION"] = "SHA-224withRSA";
		NCLCMMGJEBI[NLPPJKFFBON.PJFNBLDALME.EEFMIHDPJPG] = "SHA-224withRSA";
		NCLCMMGJEBI["SHA-224WITHRSA"] = "SHA-224withRSA";
		NCLCMMGJEBI["SHA256WITHRSA"] = "SHA-256withRSA";
		NCLCMMGJEBI["SHA256WITHRSAENCRYPTION"] = "SHA-256withRSA";
		NCLCMMGJEBI[NLPPJKFFBON.OAIONFDMHJG.EEFMIHDPJPG] = "SHA-256withRSA";
		NCLCMMGJEBI["SHA-256WITHRSA"] = "SHA-256withRSA";
		NCLCMMGJEBI["SHA384WITHRSA"] = "SHA-384withRSA";
		NCLCMMGJEBI["SHA384WITHRSAENCRYPTION"] = "SHA-384withRSA";
		NCLCMMGJEBI[NLPPJKFFBON.DCHKOPOOPDP.EEFMIHDPJPG] = "SHA-384withRSA";
		NCLCMMGJEBI["SHA-384WITHRSA"] = "SHA-384withRSA";
		NCLCMMGJEBI["SHA512WITHRSA"] = "SHA-512withRSA";
		NCLCMMGJEBI["SHA512WITHRSAENCRYPTION"] = "SHA-512withRSA";
		NCLCMMGJEBI[NLPPJKFFBON.ACLCPAOCHDL.EEFMIHDPJPG] = "SHA-512withRSA";
		NCLCMMGJEBI["SHA-512WITHRSA"] = "SHA-512withRSA";
		NCLCMMGJEBI["PSSWITHRSA"] = "PSSwithRSA";
		NCLCMMGJEBI["RSASSA-PSS"] = "PSSwithRSA";
		NCLCMMGJEBI[NLPPJKFFBON.NLKEIILLMGF.EEFMIHDPJPG] = "PSSwithRSA";
		NCLCMMGJEBI["RSAPSS"] = "PSSwithRSA";
		NCLCMMGJEBI["SHA1WITHRSAANDMGF1"] = "SHA-1withRSAandMGF1";
		NCLCMMGJEBI["SHA-1WITHRSAANDMGF1"] = "SHA-1withRSAandMGF1";
		NCLCMMGJEBI["SHA1WITHRSA/PSS"] = "SHA-1withRSAandMGF1";
		NCLCMMGJEBI["SHA-1WITHRSA/PSS"] = "SHA-1withRSAandMGF1";
		NCLCMMGJEBI["SHA224WITHRSAANDMGF1"] = "SHA-224withRSAandMGF1";
		NCLCMMGJEBI["SHA-224WITHRSAANDMGF1"] = "SHA-224withRSAandMGF1";
		NCLCMMGJEBI["SHA224WITHRSA/PSS"] = "SHA-224withRSAandMGF1";
		NCLCMMGJEBI["SHA-224WITHRSA/PSS"] = "SHA-224withRSAandMGF1";
		NCLCMMGJEBI["SHA256WITHRSAANDMGF1"] = "SHA-256withRSAandMGF1";
		NCLCMMGJEBI["SHA-256WITHRSAANDMGF1"] = "SHA-256withRSAandMGF1";
		NCLCMMGJEBI["SHA256WITHRSA/PSS"] = "SHA-256withRSAandMGF1";
		NCLCMMGJEBI["SHA-256WITHRSA/PSS"] = "SHA-256withRSAandMGF1";
		NCLCMMGJEBI["SHA384WITHRSAANDMGF1"] = "SHA-384withRSAandMGF1";
		NCLCMMGJEBI["SHA-384WITHRSAANDMGF1"] = "SHA-384withRSAandMGF1";
		NCLCMMGJEBI["SHA384WITHRSA/PSS"] = "SHA-384withRSAandMGF1";
		NCLCMMGJEBI["SHA-384WITHRSA/PSS"] = "SHA-384withRSAandMGF1";
		NCLCMMGJEBI["SHA512WITHRSAANDMGF1"] = "SHA-512withRSAandMGF1";
		NCLCMMGJEBI["SHA-512WITHRSAANDMGF1"] = "SHA-512withRSAandMGF1";
		NCLCMMGJEBI["SHA512WITHRSA/PSS"] = "SHA-512withRSAandMGF1";
		NCLCMMGJEBI["SHA-512WITHRSA/PSS"] = "SHA-512withRSAandMGF1";
		NCLCMMGJEBI["RIPEMD128WITHRSA"] = "RIPEMD128withRSA";
		NCLCMMGJEBI["RIPEMD128WITHRSAENCRYPTION"] = "RIPEMD128withRSA";
		NCLCMMGJEBI[HECJIGBIHCA.DJLLMMGNGHO.EEFMIHDPJPG] = "RIPEMD128withRSA";
		NCLCMMGJEBI["RIPEMD160WITHRSA"] = "RIPEMD160withRSA";
		NCLCMMGJEBI["RIPEMD160WITHRSAENCRYPTION"] = "RIPEMD160withRSA";
		NCLCMMGJEBI[HECJIGBIHCA.FPONNNCJMMA.EEFMIHDPJPG] = "RIPEMD160withRSA";
		NCLCMMGJEBI["RIPEMD256WITHRSA"] = "RIPEMD256withRSA";
		NCLCMMGJEBI["RIPEMD256WITHRSAENCRYPTION"] = "RIPEMD256withRSA";
		NCLCMMGJEBI[HECJIGBIHCA.HOGNOMEIEPE.EEFMIHDPJPG] = "RIPEMD256withRSA";
		NCLCMMGJEBI["NONEWITHRSA"] = "RSA";
		NCLCMMGJEBI["RSAWITHNONE"] = "RSA";
		NCLCMMGJEBI["RAWRSA"] = "RSA";
		NCLCMMGJEBI["RAWRSAPSS"] = "RAWRSASSA-PSS";
		NCLCMMGJEBI["NONEWITHRSAPSS"] = "RAWRSASSA-PSS";
		NCLCMMGJEBI["NONEWITHRSASSA-PSS"] = "RAWRSASSA-PSS";
		NCLCMMGJEBI["NONEWITHDSA"] = "NONEwithDSA";
		NCLCMMGJEBI["DSAWITHNONE"] = "NONEwithDSA";
		NCLCMMGJEBI["RAWDSA"] = "NONEwithDSA";
		NCLCMMGJEBI["DSA"] = "SHA-1withDSA";
		NCLCMMGJEBI["DSAWITHSHA1"] = "SHA-1withDSA";
		NCLCMMGJEBI["DSAWITHSHA-1"] = "SHA-1withDSA";
		NCLCMMGJEBI["SHA/DSA"] = "SHA-1withDSA";
		NCLCMMGJEBI["SHA1/DSA"] = "SHA-1withDSA";
		NCLCMMGJEBI["SHA-1/DSA"] = "SHA-1withDSA";
		NCLCMMGJEBI["SHA1WITHDSA"] = "SHA-1withDSA";
		NCLCMMGJEBI["SHA-1WITHDSA"] = "SHA-1withDSA";
		NCLCMMGJEBI[JJFMEBLGJEP.CGJLNBCIAHE.EEFMIHDPJPG] = "SHA-1withDSA";
		NCLCMMGJEBI["DSAWITHSHA224"] = "SHA-224withDSA";
		NCLCMMGJEBI["DSAWITHSHA-224"] = "SHA-224withDSA";
		NCLCMMGJEBI["SHA224/DSA"] = "SHA-224withDSA";
		NCLCMMGJEBI["SHA-224/DSA"] = "SHA-224withDSA";
		NCLCMMGJEBI["SHA224WITHDSA"] = "SHA-224withDSA";
		NCLCMMGJEBI["SHA-224WITHDSA"] = "SHA-224withDSA";
		NCLCMMGJEBI[HHKLFIFJNFO.FIDJHIJHIJB.EEFMIHDPJPG] = "SHA-224withDSA";
		NCLCMMGJEBI["DSAWITHSHA256"] = "SHA-256withDSA";
		NCLCMMGJEBI["DSAWITHSHA-256"] = "SHA-256withDSA";
		NCLCMMGJEBI["SHA256/DSA"] = "SHA-256withDSA";
		NCLCMMGJEBI["SHA-256/DSA"] = "SHA-256withDSA";
		NCLCMMGJEBI["SHA256WITHDSA"] = "SHA-256withDSA";
		NCLCMMGJEBI["SHA-256WITHDSA"] = "SHA-256withDSA";
		NCLCMMGJEBI[HHKLFIFJNFO.GHJPDHPHJCG.EEFMIHDPJPG] = "SHA-256withDSA";
		NCLCMMGJEBI["DSAWITHSHA384"] = "SHA-384withDSA";
		NCLCMMGJEBI["DSAWITHSHA-384"] = "SHA-384withDSA";
		NCLCMMGJEBI["SHA384/DSA"] = "SHA-384withDSA";
		NCLCMMGJEBI["SHA-384/DSA"] = "SHA-384withDSA";
		NCLCMMGJEBI["SHA384WITHDSA"] = "SHA-384withDSA";
		NCLCMMGJEBI["SHA-384WITHDSA"] = "SHA-384withDSA";
		NCLCMMGJEBI[HHKLFIFJNFO.DFGLNGHMBBM.EEFMIHDPJPG] = "SHA-384withDSA";
		NCLCMMGJEBI["DSAWITHSHA512"] = "SHA-512withDSA";
		NCLCMMGJEBI["DSAWITHSHA-512"] = "SHA-512withDSA";
		NCLCMMGJEBI["SHA512/DSA"] = "SHA-512withDSA";
		NCLCMMGJEBI["SHA-512/DSA"] = "SHA-512withDSA";
		NCLCMMGJEBI["SHA512WITHDSA"] = "SHA-512withDSA";
		NCLCMMGJEBI["SHA-512WITHDSA"] = "SHA-512withDSA";
		NCLCMMGJEBI[HHKLFIFJNFO.LAGABLOADKP.EEFMIHDPJPG] = "SHA-512withDSA";
		NCLCMMGJEBI["NONEWITHECDSA"] = "NONEwithECDSA";
		NCLCMMGJEBI["ECDSAWITHNONE"] = "NONEwithECDSA";
		NCLCMMGJEBI["ECDSA"] = "SHA-1withECDSA";
		NCLCMMGJEBI["SHA1/ECDSA"] = "SHA-1withECDSA";
		NCLCMMGJEBI["SHA-1/ECDSA"] = "SHA-1withECDSA";
		NCLCMMGJEBI["ECDSAWITHSHA1"] = "SHA-1withECDSA";
		NCLCMMGJEBI["ECDSAWITHSHA-1"] = "SHA-1withECDSA";
		NCLCMMGJEBI["SHA1WITHECDSA"] = "SHA-1withECDSA";
		NCLCMMGJEBI["SHA-1WITHECDSA"] = "SHA-1withECDSA";
		NCLCMMGJEBI[JJFMEBLGJEP.MKGMLCOCCPL.EEFMIHDPJPG] = "SHA-1withECDSA";
		NCLCMMGJEBI[HECJIGBIHCA.FOCOJNPOPCG.EEFMIHDPJPG] = "SHA-1withECDSA";
		NCLCMMGJEBI["SHA224/ECDSA"] = "SHA-224withECDSA";
		NCLCMMGJEBI["SHA-224/ECDSA"] = "SHA-224withECDSA";
		NCLCMMGJEBI["ECDSAWITHSHA224"] = "SHA-224withECDSA";
		NCLCMMGJEBI["ECDSAWITHSHA-224"] = "SHA-224withECDSA";
		NCLCMMGJEBI["SHA224WITHECDSA"] = "SHA-224withECDSA";
		NCLCMMGJEBI["SHA-224WITHECDSA"] = "SHA-224withECDSA";
		NCLCMMGJEBI[JJFMEBLGJEP.KICHODOIAMD.EEFMIHDPJPG] = "SHA-224withECDSA";
		NCLCMMGJEBI["SHA256/ECDSA"] = "SHA-256withECDSA";
		NCLCMMGJEBI["SHA-256/ECDSA"] = "SHA-256withECDSA";
		NCLCMMGJEBI["ECDSAWITHSHA256"] = "SHA-256withECDSA";
		NCLCMMGJEBI["ECDSAWITHSHA-256"] = "SHA-256withECDSA";
		NCLCMMGJEBI["SHA256WITHECDSA"] = "SHA-256withECDSA";
		NCLCMMGJEBI["SHA-256WITHECDSA"] = "SHA-256withECDSA";
		NCLCMMGJEBI[JJFMEBLGJEP.EGLFGAJEAPJ.EEFMIHDPJPG] = "SHA-256withECDSA";
		NCLCMMGJEBI["SHA384/ECDSA"] = "SHA-384withECDSA";
		NCLCMMGJEBI["SHA-384/ECDSA"] = "SHA-384withECDSA";
		NCLCMMGJEBI["ECDSAWITHSHA384"] = "SHA-384withECDSA";
		NCLCMMGJEBI["ECDSAWITHSHA-384"] = "SHA-384withECDSA";
		NCLCMMGJEBI["SHA384WITHECDSA"] = "SHA-384withECDSA";
		NCLCMMGJEBI["SHA-384WITHECDSA"] = "SHA-384withECDSA";
		NCLCMMGJEBI[JJFMEBLGJEP.AACDLNGKGGH.EEFMIHDPJPG] = "SHA-384withECDSA";
		NCLCMMGJEBI["SHA512/ECDSA"] = "SHA-512withECDSA";
		NCLCMMGJEBI["SHA-512/ECDSA"] = "SHA-512withECDSA";
		NCLCMMGJEBI["ECDSAWITHSHA512"] = "SHA-512withECDSA";
		NCLCMMGJEBI["ECDSAWITHSHA-512"] = "SHA-512withECDSA";
		NCLCMMGJEBI["SHA512WITHECDSA"] = "SHA-512withECDSA";
		NCLCMMGJEBI["SHA-512WITHECDSA"] = "SHA-512withECDSA";
		NCLCMMGJEBI[JJFMEBLGJEP.CGLPLAKDEOP.EEFMIHDPJPG] = "SHA-512withECDSA";
		NCLCMMGJEBI["RIPEMD160/ECDSA"] = "RIPEMD160withECDSA";
		NCLCMMGJEBI["ECDSAWITHRIPEMD160"] = "RIPEMD160withECDSA";
		NCLCMMGJEBI["RIPEMD160WITHECDSA"] = "RIPEMD160withECDSA";
		NCLCMMGJEBI[HECJIGBIHCA.CKHDOBLLIOC.EEFMIHDPJPG] = "RIPEMD160withECDSA";
		NCLCMMGJEBI["GOST-3410"] = "GOST3410";
		NCLCMMGJEBI["GOST-3410-94"] = "GOST3410";
		NCLCMMGJEBI["GOST3411WITHGOST3410"] = "GOST3410";
		NCLCMMGJEBI[FNOHIHFMAMN.NPBGKJFALDM.EEFMIHDPJPG] = "GOST3410";
		NCLCMMGJEBI["ECGOST-3410"] = "ECGOST3410";
		NCLCMMGJEBI["ECGOST-3410-2001"] = "ECGOST3410";
		NCLCMMGJEBI["GOST3411WITHECGOST3410"] = "ECGOST3410";
		NCLCMMGJEBI[FNOHIHFMAMN.LEOPAFAFMPJ.EEFMIHDPJPG] = "ECGOST3410";
		MJNANGPLADC["MD2withRSA"] = NLPPJKFFBON.IOAJGDJJEOD;
		MJNANGPLADC["MD4withRSA"] = NLPPJKFFBON.OICNHJDHIDM;
		MJNANGPLADC["MD5withRSA"] = NLPPJKFFBON.PMNPHGFIJKB;
		MJNANGPLADC["SHA-1withRSA"] = NLPPJKFFBON.HHJOGJKDABE;
		MJNANGPLADC["SHA-224withRSA"] = NLPPJKFFBON.PJFNBLDALME;
		MJNANGPLADC["SHA-256withRSA"] = NLPPJKFFBON.OAIONFDMHJG;
		MJNANGPLADC["SHA-384withRSA"] = NLPPJKFFBON.DCHKOPOOPDP;
		MJNANGPLADC["SHA-512withRSA"] = NLPPJKFFBON.ACLCPAOCHDL;
		MJNANGPLADC["PSSwithRSA"] = NLPPJKFFBON.NLKEIILLMGF;
		MJNANGPLADC["SHA-1withRSAandMGF1"] = NLPPJKFFBON.NLKEIILLMGF;
		MJNANGPLADC["SHA-224withRSAandMGF1"] = NLPPJKFFBON.NLKEIILLMGF;
		MJNANGPLADC["SHA-256withRSAandMGF1"] = NLPPJKFFBON.NLKEIILLMGF;
		MJNANGPLADC["SHA-384withRSAandMGF1"] = NLPPJKFFBON.NLKEIILLMGF;
		MJNANGPLADC["SHA-512withRSAandMGF1"] = NLPPJKFFBON.NLKEIILLMGF;
		MJNANGPLADC["RIPEMD128withRSA"] = HECJIGBIHCA.DJLLMMGNGHO;
		MJNANGPLADC["RIPEMD160withRSA"] = HECJIGBIHCA.FPONNNCJMMA;
		MJNANGPLADC["RIPEMD256withRSA"] = HECJIGBIHCA.HOGNOMEIEPE;
		MJNANGPLADC["SHA-1withDSA"] = JJFMEBLGJEP.CGJLNBCIAHE;
		MJNANGPLADC["SHA-1withECDSA"] = JJFMEBLGJEP.MKGMLCOCCPL;
		MJNANGPLADC["SHA-224withECDSA"] = JJFMEBLGJEP.KICHODOIAMD;
		MJNANGPLADC["SHA-256withECDSA"] = JJFMEBLGJEP.EGLFGAJEAPJ;
		MJNANGPLADC["SHA-384withECDSA"] = JJFMEBLGJEP.AACDLNGKGGH;
		MJNANGPLADC["SHA-512withECDSA"] = JJFMEBLGJEP.CGLPLAKDEOP;
		MJNANGPLADC["GOST3410"] = FNOHIHFMAMN.NPBGKJFALDM;
		MJNANGPLADC["ECGOST3410"] = FNOHIHFMAMN.LEOPAFAFMPJ;
	}

	public static KLKJHFKJLEM JPMMBAMMCLO(string MOGLECBIKEG)
	{
		if (MOGLECBIKEG == null)
		{
			throw new ArgumentNullException("mechanism");
		}
		MOGLECBIKEG = LHFGHNFJIKM.OGLCLCODHJI(MOGLECBIKEG);
		string text = (string)NCLCMMGJEBI[MOGLECBIKEG];
		if (text != null)
		{
			MOGLECBIKEG = text;
		}
		return (KLKJHFKJLEM)MJNANGPLADC[MOGLECBIKEG];
	}

	public static LNKPCJLANAO HFMABCCJDEG(KLKJHFKJLEM BDKFNEDHAOJ)
	{
		return HFMABCCJDEG(BDKFNEDHAOJ.EEFMIHDPJPG);
	}

	public static LNKPCJLANAO HFMABCCJDEG(string ADLMOHOLCGL)
	{
		if (ADLMOHOLCGL == null)
		{
			throw new ArgumentNullException("algorithm");
		}
		ADLMOHOLCGL = LHFGHNFJIKM.OGLCLCODHJI(ADLMOHOLCGL);
		string text = (string)NCLCMMGJEBI[ADLMOHOLCGL];
		if (text == null)
		{
			text = ADLMOHOLCGL;
		}
		if (text == "PSSwithRSA")
		{
			return GLNPHCMGLLP("SHA-1");
		}
		if (LHFGHNFJIKM.BGIBPBNIHDL(text, "withRSAandMGF1"))
		{
			string lGBIALICPLG = text.Substring(0, text.Length - "withRSAandMGF1".Length);
			return GLNPHCMGLLP(lGBIALICPLG);
		}
		return HLAKNNHGPNP.GABGKBAKHDP;
	}

	private static LNKPCJLANAO GLNPHCMGLLP(string LGBIALICPLG)
	{
		COCECKPDIKC cOCECKPDIKC = new COCECKPDIKC(KDDIIEMIPKF.JPMMBAMMCLO(LGBIALICPLG), HLAKNNHGPNP.GABGKBAKHDP);
		COCECKPDIKC pNJAGJLLOPF = new COCECKPDIKC(NLPPJKFFBON.NKBNJIMIGJP, cOCECKPDIKC);
		int eDDNOJDPMCF = KDDIIEMIPKF.GANMELFOOMP(LGBIALICPLG).EEMLLAMENHO();
		return new LHCALAMFAOK(cOCECKPDIKC, pNJAGJLLOPF, new GLFDIPNOLKN(eDDNOJDPMCF), new GLFDIPNOLKN(1));
	}

	public static OHPHNNNHCOO OOLDLJODJGM(KLKJHFKJLEM BDKFNEDHAOJ)
	{
		return OOLDLJODJGM(BDKFNEDHAOJ.EEFMIHDPJPG);
	}

	public static OHPHNNNHCOO OOLDLJODJGM(string ADLMOHOLCGL)
	{
		if (ADLMOHOLCGL == null)
		{
			throw new ArgumentNullException("algorithm");
		}
		ADLMOHOLCGL = LHFGHNFJIKM.OGLCLCODHJI(ADLMOHOLCGL);
		string text = (string)NCLCMMGJEBI[ADLMOHOLCGL];
		if (text == null)
		{
			text = ADLMOHOLCGL;
		}
		if (text.Equals("RSA"))
		{
			return new MEHKHDBEJDF((BJLAMONNNDD)new OHAOIPKCMFC(), (COCECKPDIKC)null);
		}
		if (text.Equals("MD2withRSA"))
		{
			return new MEHKHDBEJDF(new OPBPDKCEGIJ());
		}
		if (text.Equals("MD4withRSA"))
		{
			return new MEHKHDBEJDF(new GBFIJMMDMKK());
		}
		if (text.Equals("MD5withRSA"))
		{
			return new MEHKHDBEJDF(new DDPKOBCIGDJ());
		}
		if (text.Equals("SHA-1withRSA"))
		{
			return new MEHKHDBEJDF(new KALMDEHGEAC());
		}
		if (text.Equals("SHA-224withRSA"))
		{
			return new MEHKHDBEJDF(new JAHCGEGGLMA());
		}
		if (text.Equals("SHA-256withRSA"))
		{
			return new MEHKHDBEJDF(new AFKIHPLKGEE());
		}
		if (text.Equals("SHA-384withRSA"))
		{
			return new MEHKHDBEJDF(new JIDIPOBKBGH());
		}
		if (text.Equals("SHA-512withRSA"))
		{
			return new MEHKHDBEJDF(new NLPHAELCKOJ());
		}
		if (text.Equals("RIPEMD128withRSA"))
		{
			return new MEHKHDBEJDF(new CONJOCHPANG());
		}
		if (text.Equals("RIPEMD160withRSA"))
		{
			return new MEHKHDBEJDF(new KHIEBIHIHJA());
		}
		if (text.Equals("RIPEMD256withRSA"))
		{
			return new MEHKHDBEJDF(new KDOKNEONHOF());
		}
		if (text.Equals("RAWRSASSA-PSS"))
		{
			return ENNJDNNBHPM.CIIEDPIEFEJ(new EPDGODLEJEF(), new KALMDEHGEAC());
		}
		if (text.Equals("PSSwithRSA"))
		{
			return new ENNJDNNBHPM(new EPDGODLEJEF(), new KALMDEHGEAC());
		}
		if (text.Equals("SHA-1withRSAandMGF1"))
		{
			return new ENNJDNNBHPM(new EPDGODLEJEF(), new KALMDEHGEAC());
		}
		if (text.Equals("SHA-224withRSAandMGF1"))
		{
			return new ENNJDNNBHPM(new EPDGODLEJEF(), new JAHCGEGGLMA());
		}
		if (text.Equals("SHA-256withRSAandMGF1"))
		{
			return new ENNJDNNBHPM(new EPDGODLEJEF(), new AFKIHPLKGEE());
		}
		if (text.Equals("SHA-384withRSAandMGF1"))
		{
			return new ENNJDNNBHPM(new EPDGODLEJEF(), new JIDIPOBKBGH());
		}
		if (text.Equals("SHA-512withRSAandMGF1"))
		{
			return new ENNJDNNBHPM(new EPDGODLEJEF(), new NLPHAELCKOJ());
		}
		if (text.Equals("NONEwithDSA"))
		{
			return new OBOJFCBALPO(new GACIPJJGHLM(), new OHAOIPKCMFC());
		}
		if (text.Equals("SHA-1withDSA"))
		{
			return new OBOJFCBALPO(new GACIPJJGHLM(), new KALMDEHGEAC());
		}
		if (text.Equals("SHA-224withDSA"))
		{
			return new OBOJFCBALPO(new GACIPJJGHLM(), new JAHCGEGGLMA());
		}
		if (text.Equals("SHA-256withDSA"))
		{
			return new OBOJFCBALPO(new GACIPJJGHLM(), new AFKIHPLKGEE());
		}
		if (text.Equals("SHA-384withDSA"))
		{
			return new OBOJFCBALPO(new GACIPJJGHLM(), new JIDIPOBKBGH());
		}
		if (text.Equals("SHA-512withDSA"))
		{
			return new OBOJFCBALPO(new GACIPJJGHLM(), new NLPHAELCKOJ());
		}
		if (text.Equals("NONEwithECDSA"))
		{
			return new OBOJFCBALPO(new AHGEJFKHBIN(), new OHAOIPKCMFC());
		}
		if (text.Equals("SHA-1withECDSA"))
		{
			return new OBOJFCBALPO(new AHGEJFKHBIN(), new KALMDEHGEAC());
		}
		if (text.Equals("SHA-224withECDSA"))
		{
			return new OBOJFCBALPO(new AHGEJFKHBIN(), new JAHCGEGGLMA());
		}
		if (text.Equals("SHA-256withECDSA"))
		{
			return new OBOJFCBALPO(new AHGEJFKHBIN(), new AFKIHPLKGEE());
		}
		if (text.Equals("SHA-384withECDSA"))
		{
			return new OBOJFCBALPO(new AHGEJFKHBIN(), new JIDIPOBKBGH());
		}
		if (text.Equals("SHA-512withECDSA"))
		{
			return new OBOJFCBALPO(new AHGEJFKHBIN(), new NLPHAELCKOJ());
		}
		if (text.Equals("RIPEMD160withECDSA"))
		{
			return new OBOJFCBALPO(new AHGEJFKHBIN(), new KHIEBIHIHJA());
		}
		if (text.Equals("SHA1WITHECNR"))
		{
			return new OBOJFCBALPO(new PBIFCJMEOJL(), new KALMDEHGEAC());
		}
		if (text.Equals("SHA224WITHECNR"))
		{
			return new OBOJFCBALPO(new PBIFCJMEOJL(), new JAHCGEGGLMA());
		}
		if (text.Equals("SHA256WITHECNR"))
		{
			return new OBOJFCBALPO(new PBIFCJMEOJL(), new AFKIHPLKGEE());
		}
		if (text.Equals("SHA384WITHECNR"))
		{
			return new OBOJFCBALPO(new PBIFCJMEOJL(), new JIDIPOBKBGH());
		}
		if (text.Equals("SHA512WITHECNR"))
		{
			return new OBOJFCBALPO(new PBIFCJMEOJL(), new NLPHAELCKOJ());
		}
		if (text.Equals("GOST3410"))
		{
			return new BMBPAAOADID(new EEIEMDJCLIL(), new FHMGJEBDMAG());
		}
		if (text.Equals("ECGOST3410"))
		{
			return new BMBPAAOADID(new BKBFGOOKCEF(), new FHMGJEBDMAG());
		}
		if (text.Equals("SHA1WITHRSA/ISO9796-2"))
		{
			return new NDLCIMPJNBK(new EPDGODLEJEF(), new KALMDEHGEAC(), true);
		}
		if (text.Equals("MD5WITHRSA/ISO9796-2"))
		{
			return new NDLCIMPJNBK(new EPDGODLEJEF(), new DDPKOBCIGDJ(), true);
		}
		if (text.Equals("RIPEMD160WITHRSA/ISO9796-2"))
		{
			return new NDLCIMPJNBK(new EPDGODLEJEF(), new KHIEBIHIHJA(), true);
		}
		if (LHFGHNFJIKM.BGIBPBNIHDL(text, "/X9.31"))
		{
			string text2 = text.Substring(0, text.Length - "/X9.31".Length);
			int num = LHFGHNFJIKM.NFLFPHCMIOK(text2, "WITH");
			if (num > 0)
			{
				int num2 = num + "WITH".Length;
				string aDLMOHOLCGL = text2.Substring(0, num);
				BJLAMONNNDD hABFKBCEIBN = KDDIIEMIPKF.GANMELFOOMP(aDLMOHOLCGL);
				string text3 = text2.Substring(num2, text2.Length - num2);
				if (text3.Equals("RSA"))
				{
					DGCIOOEELCP iEDPBFAFGGJ = new EPDGODLEJEF();
					return new LLCELMMHEFE(iEDPBFAFGGJ, hABFKBCEIBN);
				}
			}
		}
		throw new SecurityUtilityException("Signer " + ADLMOHOLCGL + " not recognised.");
	}

	public static string LCNAJOHCAII(KLKJHFKJLEM GDFLIKNMBCL)
	{
		return (string)NCLCMMGJEBI[GDFLIKNMBCL.EEFMIHDPJPG];
	}
}
