using Assets.Scripts.CasualTools.Common.DB;

public class FMHKCJGDPEB : Entity
{
	public int OADDPGNIINO;

	public string PNGPLGHKFDI;

	public int GMCGMPEEHJP;

	public string FGPGOGEKDAM;

	public int DJADMBLKBKJ;

	public int HDENPOJOAKC;

	public int AMKMOFAHFOC;

	public FMHKCJGDPEB(int? BDKFNEDHAOJ, int EMNOJOHFMEH, string IOCMOCCFALN, int ENMLICFLHAO, string PMKHOPIMKNH, int MGCMMJPNJPH, int HCJOGBJOGAH, int OMOCHOLJCIL)
	{
		PNLKNJNILDD(BDKFNEDHAOJ);
		OADDPGNIINO = EMNOJOHFMEH;
		PNGPLGHKFDI = IOCMOCCFALN;
		GMCGMPEEHJP = ENMLICFLHAO;
		FGPGOGEKDAM = PMKHOPIMKNH;
		DJADMBLKBKJ = MGCMMJPNJPH;
		HDENPOJOAKC = HCJOGBJOGAH;
		AMKMOFAHFOC = OMOCHOLJCIL;
	}
}
