using Org.BouncyCastle.Math;

internal class FNLHOJHHBGB : HAEJCOAFOIJ
{
	public static readonly BigInteger OKDPJHOEPBJ = new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFAC73"));

	private const int JKBHAHLCFIJ = 2;

	protected readonly LKAHFJPBMHD IAALHPOGFAN;

	public virtual BigInteger FNPELDEHJKL
	{
		get
		{
			return OKDPJHOEPBJ;
		}
	}

	public override JGAFKLGGBGF EFOLNCNGADB
	{
		get
		{
			return IAALHPOGFAN;
		}
	}

	public override int PJNLBAHOKGC
	{
		get
		{
			return OKDPJHOEPBJ.BitLength;
		}
	}

	public FNLHOJHHBGB()
		: base(OKDPJHOEPBJ)
	{
		IAALHPOGFAN = new LKAHFJPBMHD(this, null, null);
		CFJANGMBPML = HFENNGHNFLF(new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFAC70")));
		MPDGCILOEML = HFENNGHNFLF(new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("B4E134D3FB59EB8BAB57274904664D5AF50388BA")));
		NNGLKCDBIBE = new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("0100000000000000000000351EE786A818F3A1A16B"));
		LDKJJAOPAAP = BigInteger.One;
		NHKGIJJFPEK = 2;
	}

	protected override BHPIABAGAPB LNLMICLEEPK()
	{
		return new FNLHOJHHBGB();
	}

	public override bool ELIMDCKLHCJ(int FOOJPIGHMKH)
	{
		if (FOOJPIGHMKH == 2)
		{
			return true;
		}
		return false;
	}

	public override KBINBLGGLNE HFENNGHNFLF(BigInteger AMFCENFNAJJ)
	{
		return new JOCDNFCLFEB(AMFCENFNAJJ);
	}

	protected internal override JGAFKLGGBGF IMOPAOHAOAN(KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
	{
		return new LKAHFJPBMHD(this, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG);
	}

	protected internal override JGAFKLGGBGF IMOPAOHAOAN(KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
	{
		return new LKAHFJPBMHD(this, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG);
	}
}
