using System;

public class FNPNLKNFAMA : LNKPCJLANAO
{
	internal ALLINHNNNJN MIABODPHOIP;

	internal GLFDIPNOLKN AKBAHCLBLBO;

	internal KAGLNJGDIPD KKPDIKNGEMF;

	internal HLAHBGANIKK PNNONFMBDFM;

	public GLFDIPNOLKN OCKLOHPFNKG
	{
		get
		{
			return AKBAHCLBLBO;
		}
	}

	public KAGLNJGDIPD FHNDBMIJJJF
	{
		get
		{
			return KKPDIKNGEMF;
		}
	}

	public HLAHBGANIKK GBGIDCHPICA
	{
		get
		{
			if (PNNONFMBDFM == null && MIABODPHOIP.GMCGMPEEHJP == 3)
			{
				PNNONFMBDFM = HLAHBGANIKK.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(2));
			}
			return PNNONFMBDFM;
		}
	}

	public FNPNLKNFAMA(ALLINHNNNJN MIABODPHOIP)
	{
		if (MIABODPHOIP.GMCGMPEEHJP < 2 || MIABODPHOIP.GMCGMPEEHJP > 3)
		{
			throw new ArgumentException("Bad sequence size: " + MIABODPHOIP.GMCGMPEEHJP);
		}
		this.MIABODPHOIP = MIABODPHOIP;
		AKBAHCLBLBO = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(0));
		KKPDIKNGEMF = KAGLNJGDIPD.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(1));
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		return MIABODPHOIP;
	}
}
