using Org.BouncyCastle.Math;

public class FOMGBNHPDEG : CFMMJCMIGNM
{
	private DOKOCOIBGMK BOFHHECPKNF;

	public void DIOELAHNLKJ(HPBPDALECOG IJJHBEECMBP)
	{
		BOFHHECPKNF = (DOKOCOIBGMK)IJJHBEECMBP;
	}

	public HOHJPJDGOLF LOFCKPBODIJ()
	{
		GFNHMNLOOBB gABGKBAKHDP = GFNHMNLOOBB.GABGKBAKHDP;
		CFBBJKGJFPE cFBBJKGJFPE = BOFHHECPKNF.KPJHHAAOFOH;
		CLBPDHGBHML iFEEEDFDKMB = new CLBPDHGBHML(cFBBJKGJFPE.MBIJHANOCOC, cFBBJKGJFPE.HBGOKILMBJG, null, 0, cFBBJKGJFPE.NBFDOJDLKOG);
		BigInteger aMFCENFNAJJ = gABGKBAKHDP.ILJLFKLPKKM(iFEEEDFDKMB, BOFHHECPKNF.IPFKDIJBGIM);
		BigInteger cNLILOEEBOJ = gABGKBAKHDP.LEGMJIGOKFE(iFEEEDFDKMB, aMFCENFNAJJ);
		return new HOHJPJDGOLF(new IOEANHAEOBK(cNLILOEEBOJ, cFBBJKGJFPE), new IDCNEBAGENN(aMFCENFNAJJ, cFBBJKGJFPE));
	}
}
