using System;

public class GBFIJMMDMKK : EEBNPONHKOK
{
	private const int IOCOCGHMNGB = 16;

	private int NAHACOBOKIM;

	private int MPNNHCHGEGL;

	private int AJBHIPPAFIJ;

	private int GCLNAIGNJJN;

	private int[] CBPFFIBINEH = new int[16];

	private int ABBPDEOGNFE;

	private const int KBMGNCEBFKD = 3;

	private const int POKFCJBIKPG = 7;

	private const int FGANPBPIGKN = 11;

	private const int DNANPNAAAKK = 19;

	private const int NPFKJCOGAPI = 3;

	private const int GPNJIALDLIG = 5;

	private const int MCELPAPFJOP = 9;

	private const int OHAMBGEKDHC = 13;

	private const int CFMIPEKDLEK = 3;

	private const int ANHHIBKIPKK = 9;

	private const int PJAALIGLOLP = 11;

	private const int NGEKJAGBIBC = 15;

	public override string KFKMEPMEBND
	{
		get
		{
			return "MD4";
		}
	}

	public GBFIJMMDMKK()
	{
		OMOKOKFNBKI();
	}

	public GBFIJMMDMKK(GBFIJMMDMKK LLIEHCKNJEM)
		: base(LLIEHCKNJEM)
	{
		AKBPCECABIO(LLIEHCKNJEM);
	}

	private void AKBPCECABIO(GBFIJMMDMKK LLIEHCKNJEM)
	{
		AKBPCECABIO((EEBNPONHKOK)LLIEHCKNJEM);
		NAHACOBOKIM = LLIEHCKNJEM.NAHACOBOKIM;
		MPNNHCHGEGL = LLIEHCKNJEM.MPNNHCHGEGL;
		AJBHIPPAFIJ = LLIEHCKNJEM.AJBHIPPAFIJ;
		GCLNAIGNJJN = LLIEHCKNJEM.GCLNAIGNJJN;
		Array.Copy(LLIEHCKNJEM.CBPFFIBINEH, 0, CBPFFIBINEH, 0, LLIEHCKNJEM.CBPFFIBINEH.Length);
		ABBPDEOGNFE = LLIEHCKNJEM.ABBPDEOGNFE;
	}

	public override int EEMLLAMENHO()
	{
		return 16;
	}

	internal override void ICKIHAABCPI(byte[] MOPCLEEGDFB, int ELICNEDIBGB)
	{
		CBPFFIBINEH[ABBPDEOGNFE++] = (MOPCLEEGDFB[ELICNEDIBGB] & 0xFF) | ((MOPCLEEGDFB[ELICNEDIBGB + 1] & 0xFF) << 8) | ((MOPCLEEGDFB[ELICNEDIBGB + 2] & 0xFF) << 16) | ((MOPCLEEGDFB[ELICNEDIBGB + 3] & 0xFF) << 24);
		if (ABBPDEOGNFE == 16)
		{
			DPACJDFHLKB();
		}
	}

	internal override void IIENDLEDGMC(long EAJFCEBGGIG)
	{
		if (ABBPDEOGNFE > 14)
		{
			DPACJDFHLKB();
		}
		CBPFFIBINEH[14] = (int)(EAJFCEBGGIG & 0xFFFFFFFFu);
		CBPFFIBINEH[15] = (int)((ulong)EAJFCEBGGIG >> 32);
	}

	private void DKLAJHNFBJM(int BKKMJAIKJAL, byte[] NGAGMIIBGKA, int EMAKNGBIFDC)
	{
		NGAGMIIBGKA[EMAKNGBIFDC] = (byte)BKKMJAIKJAL;
		NGAGMIIBGKA[EMAKNGBIFDC + 1] = (byte)((uint)BKKMJAIKJAL >> 8);
		NGAGMIIBGKA[EMAKNGBIFDC + 2] = (byte)((uint)BKKMJAIKJAL >> 16);
		NGAGMIIBGKA[EMAKNGBIFDC + 3] = (byte)((uint)BKKMJAIKJAL >> 24);
	}

	public override int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		OJILOEAPDCL();
		DKLAJHNFBJM(NAHACOBOKIM, BILGCJNPJGJ, EMAKNGBIFDC);
		DKLAJHNFBJM(MPNNHCHGEGL, BILGCJNPJGJ, EMAKNGBIFDC + 4);
		DKLAJHNFBJM(AJBHIPPAFIJ, BILGCJNPJGJ, EMAKNGBIFDC + 8);
		DKLAJHNFBJM(GCLNAIGNJJN, BILGCJNPJGJ, EMAKNGBIFDC + 12);
		OMOKOKFNBKI();
		return 16;
	}

	public override void OMOKOKFNBKI()
	{
		base.OMOKOKFNBKI();
		NAHACOBOKIM = 1732584193;
		MPNNHCHGEGL = -271733879;
		AJBHIPPAFIJ = -1732584194;
		GCLNAIGNJJN = 271733878;
		ABBPDEOGNFE = 0;
		for (int i = 0; i != CBPFFIBINEH.Length; i++)
		{
			CBPFFIBINEH[i] = 0;
		}
	}

	private int MBBDJFKAACD(int AMFCENFNAJJ, int IDHLPOFDLKJ)
	{
		return (AMFCENFNAJJ << IDHLPOFDLKJ) | (int)((uint)AMFCENFNAJJ >> 32 - IDHLPOFDLKJ);
	}

	private int KEFHMDALCHB(int OJOAGEHFPNP, int AAIEJDNAODP, int PHFLBLJJMLI)
	{
		return (OJOAGEHFPNP & AAIEJDNAODP) | (~OJOAGEHFPNP & PHFLBLJJMLI);
	}

	private int HBGOKILMBJG(int OJOAGEHFPNP, int AAIEJDNAODP, int PHFLBLJJMLI)
	{
		return (OJOAGEHFPNP & AAIEJDNAODP) | (OJOAGEHFPNP & PHFLBLJJMLI) | (AAIEJDNAODP & PHFLBLJJMLI);
	}

	private int JGOHMOHEFMJ(int OJOAGEHFPNP, int AAIEJDNAODP, int PHFLBLJJMLI)
	{
		return OJOAGEHFPNP ^ AAIEJDNAODP ^ PHFLBLJJMLI;
	}

	internal override void DPACJDFHLKB()
	{
		int nAHACOBOKIM = NAHACOBOKIM;
		int mPNNHCHGEGL = MPNNHCHGEGL;
		int aJBHIPPAFIJ = AJBHIPPAFIJ;
		int gCLNAIGNJJN = GCLNAIGNJJN;
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + KEFHMDALCHB(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[0], 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + KEFHMDALCHB(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[1], 7);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + KEFHMDALCHB(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[2], 11);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + KEFHMDALCHB(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[3], 19);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + KEFHMDALCHB(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[4], 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + KEFHMDALCHB(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[5], 7);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + KEFHMDALCHB(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[6], 11);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + KEFHMDALCHB(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[7], 19);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + KEFHMDALCHB(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[8], 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + KEFHMDALCHB(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[9], 7);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + KEFHMDALCHB(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[10], 11);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + KEFHMDALCHB(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[11], 19);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + KEFHMDALCHB(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[12], 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + KEFHMDALCHB(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[13], 7);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + KEFHMDALCHB(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[14], 11);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + KEFHMDALCHB(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[15], 19);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + HBGOKILMBJG(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[0] + 1518500249, 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + HBGOKILMBJG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[4] + 1518500249, 5);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + HBGOKILMBJG(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[8] + 1518500249, 9);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + HBGOKILMBJG(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[12] + 1518500249, 13);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + HBGOKILMBJG(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[1] + 1518500249, 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + HBGOKILMBJG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[5] + 1518500249, 5);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + HBGOKILMBJG(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[9] + 1518500249, 9);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + HBGOKILMBJG(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[13] + 1518500249, 13);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + HBGOKILMBJG(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[2] + 1518500249, 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + HBGOKILMBJG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[6] + 1518500249, 5);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + HBGOKILMBJG(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[10] + 1518500249, 9);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + HBGOKILMBJG(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[14] + 1518500249, 13);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + HBGOKILMBJG(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[3] + 1518500249, 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + HBGOKILMBJG(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[7] + 1518500249, 5);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + HBGOKILMBJG(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[11] + 1518500249, 9);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + HBGOKILMBJG(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[15] + 1518500249, 13);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + JGOHMOHEFMJ(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[0] + 1859775393, 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + JGOHMOHEFMJ(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[8] + 1859775393, 9);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + JGOHMOHEFMJ(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[4] + 1859775393, 11);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + JGOHMOHEFMJ(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[12] + 1859775393, 15);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + JGOHMOHEFMJ(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[2] + 1859775393, 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + JGOHMOHEFMJ(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[10] + 1859775393, 9);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + JGOHMOHEFMJ(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[6] + 1859775393, 11);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + JGOHMOHEFMJ(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[14] + 1859775393, 15);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + JGOHMOHEFMJ(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[1] + 1859775393, 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + JGOHMOHEFMJ(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[9] + 1859775393, 9);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + JGOHMOHEFMJ(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[5] + 1859775393, 11);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + JGOHMOHEFMJ(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[13] + 1859775393, 15);
		nAHACOBOKIM = MBBDJFKAACD(nAHACOBOKIM + JGOHMOHEFMJ(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[3] + 1859775393, 3);
		gCLNAIGNJJN = MBBDJFKAACD(gCLNAIGNJJN + JGOHMOHEFMJ(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[11] + 1859775393, 9);
		aJBHIPPAFIJ = MBBDJFKAACD(aJBHIPPAFIJ + JGOHMOHEFMJ(gCLNAIGNJJN, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[7] + 1859775393, 11);
		mPNNHCHGEGL = MBBDJFKAACD(mPNNHCHGEGL + JGOHMOHEFMJ(aJBHIPPAFIJ, gCLNAIGNJJN, nAHACOBOKIM) + CBPFFIBINEH[15] + 1859775393, 15);
		NAHACOBOKIM += nAHACOBOKIM;
		MPNNHCHGEGL += mPNNHCHGEGL;
		AJBHIPPAFIJ += aJBHIPPAFIJ;
		GCLNAIGNJJN += gCLNAIGNJJN;
		ABBPDEOGNFE = 0;
		for (int i = 0; i != CBPFFIBINEH.Length; i++)
		{
			CBPFFIBINEH[i] = 0;
		}
	}

	public override MIPBJNJHNGA FDCFKGAEJFF()
	{
		return new GBFIJMMDMKK(this);
	}

	public override void OMOKOKFNBKI(MIPBJNJHNGA CJHEIBNHNNE)
	{
		GBFIJMMDMKK lLIEHCKNJEM = (GBFIJMMDMKK)CJHEIBNHNNE;
		AKBPCECABIO(lLIEHCKNJEM);
	}
}
