using System;
using UnityEngine;

public static class GBHLAJEFCCF
{
	public static FCPKAKFLFEG CIAICBMJBNH(this OAMNGFLKEFI DFHHMKMLCFF)
	{
		MKEALIMJCFJ mKEALIMJCFJ = DFHHMKMLCFF as MKEALIMJCFJ;
		if (mKEALIMJCFJ != null)
		{
			return mKEALIMJCFJ.HIPOEPNPBPO as FCPKAKFLFEG;
		}
		MGCLDKAFCIB mGCLDKAFCIB = DFHHMKMLCFF as MGCLDKAFCIB;
		if (mGCLDKAFCIB != null)
		{
			return mGCLDKAFCIB.HIPOEPNPBPO as FCPKAKFLFEG;
		}
		return null;
	}

	public static FCPKAKFLFEG CIAICBMJBNH(this MKEALIMJCFJ IOJFGJDNBOH)
	{
		return IOJFGJDNBOH.HIPOEPNPBPO as FCPKAKFLFEG;
	}

	public static FCPKAKFLFEG CIAICBMJBNH(this MGCLDKAFCIB COEOALCDGEK)
	{
		return COEOALCDGEK.HIPOEPNPBPO as FCPKAKFLFEG;
	}

	public static void HJJKKGEMFOM(this OAMNGFLKEFI DFHHMKMLCFF, FCPKAKFLFEG PMKKIEFBKAK, bool PMBKFHBHFHE = true)
	{
		MKEALIMJCFJ mKEALIMJCFJ = DFHHMKMLCFF as MKEALIMJCFJ;
		if (mKEALIMJCFJ != null)
		{
			mKEALIMJCFJ.HJJKKGEMFOM(PMKKIEFBKAK, PMBKFHBHFHE);
		}
		MGCLDKAFCIB mGCLDKAFCIB = DFHHMKMLCFF as MGCLDKAFCIB;
		if (mGCLDKAFCIB != null)
		{
			mGCLDKAFCIB.HJJKKGEMFOM(PMKKIEFBKAK, PMBKFHBHFHE);
		}
	}

	public static void HJJKKGEMFOM(this MKEALIMJCFJ DFHHMKMLCFF, FCPKAKFLFEG PMKKIEFBKAK, bool PMBKFHBHFHE = true)
	{
		if (PMKKIEFBKAK == null)
		{
			throw new ArgumentNullException("region");
		}
		DFHHMKMLCFF.HIPOEPNPBPO = PMKKIEFBKAK;
		DFHHMKMLCFF.ECIMDDHDCFK(PMKKIEFBKAK.OJOAGEHFPNP, PMKKIEFBKAK.AAIEJDNAODP, PMKKIEFBKAK.ECKFKMJFOCI, PMKKIEFBKAK.OFFFLJCPAJE, PMKKIEFBKAK.BBMMCOJNJHE);
		DFHHMKMLCFF.MBHOIJFNKPO = PMKKIEFBKAK.MLKPDGNHNAE;
		DFHHMKMLCFF.JGEIMMGNNFN = PMKKIEFBKAK.INDIJOFPNGA;
		DFHHMKMLCFF.ECJFPIOKKGN = PMKKIEFBKAK.HHHMOGOKFHF;
		DFHHMKMLCFF.MJCEICPLJKP = PMKKIEFBKAK.JKNPBEOPMPK;
		DFHHMKMLCFF.LBNLLJNGJHP = PMKKIEFBKAK.OMHIBPLGBME;
		DFHHMKMLCFF.HLMKOMNGAMA = PMKKIEFBKAK.JMEGIPJIGMK;
		if (PMBKFHBHFHE)
		{
			DFHHMKMLCFF.MNIMJDFOILP();
		}
	}

	public static void HJJKKGEMFOM(this MGCLDKAFCIB DFHHMKMLCFF, FCPKAKFLFEG PMKKIEFBKAK, bool JDKCEIEAPDC = true)
	{
		if (PMKKIEFBKAK == null)
		{
			throw new ArgumentNullException("region");
		}
		DFHHMKMLCFF.HIPOEPNPBPO = PMKKIEFBKAK;
		DFHHMKMLCFF.AMPGPNLBJKC = PMKKIEFBKAK.OJOAGEHFPNP;
		DFHHMKMLCFF.INFIMLAEHGL = PMKKIEFBKAK.AAIEJDNAODP;
		DFHHMKMLCFF.GGHFMMGLANA = PMKKIEFBKAK.ECKFKMJFOCI;
		DFHHMKMLCFF.HDCMGPKKCEJ = PMKKIEFBKAK.OFFFLJCPAJE;
		DFHHMKMLCFF.GCNJNMPFNJC = PMKKIEFBKAK.BBMMCOJNJHE;
		DFHHMKMLCFF.MBHOIJFNKPO = PMKKIEFBKAK.MLKPDGNHNAE;
		DFHHMKMLCFF.JGEIMMGNNFN = PMKKIEFBKAK.INDIJOFPNGA;
		DFHHMKMLCFF.ECJFPIOKKGN = PMKKIEFBKAK.HHHMOGOKFHF;
		DFHHMKMLCFF.MJCEICPLJKP = PMKKIEFBKAK.JKNPBEOPMPK;
		DFHHMKMLCFF.LBNLLJNGJHP = PMKKIEFBKAK.OMHIBPLGBME;
		DFHHMKMLCFF.HLMKOMNGAMA = PMKKIEFBKAK.JMEGIPJIGMK;
		if (JDKCEIEAPDC)
		{
			DFHHMKMLCFF.IFAIOMLBIAD();
		}
	}

	public static MKEALIMJCFJ GBANGNAEBAH(this Sprite MJOJAOIHCIO, Material GHPFOPNNJOB, float ODLHFMOPCHL = 0f)
	{
		return MJOJAOIHCIO.GBANGNAEBAH(GHPFOPNNJOB.PAOAGJDAHME(), ODLHFMOPCHL);
	}

	public static MKEALIMJCFJ GBANGNAEBAH(this Sprite MJOJAOIHCIO, LLLHGJNHPML CPIKPMLODAK, float ODLHFMOPCHL = 0f)
	{
		if (MJOJAOIHCIO == null)
		{
			throw new ArgumentNullException("sprite");
		}
		if (CPIKPMLODAK == null)
		{
			throw new ArgumentNullException("page");
		}
		FCPKAKFLFEG pMKKIEFBKAK = MJOJAOIHCIO.PKGKHHABACE(CPIKPMLODAK);
		float hJLOCAEAFMJ = 1f / MJOJAOIHCIO.pixelsPerUnit;
		return pMKKIEFBKAK.GBANGNAEBAH(MJOJAOIHCIO.name, hJLOCAEAFMJ, ODLHFMOPCHL);
	}

	public static MKEALIMJCFJ GCAIEFLKMON(this Sprite MJOJAOIHCIO, Shader BLCFLFHNKFG, TextureFormat MLLDGOCKHPL = TextureFormat.RGBA32, bool AOGOEMOPFKJ = false, Material DMOJCHBFADP = null, float ODLHFMOPCHL = 0f)
	{
		if (MJOJAOIHCIO == null)
		{
			throw new ArgumentNullException("sprite");
		}
		if (BLCFLFHNKFG == null)
		{
			throw new ArgumentNullException("shader");
		}
		FCPKAKFLFEG pMKKIEFBKAK = MJOJAOIHCIO.JOEMHKMEGJF(BLCFLFHNKFG, MLLDGOCKHPL, AOGOEMOPFKJ, DMOJCHBFADP);
		float hJLOCAEAFMJ = 1f / MJOJAOIHCIO.pixelsPerUnit;
		return pMKKIEFBKAK.GBANGNAEBAH(MJOJAOIHCIO.name, hJLOCAEAFMJ, ODLHFMOPCHL);
	}

	public static MKEALIMJCFJ GCAIEFLKMON(this Sprite MJOJAOIHCIO, Material DMOJCHBFADP, TextureFormat MLLDGOCKHPL = TextureFormat.RGBA32, bool AOGOEMOPFKJ = false, float ODLHFMOPCHL = 0f)
	{
		return MJOJAOIHCIO.GCAIEFLKMON(DMOJCHBFADP.shader, MLLDGOCKHPL, AOGOEMOPFKJ, DMOJCHBFADP, ODLHFMOPCHL);
	}

	public static MKEALIMJCFJ GBANGNAEBAH(this FCPKAKFLFEG PMKKIEFBKAK, string FKAJNAAKEFH, float HJLOCAEAFMJ = 0.01f, float ODLHFMOPCHL = 0f)
	{
		if (string.IsNullOrEmpty(FKAJNAAKEFH))
		{
			throw new ArgumentException("attachmentName can't be null or empty.", "attachmentName");
		}
		if (PMKKIEFBKAK == null)
		{
			throw new ArgumentNullException("region");
		}
		MKEALIMJCFJ mKEALIMJCFJ = new MKEALIMJCFJ(FKAJNAAKEFH);
		mKEALIMJCFJ.HIPOEPNPBPO = PMKKIEFBKAK;
		mKEALIMJCFJ.ECIMDDHDCFK(PMKKIEFBKAK.OJOAGEHFPNP, PMKKIEFBKAK.AAIEJDNAODP, PMKKIEFBKAK.ECKFKMJFOCI, PMKKIEFBKAK.OFFFLJCPAJE, PMKKIEFBKAK.BBMMCOJNJHE);
		mKEALIMJCFJ.MBHOIJFNKPO = PMKKIEFBKAK.MLKPDGNHNAE;
		mKEALIMJCFJ.JGEIMMGNNFN = PMKKIEFBKAK.INDIJOFPNGA;
		mKEALIMJCFJ.ECJFPIOKKGN = PMKKIEFBKAK.HHHMOGOKFHF;
		mKEALIMJCFJ.MJCEICPLJKP = PMKKIEFBKAK.JKNPBEOPMPK;
		mKEALIMJCFJ.LBNLLJNGJHP = PMKKIEFBKAK.OMHIBPLGBME;
		mKEALIMJCFJ.HLMKOMNGAMA = PMKKIEFBKAK.JMEGIPJIGMK;
		mKEALIMJCFJ.MJCBDBIDMGF = PMKKIEFBKAK.IOCMOCCFALN;
		mKEALIMJCFJ.IAFNPOKEFMB = 1f;
		mKEALIMJCFJ.GFMCPIJHIGD = 1f;
		mKEALIMJCFJ.ODLHFMOPCHL = ODLHFMOPCHL;
		mKEALIMJCFJ.GPGDCCMECGF = 1f;
		mKEALIMJCFJ.HJMBDGKAOBP = 1f;
		mKEALIMJCFJ.BCIHLCMFAEK = 1f;
		mKEALIMJCFJ.MNIMEAMHNMI = 1f;
		mKEALIMJCFJ.HHHMOGOKFHF = mKEALIMJCFJ.LBNLLJNGJHP * HJLOCAEAFMJ;
		mKEALIMJCFJ.JKNPBEOPMPK = mKEALIMJCFJ.HLMKOMNGAMA * HJLOCAEAFMJ;
		mKEALIMJCFJ.FHGEHEFAHKO(Color.white);
		mKEALIMJCFJ.MNIMJDFOILP();
		return mKEALIMJCFJ;
	}

	public static void CJPOBHHAMCC(this MKEALIMJCFJ IOJFGJDNBOH, Vector2 HJLOCAEAFMJ)
	{
		IOJFGJDNBOH.IAFNPOKEFMB = HJLOCAEAFMJ.x;
		IOJFGJDNBOH.GFMCPIJHIGD = HJLOCAEAFMJ.y;
	}

	public static void CJPOBHHAMCC(this MKEALIMJCFJ IOJFGJDNBOH, float AMFCENFNAJJ, float CNLILOEEBOJ)
	{
		IOJFGJDNBOH.IAFNPOKEFMB = AMFCENFNAJJ;
		IOJFGJDNBOH.GFMCPIJHIGD = CNLILOEEBOJ;
	}

	public static void MLBNCLNPHDM(this MKEALIMJCFJ IOJFGJDNBOH, Vector2 IBNDGNOIEEF)
	{
		IOJFGJDNBOH.AMFCENFNAJJ = IBNDGNOIEEF.x;
		IOJFGJDNBOH.CNLILOEEBOJ = IBNDGNOIEEF.y;
	}

	public static void MLBNCLNPHDM(this MKEALIMJCFJ IOJFGJDNBOH, float AMFCENFNAJJ, float CNLILOEEBOJ)
	{
		IOJFGJDNBOH.AMFCENFNAJJ = AMFCENFNAJJ;
		IOJFGJDNBOH.CNLILOEEBOJ = CNLILOEEBOJ;
	}

	public static void AJINLIFLMIC(this MKEALIMJCFJ IOJFGJDNBOH, float ODLHFMOPCHL)
	{
		IOJFGJDNBOH.ODLHFMOPCHL = ODLHFMOPCHL;
	}
}
