using System;

public class GDNPKPCHNBE : PHFBFDEAHMD
{
	private byte[] GHPCHPOHELF;

	private int MNIGMJPFNDA;

	private JMPFLJGHAIM IEDPBFAFGGJ;

	private ELGNLPAGPNI HFHKPBBFDFD;

	private int DLFPGGOCGNE;

	public string KFKMEPMEBND
	{
		get
		{
			return IEDPBFAFGGJ.KFKMEPMEBND;
		}
	}

	public GDNPKPCHNBE(JMPFLJGHAIM IEDPBFAFGGJ)
		: this(IEDPBFAFGGJ, IEDPBFAFGGJ.BDIGGHEPIIP() * 8 / 2, null)
	{
	}

	public GDNPKPCHNBE(JMPFLJGHAIM IEDPBFAFGGJ, ELGNLPAGPNI HFHKPBBFDFD)
		: this(IEDPBFAFGGJ, IEDPBFAFGGJ.BDIGGHEPIIP() * 8 / 2, HFHKPBBFDFD)
	{
	}

	public GDNPKPCHNBE(JMPFLJGHAIM IEDPBFAFGGJ, int DOPHJMLEJPG)
		: this(IEDPBFAFGGJ, DOPHJMLEJPG, null)
	{
	}

	public GDNPKPCHNBE(JMPFLJGHAIM IEDPBFAFGGJ, int DOPHJMLEJPG, ELGNLPAGPNI HFHKPBBFDFD)
	{
		if (DOPHJMLEJPG % 8 != 0)
		{
			throw new ArgumentException("MAC size must be multiple of 8");
		}
		this.IEDPBFAFGGJ = new OJGBFLKAPOB(IEDPBFAFGGJ);
		this.HFHKPBBFDFD = HFHKPBBFDFD;
		DLFPGGOCGNE = DOPHJMLEJPG / 8;
		GHPCHPOHELF = new byte[IEDPBFAFGGJ.BDIGGHEPIIP()];
		MNIGMJPFNDA = 0;
	}

	public void DIOELAHNLKJ(IGMAJHKIIPK IJJHBEECMBP)
	{
		OMOKOKFNBKI();
		IEDPBFAFGGJ.DIOELAHNLKJ(true, IJJHBEECMBP);
	}

	public int BKGLOJPPBIG()
	{
		return DLFPGGOCGNE;
	}

	public void BPAJGOINFNL(byte MOPCLEEGDFB)
	{
		if (MNIGMJPFNDA == GHPCHPOHELF.Length)
		{
			IEDPBFAFGGJ.DPACJDFHLKB(GHPCHPOHELF, 0, GHPCHPOHELF, 0);
			MNIGMJPFNDA = 0;
		}
		GHPCHPOHELF[MNIGMJPFNDA++] = MOPCLEEGDFB;
	}

	public void GONEEEFEDGF(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int NBEDPKHALCN)
	{
		if (NBEDPKHALCN < 0)
		{
			throw new ArgumentException("Can't have a negative input length!");
		}
		int num = IEDPBFAFGGJ.BDIGGHEPIIP();
		int num2 = num - MNIGMJPFNDA;
		if (NBEDPKHALCN > num2)
		{
			Array.Copy(MOPCLEEGDFB, ELICNEDIBGB, GHPCHPOHELF, MNIGMJPFNDA, num2);
			IEDPBFAFGGJ.DPACJDFHLKB(GHPCHPOHELF, 0, GHPCHPOHELF, 0);
			MNIGMJPFNDA = 0;
			NBEDPKHALCN -= num2;
			ELICNEDIBGB += num2;
			while (NBEDPKHALCN > num)
			{
				IEDPBFAFGGJ.DPACJDFHLKB(MOPCLEEGDFB, ELICNEDIBGB, GHPCHPOHELF, 0);
				NBEDPKHALCN -= num;
				ELICNEDIBGB += num;
			}
		}
		Array.Copy(MOPCLEEGDFB, ELICNEDIBGB, GHPCHPOHELF, MNIGMJPFNDA, NBEDPKHALCN);
		MNIGMJPFNDA += NBEDPKHALCN;
	}

	public int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		int num = IEDPBFAFGGJ.BDIGGHEPIIP();
		if (HFHKPBBFDFD == null)
		{
			while (MNIGMJPFNDA < num)
			{
				GHPCHPOHELF[MNIGMJPFNDA++] = 0;
			}
		}
		else
		{
			if (MNIGMJPFNDA == num)
			{
				IEDPBFAFGGJ.DPACJDFHLKB(GHPCHPOHELF, 0, GHPCHPOHELF, 0);
				MNIGMJPFNDA = 0;
			}
			HFHKPBBFDFD.MDNFIGPPOFC(GHPCHPOHELF, MNIGMJPFNDA);
		}
		IEDPBFAFGGJ.DPACJDFHLKB(GHPCHPOHELF, 0, GHPCHPOHELF, 0);
		Array.Copy(GHPCHPOHELF, 0, BILGCJNPJGJ, EMAKNGBIFDC, DLFPGGOCGNE);
		OMOKOKFNBKI();
		return DLFPGGOCGNE;
	}

	public void OMOKOKFNBKI()
	{
		Array.Clear(GHPCHPOHELF, 0, GHPCHPOHELF.Length);
		MNIGMJPFNDA = 0;
		IEDPBFAFGGJ.OMOKOKFNBKI();
	}
}
