using BestHTTP;

public class GEDLICHBKMF
{
	public LJNCMANOJMB HIBNMJBJEBI;

	public NOFFPNBJBGC LNEDKINAAOD;

	public HTTPRequest IBEBJIBKGOC;

	public GEDLICHBKMF(LJNCMANOJMB OLLJFDNPFMH)
	{
		HIBNMJBJEBI = OLLJFDNPFMH;
	}
}
