using System;
using System.Collections.Generic;

internal class GIBJACMAIKI
{
	private struct NOCACJDLLLJ
	{
		public JDHBNBGHEGC NBFBPNNEKMN;

		public JHFLAELBLPM GBKPDDDJOFO;

		public DCBJAMHBAJB EKFOKNPODBK;

		public NOCACJDLLLJ(JDHBNBGHEGC DCELGKOIMPK, JHFLAELBLPM NBOKLOHDENL, DCBJAMHBAJB EKFOKNPODBK = null)
		{
			NBFBPNNEKMN = DCELGKOIMPK;
			GBKPDDDJOFO = NBOKLOHDENL;
			this.EKFOKNPODBK = EKFOKNPODBK;
		}
	}

	private enum JDHBNBGHEGC
	{
		Start = 0,
		Interrupt = 1,
		End = 2,
		Dispose = 3,
		Complete = 4,
		Event = 5
	}

	private readonly List<NOCACJDLLLJ> GJPAAGLKEPH = new List<NOCACJDLLLJ>();

	internal bool HAAAHDKHDIH;

	private readonly KJKAIEHNGAL BGEDKGLJIGM;

	private readonly global::ECEEFKLEDDE<JHFLAELBLPM> OMNJAFKLAOI;

	internal event Action ELMDCIJDDHE;

	internal GIBJACMAIKI(KJKAIEHNGAL BGEDKGLJIGM, Action MAAECDGNLMI, global::ECEEFKLEDDE<JHFLAELBLPM> OMNJAFKLAOI)
	{
		this.BGEDKGLJIGM = BGEDKGLJIGM;
		ELMDCIJDDHE += MAAECDGNLMI;
		this.OMNJAFKLAOI = OMNJAFKLAOI;
	}

	internal void BAMKBCHHLGP(JHFLAELBLPM GBKPDDDJOFO)
	{
		GJPAAGLKEPH.Add(new NOCACJDLLLJ(JDHBNBGHEGC.Start, GBKPDDDJOFO));
		if (this.ELMDCIJDDHE != null)
		{
			this.ELMDCIJDDHE();
		}
	}

	internal void MMEJCOEJLGD(JHFLAELBLPM GBKPDDDJOFO)
	{
		GJPAAGLKEPH.Add(new NOCACJDLLLJ(JDHBNBGHEGC.Interrupt, GBKPDDDJOFO));
	}

	internal void BBLBNCKNGDL(JHFLAELBLPM GBKPDDDJOFO)
	{
		GJPAAGLKEPH.Add(new NOCACJDLLLJ(JDHBNBGHEGC.End, GBKPDDDJOFO));
		if (this.ELMDCIJDDHE != null)
		{
			this.ELMDCIJDDHE();
		}
	}

	internal void PCHCAFHEJJM(JHFLAELBLPM GBKPDDDJOFO)
	{
		GJPAAGLKEPH.Add(new NOCACJDLLLJ(JDHBNBGHEGC.Dispose, GBKPDDDJOFO));
	}

	internal void DHOFLMAIDKL(JHFLAELBLPM GBKPDDDJOFO)
	{
		GJPAAGLKEPH.Add(new NOCACJDLLLJ(JDHBNBGHEGC.Complete, GBKPDDDJOFO));
	}

	internal void FAMOCPPGDPK(JHFLAELBLPM GBKPDDDJOFO, DCBJAMHBAJB EKFOKNPODBK)
	{
		GJPAAGLKEPH.Add(new NOCACJDLLLJ(JDHBNBGHEGC.Event, GBKPDDDJOFO, EKFOKNPODBK));
	}

	internal void LJBNACEMHEP()
	{
		if (HAAAHDKHDIH)
		{
			return;
		}
		HAAAHDKHDIH = true;
		List<NOCACJDLLLJ> gJPAAGLKEPH = GJPAAGLKEPH;
		KJKAIEHNGAL bGEDKGLJIGM = BGEDKGLJIGM;
		for (int i = 0; i < gJPAAGLKEPH.Count; i++)
		{
			NOCACJDLLLJ nOCACJDLLLJ = gJPAAGLKEPH[i];
			JHFLAELBLPM gBKPDDDJOFO = nOCACJDLLLJ.GBKPDDDJOFO;
			switch (nOCACJDLLLJ.NBFBPNNEKMN)
			{
			case JDHBNBGHEGC.Start:
				gBKPDDDJOFO.MBMDOPAKKJD();
				bGEDKGLJIGM.MBMDOPAKKJD(gBKPDDDJOFO);
				break;
			case JDHBNBGHEGC.Interrupt:
				gBKPDDDJOFO.HCFLHLLJAMB();
				bGEDKGLJIGM.HCFLHLLJAMB(gBKPDDDJOFO);
				break;
			case JDHBNBGHEGC.End:
				gBKPDDDJOFO.CHJBJJBOKGM();
				bGEDKGLJIGM.CHJBJJBOKGM(gBKPDDDJOFO);
				goto case JDHBNBGHEGC.Dispose;
			case JDHBNBGHEGC.Dispose:
				gBKPDDDJOFO.CNHMOAAOINH();
				bGEDKGLJIGM.CNHMOAAOINH(gBKPDDDJOFO);
				OMNJAFKLAOI.CFPHGMEPNFK(gBKPDDDJOFO);
				break;
			case JDHBNBGHEGC.Complete:
				gBKPDDDJOFO.CECMINAKHFJ();
				bGEDKGLJIGM.CECMINAKHFJ(gBKPDDDJOFO);
				break;
			case JDHBNBGHEGC.Event:
				gBKPDDDJOFO.AAOONJHLMOM(nOCACJDLLLJ.EKFOKNPODBK);
				bGEDKGLJIGM.AAOONJHLMOM(gBKPDDDJOFO, nOCACJDLLLJ.EKFOKNPODBK);
				break;
			}
		}
		GJPAAGLKEPH.Clear();
		HAAAHDKHDIH = false;
	}

	internal void BOPEPLONIFL()
	{
		GJPAAGLKEPH.Clear();
	}
}
