public class GIJDCJHDFCO : LNKPCJLANAO
{
	private readonly MKNDIEHOMOI IGCEJBIEACI;

	public GIJDCJHDFCO(MKNDIEHOMOI BKOBLIALKKC)
	{
		IGCEJBIEACI = BKOBLIALKKC;
	}

	public HGIAHEKANFO DMHLIGLGJGI()
	{
		return IGCEJBIEACI.DMHLIGLGJGI();
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		return new EKNLINDFMIM(IGCEJBIEACI.IFPAJCFNKGJ());
	}
}
