using Spine;

public class GLKBNKGOCDE : CPCLJAHCDGN
{
	public override int ODHLEJHEBGD
	{
		get
		{
			return 50331648 + DHJJGGGLNNH;
		}
	}

	public GLKBNKGOCDE(int IJKENLLBMOJ)
		: base(IJKENLLBMOJ)
	{
	}

	public override void FCHLOGCODOA(GCJKICAPOFL GDNININLMFD, float CGICCPOKJHB, float HFLODNLEGFL, ExposedList<DCBJAMHBAJB> ELMIMIMBNHP, float KBKMPEOMABI, BFCFMFBHBCH IFKBABBBDJM, ODPDBCNBOAK AJLDJAHHGOJ)
	{
		NBKCFDOMAPI nBKCFDOMAPI = GDNININLMFD.LIKIOBHLHHF.Items[DHJJGGGLNNH];
		float[] eNBKHCNKHCC = ENBKHCNKHCC;
		if (HFLODNLEGFL < eNBKHCNKHCC[0])
		{
			switch (IFKBABBBDJM)
			{
			case BFCFMFBHBCH.Setup:
				nBKCFDOMAPI.BALNAGONJDA = nBKCFDOMAPI.MBBPBGHKLJM.BALNAGONJDA;
				nBKCFDOMAPI.DADFBNMBFCD = nBKCFDOMAPI.MBBPBGHKLJM.DADFBNMBFCD;
				break;
			case BFCFMFBHBCH.Current:
				nBKCFDOMAPI.BALNAGONJDA += (nBKCFDOMAPI.MBBPBGHKLJM.BALNAGONJDA - nBKCFDOMAPI.BALNAGONJDA) * KBKMPEOMABI;
				nBKCFDOMAPI.DADFBNMBFCD += (nBKCFDOMAPI.MBBPBGHKLJM.DADFBNMBFCD - nBKCFDOMAPI.DADFBNMBFCD) * KBKMPEOMABI;
				break;
			}
			return;
		}
		float num;
		float num2;
		if (HFLODNLEGFL >= eNBKHCNKHCC[eNBKHCNKHCC.Length - 3])
		{
			num = eNBKHCNKHCC[eNBKHCNKHCC.Length + -2];
			num2 = eNBKHCNKHCC[eNBKHCNKHCC.Length + -1];
		}
		else
		{
			int num3 = GNGKKPOGGGM.EIAMMDBFDFO(eNBKHCNKHCC, HFLODNLEGFL, 3);
			num = eNBKHCNKHCC[num3 + -2];
			num2 = eNBKHCNKHCC[num3 + -1];
			float num4 = eNBKHCNKHCC[num3];
			float num5 = IFMKHGLKEMB(num3 / 3 - 1, 1f - (HFLODNLEGFL - num4) / (eNBKHCNKHCC[num3 + -3] - num4));
			num += (eNBKHCNKHCC[num3 + 1] - num) * num5;
			num2 += (eNBKHCNKHCC[num3 + 2] - num2) * num5;
		}
		if (IFKBABBBDJM == BFCFMFBHBCH.Setup)
		{
			nBKCFDOMAPI.BALNAGONJDA = nBKCFDOMAPI.MBBPBGHKLJM.BALNAGONJDA + num * KBKMPEOMABI;
			nBKCFDOMAPI.DADFBNMBFCD = nBKCFDOMAPI.MBBPBGHKLJM.DADFBNMBFCD + num2 * KBKMPEOMABI;
		}
		else
		{
			nBKCFDOMAPI.BALNAGONJDA += (nBKCFDOMAPI.MBBPBGHKLJM.BALNAGONJDA + num - nBKCFDOMAPI.BALNAGONJDA) * KBKMPEOMABI;
			nBKCFDOMAPI.DADFBNMBFCD += (nBKCFDOMAPI.MBBPBGHKLJM.DADFBNMBFCD + num2 - nBKCFDOMAPI.DADFBNMBFCD) * KBKMPEOMABI;
		}
	}
}
