public class GLMHPPCHCJN : HDNHKJHOCHB
{
	private readonly int KFLAELKHKKI;

	public GLMHPPCHCJN(NOALGNJECAD HBBIFNLDKPO, string CFGGBONGJNP)
		: base(CFGGBONGJNP)
	{
		KFLAELKHKKI = (int)HBBIFNLDKPO;
	}

	public override int BHCEMBBCHKE(KFCEILFGADG GIOFHACJEGA)
	{
		return GIOFHACJEGA.NJHCINMDGKB[KFLAELKHKKI];
	}
}
