using System.Collections.Generic;

internal class GMAIMPBFBOA : AABPHGNCPFE
{
	private LFPFFONHOAN EMPOCPFCJBG;

	public GMAIMPBFBOA()
	{
		EMPOCPFCJBG = new LFPFFONHOAN();
	}

	public void NGPHNLCGMGP(string ELKHFBGEJLK, bool? EEKJMDHEJCK, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("SignUpEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.HLDIJPHLNAN(ELKHFBGEJLK);
		lNEGKOGBOAG.CJLFDOPNCOP(EEKJMDHEJCK);
		EMPOCPFCJBG.ILNNDCGJCKG("logSignUp", lNEGKOGBOAG);
	}

	public void ODOHJMBMEAI(string ELKHFBGEJLK, bool? EEKJMDHEJCK, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("LoginEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.HLDIJPHLNAN(ELKHFBGEJLK);
		lNEGKOGBOAG.CJLFDOPNCOP(EEKJMDHEJCK);
		EMPOCPFCJBG.ILNNDCGJCKG("logLogin", lNEGKOGBOAG);
	}

	public void OMNCEFIEDNC(string ELKHFBGEJLK, string BJPPGCGDMLD, string JAFLHIJPFKD, string IFACNDLFIOI, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("ShareEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.HLDIJPHLNAN(ELKHFBGEJLK);
		lNEGKOGBOAG.JANHFNFEDIL(BJPPGCGDMLD);
		lNEGKOGBOAG.ADHINDEJJDH(JAFLHIJPFKD);
		lNEGKOGBOAG.JKMGLGCGCOC(IFACNDLFIOI);
		EMPOCPFCJBG.ILNNDCGJCKG("logShare", lNEGKOGBOAG);
	}

	public void DHLIACCJDEE(string ELKHFBGEJLK, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("InviteEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.HLDIJPHLNAN(ELKHFBGEJLK);
		EMPOCPFCJBG.ILNNDCGJCKG("logInvite", lNEGKOGBOAG);
	}

	public void GFCPKKKLNDB(string GIOFHACJEGA, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("LevelStartEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.HGIPBGKODCN("putLevelName", GIOFHACJEGA);
		EMPOCPFCJBG.ILNNDCGJCKG("logLevelStart", lNEGKOGBOAG);
	}

	public void IJAIBDDDPDO(string GIOFHACJEGA, double? MGCMMJPNJPH, bool? EEKJMDHEJCK, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("LevelEndEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.HGIPBGKODCN("putLevelName", GIOFHACJEGA);
		lNEGKOGBOAG.MPHHHLHKOIJ("putScore", MGCMMJPNJPH);
		lNEGKOGBOAG.CJLFDOPNCOP(EEKJMDHEJCK);
		EMPOCPFCJBG.ILNNDCGJCKG("logLevelEnd", lNEGKOGBOAG);
	}

	public void KKCAJBIDHGF(decimal? NCOHIIBBFCE, string FMGPCBJLMDF, string AOBBNKGDIPL, string HBBIFNLDKPO, string HBMKHCHGHHF, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("AddToCartEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.OMAKCDLPNLA("putItemPrice", NCOHIIBBFCE);
		lNEGKOGBOAG.MJCBNFAHAKH(FMGPCBJLMDF);
		lNEGKOGBOAG.HGIPBGKODCN("putItemName", AOBBNKGDIPL);
		lNEGKOGBOAG.HGIPBGKODCN("putItemId", HBMKHCHGHHF);
		lNEGKOGBOAG.HGIPBGKODCN("putItemType", HBBIFNLDKPO);
		EMPOCPFCJBG.ILNNDCGJCKG("logAddToCart", lNEGKOGBOAG);
	}

	public void LKNCMIJEKOI(decimal? NJBGJKFBHGJ, string FMGPCBJLMDF, bool? EEKJMDHEJCK, string AOBBNKGDIPL, string HBBIFNLDKPO, string HBMKHCHGHHF, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("PurchaseEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.OMAKCDLPNLA("putItemPrice", NJBGJKFBHGJ);
		lNEGKOGBOAG.MJCBNFAHAKH(FMGPCBJLMDF);
		lNEGKOGBOAG.CJLFDOPNCOP(EEKJMDHEJCK);
		lNEGKOGBOAG.HGIPBGKODCN("putItemName", AOBBNKGDIPL);
		lNEGKOGBOAG.HGIPBGKODCN("putItemId", HBMKHCHGHHF);
		lNEGKOGBOAG.HGIPBGKODCN("putItemType", HBBIFNLDKPO);
		EMPOCPFCJBG.ILNNDCGJCKG("logPurchase", lNEGKOGBOAG);
	}

	public void MOFHCFJKMLF(decimal? PNNPJPPFKDL, string FMGPCBJLMDF, int? NNFOEMNONFK, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("StartCheckoutEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.OMAKCDLPNLA("putTotalPrice", PNNPJPPFKDL);
		lNEGKOGBOAG.MJCBNFAHAKH(FMGPCBJLMDF);
		lNEGKOGBOAG.MADFOJNOAHF("putItemCount", NNFOEMNONFK);
		EMPOCPFCJBG.ILNNDCGJCKG("logStartCheckout", lNEGKOGBOAG);
	}

	public void CFJLCHIILNP(int? APMONJMHAKP, string BJPPGCGDMLD, string JAFLHIJPFKD, string IFACNDLFIOI, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("RatingEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.MADFOJNOAHF("putRating", APMONJMHAKP);
		lNEGKOGBOAG.JANHFNFEDIL(BJPPGCGDMLD);
		lNEGKOGBOAG.ADHINDEJJDH(JAFLHIJPFKD);
		lNEGKOGBOAG.JKMGLGCGCOC(IFACNDLFIOI);
		EMPOCPFCJBG.ILNNDCGJCKG("logRating", lNEGKOGBOAG);
	}

	public void HHJDKKMFOPG(string BJPPGCGDMLD, string JAFLHIJPFKD, string IFACNDLFIOI, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("ContentViewEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.JANHFNFEDIL(BJPPGCGDMLD);
		lNEGKOGBOAG.ADHINDEJJDH(JAFLHIJPFKD);
		lNEGKOGBOAG.JKMGLGCGCOC(IFACNDLFIOI);
		EMPOCPFCJBG.ILNNDCGJCKG("logContentView", lNEGKOGBOAG);
	}

	public void NOPNGDMLDBD(string HKCKEACCMMA, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG lNEGKOGBOAG = new LNEGKOGBOAG("SearchEvent", LGOLOOGGKNC);
		lNEGKOGBOAG.HGIPBGKODCN("putQuery", HKCKEACCMMA);
		EMPOCPFCJBG.ILNNDCGJCKG("logSearch", lNEGKOGBOAG);
	}

	public void LKGHCNPKDAN(string PACBNANIAKH, Dictionary<string, object> LGOLOOGGKNC)
	{
		LNEGKOGBOAG aAEJFMIBHJN = new LNEGKOGBOAG("CustomEvent", LGOLOOGGKNC, PACBNANIAKH);
		EMPOCPFCJBG.ILNNDCGJCKG("logCustom", aAEJFMIBHJN);
	}
}
