using System;

internal class GMLCNFNILBG : OMOBJNLGOBO
{
	public GMLCNFNILBG(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public GMLCNFNILBG(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal GMLCNFNILBG(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new GMLCNFNILBG(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		EJHACKAIOPN eJHACKAIOPN = (EJHACKAIOPN)base.NBPANDNEJGI;
		EJHACKAIOPN eJHACKAIOPN2 = (EJHACKAIOPN)base.FIJLKLCHMGH;
		EJHACKAIOPN eJHACKAIOPN3 = (EJHACKAIOPN)BCIHLCMFAEK.NBPANDNEJGI;
		EJHACKAIOPN eJHACKAIOPN4 = (EJHACKAIOPN)BCIHLCMFAEK.FIJLKLCHMGH;
		EJHACKAIOPN eJHACKAIOPN5 = (EJHACKAIOPN)base.LAMGGDKLPJH[0];
		EJHACKAIOPN eJHACKAIOPN6 = (EJHACKAIOPN)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = EJJGNFBFKIJ.DCPJKFEDHOJ();
		uint[] array2 = EJJGNFBFKIJ.PLIFFMMBNPM();
		uint[] array3 = EJJGNFBFKIJ.PLIFFMMBNPM();
		uint[] array4 = EJJGNFBFKIJ.PLIFFMMBNPM();
		bool flag = eJHACKAIOPN5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = eJHACKAIOPN3.AMFCENFNAJJ;
			array6 = eJHACKAIOPN4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			FKAFCHAAOMJ.MIOEHGDPGAG(eJHACKAIOPN5.AMFCENFNAJJ, array6);
			array5 = array2;
			FKAFCHAAOMJ.IBJBIGNPNEM(array6, eJHACKAIOPN3.AMFCENFNAJJ, array5);
			FKAFCHAAOMJ.IBJBIGNPNEM(array6, eJHACKAIOPN5.AMFCENFNAJJ, array6);
			FKAFCHAAOMJ.IBJBIGNPNEM(array6, eJHACKAIOPN4.AMFCENFNAJJ, array6);
		}
		bool flag2 = eJHACKAIOPN6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = eJHACKAIOPN.AMFCENFNAJJ;
			array8 = eJHACKAIOPN2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			FKAFCHAAOMJ.MIOEHGDPGAG(eJHACKAIOPN6.AMFCENFNAJJ, array8);
			array7 = array;
			FKAFCHAAOMJ.IBJBIGNPNEM(array8, eJHACKAIOPN.AMFCENFNAJJ, array7);
			FKAFCHAAOMJ.IBJBIGNPNEM(array8, eJHACKAIOPN6.AMFCENFNAJJ, array8);
			FKAFCHAAOMJ.IBJBIGNPNEM(array8, eJHACKAIOPN2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = EJJGNFBFKIJ.PLIFFMMBNPM();
		FKAFCHAAOMJ.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		FKAFCHAAOMJ.FBGIHKPECCO(array8, array6, array10);
		if (EJJGNFBFKIJ.EJJHHCOFAAI(array9))
		{
			if (EJJGNFBFKIJ.EJJHHCOFAAI(array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		FKAFCHAAOMJ.MIOEHGDPGAG(array9, array11);
		uint[] array12 = EJJGNFBFKIJ.PLIFFMMBNPM();
		FKAFCHAAOMJ.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		FKAFCHAAOMJ.IBJBIGNPNEM(array11, array7, array13);
		FKAFCHAAOMJ.BHKOFHMDACN(array12, array12);
		EJJGNFBFKIJ.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = EJJGNFBFKIJ.FIBDFFPCDGC(array13, array13, array12);
		FKAFCHAAOMJ.KKIGIOINLCI(aMFCENFNAJJ, array12);
		EJHACKAIOPN eJHACKAIOPN7 = new EJHACKAIOPN(array4);
		FKAFCHAAOMJ.MIOEHGDPGAG(array10, eJHACKAIOPN7.AMFCENFNAJJ);
		FKAFCHAAOMJ.FBGIHKPECCO(eJHACKAIOPN7.AMFCENFNAJJ, array12, eJHACKAIOPN7.AMFCENFNAJJ);
		EJHACKAIOPN eJHACKAIOPN8 = new EJHACKAIOPN(array12);
		FKAFCHAAOMJ.FBGIHKPECCO(array13, eJHACKAIOPN7.AMFCENFNAJJ, eJHACKAIOPN8.AMFCENFNAJJ);
		FKAFCHAAOMJ.OMJFFHEIEFH(eJHACKAIOPN8.AMFCENFNAJJ, array10, array);
		FKAFCHAAOMJ.BKCHMGKFECM(array, eJHACKAIOPN8.AMFCENFNAJJ);
		EJHACKAIOPN eJHACKAIOPN9 = new EJHACKAIOPN(array9);
		if (!flag)
		{
			FKAFCHAAOMJ.IBJBIGNPNEM(eJHACKAIOPN9.AMFCENFNAJJ, eJHACKAIOPN5.AMFCENFNAJJ, eJHACKAIOPN9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			FKAFCHAAOMJ.IBJBIGNPNEM(eJHACKAIOPN9.AMFCENFNAJJ, eJHACKAIOPN6.AMFCENFNAJJ, eJHACKAIOPN9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { eJHACKAIOPN9 };
		return new GMLCNFNILBG(bHPIABAGAPB, eJHACKAIOPN7, eJHACKAIOPN8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		EJHACKAIOPN eJHACKAIOPN = (EJHACKAIOPN)base.FIJLKLCHMGH;
		if (eJHACKAIOPN.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		EJHACKAIOPN eJHACKAIOPN2 = (EJHACKAIOPN)base.NBPANDNEJGI;
		EJHACKAIOPN eJHACKAIOPN3 = (EJHACKAIOPN)base.LAMGGDKLPJH[0];
		uint[] array = EJJGNFBFKIJ.PLIFFMMBNPM();
		uint[] array2 = EJJGNFBFKIJ.PLIFFMMBNPM();
		uint[] array3 = EJJGNFBFKIJ.PLIFFMMBNPM();
		FKAFCHAAOMJ.MIOEHGDPGAG(eJHACKAIOPN.AMFCENFNAJJ, array3);
		uint[] array4 = EJJGNFBFKIJ.PLIFFMMBNPM();
		FKAFCHAAOMJ.MIOEHGDPGAG(array3, array4);
		bool flag = eJHACKAIOPN3.EOJCHPEGABD;
		uint[] array5 = eJHACKAIOPN3.AMFCENFNAJJ;
		if (!flag)
		{
			array5 = array2;
			FKAFCHAAOMJ.MIOEHGDPGAG(eJHACKAIOPN3.AMFCENFNAJJ, array5);
		}
		FKAFCHAAOMJ.FBGIHKPECCO(eJHACKAIOPN2.AMFCENFNAJJ, array5, array);
		uint[] array6 = array2;
		FKAFCHAAOMJ.JEACJNAKLDJ(eJHACKAIOPN2.AMFCENFNAJJ, array5, array6);
		FKAFCHAAOMJ.IBJBIGNPNEM(array6, array, array6);
		uint aMFCENFNAJJ = EJJGNFBFKIJ.FIBDFFPCDGC(array6, array6, array6);
		FKAFCHAAOMJ.KKIGIOINLCI(aMFCENFNAJJ, array6);
		uint[] array7 = array3;
		FKAFCHAAOMJ.IBJBIGNPNEM(array3, eJHACKAIOPN2.AMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(5, array7, 2, 0u);
		FKAFCHAAOMJ.KKIGIOINLCI(aMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(5, array4, 3, 0u, array);
		FKAFCHAAOMJ.KKIGIOINLCI(aMFCENFNAJJ, array);
		EJHACKAIOPN eJHACKAIOPN4 = new EJHACKAIOPN(array4);
		FKAFCHAAOMJ.MIOEHGDPGAG(array6, eJHACKAIOPN4.AMFCENFNAJJ);
		FKAFCHAAOMJ.FBGIHKPECCO(eJHACKAIOPN4.AMFCENFNAJJ, array7, eJHACKAIOPN4.AMFCENFNAJJ);
		FKAFCHAAOMJ.FBGIHKPECCO(eJHACKAIOPN4.AMFCENFNAJJ, array7, eJHACKAIOPN4.AMFCENFNAJJ);
		EJHACKAIOPN eJHACKAIOPN5 = new EJHACKAIOPN(array7);
		FKAFCHAAOMJ.FBGIHKPECCO(array7, eJHACKAIOPN4.AMFCENFNAJJ, eJHACKAIOPN5.AMFCENFNAJJ);
		FKAFCHAAOMJ.IBJBIGNPNEM(eJHACKAIOPN5.AMFCENFNAJJ, array6, eJHACKAIOPN5.AMFCENFNAJJ);
		FKAFCHAAOMJ.FBGIHKPECCO(eJHACKAIOPN5.AMFCENFNAJJ, array, eJHACKAIOPN5.AMFCENFNAJJ);
		EJHACKAIOPN eJHACKAIOPN6 = new EJHACKAIOPN(array6);
		FKAFCHAAOMJ.LLGLJBDLBOP(eJHACKAIOPN.AMFCENFNAJJ, eJHACKAIOPN6.AMFCENFNAJJ);
		if (!flag)
		{
			FKAFCHAAOMJ.IBJBIGNPNEM(eJHACKAIOPN6.AMFCENFNAJJ, eJHACKAIOPN3.AMFCENFNAJJ, eJHACKAIOPN6.AMFCENFNAJJ);
		}
		return new GMLCNFNILBG(bHPIABAGAPB, eJHACKAIOPN4, eJHACKAIOPN5, new KBINBLGGLNE[1] { eJHACKAIOPN6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new GMLCNFNILBG(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
