using System;
using Org.BouncyCastle.Math;

public abstract class HAEJCOAFOIJ : BHPIABAGAPB
{
	protected HAEJCOAFOIJ(BigInteger OKDPJHOEPBJ)
		: base(FGALCADFLCL.BMFGIJEIHEK(OKDPJHOEPBJ))
	{
	}

	public override bool DBFKLCPIHOI(BigInteger AMFCENFNAJJ)
	{
		return AMFCENFNAJJ != null && AMFCENFNAJJ.SignValue >= 0 && AMFCENFNAJJ.JLPDKNFCNPO(LLHBLBINBOA.HJKCMCLHBEN) < 0;
	}

	protected override JGAFKLGGBGF FMLLIJEENJJ(int ICNNEMMNLHC, BigInteger JCJOMANHEBB)
	{
		KBINBLGGLNE kBINBLGGLNE = HFENNGHNFLF(JCJOMANHEBB);
		KBINBLGGLNE kBINBLGGLNE2 = kBINBLGGLNE.MIOEHGDPGAG().JEACJNAKLDJ(JEHECJGFJEB).IBJBIGNPNEM(kBINBLGGLNE)
			.JEACJNAKLDJ(FPKDKHJKEEF);
		KBINBLGGLNE kBINBLGGLNE3 = kBINBLGGLNE2.PAEDNKEIDOM();
		if (kBINBLGGLNE3 == null)
		{
			throw new ArgumentException("Invalid point compression");
		}
		if (kBINBLGGLNE3.OFGNPBCCHAA() != (ICNNEMMNLHC == 1))
		{
			kBINBLGGLNE3 = kBINBLGGLNE3.BHKOFHMDACN();
		}
		return IMOPAOHAOAN(kBINBLGGLNE, kBINBLGGLNE3, true);
	}
}
