using System;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text;

internal class HECAJHFNLKF
{
	private delegate bool KKLMPOPLBKH(AEBEBKKBGEO ILMCNHDMEGI);

	private static int[] ECAEKCDFCBC;

	private static KKLMPOPLBKH[] KEIPFMNBMPJ;

	private bool INGLKIHAHFL;

	private bool IKAKAMLDFEN;

	private bool EOIEIDCNBGL;

	private AEBEBKKBGEO PJGODCHMIKB;

	private int PCDHFKANEBM;

	private int HPLBPDOBIKC;

	private TextReader JIGJDAHIIBA;

	private int BGEDKGLJIGM;

	private StringBuilder IFGAJIMCIAK;

	private string LECNLMBAAAD;

	private int DJJGDFFDGFN;

	private int JNAGFDIPNJN;

	[CompilerGenerated]
	private static KKLMPOPLBKH JANLDOMIIEF;

	[CompilerGenerated]
	private static KKLMPOPLBKH GEBGDBLHLKE;

	[CompilerGenerated]
	private static KKLMPOPLBKH FNBHFDJDLFP;

	[CompilerGenerated]
	private static KKLMPOPLBKH CHPGAHFCLFK;

	[CompilerGenerated]
	private static KKLMPOPLBKH GCKOFPLKKBL;

	[CompilerGenerated]
	private static KKLMPOPLBKH DGFMGBBBPGB;

	[CompilerGenerated]
	private static KKLMPOPLBKH MLKLLFBPCFD;

	[CompilerGenerated]
	private static KKLMPOPLBKH GJDKNJAHCFC;

	[CompilerGenerated]
	private static KKLMPOPLBKH EIPKJGBGEFK;

	[CompilerGenerated]
	private static KKLMPOPLBKH JFHGCPBGHHM;

	[CompilerGenerated]
	private static KKLMPOPLBKH AACOEIMNHAN;

	[CompilerGenerated]
	private static KKLMPOPLBKH JLKIPFLEEME;

	[CompilerGenerated]
	private static KKLMPOPLBKH JIGNMJKAAHO;

	[CompilerGenerated]
	private static KKLMPOPLBKH FMPCDEDDHIF;

	[CompilerGenerated]
	private static KKLMPOPLBKH KJCGPCMLHJC;

	[CompilerGenerated]
	private static KKLMPOPLBKH AIBNHKPMLEE;

	[CompilerGenerated]
	private static KKLMPOPLBKH LFNEGKBAOPC;

	[CompilerGenerated]
	private static KKLMPOPLBKH JNNPKBMMJBN;

	[CompilerGenerated]
	private static KKLMPOPLBKH LFJIKMBHBJJ;

	[CompilerGenerated]
	private static KKLMPOPLBKH CGDIEPNPADP;

	[CompilerGenerated]
	private static KKLMPOPLBKH IABNDGAOABM;

	[CompilerGenerated]
	private static KKLMPOPLBKH JAJGFELFALB;

	[CompilerGenerated]
	private static KKLMPOPLBKH KDPBOHNJDMG;

	[CompilerGenerated]
	private static KKLMPOPLBKH OLDNOJDCBPD;

	[CompilerGenerated]
	private static KKLMPOPLBKH PONCNCFPDFP;

	[CompilerGenerated]
	private static KKLMPOPLBKH LEJGHJJKEJG;

	[CompilerGenerated]
	private static KKLMPOPLBKH KPBKDOHOJAB;

	[CompilerGenerated]
	private static KKLMPOPLBKH KMBLJOIKINN;

	public bool NHMLDOIDONK
	{
		get
		{
			return INGLKIHAHFL;
		}
		set
		{
			INGLKIHAHFL = value;
		}
	}

	public bool ODEJFABEPOD
	{
		get
		{
			return IKAKAMLDFEN;
		}
		set
		{
			IKAKAMLDFEN = value;
		}
	}

	public bool CNJMIMFCDDM
	{
		get
		{
			return EOIEIDCNBGL;
		}
	}

	public int FIPPLABNDON
	{
		get
		{
			return DJJGDFFDGFN;
		}
	}

	public string IMDJJNLOEAD
	{
		get
		{
			return LECNLMBAAAD;
		}
	}

	static HECAJHFNLKF()
	{
		PIBDKAJOLBE();
	}

	public HECAJHFNLKF(TextReader JIGJDAHIIBA)
	{
		INGLKIHAHFL = true;
		IKAKAMLDFEN = true;
		PCDHFKANEBM = 0;
		IFGAJIMCIAK = new StringBuilder(128);
		BGEDKGLJIGM = 1;
		EOIEIDCNBGL = false;
		this.JIGJDAHIIBA = JIGJDAHIIBA;
		PJGODCHMIKB = new AEBEBKKBGEO();
		PJGODCHMIKB.NBFDOJDLKOG = this;
	}

	private static int GMFCIFKKGNC(int JHGNALGNKKC)
	{
		switch (JHGNALGNKKC)
		{
		case 65:
		case 97:
			return 10;
		case 66:
		case 98:
			return 11;
		case 67:
		case 99:
			return 12;
		case 68:
		case 100:
			return 13;
		case 69:
		case 101:
			return 14;
		case 70:
		case 102:
			return 15;
		default:
			return JHGNALGNKKC - 48;
		}
	}

	private static void PIBDKAJOLBE()
	{
		KEIPFMNBMPJ = new KKLMPOPLBKH[28]
		{
			EJHGEHNBPPO, JHHJABOIFPK, LDEMLBNBDFB, AAIMGDCIIGD, OAMLFDKNGKL, AENCIAJOAOF, FPIJGOHOIJN, KEDGBMOMNFJ, DFJIKBDJNEG, GIAKPHDAHAF,
			LBJACCIBIJK, DDLHJLLPKIH, BBAPGPCHPDB, OLKFFILOKDB, GCFAAGCACDG, ANBHPKDMKMN, AJCMLPNOBPI, PGMKFDIDCDC, NFBDHMNCLFO, OMCFFLHNFAL,
			EGLCGAOPOCD, KAGMMGMNMBI, GLGBJLMEEGI, FOHHEIPHFMP, DNHEKGKAEHH, CKGGNNELNDE, PAFIAPOJBAM, PKEJINOCBMF
		};
		ECAEKCDFCBC = new int[28]
		{
			65542, 0, 65537, 65537, 0, 65537, 0, 65537, 0, 0,
			65538, 0, 0, 0, 65539, 0, 0, 65540, 65541, 65542,
			0, 0, 65541, 65542, 0, 0, 0, 0
		};
	}

	private static char GGAFIAJPDIJ(int PAEBNKIMPIE)
	{
		switch (PAEBNKIMPIE)
		{
		case 34:
		case 39:
		case 47:
		case 92:
			return Convert.ToChar(PAEBNKIMPIE);
		case 110:
			return '\n';
		case 116:
			return '\t';
		case 114:
			return '\r';
		case 98:
			return '\b';
		case 102:
			return '\f';
		default:
			return '?';
		}
	}

	private static bool EJHGEHNBPPO(AEBEBKKBGEO ILMCNHDMEGI)
	{
		while (ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF())
		{
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC == 32 || (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 9 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 13))
			{
				continue;
			}
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 49 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 57)
			{
				ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
				ILMCNHDMEGI.HNMBBFMBPHE = 3;
				return true;
			}
			switch (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC)
			{
			case 34:
				ILMCNHDMEGI.HNMBBFMBPHE = 19;
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				return true;
			case 44:
			case 58:
			case 91:
			case 93:
			case 123:
			case 125:
				ILMCNHDMEGI.HNMBBFMBPHE = 1;
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				return true;
			case 45:
				ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
				ILMCNHDMEGI.HNMBBFMBPHE = 2;
				return true;
			case 48:
				ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
				ILMCNHDMEGI.HNMBBFMBPHE = 4;
				return true;
			case 102:
				ILMCNHDMEGI.HNMBBFMBPHE = 12;
				return true;
			case 110:
				ILMCNHDMEGI.HNMBBFMBPHE = 16;
				return true;
			case 116:
				ILMCNHDMEGI.HNMBBFMBPHE = 9;
				return true;
			case 39:
				if (!ILMCNHDMEGI.NBFDOJDLKOG.IKAKAMLDFEN)
				{
					return false;
				}
				ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC = 34;
				ILMCNHDMEGI.HNMBBFMBPHE = 23;
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				return true;
			case 47:
				if (!ILMCNHDMEGI.NBFDOJDLKOG.INGLKIHAHFL)
				{
					return false;
				}
				ILMCNHDMEGI.HNMBBFMBPHE = 25;
				return true;
			default:
				return false;
			}
		}
		return true;
	}

	private static bool JHHJABOIFPK(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 49 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 57)
		{
			ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
			ILMCNHDMEGI.HNMBBFMBPHE = 3;
			return true;
		}
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 48)
		{
			ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
			ILMCNHDMEGI.HNMBBFMBPHE = 4;
			return true;
		}
		return false;
	}

	private static bool LDEMLBNBDFB(AEBEBKKBGEO ILMCNHDMEGI)
	{
		while (ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF())
		{
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 48 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 57)
			{
				ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
				continue;
			}
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC == 32 || (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 9 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 13))
			{
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				ILMCNHDMEGI.HNMBBFMBPHE = 1;
				return true;
			}
			switch (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC)
			{
			case 44:
			case 93:
			case 125:
				ILMCNHDMEGI.NBFDOJDLKOG.ACHGEFLAALD();
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				ILMCNHDMEGI.HNMBBFMBPHE = 1;
				return true;
			case 46:
				ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
				ILMCNHDMEGI.HNMBBFMBPHE = 5;
				return true;
			case 69:
			case 101:
				ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
				ILMCNHDMEGI.HNMBBFMBPHE = 7;
				return true;
			default:
				return false;
			}
		}
		return true;
	}

	private static bool AAIMGDCIIGD(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC == 32 || (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 9 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 13))
		{
			ILMCNHDMEGI.BBMLNDGJLDP = true;
			ILMCNHDMEGI.HNMBBFMBPHE = 1;
			return true;
		}
		switch (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC)
		{
		case 44:
		case 93:
		case 125:
			ILMCNHDMEGI.NBFDOJDLKOG.ACHGEFLAALD();
			ILMCNHDMEGI.BBMLNDGJLDP = true;
			ILMCNHDMEGI.HNMBBFMBPHE = 1;
			return true;
		case 46:
			ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
			ILMCNHDMEGI.HNMBBFMBPHE = 5;
			return true;
		case 69:
		case 101:
			ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
			ILMCNHDMEGI.HNMBBFMBPHE = 7;
			return true;
		default:
			return false;
		}
	}

	private static bool OAMLFDKNGKL(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 48 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 57)
		{
			ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
			ILMCNHDMEGI.HNMBBFMBPHE = 6;
			return true;
		}
		return false;
	}

	private static bool AENCIAJOAOF(AEBEBKKBGEO ILMCNHDMEGI)
	{
		while (ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF())
		{
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 48 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 57)
			{
				ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
				continue;
			}
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC == 32 || (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 9 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 13))
			{
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				ILMCNHDMEGI.HNMBBFMBPHE = 1;
				return true;
			}
			switch (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC)
			{
			case 44:
			case 93:
			case 125:
				ILMCNHDMEGI.NBFDOJDLKOG.ACHGEFLAALD();
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				ILMCNHDMEGI.HNMBBFMBPHE = 1;
				return true;
			case 69:
			case 101:
				ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
				ILMCNHDMEGI.HNMBBFMBPHE = 7;
				return true;
			default:
				return false;
			}
		}
		return true;
	}

	private static bool FPIJGOHOIJN(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 48 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 57)
		{
			ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
			ILMCNHDMEGI.HNMBBFMBPHE = 8;
			return true;
		}
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 43 || hPLBPDOBIKC == 45)
		{
			ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
			ILMCNHDMEGI.HNMBBFMBPHE = 8;
			return true;
		}
		return false;
	}

	private static bool KEDGBMOMNFJ(AEBEBKKBGEO ILMCNHDMEGI)
	{
		while (ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF())
		{
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 48 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 57)
			{
				ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
				continue;
			}
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC == 32 || (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 9 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 13))
			{
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				ILMCNHDMEGI.HNMBBFMBPHE = 1;
				return true;
			}
			int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
			if (hPLBPDOBIKC == 44 || hPLBPDOBIKC == 93 || hPLBPDOBIKC == 125)
			{
				ILMCNHDMEGI.NBFDOJDLKOG.ACHGEFLAALD();
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				ILMCNHDMEGI.HNMBBFMBPHE = 1;
				return true;
			}
			return false;
		}
		return true;
	}

	private static bool DFJIKBDJNEG(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 114)
		{
			ILMCNHDMEGI.HNMBBFMBPHE = 10;
			return true;
		}
		return false;
	}

	private static bool GIAKPHDAHAF(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 117)
		{
			ILMCNHDMEGI.HNMBBFMBPHE = 11;
			return true;
		}
		return false;
	}

	private static bool LBJACCIBIJK(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 101)
		{
			ILMCNHDMEGI.BBMLNDGJLDP = true;
			ILMCNHDMEGI.HNMBBFMBPHE = 1;
			return true;
		}
		return false;
	}

	private static bool DDLHJLLPKIH(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 97)
		{
			ILMCNHDMEGI.HNMBBFMBPHE = 13;
			return true;
		}
		return false;
	}

	private static bool BBAPGPCHPDB(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 108)
		{
			ILMCNHDMEGI.HNMBBFMBPHE = 14;
			return true;
		}
		return false;
	}

	private static bool OLKFFILOKDB(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 115)
		{
			ILMCNHDMEGI.HNMBBFMBPHE = 15;
			return true;
		}
		return false;
	}

	private static bool GCFAAGCACDG(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 101)
		{
			ILMCNHDMEGI.BBMLNDGJLDP = true;
			ILMCNHDMEGI.HNMBBFMBPHE = 1;
			return true;
		}
		return false;
	}

	private static bool ANBHPKDMKMN(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 117)
		{
			ILMCNHDMEGI.HNMBBFMBPHE = 17;
			return true;
		}
		return false;
	}

	private static bool AJCMLPNOBPI(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 108)
		{
			ILMCNHDMEGI.HNMBBFMBPHE = 18;
			return true;
		}
		return false;
	}

	private static bool PGMKFDIDCDC(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 108)
		{
			ILMCNHDMEGI.BBMLNDGJLDP = true;
			ILMCNHDMEGI.HNMBBFMBPHE = 1;
			return true;
		}
		return false;
	}

	private static bool NFBDHMNCLFO(AEBEBKKBGEO ILMCNHDMEGI)
	{
		while (ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF())
		{
			switch (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC)
			{
			case 34:
				ILMCNHDMEGI.NBFDOJDLKOG.ACHGEFLAALD();
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				ILMCNHDMEGI.HNMBBFMBPHE = 20;
				return true;
			case 92:
				ILMCNHDMEGI.GFGJKAKHGMJ = 19;
				ILMCNHDMEGI.HNMBBFMBPHE = 21;
				return true;
			}
			ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
		}
		return true;
	}

	private static bool OMCFFLHNFAL(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 34)
		{
			ILMCNHDMEGI.BBMLNDGJLDP = true;
			ILMCNHDMEGI.HNMBBFMBPHE = 1;
			return true;
		}
		return false;
	}

	private static bool EGLCGAOPOCD(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		switch (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC)
		{
		case 117:
			ILMCNHDMEGI.HNMBBFMBPHE = 22;
			return true;
		case 34:
		case 39:
		case 47:
		case 92:
		case 98:
		case 102:
		case 110:
		case 114:
		case 116:
			ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append(GGAFIAJPDIJ(ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC));
			ILMCNHDMEGI.HNMBBFMBPHE = ILMCNHDMEGI.GFGJKAKHGMJ;
			return true;
		default:
			return false;
		}
	}

	private static bool KAGMMGMNMBI(AEBEBKKBGEO ILMCNHDMEGI)
	{
		int num = 0;
		int num2 = 4096;
		ILMCNHDMEGI.NBFDOJDLKOG.JNAGFDIPNJN = 0;
		while (ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF())
		{
			if ((ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 48 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 57) || (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 65 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 70) || (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC >= 97 && ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC <= 102))
			{
				ILMCNHDMEGI.NBFDOJDLKOG.JNAGFDIPNJN += GMFCIFKKGNC(ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC) * num2;
				num++;
				num2 /= 16;
				if (num == 4)
				{
					ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append(Convert.ToChar(ILMCNHDMEGI.NBFDOJDLKOG.JNAGFDIPNJN));
					ILMCNHDMEGI.HNMBBFMBPHE = ILMCNHDMEGI.GFGJKAKHGMJ;
					return true;
				}
				continue;
			}
			return false;
		}
		return true;
	}

	private static bool GLGBJLMEEGI(AEBEBKKBGEO ILMCNHDMEGI)
	{
		while (ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF())
		{
			switch (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC)
			{
			case 39:
				ILMCNHDMEGI.NBFDOJDLKOG.ACHGEFLAALD();
				ILMCNHDMEGI.BBMLNDGJLDP = true;
				ILMCNHDMEGI.HNMBBFMBPHE = 24;
				return true;
			case 92:
				ILMCNHDMEGI.GFGJKAKHGMJ = 23;
				ILMCNHDMEGI.HNMBBFMBPHE = 21;
				return true;
			}
			ILMCNHDMEGI.NBFDOJDLKOG.IFGAJIMCIAK.Append((char)ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC);
		}
		return true;
	}

	private static bool FOHHEIPHFMP(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		int hPLBPDOBIKC = ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC;
		if (hPLBPDOBIKC == 39)
		{
			ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC = 34;
			ILMCNHDMEGI.BBMLNDGJLDP = true;
			ILMCNHDMEGI.HNMBBFMBPHE = 1;
			return true;
		}
		return false;
	}

	private static bool DNHEKGKAEHH(AEBEBKKBGEO ILMCNHDMEGI)
	{
		ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF();
		switch (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC)
		{
		case 42:
			ILMCNHDMEGI.HNMBBFMBPHE = 27;
			return true;
		case 47:
			ILMCNHDMEGI.HNMBBFMBPHE = 26;
			return true;
		default:
			return false;
		}
	}

	private static bool CKGGNNELNDE(AEBEBKKBGEO ILMCNHDMEGI)
	{
		while (ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF())
		{
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC == 10)
			{
				ILMCNHDMEGI.HNMBBFMBPHE = 1;
				return true;
			}
		}
		return true;
	}

	private static bool PAFIAPOJBAM(AEBEBKKBGEO ILMCNHDMEGI)
	{
		while (ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF())
		{
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC == 42)
			{
				ILMCNHDMEGI.HNMBBFMBPHE = 28;
				return true;
			}
		}
		return true;
	}

	private static bool PKEJINOCBMF(AEBEBKKBGEO ILMCNHDMEGI)
	{
		while (ILMCNHDMEGI.NBFDOJDLKOG.NALMEJPLOBF())
		{
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC == 42)
			{
				continue;
			}
			if (ILMCNHDMEGI.NBFDOJDLKOG.HPLBPDOBIKC == 47)
			{
				ILMCNHDMEGI.HNMBBFMBPHE = 1;
				return true;
			}
			ILMCNHDMEGI.HNMBBFMBPHE = 27;
			return true;
		}
		return true;
	}

	private bool NALMEJPLOBF()
	{
		if ((HPLBPDOBIKC = HJCKKKBJNFJ()) != -1)
		{
			return true;
		}
		EOIEIDCNBGL = true;
		return false;
	}

	private int HJCKKKBJNFJ()
	{
		if (PCDHFKANEBM != 0)
		{
			int pCDHFKANEBM = PCDHFKANEBM;
			PCDHFKANEBM = 0;
			return pCDHFKANEBM;
		}
		return JIGJDAHIIBA.Read();
	}

	public bool NMLDMNBOJFN()
	{
		PJGODCHMIKB.BBMLNDGJLDP = false;
		while (true)
		{
			KKLMPOPLBKH kKLMPOPLBKH = KEIPFMNBMPJ[BGEDKGLJIGM - 1];
			if (!kKLMPOPLBKH(PJGODCHMIKB))
			{
				throw new AHFEPEFFHLL(HPLBPDOBIKC);
			}
			if (EOIEIDCNBGL)
			{
				return false;
			}
			if (PJGODCHMIKB.BBMLNDGJLDP)
			{
				break;
			}
			BGEDKGLJIGM = PJGODCHMIKB.HNMBBFMBPHE;
		}
		LECNLMBAAAD = IFGAJIMCIAK.ToString();
		IFGAJIMCIAK.Remove(0, IFGAJIMCIAK.Length);
		DJJGDFFDGFN = ECAEKCDFCBC[BGEDKGLJIGM - 1];
		if (DJJGDFFDGFN == 65542)
		{
			DJJGDFFDGFN = HPLBPDOBIKC;
		}
		BGEDKGLJIGM = PJGODCHMIKB.HNMBBFMBPHE;
		return true;
	}

	private void ACHGEFLAALD()
	{
		PCDHFKANEBM = HPLBPDOBIKC;
	}
}
