using System;

public class HEOPEFDAHFI : HFLDELFJCEE
{
	protected NHLBHJOEAMB MILMGDHGDHG;

	protected GFDALMJEJKF PNDPJNCMJEL;

	protected Uri BBNDBGDBCDI;

	public HEOPEFDAHFI(Uri FCPBJKBJNOJ, NHLBHJOEAMB MILMGDHGDHG, GFDALMJEJKF FIMGCDAHGGH)
	{
		BBNDBGDBCDI = FCPBJKBJNOJ;
		this.MILMGDHGDHG = MILMGDHGDHG;
		PNDPJNCMJEL = FIMGCDAHGGH;
	}

	public virtual void NGHHKPODNBG(PAJJBHMEFKE EIMEPDCAJLE)
	{
		if (!MILMGDHGDHG.NAFCDEECGEF(BBNDBGDBCDI, EIMEPDCAJLE.ELCOAJMCEMD()))
		{
			throw new DEIDBCPPCMB(90);
		}
	}

	public virtual OPCLIKBOHJP BOMAEPDBKLF(CGDEGBGOKJO MBEMNOCDDBC, OOKLBMMBONO FJLPCHOBGAM)
	{
		return (PNDPJNCMJEL != null) ? PNDPJNCMJEL.BOMAEPDBKLF(MBEMNOCDDBC, FJLPCHOBGAM) : null;
	}
}
