using System;

public class HIKKGKGPJII : ECBKNMOGLEG
{
	protected readonly CGDEGBGOKJO MBEMNOCDDBC;

	protected readonly LHAMCHLCIFH EGFFINOBDFH;

	protected readonly LHAMCHLCIFH CKDGLMGBEAL;

	public HIKKGKGPJII(CGDEGBGOKJO MBEMNOCDDBC)
	{
		this.MBEMNOCDDBC = MBEMNOCDDBC;
		EGFFINOBDFH = null;
		CKDGLMGBEAL = null;
	}

	public HIKKGKGPJII(CGDEGBGOKJO MBEMNOCDDBC, BJLAMONNNDD FPIFEGNLIEG, BJLAMONNNDD LLJMCJPMGHL)
	{
		if (FPIFEGNLIEG == null != (LLJMCJPMGHL == null))
		{
			throw new DEIDBCPPCMB(80);
		}
		this.MBEMNOCDDBC = MBEMNOCDDBC;
		LHAMCHLCIFH lHAMCHLCIFH = null;
		LHAMCHLCIFH lHAMCHLCIFH2 = null;
		if (FPIFEGNLIEG != null)
		{
			int num = FPIFEGNLIEG.EEMLLAMENHO() + LLJMCJPMGHL.EEMLLAMENHO();
			byte[] iKNCPEPOKGJ = KINEBFNENMB.IJLFLBPLJHD(MBEMNOCDDBC, num);
			int num2 = 0;
			lHAMCHLCIFH = new LHAMCHLCIFH(MBEMNOCDDBC, FPIFEGNLIEG, iKNCPEPOKGJ, num2, FPIFEGNLIEG.EEMLLAMENHO());
			num2 += FPIFEGNLIEG.EEMLLAMENHO();
			lHAMCHLCIFH2 = new LHAMCHLCIFH(MBEMNOCDDBC, LLJMCJPMGHL, iKNCPEPOKGJ, num2, LLJMCJPMGHL.EEMLLAMENHO());
			num2 += LLJMCJPMGHL.EEMLLAMENHO();
			if (num2 != num)
			{
				throw new DEIDBCPPCMB(80);
			}
		}
		if (MBEMNOCDDBC.DLHCCNKGKJP)
		{
			EGFFINOBDFH = lHAMCHLCIFH2;
			CKDGLMGBEAL = lHAMCHLCIFH;
		}
		else
		{
			EGFFINOBDFH = lHAMCHLCIFH;
			CKDGLMGBEAL = lHAMCHLCIFH2;
		}
	}

	public virtual int LBEOGHDBCJM(int DOILBJKOFDG)
	{
		int num = DOILBJKOFDG;
		if (EGFFINOBDFH != null)
		{
			num -= EGFFINOBDFH.PNBDAGKFOBN;
		}
		return num;
	}

	public virtual byte[] BIIKEIOAPCJ(long MHCDKMMAMKP, byte NBFBPNNEKMN, byte[] NEOIPBBDIMB, int IBNDGNOIEEF, int NBEDPKHALCN)
	{
		if (EGFFINOBDFH == null)
		{
			return NOGCEBKPPJE.EHLHBAMJLNI(NEOIPBBDIMB, IBNDGNOIEEF, IBNDGNOIEEF + NBEDPKHALCN);
		}
		byte[] array = EGFFINOBDFH.OFLKIODCBJJ(MHCDKMMAMKP, NBFBPNNEKMN, NEOIPBBDIMB, IBNDGNOIEEF, NBEDPKHALCN);
		byte[] array2 = new byte[NBEDPKHALCN + array.Length];
		Array.Copy(NEOIPBBDIMB, IBNDGNOIEEF, array2, 0, NBEDPKHALCN);
		Array.Copy(array, 0, array2, NBEDPKHALCN, array.Length);
		return array2;
	}

	public virtual byte[] OBMCLFEIPBL(long MHCDKMMAMKP, byte NBFBPNNEKMN, byte[] JNGDHEECGIG, int IBNDGNOIEEF, int NBEDPKHALCN)
	{
		if (CKDGLMGBEAL == null)
		{
			return NOGCEBKPPJE.EHLHBAMJLNI(JNGDHEECGIG, IBNDGNOIEEF, IBNDGNOIEEF + NBEDPKHALCN);
		}
		int num = CKDGLMGBEAL.PNBDAGKFOBN;
		if (NBEDPKHALCN < num)
		{
			throw new DEIDBCPPCMB(50);
		}
		int num2 = NBEDPKHALCN - num;
		byte[] mNIMEAMHNMI = NOGCEBKPPJE.EHLHBAMJLNI(JNGDHEECGIG, IBNDGNOIEEF + num2, IBNDGNOIEEF + NBEDPKHALCN);
		byte[] bCIHLCMFAEK = CKDGLMGBEAL.OFLKIODCBJJ(MHCDKMMAMKP, NBFBPNNEKMN, JNGDHEECGIG, IBNDGNOIEEF, num2);
		if (!NOGCEBKPPJE.PBBFCJBKJEN(mNIMEAMHNMI, bCIHLCMFAEK))
		{
			throw new DEIDBCPPCMB(20);
		}
		return NOGCEBKPPJE.EHLHBAMJLNI(JNGDHEECGIG, IBNDGNOIEEF, IBNDGNOIEEF + num2);
	}
}
