public abstract class HLKNPKHFGOH
{
	public static readonly KLKJHFKJLEM PLIFOLIJLJP = new KLKJHFKJLEM("2.16.840.1.113730.1");

	public static readonly KLKJHFKJLEM AJMECFJFFAD = PLIFOLIJLJP.BCDAGLPENOK("1");

	public static readonly KLKJHFKJLEM FJPJABBIEDJ = PLIFOLIJLJP.BCDAGLPENOK("2");

	public static readonly KLKJHFKJLEM OAILILGOANG = PLIFOLIJLJP.BCDAGLPENOK("3");

	public static readonly KLKJHFKJLEM HEFJFENHOED = PLIFOLIJLJP.BCDAGLPENOK("4");

	public static readonly KLKJHFKJLEM IMLABCEMGOF = PLIFOLIJLJP.BCDAGLPENOK("7");

	public static readonly KLKJHFKJLEM MGFNDEJOMAD = PLIFOLIJLJP.BCDAGLPENOK("8");

	public static readonly KLKJHFKJLEM AKOOCIKKLMH = PLIFOLIJLJP.BCDAGLPENOK("12");

	public static readonly KLKJHFKJLEM JHHNEJNMLGP = PLIFOLIJLJP.BCDAGLPENOK("13");

	public static readonly KLKJHFKJLEM MNEDIMGBEML = new KLKJHFKJLEM("2.16.840.1.113733.1");

	public static readonly KLKJHFKJLEM PEKDIEJCAJK = MNEDIMGBEML.BCDAGLPENOK("6.3");

	public static readonly KLKJHFKJLEM HHHKMBCPEIF = MNEDIMGBEML.BCDAGLPENOK("6.9");

	public static readonly KLKJHFKJLEM JDLPPLIGNCC = MNEDIMGBEML.BCDAGLPENOK("6.11");

	public static readonly KLKJHFKJLEM MLOJIOKIMKO = MNEDIMGBEML.BCDAGLPENOK("6.13");

	public static readonly KLKJHFKJLEM AGMMHBNOGIH = MNEDIMGBEML.BCDAGLPENOK("6.15");

	public static readonly KLKJHFKJLEM MPPICIAJGEH = MNEDIMGBEML.BCDAGLPENOK("8.1");

	public static readonly string FFFIGMEMIFJ = "2.16.840.1.113719";

	public static readonly KLKJHFKJLEM MEOBGBJHIPN = new KLKJHFKJLEM(FFFIGMEMIFJ + ".1.9.4.1");

	public static readonly string FHECMCKIPCL = "1.2.840.113533.7";

	public static readonly KLKJHFKJLEM HGICHIDDGDL = new KLKJHFKJLEM(FHECMCKIPCL + ".65.0");

	public static readonly KLKJHFKJLEM DGFMEJJNOHC = new KLKJHFKJLEM("1.3.6.1.4.1.188.7.1.1.2");

	public static readonly KLKJHFKJLEM JNBHGNHKJPA = new KLKJHFKJLEM("1.3.6.1.4.1.3029");

	public static readonly KLKJHFKJLEM FFBENNEPIPF = JNBHGNHKJPA.BCDAGLPENOK("1");

	public static readonly KLKJHFKJLEM DHJLGIFOCOH = FFBENNEPIPF.BCDAGLPENOK("1.1");

	public static readonly KLKJHFKJLEM HOKIBKEPBFJ = FFBENNEPIPF.BCDAGLPENOK("1.2");

	public static readonly KLKJHFKJLEM DKFKFBECDHA = FFBENNEPIPF.BCDAGLPENOK("1.3");

	public static readonly KLKJHFKJLEM OEBCPAOGEAM = FFBENNEPIPF.BCDAGLPENOK("1.4");

	public static readonly KLKJHFKJLEM EPEBCBEDLHA = new KLKJHFKJLEM("1.3.6.1.4.1.1722.12.2");

	public static readonly KLKJHFKJLEM EIMDEMBLKAC = EPEBCBEDLHA.BCDAGLPENOK("1.5");

	public static readonly KLKJHFKJLEM HDEJLMJNPMB = EPEBCBEDLHA.BCDAGLPENOK("1.8");

	public static readonly KLKJHFKJLEM LIKLHIPMOII = EPEBCBEDLHA.BCDAGLPENOK("1.12");

	public static readonly KLKJHFKJLEM JAHANBJABEC = EPEBCBEDLHA.BCDAGLPENOK("1.16");
}
