public class HLOAHBDHDHK : IMNCECFNKLL, HGIAHEKANFO
{
	private readonly int MOKLDCMGFFB;

	private readonly MKNDIEHOMOI BKOBLIALKKC;

	internal HLOAHBDHDHK(int MOKLDCMGFFB, MKNDIEHOMOI BKOBLIALKKC)
	{
		this.MOKLDCMGFFB = MOKLDCMGFFB;
		this.BKOBLIALKKC = BKOBLIALKKC;
	}

	public HGIAHEKANFO DMHLIGLGJGI()
	{
		return BKOBLIALKKC.DMHLIGLGJGI();
	}

	public EDOEBJJFOBM IIHKEACDNID()
	{
		return new IPJAJPAKCDB(MOKLDCMGFFB, BKOBLIALKKC.IFPAJCFNKGJ());
	}
}
