public class HMBOJCADBKN
{
	public string PNGPLGHKFDI;

	public int? EEFMIHDPJPG;

	public LivesInbox LGMFIJJIIDN;

	public int ENBPGGCIADN;

	public HMBOJCADBKN(string IOCMOCCFALN, int? BDKFNEDHAOJ, LivesInbox IKFGKFKACMN, int NBFBPNNEKMN)
	{
		PNGPLGHKFDI = IOCMOCCFALN;
		EEFMIHDPJPG = BDKFNEDHAOJ;
		LGMFIJJIIDN = IKFGKFKACMN;
		ENBPGGCIADN = NBFBPNNEKMN;
	}
}
