using System;
using Org.BouncyCastle.Math;

public class HMFDKDDBGPO : KBINBLGGLNE
{
	public const int JFEMFCDEFEN = 1;

	public const int MCCCDMHOAHE = 2;

	public const int LOCLNPAIPDP = 3;

	private int GLMLFOOCLPJ;

	private int CEKMAJAHNAG;

	private int[] APIJJGNJKNF;

	private IOPFKLMMOOP AMFCENFNAJJ;

	public override int LBAGICKMJNP
	{
		get
		{
			return AMFCENFNAJJ.NMAPLGALKKK();
		}
	}

	public override bool EOJCHPEGABD
	{
		get
		{
			return AMFCENFNAJJ.EOJCHPEGABD();
		}
	}

	public override bool EJJHHCOFAAI
	{
		get
		{
			return AMFCENFNAJJ.EJJHHCOFAAI();
		}
	}

	public override string DALLCADGMKK
	{
		get
		{
			return "F2m";
		}
	}

	public override int PJNLBAHOKGC
	{
		get
		{
			return CEKMAJAHNAG;
		}
	}

	public int ODKKDJMPBEO
	{
		get
		{
			return GLMLFOOCLPJ;
		}
	}

	public int IGBPKOOBCMA
	{
		get
		{
			return CEKMAJAHNAG;
		}
	}

	public int JDADINDBJLD
	{
		get
		{
			return APIJJGNJKNF[0];
		}
	}

	public int AELMELOBNJJ
	{
		get
		{
			return (APIJJGNJKNF.Length >= 2) ? APIJJGNJKNF[1] : 0;
		}
	}

	public int CKKHLMGICAB
	{
		get
		{
			return (APIJJGNJKNF.Length >= 3) ? APIJJGNJKNF[2] : 0;
		}
	}

	public HMFDKDDBGPO(int CEKMAJAHNAG, int KDFFDKFCDKK, int FKOBMEPIABG, int KHNDCPCHOEM, BigInteger AMFCENFNAJJ)
	{
		if (AMFCENFNAJJ == null || AMFCENFNAJJ.SignValue < 0 || AMFCENFNAJJ.BitLength > CEKMAJAHNAG)
		{
			throw new ArgumentException("value invalid in F2m field element", "x");
		}
		if (FKOBMEPIABG == 0 && KHNDCPCHOEM == 0)
		{
			GLMLFOOCLPJ = 2;
			APIJJGNJKNF = new int[1] { KDFFDKFCDKK };
		}
		else
		{
			if (FKOBMEPIABG >= KHNDCPCHOEM)
			{
				throw new ArgumentException("k2 must be smaller than k3");
			}
			if (FKOBMEPIABG <= 0)
			{
				throw new ArgumentException("k2 must be larger than 0");
			}
			GLMLFOOCLPJ = 3;
			APIJJGNJKNF = new int[3] { KDFFDKFCDKK, FKOBMEPIABG, KHNDCPCHOEM };
		}
		this.CEKMAJAHNAG = CEKMAJAHNAG;
		this.AMFCENFNAJJ = new IOPFKLMMOOP(AMFCENFNAJJ);
	}

	public HMFDKDDBGPO(int CEKMAJAHNAG, int BENKLGPHLGI, BigInteger AMFCENFNAJJ)
		: this(CEKMAJAHNAG, BENKLGPHLGI, 0, 0, AMFCENFNAJJ)
	{
	}

	private HMFDKDDBGPO(int CEKMAJAHNAG, int[] APIJJGNJKNF, IOPFKLMMOOP AMFCENFNAJJ)
	{
		this.CEKMAJAHNAG = CEKMAJAHNAG;
		GLMLFOOCLPJ = ((APIJJGNJKNF.Length != 1) ? 3 : 2);
		this.APIJJGNJKNF = APIJJGNJKNF;
		this.AMFCENFNAJJ = AMFCENFNAJJ;
	}

	public override bool OFGNPBCCHAA()
	{
		return AMFCENFNAJJ.OFGNPBCCHAA();
	}

	public override BigInteger DOJBPIFPALJ()
	{
		return AMFCENFNAJJ.DOJBPIFPALJ();
	}

	public static void FOAIMOICGCC(KBINBLGGLNE MNIMEAMHNMI, KBINBLGGLNE BCIHLCMFAEK)
	{
		if (!(MNIMEAMHNMI is HMFDKDDBGPO) || !(BCIHLCMFAEK is HMFDKDDBGPO))
		{
			throw new ArgumentException("Field elements are not both instances of F2mFieldElement");
		}
		HMFDKDDBGPO hMFDKDDBGPO = (HMFDKDDBGPO)MNIMEAMHNMI;
		HMFDKDDBGPO hMFDKDDBGPO2 = (HMFDKDDBGPO)BCIHLCMFAEK;
		if (hMFDKDDBGPO.GLMLFOOCLPJ != hMFDKDDBGPO2.GLMLFOOCLPJ)
		{
			throw new ArgumentException("One of the F2m field elements has incorrect representation");
		}
		if (hMFDKDDBGPO.CEKMAJAHNAG != hMFDKDDBGPO2.CEKMAJAHNAG || !NOGCEBKPPJE.ICKLINNFHKK(hMFDKDDBGPO.APIJJGNJKNF, hMFDKDDBGPO2.APIJJGNJKNF))
		{
			throw new ArgumentException("Field elements are not elements of the same field F2m");
		}
	}

	public override KBINBLGGLNE JEACJNAKLDJ(KBINBLGGLNE BCIHLCMFAEK)
	{
		IOPFKLMMOOP iOPFKLMMOOP = AMFCENFNAJJ.FDCFKGAEJFF();
		HMFDKDDBGPO hMFDKDDBGPO = (HMFDKDDBGPO)BCIHLCMFAEK;
		iOPFKLMMOOP.OMJOPOLAHOC(hMFDKDDBGPO.AMFCENFNAJJ, 0);
		return new HMFDKDDBGPO(CEKMAJAHNAG, APIJJGNJKNF, iOPFKLMMOOP);
	}

	public override KBINBLGGLNE AOAINNMNBHC()
	{
		return new HMFDKDDBGPO(CEKMAJAHNAG, APIJJGNJKNF, AMFCENFNAJJ.AOAINNMNBHC());
	}

	public override KBINBLGGLNE FBGIHKPECCO(KBINBLGGLNE BCIHLCMFAEK)
	{
		return JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override KBINBLGGLNE IBJBIGNPNEM(KBINBLGGLNE BCIHLCMFAEK)
	{
		return new HMFDKDDBGPO(CEKMAJAHNAG, APIJJGNJKNF, AMFCENFNAJJ.CPDIGLNAGGL(((HMFDKDDBGPO)BCIHLCMFAEK).AMFCENFNAJJ, CEKMAJAHNAG, APIJJGNJKNF));
	}

	public override KBINBLGGLNE MEBMJLIHOEJ(KBINBLGGLNE BCIHLCMFAEK, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
	{
		return CIDGMJAFLHM(BCIHLCMFAEK, AMFCENFNAJJ, CNLILOEEBOJ);
	}

	public override KBINBLGGLNE CIDGMJAFLHM(KBINBLGGLNE BCIHLCMFAEK, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
	{
		IOPFKLMMOOP aMFCENFNAJJ = this.AMFCENFNAJJ;
		IOPFKLMMOOP aMFCENFNAJJ2 = ((HMFDKDDBGPO)BCIHLCMFAEK).AMFCENFNAJJ;
		IOPFKLMMOOP aMFCENFNAJJ3 = ((HMFDKDDBGPO)AMFCENFNAJJ).AMFCENFNAJJ;
		IOPFKLMMOOP aMFCENFNAJJ4 = ((HMFDKDDBGPO)CNLILOEEBOJ).AMFCENFNAJJ;
		IOPFKLMMOOP iOPFKLMMOOP = aMFCENFNAJJ.IBJBIGNPNEM(aMFCENFNAJJ2, CEKMAJAHNAG, APIJJGNJKNF);
		IOPFKLMMOOP cJHEIBNHNNE = aMFCENFNAJJ3.IBJBIGNPNEM(aMFCENFNAJJ4, CEKMAJAHNAG, APIJJGNJKNF);
		if (iOPFKLMMOOP == aMFCENFNAJJ || iOPFKLMMOOP == aMFCENFNAJJ2)
		{
			iOPFKLMMOOP = iOPFKLMMOOP.FDCFKGAEJFF();
		}
		iOPFKLMMOOP.OMJOPOLAHOC(cJHEIBNHNNE, 0);
		iOPFKLMMOOP.BKCHMGKFECM(CEKMAJAHNAG, APIJJGNJKNF);
		return new HMFDKDDBGPO(CEKMAJAHNAG, APIJJGNJKNF, iOPFKLMMOOP);
	}

	public override KBINBLGGLNE MCPDGENJCDB(KBINBLGGLNE BCIHLCMFAEK)
	{
		KBINBLGGLNE bCIHLCMFAEK = BCIHLCMFAEK.LEIECFOMCNL();
		return IBJBIGNPNEM(bCIHLCMFAEK);
	}

	public override KBINBLGGLNE BHKOFHMDACN()
	{
		return this;
	}

	public override KBINBLGGLNE MIOEHGDPGAG()
	{
		return new HMFDKDDBGPO(CEKMAJAHNAG, APIJJGNJKNF, AMFCENFNAJJ.CPIOCAPDBEF(CEKMAJAHNAG, APIJJGNJKNF));
	}

	public override KBINBLGGLNE NGOGEEMPMGH(KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
	{
		return FGLCIBKKKFF(AMFCENFNAJJ, CNLILOEEBOJ);
	}

	public override KBINBLGGLNE FGLCIBKKKFF(KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
	{
		IOPFKLMMOOP aMFCENFNAJJ = this.AMFCENFNAJJ;
		IOPFKLMMOOP aMFCENFNAJJ2 = ((HMFDKDDBGPO)AMFCENFNAJJ).AMFCENFNAJJ;
		IOPFKLMMOOP aMFCENFNAJJ3 = ((HMFDKDDBGPO)CNLILOEEBOJ).AMFCENFNAJJ;
		IOPFKLMMOOP iOPFKLMMOOP = aMFCENFNAJJ.MIOEHGDPGAG(CEKMAJAHNAG, APIJJGNJKNF);
		IOPFKLMMOOP cJHEIBNHNNE = aMFCENFNAJJ2.IBJBIGNPNEM(aMFCENFNAJJ3, CEKMAJAHNAG, APIJJGNJKNF);
		if (iOPFKLMMOOP == aMFCENFNAJJ)
		{
			iOPFKLMMOOP = iOPFKLMMOOP.FDCFKGAEJFF();
		}
		iOPFKLMMOOP.OMJOPOLAHOC(cJHEIBNHNNE, 0);
		iOPFKLMMOOP.BKCHMGKFECM(CEKMAJAHNAG, APIJJGNJKNF);
		return new HMFDKDDBGPO(CEKMAJAHNAG, APIJJGNJKNF, iOPFKLMMOOP);
	}

	public override KBINBLGGLNE LHPDNIJHMIA(int DELAPGFJHAP)
	{
		return (DELAPGFJHAP >= 1) ? new HMFDKDDBGPO(CEKMAJAHNAG, APIJJGNJKNF, AMFCENFNAJJ.DHFOICNBPGK(DELAPGFJHAP, CEKMAJAHNAG, APIJJGNJKNF)) : this;
	}

	public override KBINBLGGLNE LEIECFOMCNL()
	{
		return new HMFDKDDBGPO(CEKMAJAHNAG, APIJJGNJKNF, AMFCENFNAJJ.DDENLEMHHAM(CEKMAJAHNAG, APIJJGNJKNF));
	}

	public override KBINBLGGLNE PAEDNKEIDOM()
	{
		return (!AMFCENFNAJJ.EJJHHCOFAAI() && !AMFCENFNAJJ.EOJCHPEGABD()) ? LHPDNIJHMIA(CEKMAJAHNAG - 1) : this;
	}

	public virtual bool KIFDKLPDKMD(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC == this)
		{
			return true;
		}
		HMFDKDDBGPO hMFDKDDBGPO = NEMEKIOEOLC as HMFDKDDBGPO;
		if (hMFDKDDBGPO == null)
		{
			return false;
		}
		return KIFDKLPDKMD(hMFDKDDBGPO);
	}

	public virtual bool KIFDKLPDKMD(HMFDKDDBGPO CJHEIBNHNNE)
	{
		return CEKMAJAHNAG == CJHEIBNHNNE.CEKMAJAHNAG && GLMLFOOCLPJ == CJHEIBNHNNE.GLMLFOOCLPJ && NOGCEBKPPJE.ICKLINNFHKK(APIJJGNJKNF, CJHEIBNHNNE.APIJJGNJKNF) && AMFCENFNAJJ.KIFDKLPDKMD(CJHEIBNHNNE.AMFCENFNAJJ);
	}

	public override int GetHashCode()
	{
		return AMFCENFNAJJ.GetHashCode() ^ CEKMAJAHNAG ^ NOGCEBKPPJE.ILMFICENEMK(APIJJGNJKNF);
	}
}
