public class HMLGPPFNDOD : NADPOFCHCON
{
	public HMLGPPFNDOD(IKDMCJPBBIH KAGBOIDKAED, GBJNCLLOCJB KFNJHBPIHOI)
		: base(KAGBOIDKAED, KFNJHBPIHOI)
	{
	}

	public override void JLECFJEAFCD()
	{
		KMBNIBGIHGH.CNDHPGOOPKO();
	}
}
