using System.IO;

public interface HMPLNBAPPNE
{
	bool GPEPNOJIMAB { get; }

	void DIOELAHNLKJ(CGDEGBGOKJO MBEMNOCDDBC);

	void PHFBGHEJBHM();

	void OPECIECMFCD(OPCLIKBOHJP BGFNAKMFCHD);

	void BGLKKBMEEEK(PAJJBHMEFKE EIMEPDCAJLE);

	byte[] DMJCNEDKPEA();

	void EDBOAAHOOMB();

	void OJGCPPFDPBN(Stream MOPCLEEGDFB);

	void JNMIHCPINHE(OOKLBMMBONO FJLPCHOBGAM);

	void IPDLGANAAKE();

	void FBGFHDOCEOO(OPCLIKBOHJP CLBMIAJGDMO);

	void KHJELAAEAPK(PAJJBHMEFKE HDJIOCGDIKM);

	void BAILJOPLLNN(Stream BILGCJNPJGJ);

	void DHMEHGEGGCB(Stream MOPCLEEGDFB);

	byte[] CGMFKLNEDAP();
}
