public static class HNFLMDPPECD
{
	public static bool EBAJIHOCKGM(this NOALGNJECAD HBBIFNLDKPO)
	{
		return HBBIFNLDKPO == NOALGNJECAD.SolidColor1 || HBBIFNLDKPO == NOALGNJECAD.SolidColor2 || HBBIFNLDKPO == NOALGNJECAD.SolidColor3 || HBBIFNLDKPO == NOALGNJECAD.SolidColor4 || HBBIFNLDKPO == NOALGNJECAD.SolidColor5 || HBBIFNLDKPO == NOALGNJECAD.SolidColor6;
	}

	public static bool MCMDJCBFENO(this NOALGNJECAD HBBIFNLDKPO)
	{
		return HBBIFNLDKPO == NOALGNJECAD.Rocket || HBBIFNLDKPO == NOALGNJECAD.Bomb || HBBIFNLDKPO == NOALGNJECAD.DiscoBall;
	}
}
