public class HPODBBIKPLB : ACDPFOPPPOP
{
	public HPODBBIKPLB(string MLNCFCEEFLL = "", string NDGJHCMKDON = "", bool DHPCLHLMCPG = true, bool JICOEKBHOFE = false)
	{
		base.MLNCFCEEFLL = MLNCFCEEFLL;
		base.NDGJHCMKDON = NDGJHCMKDON;
		base.DHPCLHLMCPG = DHPCLHLMCPG;
		base.JICOEKBHOFE = JICOEKBHOFE;
	}
}
