using System;

internal class ICLADBKHJFF : OMOBJNLGOBO
{
	public ICLADBKHJFF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public ICLADBKHJFF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal ICLADBKHJFF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new ICLADBKHJFF(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		NJABEGPIIEK nJABEGPIIEK = (NJABEGPIIEK)base.NBPANDNEJGI;
		NJABEGPIIEK nJABEGPIIEK2 = (NJABEGPIIEK)base.FIJLKLCHMGH;
		NJABEGPIIEK nJABEGPIIEK3 = (NJABEGPIIEK)BCIHLCMFAEK.NBPANDNEJGI;
		NJABEGPIIEK nJABEGPIIEK4 = (NJABEGPIIEK)BCIHLCMFAEK.FIJLKLCHMGH;
		NJABEGPIIEK nJABEGPIIEK5 = (NJABEGPIIEK)base.LAMGGDKLPJH[0];
		NJABEGPIIEK nJABEGPIIEK6 = (NJABEGPIIEK)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = AKOICJCJNFB.DCPJKFEDHOJ();
		uint[] array2 = AKOICJCJNFB.PLIFFMMBNPM();
		uint[] array3 = AKOICJCJNFB.PLIFFMMBNPM();
		uint[] array4 = AKOICJCJNFB.PLIFFMMBNPM();
		bool flag = nJABEGPIIEK5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = nJABEGPIIEK3.AMFCENFNAJJ;
			array6 = nJABEGPIIEK4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			PNKPNHLPKNF.MIOEHGDPGAG(nJABEGPIIEK5.AMFCENFNAJJ, array6);
			array5 = array2;
			PNKPNHLPKNF.IBJBIGNPNEM(array6, nJABEGPIIEK3.AMFCENFNAJJ, array5);
			PNKPNHLPKNF.IBJBIGNPNEM(array6, nJABEGPIIEK5.AMFCENFNAJJ, array6);
			PNKPNHLPKNF.IBJBIGNPNEM(array6, nJABEGPIIEK4.AMFCENFNAJJ, array6);
		}
		bool flag2 = nJABEGPIIEK6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = nJABEGPIIEK.AMFCENFNAJJ;
			array8 = nJABEGPIIEK2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			PNKPNHLPKNF.MIOEHGDPGAG(nJABEGPIIEK6.AMFCENFNAJJ, array8);
			array7 = array;
			PNKPNHLPKNF.IBJBIGNPNEM(array8, nJABEGPIIEK.AMFCENFNAJJ, array7);
			PNKPNHLPKNF.IBJBIGNPNEM(array8, nJABEGPIIEK6.AMFCENFNAJJ, array8);
			PNKPNHLPKNF.IBJBIGNPNEM(array8, nJABEGPIIEK2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = AKOICJCJNFB.PLIFFMMBNPM();
		PNKPNHLPKNF.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		PNKPNHLPKNF.FBGIHKPECCO(array8, array6, array10);
		if (AKOICJCJNFB.EJJHHCOFAAI(array9))
		{
			if (AKOICJCJNFB.EJJHHCOFAAI(array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		PNKPNHLPKNF.MIOEHGDPGAG(array9, array11);
		uint[] array12 = AKOICJCJNFB.PLIFFMMBNPM();
		PNKPNHLPKNF.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		PNKPNHLPKNF.IBJBIGNPNEM(array11, array7, array13);
		PNKPNHLPKNF.BHKOFHMDACN(array12, array12);
		AKOICJCJNFB.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = AKOICJCJNFB.FIBDFFPCDGC(array13, array13, array12);
		PNKPNHLPKNF.KKIGIOINLCI(aMFCENFNAJJ, array12);
		NJABEGPIIEK nJABEGPIIEK7 = new NJABEGPIIEK(array4);
		PNKPNHLPKNF.MIOEHGDPGAG(array10, nJABEGPIIEK7.AMFCENFNAJJ);
		PNKPNHLPKNF.FBGIHKPECCO(nJABEGPIIEK7.AMFCENFNAJJ, array12, nJABEGPIIEK7.AMFCENFNAJJ);
		NJABEGPIIEK nJABEGPIIEK8 = new NJABEGPIIEK(array12);
		PNKPNHLPKNF.FBGIHKPECCO(array13, nJABEGPIIEK7.AMFCENFNAJJ, nJABEGPIIEK8.AMFCENFNAJJ);
		PNKPNHLPKNF.OMJFFHEIEFH(nJABEGPIIEK8.AMFCENFNAJJ, array10, array);
		PNKPNHLPKNF.BKCHMGKFECM(array, nJABEGPIIEK8.AMFCENFNAJJ);
		NJABEGPIIEK nJABEGPIIEK9 = new NJABEGPIIEK(array9);
		if (!flag)
		{
			PNKPNHLPKNF.IBJBIGNPNEM(nJABEGPIIEK9.AMFCENFNAJJ, nJABEGPIIEK5.AMFCENFNAJJ, nJABEGPIIEK9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			PNKPNHLPKNF.IBJBIGNPNEM(nJABEGPIIEK9.AMFCENFNAJJ, nJABEGPIIEK6.AMFCENFNAJJ, nJABEGPIIEK9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { nJABEGPIIEK9 };
		return new ICLADBKHJFF(bHPIABAGAPB, nJABEGPIIEK7, nJABEGPIIEK8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		NJABEGPIIEK nJABEGPIIEK = (NJABEGPIIEK)base.FIJLKLCHMGH;
		if (nJABEGPIIEK.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		NJABEGPIIEK nJABEGPIIEK2 = (NJABEGPIIEK)base.NBPANDNEJGI;
		NJABEGPIIEK nJABEGPIIEK3 = (NJABEGPIIEK)base.LAMGGDKLPJH[0];
		uint[] array = AKOICJCJNFB.PLIFFMMBNPM();
		PNKPNHLPKNF.MIOEHGDPGAG(nJABEGPIIEK.AMFCENFNAJJ, array);
		uint[] array2 = AKOICJCJNFB.PLIFFMMBNPM();
		PNKPNHLPKNF.MIOEHGDPGAG(array, array2);
		uint[] array3 = AKOICJCJNFB.PLIFFMMBNPM();
		PNKPNHLPKNF.MIOEHGDPGAG(nJABEGPIIEK2.AMFCENFNAJJ, array3);
		uint aMFCENFNAJJ = AKOICJCJNFB.FIBDFFPCDGC(array3, array3, array3);
		PNKPNHLPKNF.KKIGIOINLCI(aMFCENFNAJJ, array3);
		uint[] array4 = array;
		PNKPNHLPKNF.IBJBIGNPNEM(array, nJABEGPIIEK2.AMFCENFNAJJ, array4);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(8, array4, 2, 0u);
		PNKPNHLPKNF.KKIGIOINLCI(aMFCENFNAJJ, array4);
		uint[] array5 = AKOICJCJNFB.PLIFFMMBNPM();
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(8, array2, 3, 0u, array5);
		PNKPNHLPKNF.KKIGIOINLCI(aMFCENFNAJJ, array5);
		NJABEGPIIEK nJABEGPIIEK4 = new NJABEGPIIEK(array2);
		PNKPNHLPKNF.MIOEHGDPGAG(array3, nJABEGPIIEK4.AMFCENFNAJJ);
		PNKPNHLPKNF.FBGIHKPECCO(nJABEGPIIEK4.AMFCENFNAJJ, array4, nJABEGPIIEK4.AMFCENFNAJJ);
		PNKPNHLPKNF.FBGIHKPECCO(nJABEGPIIEK4.AMFCENFNAJJ, array4, nJABEGPIIEK4.AMFCENFNAJJ);
		NJABEGPIIEK nJABEGPIIEK5 = new NJABEGPIIEK(array4);
		PNKPNHLPKNF.FBGIHKPECCO(array4, nJABEGPIIEK4.AMFCENFNAJJ, nJABEGPIIEK5.AMFCENFNAJJ);
		PNKPNHLPKNF.IBJBIGNPNEM(nJABEGPIIEK5.AMFCENFNAJJ, array3, nJABEGPIIEK5.AMFCENFNAJJ);
		PNKPNHLPKNF.FBGIHKPECCO(nJABEGPIIEK5.AMFCENFNAJJ, array5, nJABEGPIIEK5.AMFCENFNAJJ);
		NJABEGPIIEK nJABEGPIIEK6 = new NJABEGPIIEK(array3);
		PNKPNHLPKNF.LLGLJBDLBOP(nJABEGPIIEK.AMFCENFNAJJ, nJABEGPIIEK6.AMFCENFNAJJ);
		if (!nJABEGPIIEK3.EOJCHPEGABD)
		{
			PNKPNHLPKNF.IBJBIGNPNEM(nJABEGPIIEK6.AMFCENFNAJJ, nJABEGPIIEK3.AMFCENFNAJJ, nJABEGPIIEK6.AMFCENFNAJJ);
		}
		return new ICLADBKHJFF(bHPIABAGAPB, nJABEGPIIEK4, nJABEGPIIEK5, new KBINBLGGLNE[1] { nJABEGPIIEK6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new ICLADBKHJFF(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
