public class IEEPDCDKDNM : ACDPFOPPPOP
{
	public bool JIEIIOBOPLA;

	public IEEPDCDKDNM(string MLNCFCEEFLL = "", string NDGJHCMKDON = "", bool JIEIIOBOPLA = false, bool DHPCLHLMCPG = true, bool JICOEKBHOFE = false)
	{
		base.MLNCFCEEFLL = MLNCFCEEFLL;
		base.NDGJHCMKDON = NDGJHCMKDON;
		this.JIEIIOBOPLA = JIEIIOBOPLA;
		base.DHPCLHLMCPG = DHPCLHLMCPG;
		base.JICOEKBHOFE = JICOEKBHOFE;
	}
}
