public interface IEKIBBAKJDP
{
	string KFKMEPMEBND { get; }

	void DIOELAHNLKJ(bool CDOHJGCEGAJ, IGMAJHKIIPK IJJHBEECMBP);

	byte[] LFAFFAHKPCD(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int EOFAGACBNFP);

	byte[] FKFAOFJMEEF(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int EOFAGACBNFP);
}
