public struct IEMNAKGGKLB
{
	public int EHJNMODJEAN;

	public FKJCPPFCKFE LDMDBPLADGD;

	public IEMNAKGGKLB(int EHJNMODJEAN, FKJCPPFCKFE LDMDBPLADGD)
	{
		this.EHJNMODJEAN = EHJNMODJEAN;
		this.LDMDBPLADGD = LDMDBPLADGD;
	}
}
