public class IEOOBPLPNNL : GDHBILADCFG, HGIAHEKANFO
{
	private readonly MKNDIEHOMOI IGCEJBIEACI;

	internal IEOOBPLPNNL(MKNDIEHOMOI BKOBLIALKKC)
	{
		IGCEJBIEACI = BKOBLIALKKC;
	}

	public HGIAHEKANFO DMHLIGLGJGI()
	{
		return IGCEJBIEACI.DMHLIGLGJGI();
	}

	public EDOEBJJFOBM IIHKEACDNID()
	{
		return new KOGPLMALOEH(IGCEJBIEACI.IFPAJCFNKGJ());
	}
}
