using System.Collections;

public sealed class IFMGMOAKJAD
{
	private static readonly IDictionary JHHPAIKDGHF;

	private static readonly IDictionary ANNGLDLKCBL;

	public static IEnumerable IBDKONGLAHK
	{
		get
		{
			return new FLJIAKGGJBO(ANNGLDLKCBL.Values);
		}
	}

	private IFMGMOAKJAD()
	{
	}

	static IFMGMOAKJAD()
	{
		JHHPAIKDGHF = LHFGHNFJIKM.JBEOCJEMGCE();
		ANNGLDLKCBL = LHFGHNFJIKM.JBEOCJEMGCE();
		KKKFCBJCHMO("B-163", LNFIJKGIHLA.BHJPEMICEDI);
		KKKFCBJCHMO("B-233", LNFIJKGIHLA.MMCONAOLNPN);
		KKKFCBJCHMO("B-283", LNFIJKGIHLA.GFBEEEKLLDM);
		KKKFCBJCHMO("B-409", LNFIJKGIHLA.MKCKCGFMIMA);
		KKKFCBJCHMO("B-571", LNFIJKGIHLA.AOBMACFILLC);
		KKKFCBJCHMO("K-163", LNFIJKGIHLA.OKNDIFONNGH);
		KKKFCBJCHMO("K-233", LNFIJKGIHLA.LLKBFJKGMJD);
		KKKFCBJCHMO("K-283", LNFIJKGIHLA.NPMKDIEHOBN);
		KKKFCBJCHMO("K-409", LNFIJKGIHLA.CMEAOEDELNA);
		KKKFCBJCHMO("K-571", LNFIJKGIHLA.GPKADKBAHBJ);
		KKKFCBJCHMO("P-192", LNFIJKGIHLA.NKGAKBEPIEM);
		KKKFCBJCHMO("P-224", LNFIJKGIHLA.IOHKEAFEBNE);
		KKKFCBJCHMO("P-256", LNFIJKGIHLA.PECKBBNNGLC);
		KKKFCBJCHMO("P-384", LNFIJKGIHLA.AEMEHBDKHLF);
		KKKFCBJCHMO("P-521", LNFIJKGIHLA.BCCOIEKEHKB);
	}

	private static void KKKFCBJCHMO(string IOCMOCCFALN, KLKJHFKJLEM GDFLIKNMBCL)
	{
		JHHPAIKDGHF.Add(LHFGHNFJIKM.OGLCLCODHJI(IOCMOCCFALN), GDFLIKNMBCL);
		ANNGLDLKCBL.Add(GDFLIKNMBCL, IOCMOCCFALN);
	}

	public static JMLDNPGFBDA KJOGHMPFOHL(string IOCMOCCFALN)
	{
		KLKJHFKJLEM kLKJHFKJLEM = MAKKKJHMAHH(IOCMOCCFALN);
		return (kLKJHFKJLEM != null) ? BHLONOMMIGE(kLKJHFKJLEM) : null;
	}

	public static JMLDNPGFBDA BHLONOMMIGE(KLKJHFKJLEM GDFLIKNMBCL)
	{
		return HGIJNPOCIFN.BHLONOMMIGE(GDFLIKNMBCL);
	}

	public static KLKJHFKJLEM MAKKKJHMAHH(string IOCMOCCFALN)
	{
		return (KLKJHFKJLEM)JHHPAIKDGHF[LHFGHNFJIKM.OGLCLCODHJI(IOCMOCCFALN)];
	}

	public static string CILJKDELPFP(KLKJHFKJLEM GDFLIKNMBCL)
	{
		return (string)ANNGLDLKCBL[GDFLIKNMBCL];
	}
}
