public class IHNCFFPEECN : LFADADGHPPC
{
	protected readonly KBINBLGGLNE HJLOCAEAFMJ;

	public IHNCFFPEECN(KBINBLGGLNE HJLOCAEAFMJ)
	{
		this.HJLOCAEAFMJ = HJLOCAEAFMJ;
	}

	public virtual JGAFKLGGBGF FBDFAFGCDIO(JGAFKLGGBGF HPHBDNBJPHB)
	{
		return HPHBDNBJPHB.FLDLCFHBMEA(HJLOCAEAFMJ);
	}
}
