using System;
using Org.BouncyCastle.Math;

internal class IKBHHNIGFHL : KBINBLGGLNE
{
	public static readonly BigInteger FNPELDEHJKL = PGKOBFICMII.OKDPJHOEPBJ;

	protected internal readonly uint[] AMFCENFNAJJ;

	public override bool EJJHHCOFAAI
	{
		get
		{
			return MADOAPNPCCB.EJJHHCOFAAI(AMFCENFNAJJ);
		}
	}

	public override bool EOJCHPEGABD
	{
		get
		{
			return MADOAPNPCCB.EOJCHPEGABD(AMFCENFNAJJ);
		}
	}

	public override string DALLCADGMKK
	{
		get
		{
			return "SecP224R1Field";
		}
	}

	public override int PJNLBAHOKGC
	{
		get
		{
			return FNPELDEHJKL.BitLength;
		}
	}

	public IKBHHNIGFHL(BigInteger AMFCENFNAJJ)
	{
		if (AMFCENFNAJJ == null || AMFCENFNAJJ.SignValue < 0 || AMFCENFNAJJ.JLPDKNFCNPO(FNPELDEHJKL) >= 0)
		{
			throw new ArgumentException("value invalid for SecP224R1FieldElement", "x");
		}
		this.AMFCENFNAJJ = ADLDIDKJJFG.HFENNGHNFLF(AMFCENFNAJJ);
	}

	public IKBHHNIGFHL()
	{
		AMFCENFNAJJ = MADOAPNPCCB.PLIFFMMBNPM();
	}

	protected internal IKBHHNIGFHL(uint[] AMFCENFNAJJ)
	{
		this.AMFCENFNAJJ = AMFCENFNAJJ;
	}

	public override bool OFGNPBCCHAA()
	{
		return MADOAPNPCCB.DOFLEKCIDCA(AMFCENFNAJJ, 0) == 1;
	}

	public override BigInteger DOJBPIFPALJ()
	{
		return MADOAPNPCCB.DOJBPIFPALJ(AMFCENFNAJJ);
	}

	public override KBINBLGGLNE JEACJNAKLDJ(KBINBLGGLNE BCIHLCMFAEK)
	{
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.JEACJNAKLDJ(AMFCENFNAJJ, ((IKBHHNIGFHL)BCIHLCMFAEK).AMFCENFNAJJ, array);
		return new IKBHHNIGFHL(array);
	}

	public override KBINBLGGLNE AOAINNMNBHC()
	{
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.AOAINNMNBHC(AMFCENFNAJJ, array);
		return new IKBHHNIGFHL(array);
	}

	public override KBINBLGGLNE FBGIHKPECCO(KBINBLGGLNE BCIHLCMFAEK)
	{
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.FBGIHKPECCO(AMFCENFNAJJ, ((IKBHHNIGFHL)BCIHLCMFAEK).AMFCENFNAJJ, array);
		return new IKBHHNIGFHL(array);
	}

	public override KBINBLGGLNE IBJBIGNPNEM(KBINBLGGLNE BCIHLCMFAEK)
	{
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.IBJBIGNPNEM(AMFCENFNAJJ, ((IKBHHNIGFHL)BCIHLCMFAEK).AMFCENFNAJJ, array);
		return new IKBHHNIGFHL(array);
	}

	public override KBINBLGGLNE MCPDGENJCDB(KBINBLGGLNE BCIHLCMFAEK)
	{
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		JHJKFDMNDBP.LEIECFOMCNL(ADLDIDKJJFG.MBIJHANOCOC, ((IKBHHNIGFHL)BCIHLCMFAEK).AMFCENFNAJJ, array);
		ADLDIDKJJFG.IBJBIGNPNEM(array, AMFCENFNAJJ, array);
		return new IKBHHNIGFHL(array);
	}

	public override KBINBLGGLNE BHKOFHMDACN()
	{
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.BHKOFHMDACN(AMFCENFNAJJ, array);
		return new IKBHHNIGFHL(array);
	}

	public override KBINBLGGLNE MIOEHGDPGAG()
	{
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.MIOEHGDPGAG(AMFCENFNAJJ, array);
		return new IKBHHNIGFHL(array);
	}

	public override KBINBLGGLNE LEIECFOMCNL()
	{
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		JHJKFDMNDBP.LEIECFOMCNL(ADLDIDKJJFG.MBIJHANOCOC, AMFCENFNAJJ, array);
		return new IKBHHNIGFHL(array);
	}

	public override KBINBLGGLNE PAEDNKEIDOM()
	{
		uint[] aMFCENFNAJJ = AMFCENFNAJJ;
		if (MADOAPNPCCB.EJJHHCOFAAI(aMFCENFNAJJ) || MADOAPNPCCB.EOJCHPEGABD(aMFCENFNAJJ))
		{
			return this;
		}
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		ADLDIDKJJFG.BHKOFHMDACN(aMFCENFNAJJ, array);
		uint[] array2 = JHJKFDMNDBP.IPFKDIJBGIM(ADLDIDKJJFG.MBIJHANOCOC);
		uint[] array3 = MADOAPNPCCB.PLIFFMMBNPM();
		if (!BAHLFIMEDDF(aMFCENFNAJJ))
		{
			return null;
		}
		while (!CFLBGOMJNNO(array, array2, array3))
		{
			ADLDIDKJJFG.AOAINNMNBHC(array2, array2);
		}
		ADLDIDKJJFG.MIOEHGDPGAG(array3, array2);
		return (!MADOAPNPCCB.HIPMIOOIEJO(aMFCENFNAJJ, array2)) ? null : new IKBHHNIGFHL(array3);
	}

	public virtual bool KIFDKLPDKMD(object NEMEKIOEOLC)
	{
		return KIFDKLPDKMD(NEMEKIOEOLC as IKBHHNIGFHL);
	}

	public override bool KIFDKLPDKMD(KBINBLGGLNE CJHEIBNHNNE)
	{
		return KIFDKLPDKMD(CJHEIBNHNNE as IKBHHNIGFHL);
	}

	public virtual bool KIFDKLPDKMD(IKBHHNIGFHL CJHEIBNHNNE)
	{
		if (this == CJHEIBNHNNE)
		{
			return true;
		}
		if (CJHEIBNHNNE == null)
		{
			return false;
		}
		return MADOAPNPCCB.HIPMIOOIEJO(AMFCENFNAJJ, CJHEIBNHNNE.AMFCENFNAJJ);
	}

	public override int GetHashCode()
	{
		return FNPELDEHJKL.GetHashCode() ^ NOGCEBKPPJE.ILMFICENEMK(AMFCENFNAJJ, 0, 7);
	}

	private static bool BAHLFIMEDDF(uint[] AMFCENFNAJJ)
	{
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		uint[] array2 = MADOAPNPCCB.PLIFFMMBNPM();
		MADOAPNPCCB.FDCFKGAEJFF(AMFCENFNAJJ, array);
		for (int i = 0; i < 7; i++)
		{
			MADOAPNPCCB.FDCFKGAEJFF(array, array2);
			ADLDIDKJJFG.OIEFGPHNOFN(array, 1 << i, array);
			ADLDIDKJJFG.IBJBIGNPNEM(array, array2, array);
		}
		ADLDIDKJJFG.OIEFGPHNOFN(array, 95, array);
		return MADOAPNPCCB.EOJCHPEGABD(array);
	}

	private static void ECMGLFHLFGH(uint[] GDMOEEKGACM, uint[] IFNBAJNGFJI, uint[] NJPMCMOGLIL, uint[] IAPHFDOKNAN, uint[] MDMDDNNMBEJ, uint[] MGBFNGCLLGC, uint[] LLIEHCKNJEM)
	{
		ADLDIDKJJFG.IBJBIGNPNEM(MDMDDNNMBEJ, NJPMCMOGLIL, LLIEHCKNJEM);
		ADLDIDKJJFG.IBJBIGNPNEM(LLIEHCKNJEM, GDMOEEKGACM, LLIEHCKNJEM);
		ADLDIDKJJFG.IBJBIGNPNEM(IAPHFDOKNAN, IFNBAJNGFJI, MGBFNGCLLGC);
		ADLDIDKJJFG.JEACJNAKLDJ(MGBFNGCLLGC, LLIEHCKNJEM, MGBFNGCLLGC);
		ADLDIDKJJFG.IBJBIGNPNEM(IAPHFDOKNAN, NJPMCMOGLIL, LLIEHCKNJEM);
		MADOAPNPCCB.FDCFKGAEJFF(MGBFNGCLLGC, IAPHFDOKNAN);
		ADLDIDKJJFG.IBJBIGNPNEM(MDMDDNNMBEJ, IFNBAJNGFJI, MDMDDNNMBEJ);
		ADLDIDKJJFG.JEACJNAKLDJ(MDMDDNNMBEJ, LLIEHCKNJEM, MDMDDNNMBEJ);
		ADLDIDKJJFG.MIOEHGDPGAG(MDMDDNNMBEJ, MGBFNGCLLGC);
		ADLDIDKJJFG.IBJBIGNPNEM(MGBFNGCLLGC, GDMOEEKGACM, MGBFNGCLLGC);
	}

	private static void PHOBLKEOEBB(uint[] GDMOEEKGACM, uint[] IAPHFDOKNAN, uint[] MDMDDNNMBEJ, uint[] MGBFNGCLLGC, uint[] LLIEHCKNJEM)
	{
		MADOAPNPCCB.FDCFKGAEJFF(GDMOEEKGACM, MGBFNGCLLGC);
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		uint[] array2 = MADOAPNPCCB.PLIFFMMBNPM();
		for (int i = 0; i < 7; i++)
		{
			MADOAPNPCCB.FDCFKGAEJFF(IAPHFDOKNAN, array);
			MADOAPNPCCB.FDCFKGAEJFF(MDMDDNNMBEJ, array2);
			int num = 1 << i;
			while (--num >= 0)
			{
				OJNJHICDCEO(IAPHFDOKNAN, MDMDDNNMBEJ, MGBFNGCLLGC, LLIEHCKNJEM);
			}
			ECMGLFHLFGH(GDMOEEKGACM, array, array2, IAPHFDOKNAN, MDMDDNNMBEJ, MGBFNGCLLGC, LLIEHCKNJEM);
		}
	}

	private static void OJNJHICDCEO(uint[] ELNCCDELMMH, uint[] EKFOKNPODBK, uint[] GNGLLMMGOJI, uint[] LLIEHCKNJEM)
	{
		ADLDIDKJJFG.IBJBIGNPNEM(EKFOKNPODBK, ELNCCDELMMH, EKFOKNPODBK);
		ADLDIDKJJFG.LLGLJBDLBOP(EKFOKNPODBK, EKFOKNPODBK);
		ADLDIDKJJFG.MIOEHGDPGAG(ELNCCDELMMH, LLIEHCKNJEM);
		ADLDIDKJJFG.JEACJNAKLDJ(GNGLLMMGOJI, LLIEHCKNJEM, ELNCCDELMMH);
		ADLDIDKJJFG.IBJBIGNPNEM(GNGLLMMGOJI, LLIEHCKNJEM, GNGLLMMGOJI);
		uint aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(7, GNGLLMMGOJI, 2, 0u);
		ADLDIDKJJFG.KKIGIOINLCI(aMFCENFNAJJ, GNGLLMMGOJI);
	}

	private static bool CFLBGOMJNNO(uint[] GDMOEEKGACM, uint[] GPGDCCMECGF, uint[] LLIEHCKNJEM)
	{
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		MADOAPNPCCB.FDCFKGAEJFF(GPGDCCMECGF, array);
		uint[] array2 = MADOAPNPCCB.PLIFFMMBNPM();
		array2[0] = 1u;
		uint[] array3 = MADOAPNPCCB.PLIFFMMBNPM();
		PHOBLKEOEBB(GDMOEEKGACM, array, array2, array3, LLIEHCKNJEM);
		uint[] array4 = MADOAPNPCCB.PLIFFMMBNPM();
		uint[] array5 = MADOAPNPCCB.PLIFFMMBNPM();
		for (int i = 1; i < 96; i++)
		{
			MADOAPNPCCB.FDCFKGAEJFF(array, array4);
			MADOAPNPCCB.FDCFKGAEJFF(array2, array5);
			OJNJHICDCEO(array, array2, array3, LLIEHCKNJEM);
			if (MADOAPNPCCB.EJJHHCOFAAI(array))
			{
				JHJKFDMNDBP.LEIECFOMCNL(ADLDIDKJJFG.MBIJHANOCOC, array5, LLIEHCKNJEM);
				ADLDIDKJJFG.IBJBIGNPNEM(LLIEHCKNJEM, array4, LLIEHCKNJEM);
				return true;
			}
		}
		return false;
	}
}
