public sealed class ILOJEJJCAEK : CNDMOBHIMJA
{
	private const int DFBJOFIADHK = 12;

	private const int ANKLOALOPKP = 16;

	private int[] FPEIGKHPEHG = new int[48];

	private uint[] HAODKGBJMLK = new uint[48];

	private int[] ABHKMFOKPKE = new int[192];

	private uint[] DNPCLLNNJPE = new uint[192];

	private uint[] PFGAANOKEJC = new uint[8];

	public override string KFKMEPMEBND
	{
		get
		{
			return "CAST6";
		}
	}

	public override void OMOKOKFNBKI()
	{
	}

	public override int BDIGGHEPIIP()
	{
		return 16;
	}

	internal override void KBEFMBDOIJH(byte[] IKNCPEPOKGJ)
	{
		uint num = 1518500249u;
		uint num2 = 1859775393u;
		int num3 = 19;
		int num4 = 17;
		for (int i = 0; i < 24; i++)
		{
			for (int j = 0; j < 8; j++)
			{
				DNPCLLNNJPE[i * 8 + j] = num;
				num += num2;
				ABHKMFOKPKE[i * 8 + j] = num3;
				num3 = (num3 + num4) & 0x1F;
			}
		}
		byte[] array = new byte[64];
		IKNCPEPOKGJ.CopyTo(array, 0);
		for (int k = 0; k < 8; k++)
		{
			PFGAANOKEJC[k] = PGOKFBKEOAB.EFODDMAJNOA(array, k * 4);
		}
		for (int l = 0; l < 12; l++)
		{
			int num5 = l * 2 * 8;
			PFGAANOKEJC[6] ^= CNDMOBHIMJA.HBFJAOFJIFP(PFGAANOKEJC[7], DNPCLLNNJPE[num5], ABHKMFOKPKE[num5]);
			PFGAANOKEJC[5] ^= CNDMOBHIMJA.IKKGCFMJODC(PFGAANOKEJC[6], DNPCLLNNJPE[num5 + 1], ABHKMFOKPKE[num5 + 1]);
			PFGAANOKEJC[4] ^= CNDMOBHIMJA.HJEBNCKAABK(PFGAANOKEJC[5], DNPCLLNNJPE[num5 + 2], ABHKMFOKPKE[num5 + 2]);
			PFGAANOKEJC[3] ^= CNDMOBHIMJA.HBFJAOFJIFP(PFGAANOKEJC[4], DNPCLLNNJPE[num5 + 3], ABHKMFOKPKE[num5 + 3]);
			PFGAANOKEJC[2] ^= CNDMOBHIMJA.IKKGCFMJODC(PFGAANOKEJC[3], DNPCLLNNJPE[num5 + 4], ABHKMFOKPKE[num5 + 4]);
			PFGAANOKEJC[1] ^= CNDMOBHIMJA.HJEBNCKAABK(PFGAANOKEJC[2], DNPCLLNNJPE[num5 + 5], ABHKMFOKPKE[num5 + 5]);
			PFGAANOKEJC[0] ^= CNDMOBHIMJA.HBFJAOFJIFP(PFGAANOKEJC[1], DNPCLLNNJPE[num5 + 6], ABHKMFOKPKE[num5 + 6]);
			PFGAANOKEJC[7] ^= CNDMOBHIMJA.IKKGCFMJODC(PFGAANOKEJC[0], DNPCLLNNJPE[num5 + 7], ABHKMFOKPKE[num5 + 7]);
			num5 = (l * 2 + 1) * 8;
			PFGAANOKEJC[6] ^= CNDMOBHIMJA.HBFJAOFJIFP(PFGAANOKEJC[7], DNPCLLNNJPE[num5], ABHKMFOKPKE[num5]);
			PFGAANOKEJC[5] ^= CNDMOBHIMJA.IKKGCFMJODC(PFGAANOKEJC[6], DNPCLLNNJPE[num5 + 1], ABHKMFOKPKE[num5 + 1]);
			PFGAANOKEJC[4] ^= CNDMOBHIMJA.HJEBNCKAABK(PFGAANOKEJC[5], DNPCLLNNJPE[num5 + 2], ABHKMFOKPKE[num5 + 2]);
			PFGAANOKEJC[3] ^= CNDMOBHIMJA.HBFJAOFJIFP(PFGAANOKEJC[4], DNPCLLNNJPE[num5 + 3], ABHKMFOKPKE[num5 + 3]);
			PFGAANOKEJC[2] ^= CNDMOBHIMJA.IKKGCFMJODC(PFGAANOKEJC[3], DNPCLLNNJPE[num5 + 4], ABHKMFOKPKE[num5 + 4]);
			PFGAANOKEJC[1] ^= CNDMOBHIMJA.HJEBNCKAABK(PFGAANOKEJC[2], DNPCLLNNJPE[num5 + 5], ABHKMFOKPKE[num5 + 5]);
			PFGAANOKEJC[0] ^= CNDMOBHIMJA.HBFJAOFJIFP(PFGAANOKEJC[1], DNPCLLNNJPE[num5 + 6], ABHKMFOKPKE[num5 + 6]);
			PFGAANOKEJC[7] ^= CNDMOBHIMJA.IKKGCFMJODC(PFGAANOKEJC[0], DNPCLLNNJPE[num5 + 7], ABHKMFOKPKE[num5 + 7]);
			FPEIGKHPEHG[l * 4] = (int)(PFGAANOKEJC[0] & 0x1F);
			FPEIGKHPEHG[l * 4 + 1] = (int)(PFGAANOKEJC[2] & 0x1F);
			FPEIGKHPEHG[l * 4 + 2] = (int)(PFGAANOKEJC[4] & 0x1F);
			FPEIGKHPEHG[l * 4 + 3] = (int)(PFGAANOKEJC[6] & 0x1F);
			HAODKGBJMLK[l * 4] = PFGAANOKEJC[7];
			HAODKGBJMLK[l * 4 + 1] = PFGAANOKEJC[5];
			HAODKGBJMLK[l * 4 + 2] = PFGAANOKEJC[3];
			HAODKGBJMLK[l * 4 + 3] = PFGAANOKEJC[1];
		}
	}

	internal override int HDOLNBOHAJA(byte[] ENICBMKPJJK, int LPOANJMPJMG, byte[] PPFHFMDDDLM, int IJJEDDKCAOE)
	{
		uint jEHECJGFJEB = PGOKFBKEOAB.EFODDMAJNOA(ENICBMKPJJK, LPOANJMPJMG);
		uint fPKDKHJKEEF = PGOKFBKEOAB.EFODDMAJNOA(ENICBMKPJJK, LPOANJMPJMG + 4);
		uint aNGINAGELKI = PGOKFBKEOAB.EFODDMAJNOA(ENICBMKPJJK, LPOANJMPJMG + 8);
		uint iNCIODEICNM = PGOKFBKEOAB.EFODDMAJNOA(ENICBMKPJJK, LPOANJMPJMG + 12);
		uint[] array = new uint[4];
		AKGIDMCKBIB(jEHECJGFJEB, fPKDKHJKEEF, aNGINAGELKI, iNCIODEICNM, array);
		PGOKFBKEOAB.MPMAFPANDLC(array[0], PPFHFMDDDLM, IJJEDDKCAOE);
		PGOKFBKEOAB.MPMAFPANDLC(array[1], PPFHFMDDDLM, IJJEDDKCAOE + 4);
		PGOKFBKEOAB.MPMAFPANDLC(array[2], PPFHFMDDDLM, IJJEDDKCAOE + 8);
		PGOKFBKEOAB.MPMAFPANDLC(array[3], PPFHFMDDDLM, IJJEDDKCAOE + 12);
		return 16;
	}

	internal override int GFKALHGNIOJ(byte[] ENICBMKPJJK, int LPOANJMPJMG, byte[] PPFHFMDDDLM, int IJJEDDKCAOE)
	{
		uint jEHECJGFJEB = PGOKFBKEOAB.EFODDMAJNOA(ENICBMKPJJK, LPOANJMPJMG);
		uint fPKDKHJKEEF = PGOKFBKEOAB.EFODDMAJNOA(ENICBMKPJJK, LPOANJMPJMG + 4);
		uint aNGINAGELKI = PGOKFBKEOAB.EFODDMAJNOA(ENICBMKPJJK, LPOANJMPJMG + 8);
		uint iNCIODEICNM = PGOKFBKEOAB.EFODDMAJNOA(ENICBMKPJJK, LPOANJMPJMG + 12);
		uint[] array = new uint[4];
		CIJDHKPAPMN(jEHECJGFJEB, fPKDKHJKEEF, aNGINAGELKI, iNCIODEICNM, array);
		PGOKFBKEOAB.MPMAFPANDLC(array[0], PPFHFMDDDLM, IJJEDDKCAOE);
		PGOKFBKEOAB.MPMAFPANDLC(array[1], PPFHFMDDDLM, IJJEDDKCAOE + 4);
		PGOKFBKEOAB.MPMAFPANDLC(array[2], PPFHFMDDDLM, IJJEDDKCAOE + 8);
		PGOKFBKEOAB.MPMAFPANDLC(array[3], PPFHFMDDDLM, IJJEDDKCAOE + 12);
		return 16;
	}

	private void AKGIDMCKBIB(uint JEHECJGFJEB, uint FPKDKHJKEEF, uint ANGINAGELKI, uint INCIODEICNM, uint[] DIDHNNMKJFE)
	{
		for (int i = 0; i < 6; i++)
		{
			int num = i * 4;
			ANGINAGELKI ^= CNDMOBHIMJA.HBFJAOFJIFP(INCIODEICNM, HAODKGBJMLK[num], FPEIGKHPEHG[num]);
			FPKDKHJKEEF ^= CNDMOBHIMJA.IKKGCFMJODC(ANGINAGELKI, HAODKGBJMLK[num + 1], FPEIGKHPEHG[num + 1]);
			JEHECJGFJEB ^= CNDMOBHIMJA.HJEBNCKAABK(FPKDKHJKEEF, HAODKGBJMLK[num + 2], FPEIGKHPEHG[num + 2]);
			INCIODEICNM ^= CNDMOBHIMJA.HBFJAOFJIFP(JEHECJGFJEB, HAODKGBJMLK[num + 3], FPEIGKHPEHG[num + 3]);
		}
		for (int j = 6; j < 12; j++)
		{
			int num2 = j * 4;
			INCIODEICNM ^= CNDMOBHIMJA.HBFJAOFJIFP(JEHECJGFJEB, HAODKGBJMLK[num2 + 3], FPEIGKHPEHG[num2 + 3]);
			JEHECJGFJEB ^= CNDMOBHIMJA.HJEBNCKAABK(FPKDKHJKEEF, HAODKGBJMLK[num2 + 2], FPEIGKHPEHG[num2 + 2]);
			FPKDKHJKEEF ^= CNDMOBHIMJA.IKKGCFMJODC(ANGINAGELKI, HAODKGBJMLK[num2 + 1], FPEIGKHPEHG[num2 + 1]);
			ANGINAGELKI ^= CNDMOBHIMJA.HBFJAOFJIFP(INCIODEICNM, HAODKGBJMLK[num2], FPEIGKHPEHG[num2]);
		}
		DIDHNNMKJFE[0] = JEHECJGFJEB;
		DIDHNNMKJFE[1] = FPKDKHJKEEF;
		DIDHNNMKJFE[2] = ANGINAGELKI;
		DIDHNNMKJFE[3] = INCIODEICNM;
	}

	private void CIJDHKPAPMN(uint JEHECJGFJEB, uint FPKDKHJKEEF, uint ANGINAGELKI, uint INCIODEICNM, uint[] DIDHNNMKJFE)
	{
		for (int i = 0; i < 6; i++)
		{
			int num = (11 - i) * 4;
			ANGINAGELKI ^= CNDMOBHIMJA.HBFJAOFJIFP(INCIODEICNM, HAODKGBJMLK[num], FPEIGKHPEHG[num]);
			FPKDKHJKEEF ^= CNDMOBHIMJA.IKKGCFMJODC(ANGINAGELKI, HAODKGBJMLK[num + 1], FPEIGKHPEHG[num + 1]);
			JEHECJGFJEB ^= CNDMOBHIMJA.HJEBNCKAABK(FPKDKHJKEEF, HAODKGBJMLK[num + 2], FPEIGKHPEHG[num + 2]);
			INCIODEICNM ^= CNDMOBHIMJA.HBFJAOFJIFP(JEHECJGFJEB, HAODKGBJMLK[num + 3], FPEIGKHPEHG[num + 3]);
		}
		for (int j = 6; j < 12; j++)
		{
			int num2 = (11 - j) * 4;
			INCIODEICNM ^= CNDMOBHIMJA.HBFJAOFJIFP(JEHECJGFJEB, HAODKGBJMLK[num2 + 3], FPEIGKHPEHG[num2 + 3]);
			JEHECJGFJEB ^= CNDMOBHIMJA.HJEBNCKAABK(FPKDKHJKEEF, HAODKGBJMLK[num2 + 2], FPEIGKHPEHG[num2 + 2]);
			FPKDKHJKEEF ^= CNDMOBHIMJA.IKKGCFMJODC(ANGINAGELKI, HAODKGBJMLK[num2 + 1], FPEIGKHPEHG[num2 + 1]);
			ANGINAGELKI ^= CNDMOBHIMJA.HBFJAOFJIFP(INCIODEICNM, HAODKGBJMLK[num2], FPEIGKHPEHG[num2]);
		}
		DIDHNNMKJFE[0] = JEHECJGFJEB;
		DIDHNNMKJFE[1] = FPKDKHJKEEF;
		DIDHNNMKJFE[2] = ANGINAGELKI;
		DIDHNNMKJFE[3] = INCIODEICNM;
	}
}
