public class IMLEOOAPMMC : JEMNCGMEABF
{
	private readonly int IODPDKHNDIE;

	public int PMGBFMBJDJL
	{
		get
		{
			return IODPDKHNDIE;
		}
	}

	public IMLEOOAPMMC(byte[] IKNCPEPOKGJ)
		: this(IKNCPEPOKGJ, (IKNCPEPOKGJ.Length <= 128) ? (IKNCPEPOKGJ.Length * 8) : 1024)
	{
	}

	public IMLEOOAPMMC(byte[] IKNCPEPOKGJ, int EDKGBLMGFOO, int JJBNFEJMIPJ)
		: this(IKNCPEPOKGJ, EDKGBLMGFOO, JJBNFEJMIPJ, (JJBNFEJMIPJ <= 128) ? (JJBNFEJMIPJ * 8) : 1024)
	{
	}

	public IMLEOOAPMMC(byte[] IKNCPEPOKGJ, int IODPDKHNDIE)
		: base(IKNCPEPOKGJ)
	{
		this.IODPDKHNDIE = IODPDKHNDIE;
	}

	public IMLEOOAPMMC(byte[] IKNCPEPOKGJ, int EDKGBLMGFOO, int JJBNFEJMIPJ, int IODPDKHNDIE)
		: base(IKNCPEPOKGJ, EDKGBLMGFOO, JJBNFEJMIPJ)
	{
		this.IODPDKHNDIE = IODPDKHNDIE;
	}
}
