internal sealed class IMOBOFAOCFF
{
	private const int IAJKCABAHPK = 15;

	private const int HGNGLAIEPMD = 32;

	internal const int JFDALPFEPBP = 0;

	internal const int POIIGKLBFHO = 1;

	internal const int EOAPKAGKKGF = 2;

	internal const int NNCOMIBMLJL = 3;

	internal const int FNHBEHONKEN = 4;

	private const int DOPDGBKPGKN = 8;

	private const int KKHDFMOFKNE = 0;

	private const int BECBHHLALAH = 1;

	private const int IFCBECJBKOD = 2;

	private const int FGFKAJJPPMK = -1;

	private const int DLMDNANOOJF = -2;

	private const int FMAKHMNJPBM = -3;

	private const int BHLHAIENNIN = -4;

	private const int EFNAHKCFCME = -5;

	private const int IPPHHEKPNPC = -6;

	private const int KNFBKDMCKLI = 0;

	private const int FPAGNLCADLE = 1;

	private const int BGHOHPLPLFJ = 2;

	private const int NHMCDOGHEHM = 3;

	private const int EBOHDHBBGAE = 4;

	private const int MCABLHMBDFG = 5;

	private const int AKKPFNFCFNC = 6;

	private const int OBDHHDKNCKL = 7;

	private const int GIAINHLPHNN = 8;

	private const int ENHAMOCEAKF = 9;

	private const int ONIDKJLDGMD = 10;

	private const int OEFBBPEOMIN = 11;

	private const int EHPFOPCBJCK = 12;

	private const int PDEDELKPNFE = 13;

	internal int LJCPOAOKFOE;

	internal int ELKHFBGEJLK;

	internal long[] FKLFLCIPFAE = new long[1];

	internal long CDGFDLPJJFG;

	internal int LPKLPDABOHJ;

	internal int ENEMOKBHJHI;

	internal int BMMNEHGPPNN;

	internal JMDKLJDMAPK LLCEJHAKFAI;

	private static readonly byte[] OKKHCBOAAPB = new byte[4] { 0, 0, 255, 255 };

	internal int DLGIGHNILKK(NNHGBFFHNMG IGNEOOOFEMO)
	{
		if (IGNEOOOFEMO == null || IGNEOOOFEMO.KKJCMLLCLAL == null)
		{
			return -2;
		}
		IGNEOOOFEMO.IOKPEPLADED = (IGNEOOOFEMO.MDLEDIJMGHC = 0L);
		IGNEOOOFEMO.NOIOHIPHFHA = null;
		IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = ((IGNEOOOFEMO.KKJCMLLCLAL.ENEMOKBHJHI != 0) ? 7 : 0);
		IGNEOOOFEMO.KKJCMLLCLAL.LLCEJHAKFAI.PBKKHDHKMFG(IGNEOOOFEMO, null);
		return 0;
	}

	internal int BIMEKKEKKPB(NNHGBFFHNMG IGNEOOOFEMO)
	{
		if (LLCEJHAKFAI != null)
		{
			LLCEJHAKFAI.KNLOBIILDMP(IGNEOOOFEMO);
		}
		LLCEJHAKFAI = null;
		return 0;
	}

	internal int EHLPFDMFEKP(NNHGBFFHNMG IGNEOOOFEMO, int PHFLBLJJMLI)
	{
		IGNEOOOFEMO.NOIOHIPHFHA = null;
		LLCEJHAKFAI = null;
		ENEMOKBHJHI = 0;
		if (PHFLBLJJMLI < 0)
		{
			PHFLBLJJMLI = -PHFLBLJJMLI;
			ENEMOKBHJHI = 1;
		}
		if (PHFLBLJJMLI < 8 || PHFLBLJJMLI > 15)
		{
			BIMEKKEKKPB(IGNEOOOFEMO);
			return -2;
		}
		BMMNEHGPPNN = PHFLBLJJMLI;
		IGNEOOOFEMO.KKJCMLLCLAL.LLCEJHAKFAI = new JMDKLJDMAPK(IGNEOOOFEMO, (IGNEOOOFEMO.KKJCMLLCLAL.ENEMOKBHJHI == 0) ? this : null, 1 << PHFLBLJJMLI);
		DLGIGHNILKK(IGNEOOOFEMO);
		return 0;
	}

	internal int HHFIBDKMPBP(NNHGBFFHNMG IGNEOOOFEMO, int GNGLLMMGOJI)
	{
		if (IGNEOOOFEMO == null || IGNEOOOFEMO.KKJCMLLCLAL == null || IGNEOOOFEMO.BLJFIEBCEPL == null)
		{
			return -2;
		}
		GNGLLMMGOJI = ((GNGLLMMGOJI == 4) ? (-5) : 0);
		int num = -5;
		while (true)
		{
			switch (IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE)
			{
			case 0:
				if (IGNEOOOFEMO.HCNAGHNCFLL == 0)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.HCNAGHNCFLL--;
				IGNEOOOFEMO.IOKPEPLADED++;
				if (((IGNEOOOFEMO.KKJCMLLCLAL.ELKHFBGEJLK = IGNEOOOFEMO.BLJFIEBCEPL[IGNEOOOFEMO.HBCHEGLPAIJ++]) & 0xF) != 8)
				{
					IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 13;
					IGNEOOOFEMO.NOIOHIPHFHA = "unknown compression method";
					IGNEOOOFEMO.KKJCMLLCLAL.LPKLPDABOHJ = 5;
					break;
				}
				if ((IGNEOOOFEMO.KKJCMLLCLAL.ELKHFBGEJLK >> 4) + 8 > IGNEOOOFEMO.KKJCMLLCLAL.BMMNEHGPPNN)
				{
					IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 13;
					IGNEOOOFEMO.NOIOHIPHFHA = "invalid window size";
					IGNEOOOFEMO.KKJCMLLCLAL.LPKLPDABOHJ = 5;
					break;
				}
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 1;
				goto case 1;
			case 1:
			{
				if (IGNEOOOFEMO.HCNAGHNCFLL == 0)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.HCNAGHNCFLL--;
				IGNEOOOFEMO.IOKPEPLADED++;
				int num2 = IGNEOOOFEMO.BLJFIEBCEPL[IGNEOOOFEMO.HBCHEGLPAIJ++] & 0xFF;
				if (((IGNEOOOFEMO.KKJCMLLCLAL.ELKHFBGEJLK << 8) + num2) % 31 != 0)
				{
					IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 13;
					IGNEOOOFEMO.NOIOHIPHFHA = "incorrect header check";
					IGNEOOOFEMO.KKJCMLLCLAL.LPKLPDABOHJ = 5;
					break;
				}
				if ((num2 & 0x20) == 0)
				{
					IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 7;
					break;
				}
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 2;
				goto case 2;
			}
			case 2:
				if (IGNEOOOFEMO.HCNAGHNCFLL == 0)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.HCNAGHNCFLL--;
				IGNEOOOFEMO.IOKPEPLADED++;
				IGNEOOOFEMO.KKJCMLLCLAL.CDGFDLPJJFG = ((IGNEOOOFEMO.BLJFIEBCEPL[IGNEOOOFEMO.HBCHEGLPAIJ++] & 0xFF) << 24) & 0xFF000000u;
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 3;
				goto case 3;
			case 3:
				if (IGNEOOOFEMO.HCNAGHNCFLL == 0)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.HCNAGHNCFLL--;
				IGNEOOOFEMO.IOKPEPLADED++;
				IGNEOOOFEMO.KKJCMLLCLAL.CDGFDLPJJFG += (long)((ulong)((IGNEOOOFEMO.BLJFIEBCEPL[IGNEOOOFEMO.HBCHEGLPAIJ++] & 0xFF) << 16) & 0xFF0000uL);
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 4;
				goto case 4;
			case 4:
				if (IGNEOOOFEMO.HCNAGHNCFLL == 0)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.HCNAGHNCFLL--;
				IGNEOOOFEMO.IOKPEPLADED++;
				IGNEOOOFEMO.KKJCMLLCLAL.CDGFDLPJJFG += (long)((ulong)((IGNEOOOFEMO.BLJFIEBCEPL[IGNEOOOFEMO.HBCHEGLPAIJ++] & 0xFF) << 8) & 0xFF00uL);
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 5;
				goto case 5;
			case 5:
				if (IGNEOOOFEMO.HCNAGHNCFLL == 0)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.HCNAGHNCFLL--;
				IGNEOOOFEMO.IOKPEPLADED++;
				IGNEOOOFEMO.KKJCMLLCLAL.CDGFDLPJJFG += (long)((ulong)(int)IGNEOOOFEMO.BLJFIEBCEPL[IGNEOOOFEMO.HBCHEGLPAIJ++] & 0xFFuL);
				IGNEOOOFEMO.LEIJBCJFPGI = IGNEOOOFEMO.KKJCMLLCLAL.CDGFDLPJJFG;
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 6;
				return 2;
			case 6:
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 13;
				IGNEOOOFEMO.NOIOHIPHFHA = "need dictionary";
				IGNEOOOFEMO.KKJCMLLCLAL.LPKLPDABOHJ = 0;
				return -2;
			case 7:
				num = IGNEOOOFEMO.KKJCMLLCLAL.LLCEJHAKFAI.NEGIBIGJEKE(IGNEOOOFEMO, num);
				switch (num)
				{
				case -3:
					IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 13;
					IGNEOOOFEMO.KKJCMLLCLAL.LPKLPDABOHJ = 0;
					goto end_IL_0040;
				case 0:
					num = GNGLLMMGOJI;
					break;
				}
				if (num != 1)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.KKJCMLLCLAL.LLCEJHAKFAI.PBKKHDHKMFG(IGNEOOOFEMO, IGNEOOOFEMO.KKJCMLLCLAL.FKLFLCIPFAE);
				if (IGNEOOOFEMO.KKJCMLLCLAL.ENEMOKBHJHI != 0)
				{
					IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 12;
					break;
				}
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 8;
				goto case 8;
			case 8:
				if (IGNEOOOFEMO.HCNAGHNCFLL == 0)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.HCNAGHNCFLL--;
				IGNEOOOFEMO.IOKPEPLADED++;
				IGNEOOOFEMO.KKJCMLLCLAL.CDGFDLPJJFG = ((IGNEOOOFEMO.BLJFIEBCEPL[IGNEOOOFEMO.HBCHEGLPAIJ++] & 0xFF) << 24) & 0xFF000000u;
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 9;
				goto case 9;
			case 9:
				if (IGNEOOOFEMO.HCNAGHNCFLL == 0)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.HCNAGHNCFLL--;
				IGNEOOOFEMO.IOKPEPLADED++;
				IGNEOOOFEMO.KKJCMLLCLAL.CDGFDLPJJFG += (long)((ulong)((IGNEOOOFEMO.BLJFIEBCEPL[IGNEOOOFEMO.HBCHEGLPAIJ++] & 0xFF) << 16) & 0xFF0000uL);
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 10;
				goto case 10;
			case 10:
				if (IGNEOOOFEMO.HCNAGHNCFLL == 0)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.HCNAGHNCFLL--;
				IGNEOOOFEMO.IOKPEPLADED++;
				IGNEOOOFEMO.KKJCMLLCLAL.CDGFDLPJJFG += (long)((ulong)((IGNEOOOFEMO.BLJFIEBCEPL[IGNEOOOFEMO.HBCHEGLPAIJ++] & 0xFF) << 8) & 0xFF00uL);
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 11;
				goto case 11;
			case 11:
				if (IGNEOOOFEMO.HCNAGHNCFLL == 0)
				{
					return num;
				}
				num = GNGLLMMGOJI;
				IGNEOOOFEMO.HCNAGHNCFLL--;
				IGNEOOOFEMO.IOKPEPLADED++;
				IGNEOOOFEMO.KKJCMLLCLAL.CDGFDLPJJFG += (long)((ulong)(int)IGNEOOOFEMO.BLJFIEBCEPL[IGNEOOOFEMO.HBCHEGLPAIJ++] & 0xFFuL);
				if ((int)IGNEOOOFEMO.KKJCMLLCLAL.FKLFLCIPFAE[0] != (int)IGNEOOOFEMO.KKJCMLLCLAL.CDGFDLPJJFG)
				{
					IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 13;
					IGNEOOOFEMO.NOIOHIPHFHA = "incorrect data check";
					IGNEOOOFEMO.KKJCMLLCLAL.LPKLPDABOHJ = 5;
					break;
				}
				IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 12;
				goto case 12;
			case 12:
				return 1;
			case 13:
				return -3;
			default:
				{
					return -2;
				}
				end_IL_0040:
				break;
			}
		}
	}

	internal int MGBGHFHHPDL(NNHGBFFHNMG IGNEOOOFEMO, byte[] EAPGOBAJLJE, int NLJGHHOCFCC)
	{
		int eHGOOEHDNMM = 0;
		int num = NLJGHHOCFCC;
		if (IGNEOOOFEMO == null || IGNEOOOFEMO.KKJCMLLCLAL == null || IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE != 6)
		{
			return -2;
		}
		if (IGNEOOOFEMO.JHMLJILAIMK.IKGHHFMJBJG(1L, EAPGOBAJLJE, 0, NLJGHHOCFCC) != IGNEOOOFEMO.LEIJBCJFPGI)
		{
			return -3;
		}
		IGNEOOOFEMO.LEIJBCJFPGI = IGNEOOOFEMO.JHMLJILAIMK.IKGHHFMJBJG(0L, null, 0, 0);
		if (num >= 1 << IGNEOOOFEMO.KKJCMLLCLAL.BMMNEHGPPNN)
		{
			num = (1 << IGNEOOOFEMO.KKJCMLLCLAL.BMMNEHGPPNN) - 1;
			eHGOOEHDNMM = NLJGHHOCFCC - num;
		}
		IGNEOOOFEMO.KKJCMLLCLAL.LLCEJHAKFAI.OMGAEBKAGLJ(EAPGOBAJLJE, eHGOOEHDNMM, num);
		IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 7;
		return 0;
	}

	internal int BPGIOOLOBLJ(NNHGBFFHNMG IGNEOOOFEMO)
	{
		if (IGNEOOOFEMO == null || IGNEOOOFEMO.KKJCMLLCLAL == null)
		{
			return -2;
		}
		if (IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE != 13)
		{
			IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 13;
			IGNEOOOFEMO.KKJCMLLCLAL.LPKLPDABOHJ = 0;
		}
		int num;
		if ((num = IGNEOOOFEMO.HCNAGHNCFLL) == 0)
		{
			return -5;
		}
		int num2 = IGNEOOOFEMO.HBCHEGLPAIJ;
		int num3 = IGNEOOOFEMO.KKJCMLLCLAL.LPKLPDABOHJ;
		while (num != 0 && num3 < 4)
		{
			num3 = ((IGNEOOOFEMO.BLJFIEBCEPL[num2] != OKKHCBOAAPB[num3]) ? ((IGNEOOOFEMO.BLJFIEBCEPL[num2] == 0) ? (4 - num3) : 0) : (num3 + 1));
			num2++;
			num--;
		}
		IGNEOOOFEMO.IOKPEPLADED += num2 - IGNEOOOFEMO.HBCHEGLPAIJ;
		IGNEOOOFEMO.HBCHEGLPAIJ = num2;
		IGNEOOOFEMO.HCNAGHNCFLL = num;
		IGNEOOOFEMO.KKJCMLLCLAL.LPKLPDABOHJ = num3;
		if (num3 != 4)
		{
			return -3;
		}
		long iOKPEPLADED = IGNEOOOFEMO.IOKPEPLADED;
		long mDLEDIJMGHC = IGNEOOOFEMO.MDLEDIJMGHC;
		DLGIGHNILKK(IGNEOOOFEMO);
		IGNEOOOFEMO.IOKPEPLADED = iOKPEPLADED;
		IGNEOOOFEMO.MDLEDIJMGHC = mDLEDIJMGHC;
		IGNEOOOFEMO.KKJCMLLCLAL.LJCPOAOKFOE = 7;
		return 0;
	}

	internal int NEIMDPMHJLB(NNHGBFFHNMG IGNEOOOFEMO)
	{
		if (IGNEOOOFEMO == null || IGNEOOOFEMO.KKJCMLLCLAL == null || IGNEOOOFEMO.KKJCMLLCLAL.LLCEJHAKFAI == null)
		{
			return -2;
		}
		return IGNEOOOFEMO.KKJCMLLCLAL.LLCEJHAKFAI.EPMJFDEIOIK();
	}
}
