using System.IO;

public class INPJGCJAKBA : KIGEMNPNCBN
{
	public INPJGCJAKBA(Stream OMCALCLJPOD)
		: base(OMCALCLJPOD)
	{
		HICECABJALK(48);
	}

	public INPJGCJAKBA(Stream OMCALCLJPOD, int LGPKPEMILHA, bool DNBCBHLACCP)
		: base(OMCALCLJPOD, LGPKPEMILHA, DNBCBHLACCP)
	{
		HICECABJALK(48);
	}
}
