internal abstract class JACKOMDKHEF
{
	public static void BMEIFJDODCF(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] JMNJPLAGDDJ)
	{
		PHEKPHCPKLA.BMEIFJDODCF(AMFCENFNAJJ, CNLILOEEBOJ, JMNJPLAGDDJ);
		PHEKPHCPKLA.BMEIFJDODCF(AMFCENFNAJJ, 6, CNLILOEEBOJ, 6, JMNJPLAGDDJ, 12);
		uint num = PHEKPHCPKLA.HFHBOBLBLDH(JMNJPLAGDDJ, 6, JMNJPLAGDDJ, 12);
		uint eFEEMAAFCMH = num + PHEKPHCPKLA.MAALDEFJPJA(JMNJPLAGDDJ, 0, JMNJPLAGDDJ, 6, 0u);
		num += PHEKPHCPKLA.MAALDEFJPJA(JMNJPLAGDDJ, 18, JMNJPLAGDDJ, 12, eFEEMAAFCMH);
		uint[] array = PHEKPHCPKLA.PLIFFMMBNPM();
		uint[] array2 = PHEKPHCPKLA.PLIFFMMBNPM();
		bool flag = PHEKPHCPKLA.COOLFBDPHEO(AMFCENFNAJJ, 6, AMFCENFNAJJ, 0, array, 0) != PHEKPHCPKLA.COOLFBDPHEO(CNLILOEEBOJ, 6, CNLILOEEBOJ, 0, array2, 0);
		uint[] array3 = PHEKPHCPKLA.DCPJKFEDHOJ();
		PHEKPHCPKLA.BMEIFJDODCF(array, array2, array3);
		num += (uint)((!flag) ? BCMDHIIJKJE.DKAMAFLMHEJ(12, array3, 0, JMNJPLAGDDJ, 6) : ((int)BCMDHIIJKJE.MAALDEFJPJA(12, array3, 0, JMNJPLAGDDJ, 6)));
		BCMDHIIJKJE.HNPBCAPBDGJ(24, num, JMNJPLAGDDJ, 18);
	}

	public static void MIOEHGDPGAG(uint[] AMFCENFNAJJ, uint[] JMNJPLAGDDJ)
	{
		PHEKPHCPKLA.MIOEHGDPGAG(AMFCENFNAJJ, JMNJPLAGDDJ);
		PHEKPHCPKLA.MIOEHGDPGAG(AMFCENFNAJJ, 6, JMNJPLAGDDJ, 12);
		uint num = PHEKPHCPKLA.HFHBOBLBLDH(JMNJPLAGDDJ, 6, JMNJPLAGDDJ, 12);
		uint eFEEMAAFCMH = num + PHEKPHCPKLA.MAALDEFJPJA(JMNJPLAGDDJ, 0, JMNJPLAGDDJ, 6, 0u);
		num += PHEKPHCPKLA.MAALDEFJPJA(JMNJPLAGDDJ, 18, JMNJPLAGDDJ, 12, eFEEMAAFCMH);
		uint[] array = PHEKPHCPKLA.PLIFFMMBNPM();
		PHEKPHCPKLA.COOLFBDPHEO(AMFCENFNAJJ, 6, AMFCENFNAJJ, 0, array, 0);
		uint[] array2 = PHEKPHCPKLA.DCPJKFEDHOJ();
		PHEKPHCPKLA.MIOEHGDPGAG(array, array2);
		num += (uint)BCMDHIIJKJE.DKAMAFLMHEJ(12, array2, 0, JMNJPLAGDDJ, 6);
		BCMDHIIJKJE.HNPBCAPBDGJ(24, num, JMNJPLAGDDJ, 18);
	}
}
