internal class JDDHOECMHII
{
	public readonly string PNGPLGHKFDI;

	public readonly bool MELBODIIPKN;

	public readonly KJKAIEHNGAL.NAHKLDLMHFA DHOFLMAIDKL;

	public JDDHOECMHII(string IOCMOCCFALN, bool IKGIEEMCFDK, KJKAIEHNGAL.NAHKLDLMHFA HHLHIPKJHCJ)
	{
		PNGPLGHKFDI = IOCMOCCFALN;
		MELBODIIPKN = IKGIEEMCFDK;
		DHOFLMAIDKL = HHLHIPKJHCJ;
	}
}
