public class JDKCFKJJIHN : HPBPDALECOG
{
	private readonly MJDENGGDLMJ AFCJCHEOGJK;

	private readonly KLKJHFKJLEM DHNJFHPNJLM;

	public MJDENGGDLMJ DAFBLKBCACB
	{
		get
		{
			return AFCJCHEOGJK;
		}
	}

	public KLKJHFKJLEM LMJPMDMLPNH
	{
		get
		{
			return DHNJFHPNJLM;
		}
	}

	public JDKCFKJJIHN(MJDENGGDLMJ ONBCKCLKGIE, FBIJJFGLKMK GECCLOFELEC)
		: base(GECCLOFELEC, ONBCKCLKGIE.HNLMGJGNBDD.BitLength)
	{
		AFCJCHEOGJK = ONBCKCLKGIE;
	}

	public JDKCFKJJIHN(KLKJHFKJLEM DHNJFHPNJLM, FBIJJFGLKMK GECCLOFELEC)
		: this(BKFMFPGHIJB.BMENKBLGJJK(DHNJFHPNJLM), GECCLOFELEC)
	{
		this.DHNJFHPNJLM = DHNJFHPNJLM;
	}
}
