using System;

internal class JDNANIIIFGM : KKMFHDBDNLF, BJLAMONNNDD
{
	protected CGDEGBGOKJO COOBIGONLDK;

	protected BJLAMONNNDD NELDCOGAKNE;

	protected BJLAMONNNDD FOIMGGHOJGF;

	public virtual string KFKMEPMEBND
	{
		get
		{
			return NELDCOGAKNE.KFKMEPMEBND + " and " + FOIMGGHOJGF.KFKMEPMEBND;
		}
	}

	internal JDNANIIIFGM()
	{
		NELDCOGAKNE = KINEBFNENMB.KNADNPDKLGD(1);
		FOIMGGHOJGF = KINEBFNENMB.KNADNPDKLGD(2);
	}

	internal JDNANIIIFGM(JDNANIIIFGM LLIEHCKNJEM)
	{
		COOBIGONLDK = LLIEHCKNJEM.COOBIGONLDK;
		NELDCOGAKNE = KINEBFNENMB.JIDIDNFBFKJ(1, LLIEHCKNJEM.NELDCOGAKNE);
		FOIMGGHOJGF = KINEBFNENMB.JIDIDNFBFKJ(2, LLIEHCKNJEM.FOIMGGHOJGF);
	}

	public virtual void DIOELAHNLKJ(CGDEGBGOKJO MBEMNOCDDBC)
	{
		COOBIGONLDK = MBEMNOCDDBC;
	}

	public virtual KKMFHDBDNLF NFEDILFGOFB()
	{
		return this;
	}

	public virtual void PDDLLDKPKOC(byte JMCLOFPGGNN)
	{
		throw new InvalidOperationException("CombinedHash only supports calculating the legacy PRF for handshake hash");
	}

	public virtual void OLDLMNLPAMN()
	{
	}

	public virtual KKMFHDBDNLF ANPICCCJCIH()
	{
		return new JDNANIIIFGM(this);
	}

	public virtual BJLAMONNNDD IFHHBFPJJHN()
	{
		return new JDNANIIIFGM(this);
	}

	public virtual byte[] LGOMGMANPHC(byte JMCLOFPGGNN)
	{
		throw new InvalidOperationException("CombinedHash doesn't support multiple hashes");
	}

	public virtual int MNAIJEEKPCP()
	{
		return Math.Max(NELDCOGAKNE.MNAIJEEKPCP(), FOIMGGHOJGF.MNAIJEEKPCP());
	}

	public virtual int EEMLLAMENHO()
	{
		return NELDCOGAKNE.EEMLLAMENHO() + FOIMGGHOJGF.EEMLLAMENHO();
	}

	public virtual void BPAJGOINFNL(byte MOPCLEEGDFB)
	{
		NELDCOGAKNE.BPAJGOINFNL(MOPCLEEGDFB);
		FOIMGGHOJGF.BPAJGOINFNL(MOPCLEEGDFB);
	}

	public virtual void GONEEEFEDGF(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int NBEDPKHALCN)
	{
		NELDCOGAKNE.GONEEEFEDGF(MOPCLEEGDFB, ELICNEDIBGB, NBEDPKHALCN);
		FOIMGGHOJGF.GONEEEFEDGF(MOPCLEEGDFB, ELICNEDIBGB, NBEDPKHALCN);
	}

	public virtual int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		if (COOBIGONLDK != null && KINEBFNENMB.NFEADLBGDGE(COOBIGONLDK))
		{
			BFBJIMLHNCE(NELDCOGAKNE, EBIOFEGJMGL.HDBEHGHJLCE, EBIOFEGJMGL.NBKPLNHFBOH, 48);
			BFBJIMLHNCE(FOIMGGHOJGF, EBIOFEGJMGL.HDBEHGHJLCE, EBIOFEGJMGL.NBKPLNHFBOH, 40);
		}
		int num = NELDCOGAKNE.LCNOFBMOHHM(BILGCJNPJGJ, EMAKNGBIFDC);
		int num2 = FOIMGGHOJGF.LCNOFBMOHHM(BILGCJNPJGJ, EMAKNGBIFDC + num);
		return num + num2;
	}

	public virtual void OMOKOKFNBKI()
	{
		NELDCOGAKNE.OMOKOKFNBKI();
		FOIMGGHOJGF.OMOKOKFNBKI();
	}

	protected virtual void BFBJIMLHNCE(BJLAMONNNDD ELNCCDELMMH, byte[] KNDAPHHFBFC, byte[] DOPPMMBJFHK, int HLGAKLOKMFG)
	{
		byte[] iENFDPCIFNJ = COOBIGONLDK.HFMNBFOAPOP.IENFDPCIFNJ;
		ELNCCDELMMH.GONEEEFEDGF(iENFDPCIFNJ, 0, iENFDPCIFNJ.Length);
		ELNCCDELMMH.GONEEEFEDGF(KNDAPHHFBFC, 0, HLGAKLOKMFG);
		byte[] array = KDDIIEMIPKF.LCNOFBMOHHM(ELNCCDELMMH);
		ELNCCDELMMH.GONEEEFEDGF(iENFDPCIFNJ, 0, iENFDPCIFNJ.Length);
		ELNCCDELMMH.GONEEEFEDGF(DOPPMMBJFHK, 0, HLGAKLOKMFG);
		ELNCCDELMMH.GONEEEFEDGF(array, 0, array.Length);
	}
}
