using Org.BouncyCastle.Math;

public class JFOKJMPGMEJ : LNKPCJLANAO
{
	private KBINBLGGLNE GNGLLMMGOJI;

	public KBINBLGGLNE JBGOANMLBFA
	{
		get
		{
			return GNGLLMMGOJI;
		}
	}

	public JFOKJMPGMEJ(KBINBLGGLNE GNGLLMMGOJI)
	{
		this.GNGLLMMGOJI = GNGLLMMGOJI;
	}

	public JFOKJMPGMEJ(BigInteger HPHBDNBJPHB, PJGIGKJFGFI IBBBMACIBGK)
		: this(new NJEIAFKPJFE(HPHBDNBJPHB, new BigInteger(1, IBBBMACIBGK.KLHNEKMCKKI())))
	{
	}

	public JFOKJMPGMEJ(int CEKMAJAHNAG, int KDFFDKFCDKK, int FKOBMEPIABG, int KHNDCPCHOEM, PJGIGKJFGFI IBBBMACIBGK)
		: this(new HMFDKDDBGPO(CEKMAJAHNAG, KDFFDKFCDKK, FKOBMEPIABG, KHNDCPCHOEM, new BigInteger(1, IBBBMACIBGK.KLHNEKMCKKI())))
	{
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		int lHLOCJDFJHB = AEHODCJKLBP.MNAIJEEKPCP(GNGLLMMGOJI);
		byte[] gFPBBLPMOOL = AEHODCJKLBP.OIDMLPILCDK(GNGLLMMGOJI.DOJBPIFPALJ(), lHLOCJDFJHB);
		return new CFMJBFILJCB(gFPBBLPMOOL);
	}
}
