using System;
using System.IO;
using Org.BouncyCastle.Math;
using Org.BouncyCastle.Security;

public sealed class JHGHHFDFJEG
{
	private JHGHHFDFJEG()
	{
	}

	public static COEMJAGOFJJ HCBKCKKDGCP(byte[] NLBMCCFLLBE)
	{
		return HCBKCKKDGCP(MHBCFNELGOJ.BJLJCGFMFOO(EDOEBJJFOBM.HPDCKMOPEMM(NLBMCCFLLBE)));
	}

	public static COEMJAGOFJJ HCBKCKKDGCP(Stream FILBOAMBNOP)
	{
		return HCBKCKKDGCP(MHBCFNELGOJ.BJLJCGFMFOO(EDOEBJJFOBM.IHHDEKPLKHC(FILBOAMBNOP)));
	}

	public static COEMJAGOFJJ HCBKCKKDGCP(MHBCFNELGOJ MJHHKCCPFEE)
	{
		COCECKPDIKC cOCECKPDIKC = MJHHKCCPFEE.ABHPJEPGJGI;
		KLKJHFKJLEM kLKJHFKJLEM = cOCECKPDIKC.GOFDFGBGLFC;
		if (kLKJHFKJLEM.Equals(NLPPJKFFBON.FFGIEGPCJEG) || kLKJHFKJLEM.Equals(FBFBJFFFNOF.KKCPGKBGKPJ) || kLKJHFKJLEM.Equals(NLPPJKFFBON.NLKEIILLMGF) || kLKJHFKJLEM.Equals(NLPPJKFFBON.APKGEGJDFEH))
		{
			FFFLPDDFAAK fFFLPDDFAAK = FFFLPDDFAAK.BJLJCGFMFOO(MJHHKCCPFEE.DGEOLGIDGFE());
			return new PLGGNEJEIIP(false, fFFLPDDFAAK.FILOMPHGFKD, fFFLPDDFAAK.IHOPDFAGDAF);
		}
		if (kLKJHFKJLEM.Equals(JJFMEBLGJEP.KFMEGEAGKOD))
		{
			ALLINHNNNJN aLLINHNNNJN = ALLINHNNNJN.BJLJCGFMFOO(cOCECKPDIKC.KPJHHAAOFOH.IIHKEACDNID());
			JGAMOCIKLMF jGAMOCIKLMF = JGAMOCIKLMF.BJLJCGFMFOO(MJHHKCCPFEE.DGEOLGIDGFE());
			BigInteger cNLILOEEBOJ = jGAMOCIKLMF.MOAGLBJDKKL.JBGOANMLBFA;
			if (GIOCOFCHDBC(aLLINHNNNJN))
			{
				return ENMJMKBCGND(kLKJHFKJLEM, cNLILOEEBOJ, aLLINHNNNJN);
			}
			CKPCOMAFPHE cKPCOMAFPHE = CKPCOMAFPHE.BJLJCGFMFOO(aLLINHNNNJN);
			BigInteger hPHBDNBJPHB = cKPCOMAFPHE.MBIJHANOCOC.JBGOANMLBFA;
			BigInteger hJMBDGKAOBP = cKPCOMAFPHE.HBGOKILMBJG.JBGOANMLBFA;
			BigInteger oKDPJHOEPBJ = cKPCOMAFPHE.FNPELDEHJKL.JBGOANMLBFA;
			BigInteger jEMICOMMKMO = null;
			if (cKPCOMAFPHE.GHGFJBIOAAC != null)
			{
				jEMICOMMKMO = cKPCOMAFPHE.GHGFJBIOAAC.JBGOANMLBFA;
			}
			IPCHHFKBJGE cANIMMGDFPJ = null;
			NBCMAOFMJKO nBCMAOFMJKO = cKPCOMAFPHE.KAONDBJECOJ;
			if (nBCMAOFMJKO != null)
			{
				byte[] hJBOEOOLOOE = nBCMAOFMJKO.DKHFDIBCCME.MIBPLNJNEGA();
				BigInteger bigInteger = nBCMAOFMJKO.ODDAKJPBFDO.JBGOANMLBFA;
				cANIMMGDFPJ = new IPCHHFKBJGE(hJBOEOOLOOE, bigInteger.IntValue);
			}
			return new GBBNCENGABI(cNLILOEEBOJ, new CLBPDHGBHML(hPHBDNBJPHB, hJMBDGKAOBP, oKDPJHOEPBJ, jEMICOMMKMO, cANIMMGDFPJ));
		}
		if (kLKJHFKJLEM.Equals(NLPPJKFFBON.JDDKJFLACKJ))
		{
			ALLINHNNNJN mIABODPHOIP = ALLINHNNNJN.BJLJCGFMFOO(cOCECKPDIKC.KPJHHAAOFOH.IIHKEACDNID());
			GLFDIPNOLKN gLFDIPNOLKN = (GLFDIPNOLKN)MJHHKCCPFEE.DGEOLGIDGFE();
			return ENMJMKBCGND(kLKJHFKJLEM, gLFDIPNOLKN.JBGOANMLBFA, mIABODPHOIP);
		}
		if (kLKJHFKJLEM.Equals(POLLKACILDK.FOOFKGEODKF))
		{
			IGDDPPIGNKH iGDDPPIGNKH = new IGDDPPIGNKH(ALLINHNNNJN.BJLJCGFMFOO(cOCECKPDIKC.KPJHHAAOFOH.IIHKEACDNID()));
			GLFDIPNOLKN gLFDIPNOLKN2 = (GLFDIPNOLKN)MJHHKCCPFEE.DGEOLGIDGFE();
			return new IOEANHAEOBK(gLFDIPNOLKN2.JBGOANMLBFA, new CFBBJKGJFPE(iGDDPPIGNKH.MBIJHANOCOC, iGDDPPIGNKH.HBGOKILMBJG));
		}
		if (kLKJHFKJLEM.Equals(JJFMEBLGJEP.IENGAOPONAC) || kLKJHFKJLEM.Equals(POLLKACILDK.KJIPDFIDFKF))
		{
			GLFDIPNOLKN gLFDIPNOLKN3 = (GLFDIPNOLKN)MJHHKCCPFEE.DGEOLGIDGFE();
			LNKPCJLANAO lNKPCJLANAO = cOCECKPDIKC.KPJHHAAOFOH;
			JEHNKJOKBGF iJJHBEECMBP = null;
			if (lNKPCJLANAO != null)
			{
				DEBNMAAEBAP dEBNMAAEBAP = DEBNMAAEBAP.BJLJCGFMFOO(lNKPCJLANAO.IIHKEACDNID());
				iJJHBEECMBP = new JEHNKJOKBGF(dEBNMAAEBAP.MBIJHANOCOC, dEBNMAAEBAP.FNPELDEHJKL, dEBNMAAEBAP.HBGOKILMBJG);
			}
			return new NFJLHCNCCHB(gLFDIPNOLKN3.JBGOANMLBFA, iJJHBEECMBP);
		}
		if (kLKJHFKJLEM.Equals(JJFMEBLGJEP.KGEJMACHDJI))
		{
			IOPAEMIMKAA iOPAEMIMKAA = new IOPAEMIMKAA(cOCECKPDIKC.KPJHHAAOFOH.IIHKEACDNID());
			JMLDNPGFBDA jMLDNPGFBDA = ((!iOPAEMIMKAA.EKBDDOPLOLM) ? new JMLDNPGFBDA((ALLINHNNNJN)iOPAEMIMKAA.KPJHHAAOFOH) : JMLCKFLAGEF.GJFLBAIJAEM((KLKJHFKJLEM)iOPAEMIMKAA.KPJHHAAOFOH));
			PJGIGKJFGFI iBBBMACIBGK = new CFMJBFILJCB(MJHHKCCPFEE.FEJGHPNBLMJ.MIBPLNJNEGA());
			EPOKPEIHHJG ePOKPEIHHJG = new EPOKPEIHHJG(jMLDNPGFBDA.ECFGFKNLLGH, iBBBMACIBGK);
			JGAFKLGGBGF oKDPJHOEPBJ2 = ePOKPEIHHJG.NCJHDEHECDN;
			if (iOPAEMIMKAA.EKBDDOPLOLM)
			{
				return new EGEBOHHBFLK("EC", oKDPJHOEPBJ2, (KLKJHFKJLEM)iOPAEMIMKAA.KPJHHAAOFOH);
			}
			MJDENGGDLMJ iJJHBEECMBP2 = new MJDENGGDLMJ(jMLDNPGFBDA.ECFGFKNLLGH, jMLDNPGFBDA.HBGOKILMBJG, jMLDNPGFBDA.HNLMGJGNBDD, jMLDNPGFBDA.JGOHMOHEFMJ, jMLDNPGFBDA.GKBBKKNGJAK());
			return new EGEBOHHBFLK(oKDPJHOEPBJ2, iJJHBEECMBP2);
		}
		if (kLKJHFKJLEM.Equals(FNOHIHFMAMN.CCJKBECINHA))
		{
			EJJALOKPAKK eJJALOKPAKK = new EJJALOKPAKK((ALLINHNNNJN)cOCECKPDIKC.KPJHHAAOFOH);
			PJGIGKJFGFI pJGIGKJFGFI;
			try
			{
				pJGIGKJFGFI = (PJGIGKJFGFI)MJHHKCCPFEE.DGEOLGIDGFE();
			}
			catch (IOException)
			{
				throw new ArgumentException("invalid info structure in GOST3410 public key");
			}
			byte[] array = pJGIGKJFGFI.KLHNEKMCKKI();
			byte[] array2 = new byte[32];
			byte[] array3 = new byte[32];
			for (int i = 0; i != array3.Length; i++)
			{
				array2[i] = array[31 - i];
			}
			for (int j = 0; j != array2.Length; j++)
			{
				array3[j] = array[63 - j];
			}
			MJDENGGDLMJ mJDENGGDLMJ = PBFONLGGGIN.BHLONOMMIGE(eJJALOKPAKK.LMJPMDMLPNH);
			if (mJDENGGDLMJ == null)
			{
				return null;
			}
			JGAFKLGGBGF oKDPJHOEPBJ3 = mJDENGGDLMJ.ECFGFKNLLGH.IIDKCEOFIBH(new BigInteger(1, array2), new BigInteger(1, array3));
			return new EGEBOHHBFLK("ECGOST3410", oKDPJHOEPBJ3, eJJALOKPAKK.LMJPMDMLPNH);
		}
		if (kLKJHFKJLEM.Equals(FNOHIHFMAMN.HEKHMFFMGJL))
		{
			EJJALOKPAKK eJJALOKPAKK2 = new EJJALOKPAKK((ALLINHNNNJN)cOCECKPDIKC.KPJHHAAOFOH);
			CFMJBFILJCB cFMJBFILJCB;
			try
			{
				cFMJBFILJCB = (CFMJBFILJCB)MJHHKCCPFEE.DGEOLGIDGFE();
			}
			catch (IOException)
			{
				throw new ArgumentException("invalid info structure in GOST3410 public key");
			}
			byte[] array4 = cFMJBFILJCB.KLHNEKMCKKI();
			byte[] array5 = new byte[array4.Length];
			for (int k = 0; k != array4.Length; k++)
			{
				array5[k] = array4[array4.Length - 1 - k];
			}
			BigInteger cNLILOEEBOJ2 = new BigInteger(1, array5);
			return new EBIECGDGAPI(cNLILOEEBOJ2, eJJALOKPAKK2.LMJPMDMLPNH);
		}
		throw new SecurityUtilityException("algorithm identifier in key not recognised: " + kLKJHFKJLEM);
	}

	private static bool GIOCOFCHDBC(ALLINHNNNJN MIABODPHOIP)
	{
		if (MIABODPHOIP.GMCGMPEEHJP == 2)
		{
			return true;
		}
		if (MIABODPHOIP.GMCGMPEEHJP > 3)
		{
			return false;
		}
		GLFDIPNOLKN gLFDIPNOLKN = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(2));
		GLFDIPNOLKN gLFDIPNOLKN2 = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(0));
		return gLFDIPNOLKN.JBGOANMLBFA.JLPDKNFCNPO(BigInteger.AGLOJCOAJIK(gLFDIPNOLKN2.JBGOANMLBFA.BitLength)) <= 0;
	}

	private static GBBNCENGABI ENMJMKBCGND(KLKJHFKJLEM IDNMNLLLOEI, BigInteger CNLILOEEBOJ, ALLINHNNNJN MIABODPHOIP)
	{
		NBABLEEBDJL nBABLEEBDJL = new NBABLEEBDJL(MIABODPHOIP);
		BigInteger bigInteger = nBABLEEBDJL.NBFDOJDLKOG;
		int pHILIHLPDFD = ((bigInteger != null) ? bigInteger.IntValue : 0);
		CLBPDHGBHML iJJHBEECMBP = new CLBPDHGBHML(nBABLEEBDJL.MBIJHANOCOC, nBABLEEBDJL.HBGOKILMBJG, null, pHILIHLPDFD);
		return new GBBNCENGABI(CNLILOEEBOJ, iJJHBEECMBP, IDNMNLLLOEI);
	}
}
