public class JIHIOOKBBLB : PAANMJLACEF
{
	public JIHIOOKBBLB(int LGPKPEMILHA, LNKPCJLANAO NEMEKIOEOLC)
		: base(LGPKPEMILHA, NEMEKIOEOLC)
	{
	}

	public JIHIOOKBBLB(bool DHGLJHFEJFL, int LGPKPEMILHA, LNKPCJLANAO NEMEKIOEOLC)
		: base(DHGLJHFEJFL, LGPKPEMILHA, NEMEKIOEOLC)
	{
	}

	public JIHIOOKBBLB(int LGPKPEMILHA)
		: base(false, LGPKPEMILHA, KOGPLMALOEH.JIKOOGGLMBO)
	{
	}

	internal override void LMDBBPLCJDM(JBLJHINPLMC NMHOOGAGLOA)
	{
		if (!DHIKCKFGKID())
		{
			byte[] array = NEMEKIOEOLC.KMBJLPOKIAC();
			if (DHGLJHFEJFL)
			{
				NMHOOGAGLOA.AGNEJPEMPAP(160, LGPKPEMILHA, array);
				return;
			}
			int kCHENLJCHHH = (array[0] & 0x20) | 0x80;
			NMHOOGAGLOA.DCFAKMDJNLN(kCHENLJCHHH, LGPKPEMILHA);
			NMHOOGAGLOA.Write(array, 1, array.Length - 1);
		}
		else
		{
			NMHOOGAGLOA.AGNEJPEMPAP(160, LGPKPEMILHA, new byte[0]);
		}
	}
}
