using System;

public abstract class JJFMEBLGJEP
{
	internal const string KNOJJONLNHH = "1.2.840.10045";

	public static readonly KLKJHFKJLEM KCFCJIJMKBI = new KLKJHFKJLEM("1.2.840.10045");

	public static readonly KLKJHFKJLEM DJBHCGCBMJP = KCFCJIJMKBI.BCDAGLPENOK("1");

	public static readonly KLKJHFKJLEM FCKODOMMAFF = DJBHCGCBMJP.BCDAGLPENOK("1");

	public static readonly KLKJHFKJLEM IOCHGCOMCGG = DJBHCGCBMJP.BCDAGLPENOK("2");

	public static readonly KLKJHFKJLEM LMGODHLHGBH = IOCHGCOMCGG.BCDAGLPENOK("3.1");

	public static readonly KLKJHFKJLEM OILAJONOOJC = IOCHGCOMCGG.BCDAGLPENOK("3.2");

	public static readonly KLKJHFKJLEM EDBKIIPIICC = IOCHGCOMCGG.BCDAGLPENOK("3.3");

	[Obsolete("Use 'id_ecSigType' instead")]
	public const string GPNGLBPBGGJ = "1.2.840.10045.4";

	public static readonly KLKJHFKJLEM IGDHLINCFJN = KCFCJIJMKBI.BCDAGLPENOK("4");

	public static readonly KLKJHFKJLEM MKGMLCOCCPL = IGDHLINCFJN.BCDAGLPENOK("1");

	[Obsolete("Use 'id_publicKeyType' instead")]
	public const string APFMLHLMBEE = "1.2.840.10045.2";

	public static readonly KLKJHFKJLEM OAAAGOPLJNO = KCFCJIJMKBI.BCDAGLPENOK("2");

	public static readonly KLKJHFKJLEM KGEJMACHDJI = OAAAGOPLJNO.BCDAGLPENOK("1");

	public static readonly KLKJHFKJLEM GOEPMLIFLFH = IGDHLINCFJN.BCDAGLPENOK("3");

	public static readonly KLKJHFKJLEM KICHODOIAMD = GOEPMLIFLFH.BCDAGLPENOK("1");

	public static readonly KLKJHFKJLEM EGLFGAJEAPJ = GOEPMLIFLFH.BCDAGLPENOK("2");

	public static readonly KLKJHFKJLEM AACDLNGKGGH = GOEPMLIFLFH.BCDAGLPENOK("3");

	public static readonly KLKJHFKJLEM CGLPLAKDEOP = GOEPMLIFLFH.BCDAGLPENOK("4");

	public static readonly KLKJHFKJLEM FAPNOCPOAGH = KCFCJIJMKBI.BCDAGLPENOK("3");

	public static readonly KLKJHFKJLEM OGACCHIOOFF = FAPNOCPOAGH.BCDAGLPENOK("0");

	public static readonly KLKJHFKJLEM MOEIODANJCL = OGACCHIOOFF.BCDAGLPENOK("1");

	public static readonly KLKJHFKJLEM HHPBONEKKBO = OGACCHIOOFF.BCDAGLPENOK("2");

	public static readonly KLKJHFKJLEM GIGCBMJEHCP = OGACCHIOOFF.BCDAGLPENOK("3");

	public static readonly KLKJHFKJLEM OEAMEOGNDAN = OGACCHIOOFF.BCDAGLPENOK("4");

	public static readonly KLKJHFKJLEM IIKPCPAMDOF = OGACCHIOOFF.BCDAGLPENOK("5");

	public static readonly KLKJHFKJLEM BABPLBEEOGG = OGACCHIOOFF.BCDAGLPENOK("6");

	public static readonly KLKJHFKJLEM PLBNDLIPDPN = OGACCHIOOFF.BCDAGLPENOK("7");

	public static readonly KLKJHFKJLEM MKKEBGJNIDJ = OGACCHIOOFF.BCDAGLPENOK("8");

	public static readonly KLKJHFKJLEM IGACIEEGGFD = OGACCHIOOFF.BCDAGLPENOK("9");

	public static readonly KLKJHFKJLEM ALNDHGOOHIO = OGACCHIOOFF.BCDAGLPENOK("10");

	public static readonly KLKJHFKJLEM NCCGOMDDCKC = OGACCHIOOFF.BCDAGLPENOK("11");

	public static readonly KLKJHFKJLEM JPNPGAGDLKE = OGACCHIOOFF.BCDAGLPENOK("12");

	public static readonly KLKJHFKJLEM OJAAAEAKIKM = OGACCHIOOFF.BCDAGLPENOK("13");

	public static readonly KLKJHFKJLEM BFILONNEFND = OGACCHIOOFF.BCDAGLPENOK("14");

	public static readonly KLKJHFKJLEM CPAIOHPOOCE = OGACCHIOOFF.BCDAGLPENOK("15");

	public static readonly KLKJHFKJLEM PDNDFCBJNBO = OGACCHIOOFF.BCDAGLPENOK("16");

	public static readonly KLKJHFKJLEM AAGAEFPEKMM = OGACCHIOOFF.BCDAGLPENOK("17");

	public static readonly KLKJHFKJLEM HPHFFLMAMOF = OGACCHIOOFF.BCDAGLPENOK("18");

	public static readonly KLKJHFKJLEM LAHLNONKLCC = OGACCHIOOFF.BCDAGLPENOK("19");

	public static readonly KLKJHFKJLEM HKPLIGAFOKM = OGACCHIOOFF.BCDAGLPENOK("20");

	public static readonly KLKJHFKJLEM FMKFLIKEOCI = FAPNOCPOAGH.BCDAGLPENOK("1");

	public static readonly KLKJHFKJLEM OOMKCFHKIAE = FMKFLIKEOCI.BCDAGLPENOK("1");

	public static readonly KLKJHFKJLEM JLFEMGBCDAC = FMKFLIKEOCI.BCDAGLPENOK("2");

	public static readonly KLKJHFKJLEM HBNFFANOCJI = FMKFLIKEOCI.BCDAGLPENOK("3");

	public static readonly KLKJHFKJLEM MCFHNBEONGF = FMKFLIKEOCI.BCDAGLPENOK("4");

	public static readonly KLKJHFKJLEM JDMBHHNNILB = FMKFLIKEOCI.BCDAGLPENOK("5");

	public static readonly KLKJHFKJLEM FPNOEJLMKIB = FMKFLIKEOCI.BCDAGLPENOK("6");

	public static readonly KLKJHFKJLEM IGNEAKENMLM = FMKFLIKEOCI.BCDAGLPENOK("7");

	public static readonly KLKJHFKJLEM IENGAOPONAC = new KLKJHFKJLEM("1.2.840.10040.4.1");

	public static readonly KLKJHFKJLEM CGJLNBCIAHE = new KLKJHFKJLEM("1.2.840.10040.4.3");

	public static readonly KLKJHFKJLEM BPINNNIODPD = new KLKJHFKJLEM("1.3.133.16.840.63.0");

	public static readonly KLKJHFKJLEM DFPEIJCHIEH = BPINNNIODPD.BCDAGLPENOK("2");

	public static readonly KLKJHFKJLEM DNFPIHDCJLA = BPINNNIODPD.BCDAGLPENOK("3");

	public static readonly KLKJHFKJLEM GLCLDBAHIEK = BPINNNIODPD.BCDAGLPENOK("16");

	public static readonly KLKJHFKJLEM ECAEPKAOODF = new KLKJHFKJLEM("1.2.840.10046");

	public static readonly KLKJHFKJLEM KFMEGEAGKOD = ECAEPKAOODF.BCDAGLPENOK("2.1");

	public static readonly KLKJHFKJLEM DCHAIAFOLAM = ECAEPKAOODF.BCDAGLPENOK("2.3");

	public static readonly KLKJHFKJLEM LAGLHPKFDCF = DCHAIAFOLAM.BCDAGLPENOK("1");

	public static readonly KLKJHFKJLEM NAKBKBKCPBC = DCHAIAFOLAM.BCDAGLPENOK("2");

	public static readonly KLKJHFKJLEM JPANNAPKKGP = DCHAIAFOLAM.BCDAGLPENOK("3");

	public static readonly KLKJHFKJLEM LHJKOAFBMMH = DCHAIAFOLAM.BCDAGLPENOK("4");

	public static readonly KLKJHFKJLEM DCAJBOPONMA = DCHAIAFOLAM.BCDAGLPENOK("5");

	public static readonly KLKJHFKJLEM CBNOGFBPMDC = DCHAIAFOLAM.BCDAGLPENOK("6");

	public static readonly KLKJHFKJLEM OONMEPBPKLB = DCHAIAFOLAM.BCDAGLPENOK("7");

	public static readonly KLKJHFKJLEM KPIHPELDBEF = DCHAIAFOLAM.BCDAGLPENOK("8");
}
