using System;

public class JKAOAAMMPPH : EDENIAPLFEN
{
	private GFNFFCGAGEH[] ANMHLKGBNIP;

	public JKAOAAMMPPH(params GFNFFCGAGEH[] ANMHLKGBNIP)
	{
		if (ANMHLKGBNIP == null)
		{
			throw new ArgumentNullException("atlas array cannot be null.");
		}
		this.ANMHLKGBNIP = ANMHLKGBNIP;
	}

	public MKEALIMJCFJ HNCBJFIPJNP(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN, string LCCKDPIBKPJ)
	{
		FCPKAKFLFEG fCPKAKFLFEG = GIGKGEPPBCG(LCCKDPIBKPJ);
		if (fCPKAKFLFEG == null)
		{
			throw new ArgumentException(string.Format("Region not found in atlas: {0} (region attachment: {1})", LCCKDPIBKPJ, IOCMOCCFALN));
		}
		MKEALIMJCFJ mKEALIMJCFJ = new MKEALIMJCFJ(IOCMOCCFALN);
		mKEALIMJCFJ.HIPOEPNPBPO = fCPKAKFLFEG;
		mKEALIMJCFJ.ECIMDDHDCFK(fCPKAKFLFEG.OJOAGEHFPNP, fCPKAKFLFEG.AAIEJDNAODP, fCPKAKFLFEG.ECKFKMJFOCI, fCPKAKFLFEG.OFFFLJCPAJE, fCPKAKFLFEG.BBMMCOJNJHE);
		mKEALIMJCFJ.MBHOIJFNKPO = fCPKAKFLFEG.MLKPDGNHNAE;
		mKEALIMJCFJ.JGEIMMGNNFN = fCPKAKFLFEG.INDIJOFPNGA;
		mKEALIMJCFJ.ECJFPIOKKGN = fCPKAKFLFEG.HHHMOGOKFHF;
		mKEALIMJCFJ.MJCEICPLJKP = fCPKAKFLFEG.JKNPBEOPMPK;
		mKEALIMJCFJ.LBNLLJNGJHP = fCPKAKFLFEG.OMHIBPLGBME;
		mKEALIMJCFJ.HLMKOMNGAMA = fCPKAKFLFEG.JMEGIPJIGMK;
		return mKEALIMJCFJ;
	}

	public MGCLDKAFCIB MPDDHGBKGCP(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN, string LCCKDPIBKPJ)
	{
		FCPKAKFLFEG fCPKAKFLFEG = GIGKGEPPBCG(LCCKDPIBKPJ);
		if (fCPKAKFLFEG == null)
		{
			throw new ArgumentException(string.Format("Region not found in atlas: {0} (region attachment: {1})", LCCKDPIBKPJ, IOCMOCCFALN));
		}
		MGCLDKAFCIB mGCLDKAFCIB = new MGCLDKAFCIB(IOCMOCCFALN);
		mGCLDKAFCIB.HIPOEPNPBPO = fCPKAKFLFEG;
		mGCLDKAFCIB.AMPGPNLBJKC = fCPKAKFLFEG.OJOAGEHFPNP;
		mGCLDKAFCIB.INFIMLAEHGL = fCPKAKFLFEG.AAIEJDNAODP;
		mGCLDKAFCIB.GGHFMMGLANA = fCPKAKFLFEG.ECKFKMJFOCI;
		mGCLDKAFCIB.HDCMGPKKCEJ = fCPKAKFLFEG.OFFFLJCPAJE;
		mGCLDKAFCIB.GCNJNMPFNJC = fCPKAKFLFEG.BBMMCOJNJHE;
		mGCLDKAFCIB.MBHOIJFNKPO = fCPKAKFLFEG.MLKPDGNHNAE;
		mGCLDKAFCIB.JGEIMMGNNFN = fCPKAKFLFEG.INDIJOFPNGA;
		mGCLDKAFCIB.ECJFPIOKKGN = fCPKAKFLFEG.HHHMOGOKFHF;
		mGCLDKAFCIB.MJCEICPLJKP = fCPKAKFLFEG.JKNPBEOPMPK;
		mGCLDKAFCIB.LBNLLJNGJHP = fCPKAKFLFEG.OMHIBPLGBME;
		mGCLDKAFCIB.HLMKOMNGAMA = fCPKAKFLFEG.JMEGIPJIGMK;
		return mGCLDKAFCIB;
	}

	public KBLNEHAAAJK KMGJEJLCPLE(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN)
	{
		return new KBLNEHAAAJK(IOCMOCCFALN);
	}

	public GMLCOKFENFN HAOODEOAMHH(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN)
	{
		return new GMLCOKFENFN(IOCMOCCFALN);
	}

	public ENIPPOEKJPA NJIHKIHEHKL(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN)
	{
		return new ENIPPOEKJPA(IOCMOCCFALN);
	}

	public ACEGNBDLKEG HLKKDHKIPOC(JPAALKCPGNB HLCFGIFLPPE, string IOCMOCCFALN)
	{
		return new ACEGNBDLKEG(IOCMOCCFALN);
	}

	public FCPKAKFLFEG GIGKGEPPBCG(string IOCMOCCFALN)
	{
		for (int i = 0; i < ANMHLKGBNIP.Length; i++)
		{
			FCPKAKFLFEG fCPKAKFLFEG = ANMHLKGBNIP[i].GIGKGEPPBCG(IOCMOCCFALN);
			if (fCPKAKFLFEG != null)
			{
				return fCPKAKFLFEG;
			}
		}
		return null;
	}
}
