using System;
using Org.BouncyCastle.Math;
using Org.BouncyCastle.Security;

public class JMLCKFLAGEF : CFMMJCMIGNM
{
	private readonly string ADLMOHOLCGL;

	private MJDENGGDLMJ IJJHBEECMBP;

	private KLKJHFKJLEM DHNJFHPNJLM;

	private FBIJJFGLKMK GECCLOFELEC;

	public JMLCKFLAGEF()
		: this("EC")
	{
	}

	public JMLCKFLAGEF(string ADLMOHOLCGL)
	{
		if (ADLMOHOLCGL == null)
		{
			throw new ArgumentNullException("algorithm");
		}
		this.ADLMOHOLCGL = BKFMFPGHIJB.HFPDJDIJMPC(ADLMOHOLCGL);
	}

	public void DIOELAHNLKJ(HPBPDALECOG IJJHBEECMBP)
	{
		if (IJJHBEECMBP is JDKCFKJJIHN)
		{
			JDKCFKJJIHN jDKCFKJJIHN = (JDKCFKJJIHN)IJJHBEECMBP;
			DHNJFHPNJLM = jDKCFKJJIHN.LMJPMDMLPNH;
			this.IJJHBEECMBP = jDKCFKJJIHN.DAFBLKBCACB;
		}
		else
		{
			KLKJHFKJLEM kLKJHFKJLEM;
			switch (IJJHBEECMBP.IBANINMCJPP)
			{
			case 192:
				kLKJHFKJLEM = JJFMEBLGJEP.OOMKCFHKIAE;
				break;
			case 224:
				kLKJHFKJLEM = LNFIJKGIHLA.IOHKEAFEBNE;
				break;
			case 239:
				kLKJHFKJLEM = JJFMEBLGJEP.MCFHNBEONGF;
				break;
			case 256:
				kLKJHFKJLEM = JJFMEBLGJEP.IGNEAKENMLM;
				break;
			case 384:
				kLKJHFKJLEM = LNFIJKGIHLA.AEMEHBDKHLF;
				break;
			case 521:
				kLKJHFKJLEM = LNFIJKGIHLA.BCCOIEKEHKB;
				break;
			default:
				throw new InvalidParameterException("unknown key size.");
			}
			JMLDNPGFBDA jMLDNPGFBDA = GJFLBAIJAEM(kLKJHFKJLEM);
			DHNJFHPNJLM = kLKJHFKJLEM;
			this.IJJHBEECMBP = new MJDENGGDLMJ(jMLDNPGFBDA.ECFGFKNLLGH, jMLDNPGFBDA.HBGOKILMBJG, jMLDNPGFBDA.HNLMGJGNBDD, jMLDNPGFBDA.JGOHMOHEFMJ, jMLDNPGFBDA.GKBBKKNGJAK());
		}
		GECCLOFELEC = IJJHBEECMBP.IPFKDIJBGIM;
		if (GECCLOFELEC == null)
		{
			GECCLOFELEC = new FBIJJFGLKMK();
		}
	}

	public HOHJPJDGOLF LOFCKPBODIJ()
	{
		BigInteger bigInteger = IJJHBEECMBP.HNLMGJGNBDD;
		int num = bigInteger.BitLength >> 2;
		BigInteger bigInteger2;
		do
		{
			bigInteger2 = new BigInteger(bigInteger.BitLength, GECCLOFELEC);
		}
		while (bigInteger2.JLPDKNFCNPO(BigInteger.Two) < 0 || bigInteger2.JLPDKNFCNPO(bigInteger) >= 0 || ABHJGAELGKM.BKBGONMOPKI(bigInteger2) < num);
		JGAFKLGGBGF oKDPJHOEPBJ = MNNAMFOOBIC().IBJBIGNPNEM(IJJHBEECMBP.HBGOKILMBJG, bigInteger2);
		if (DHNJFHPNJLM != null)
		{
			return new HOHJPJDGOLF(new EGEBOHHBFLK(ADLMOHOLCGL, oKDPJHOEPBJ, DHNJFHPNJLM), new EKGPBAENHIF(ADLMOHOLCGL, bigInteger2, DHNJFHPNJLM));
		}
		return new HOHJPJDGOLF(new EGEBOHHBFLK(ADLMOHOLCGL, oKDPJHOEPBJ, IJJHBEECMBP), new EKGPBAENHIF(ADLMOHOLCGL, bigInteger2, IJJHBEECMBP));
	}

	protected virtual FFPNOKBELNH MNNAMFOOBIC()
	{
		return new JPEIAFMHCOG();
	}

	internal static JMLDNPGFBDA GJFLBAIJAEM(KLKJHFKJLEM GDFLIKNMBCL)
	{
		JMLDNPGFBDA jMLDNPGFBDA = FNGEMGAMEDA.BHLONOMMIGE(GDFLIKNMBCL);
		if (jMLDNPGFBDA == null)
		{
			jMLDNPGFBDA = BBLDODBKNIN.BHLONOMMIGE(GDFLIKNMBCL);
		}
		return jMLDNPGFBDA;
	}

	internal static EGEBOHHBFLK CIFDICAMGIE(EKGPBAENHIF HJHDLHEGMJF)
	{
		MJDENGGDLMJ mJDENGGDLMJ = HJHDLHEGMJF.KPJHHAAOFOH;
		JGAFKLGGBGF oKDPJHOEPBJ = new JPEIAFMHCOG().IBJBIGNPNEM(mJDENGGDLMJ.HBGOKILMBJG, HJHDLHEGMJF.INCIODEICNM);
		if (HJHDLHEGMJF.LMJPMDMLPNH != null)
		{
			return new EGEBOHHBFLK(HJHDLHEGMJF.KFKMEPMEBND, oKDPJHOEPBJ, HJHDLHEGMJF.LMJPMDMLPNH);
		}
		return new EGEBOHHBFLK(HJHDLHEGMJF.KFKMEPMEBND, oKDPJHOEPBJ, mJDENGGDLMJ);
	}
}
