using System;
using Org.BouncyCastle.Math;

public class JMLDNPGFBDA : LNKPCJLANAO
{
	private CGAMCAFJLGJ NINOABCHAHL;

	private BHPIABAGAPB NINILENHPHE;

	private EPOKPEIHHJG HJMBDGKAOBP;

	private BigInteger IDHLPOFDLKJ;

	private BigInteger GPJDJCGDJDC;

	private byte[] HJBOEOOLOOE;

	public BHPIABAGAPB ECFGFKNLLGH
	{
		get
		{
			return NINILENHPHE;
		}
	}

	public JGAFKLGGBGF HBGOKILMBJG
	{
		get
		{
			return HJMBDGKAOBP.NCJHDEHECDN;
		}
	}

	public BigInteger HNLMGJGNBDD
	{
		get
		{
			return IDHLPOFDLKJ;
		}
	}

	public BigInteger JGOHMOHEFMJ
	{
		get
		{
			return GPJDJCGDJDC;
		}
	}

	public EBMGIDBMGJP OFLPPNGJIJI
	{
		get
		{
			return new EBMGIDBMGJP(NINILENHPHE, HJBOEOOLOOE);
		}
	}

	public CGAMCAFJLGJ GFCJAOFENIG
	{
		get
		{
			return NINOABCHAHL;
		}
	}

	public EPOKPEIHHJG FPHALCGDPGL
	{
		get
		{
			return HJMBDGKAOBP;
		}
	}

	public JMLDNPGFBDA(ALLINHNNNJN MIABODPHOIP)
	{
		if (!(MIABODPHOIP.ECNCPJGHBIG(0) is GLFDIPNOLKN) || !((GLFDIPNOLKN)MIABODPHOIP.ECNCPJGHBIG(0)).JBGOANMLBFA.Equals(BigInteger.One))
		{
			throw new ArgumentException("bad version in X9ECParameters");
		}
		EBMGIDBMGJP eBMGIDBMGJP = new EBMGIDBMGJP(CGAMCAFJLGJ.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(1)), ALLINHNNNJN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(2)));
		NINILENHPHE = eBMGIDBMGJP.ECFGFKNLLGH;
		object obj = MIABODPHOIP.ECNCPJGHBIG(3);
		if (obj is EPOKPEIHHJG)
		{
			HJMBDGKAOBP = (EPOKPEIHHJG)obj;
		}
		else
		{
			HJMBDGKAOBP = new EPOKPEIHHJG(NINILENHPHE, (PJGIGKJFGFI)obj);
		}
		IDHLPOFDLKJ = ((GLFDIPNOLKN)MIABODPHOIP.ECNCPJGHBIG(4)).JBGOANMLBFA;
		HJBOEOOLOOE = eBMGIDBMGJP.GKBBKKNGJAK();
		if (MIABODPHOIP.GMCGMPEEHJP == 6)
		{
			GPJDJCGDJDC = ((GLFDIPNOLKN)MIABODPHOIP.ECNCPJGHBIG(5)).JBGOANMLBFA;
		}
	}

	public JMLDNPGFBDA(BHPIABAGAPB NINILENHPHE, JGAFKLGGBGF HJMBDGKAOBP, BigInteger IDHLPOFDLKJ)
		: this(NINILENHPHE, HJMBDGKAOBP, IDHLPOFDLKJ, null, null)
	{
	}

	public JMLDNPGFBDA(BHPIABAGAPB NINILENHPHE, EPOKPEIHHJG HJMBDGKAOBP, BigInteger IDHLPOFDLKJ, BigInteger GPJDJCGDJDC)
		: this(NINILENHPHE, HJMBDGKAOBP, IDHLPOFDLKJ, GPJDJCGDJDC, null)
	{
	}

	public JMLDNPGFBDA(BHPIABAGAPB NINILENHPHE, JGAFKLGGBGF HJMBDGKAOBP, BigInteger IDHLPOFDLKJ, BigInteger GPJDJCGDJDC)
		: this(NINILENHPHE, HJMBDGKAOBP, IDHLPOFDLKJ, GPJDJCGDJDC, null)
	{
	}

	public JMLDNPGFBDA(BHPIABAGAPB NINILENHPHE, JGAFKLGGBGF HJMBDGKAOBP, BigInteger IDHLPOFDLKJ, BigInteger GPJDJCGDJDC, byte[] HJBOEOOLOOE)
		: this(NINILENHPHE, new EPOKPEIHHJG(HJMBDGKAOBP), IDHLPOFDLKJ, GPJDJCGDJDC, HJBOEOOLOOE)
	{
	}

	public JMLDNPGFBDA(BHPIABAGAPB NINILENHPHE, EPOKPEIHHJG HJMBDGKAOBP, BigInteger IDHLPOFDLKJ, BigInteger GPJDJCGDJDC, byte[] HJBOEOOLOOE)
	{
		this.NINILENHPHE = NINILENHPHE;
		this.HJMBDGKAOBP = HJMBDGKAOBP;
		this.IDHLPOFDLKJ = IDHLPOFDLKJ;
		this.GPJDJCGDJDC = GPJDJCGDJDC;
		this.HJBOEOOLOOE = HJBOEOOLOOE;
		if (KHJLHEJBLOA.FNAAANIPFOP(NINILENHPHE))
		{
			NINOABCHAHL = new CGAMCAFJLGJ(NINILENHPHE.LLHBLBINBOA.HJKCMCLHBEN);
			return;
		}
		if (KHJLHEJBLOA.BDGICGJIGPF(NINILENHPHE))
		{
			AIGKJBLDPNN aIGKJBLDPNN = (AIGKJBLDPNN)NINILENHPHE.LLHBLBINBOA;
			int[] array = aIGKJBLDPNN.AJFCOOELGPF.KOHLMNNELKF();
			if (array.Length == 3)
			{
				NINOABCHAHL = new CGAMCAFJLGJ(array[2], array[1]);
				return;
			}
			if (array.Length == 5)
			{
				NINOABCHAHL = new CGAMCAFJLGJ(array[4], array[1], array[2], array[3]);
				return;
			}
			throw new ArgumentException("Only trinomial and pentomial curves are supported");
		}
		throw new ArgumentException("'curve' is of an unsupported type");
	}

	public static JMLDNPGFBDA BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC is JMLDNPGFBDA)
		{
			return (JMLDNPGFBDA)NEMEKIOEOLC;
		}
		if (NEMEKIOEOLC != null)
		{
			return new JMLDNPGFBDA(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC));
		}
		return null;
	}

	public byte[] GKBBKKNGJAK()
	{
		return HJBOEOOLOOE;
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		DLDBGGDLOOO dLDBGGDLOOO = new DLDBGGDLOOO(new GLFDIPNOLKN(BigInteger.One), NINOABCHAHL, new EBMGIDBMGJP(NINILENHPHE, HJBOEOOLOOE), HJMBDGKAOBP, new GLFDIPNOLKN(IDHLPOFDLKJ));
		if (GPJDJCGDJDC != null)
		{
			dLDBGGDLOOO.JEACJNAKLDJ(new GLFDIPNOLKN(GPJDJCGDJDC));
		}
		return new KOGPLMALOEH(dLDBGGDLOOO);
	}
}
