using System.Collections.Generic;
using Assets.Scripts.SceneTransitions;
using Assets.Scripts.Utils.Analytics;
using UnityEngine;
using caravan.protobuf.messages;

public static class KBEGNPKLMDE
{
	private static bool HHEABNCOLEL;

	private static bool OIDCDBGELLH;

	public static void IAEBCJLMJJO()
	{
		if (ELBMHNOBHPN.DJGMHLLAGLE)
		{
			return;
		}
		bool flag = CaravanSceneManager.SceneToBeLoaded == GKBHIKONCKJ.Map;
		bool flag2 = CaravanSceneManager.CurrentScene == GKBHIKONCKJ.Map;
		if (flag2)
		{
			OIDCDBGELLH = false;
		}
		if (flag || flag2)
		{
			List<IKDMCJPBBIH> list = new List<IKDMCJPBBIH>();
			if (!OIAJPMNJGLK.CHHIMPENGBG() || ELBMHNOBHPN.EDAFBCMCHDH)
			{
				HHEABNCOLEL = true;
				list.Add(new CBLGCPEEKDM());
				list.Add(new AEJCEEFPJIA());
				KIHMBFDKLJM.GABGKBAKHDP.IINKCBOCHBG(list);
				return;
			}
			JGKAOEGOPCP(list);
			OBPBBIECJPF(list, flag2);
			LGFFLIDBABK(list, flag2);
			IBGOGGJKFLP(list, flag2);
			FFACCBGFJIH(list);
			HHEABNCOLEL = false;
			OIDCDBGELLH = false;
			KIHMBFDKLJM.GABGKBAKHDP.IINKCBOCHBG(list);
		}
	}

	private static void JGKAOEGOPCP(List<IKDMCJPBBIH> IOEIGPCEKOO)
	{
		JOPDCIADIEB jOPDCIADIEB = new JOPDCIADIEB();
		NCHDJAAJNIG nCHDJAAJNIG = new NCHDJAAJNIG();
		if (!HHEABNCOLEL)
		{
			IOEIGPCEKOO.Add(new CBLGCPEEKDM());
		}
		if (!OIDCDBGELLH && jOPDCIADIEB.ELDBGPGMBBK())
		{
			IOEIGPCEKOO.Add(jOPDCIADIEB);
		}
		if (!OIDCDBGELLH && nCHDJAAJNIG.ELDBGPGMBBK())
		{
			IOEIGPCEKOO.Add(nCHDJAAJNIG);
		}
		OIMALFKCFDJ(IOEIGPCEKOO);
	}

	private static void OIMALFKCFDJ(List<IKDMCJPBBIH> IOEIGPCEKOO)
	{
		if (!NDGOJGLPIJF.GABGKBAKHDP.NEEBONFOOCB())
		{
			IOEIGPCEKOO.Add(new NKPDMAEDFHC());
		}
		if (DJFEHCGIDGC.GABGKBAKHDP.DNFKADNNPCD())
		{
			IOEIGPCEKOO.Add(new JMKANEEICJF());
		}
		if (BPPNANHCLJI.GABGKBAKHDP.PNOLICHIGEC())
		{
			IOEIGPCEKOO.Add(new JOLEBCDGILA());
		}
	}

	private static void OBPBBIECJPF(List<IKDMCJPBBIH> IOEIGPCEKOO, bool FGIHCMCJBPN)
	{
		IDFPAFEJPPH iDFPAFEJPPH = IDFPAFEJPPH.GABGKBAKHDP;
		if (!OIDCDBGELLH && iDFPAFEJPPH.HGNJBHGBLIN && !IDFPAFEJPPH.GABGKBAKHDP.KDFCPCAHFPC())
		{
			PKHCHGIKLED item = new PKHCHGIKLED(iDFPAFEJPPH.PDGLECFDLJJ, iDFPAFEJPPH.KOPMPMIFHNF, iDFPAFEJPPH.MMFJEAJBJJG, iDFPAFEJPPH.NBJMMBIGCOB);
			IOEIGPCEKOO.Add(item);
		}
		if (FGIHCMCJBPN)
		{
			GBFAPADEBEC.PFGLLCEKCGI(PBIIDJOKNEK.ChampionsLeague, "Focus In > CheckStatusCommand Called");
			IOEIGPCEKOO.Add(iDFPAFEJPPH.CGOOBAHCDDK());
		}
		else if (IDFPAFEJPPH.APCILMENFLJ() || iDFPAFEJPPH.AEPLIGFCGIF == ClStatusType.CONNECTED)
		{
			GBFAPADEBEC.PFGLLCEKCGI(PBIIDJOKNEK.ChampionsLeague, "Game Start Commands > CheckStatusCommand Called");
			IOEIGPCEKOO.Add(iDFPAFEJPPH.EBAMEPLFLKO());
		}
	}

	private static void LGFFLIDBABK(List<IKDMCJPBBIH> IOEIGPCEKOO, bool FGIHCMCJBPN)
	{
		IOEIGPCEKOO.Add(new KBBPGCKJHNJ
		{
			OOKBNILGMAN = FGIHCMCJBPN
		});
		PKGCHMIBMNB(IOEIGPCEKOO);
		OKMIDOFBCDG(IOEIGPCEKOO);
		IFBNOKMIHME(IOEIGPCEKOO);
	}

	private static void PKGCHMIBMNB(List<IKDMCJPBBIH> IOEIGPCEKOO)
	{
		long EMNOJOHFMEH;
		int GCKOBKBPOBE;
		AAPMDEEMEMM.GHPPDPBLAOL(out EMNOJOHFMEH, out GCKOBKBPOBE);
		if (EMNOJOHFMEH != 0 && GCKOBKBPOBE != 0)
		{
			IOEIGPCEKOO.Add(new GFOFLPPPDOF(EMNOJOHFMEH, GCKOBKBPOBE));
		}
		AAPMDEEMEMM aAPMDEEMEMM = DGOMNDMPMBG.GABGKBAKHDP.BHGCBNAMEFK;
		if (aAPMDEEMEMM != null)
		{
			if (EMNOJOHFMEH != 0)
			{
				IOEIGPCEKOO.Add(new GFOFLPPPDOF(EMNOJOHFMEH, (GCKOBKBPOBE == 0) ? aAPMDEEMEMM.IFOAAOCJODG : GCKOBKBPOBE));
			}
			if (aAPMDEEMEMM.AEBACBBGHKI == 0 && aAPMDEEMEMM.PGMKKMIEBGB == 0 && aAPMDEEMEMM.EBEALFFCHFB)
			{
				DGOMNDMPMBG.GABGKBAKHDP.JJEPNNKPNBP(3, aAPMDEEMEMM.IFOAAOCJODG);
				AAPMDEEMEMM.BKDMLALPOEN();
				DGOMNDMPMBG.GABGKBAKHDP.MONGKICFIMO(3);
			}
			long num = LECPGNKOABP.GABGKBAKHDP.OADDPGNIINO;
			if (GFHPEDILAJG.GABGKBAKHDP.ODMCGBLJFKM && num != EMNOJOHFMEH)
			{
				IOEIGPCEKOO.Add(new IOCEEPMIBLN(num, aAPMDEEMEMM.IFOAAOCJODG));
			}
		}
	}

	private static void OKMIDOFBCDG(List<IKDMCJPBBIH> IOEIGPCEKOO)
	{
		KCKDNJOMPJH.CDGGACPJAPD();
		if (!GFHPEDILAJG.GABGKBAKHDP.ODMCGBLJFKM)
		{
			return;
		}
		long gCKOBKBPOBE = 0L;
		long kEKPBEKCPNN = 0L;
		long eMNOJOHFMEH = LECPGNKOABP.GABGKBAKHDP.OADDPGNIINO;
		KCKDNJOMPJH kCKDNJOMPJH = DGOMNDMPMBG.GABGKBAKHDP.FABKMFCBELE;
		if (kCKDNJOMPJH != null)
		{
			if (kCKDNJOMPJH.AEPLIGFCGIF == 3)
			{
				if (kCKDNJOMPJH.EEJGJPLADGB > 0)
				{
					DGOMNDMPMBG.GABGKBAKHDP.JJEPNNKPNBP(6, kCKDNJOMPJH.IFOAAOCJODG);
					KCKDNJOMPJH.PMHFHCBEENO();
				}
				DGOMNDMPMBG.GABGKBAKHDP.MONGKICFIMO(6);
			}
			gCKOBKBPOBE = kCKDNJOMPJH.IFOAAOCJODG;
			kEKPBEKCPNN = kCKDNJOMPJH.INFAGKCBEHL;
		}
		if (kCKDNJOMPJH == null || kCKDNJOMPJH.AEPLIGFCGIF < 2 || kCKDNJOMPJH.AEBACBBGHKI <= 0)
		{
			IOEIGPCEKOO.Add(new FBNFMCGHLEE(gCKOBKBPOBE, kEKPBEKCPNN, eMNOJOHFMEH));
		}
	}

	private static void IFBNOKMIHME(List<IKDMCJPBBIH> IOEIGPCEKOO)
	{
		GPAFPAEDOHM.CDGGACPJAPD();
		long num = 0L;
		GPAFPAEDOHM gPAFPAEDOHM = DGOMNDMPMBG.GABGKBAKHDP.IIEALLANECJ;
		if (gPAFPAEDOHM != null)
		{
			if (gPAFPAEDOHM.AEPLIGFCGIF == 3)
			{
				DGOMNDMPMBG.GABGKBAKHDP.JJEPNNKPNBP(4, gPAFPAEDOHM.IFOAAOCJODG);
				GPAFPAEDOHM.PMHFHCBEENO();
				DGOMNDMPMBG.GABGKBAKHDP.MONGKICFIMO(4);
			}
			else
			{
				num = gPAFPAEDOHM.INFAGKCBEHL;
			}
		}
		IOEIGPCEKOO.Add(new ILCNNFKJEFG(num, num == 0));
	}

	private static void IBGOGGJKFLP(List<IKDMCJPBBIH> IOEIGPCEKOO, bool FGIHCMCJBPN)
	{
		if (!FGIHCMCJBPN && LECPGNKOABP.GABGKBAKHDP.GDMECFECCOM > 0)
		{
			string deviceId = PeakAnalytics.GetDeviceId();
			string @string = PlayerPrefs.GetString("LastDeviceId", string.Empty);
			if (!(deviceId == @string))
			{
				IOEIGPCEKOO.Add(new FHAMJBLFOHL(deviceId));
			}
		}
	}

	private static void FFACCBGFJIH(List<IKDMCJPBBIH> IOEIGPCEKOO)
	{
		if (JDOKMBCDMLO.EBFFKPDMFIG().Count > 0)
		{
			IOEIGPCEKOO.Add(new JDOKMBCDMLO());
		}
	}

	public static void BHGNAHECMDH()
	{
		HHEABNCOLEL = true;
		List<IKDMCJPBBIH> list = new List<IKDMCJPBBIH>();
		list.Add(new CBLGCPEEKDM());
		List<IKDMCJPBBIH> list2 = list;
		if (!ELBMHNOBHPN.DJGMHLLAGLE || !ELBMHNOBHPN.IFBBNKJDOHE)
		{
			list2.Add(new AEJCEEFPJIA());
		}
		KIHMBFDKLJM.GABGKBAKHDP.IINKCBOCHBG(list2);
	}

	public static void BFMGMOGNPLJ()
	{
		OIDCDBGELLH = true;
		List<IKDMCJPBBIH> list = new List<IKDMCJPBBIH>();
		JOPDCIADIEB jOPDCIADIEB = new JOPDCIADIEB();
		NCHDJAAJNIG nCHDJAAJNIG = new NCHDJAAJNIG();
		IDFPAFEJPPH iDFPAFEJPPH = IDFPAFEJPPH.GABGKBAKHDP;
		if (jOPDCIADIEB.ELDBGPGMBBK())
		{
			list.Add(jOPDCIADIEB);
		}
		if (nCHDJAAJNIG.ELDBGPGMBBK())
		{
			list.Add(nCHDJAAJNIG);
		}
		if (iDFPAFEJPPH.HGNJBHGBLIN && !IDFPAFEJPPH.GABGKBAKHDP.KDFCPCAHFPC())
		{
			PKHCHGIKLED item = new PKHCHGIKLED(iDFPAFEJPPH.PDGLECFDLJJ, iDFPAFEJPPH.KOPMPMIFHNF, iDFPAFEJPPH.MMFJEAJBJJG, iDFPAFEJPPH.NBJMMBIGCOB);
			list.Add(item);
		}
		KIHMBFDKLJM.GABGKBAKHDP.IINKCBOCHBG(list);
	}
}
