using System;
using System.Collections;
using Org.BouncyCastle.Security;

public sealed class KDDIIEMIPKF
{
	private enum GKPBGCDNLLL
	{
		GOST3411 = 0,
		KECCAK_224 = 1,
		KECCAK_256 = 2,
		KECCAK_288 = 3,
		KECCAK_384 = 4,
		KECCAK_512 = 5,
		MD2 = 6,
		MD4 = 7,
		MD5 = 8,
		RIPEMD128 = 9,
		RIPEMD160 = 10,
		RIPEMD256 = 11,
		RIPEMD320 = 12,
		SHA_1 = 13,
		SHA_224 = 14,
		SHA_256 = 15,
		SHA_384 = 16,
		SHA_512 = 17,
		SHA_512_224 = 18,
		SHA_512_256 = 19,
		SHA3_224 = 20,
		SHA3_256 = 21,
		SHA3_384 = 22,
		SHA3_512 = 23,
		SHAKE128 = 24,
		SHAKE256 = 25,
		TIGER = 26,
		WHIRLPOOL = 27
	}

	private static readonly IDictionary NCLCMMGJEBI;

	private static readonly IDictionary MJNANGPLADC;

	public static ICollection BHDMAEHKBEP
	{
		get
		{
			return MJNANGPLADC.Keys;
		}
	}

	private KDDIIEMIPKF()
	{
	}

	static KDDIIEMIPKF()
	{
		NCLCMMGJEBI = LHFGHNFJIKM.JBEOCJEMGCE();
		MJNANGPLADC = LHFGHNFJIKM.JBEOCJEMGCE();
		((GKPBGCDNLLL)(object)APJJMPFMLBB.CHNBJKHAAJH(typeof(GKPBGCDNLLL))).ToString();
		NCLCMMGJEBI[NLPPJKFFBON.LEJDEOPIHPN.EEFMIHDPJPG] = "MD2";
		NCLCMMGJEBI[NLPPJKFFBON.PKOKJMOJEHF.EEFMIHDPJPG] = "MD4";
		NCLCMMGJEBI[NLPPJKFFBON.HCEBKEDMKGI.EEFMIHDPJPG] = "MD5";
		NCLCMMGJEBI["SHA1"] = "SHA-1";
		NCLCMMGJEBI[POLLKACILDK.MEBPJCLMCDA.EEFMIHDPJPG] = "SHA-1";
		NCLCMMGJEBI["SHA224"] = "SHA-224";
		NCLCMMGJEBI[HHKLFIFJNFO.NGAKIGLLNMJ.EEFMIHDPJPG] = "SHA-224";
		NCLCMMGJEBI["SHA256"] = "SHA-256";
		NCLCMMGJEBI[HHKLFIFJNFO.OKLEKJJIGME.EEFMIHDPJPG] = "SHA-256";
		NCLCMMGJEBI["SHA384"] = "SHA-384";
		NCLCMMGJEBI[HHKLFIFJNFO.EJIHFCHFMLO.EEFMIHDPJPG] = "SHA-384";
		NCLCMMGJEBI["SHA512"] = "SHA-512";
		NCLCMMGJEBI[HHKLFIFJNFO.HBLLHCKNOKB.EEFMIHDPJPG] = "SHA-512";
		NCLCMMGJEBI["SHA512/224"] = "SHA-512/224";
		NCLCMMGJEBI[HHKLFIFJNFO.NLHHAIELEHG.EEFMIHDPJPG] = "SHA-512/224";
		NCLCMMGJEBI["SHA512/256"] = "SHA-512/256";
		NCLCMMGJEBI[HHKLFIFJNFO.OEBFCNGIHOA.EEFMIHDPJPG] = "SHA-512/256";
		NCLCMMGJEBI["RIPEMD-128"] = "RIPEMD128";
		NCLCMMGJEBI[HECJIGBIHCA.KCPONBGBCIG.EEFMIHDPJPG] = "RIPEMD128";
		NCLCMMGJEBI["RIPEMD-160"] = "RIPEMD160";
		NCLCMMGJEBI[HECJIGBIHCA.LNJCFFFDBMO.EEFMIHDPJPG] = "RIPEMD160";
		NCLCMMGJEBI["RIPEMD-256"] = "RIPEMD256";
		NCLCMMGJEBI[HECJIGBIHCA.AEIDPDDECDO.EEFMIHDPJPG] = "RIPEMD256";
		NCLCMMGJEBI["RIPEMD-320"] = "RIPEMD320";
		NCLCMMGJEBI[FNOHIHFMAMN.EPDBPJHHJIP.EEFMIHDPJPG] = "GOST3411";
		NCLCMMGJEBI[HHKLFIFJNFO.PNLGOMMMHOP.EEFMIHDPJPG] = "SHA3-224";
		NCLCMMGJEBI[HHKLFIFJNFO.IICEOLLCEDN.EEFMIHDPJPG] = "SHA3-256";
		NCLCMMGJEBI[HHKLFIFJNFO.JMCCAFJFGFE.EEFMIHDPJPG] = "SHA3-384";
		NCLCMMGJEBI[HHKLFIFJNFO.FIPJCKMCKLD.EEFMIHDPJPG] = "SHA3-512";
		NCLCMMGJEBI[HHKLFIFJNFO.OFOKHPLDFHF.EEFMIHDPJPG] = "SHAKE128";
		NCLCMMGJEBI[HHKLFIFJNFO.MNHBLJINCDF.EEFMIHDPJPG] = "SHAKE256";
		MJNANGPLADC["MD2"] = NLPPJKFFBON.LEJDEOPIHPN;
		MJNANGPLADC["MD4"] = NLPPJKFFBON.PKOKJMOJEHF;
		MJNANGPLADC["MD5"] = NLPPJKFFBON.HCEBKEDMKGI;
		MJNANGPLADC["SHA-1"] = POLLKACILDK.MEBPJCLMCDA;
		MJNANGPLADC["SHA-224"] = HHKLFIFJNFO.NGAKIGLLNMJ;
		MJNANGPLADC["SHA-256"] = HHKLFIFJNFO.OKLEKJJIGME;
		MJNANGPLADC["SHA-384"] = HHKLFIFJNFO.EJIHFCHFMLO;
		MJNANGPLADC["SHA-512"] = HHKLFIFJNFO.HBLLHCKNOKB;
		MJNANGPLADC["SHA-512/224"] = HHKLFIFJNFO.NLHHAIELEHG;
		MJNANGPLADC["SHA-512/256"] = HHKLFIFJNFO.OEBFCNGIHOA;
		MJNANGPLADC["SHA3-224"] = HHKLFIFJNFO.PNLGOMMMHOP;
		MJNANGPLADC["SHA3-256"] = HHKLFIFJNFO.IICEOLLCEDN;
		MJNANGPLADC["SHA3-384"] = HHKLFIFJNFO.JMCCAFJFGFE;
		MJNANGPLADC["SHA3-512"] = HHKLFIFJNFO.FIPJCKMCKLD;
		MJNANGPLADC["SHAKE128"] = HHKLFIFJNFO.OFOKHPLDFHF;
		MJNANGPLADC["SHAKE256"] = HHKLFIFJNFO.MNHBLJINCDF;
		MJNANGPLADC["RIPEMD128"] = HECJIGBIHCA.KCPONBGBCIG;
		MJNANGPLADC["RIPEMD160"] = HECJIGBIHCA.LNJCFFFDBMO;
		MJNANGPLADC["RIPEMD256"] = HECJIGBIHCA.AEIDPDDECDO;
		MJNANGPLADC["GOST3411"] = FNOHIHFMAMN.EPDBPJHHJIP;
	}

	public static KLKJHFKJLEM JPMMBAMMCLO(string MOGLECBIKEG)
	{
		if (MOGLECBIKEG == null)
		{
			throw new ArgumentNullException("mechanism");
		}
		MOGLECBIKEG = LHFGHNFJIKM.OGLCLCODHJI(MOGLECBIKEG);
		string text = (string)NCLCMMGJEBI[MOGLECBIKEG];
		if (text != null)
		{
			MOGLECBIKEG = text;
		}
		return (KLKJHFKJLEM)MJNANGPLADC[MOGLECBIKEG];
	}

	public static BJLAMONNNDD GANMELFOOMP(KLKJHFKJLEM BDKFNEDHAOJ)
	{
		return GANMELFOOMP(BDKFNEDHAOJ.EEFMIHDPJPG);
	}

	public static BJLAMONNNDD GANMELFOOMP(string ADLMOHOLCGL)
	{
		string text = LHFGHNFJIKM.OGLCLCODHJI(ADLMOHOLCGL);
		string text2 = (string)NCLCMMGJEBI[text];
		if (text2 == null)
		{
			text2 = text;
		}
		try
		{
			switch ((GKPBGCDNLLL)(object)APJJMPFMLBB.OAOMOAFOOKD(typeof(GKPBGCDNLLL), text2))
			{
			case GKPBGCDNLLL.GOST3411:
				return new FHMGJEBDMAG();
			case GKPBGCDNLLL.KECCAK_224:
				return new PPHLCNGICDP(224);
			case GKPBGCDNLLL.KECCAK_256:
				return new PPHLCNGICDP(256);
			case GKPBGCDNLLL.KECCAK_288:
				return new PPHLCNGICDP(288);
			case GKPBGCDNLLL.KECCAK_384:
				return new PPHLCNGICDP(384);
			case GKPBGCDNLLL.KECCAK_512:
				return new PPHLCNGICDP(512);
			case GKPBGCDNLLL.MD2:
				return new OPBPDKCEGIJ();
			case GKPBGCDNLLL.MD4:
				return new GBFIJMMDMKK();
			case GKPBGCDNLLL.MD5:
				return new DDPKOBCIGDJ();
			case GKPBGCDNLLL.RIPEMD128:
				return new CONJOCHPANG();
			case GKPBGCDNLLL.RIPEMD160:
				return new KHIEBIHIHJA();
			case GKPBGCDNLLL.RIPEMD256:
				return new KDOKNEONHOF();
			case GKPBGCDNLLL.RIPEMD320:
				return new GGKGKMDFKPA();
			case GKPBGCDNLLL.SHA_1:
				return new KALMDEHGEAC();
			case GKPBGCDNLLL.SHA_224:
				return new JAHCGEGGLMA();
			case GKPBGCDNLLL.SHA_256:
				return new AFKIHPLKGEE();
			case GKPBGCDNLLL.SHA_384:
				return new JIDIPOBKBGH();
			case GKPBGCDNLLL.SHA_512:
				return new NLPHAELCKOJ();
			case GKPBGCDNLLL.SHA_512_224:
				return new OHELNPHIELD(224);
			case GKPBGCDNLLL.SHA_512_256:
				return new OHELNPHIELD(256);
			case GKPBGCDNLLL.SHA3_224:
				return new ONAJJHCKLPD(224);
			case GKPBGCDNLLL.SHA3_256:
				return new ONAJJHCKLPD(256);
			case GKPBGCDNLLL.SHA3_384:
				return new ONAJJHCKLPD(384);
			case GKPBGCDNLLL.SHA3_512:
				return new ONAJJHCKLPD(512);
			case GKPBGCDNLLL.SHAKE128:
				return new PFLLOAHIJKM(128);
			case GKPBGCDNLLL.SHAKE256:
				return new PFLLOAHIJKM(256);
			case GKPBGCDNLLL.TIGER:
				return new CDKEMEJLGHE();
			case GKPBGCDNLLL.WHIRLPOOL:
				return new BJCPOLAOIAB();
			}
		}
		catch (ArgumentException)
		{
		}
		throw new SecurityUtilityException("Digest " + text2 + " not recognised.");
	}

	public static string JDOPPMEGEMC(KLKJHFKJLEM GDFLIKNMBCL)
	{
		return (string)NCLCMMGJEBI[GDFLIKNMBCL.EEFMIHDPJPG];
	}

	public static byte[] MFLLPNBACJP(string ADLMOHOLCGL, byte[] MOPCLEEGDFB)
	{
		BJLAMONNNDD bJLAMONNNDD = GANMELFOOMP(ADLMOHOLCGL);
		bJLAMONNNDD.GONEEEFEDGF(MOPCLEEGDFB, 0, MOPCLEEGDFB.Length);
		return LCNOFBMOHHM(bJLAMONNNDD);
	}

	public static byte[] LCNOFBMOHHM(BJLAMONNNDD HABFKBCEIBN)
	{
		byte[] array = new byte[HABFKBCEIBN.EEMLLAMENHO()];
		HABFKBCEIBN.LCNOFBMOHHM(array, 0);
		return array;
	}

	public static byte[] LCNOFBMOHHM(BJLAMONNNDD HABFKBCEIBN, byte[] MOPCLEEGDFB)
	{
		HABFKBCEIBN.GONEEEFEDGF(MOPCLEEGDFB, 0, MOPCLEEGDFB.Length);
		return LCNOFBMOHHM(HABFKBCEIBN);
	}
}
