using UnityEngine;

public class KDLNDGMPAIH : AndroidJavaProxy
{
	private DGEFIMEIGKH NBFMBJCKJKO;

	public KDLNDGMPAIH(DGEFIMEIGKH NBFMBJCKJKO)
		: base("com.helpshift.campaigns.delegates.InboxMessageDelegate")
	{
		this.NBFMBJCKJKO = NBFMBJCKJKO;
	}

	public void ANANCFIJKJD(AndroidJavaObject OEFCOJLNCKP)
	{
		CNPKMBNDFPD oEFCOJLNCKP = CNPKMBNDFPD.IAPNPECKPPL(OEFCOJLNCKP);
		NBFMBJCKJKO.GNDAGDEMKDE(oEFCOJLNCKP);
	}

	public void NGDINMKFNFD(string KHAHOPFFEJO)
	{
		NBFMBJCKJKO.PJMFDACDFKP(KHAHOPFFEJO);
	}

	public void FEJBCDMCIAC(string KHAHOPFFEJO)
	{
		NBFMBJCKJKO.NBFDLBLONIF(KHAHOPFFEJO);
	}

	public void CLJADDMMNMF(string KHAHOPFFEJO)
	{
		NBFMBJCKJKO.JMBAINJBOEI(KHAHOPFFEJO);
	}

	public void HKIJLCFGBAH(string KHAHOPFFEJO)
	{
		NBFMBJCKJKO.PKKHKAPFLGD(KHAHOPFFEJO);
	}

	public void NIKLCHPMMJE(string KHAHOPFFEJO)
	{
		NBFMBJCKJKO.GPGAKDGANKF(KHAHOPFFEJO);
	}
}
