using System;

public class KDOKNEONHOF : EEBNPONHKOK
{
	private const int IOCOCGHMNGB = 32;

	private int OLFEOHKKGIP;

	private int NAHACOBOKIM;

	private int MPNNHCHGEGL;

	private int AJBHIPPAFIJ;

	private int GCLNAIGNJJN;

	private int CCFJELJJBPD;

	private int OCNHMOBFIKJ;

	private int HKHGOKHCEGC;

	private int[] CBPFFIBINEH = new int[16];

	private int ABBPDEOGNFE;

	public override string KFKMEPMEBND
	{
		get
		{
			return "RIPEMD256";
		}
	}

	public KDOKNEONHOF()
	{
		OMOKOKFNBKI();
	}

	public KDOKNEONHOF(KDOKNEONHOF LLIEHCKNJEM)
		: base(LLIEHCKNJEM)
	{
		AKBPCECABIO(LLIEHCKNJEM);
	}

	public override int EEMLLAMENHO()
	{
		return 32;
	}

	private void AKBPCECABIO(KDOKNEONHOF LLIEHCKNJEM)
	{
		AKBPCECABIO((EEBNPONHKOK)LLIEHCKNJEM);
		OLFEOHKKGIP = LLIEHCKNJEM.OLFEOHKKGIP;
		NAHACOBOKIM = LLIEHCKNJEM.NAHACOBOKIM;
		MPNNHCHGEGL = LLIEHCKNJEM.MPNNHCHGEGL;
		AJBHIPPAFIJ = LLIEHCKNJEM.AJBHIPPAFIJ;
		GCLNAIGNJJN = LLIEHCKNJEM.GCLNAIGNJJN;
		CCFJELJJBPD = LLIEHCKNJEM.CCFJELJJBPD;
		OCNHMOBFIKJ = LLIEHCKNJEM.OCNHMOBFIKJ;
		HKHGOKHCEGC = LLIEHCKNJEM.HKHGOKHCEGC;
		Array.Copy(LLIEHCKNJEM.CBPFFIBINEH, 0, CBPFFIBINEH, 0, LLIEHCKNJEM.CBPFFIBINEH.Length);
		ABBPDEOGNFE = LLIEHCKNJEM.ABBPDEOGNFE;
	}

	internal override void ICKIHAABCPI(byte[] MOPCLEEGDFB, int ELICNEDIBGB)
	{
		CBPFFIBINEH[ABBPDEOGNFE++] = (MOPCLEEGDFB[ELICNEDIBGB] & 0xFF) | ((MOPCLEEGDFB[ELICNEDIBGB + 1] & 0xFF) << 8) | ((MOPCLEEGDFB[ELICNEDIBGB + 2] & 0xFF) << 16) | ((MOPCLEEGDFB[ELICNEDIBGB + 3] & 0xFF) << 24);
		if (ABBPDEOGNFE == 16)
		{
			DPACJDFHLKB();
		}
	}

	internal override void IIENDLEDGMC(long EAJFCEBGGIG)
	{
		if (ABBPDEOGNFE > 14)
		{
			DPACJDFHLKB();
		}
		CBPFFIBINEH[14] = (int)(EAJFCEBGGIG & 0xFFFFFFFFu);
		CBPFFIBINEH[15] = (int)((ulong)EAJFCEBGGIG >> 32);
	}

	private void DKLAJHNFBJM(int BKKMJAIKJAL, byte[] NGAGMIIBGKA, int EMAKNGBIFDC)
	{
		NGAGMIIBGKA[EMAKNGBIFDC] = (byte)BKKMJAIKJAL;
		NGAGMIIBGKA[EMAKNGBIFDC + 1] = (byte)((uint)BKKMJAIKJAL >> 8);
		NGAGMIIBGKA[EMAKNGBIFDC + 2] = (byte)((uint)BKKMJAIKJAL >> 16);
		NGAGMIIBGKA[EMAKNGBIFDC + 3] = (byte)((uint)BKKMJAIKJAL >> 24);
	}

	public override int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		OJILOEAPDCL();
		DKLAJHNFBJM(OLFEOHKKGIP, BILGCJNPJGJ, EMAKNGBIFDC);
		DKLAJHNFBJM(NAHACOBOKIM, BILGCJNPJGJ, EMAKNGBIFDC + 4);
		DKLAJHNFBJM(MPNNHCHGEGL, BILGCJNPJGJ, EMAKNGBIFDC + 8);
		DKLAJHNFBJM(AJBHIPPAFIJ, BILGCJNPJGJ, EMAKNGBIFDC + 12);
		DKLAJHNFBJM(GCLNAIGNJJN, BILGCJNPJGJ, EMAKNGBIFDC + 16);
		DKLAJHNFBJM(CCFJELJJBPD, BILGCJNPJGJ, EMAKNGBIFDC + 20);
		DKLAJHNFBJM(OCNHMOBFIKJ, BILGCJNPJGJ, EMAKNGBIFDC + 24);
		DKLAJHNFBJM(HKHGOKHCEGC, BILGCJNPJGJ, EMAKNGBIFDC + 28);
		OMOKOKFNBKI();
		return 32;
	}

	public override void OMOKOKFNBKI()
	{
		base.OMOKOKFNBKI();
		OLFEOHKKGIP = 1732584193;
		NAHACOBOKIM = -271733879;
		MPNNHCHGEGL = -1732584194;
		AJBHIPPAFIJ = 271733878;
		GCLNAIGNJJN = 1985229328;
		CCFJELJJBPD = -19088744;
		OCNHMOBFIKJ = -1985229329;
		HKHGOKHCEGC = 19088743;
		ABBPDEOGNFE = 0;
		for (int i = 0; i != CBPFFIBINEH.Length; i++)
		{
			CBPFFIBINEH[i] = 0;
		}
	}

	private int CKFFNPFNMMM(int AMFCENFNAJJ, int IDHLPOFDLKJ)
	{
		return (AMFCENFNAJJ << IDHLPOFDLKJ) | (int)((uint)AMFCENFNAJJ >> 32 - IDHLPOFDLKJ);
	}

	private int HBFJAOFJIFP(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return AMFCENFNAJJ ^ CNLILOEEBOJ ^ IGNEOOOFEMO;
	}

	private int IKKGCFMJODC(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return (AMFCENFNAJJ & CNLILOEEBOJ) | (~AMFCENFNAJJ & IGNEOOOFEMO);
	}

	private int HJEBNCKAABK(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return (AMFCENFNAJJ | ~CNLILOEEBOJ) ^ IGNEOOOFEMO;
	}

	private int LJFNDAMNFAC(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return (AMFCENFNAJJ & IGNEOOOFEMO) | (CNLILOEEBOJ & ~IGNEOOOFEMO);
	}

	private int HBFJAOFJIFP(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + HBFJAOFJIFP(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ, IBBBMACIBGK);
	}

	private int IKKGCFMJODC(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + IKKGCFMJODC(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + 1518500249, IBBBMACIBGK);
	}

	private int HJEBNCKAABK(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + HJEBNCKAABK(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + 1859775393, IBBBMACIBGK);
	}

	private int LJFNDAMNFAC(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + LJFNDAMNFAC(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + -1894007588, IBBBMACIBGK);
	}

	private int NPCEFGPCCLG(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + HBFJAOFJIFP(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ, IBBBMACIBGK);
	}

	private int PNOFCEHBIDI(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + IKKGCFMJODC(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + 1836072691, IBBBMACIBGK);
	}

	private int MCFNGOIJBHD(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + HJEBNCKAABK(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + 1548603684, IBBBMACIBGK);
	}

	private int PPPBJLPMJPG(int MNIMEAMHNMI, int BCIHLCMFAEK, int FMFABAKPMLB, int ELNCCDELMMH, int AMFCENFNAJJ, int IBBBMACIBGK)
	{
		return CKFFNPFNMMM(MNIMEAMHNMI + LJFNDAMNFAC(BCIHLCMFAEK, FMFABAKPMLB, ELNCCDELMMH) + AMFCENFNAJJ + 1352829926, IBBBMACIBGK);
	}

	internal override void DPACJDFHLKB()
	{
		int oLFEOHKKGIP = OLFEOHKKGIP;
		int nAHACOBOKIM = NAHACOBOKIM;
		int mPNNHCHGEGL = MPNNHCHGEGL;
		int aJBHIPPAFIJ = AJBHIPPAFIJ;
		int gCLNAIGNJJN = GCLNAIGNJJN;
		int cCFJELJJBPD = CCFJELJJBPD;
		int oCNHMOBFIKJ = OCNHMOBFIKJ;
		int hKHGOKHCEGC = HKHGOKHCEGC;
		oLFEOHKKGIP = HBFJAOFJIFP(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[0], 11);
		aJBHIPPAFIJ = HBFJAOFJIFP(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[1], 14);
		mPNNHCHGEGL = HBFJAOFJIFP(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[2], 15);
		nAHACOBOKIM = HBFJAOFJIFP(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[3], 12);
		oLFEOHKKGIP = HBFJAOFJIFP(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[4], 5);
		aJBHIPPAFIJ = HBFJAOFJIFP(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[5], 8);
		mPNNHCHGEGL = HBFJAOFJIFP(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[6], 7);
		nAHACOBOKIM = HBFJAOFJIFP(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[7], 9);
		oLFEOHKKGIP = HBFJAOFJIFP(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[8], 11);
		aJBHIPPAFIJ = HBFJAOFJIFP(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[9], 13);
		mPNNHCHGEGL = HBFJAOFJIFP(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[10], 14);
		nAHACOBOKIM = HBFJAOFJIFP(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[11], 15);
		oLFEOHKKGIP = HBFJAOFJIFP(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[12], 6);
		aJBHIPPAFIJ = HBFJAOFJIFP(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[13], 7);
		mPNNHCHGEGL = HBFJAOFJIFP(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[14], 9);
		nAHACOBOKIM = HBFJAOFJIFP(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[15], 8);
		gCLNAIGNJJN = PPPBJLPMJPG(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[5], 8);
		hKHGOKHCEGC = PPPBJLPMJPG(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[14], 9);
		oCNHMOBFIKJ = PPPBJLPMJPG(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[7], 9);
		cCFJELJJBPD = PPPBJLPMJPG(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[0], 11);
		gCLNAIGNJJN = PPPBJLPMJPG(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[9], 13);
		hKHGOKHCEGC = PPPBJLPMJPG(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[2], 15);
		oCNHMOBFIKJ = PPPBJLPMJPG(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[11], 15);
		cCFJELJJBPD = PPPBJLPMJPG(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[4], 5);
		gCLNAIGNJJN = PPPBJLPMJPG(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[13], 7);
		hKHGOKHCEGC = PPPBJLPMJPG(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[6], 7);
		oCNHMOBFIKJ = PPPBJLPMJPG(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[15], 8);
		cCFJELJJBPD = PPPBJLPMJPG(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[8], 11);
		gCLNAIGNJJN = PPPBJLPMJPG(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[1], 14);
		hKHGOKHCEGC = PPPBJLPMJPG(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[10], 14);
		oCNHMOBFIKJ = PPPBJLPMJPG(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[3], 12);
		cCFJELJJBPD = PPPBJLPMJPG(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[12], 6);
		int num = oLFEOHKKGIP;
		oLFEOHKKGIP = gCLNAIGNJJN;
		gCLNAIGNJJN = num;
		oLFEOHKKGIP = IKKGCFMJODC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[7], 7);
		aJBHIPPAFIJ = IKKGCFMJODC(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[4], 6);
		mPNNHCHGEGL = IKKGCFMJODC(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[13], 8);
		nAHACOBOKIM = IKKGCFMJODC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[1], 13);
		oLFEOHKKGIP = IKKGCFMJODC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[10], 11);
		aJBHIPPAFIJ = IKKGCFMJODC(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[6], 9);
		mPNNHCHGEGL = IKKGCFMJODC(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[15], 7);
		nAHACOBOKIM = IKKGCFMJODC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[3], 15);
		oLFEOHKKGIP = IKKGCFMJODC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[12], 7);
		aJBHIPPAFIJ = IKKGCFMJODC(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[0], 12);
		mPNNHCHGEGL = IKKGCFMJODC(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[9], 15);
		nAHACOBOKIM = IKKGCFMJODC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[5], 9);
		oLFEOHKKGIP = IKKGCFMJODC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[2], 11);
		aJBHIPPAFIJ = IKKGCFMJODC(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[14], 7);
		mPNNHCHGEGL = IKKGCFMJODC(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[11], 13);
		nAHACOBOKIM = IKKGCFMJODC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[8], 12);
		gCLNAIGNJJN = MCFNGOIJBHD(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[6], 9);
		hKHGOKHCEGC = MCFNGOIJBHD(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[11], 13);
		oCNHMOBFIKJ = MCFNGOIJBHD(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[3], 15);
		cCFJELJJBPD = MCFNGOIJBHD(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[7], 7);
		gCLNAIGNJJN = MCFNGOIJBHD(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[0], 12);
		hKHGOKHCEGC = MCFNGOIJBHD(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[13], 8);
		oCNHMOBFIKJ = MCFNGOIJBHD(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[5], 9);
		cCFJELJJBPD = MCFNGOIJBHD(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[10], 11);
		gCLNAIGNJJN = MCFNGOIJBHD(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[14], 7);
		hKHGOKHCEGC = MCFNGOIJBHD(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[15], 7);
		oCNHMOBFIKJ = MCFNGOIJBHD(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[8], 12);
		cCFJELJJBPD = MCFNGOIJBHD(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[12], 7);
		gCLNAIGNJJN = MCFNGOIJBHD(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[4], 6);
		hKHGOKHCEGC = MCFNGOIJBHD(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[9], 15);
		oCNHMOBFIKJ = MCFNGOIJBHD(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[1], 13);
		cCFJELJJBPD = MCFNGOIJBHD(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[2], 11);
		num = nAHACOBOKIM;
		nAHACOBOKIM = cCFJELJJBPD;
		cCFJELJJBPD = num;
		oLFEOHKKGIP = HJEBNCKAABK(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[3], 11);
		aJBHIPPAFIJ = HJEBNCKAABK(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[10], 13);
		mPNNHCHGEGL = HJEBNCKAABK(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[14], 6);
		nAHACOBOKIM = HJEBNCKAABK(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[4], 7);
		oLFEOHKKGIP = HJEBNCKAABK(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[9], 14);
		aJBHIPPAFIJ = HJEBNCKAABK(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[15], 9);
		mPNNHCHGEGL = HJEBNCKAABK(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[8], 13);
		nAHACOBOKIM = HJEBNCKAABK(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[1], 15);
		oLFEOHKKGIP = HJEBNCKAABK(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[2], 14);
		aJBHIPPAFIJ = HJEBNCKAABK(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[7], 8);
		mPNNHCHGEGL = HJEBNCKAABK(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[0], 13);
		nAHACOBOKIM = HJEBNCKAABK(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[6], 6);
		oLFEOHKKGIP = HJEBNCKAABK(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[13], 5);
		aJBHIPPAFIJ = HJEBNCKAABK(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[11], 12);
		mPNNHCHGEGL = HJEBNCKAABK(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[5], 7);
		nAHACOBOKIM = HJEBNCKAABK(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[12], 5);
		gCLNAIGNJJN = PNOFCEHBIDI(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[15], 9);
		hKHGOKHCEGC = PNOFCEHBIDI(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[5], 7);
		oCNHMOBFIKJ = PNOFCEHBIDI(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[1], 15);
		cCFJELJJBPD = PNOFCEHBIDI(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[3], 11);
		gCLNAIGNJJN = PNOFCEHBIDI(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[7], 8);
		hKHGOKHCEGC = PNOFCEHBIDI(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[14], 6);
		oCNHMOBFIKJ = PNOFCEHBIDI(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[6], 6);
		cCFJELJJBPD = PNOFCEHBIDI(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[9], 14);
		gCLNAIGNJJN = PNOFCEHBIDI(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[11], 12);
		hKHGOKHCEGC = PNOFCEHBIDI(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[8], 13);
		oCNHMOBFIKJ = PNOFCEHBIDI(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[12], 5);
		cCFJELJJBPD = PNOFCEHBIDI(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[2], 14);
		gCLNAIGNJJN = PNOFCEHBIDI(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[10], 13);
		hKHGOKHCEGC = PNOFCEHBIDI(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[0], 13);
		oCNHMOBFIKJ = PNOFCEHBIDI(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[4], 7);
		cCFJELJJBPD = PNOFCEHBIDI(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[13], 5);
		num = mPNNHCHGEGL;
		mPNNHCHGEGL = oCNHMOBFIKJ;
		oCNHMOBFIKJ = num;
		oLFEOHKKGIP = LJFNDAMNFAC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[1], 11);
		aJBHIPPAFIJ = LJFNDAMNFAC(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[9], 12);
		mPNNHCHGEGL = LJFNDAMNFAC(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[11], 14);
		nAHACOBOKIM = LJFNDAMNFAC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[10], 15);
		oLFEOHKKGIP = LJFNDAMNFAC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[0], 14);
		aJBHIPPAFIJ = LJFNDAMNFAC(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[8], 15);
		mPNNHCHGEGL = LJFNDAMNFAC(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[12], 9);
		nAHACOBOKIM = LJFNDAMNFAC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[4], 8);
		oLFEOHKKGIP = LJFNDAMNFAC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[13], 9);
		aJBHIPPAFIJ = LJFNDAMNFAC(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[3], 14);
		mPNNHCHGEGL = LJFNDAMNFAC(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[7], 5);
		nAHACOBOKIM = LJFNDAMNFAC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[15], 6);
		oLFEOHKKGIP = LJFNDAMNFAC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, CBPFFIBINEH[14], 8);
		aJBHIPPAFIJ = LJFNDAMNFAC(aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL, CBPFFIBINEH[5], 6);
		mPNNHCHGEGL = LJFNDAMNFAC(mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, nAHACOBOKIM, CBPFFIBINEH[6], 5);
		nAHACOBOKIM = LJFNDAMNFAC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ, oLFEOHKKGIP, CBPFFIBINEH[2], 12);
		gCLNAIGNJJN = NPCEFGPCCLG(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[8], 15);
		hKHGOKHCEGC = NPCEFGPCCLG(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[6], 5);
		oCNHMOBFIKJ = NPCEFGPCCLG(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[4], 8);
		cCFJELJJBPD = NPCEFGPCCLG(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[1], 11);
		gCLNAIGNJJN = NPCEFGPCCLG(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[3], 14);
		hKHGOKHCEGC = NPCEFGPCCLG(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[11], 14);
		oCNHMOBFIKJ = NPCEFGPCCLG(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[15], 6);
		cCFJELJJBPD = NPCEFGPCCLG(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[0], 14);
		gCLNAIGNJJN = NPCEFGPCCLG(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[5], 6);
		hKHGOKHCEGC = NPCEFGPCCLG(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[12], 9);
		oCNHMOBFIKJ = NPCEFGPCCLG(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[2], 12);
		cCFJELJJBPD = NPCEFGPCCLG(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[13], 9);
		gCLNAIGNJJN = NPCEFGPCCLG(gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, CBPFFIBINEH[9], 12);
		hKHGOKHCEGC = NPCEFGPCCLG(hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, oCNHMOBFIKJ, CBPFFIBINEH[7], 5);
		oCNHMOBFIKJ = NPCEFGPCCLG(oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, cCFJELJJBPD, CBPFFIBINEH[10], 15);
		cCFJELJJBPD = NPCEFGPCCLG(cCFJELJJBPD, oCNHMOBFIKJ, hKHGOKHCEGC, gCLNAIGNJJN, CBPFFIBINEH[14], 8);
		num = aJBHIPPAFIJ;
		aJBHIPPAFIJ = hKHGOKHCEGC;
		hKHGOKHCEGC = num;
		OLFEOHKKGIP += oLFEOHKKGIP;
		NAHACOBOKIM += nAHACOBOKIM;
		MPNNHCHGEGL += mPNNHCHGEGL;
		AJBHIPPAFIJ += aJBHIPPAFIJ;
		GCLNAIGNJJN += gCLNAIGNJJN;
		CCFJELJJBPD += cCFJELJJBPD;
		OCNHMOBFIKJ += oCNHMOBFIKJ;
		HKHGOKHCEGC += hKHGOKHCEGC;
		ABBPDEOGNFE = 0;
		for (int i = 0; i != CBPFFIBINEH.Length; i++)
		{
			CBPFFIBINEH[i] = 0;
		}
	}

	public override MIPBJNJHNGA FDCFKGAEJFF()
	{
		return new KDOKNEONHOF(this);
	}

	public override void OMOKOKFNBKI(MIPBJNJHNGA CJHEIBNHNNE)
	{
		KDOKNEONHOF lLIEHCKNJEM = (KDOKNEONHOF)CJHEIBNHNNE;
		AKBPCECABIO(lLIEHCKNJEM);
	}
}
