using System;
using Org.BouncyCastle.Math;

public class KEBOFNHLGOE : KLOGJEJCNNM
{
	protected readonly BHPIABAGAPB NINILENHPHE;

	protected readonly BBIBEHOGPHK OFPNAHJEAMN;

	public KEBOFNHLGOE(BHPIABAGAPB NINILENHPHE, BBIBEHOGPHK OFPNAHJEAMN)
	{
		if (NINILENHPHE == null || NINILENHPHE.BHIJCAOHDCM == null)
		{
			throw new ArgumentException("Need curve with known group order", "curve");
		}
		this.NINILENHPHE = NINILENHPHE;
		this.OFPNAHJEAMN = OFPNAHJEAMN;
	}

	protected override JGAFKLGGBGF OJGDKAJCDJK(JGAFKLGGBGF HPHBDNBJPHB, BigInteger BENKLGPHLGI)
	{
		if (!NINILENHPHE.KIFDKLPDKMD(HPHBDNBJPHB.ECFGFKNLLGH))
		{
			throw new InvalidOperationException();
		}
		BigInteger cEKMAJAHNAG = HPHBDNBJPHB.ECFGFKNLLGH.BHIJCAOHDCM;
		BigInteger[] array = OFPNAHJEAMN.MCNKLDGABBN(BENKLGPHLGI.MODIHOCEKBK(cEKMAJAHNAG));
		BigInteger bENKLGPHLGI = array[0];
		BigInteger pHILIHLPDFD = array[1];
		LFADADGHPPC lFADADGHPPC = OFPNAHJEAMN.ABJHMAEGCCD;
		if (OFPNAHJEAMN.KGPNOBKADCP)
		{
			return KHJLHEJBLOA.BNDHMAOGOOI(HPHBDNBJPHB, bENKLGPHLGI, lFADADGHPPC, pHILIHLPDFD);
		}
		return KHJLHEJBLOA.BNDHMAOGOOI(HPHBDNBJPHB, bENKLGPHLGI, lFADADGHPPC.FBDFAFGCDIO(HPHBDNBJPHB), pHILIHLPDFD);
	}
}
