using System;
using Org.BouncyCastle.Math;

public class KGHPPAOAMAH : OMOBJNLGOBO
{
	public KGHPPAOAMAH(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public KGHPPAOAMAH(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal KGHPPAOAMAH(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new KGHPPAOAMAH(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override KBINBLGGLNE NOIPJPPAFOH(int EHJNMODJEAN)
	{
		if (EHJNMODJEAN == 1 && FMBBJLCHHDI == 4)
		{
			return EIOKKHLHIEC();
		}
		return base.NOIPJPPAFOH(EHJNMODJEAN);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		int num = bHPIABAGAPB.DHBHKHGFIKI;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE3 = BCIHLCMFAEK.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE4 = BCIHLCMFAEK.FIJLKLCHMGH;
		switch (num)
		{
		case 0:
		{
			KBINBLGGLNE kBINBLGGLNE36 = kBINBLGGLNE3.FBGIHKPECCO(kBINBLGGLNE);
			KBINBLGGLNE kBINBLGGLNE37 = kBINBLGGLNE4.FBGIHKPECCO(kBINBLGGLNE2);
			if (kBINBLGGLNE36.EJJHHCOFAAI)
			{
				if (kBINBLGGLNE37.EJJHHCOFAAI)
				{
					return LLGLJBDLBOP();
				}
				return ECFGFKNLLGH.EFOLNCNGADB;
			}
			KBINBLGGLNE kBINBLGGLNE38 = kBINBLGGLNE37.MCPDGENJCDB(kBINBLGGLNE36);
			KBINBLGGLNE kBINBLGGLNE39 = kBINBLGGLNE38.MIOEHGDPGAG().FBGIHKPECCO(kBINBLGGLNE).FBGIHKPECCO(kBINBLGGLNE3);
			KBINBLGGLNE cNLILOEEBOJ3 = kBINBLGGLNE38.IBJBIGNPNEM(kBINBLGGLNE.FBGIHKPECCO(kBINBLGGLNE39)).FBGIHKPECCO(kBINBLGGLNE2);
			return new KGHPPAOAMAH(ECFGFKNLLGH, kBINBLGGLNE39, cNLILOEEBOJ3, base.BPGGHHMMCCB);
		}
		case 1:
		{
			KBINBLGGLNE kBINBLGGLNE25 = base.LAMGGDKLPJH[0];
			KBINBLGGLNE kBINBLGGLNE26 = BCIHLCMFAEK.LAMGGDKLPJH[0];
			bool flag3 = kBINBLGGLNE25.EOJCHPEGABD;
			bool flag4 = kBINBLGGLNE26.EOJCHPEGABD;
			KBINBLGGLNE kBINBLGGLNE27 = ((!flag3) ? kBINBLGGLNE4.IBJBIGNPNEM(kBINBLGGLNE25) : kBINBLGGLNE4);
			KBINBLGGLNE kBINBLGGLNE28 = ((!flag4) ? kBINBLGGLNE2.IBJBIGNPNEM(kBINBLGGLNE26) : kBINBLGGLNE2);
			KBINBLGGLNE kBINBLGGLNE29 = kBINBLGGLNE27.FBGIHKPECCO(kBINBLGGLNE28);
			KBINBLGGLNE kBINBLGGLNE30 = ((!flag3) ? kBINBLGGLNE3.IBJBIGNPNEM(kBINBLGGLNE25) : kBINBLGGLNE3);
			KBINBLGGLNE bCIHLCMFAEK5 = ((!flag4) ? kBINBLGGLNE.IBJBIGNPNEM(kBINBLGGLNE26) : kBINBLGGLNE);
			KBINBLGGLNE kBINBLGGLNE31 = kBINBLGGLNE30.FBGIHKPECCO(bCIHLCMFAEK5);
			if (kBINBLGGLNE31.EJJHHCOFAAI)
			{
				if (kBINBLGGLNE29.EJJHHCOFAAI)
				{
					return LLGLJBDLBOP();
				}
				return bHPIABAGAPB.EFOLNCNGADB;
			}
			KBINBLGGLNE bCIHLCMFAEK6 = (flag3 ? kBINBLGGLNE26 : ((!flag4) ? kBINBLGGLNE25.IBJBIGNPNEM(kBINBLGGLNE26) : kBINBLGGLNE25));
			KBINBLGGLNE kBINBLGGLNE32 = kBINBLGGLNE31.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE33 = kBINBLGGLNE32.IBJBIGNPNEM(kBINBLGGLNE31);
			KBINBLGGLNE kBINBLGGLNE34 = kBINBLGGLNE32.IBJBIGNPNEM(bCIHLCMFAEK5);
			KBINBLGGLNE bCIHLCMFAEK7 = kBINBLGGLNE29.MIOEHGDPGAG().IBJBIGNPNEM(bCIHLCMFAEK6).FBGIHKPECCO(kBINBLGGLNE33)
				.FBGIHKPECCO(HKBDJCAOANH(kBINBLGGLNE34));
			KBINBLGGLNE aMFCENFNAJJ = kBINBLGGLNE31.IBJBIGNPNEM(bCIHLCMFAEK7);
			KBINBLGGLNE cNLILOEEBOJ2 = kBINBLGGLNE34.FBGIHKPECCO(bCIHLCMFAEK7).MEBMJLIHOEJ(kBINBLGGLNE29, kBINBLGGLNE28, kBINBLGGLNE33);
			KBINBLGGLNE kBINBLGGLNE35 = kBINBLGGLNE33.IBJBIGNPNEM(bCIHLCMFAEK6);
			return new KGHPPAOAMAH(bHPIABAGAPB, aMFCENFNAJJ, cNLILOEEBOJ2, new KBINBLGGLNE[1] { kBINBLGGLNE35 }, base.BPGGHHMMCCB);
		}
		case 2:
		case 4:
		{
			KBINBLGGLNE kBINBLGGLNE5 = base.LAMGGDKLPJH[0];
			KBINBLGGLNE kBINBLGGLNE6 = BCIHLCMFAEK.LAMGGDKLPJH[0];
			bool flag = kBINBLGGLNE5.EOJCHPEGABD;
			KBINBLGGLNE pIBCPKOKPGO = null;
			KBINBLGGLNE kBINBLGGLNE11;
			KBINBLGGLNE cNLILOEEBOJ;
			KBINBLGGLNE kBINBLGGLNE12;
			if (!flag && kBINBLGGLNE5.KIFDKLPDKMD(kBINBLGGLNE6))
			{
				KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE.FBGIHKPECCO(kBINBLGGLNE3);
				KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE2.FBGIHKPECCO(kBINBLGGLNE4);
				if (kBINBLGGLNE7.EJJHHCOFAAI)
				{
					if (kBINBLGGLNE8.EJJHHCOFAAI)
					{
						return LLGLJBDLBOP();
					}
					return bHPIABAGAPB.EFOLNCNGADB;
				}
				KBINBLGGLNE kBINBLGGLNE9 = kBINBLGGLNE7.MIOEHGDPGAG();
				KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE.IBJBIGNPNEM(kBINBLGGLNE9);
				KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE3.IBJBIGNPNEM(kBINBLGGLNE9);
				KBINBLGGLNE bCIHLCMFAEK2 = kBINBLGGLNE10.FBGIHKPECCO(bCIHLCMFAEK).IBJBIGNPNEM(kBINBLGGLNE2);
				kBINBLGGLNE11 = kBINBLGGLNE8.MIOEHGDPGAG().FBGIHKPECCO(kBINBLGGLNE10).FBGIHKPECCO(bCIHLCMFAEK);
				cNLILOEEBOJ = kBINBLGGLNE10.FBGIHKPECCO(kBINBLGGLNE11).IBJBIGNPNEM(kBINBLGGLNE8).FBGIHKPECCO(bCIHLCMFAEK2);
				kBINBLGGLNE12 = kBINBLGGLNE7;
				if (flag)
				{
					pIBCPKOKPGO = kBINBLGGLNE9;
				}
				else
				{
					kBINBLGGLNE12 = kBINBLGGLNE12.IBJBIGNPNEM(kBINBLGGLNE5);
				}
			}
			else
			{
				KBINBLGGLNE bCIHLCMFAEK3;
				KBINBLGGLNE bCIHLCMFAEK4;
				if (flag)
				{
					KBINBLGGLNE kBINBLGGLNE13 = kBINBLGGLNE5;
					bCIHLCMFAEK3 = kBINBLGGLNE3;
					bCIHLCMFAEK4 = kBINBLGGLNE4;
				}
				else
				{
					KBINBLGGLNE kBINBLGGLNE13 = kBINBLGGLNE5.MIOEHGDPGAG();
					bCIHLCMFAEK3 = kBINBLGGLNE13.IBJBIGNPNEM(kBINBLGGLNE3);
					KBINBLGGLNE kBINBLGGLNE14 = kBINBLGGLNE13.IBJBIGNPNEM(kBINBLGGLNE5);
					bCIHLCMFAEK4 = kBINBLGGLNE14.IBJBIGNPNEM(kBINBLGGLNE4);
				}
				bool flag2 = kBINBLGGLNE6.EOJCHPEGABD;
				KBINBLGGLNE kBINBLGGLNE16;
				KBINBLGGLNE kBINBLGGLNE17;
				if (flag2)
				{
					KBINBLGGLNE kBINBLGGLNE15 = kBINBLGGLNE6;
					kBINBLGGLNE16 = kBINBLGGLNE;
					kBINBLGGLNE17 = kBINBLGGLNE2;
				}
				else
				{
					KBINBLGGLNE kBINBLGGLNE15 = kBINBLGGLNE6.MIOEHGDPGAG();
					kBINBLGGLNE16 = kBINBLGGLNE15.IBJBIGNPNEM(kBINBLGGLNE);
					KBINBLGGLNE kBINBLGGLNE18 = kBINBLGGLNE15.IBJBIGNPNEM(kBINBLGGLNE6);
					kBINBLGGLNE17 = kBINBLGGLNE18.IBJBIGNPNEM(kBINBLGGLNE2);
				}
				KBINBLGGLNE kBINBLGGLNE19 = kBINBLGGLNE16.FBGIHKPECCO(bCIHLCMFAEK3);
				KBINBLGGLNE kBINBLGGLNE20 = kBINBLGGLNE17.FBGIHKPECCO(bCIHLCMFAEK4);
				if (kBINBLGGLNE19.EJJHHCOFAAI)
				{
					if (kBINBLGGLNE20.EJJHHCOFAAI)
					{
						return LLGLJBDLBOP();
					}
					return bHPIABAGAPB.EFOLNCNGADB;
				}
				KBINBLGGLNE kBINBLGGLNE21 = kBINBLGGLNE19.MIOEHGDPGAG();
				KBINBLGGLNE kBINBLGGLNE22 = kBINBLGGLNE21.IBJBIGNPNEM(kBINBLGGLNE19);
				KBINBLGGLNE kBINBLGGLNE23 = kBINBLGGLNE21.IBJBIGNPNEM(kBINBLGGLNE16);
				kBINBLGGLNE11 = kBINBLGGLNE20.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE22).FBGIHKPECCO(HKBDJCAOANH(kBINBLGGLNE23));
				cNLILOEEBOJ = kBINBLGGLNE23.FBGIHKPECCO(kBINBLGGLNE11).MEBMJLIHOEJ(kBINBLGGLNE20, kBINBLGGLNE22, kBINBLGGLNE17);
				kBINBLGGLNE12 = kBINBLGGLNE19;
				if (!flag)
				{
					kBINBLGGLNE12 = kBINBLGGLNE12.IBJBIGNPNEM(kBINBLGGLNE5);
				}
				if (!flag2)
				{
					kBINBLGGLNE12 = kBINBLGGLNE12.IBJBIGNPNEM(kBINBLGGLNE6);
				}
				if (kBINBLGGLNE12 == kBINBLGGLNE19)
				{
					pIBCPKOKPGO = kBINBLGGLNE21;
				}
			}
			KBINBLGGLNE[] iJGNIJAMCML;
			if (num == 4)
			{
				KBINBLGGLNE kBINBLGGLNE24 = GDIHGMBCMBE(kBINBLGGLNE12, pIBCPKOKPGO);
				iJGNIJAMCML = new KBINBLGGLNE[2] { kBINBLGGLNE12, kBINBLGGLNE24 };
			}
			else
			{
				iJGNIJAMCML = new KBINBLGGLNE[1] { kBINBLGGLNE12 };
			}
			return new KGHPPAOAMAH(bHPIABAGAPB, kBINBLGGLNE11, cNLILOEEBOJ, iJGNIJAMCML, base.BPGGHHMMCCB);
		}
		default:
			throw new InvalidOperationException("unsupported coordinate system");
		}
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		int num = bHPIABAGAPB.DHBHKHGFIKI;
		KBINBLGGLNE kBINBLGGLNE2 = base.NBPANDNEJGI;
		switch (num)
		{
		case 0:
		{
			KBINBLGGLNE aMFCENFNAJJ3 = kBINBLGGLNE2.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE13 = AMHLPAKMJNE(aMFCENFNAJJ3).JEACJNAKLDJ(ECFGFKNLLGH.JEHECJGFJEB).MCPDGENJCDB(HKBDJCAOANH(kBINBLGGLNE));
			KBINBLGGLNE kBINBLGGLNE14 = kBINBLGGLNE13.MIOEHGDPGAG().FBGIHKPECCO(HKBDJCAOANH(kBINBLGGLNE2));
			KBINBLGGLNE cNLILOEEBOJ2 = kBINBLGGLNE13.IBJBIGNPNEM(kBINBLGGLNE2.FBGIHKPECCO(kBINBLGGLNE14)).FBGIHKPECCO(kBINBLGGLNE);
			return new KGHPPAOAMAH(ECFGFKNLLGH, kBINBLGGLNE14, cNLILOEEBOJ2, base.BPGGHHMMCCB);
		}
		case 1:
		{
			KBINBLGGLNE kBINBLGGLNE15 = base.LAMGGDKLPJH[0];
			bool flag2 = kBINBLGGLNE15.EOJCHPEGABD;
			KBINBLGGLNE kBINBLGGLNE16 = bHPIABAGAPB.JEHECJGFJEB;
			if (!kBINBLGGLNE16.EJJHHCOFAAI && !flag2)
			{
				kBINBLGGLNE16 = kBINBLGGLNE16.IBJBIGNPNEM(kBINBLGGLNE15.MIOEHGDPGAG());
			}
			kBINBLGGLNE16 = kBINBLGGLNE16.JEACJNAKLDJ(AMHLPAKMJNE(kBINBLGGLNE2.MIOEHGDPGAG()));
			KBINBLGGLNE kBINBLGGLNE17 = ((!flag2) ? kBINBLGGLNE.IBJBIGNPNEM(kBINBLGGLNE15) : kBINBLGGLNE);
			KBINBLGGLNE kBINBLGGLNE18 = ((!flag2) ? kBINBLGGLNE17.IBJBIGNPNEM(kBINBLGGLNE) : kBINBLGGLNE.MIOEHGDPGAG());
			KBINBLGGLNE aMFCENFNAJJ4 = kBINBLGGLNE2.IBJBIGNPNEM(kBINBLGGLNE18);
			KBINBLGGLNE kBINBLGGLNE19 = KOCFKICEECI(aMFCENFNAJJ4);
			KBINBLGGLNE kBINBLGGLNE20 = kBINBLGGLNE16.MIOEHGDPGAG().FBGIHKPECCO(HKBDJCAOANH(kBINBLGGLNE19));
			KBINBLGGLNE kBINBLGGLNE21 = HKBDJCAOANH(kBINBLGGLNE17);
			KBINBLGGLNE aMFCENFNAJJ5 = kBINBLGGLNE20.IBJBIGNPNEM(kBINBLGGLNE21);
			KBINBLGGLNE kBINBLGGLNE22 = HKBDJCAOANH(kBINBLGGLNE18);
			KBINBLGGLNE cNLILOEEBOJ3 = kBINBLGGLNE19.FBGIHKPECCO(kBINBLGGLNE20).IBJBIGNPNEM(kBINBLGGLNE16).FBGIHKPECCO(HKBDJCAOANH(kBINBLGGLNE22.MIOEHGDPGAG()));
			KBINBLGGLNE aMFCENFNAJJ6 = ((!flag2) ? kBINBLGGLNE21.MIOEHGDPGAG() : HKBDJCAOANH(kBINBLGGLNE22));
			KBINBLGGLNE kBINBLGGLNE23 = HKBDJCAOANH(aMFCENFNAJJ6).IBJBIGNPNEM(kBINBLGGLNE17);
			return new KGHPPAOAMAH(bHPIABAGAPB, aMFCENFNAJJ5, cNLILOEEBOJ3, new KBINBLGGLNE[1] { kBINBLGGLNE23 }, base.BPGGHHMMCCB);
		}
		case 2:
		{
			KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
			bool flag = kBINBLGGLNE3.EOJCHPEGABD;
			KBINBLGGLNE kBINBLGGLNE4 = kBINBLGGLNE.MIOEHGDPGAG();
			KBINBLGGLNE aMFCENFNAJJ = kBINBLGGLNE4.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE5 = bHPIABAGAPB.JEHECJGFJEB;
			KBINBLGGLNE kBINBLGGLNE6 = kBINBLGGLNE5.BHKOFHMDACN();
			KBINBLGGLNE kBINBLGGLNE7;
			KBINBLGGLNE kBINBLGGLNE8;
			if (kBINBLGGLNE6.DOJBPIFPALJ().Equals(BigInteger.AGLOJCOAJIK(3L)))
			{
				KBINBLGGLNE bCIHLCMFAEK = ((!flag) ? kBINBLGGLNE3.MIOEHGDPGAG() : kBINBLGGLNE3);
				kBINBLGGLNE7 = AMHLPAKMJNE(kBINBLGGLNE2.JEACJNAKLDJ(bCIHLCMFAEK).IBJBIGNPNEM(kBINBLGGLNE2.FBGIHKPECCO(bCIHLCMFAEK)));
				kBINBLGGLNE8 = KOCFKICEECI(kBINBLGGLNE4.IBJBIGNPNEM(kBINBLGGLNE2));
			}
			else
			{
				KBINBLGGLNE aMFCENFNAJJ2 = kBINBLGGLNE2.MIOEHGDPGAG();
				kBINBLGGLNE7 = AMHLPAKMJNE(aMFCENFNAJJ2);
				if (flag)
				{
					kBINBLGGLNE7 = kBINBLGGLNE7.JEACJNAKLDJ(kBINBLGGLNE5);
				}
				else if (!kBINBLGGLNE5.EJJHHCOFAAI)
				{
					KBINBLGGLNE kBINBLGGLNE9 = ((!flag) ? kBINBLGGLNE3.MIOEHGDPGAG() : kBINBLGGLNE3);
					KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE9.MIOEHGDPGAG();
					kBINBLGGLNE7 = ((kBINBLGGLNE6.LBAGICKMJNP >= kBINBLGGLNE5.LBAGICKMJNP) ? kBINBLGGLNE7.JEACJNAKLDJ(kBINBLGGLNE10.IBJBIGNPNEM(kBINBLGGLNE5)) : kBINBLGGLNE7.FBGIHKPECCO(kBINBLGGLNE10.IBJBIGNPNEM(kBINBLGGLNE6)));
				}
				kBINBLGGLNE8 = KOCFKICEECI(kBINBLGGLNE2.IBJBIGNPNEM(kBINBLGGLNE4));
			}
			KBINBLGGLNE kBINBLGGLNE11 = kBINBLGGLNE7.MIOEHGDPGAG().FBGIHKPECCO(HKBDJCAOANH(kBINBLGGLNE8));
			KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE8.FBGIHKPECCO(kBINBLGGLNE11).IBJBIGNPNEM(kBINBLGGLNE7).FBGIHKPECCO(COOAFHOLHGF(aMFCENFNAJJ));
			KBINBLGGLNE kBINBLGGLNE12 = HKBDJCAOANH(kBINBLGGLNE);
			if (!flag)
			{
				kBINBLGGLNE12 = kBINBLGGLNE12.IBJBIGNPNEM(kBINBLGGLNE3);
			}
			return new KGHPPAOAMAH(bHPIABAGAPB, kBINBLGGLNE11, cNLILOEEBOJ, new KBINBLGGLNE[1] { kBINBLGGLNE12 }, base.BPGGHHMMCCB);
		}
		case 4:
			return MGBLBPAGEPC(true);
		default:
			throw new InvalidOperationException("unsupported coordinate system");
		}
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		switch (bHPIABAGAPB.DHBHKHGFIKI)
		{
		case 0:
		{
			KBINBLGGLNE kBINBLGGLNE2 = base.NBPANDNEJGI;
			KBINBLGGLNE kBINBLGGLNE3 = BCIHLCMFAEK.NBPANDNEJGI;
			KBINBLGGLNE kBINBLGGLNE4 = BCIHLCMFAEK.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE5 = kBINBLGGLNE3.FBGIHKPECCO(kBINBLGGLNE2);
			KBINBLGGLNE kBINBLGGLNE6 = kBINBLGGLNE4.FBGIHKPECCO(kBINBLGGLNE);
			if (kBINBLGGLNE5.EJJHHCOFAAI)
			{
				if (kBINBLGGLNE6.EJJHHCOFAAI)
				{
					return LFFNDDCHCMH();
				}
				return this;
			}
			KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE5.MIOEHGDPGAG();
			KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE6.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE7.IBJBIGNPNEM(HKBDJCAOANH(kBINBLGGLNE2).JEACJNAKLDJ(kBINBLGGLNE3)).FBGIHKPECCO(bCIHLCMFAEK);
			if (kBINBLGGLNE8.EJJHHCOFAAI)
			{
				return ECFGFKNLLGH.EFOLNCNGADB;
			}
			KBINBLGGLNE kBINBLGGLNE9 = kBINBLGGLNE8.IBJBIGNPNEM(kBINBLGGLNE5);
			KBINBLGGLNE bCIHLCMFAEK2 = kBINBLGGLNE9.LEIECFOMCNL();
			KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE8.IBJBIGNPNEM(bCIHLCMFAEK2).IBJBIGNPNEM(kBINBLGGLNE6);
			KBINBLGGLNE kBINBLGGLNE11 = HKBDJCAOANH(kBINBLGGLNE).IBJBIGNPNEM(kBINBLGGLNE7).IBJBIGNPNEM(kBINBLGGLNE5).IBJBIGNPNEM(bCIHLCMFAEK2)
				.FBGIHKPECCO(kBINBLGGLNE10);
			KBINBLGGLNE kBINBLGGLNE12 = kBINBLGGLNE11.FBGIHKPECCO(kBINBLGGLNE10).IBJBIGNPNEM(kBINBLGGLNE10.JEACJNAKLDJ(kBINBLGGLNE11)).JEACJNAKLDJ(kBINBLGGLNE3);
			KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE2.FBGIHKPECCO(kBINBLGGLNE12).IBJBIGNPNEM(kBINBLGGLNE11).FBGIHKPECCO(kBINBLGGLNE);
			return new KGHPPAOAMAH(ECFGFKNLLGH, kBINBLGGLNE12, cNLILOEEBOJ, base.BPGGHHMMCCB);
		}
		case 4:
			return MGBLBPAGEPC(false).JEACJNAKLDJ(BCIHLCMFAEK);
		default:
			return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
		}
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		switch (bHPIABAGAPB.DHBHKHGFIKI)
		{
		case 0:
		{
			KBINBLGGLNE kBINBLGGLNE2 = base.NBPANDNEJGI;
			KBINBLGGLNE kBINBLGGLNE3 = HKBDJCAOANH(kBINBLGGLNE);
			KBINBLGGLNE kBINBLGGLNE4 = kBINBLGGLNE3.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE5 = AMHLPAKMJNE(kBINBLGGLNE2.MIOEHGDPGAG()).JEACJNAKLDJ(ECFGFKNLLGH.JEHECJGFJEB);
			KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE5.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE6 = AMHLPAKMJNE(kBINBLGGLNE2).IBJBIGNPNEM(kBINBLGGLNE4).FBGIHKPECCO(bCIHLCMFAEK);
			if (kBINBLGGLNE6.EJJHHCOFAAI)
			{
				return ECFGFKNLLGH.EFOLNCNGADB;
			}
			KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE6.IBJBIGNPNEM(kBINBLGGLNE3);
			KBINBLGGLNE bCIHLCMFAEK2 = kBINBLGGLNE7.LEIECFOMCNL();
			KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE6.IBJBIGNPNEM(bCIHLCMFAEK2).IBJBIGNPNEM(kBINBLGGLNE5);
			KBINBLGGLNE kBINBLGGLNE9 = kBINBLGGLNE4.MIOEHGDPGAG().IBJBIGNPNEM(bCIHLCMFAEK2).FBGIHKPECCO(kBINBLGGLNE8);
			KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE9.FBGIHKPECCO(kBINBLGGLNE8).IBJBIGNPNEM(kBINBLGGLNE8.JEACJNAKLDJ(kBINBLGGLNE9)).JEACJNAKLDJ(kBINBLGGLNE2);
			KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE2.FBGIHKPECCO(kBINBLGGLNE10).IBJBIGNPNEM(kBINBLGGLNE9).FBGIHKPECCO(kBINBLGGLNE);
			return new KGHPPAOAMAH(ECFGFKNLLGH, kBINBLGGLNE10, cNLILOEEBOJ, base.BPGGHHMMCCB);
		}
		case 4:
			return MGBLBPAGEPC(false).JEACJNAKLDJ(this);
		default:
			return LLGLJBDLBOP().JEACJNAKLDJ(this);
		}
	}

	public override JGAFKLGGBGF BMHHHPFDNMA(int EKFOKNPODBK)
	{
		if (EKFOKNPODBK < 0)
		{
			throw new ArgumentException("cannot be negative", "e");
		}
		if (EKFOKNPODBK == 0 || base.IFCDKFANPBO)
		{
			return this;
		}
		if (EKFOKNPODBK == 1)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		int num = bHPIABAGAPB.DHBHKHGFIKI;
		KBINBLGGLNE kBINBLGGLNE2 = bHPIABAGAPB.JEHECJGFJEB;
		KBINBLGGLNE kBINBLGGLNE3 = base.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE4 = ((base.LAMGGDKLPJH.Length >= 1) ? base.LAMGGDKLPJH[0] : bHPIABAGAPB.HFENNGHNFLF(BigInteger.One));
		if (!kBINBLGGLNE4.EOJCHPEGABD)
		{
			switch (num)
			{
			case 1:
			{
				KBINBLGGLNE kBINBLGGLNE5 = kBINBLGGLNE4.MIOEHGDPGAG();
				kBINBLGGLNE3 = kBINBLGGLNE3.IBJBIGNPNEM(kBINBLGGLNE4);
				kBINBLGGLNE = kBINBLGGLNE.IBJBIGNPNEM(kBINBLGGLNE5);
				kBINBLGGLNE2 = GDIHGMBCMBE(kBINBLGGLNE4, kBINBLGGLNE5);
				break;
			}
			case 2:
				kBINBLGGLNE2 = GDIHGMBCMBE(kBINBLGGLNE4, null);
				break;
			case 4:
				kBINBLGGLNE2 = EIOKKHLHIEC();
				break;
			}
		}
		for (int i = 0; i < EKFOKNPODBK; i++)
		{
			if (kBINBLGGLNE.EJJHHCOFAAI)
			{
				return bHPIABAGAPB.EFOLNCNGADB;
			}
			KBINBLGGLNE aMFCENFNAJJ = kBINBLGGLNE3.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE6 = AMHLPAKMJNE(aMFCENFNAJJ);
			KBINBLGGLNE kBINBLGGLNE7 = HKBDJCAOANH(kBINBLGGLNE);
			KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE7.IBJBIGNPNEM(kBINBLGGLNE);
			KBINBLGGLNE kBINBLGGLNE9 = HKBDJCAOANH(kBINBLGGLNE3.IBJBIGNPNEM(kBINBLGGLNE8));
			KBINBLGGLNE aMFCENFNAJJ2 = kBINBLGGLNE8.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE10 = HKBDJCAOANH(aMFCENFNAJJ2);
			if (!kBINBLGGLNE2.EJJHHCOFAAI)
			{
				kBINBLGGLNE6 = kBINBLGGLNE6.JEACJNAKLDJ(kBINBLGGLNE2);
				kBINBLGGLNE2 = HKBDJCAOANH(kBINBLGGLNE10.IBJBIGNPNEM(kBINBLGGLNE2));
			}
			kBINBLGGLNE3 = kBINBLGGLNE6.MIOEHGDPGAG().FBGIHKPECCO(HKBDJCAOANH(kBINBLGGLNE9));
			kBINBLGGLNE = kBINBLGGLNE6.IBJBIGNPNEM(kBINBLGGLNE9.FBGIHKPECCO(kBINBLGGLNE3)).FBGIHKPECCO(kBINBLGGLNE10);
			kBINBLGGLNE4 = ((!kBINBLGGLNE4.EOJCHPEGABD) ? kBINBLGGLNE7.IBJBIGNPNEM(kBINBLGGLNE4) : kBINBLGGLNE7);
		}
		switch (num)
		{
		case 0:
		{
			KBINBLGGLNE kBINBLGGLNE11 = kBINBLGGLNE4.LEIECFOMCNL();
			KBINBLGGLNE kBINBLGGLNE12 = kBINBLGGLNE11.MIOEHGDPGAG();
			KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE12.IBJBIGNPNEM(kBINBLGGLNE11);
			return new KGHPPAOAMAH(bHPIABAGAPB, kBINBLGGLNE3.IBJBIGNPNEM(kBINBLGGLNE12), kBINBLGGLNE.IBJBIGNPNEM(bCIHLCMFAEK), base.BPGGHHMMCCB);
		}
		case 1:
			kBINBLGGLNE3 = kBINBLGGLNE3.IBJBIGNPNEM(kBINBLGGLNE4);
			kBINBLGGLNE4 = kBINBLGGLNE4.IBJBIGNPNEM(kBINBLGGLNE4.MIOEHGDPGAG());
			return new KGHPPAOAMAH(bHPIABAGAPB, kBINBLGGLNE3, kBINBLGGLNE, new KBINBLGGLNE[1] { kBINBLGGLNE4 }, base.BPGGHHMMCCB);
		case 2:
			return new KGHPPAOAMAH(bHPIABAGAPB, kBINBLGGLNE3, kBINBLGGLNE, new KBINBLGGLNE[1] { kBINBLGGLNE4 }, base.BPGGHHMMCCB);
		case 4:
			return new KGHPPAOAMAH(bHPIABAGAPB, kBINBLGGLNE3, kBINBLGGLNE, new KBINBLGGLNE[2] { kBINBLGGLNE4, kBINBLGGLNE2 }, base.BPGGHHMMCCB);
		default:
			throw new InvalidOperationException("unsupported coordinate system");
		}
	}

	protected virtual KBINBLGGLNE HKBDJCAOANH(KBINBLGGLNE AMFCENFNAJJ)
	{
		return AMFCENFNAJJ.JEACJNAKLDJ(AMFCENFNAJJ);
	}

	protected virtual KBINBLGGLNE AMHLPAKMJNE(KBINBLGGLNE AMFCENFNAJJ)
	{
		return HKBDJCAOANH(AMFCENFNAJJ).JEACJNAKLDJ(AMFCENFNAJJ);
	}

	protected virtual KBINBLGGLNE KOCFKICEECI(KBINBLGGLNE AMFCENFNAJJ)
	{
		return HKBDJCAOANH(HKBDJCAOANH(AMFCENFNAJJ));
	}

	protected virtual KBINBLGGLNE COOAFHOLHGF(KBINBLGGLNE AMFCENFNAJJ)
	{
		return KOCFKICEECI(HKBDJCAOANH(AMFCENFNAJJ));
	}

	protected virtual KBINBLGGLNE EFOJOGFAEPG(KBINBLGGLNE MNIMEAMHNMI, KBINBLGGLNE BCIHLCMFAEK, KBINBLGGLNE ELCLBCNGINB, KBINBLGGLNE BJEAPPFEBNO)
	{
		return MNIMEAMHNMI.JEACJNAKLDJ(BCIHLCMFAEK).MIOEHGDPGAG().FBGIHKPECCO(ELCLBCNGINB)
			.FBGIHKPECCO(BJEAPPFEBNO);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		if (bHPIABAGAPB.DHBHKHGFIKI != 0)
		{
			return new KGHPPAOAMAH(bHPIABAGAPB, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
		}
		return new KGHPPAOAMAH(bHPIABAGAPB, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.BPGGHHMMCCB);
	}

	protected virtual KBINBLGGLNE GDIHGMBCMBE(KBINBLGGLNE NMLDCCMBKAD, KBINBLGGLNE PIBCPKOKPGO)
	{
		KBINBLGGLNE kBINBLGGLNE = ECFGFKNLLGH.JEHECJGFJEB;
		if (kBINBLGGLNE.EJJHHCOFAAI || NMLDCCMBKAD.EOJCHPEGABD)
		{
			return kBINBLGGLNE;
		}
		if (PIBCPKOKPGO == null)
		{
			PIBCPKOKPGO = NMLDCCMBKAD.MIOEHGDPGAG();
		}
		KBINBLGGLNE kBINBLGGLNE2 = PIBCPKOKPGO.MIOEHGDPGAG();
		KBINBLGGLNE kBINBLGGLNE3 = kBINBLGGLNE.BHKOFHMDACN();
		if (kBINBLGGLNE3.LBAGICKMJNP < kBINBLGGLNE.LBAGICKMJNP)
		{
			return kBINBLGGLNE2.IBJBIGNPNEM(kBINBLGGLNE3).BHKOFHMDACN();
		}
		return kBINBLGGLNE2.IBJBIGNPNEM(kBINBLGGLNE);
	}

	protected virtual KBINBLGGLNE EIOKKHLHIEC()
	{
		KBINBLGGLNE[] array = base.LAMGGDKLPJH;
		KBINBLGGLNE kBINBLGGLNE = array[1];
		if (kBINBLGGLNE == null)
		{
			kBINBLGGLNE = (array[1] = GDIHGMBCMBE(array[0], null));
		}
		return kBINBLGGLNE;
	}

	protected virtual KGHPPAOAMAH MGBLBPAGEPC(bool OHBCHOJPLJE)
	{
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
		KBINBLGGLNE bCIHLCMFAEK = EIOKKHLHIEC();
		KBINBLGGLNE aMFCENFNAJJ = kBINBLGGLNE.MIOEHGDPGAG();
		KBINBLGGLNE kBINBLGGLNE4 = AMHLPAKMJNE(aMFCENFNAJJ).JEACJNAKLDJ(bCIHLCMFAEK);
		KBINBLGGLNE kBINBLGGLNE5 = HKBDJCAOANH(kBINBLGGLNE2);
		KBINBLGGLNE kBINBLGGLNE6 = kBINBLGGLNE5.IBJBIGNPNEM(kBINBLGGLNE2);
		KBINBLGGLNE kBINBLGGLNE7 = HKBDJCAOANH(kBINBLGGLNE.IBJBIGNPNEM(kBINBLGGLNE6));
		KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE4.MIOEHGDPGAG().FBGIHKPECCO(HKBDJCAOANH(kBINBLGGLNE7));
		KBINBLGGLNE aMFCENFNAJJ2 = kBINBLGGLNE6.MIOEHGDPGAG();
		KBINBLGGLNE kBINBLGGLNE9 = HKBDJCAOANH(aMFCENFNAJJ2);
		KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE4.IBJBIGNPNEM(kBINBLGGLNE7.FBGIHKPECCO(kBINBLGGLNE8)).FBGIHKPECCO(kBINBLGGLNE9);
		KBINBLGGLNE kBINBLGGLNE10 = ((!OHBCHOJPLJE) ? null : HKBDJCAOANH(kBINBLGGLNE9.IBJBIGNPNEM(bCIHLCMFAEK)));
		KBINBLGGLNE kBINBLGGLNE11 = ((!kBINBLGGLNE3.EOJCHPEGABD) ? kBINBLGGLNE5.IBJBIGNPNEM(kBINBLGGLNE3) : kBINBLGGLNE5);
		return new KGHPPAOAMAH(ECFGFKNLLGH, kBINBLGGLNE8, cNLILOEEBOJ, new KBINBLGGLNE[2] { kBINBLGGLNE11, kBINBLGGLNE10 }, base.BPGGHHMMCCB);
	}
}
