using System;

public class KHIEBIHIHJA : EEBNPONHKOK
{
	private const int IOCOCGHMNGB = 20;

	private int OLFEOHKKGIP;

	private int NAHACOBOKIM;

	private int MPNNHCHGEGL;

	private int AJBHIPPAFIJ;

	private int GCLNAIGNJJN;

	private int[] CBPFFIBINEH = new int[16];

	private int ABBPDEOGNFE;

	public override string KFKMEPMEBND
	{
		get
		{
			return "RIPEMD160";
		}
	}

	public KHIEBIHIHJA()
	{
		OMOKOKFNBKI();
	}

	public KHIEBIHIHJA(KHIEBIHIHJA LLIEHCKNJEM)
		: base(LLIEHCKNJEM)
	{
		AKBPCECABIO(LLIEHCKNJEM);
	}

	private void AKBPCECABIO(KHIEBIHIHJA LLIEHCKNJEM)
	{
		AKBPCECABIO((EEBNPONHKOK)LLIEHCKNJEM);
		OLFEOHKKGIP = LLIEHCKNJEM.OLFEOHKKGIP;
		NAHACOBOKIM = LLIEHCKNJEM.NAHACOBOKIM;
		MPNNHCHGEGL = LLIEHCKNJEM.MPNNHCHGEGL;
		AJBHIPPAFIJ = LLIEHCKNJEM.AJBHIPPAFIJ;
		GCLNAIGNJJN = LLIEHCKNJEM.GCLNAIGNJJN;
		Array.Copy(LLIEHCKNJEM.CBPFFIBINEH, 0, CBPFFIBINEH, 0, LLIEHCKNJEM.CBPFFIBINEH.Length);
		ABBPDEOGNFE = LLIEHCKNJEM.ABBPDEOGNFE;
	}

	public override int EEMLLAMENHO()
	{
		return 20;
	}

	internal override void ICKIHAABCPI(byte[] MOPCLEEGDFB, int ELICNEDIBGB)
	{
		CBPFFIBINEH[ABBPDEOGNFE++] = (MOPCLEEGDFB[ELICNEDIBGB] & 0xFF) | ((MOPCLEEGDFB[ELICNEDIBGB + 1] & 0xFF) << 8) | ((MOPCLEEGDFB[ELICNEDIBGB + 2] & 0xFF) << 16) | ((MOPCLEEGDFB[ELICNEDIBGB + 3] & 0xFF) << 24);
		if (ABBPDEOGNFE == 16)
		{
			DPACJDFHLKB();
		}
	}

	internal override void IIENDLEDGMC(long EAJFCEBGGIG)
	{
		if (ABBPDEOGNFE > 14)
		{
			DPACJDFHLKB();
		}
		CBPFFIBINEH[14] = (int)(EAJFCEBGGIG & 0xFFFFFFFFu);
		CBPFFIBINEH[15] = (int)((ulong)EAJFCEBGGIG >> 32);
	}

	private void DKLAJHNFBJM(int BKKMJAIKJAL, byte[] NGAGMIIBGKA, int EMAKNGBIFDC)
	{
		NGAGMIIBGKA[EMAKNGBIFDC] = (byte)BKKMJAIKJAL;
		NGAGMIIBGKA[EMAKNGBIFDC + 1] = (byte)((uint)BKKMJAIKJAL >> 8);
		NGAGMIIBGKA[EMAKNGBIFDC + 2] = (byte)((uint)BKKMJAIKJAL >> 16);
		NGAGMIIBGKA[EMAKNGBIFDC + 3] = (byte)((uint)BKKMJAIKJAL >> 24);
	}

	public override int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		OJILOEAPDCL();
		DKLAJHNFBJM(OLFEOHKKGIP, BILGCJNPJGJ, EMAKNGBIFDC);
		DKLAJHNFBJM(NAHACOBOKIM, BILGCJNPJGJ, EMAKNGBIFDC + 4);
		DKLAJHNFBJM(MPNNHCHGEGL, BILGCJNPJGJ, EMAKNGBIFDC + 8);
		DKLAJHNFBJM(AJBHIPPAFIJ, BILGCJNPJGJ, EMAKNGBIFDC + 12);
		DKLAJHNFBJM(GCLNAIGNJJN, BILGCJNPJGJ, EMAKNGBIFDC + 16);
		OMOKOKFNBKI();
		return 20;
	}

	public override void OMOKOKFNBKI()
	{
		base.OMOKOKFNBKI();
		OLFEOHKKGIP = 1732584193;
		NAHACOBOKIM = -271733879;
		MPNNHCHGEGL = -1732584194;
		AJBHIPPAFIJ = 271733878;
		GCLNAIGNJJN = -1009589776;
		ABBPDEOGNFE = 0;
		for (int i = 0; i != CBPFFIBINEH.Length; i++)
		{
			CBPFFIBINEH[i] = 0;
		}
	}

	private int CKFFNPFNMMM(int AMFCENFNAJJ, int IDHLPOFDLKJ)
	{
		return (AMFCENFNAJJ << IDHLPOFDLKJ) | (int)((uint)AMFCENFNAJJ >> 32 - IDHLPOFDLKJ);
	}

	private int HBFJAOFJIFP(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return AMFCENFNAJJ ^ CNLILOEEBOJ ^ IGNEOOOFEMO;
	}

	private int IKKGCFMJODC(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return (AMFCENFNAJJ & CNLILOEEBOJ) | (~AMFCENFNAJJ & IGNEOOOFEMO);
	}

	private int HJEBNCKAABK(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return (AMFCENFNAJJ | ~CNLILOEEBOJ) ^ IGNEOOOFEMO;
	}

	private int LJFNDAMNFAC(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return (AMFCENFNAJJ & IGNEOOOFEMO) | (CNLILOEEBOJ & ~IGNEOOOFEMO);
	}

	private int KFOODLNFADJ(int AMFCENFNAJJ, int CNLILOEEBOJ, int IGNEOOOFEMO)
	{
		return AMFCENFNAJJ ^ (CNLILOEEBOJ | ~IGNEOOOFEMO);
	}

	internal override void DPACJDFHLKB()
	{
		int oLFEOHKKGIP;
		int num = (oLFEOHKKGIP = OLFEOHKKGIP);
		int nAHACOBOKIM;
		int num2 = (nAHACOBOKIM = NAHACOBOKIM);
		int mPNNHCHGEGL;
		int num3 = (mPNNHCHGEGL = MPNNHCHGEGL);
		int aJBHIPPAFIJ;
		int num4 = (aJBHIPPAFIJ = AJBHIPPAFIJ);
		int gCLNAIGNJJN;
		int num5 = (gCLNAIGNJJN = GCLNAIGNJJN);
		num = CKFFNPFNMMM(num + HBFJAOFJIFP(num2, num3, num4) + CBPFFIBINEH[0], 11) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + HBFJAOFJIFP(num, num2, num3) + CBPFFIBINEH[1], 14) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + HBFJAOFJIFP(num5, num, num2) + CBPFFIBINEH[2], 15) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + HBFJAOFJIFP(num4, num5, num) + CBPFFIBINEH[3], 12) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + HBFJAOFJIFP(num3, num4, num5) + CBPFFIBINEH[4], 5) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + HBFJAOFJIFP(num2, num3, num4) + CBPFFIBINEH[5], 8) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + HBFJAOFJIFP(num, num2, num3) + CBPFFIBINEH[6], 7) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + HBFJAOFJIFP(num5, num, num2) + CBPFFIBINEH[7], 9) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + HBFJAOFJIFP(num4, num5, num) + CBPFFIBINEH[8], 11) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + HBFJAOFJIFP(num3, num4, num5) + CBPFFIBINEH[9], 13) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + HBFJAOFJIFP(num2, num3, num4) + CBPFFIBINEH[10], 14) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + HBFJAOFJIFP(num, num2, num3) + CBPFFIBINEH[11], 15) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + HBFJAOFJIFP(num5, num, num2) + CBPFFIBINEH[12], 6) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + HBFJAOFJIFP(num4, num5, num) + CBPFFIBINEH[13], 7) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + HBFJAOFJIFP(num3, num4, num5) + CBPFFIBINEH[14], 9) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + HBFJAOFJIFP(num2, num3, num4) + CBPFFIBINEH[15], 8) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + KFOODLNFADJ(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[5] + 1352829926, 8) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + KFOODLNFADJ(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[14] + 1352829926, 9) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + KFOODLNFADJ(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[7] + 1352829926, 9) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + KFOODLNFADJ(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[0] + 1352829926, 11) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + KFOODLNFADJ(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[9] + 1352829926, 13) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + KFOODLNFADJ(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[2] + 1352829926, 15) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + KFOODLNFADJ(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[11] + 1352829926, 15) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + KFOODLNFADJ(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[4] + 1352829926, 5) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + KFOODLNFADJ(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[13] + 1352829926, 7) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + KFOODLNFADJ(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[6] + 1352829926, 7) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + KFOODLNFADJ(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[15] + 1352829926, 8) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + KFOODLNFADJ(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[8] + 1352829926, 11) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + KFOODLNFADJ(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[1] + 1352829926, 14) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + KFOODLNFADJ(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[10] + 1352829926, 14) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + KFOODLNFADJ(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[3] + 1352829926, 12) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + KFOODLNFADJ(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[12] + 1352829926, 6) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		num5 = CKFFNPFNMMM(num5 + IKKGCFMJODC(num, num2, num3) + CBPFFIBINEH[7] + 1518500249, 7) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + IKKGCFMJODC(num5, num, num2) + CBPFFIBINEH[4] + 1518500249, 6) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + IKKGCFMJODC(num4, num5, num) + CBPFFIBINEH[13] + 1518500249, 8) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + IKKGCFMJODC(num3, num4, num5) + CBPFFIBINEH[1] + 1518500249, 13) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + IKKGCFMJODC(num2, num3, num4) + CBPFFIBINEH[10] + 1518500249, 11) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + IKKGCFMJODC(num, num2, num3) + CBPFFIBINEH[6] + 1518500249, 9) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + IKKGCFMJODC(num5, num, num2) + CBPFFIBINEH[15] + 1518500249, 7) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + IKKGCFMJODC(num4, num5, num) + CBPFFIBINEH[3] + 1518500249, 15) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + IKKGCFMJODC(num3, num4, num5) + CBPFFIBINEH[12] + 1518500249, 7) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + IKKGCFMJODC(num2, num3, num4) + CBPFFIBINEH[0] + 1518500249, 12) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + IKKGCFMJODC(num, num2, num3) + CBPFFIBINEH[9] + 1518500249, 15) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + IKKGCFMJODC(num5, num, num2) + CBPFFIBINEH[5] + 1518500249, 9) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + IKKGCFMJODC(num4, num5, num) + CBPFFIBINEH[2] + 1518500249, 11) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + IKKGCFMJODC(num3, num4, num5) + CBPFFIBINEH[14] + 1518500249, 7) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + IKKGCFMJODC(num2, num3, num4) + CBPFFIBINEH[11] + 1518500249, 13) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + IKKGCFMJODC(num, num2, num3) + CBPFFIBINEH[8] + 1518500249, 12) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + LJFNDAMNFAC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[6] + 1548603684, 9) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + LJFNDAMNFAC(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[11] + 1548603684, 13) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + LJFNDAMNFAC(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[3] + 1548603684, 15) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + LJFNDAMNFAC(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[7] + 1548603684, 7) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + LJFNDAMNFAC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[0] + 1548603684, 12) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + LJFNDAMNFAC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[13] + 1548603684, 8) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + LJFNDAMNFAC(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[5] + 1548603684, 9) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + LJFNDAMNFAC(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[10] + 1548603684, 11) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + LJFNDAMNFAC(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[14] + 1548603684, 7) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + LJFNDAMNFAC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[15] + 1548603684, 7) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + LJFNDAMNFAC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[8] + 1548603684, 12) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + LJFNDAMNFAC(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[12] + 1548603684, 7) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + LJFNDAMNFAC(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[4] + 1548603684, 6) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + LJFNDAMNFAC(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[9] + 1548603684, 15) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + LJFNDAMNFAC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[1] + 1548603684, 13) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + LJFNDAMNFAC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[2] + 1548603684, 11) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		num4 = CKFFNPFNMMM(num4 + HJEBNCKAABK(num5, num, num2) + CBPFFIBINEH[3] + 1859775393, 11) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + HJEBNCKAABK(num4, num5, num) + CBPFFIBINEH[10] + 1859775393, 13) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + HJEBNCKAABK(num3, num4, num5) + CBPFFIBINEH[14] + 1859775393, 6) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + HJEBNCKAABK(num2, num3, num4) + CBPFFIBINEH[4] + 1859775393, 7) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + HJEBNCKAABK(num, num2, num3) + CBPFFIBINEH[9] + 1859775393, 14) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + HJEBNCKAABK(num5, num, num2) + CBPFFIBINEH[15] + 1859775393, 9) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + HJEBNCKAABK(num4, num5, num) + CBPFFIBINEH[8] + 1859775393, 13) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + HJEBNCKAABK(num3, num4, num5) + CBPFFIBINEH[1] + 1859775393, 15) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + HJEBNCKAABK(num2, num3, num4) + CBPFFIBINEH[2] + 1859775393, 14) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + HJEBNCKAABK(num, num2, num3) + CBPFFIBINEH[7] + 1859775393, 8) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + HJEBNCKAABK(num5, num, num2) + CBPFFIBINEH[0] + 1859775393, 13) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + HJEBNCKAABK(num4, num5, num) + CBPFFIBINEH[6] + 1859775393, 6) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + HJEBNCKAABK(num3, num4, num5) + CBPFFIBINEH[13] + 1859775393, 5) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + HJEBNCKAABK(num2, num3, num4) + CBPFFIBINEH[11] + 1859775393, 12) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + HJEBNCKAABK(num, num2, num3) + CBPFFIBINEH[5] + 1859775393, 7) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + HJEBNCKAABK(num5, num, num2) + CBPFFIBINEH[12] + 1859775393, 5) + num3;
		num = CKFFNPFNMMM(num, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + HJEBNCKAABK(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[15] + 1836072691, 9) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + HJEBNCKAABK(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[5] + 1836072691, 7) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + HJEBNCKAABK(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[1] + 1836072691, 15) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + HJEBNCKAABK(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[3] + 1836072691, 11) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + HJEBNCKAABK(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[7] + 1836072691, 8) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + HJEBNCKAABK(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[14] + 1836072691, 6) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + HJEBNCKAABK(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[6] + 1836072691, 6) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + HJEBNCKAABK(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[9] + 1836072691, 14) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + HJEBNCKAABK(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[11] + 1836072691, 12) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + HJEBNCKAABK(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[8] + 1836072691, 13) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + HJEBNCKAABK(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[12] + 1836072691, 5) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + HJEBNCKAABK(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[2] + 1836072691, 14) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + HJEBNCKAABK(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[10] + 1836072691, 13) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + HJEBNCKAABK(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[0] + 1836072691, 13) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + HJEBNCKAABK(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[4] + 1836072691, 7) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + HJEBNCKAABK(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[13] + 1836072691, 5) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		num3 = CKFFNPFNMMM(num3 + LJFNDAMNFAC(num4, num5, num) + CBPFFIBINEH[1] + -1894007588, 11) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + LJFNDAMNFAC(num3, num4, num5) + CBPFFIBINEH[9] + -1894007588, 12) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + LJFNDAMNFAC(num2, num3, num4) + CBPFFIBINEH[11] + -1894007588, 14) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + LJFNDAMNFAC(num, num2, num3) + CBPFFIBINEH[10] + -1894007588, 15) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + LJFNDAMNFAC(num5, num, num2) + CBPFFIBINEH[0] + -1894007588, 14) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + LJFNDAMNFAC(num4, num5, num) + CBPFFIBINEH[8] + -1894007588, 15) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + LJFNDAMNFAC(num3, num4, num5) + CBPFFIBINEH[12] + -1894007588, 9) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + LJFNDAMNFAC(num2, num3, num4) + CBPFFIBINEH[4] + -1894007588, 8) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + LJFNDAMNFAC(num, num2, num3) + CBPFFIBINEH[13] + -1894007588, 9) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + LJFNDAMNFAC(num5, num, num2) + CBPFFIBINEH[3] + -1894007588, 14) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + LJFNDAMNFAC(num4, num5, num) + CBPFFIBINEH[7] + -1894007588, 5) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + LJFNDAMNFAC(num3, num4, num5) + CBPFFIBINEH[15] + -1894007588, 6) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + LJFNDAMNFAC(num2, num3, num4) + CBPFFIBINEH[14] + -1894007588, 8) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + LJFNDAMNFAC(num, num2, num3) + CBPFFIBINEH[5] + -1894007588, 6) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + LJFNDAMNFAC(num5, num, num2) + CBPFFIBINEH[6] + -1894007588, 5) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + LJFNDAMNFAC(num4, num5, num) + CBPFFIBINEH[2] + -1894007588, 12) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + IKKGCFMJODC(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[8] + 2053994217, 15) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + IKKGCFMJODC(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[6] + 2053994217, 5) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + IKKGCFMJODC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[4] + 2053994217, 8) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + IKKGCFMJODC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[1] + 2053994217, 11) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + IKKGCFMJODC(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[3] + 2053994217, 14) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + IKKGCFMJODC(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[11] + 2053994217, 14) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + IKKGCFMJODC(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[15] + 2053994217, 6) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + IKKGCFMJODC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[0] + 2053994217, 14) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + IKKGCFMJODC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[5] + 2053994217, 6) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + IKKGCFMJODC(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[12] + 2053994217, 9) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + IKKGCFMJODC(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[2] + 2053994217, 12) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + IKKGCFMJODC(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[13] + 2053994217, 9) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + IKKGCFMJODC(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[9] + 2053994217, 12) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + IKKGCFMJODC(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[7] + 2053994217, 5) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + IKKGCFMJODC(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[10] + 2053994217, 15) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + IKKGCFMJODC(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[14] + 2053994217, 8) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		num2 = CKFFNPFNMMM(num2 + KFOODLNFADJ(num3, num4, num5) + CBPFFIBINEH[4] + -1454113458, 9) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + KFOODLNFADJ(num2, num3, num4) + CBPFFIBINEH[0] + -1454113458, 15) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + KFOODLNFADJ(num, num2, num3) + CBPFFIBINEH[5] + -1454113458, 5) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + KFOODLNFADJ(num5, num, num2) + CBPFFIBINEH[9] + -1454113458, 11) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + KFOODLNFADJ(num4, num5, num) + CBPFFIBINEH[7] + -1454113458, 6) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + KFOODLNFADJ(num3, num4, num5) + CBPFFIBINEH[12] + -1454113458, 8) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + KFOODLNFADJ(num2, num3, num4) + CBPFFIBINEH[2] + -1454113458, 13) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + KFOODLNFADJ(num, num2, num3) + CBPFFIBINEH[10] + -1454113458, 12) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + KFOODLNFADJ(num5, num, num2) + CBPFFIBINEH[14] + -1454113458, 5) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + KFOODLNFADJ(num4, num5, num) + CBPFFIBINEH[1] + -1454113458, 12) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + KFOODLNFADJ(num3, num4, num5) + CBPFFIBINEH[3] + -1454113458, 13) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		num = CKFFNPFNMMM(num + KFOODLNFADJ(num2, num3, num4) + CBPFFIBINEH[8] + -1454113458, 14) + num5;
		num3 = CKFFNPFNMMM(num3, 10);
		num5 = CKFFNPFNMMM(num5 + KFOODLNFADJ(num, num2, num3) + CBPFFIBINEH[11] + -1454113458, 11) + num4;
		num2 = CKFFNPFNMMM(num2, 10);
		num4 = CKFFNPFNMMM(num4 + KFOODLNFADJ(num5, num, num2) + CBPFFIBINEH[6] + -1454113458, 8) + num3;
		num = CKFFNPFNMMM(num, 10);
		num3 = CKFFNPFNMMM(num3 + KFOODLNFADJ(num4, num5, num) + CBPFFIBINEH[15] + -1454113458, 5) + num2;
		num5 = CKFFNPFNMMM(num5, 10);
		num2 = CKFFNPFNMMM(num2 + KFOODLNFADJ(num3, num4, num5) + CBPFFIBINEH[13] + -1454113458, 6) + num;
		num4 = CKFFNPFNMMM(num4, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + HBFJAOFJIFP(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[12], 8) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + HBFJAOFJIFP(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[15], 5) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + HBFJAOFJIFP(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[10], 12) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + HBFJAOFJIFP(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[4], 9) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + HBFJAOFJIFP(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[1], 12) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + HBFJAOFJIFP(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[5], 5) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + HBFJAOFJIFP(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[8], 14) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + HBFJAOFJIFP(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[7], 6) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + HBFJAOFJIFP(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[6], 8) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + HBFJAOFJIFP(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[2], 13) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + HBFJAOFJIFP(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[13], 6) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP + HBFJAOFJIFP(nAHACOBOKIM, mPNNHCHGEGL, aJBHIPPAFIJ) + CBPFFIBINEH[14], 5) + gCLNAIGNJJN;
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL, 10);
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN + HBFJAOFJIFP(oLFEOHKKGIP, nAHACOBOKIM, mPNNHCHGEGL) + CBPFFIBINEH[0], 15) + aJBHIPPAFIJ;
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM, 10);
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ + HBFJAOFJIFP(gCLNAIGNJJN, oLFEOHKKGIP, nAHACOBOKIM) + CBPFFIBINEH[3], 13) + mPNNHCHGEGL;
		oLFEOHKKGIP = CKFFNPFNMMM(oLFEOHKKGIP, 10);
		mPNNHCHGEGL = CKFFNPFNMMM(mPNNHCHGEGL + HBFJAOFJIFP(aJBHIPPAFIJ, gCLNAIGNJJN, oLFEOHKKGIP) + CBPFFIBINEH[9], 11) + nAHACOBOKIM;
		gCLNAIGNJJN = CKFFNPFNMMM(gCLNAIGNJJN, 10);
		nAHACOBOKIM = CKFFNPFNMMM(nAHACOBOKIM + HBFJAOFJIFP(mPNNHCHGEGL, aJBHIPPAFIJ, gCLNAIGNJJN) + CBPFFIBINEH[11], 11) + oLFEOHKKGIP;
		aJBHIPPAFIJ = CKFFNPFNMMM(aJBHIPPAFIJ, 10);
		aJBHIPPAFIJ += num3 + NAHACOBOKIM;
		NAHACOBOKIM = MPNNHCHGEGL + num4 + gCLNAIGNJJN;
		MPNNHCHGEGL = AJBHIPPAFIJ + num5 + oLFEOHKKGIP;
		AJBHIPPAFIJ = GCLNAIGNJJN + num + nAHACOBOKIM;
		GCLNAIGNJJN = OLFEOHKKGIP + num2 + mPNNHCHGEGL;
		OLFEOHKKGIP = aJBHIPPAFIJ;
		ABBPDEOGNFE = 0;
		for (int i = 0; i != CBPFFIBINEH.Length; i++)
		{
			CBPFFIBINEH[i] = 0;
		}
	}

	public override MIPBJNJHNGA FDCFKGAEJFF()
	{
		return new KHIEBIHIHJA(this);
	}

	public override void OMOKOKFNBKI(MIPBJNJHNGA CJHEIBNHNNE)
	{
		KHIEBIHIHJA lLIEHCKNJEM = (KHIEBIHIHJA)CJHEIBNHNNE;
		AKBPCECABIO(lLIEHCKNJEM);
	}
}
