using System;
using Org.BouncyCastle.Math;

public class KHJLHEJBLOA
{
	public static bool BDGICGJIGPF(BHPIABAGAPB FMFABAKPMLB)
	{
		return PFINHOCLJBC(FMFABAKPMLB.LLHBLBINBOA);
	}

	public static bool PFINHOCLJBC(AGBPCEHDLOH FCHMGNNHJAN)
	{
		return FCHMGNNHJAN.BABIEELHGOK > 1 && FCHMGNNHJAN.HJKCMCLHBEN.Equals(BigInteger.Two) && FCHMGNNHJAN is AIGKJBLDPNN;
	}

	public static bool FNAAANIPFOP(BHPIABAGAPB FMFABAKPMLB)
	{
		return GEOKCNOKBFE(FMFABAKPMLB.LLHBLBINBOA);
	}

	public static bool GEOKCNOKBFE(AGBPCEHDLOH FCHMGNNHJAN)
	{
		return FCHMGNNHJAN.BABIEELHGOK == 1;
	}

	public static JGAFKLGGBGF HPJNKPEGDJI(JGAFKLGGBGF[] FLLHHHDFCKA, BigInteger[] APIJJGNJKNF)
	{
		if (FLLHHHDFCKA == null || APIJJGNJKNF == null || FLLHHHDFCKA.Length != APIJJGNJKNF.Length || FLLHHHDFCKA.Length < 1)
		{
			throw new ArgumentException("point and scalar arrays should be non-null, and of equal, non-zero, length");
		}
		int num = FLLHHHDFCKA.Length;
		switch (num)
		{
		case 1:
			return FLLHHHDFCKA[0].IBJBIGNPNEM(APIJJGNJKNF[0]);
		case 2:
			return PCCKCCDMHGL(FLLHHHDFCKA[0], APIJJGNJKNF[0], FLLHHHDFCKA[1], APIJJGNJKNF[1]);
		default:
		{
			JGAFKLGGBGF jGAFKLGGBGF = FLLHHHDFCKA[0];
			BHPIABAGAPB bHPIABAGAPB = jGAFKLGGBGF.ECFGFKNLLGH;
			JGAFKLGGBGF[] array = new JGAFKLGGBGF[num];
			array[0] = jGAFKLGGBGF;
			for (int i = 1; i < num; i++)
			{
				array[i] = PHDNPDCNJJA(bHPIABAGAPB, FLLHHHDFCKA[i]);
			}
			BBIBEHOGPHK bBIBEHOGPHK = bHPIABAGAPB.JHKAENBDIGO() as BBIBEHOGPHK;
			if (bBIBEHOGPHK != null)
			{
				return BOHLCKHAGJO(KMFEKKHNEON(array, APIJJGNJKNF, bBIBEHOGPHK));
			}
			return BOHLCKHAGJO(NGFMCHCDBBC(array, APIJJGNJKNF));
		}
		}
	}

	public static JGAFKLGGBGF PCCKCCDMHGL(JGAFKLGGBGF MBIJHANOCOC, BigInteger MNIMEAMHNMI, JGAFKLGGBGF FNPELDEHJKL, BigInteger BCIHLCMFAEK)
	{
		BHPIABAGAPB bHPIABAGAPB = MBIJHANOCOC.ECFGFKNLLGH;
		FNPELDEHJKL = PHDNPDCNJJA(bHPIABAGAPB, FNPELDEHJKL);
		DJABAMMOHPF dJABAMMOHPF = bHPIABAGAPB as DJABAMMOHPF;
		if (dJABAMMOHPF != null && dJABAMMOHPF.FNJONABMLNB)
		{
			return BOHLCKHAGJO(MBIJHANOCOC.IBJBIGNPNEM(MNIMEAMHNMI).JEACJNAKLDJ(FNPELDEHJKL.IBJBIGNPNEM(BCIHLCMFAEK)));
		}
		BBIBEHOGPHK bBIBEHOGPHK = bHPIABAGAPB.JHKAENBDIGO() as BBIBEHOGPHK;
		if (bBIBEHOGPHK != null)
		{
			return BOHLCKHAGJO(KMFEKKHNEON(new JGAFKLGGBGF[2] { MBIJHANOCOC, FNPELDEHJKL }, new BigInteger[2] { MNIMEAMHNMI, BCIHLCMFAEK }, bBIBEHOGPHK));
		}
		return BOHLCKHAGJO(BNDHMAOGOOI(MBIJHANOCOC, MNIMEAMHNMI, FNPELDEHJKL, BCIHLCMFAEK));
	}

	public static JGAFKLGGBGF MHFCPLAGGFM(JGAFKLGGBGF MBIJHANOCOC, BigInteger BENKLGPHLGI, JGAFKLGGBGF FNPELDEHJKL, BigInteger PHILIHLPDFD)
	{
		BHPIABAGAPB fMFABAKPMLB = MBIJHANOCOC.ECFGFKNLLGH;
		FNPELDEHJKL = PHDNPDCNJJA(fMFABAKPMLB, FNPELDEHJKL);
		return BOHLCKHAGJO(PIGHJOPDLHD(MBIJHANOCOC, BENKLGPHLGI, FNPELDEHJKL, PHILIHLPDFD));
	}

	public static JGAFKLGGBGF PHDNPDCNJJA(BHPIABAGAPB FMFABAKPMLB, JGAFKLGGBGF HPHBDNBJPHB)
	{
		BHPIABAGAPB cJHEIBNHNNE = HPHBDNBJPHB.ECFGFKNLLGH;
		if (!FMFABAKPMLB.KIFDKLPDKMD(cJHEIBNHNNE))
		{
			throw new ArgumentException("Point must be on the same curve");
		}
		return FMFABAKPMLB.PHDNPDCNJJA(HPHBDNBJPHB);
	}

	public static void BHABNEODMGI(KBINBLGGLNE[] IJGNIJAMCML, int JBAJPGIAPFF, int NBEDPKHALCN)
	{
		BHABNEODMGI(IJGNIJAMCML, JBAJPGIAPFF, NBEDPKHALCN, null);
	}

	public static void BHABNEODMGI(KBINBLGGLNE[] IJGNIJAMCML, int JBAJPGIAPFF, int NBEDPKHALCN, KBINBLGGLNE HJLOCAEAFMJ)
	{
		KBINBLGGLNE[] array = new KBINBLGGLNE[NBEDPKHALCN];
		array[0] = IJGNIJAMCML[JBAJPGIAPFF];
		int num = 0;
		while (++num < NBEDPKHALCN)
		{
			array[num] = array[num - 1].IBJBIGNPNEM(IJGNIJAMCML[JBAJPGIAPFF + num]);
		}
		num--;
		if (HJLOCAEAFMJ != null)
		{
			array[num] = array[num].IBJBIGNPNEM(HJLOCAEAFMJ);
		}
		KBINBLGGLNE kBINBLGGLNE = array[num].LEIECFOMCNL();
		while (num > 0)
		{
			int num2 = JBAJPGIAPFF + num--;
			KBINBLGGLNE bCIHLCMFAEK = IJGNIJAMCML[num2];
			IJGNIJAMCML[num2] = array[num].IBJBIGNPNEM(kBINBLGGLNE);
			kBINBLGGLNE = kBINBLGGLNE.IBJBIGNPNEM(bCIHLCMFAEK);
		}
		IJGNIJAMCML[JBAJPGIAPFF] = kBINBLGGLNE;
	}

	public static JGAFKLGGBGF AGBHEEFGGBF(JGAFKLGGBGF HPHBDNBJPHB, BigInteger BENKLGPHLGI)
	{
		BigInteger bigInteger = BENKLGPHLGI.DKGOFCBJBPB();
		JGAFKLGGBGF jGAFKLGGBGF = HPHBDNBJPHB.ECFGFKNLLGH.EFOLNCNGADB;
		int bitLength = bigInteger.BitLength;
		if (bitLength > 0)
		{
			if (bigInteger.NJHNJHGDCIJ(0))
			{
				jGAFKLGGBGF = HPHBDNBJPHB;
			}
			for (int i = 1; i < bitLength; i++)
			{
				HPHBDNBJPHB = HPHBDNBJPHB.LLGLJBDLBOP();
				if (bigInteger.NJHNJHGDCIJ(i))
				{
					jGAFKLGGBGF = jGAFKLGGBGF.JEACJNAKLDJ(HPHBDNBJPHB);
				}
			}
		}
		return (BENKLGPHLGI.SignValue >= 0) ? jGAFKLGGBGF : jGAFKLGGBGF.BHKOFHMDACN();
	}

	public static JGAFKLGGBGF BOHLCKHAGJO(JGAFKLGGBGF HPHBDNBJPHB)
	{
		if (!HPHBDNBJPHB.NAFCDEECGEF())
		{
			throw new ArgumentException("Invalid point", "p");
		}
		return HPHBDNBJPHB;
	}

	internal static JGAFKLGGBGF PIGHJOPDLHD(JGAFKLGGBGF MBIJHANOCOC, BigInteger BENKLGPHLGI, JGAFKLGGBGF FNPELDEHJKL, BigInteger PHILIHLPDFD)
	{
		BHPIABAGAPB bHPIABAGAPB = MBIJHANOCOC.ECFGFKNLLGH;
		JGAFKLGGBGF jGAFKLGGBGF = bHPIABAGAPB.EFOLNCNGADB;
		JGAFKLGGBGF jGAFKLGGBGF2 = MBIJHANOCOC.JEACJNAKLDJ(FNPELDEHJKL);
		JGAFKLGGBGF jGAFKLGGBGF3 = MBIJHANOCOC.FBGIHKPECCO(FNPELDEHJKL);
		JGAFKLGGBGF[] array = new JGAFKLGGBGF[4] { FNPELDEHJKL, jGAFKLGGBGF3, MBIJHANOCOC, jGAFKLGGBGF2 };
		bHPIABAGAPB.NPDHPEDPAPA(array);
		JGAFKLGGBGF[] array2 = new JGAFKLGGBGF[9]
		{
			array[3].BHKOFHMDACN(),
			array[2].BHKOFHMDACN(),
			array[1].BHKOFHMDACN(),
			array[0].BHKOFHMDACN(),
			jGAFKLGGBGF,
			array[0],
			array[1],
			array[2],
			array[3]
		};
		byte[] array3 = ABHJGAELGKM.MBPFFFKHLON(BENKLGPHLGI, PHILIHLPDFD);
		JGAFKLGGBGF jGAFKLGGBGF4 = jGAFKLGGBGF;
		int num = array3.Length;
		while (--num >= 0)
		{
			int num2 = array3[num];
			int num3 = num2 << 24 >> 28;
			int num4 = num2 << 28 >> 28;
			int num5 = 4 + num3 * 3 + num4;
			jGAFKLGGBGF4 = jGAFKLGGBGF4.GFLGEFHLIGE(array2[num5]);
		}
		return jGAFKLGGBGF4;
	}

	internal static JGAFKLGGBGF BNDHMAOGOOI(JGAFKLGGBGF MBIJHANOCOC, BigInteger BENKLGPHLGI, JGAFKLGGBGF FNPELDEHJKL, BigInteger PHILIHLPDFD)
	{
		bool flag = BENKLGPHLGI.SignValue < 0;
		bool flag2 = PHILIHLPDFD.SignValue < 0;
		BENKLGPHLGI = BENKLGPHLGI.DKGOFCBJBPB();
		PHILIHLPDFD = PHILIHLPDFD.DKGOFCBJBPB();
		int hHHMOGOKFHF = Math.Max(2, Math.Min(16, ABHJGAELGKM.PKCOEDNEJGL(BENKLGPHLGI.BitLength)));
		int hHHMOGOKFHF2 = Math.Max(2, Math.Min(16, ABHJGAELGKM.PKCOEDNEJGL(PHILIHLPDFD.BitLength)));
		PPENFIKGBIK pPENFIKGBIK = ABHJGAELGKM.KPMDCFDMLFE(MBIJHANOCOC, hHHMOGOKFHF, true);
		PPENFIKGBIK pPENFIKGBIK2 = ABHJGAELGKM.KPMDCFDMLFE(FNPELDEHJKL, hHHMOGOKFHF2, true);
		JGAFKLGGBGF[] mKCNAJIENKM = ((!flag) ? pPENFIKGBIK.JJFOMCAIJPO : pPENFIKGBIK.JNABIODEPNL);
		JGAFKLGGBGF[] jLIBENKNDEK = ((!flag2) ? pPENFIKGBIK2.JJFOMCAIJPO : pPENFIKGBIK2.JNABIODEPNL);
		JGAFKLGGBGF[] mGIAMNJPIBK = ((!flag) ? pPENFIKGBIK.JNABIODEPNL : pPENFIKGBIK.JJFOMCAIJPO);
		JGAFKLGGBGF[] cDODAGBLJDJ = ((!flag2) ? pPENFIKGBIK2.JNABIODEPNL : pPENFIKGBIK2.JJFOMCAIJPO);
		byte[] cJPDMNHFIMJ = ABHJGAELGKM.DLOFMBAKCEG(hHHMOGOKFHF, BENKLGPHLGI);
		byte[] eKBJNAIAJEP = ABHJGAELGKM.DLOFMBAKCEG(hHHMOGOKFHF2, PHILIHLPDFD);
		return BNDHMAOGOOI(mKCNAJIENKM, mGIAMNJPIBK, cJPDMNHFIMJ, jLIBENKNDEK, cDODAGBLJDJ, eKBJNAIAJEP);
	}

	internal static JGAFKLGGBGF BNDHMAOGOOI(JGAFKLGGBGF MBIJHANOCOC, BigInteger BENKLGPHLGI, LFADADGHPPC LGCNIJOLPKK, BigInteger PHILIHLPDFD)
	{
		bool flag = BENKLGPHLGI.SignValue < 0;
		bool flag2 = PHILIHLPDFD.SignValue < 0;
		BENKLGPHLGI = BENKLGPHLGI.DKGOFCBJBPB();
		PHILIHLPDFD = PHILIHLPDFD.DKGOFCBJBPB();
		int hHHMOGOKFHF = Math.Max(2, Math.Min(16, ABHJGAELGKM.PKCOEDNEJGL(Math.Max(BENKLGPHLGI.BitLength, PHILIHLPDFD.BitLength))));
		JGAFKLGGBGF hPHBDNBJPHB = ABHJGAELGKM.ACMLIGOIIJF(MBIJHANOCOC, hHHMOGOKFHF, true, LGCNIJOLPKK);
		PPENFIKGBIK pPENFIKGBIK = ABHJGAELGKM.BLEABBDGPNI(MBIJHANOCOC);
		PPENFIKGBIK pPENFIKGBIK2 = ABHJGAELGKM.BLEABBDGPNI(hPHBDNBJPHB);
		JGAFKLGGBGF[] mKCNAJIENKM = ((!flag) ? pPENFIKGBIK.JJFOMCAIJPO : pPENFIKGBIK.JNABIODEPNL);
		JGAFKLGGBGF[] jLIBENKNDEK = ((!flag2) ? pPENFIKGBIK2.JJFOMCAIJPO : pPENFIKGBIK2.JNABIODEPNL);
		JGAFKLGGBGF[] mGIAMNJPIBK = ((!flag) ? pPENFIKGBIK.JNABIODEPNL : pPENFIKGBIK.JJFOMCAIJPO);
		JGAFKLGGBGF[] cDODAGBLJDJ = ((!flag2) ? pPENFIKGBIK2.JNABIODEPNL : pPENFIKGBIK2.JJFOMCAIJPO);
		byte[] cJPDMNHFIMJ = ABHJGAELGKM.DLOFMBAKCEG(hHHMOGOKFHF, BENKLGPHLGI);
		byte[] eKBJNAIAJEP = ABHJGAELGKM.DLOFMBAKCEG(hHHMOGOKFHF, PHILIHLPDFD);
		return BNDHMAOGOOI(mKCNAJIENKM, mGIAMNJPIBK, cJPDMNHFIMJ, jLIBENKNDEK, cDODAGBLJDJ, eKBJNAIAJEP);
	}

	private static JGAFKLGGBGF BNDHMAOGOOI(JGAFKLGGBGF[] MKCNAJIENKM, JGAFKLGGBGF[] MGIAMNJPIBK, byte[] CJPDMNHFIMJ, JGAFKLGGBGF[] JLIBENKNDEK, JGAFKLGGBGF[] CDODAGBLJDJ, byte[] EKBJNAIAJEP)
	{
		int num = Math.Max(CJPDMNHFIMJ.Length, EKBJNAIAJEP.Length);
		BHPIABAGAPB bHPIABAGAPB = MKCNAJIENKM[0].ECFGFKNLLGH;
		JGAFKLGGBGF jGAFKLGGBGF = bHPIABAGAPB.EFOLNCNGADB;
		JGAFKLGGBGF jGAFKLGGBGF2 = jGAFKLGGBGF;
		int num2 = 0;
		for (int num3 = num - 1; num3 >= 0; num3--)
		{
			int num4 = ((num3 < CJPDMNHFIMJ.Length) ? ((sbyte)CJPDMNHFIMJ[num3]) : 0);
			int num5 = ((num3 < EKBJNAIAJEP.Length) ? ((sbyte)EKBJNAIAJEP[num3]) : 0);
			if ((num4 | num5) == 0)
			{
				num2++;
			}
			else
			{
				JGAFKLGGBGF jGAFKLGGBGF3 = jGAFKLGGBGF;
				if (num4 != 0)
				{
					int num6 = Math.Abs(num4);
					JGAFKLGGBGF[] array = ((num4 >= 0) ? MKCNAJIENKM : MGIAMNJPIBK);
					jGAFKLGGBGF3 = jGAFKLGGBGF3.JEACJNAKLDJ(array[num6 >> 1]);
				}
				if (num5 != 0)
				{
					int num7 = Math.Abs(num5);
					JGAFKLGGBGF[] array2 = ((num5 >= 0) ? JLIBENKNDEK : CDODAGBLJDJ);
					jGAFKLGGBGF3 = jGAFKLGGBGF3.JEACJNAKLDJ(array2[num7 >> 1]);
				}
				if (num2 > 0)
				{
					jGAFKLGGBGF2 = jGAFKLGGBGF2.BMHHHPFDNMA(num2);
					num2 = 0;
				}
				jGAFKLGGBGF2 = jGAFKLGGBGF2.GFLGEFHLIGE(jGAFKLGGBGF3);
			}
		}
		if (num2 > 0)
		{
			jGAFKLGGBGF2 = jGAFKLGGBGF2.BMHHHPFDNMA(num2);
		}
		return jGAFKLGGBGF2;
	}

	internal static JGAFKLGGBGF NGFMCHCDBBC(JGAFKLGGBGF[] FLLHHHDFCKA, BigInteger[] APIJJGNJKNF)
	{
		int num = FLLHHHDFCKA.Length;
		bool[] array = new bool[num];
		PPENFIKGBIK[] array2 = new PPENFIKGBIK[num];
		byte[][] array3 = new byte[num][];
		for (int i = 0; i < num; i++)
		{
			BigInteger bigInteger = APIJJGNJKNF[i];
			array[i] = bigInteger.SignValue < 0;
			bigInteger = bigInteger.DKGOFCBJBPB();
			int hHHMOGOKFHF = Math.Max(2, Math.Min(16, ABHJGAELGKM.PKCOEDNEJGL(bigInteger.BitLength)));
			array2[i] = ABHJGAELGKM.KPMDCFDMLFE(FLLHHHDFCKA[i], hHHMOGOKFHF, true);
			array3[i] = ABHJGAELGKM.DLOFMBAKCEG(hHHMOGOKFHF, bigInteger);
		}
		return NGFMCHCDBBC(array, array2, array3);
	}

	internal static JGAFKLGGBGF KMFEKKHNEON(JGAFKLGGBGF[] FLLHHHDFCKA, BigInteger[] APIJJGNJKNF, BBIBEHOGPHK OFPNAHJEAMN)
	{
		BigInteger cEKMAJAHNAG = FLLHHHDFCKA[0].ECFGFKNLLGH.BHIJCAOHDCM;
		int num = FLLHHHDFCKA.Length;
		BigInteger[] array = new BigInteger[num << 1];
		int i = 0;
		int num2 = 0;
		for (; i < num; i++)
		{
			BigInteger[] array2 = OFPNAHJEAMN.MCNKLDGABBN(APIJJGNJKNF[i].MODIHOCEKBK(cEKMAJAHNAG));
			array[num2++] = array2[0];
			array[num2++] = array2[1];
		}
		LFADADGHPPC lFADADGHPPC = OFPNAHJEAMN.ABJHMAEGCCD;
		if (OFPNAHJEAMN.KGPNOBKADCP)
		{
			return NGFMCHCDBBC(FLLHHHDFCKA, lFADADGHPPC, array);
		}
		JGAFKLGGBGF[] array3 = new JGAFKLGGBGF[num << 1];
		int j = 0;
		int num3 = 0;
		for (; j < num; j++)
		{
			JGAFKLGGBGF jGAFKLGGBGF = FLLHHHDFCKA[j];
			JGAFKLGGBGF jGAFKLGGBGF2 = lFADADGHPPC.FBDFAFGCDIO(jGAFKLGGBGF);
			array3[num3++] = jGAFKLGGBGF;
			array3[num3++] = jGAFKLGGBGF2;
		}
		return NGFMCHCDBBC(array3, array);
	}

	internal static JGAFKLGGBGF NGFMCHCDBBC(JGAFKLGGBGF[] FLLHHHDFCKA, LFADADGHPPC KMLMLMCIKOG, BigInteger[] APIJJGNJKNF)
	{
		int num = FLLHHHDFCKA.Length;
		int num2 = num << 1;
		bool[] array = new bool[num2];
		PPENFIKGBIK[] array2 = new PPENFIKGBIK[num2];
		byte[][] array3 = new byte[num2][];
		for (int i = 0; i < num; i++)
		{
			int num3 = i << 1;
			int num4 = num3 + 1;
			BigInteger bigInteger = APIJJGNJKNF[num3];
			array[num3] = bigInteger.SignValue < 0;
			bigInteger = bigInteger.DKGOFCBJBPB();
			BigInteger bigInteger2 = APIJJGNJKNF[num4];
			array[num4] = bigInteger2.SignValue < 0;
			bigInteger2 = bigInteger2.DKGOFCBJBPB();
			int hHHMOGOKFHF = Math.Max(2, Math.Min(16, ABHJGAELGKM.PKCOEDNEJGL(Math.Max(bigInteger.BitLength, bigInteger2.BitLength))));
			JGAFKLGGBGF hPHBDNBJPHB = FLLHHHDFCKA[i];
			JGAFKLGGBGF hPHBDNBJPHB2 = ABHJGAELGKM.ACMLIGOIIJF(hPHBDNBJPHB, hHHMOGOKFHF, true, KMLMLMCIKOG);
			array2[num3] = ABHJGAELGKM.BLEABBDGPNI(hPHBDNBJPHB);
			array2[num4] = ABHJGAELGKM.BLEABBDGPNI(hPHBDNBJPHB2);
			array3[num3] = ABHJGAELGKM.DLOFMBAKCEG(hHHMOGOKFHF, bigInteger);
			array3[num4] = ABHJGAELGKM.DLOFMBAKCEG(hHHMOGOKFHF, bigInteger2);
		}
		return NGFMCHCDBBC(array, array2, array3);
	}

	private static JGAFKLGGBGF NGFMCHCDBBC(bool[] MOLDPLFANCI, PPENFIKGBIK[] MBHBIKDHFML, byte[][] FJBBFDMJBMO)
	{
		int num = 0;
		int num2 = FJBBFDMJBMO.Length;
		for (int i = 0; i < num2; i++)
		{
			num = Math.Max(num, FJBBFDMJBMO[i].Length);
		}
		BHPIABAGAPB bHPIABAGAPB = MBHBIKDHFML[0].JJFOMCAIJPO[0].ECFGFKNLLGH;
		JGAFKLGGBGF jGAFKLGGBGF = bHPIABAGAPB.EFOLNCNGADB;
		JGAFKLGGBGF jGAFKLGGBGF2 = jGAFKLGGBGF;
		int num3 = 0;
		for (int num4 = num - 1; num4 >= 0; num4--)
		{
			JGAFKLGGBGF jGAFKLGGBGF3 = jGAFKLGGBGF;
			for (int j = 0; j < num2; j++)
			{
				byte[] array = FJBBFDMJBMO[j];
				int num5 = ((num4 < array.Length) ? ((sbyte)array[num4]) : 0);
				if (num5 != 0)
				{
					int num6 = Math.Abs(num5);
					PPENFIKGBIK pPENFIKGBIK = MBHBIKDHFML[j];
					JGAFKLGGBGF[] array2 = ((num5 < 0 != MOLDPLFANCI[j]) ? pPENFIKGBIK.JNABIODEPNL : pPENFIKGBIK.JJFOMCAIJPO);
					jGAFKLGGBGF3 = jGAFKLGGBGF3.JEACJNAKLDJ(array2[num6 >> 1]);
				}
			}
			if (jGAFKLGGBGF3 == jGAFKLGGBGF)
			{
				num3++;
			}
			else
			{
				if (num3 > 0)
				{
					jGAFKLGGBGF2 = jGAFKLGGBGF2.BMHHHPFDNMA(num3);
					num3 = 0;
				}
				jGAFKLGGBGF2 = jGAFKLGGBGF2.GFLGEFHLIGE(jGAFKLGGBGF3);
			}
		}
		if (num3 > 0)
		{
			jGAFKLGGBGF2 = jGAFKLGGBGF2.BMHHHPFDNMA(num3);
		}
		return jGAFKLGGBGF2;
	}
}
