public interface KJLBDGGBCCF
{
	string KFKMEPMEBND { get; }

	JMPFLJGHAIM GBHNDFALCDC();

	void DIOELAHNLKJ(bool MAEALKEJALK, IGMAJHKIIPK IJJHBEECMBP);

	int BDIGGHEPIIP();

	void FBJJIIFIPGA(byte MOPCLEEGDFB);

	void JCKGDHGGKEH(byte[] AIFKJBMJOMK, int ELICNEDIBGB, int NBEDPKHALCN);

	int HBCJNPGKMDP(byte MOPCLEEGDFB, byte[] NGAGMIIBGKA, int EMAKNGBIFDC);

	int POCAGALIPAI(byte[] AIFKJBMJOMK, int ELICNEDIBGB, int NBEDPKHALCN, byte[] NGAGMIIBGKA, int EMAKNGBIFDC);

	int LCNOFBMOHHM(byte[] NGAGMIIBGKA, int EMAKNGBIFDC);

	byte[] JIDMPJJAOOI();

	int MIMJCMAODEK(int NBEDPKHALCN);

	int ACLDAECDPFN(int NBEDPKHALCN);

	void OMOKOKFNBKI();
}
