public interface KKMFHDBDNLF : BJLAMONNNDD
{
	void DIOELAHNLKJ(CGDEGBGOKJO MBEMNOCDDBC);

	KKMFHDBDNLF NFEDILFGOFB();

	void PDDLLDKPKOC(byte JMCLOFPGGNN);

	void OLDLMNLPAMN();

	KKMFHDBDNLF ANPICCCJCIH();

	BJLAMONNNDD IFHHBFPJJHN();

	byte[] LGOMGMANPHC(byte JMCLOFPGGNN);
}
