using Org.BouncyCastle.Math;

public abstract class KLOGJEJCNNM : FFPNOKBELNH
{
	public virtual JGAFKLGGBGF IBJBIGNPNEM(JGAFKLGGBGF HPHBDNBJPHB, BigInteger BENKLGPHLGI)
	{
		int signValue = BENKLGPHLGI.SignValue;
		if (signValue == 0 || HPHBDNBJPHB.IFCDKFANPBO)
		{
			return HPHBDNBJPHB.ECFGFKNLLGH.EFOLNCNGADB;
		}
		JGAFKLGGBGF jGAFKLGGBGF = OJGDKAJCDJK(HPHBDNBJPHB, BENKLGPHLGI.DKGOFCBJBPB());
		JGAFKLGGBGF hPHBDNBJPHB = ((signValue <= 0) ? jGAFKLGGBGF.BHKOFHMDACN() : jGAFKLGGBGF);
		return KHJLHEJBLOA.BOHLCKHAGJO(hPHBDNBJPHB);
	}

	protected abstract JGAFKLGGBGF OJGDKAJCDJK(JGAFKLGGBGF HPHBDNBJPHB, BigInteger BENKLGPHLGI);
}
