public class KOBDNDLAIOC : JBMFHKBENEK, HGIAHEKANFO
{
	private readonly MKNDIEHOMOI IGCEJBIEACI;

	internal KOBDNDLAIOC(MKNDIEHOMOI BKOBLIALKKC)
	{
		IGCEJBIEACI = BKOBLIALKKC;
	}

	public HGIAHEKANFO DMHLIGLGJGI()
	{
		return IGCEJBIEACI.DMHLIGLGJGI();
	}

	public EDOEBJJFOBM IIHKEACDNID()
	{
		return new ACMLPNKIJPN(IGCEJBIEACI.IFPAJCFNKGJ(), false);
	}
}
