using System;

internal class KOHAGEFADLN : OMOBJNLGOBO
{
	public KOHAGEFADLN(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public KOHAGEFADLN(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal KOHAGEFADLN(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new KOHAGEFADLN(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		PMHKCAGPLHE pMHKCAGPLHE = (PMHKCAGPLHE)base.NBPANDNEJGI;
		PMHKCAGPLHE pMHKCAGPLHE2 = (PMHKCAGPLHE)base.FIJLKLCHMGH;
		PMHKCAGPLHE pMHKCAGPLHE3 = (PMHKCAGPLHE)BCIHLCMFAEK.NBPANDNEJGI;
		PMHKCAGPLHE pMHKCAGPLHE4 = (PMHKCAGPLHE)BCIHLCMFAEK.FIJLKLCHMGH;
		PMHKCAGPLHE pMHKCAGPLHE5 = (PMHKCAGPLHE)base.LAMGGDKLPJH[0];
		PMHKCAGPLHE pMHKCAGPLHE6 = (PMHKCAGPLHE)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = AKOICJCJNFB.DCPJKFEDHOJ();
		uint[] array2 = AKOICJCJNFB.PLIFFMMBNPM();
		uint[] array3 = AKOICJCJNFB.PLIFFMMBNPM();
		uint[] array4 = AKOICJCJNFB.PLIFFMMBNPM();
		bool flag = pMHKCAGPLHE5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = pMHKCAGPLHE3.AMFCENFNAJJ;
			array6 = pMHKCAGPLHE4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			KIDIDJJDMKB.MIOEHGDPGAG(pMHKCAGPLHE5.AMFCENFNAJJ, array6);
			array5 = array2;
			KIDIDJJDMKB.IBJBIGNPNEM(array6, pMHKCAGPLHE3.AMFCENFNAJJ, array5);
			KIDIDJJDMKB.IBJBIGNPNEM(array6, pMHKCAGPLHE5.AMFCENFNAJJ, array6);
			KIDIDJJDMKB.IBJBIGNPNEM(array6, pMHKCAGPLHE4.AMFCENFNAJJ, array6);
		}
		bool flag2 = pMHKCAGPLHE6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = pMHKCAGPLHE.AMFCENFNAJJ;
			array8 = pMHKCAGPLHE2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			KIDIDJJDMKB.MIOEHGDPGAG(pMHKCAGPLHE6.AMFCENFNAJJ, array8);
			array7 = array;
			KIDIDJJDMKB.IBJBIGNPNEM(array8, pMHKCAGPLHE.AMFCENFNAJJ, array7);
			KIDIDJJDMKB.IBJBIGNPNEM(array8, pMHKCAGPLHE6.AMFCENFNAJJ, array8);
			KIDIDJJDMKB.IBJBIGNPNEM(array8, pMHKCAGPLHE2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = AKOICJCJNFB.PLIFFMMBNPM();
		KIDIDJJDMKB.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		KIDIDJJDMKB.FBGIHKPECCO(array8, array6, array10);
		if (AKOICJCJNFB.EJJHHCOFAAI(array9))
		{
			if (AKOICJCJNFB.EJJHHCOFAAI(array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		KIDIDJJDMKB.MIOEHGDPGAG(array9, array11);
		uint[] array12 = AKOICJCJNFB.PLIFFMMBNPM();
		KIDIDJJDMKB.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		KIDIDJJDMKB.IBJBIGNPNEM(array11, array7, array13);
		KIDIDJJDMKB.BHKOFHMDACN(array12, array12);
		AKOICJCJNFB.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = AKOICJCJNFB.FIBDFFPCDGC(array13, array13, array12);
		KIDIDJJDMKB.KKIGIOINLCI(aMFCENFNAJJ, array12);
		PMHKCAGPLHE pMHKCAGPLHE7 = new PMHKCAGPLHE(array4);
		KIDIDJJDMKB.MIOEHGDPGAG(array10, pMHKCAGPLHE7.AMFCENFNAJJ);
		KIDIDJJDMKB.FBGIHKPECCO(pMHKCAGPLHE7.AMFCENFNAJJ, array12, pMHKCAGPLHE7.AMFCENFNAJJ);
		PMHKCAGPLHE pMHKCAGPLHE8 = new PMHKCAGPLHE(array12);
		KIDIDJJDMKB.FBGIHKPECCO(array13, pMHKCAGPLHE7.AMFCENFNAJJ, pMHKCAGPLHE8.AMFCENFNAJJ);
		KIDIDJJDMKB.OMJFFHEIEFH(pMHKCAGPLHE8.AMFCENFNAJJ, array10, array);
		KIDIDJJDMKB.BKCHMGKFECM(array, pMHKCAGPLHE8.AMFCENFNAJJ);
		PMHKCAGPLHE pMHKCAGPLHE9 = new PMHKCAGPLHE(array9);
		if (!flag)
		{
			KIDIDJJDMKB.IBJBIGNPNEM(pMHKCAGPLHE9.AMFCENFNAJJ, pMHKCAGPLHE5.AMFCENFNAJJ, pMHKCAGPLHE9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			KIDIDJJDMKB.IBJBIGNPNEM(pMHKCAGPLHE9.AMFCENFNAJJ, pMHKCAGPLHE6.AMFCENFNAJJ, pMHKCAGPLHE9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { pMHKCAGPLHE9 };
		return new KOHAGEFADLN(bHPIABAGAPB, pMHKCAGPLHE7, pMHKCAGPLHE8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		PMHKCAGPLHE pMHKCAGPLHE = (PMHKCAGPLHE)base.FIJLKLCHMGH;
		if (pMHKCAGPLHE.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		PMHKCAGPLHE pMHKCAGPLHE2 = (PMHKCAGPLHE)base.NBPANDNEJGI;
		PMHKCAGPLHE pMHKCAGPLHE3 = (PMHKCAGPLHE)base.LAMGGDKLPJH[0];
		uint[] array = AKOICJCJNFB.PLIFFMMBNPM();
		uint[] array2 = AKOICJCJNFB.PLIFFMMBNPM();
		uint[] array3 = AKOICJCJNFB.PLIFFMMBNPM();
		KIDIDJJDMKB.MIOEHGDPGAG(pMHKCAGPLHE.AMFCENFNAJJ, array3);
		uint[] array4 = AKOICJCJNFB.PLIFFMMBNPM();
		KIDIDJJDMKB.MIOEHGDPGAG(array3, array4);
		bool flag = pMHKCAGPLHE3.EOJCHPEGABD;
		uint[] array5 = pMHKCAGPLHE3.AMFCENFNAJJ;
		if (!flag)
		{
			array5 = array2;
			KIDIDJJDMKB.MIOEHGDPGAG(pMHKCAGPLHE3.AMFCENFNAJJ, array5);
		}
		KIDIDJJDMKB.FBGIHKPECCO(pMHKCAGPLHE2.AMFCENFNAJJ, array5, array);
		uint[] array6 = array2;
		KIDIDJJDMKB.JEACJNAKLDJ(pMHKCAGPLHE2.AMFCENFNAJJ, array5, array6);
		KIDIDJJDMKB.IBJBIGNPNEM(array6, array, array6);
		uint aMFCENFNAJJ = AKOICJCJNFB.FIBDFFPCDGC(array6, array6, array6);
		KIDIDJJDMKB.KKIGIOINLCI(aMFCENFNAJJ, array6);
		uint[] array7 = array3;
		KIDIDJJDMKB.IBJBIGNPNEM(array3, pMHKCAGPLHE2.AMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(8, array7, 2, 0u);
		KIDIDJJDMKB.KKIGIOINLCI(aMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(8, array4, 3, 0u, array);
		KIDIDJJDMKB.KKIGIOINLCI(aMFCENFNAJJ, array);
		PMHKCAGPLHE pMHKCAGPLHE4 = new PMHKCAGPLHE(array4);
		KIDIDJJDMKB.MIOEHGDPGAG(array6, pMHKCAGPLHE4.AMFCENFNAJJ);
		KIDIDJJDMKB.FBGIHKPECCO(pMHKCAGPLHE4.AMFCENFNAJJ, array7, pMHKCAGPLHE4.AMFCENFNAJJ);
		KIDIDJJDMKB.FBGIHKPECCO(pMHKCAGPLHE4.AMFCENFNAJJ, array7, pMHKCAGPLHE4.AMFCENFNAJJ);
		PMHKCAGPLHE pMHKCAGPLHE5 = new PMHKCAGPLHE(array7);
		KIDIDJJDMKB.FBGIHKPECCO(array7, pMHKCAGPLHE4.AMFCENFNAJJ, pMHKCAGPLHE5.AMFCENFNAJJ);
		KIDIDJJDMKB.IBJBIGNPNEM(pMHKCAGPLHE5.AMFCENFNAJJ, array6, pMHKCAGPLHE5.AMFCENFNAJJ);
		KIDIDJJDMKB.FBGIHKPECCO(pMHKCAGPLHE5.AMFCENFNAJJ, array, pMHKCAGPLHE5.AMFCENFNAJJ);
		PMHKCAGPLHE pMHKCAGPLHE6 = new PMHKCAGPLHE(array6);
		KIDIDJJDMKB.LLGLJBDLBOP(pMHKCAGPLHE.AMFCENFNAJJ, pMHKCAGPLHE6.AMFCENFNAJJ);
		if (!flag)
		{
			KIDIDJJDMKB.IBJBIGNPNEM(pMHKCAGPLHE6.AMFCENFNAJJ, pMHKCAGPLHE3.AMFCENFNAJJ, pMHKCAGPLHE6.AMFCENFNAJJ);
		}
		return new KOHAGEFADLN(bHPIABAGAPB, pMHKCAGPLHE4, pMHKCAGPLHE5, new KBINBLGGLNE[1] { pMHKCAGPLHE6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new KOHAGEFADLN(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
