public interface KPMKFMEEJCJ
{
	string KFKMEPMEBND { get; }

	void DIOELAHNLKJ(bool MAEALKEJALK, IGMAJHKIIPK IJJHBEECMBP);

	byte IODEANDNHIP(byte MOPCLEEGDFB);

	void POCAGALIPAI(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int EOFAGACBNFP, byte[] BILGCJNPJGJ, int EMAKNGBIFDC);

	void OMOKOKFNBKI();
}
