using System.Collections.Generic;
using BestHTTP.SocketIO;

public class LEBMDIEHDMG : MJLNBKKHIPP
{
	private readonly SocketManager NLFNJGBPDEL;

	private readonly EIPCLBONPLC LNDFJKGAJAK;

	public LEBMDIEHDMG(SocketManager BMJLBDOKDPD, EIPCLBONPLC PEBICCFPCFE)
	{
		NLFNJGBPDEL = BMJLBDOKDPD;
		LNDFJKGAJAK = PEBICCFPCFE;
		NLFNJGBPDEL.Socket.On("do-show-message", NDCGAGHNPCE);
	}

	public void NDCGAGHNPCE(Socket PCAOOMAAMBE, Packet DFNAOGFJDMF, object[] MIDCNFGAIFA)
	{
		EKPAJFBBAJC eKPAJFBBAJC = new EKPAJFBBAJC((Dictionary<string, object>)MIDCNFGAIFA[0]);
		switch (eKPAJFBBAJC.ENBPGGCIADN)
		{
		case ABAPNBACABK.LeftRoom:
		case ABAPNBACABK.UserIsKicked:
			LNDFJKGAJAK.JFANMFMKOIP(eKPAJFBBAJC.AENEHCAFNMP);
			LNDFJKGAJAK.EAMBNIGLELH(eKPAJFBBAJC.AENEHCAFNMP);
			break;
		case ABAPNBACABK.Disconnected:
			LNDFJKGAJAK.EAMBNIGLELH(eKPAJFBBAJC.AENEHCAFNMP);
			break;
		case ABAPNBACABK.JoinRoom:
		case ABAPNBACABK.Connected:
			LNDFJKGAJAK.EOKBHHMLONF(eKPAJFBBAJC.AENEHCAFNMP);
			LNDFJKGAJAK.FOEGMMJDPCK(eKPAJFBBAJC.AENEHCAFNMP);
			break;
		case ABAPNBACABK.AcceptedToTeam:
			LNDFJKGAJAK.EOKBHHMLONF(eKPAJFBBAJC.AENEHCAFNMP);
			break;
		case ABAPNBACABK.NewManagerAssignedToTeam:
			LNDFJKGAJAK.COPDAKACHFM.AFPDGDAEENM = eKPAJFBBAJC.JNJOGOCNHHJ;
			return;
		case ABAPNBACABK.HelpedToUser:
		{
			if (eKPAJFBBAJC.DLDMKKEICMA.OCHADBCJEDP == LECPGNKOABP.GABGKBAKHDP.GDMECFECCOM)
			{
				LNDFJKGAJAK.IPCAELIMIBN.RequestInbox();
			}
			DKBEJLGEAOA dKBEJLGEAOA = LNDFJKGAJAK.COPDAKACHFM;
			if (dKBEJLGEAOA != null)
			{
				AKGIJAMHMNA value;
				if (dKBEJLGEAOA.HOINIMJNGFK.TryGetValue(eKPAJFBBAJC.JNJOGOCNHHJ, out value) && value != null)
				{
					value.KFBCFDALGBB++;
				}
				dKBEJLGEAOA.MCDNAIGOMAK[eKPAJFBBAJC.DLDMKKEICMA.OCHADBCJEDP] = eKPAJFBBAJC.DLDMKKEICMA;
				dKBEJLGEAOA.AKNLLPAHFOK++;
			}
			break;
		}
		default:
			GBFAPADEBEC.KIFFBFPEMGP(PBIIDJOKNEK.SocialChatModule, "Unknown message type: " + eKPAJFBBAJC.ENBPGGCIADN);
			return;
		case ABAPNBACABK.UserMessage:
		case ABAPNBACABK.HelpAsked:
			break;
		}
		LNDFJKGAJAK.IPCAELIMIBN.CurrentJoinedContainer.ChatTab.AddMessage(eKPAJFBBAJC);
	}
}
