using System;

public abstract class LEPLCPNKDCK : NHIFILGGAOG
{
	protected abstract byte EPJPGEHMICN { get; }

	public override byte[] MKEBGONJHED(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ JMNLHNOGILL, byte[] AIELCDIFLFB)
	{
		OHPHNNNHCOO oHPHNNNHCOO = LBBGKELCIGD(ADLMOHOLCGL, true, true, new MDAKJDOFCEP(JMNLHNOGILL, COOBIGONLDK.KMLKPFPCFLA));
		if (ADLMOHOLCGL == null)
		{
			oHPHNNNHCOO.GONEEEFEDGF(AIELCDIFLFB, 16, 20);
		}
		else
		{
			oHPHNNNHCOO.GONEEEFEDGF(AIELCDIFLFB, 0, AIELCDIFLFB.Length);
		}
		return oHPHNNNHCOO.HMJHAKCMGHC();
	}

	public override bool JNKONIDOPKE(FBMKOGABPFL ADLMOHOLCGL, byte[] DIJNMJINHIL, COEMJAGOFJJ ECPKCNOAOAJ, byte[] AIELCDIFLFB)
	{
		OHPHNNNHCOO oHPHNNNHCOO = LBBGKELCIGD(ADLMOHOLCGL, true, false, ECPKCNOAOAJ);
		if (ADLMOHOLCGL == null)
		{
			oHPHNNNHCOO.GONEEEFEDGF(AIELCDIFLFB, 16, 20);
		}
		else
		{
			oHPHNNNHCOO.GONEEEFEDGF(AIELCDIFLFB, 0, AIELCDIFLFB.Length);
		}
		return oHPHNNNHCOO.HLJBBONKPDG(DIJNMJINHIL);
	}

	public override OHPHNNNHCOO GBJMMNPHHNN(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ JMNLHNOGILL)
	{
		return LBBGKELCIGD(ADLMOHOLCGL, false, true, JMNLHNOGILL);
	}

	public override OHPHNNNHCOO OPKHBIHFBMM(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ ECPKCNOAOAJ)
	{
		return LBBGKELCIGD(ADLMOHOLCGL, false, false, ECPKCNOAOAJ);
	}

	protected virtual IGMAJHKIIPK BEILHNOPFGH(bool KGPBDABMHKH, IGMAJHKIIPK CILGMABNHOH)
	{
		return CILGMABNHOH;
	}

	protected virtual OHPHNNNHCOO LBBGKELCIGD(FBMKOGABPFL ADLMOHOLCGL, bool HEBAGGBJBMC, bool KGPBDABMHKH, IGMAJHKIIPK CILGMABNHOH)
	{
		if (ADLMOHOLCGL != null != KINEBFNENMB.OHGCLELCPMD(COOBIGONLDK))
		{
			throw new InvalidOperationException();
		}
		if (ADLMOHOLCGL != null && ADLMOHOLCGL.ACMDKLDPDLB != EPJPGEHMICN)
		{
			throw new InvalidOperationException();
		}
		byte jMCLOFPGGNN = (byte)((ADLMOHOLCGL != null) ? ADLMOHOLCGL.GHMJJKMGKKB : 2);
		BJLAMONNNDD hABFKBCEIBN = ((!HEBAGGBJBMC) ? KINEBFNENMB.KNADNPDKLGD(jMCLOFPGGNN) : new OHAOIPKCMFC());
		OHPHNNNHCOO oHPHNNNHCOO = new OBOJFCBALPO(EIFJLPDKAJK(jMCLOFPGGNN), hABFKBCEIBN);
		oHPHNNNHCOO.DIOELAHNLKJ(KGPBDABMHKH, BEILHNOPFGH(KGPBDABMHKH, CILGMABNHOH));
		return oHPHNNNHCOO;
	}

	protected abstract IJNFIACGEKI EIFJLPDKAJK(byte JMCLOFPGGNN);
}
