using System;

public class LFLPHPGFFKP : LNKPCJLANAO
{
	private readonly byte[] HABFKBCEIBN;

	private readonly COCECKPDIKC LGAAPLFEPMG;

	public COCECKPDIKC ABHPJEPGJGI
	{
		get
		{
			return LGAAPLFEPMG;
		}
	}

	public LFLPHPGFFKP(COCECKPDIKC LGAAPLFEPMG, byte[] HABFKBCEIBN)
	{
		this.HABFKBCEIBN = HABFKBCEIBN;
		this.LGAAPLFEPMG = LGAAPLFEPMG;
	}

	private LFLPHPGFFKP(ALLINHNNNJN MIABODPHOIP)
	{
		if (MIABODPHOIP.GMCGMPEEHJP != 2)
		{
			throw new ArgumentException("Wrong number of elements in sequence", "seq");
		}
		LGAAPLFEPMG = COCECKPDIKC.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(0));
		HABFKBCEIBN = PJGIGKJFGFI.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(1)).KLHNEKMCKKI();
	}

	public static LFLPHPGFFKP BJLJCGFMFOO(PAANMJLACEF NEMEKIOEOLC, bool DHGLJHFEJFL)
	{
		return BJLJCGFMFOO(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC, DHGLJHFEJFL));
	}

	public static LFLPHPGFFKP BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC is LFLPHPGFFKP)
		{
			return (LFLPHPGFFKP)NEMEKIOEOLC;
		}
		if (NEMEKIOEOLC is ALLINHNNNJN)
		{
			return new LFLPHPGFFKP((ALLINHNNNJN)NEMEKIOEOLC);
		}
		throw new ArgumentException("unknown object in factory: " + LHFGHNFJIKM.JKHOEKAOLPM(NEMEKIOEOLC), "obj");
	}

	public byte[] GANMELFOOMP()
	{
		return HABFKBCEIBN;
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		return new KOGPLMALOEH(LGAAPLFEPMG, new CFMJBFILJCB(HABFKBCEIBN));
	}
}
