using System;
using Org.BouncyCastle.Math;

internal class LFPIKIBPFBB : EJLHHPBLEMF
{
	public override KBINBLGGLNE LGFGMGPDEIB
	{
		get
		{
			KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			if (base.IFCDKFANPBO || kBINBLGGLNE.EJJHHCOFAAI)
			{
				return kBINBLGGLNE2;
			}
			KBINBLGGLNE kBINBLGGLNE3 = kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE).IBJBIGNPNEM(kBINBLGGLNE);
			KBINBLGGLNE kBINBLGGLNE4 = base.LAMGGDKLPJH[0];
			if (!kBINBLGGLNE4.EOJCHPEGABD)
			{
				kBINBLGGLNE3 = kBINBLGGLNE3.MCPDGENJCDB(kBINBLGGLNE4);
			}
			return kBINBLGGLNE3;
		}
	}

	protected internal override bool NLPBPDPOOAK
	{
		get
		{
			KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
			if (kBINBLGGLNE.EJJHHCOFAAI)
			{
				return false;
			}
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			return kBINBLGGLNE2.OFGNPBCCHAA() != kBINBLGGLNE.OFGNPBCCHAA();
		}
	}

	public LFPIKIBPFBB(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public LFPIKIBPFBB(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal LFPIKIBPFBB(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new LFPIKIBPFBB(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE2 = BCIHLCMFAEK.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			if (kBINBLGGLNE2.EJJHHCOFAAI)
			{
				return bHPIABAGAPB.EFOLNCNGADB;
			}
			return BCIHLCMFAEK.JEACJNAKLDJ(this);
		}
		KBINBLGGLNE kBINBLGGLNE3 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE4 = base.LAMGGDKLPJH[0];
		KBINBLGGLNE kBINBLGGLNE5 = BCIHLCMFAEK.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE6 = BCIHLCMFAEK.LAMGGDKLPJH[0];
		bool flag = kBINBLGGLNE4.EOJCHPEGABD;
		KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE2;
		KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE5;
		if (!flag)
		{
			kBINBLGGLNE7 = kBINBLGGLNE7.IBJBIGNPNEM(kBINBLGGLNE4);
			kBINBLGGLNE8 = kBINBLGGLNE8.IBJBIGNPNEM(kBINBLGGLNE4);
		}
		bool flag2 = kBINBLGGLNE6.EOJCHPEGABD;
		KBINBLGGLNE kBINBLGGLNE9 = kBINBLGGLNE;
		KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE3;
		if (!flag2)
		{
			kBINBLGGLNE9 = kBINBLGGLNE9.IBJBIGNPNEM(kBINBLGGLNE6);
			kBINBLGGLNE10 = kBINBLGGLNE10.IBJBIGNPNEM(kBINBLGGLNE6);
		}
		KBINBLGGLNE kBINBLGGLNE11 = kBINBLGGLNE10.JEACJNAKLDJ(kBINBLGGLNE8);
		KBINBLGGLNE kBINBLGGLNE12 = kBINBLGGLNE9.JEACJNAKLDJ(kBINBLGGLNE7);
		if (kBINBLGGLNE12.EJJHHCOFAAI)
		{
			if (kBINBLGGLNE11.EJJHHCOFAAI)
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		KBINBLGGLNE kBINBLGGLNE15;
		KBINBLGGLNE cNLILOEEBOJ;
		KBINBLGGLNE kBINBLGGLNE17;
		if (kBINBLGGLNE2.EJJHHCOFAAI)
		{
			JGAFKLGGBGF jGAFKLGGBGF = MIHJHLFLHNA();
			kBINBLGGLNE = jGAFKLGGBGF.OBCJFNBLIPG;
			KBINBLGGLNE kBINBLGGLNE13 = jGAFKLGGBGF.LGFGMGPDEIB;
			KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE5;
			KBINBLGGLNE kBINBLGGLNE14 = kBINBLGGLNE13.JEACJNAKLDJ(bCIHLCMFAEK).MCPDGENJCDB(kBINBLGGLNE);
			kBINBLGGLNE15 = kBINBLGGLNE14.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE14).JEACJNAKLDJ(kBINBLGGLNE)
				.JEACJNAKLDJ(bHPIABAGAPB.JEHECJGFJEB);
			if (kBINBLGGLNE15.EJJHHCOFAAI)
			{
				return new LFPIKIBPFBB(bHPIABAGAPB, kBINBLGGLNE15, bHPIABAGAPB.FPKDKHJKEEF.PAEDNKEIDOM(), base.BPGGHHMMCCB);
			}
			KBINBLGGLNE kBINBLGGLNE16 = kBINBLGGLNE14.IBJBIGNPNEM(kBINBLGGLNE.JEACJNAKLDJ(kBINBLGGLNE15)).JEACJNAKLDJ(kBINBLGGLNE15).JEACJNAKLDJ(kBINBLGGLNE13);
			cNLILOEEBOJ = kBINBLGGLNE16.MCPDGENJCDB(kBINBLGGLNE15).JEACJNAKLDJ(kBINBLGGLNE15);
			kBINBLGGLNE17 = bHPIABAGAPB.HFENNGHNFLF(BigInteger.One);
		}
		else
		{
			kBINBLGGLNE12 = kBINBLGGLNE12.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE18 = kBINBLGGLNE11.IBJBIGNPNEM(kBINBLGGLNE9);
			KBINBLGGLNE kBINBLGGLNE19 = kBINBLGGLNE11.IBJBIGNPNEM(kBINBLGGLNE7);
			kBINBLGGLNE15 = kBINBLGGLNE18.IBJBIGNPNEM(kBINBLGGLNE19);
			if (kBINBLGGLNE15.EJJHHCOFAAI)
			{
				return new LFPIKIBPFBB(bHPIABAGAPB, kBINBLGGLNE15, bHPIABAGAPB.FPKDKHJKEEF.PAEDNKEIDOM(), base.BPGGHHMMCCB);
			}
			KBINBLGGLNE kBINBLGGLNE20 = kBINBLGGLNE11.IBJBIGNPNEM(kBINBLGGLNE12);
			if (!flag2)
			{
				kBINBLGGLNE20 = kBINBLGGLNE20.IBJBIGNPNEM(kBINBLGGLNE6);
			}
			cNLILOEEBOJ = kBINBLGGLNE19.JEACJNAKLDJ(kBINBLGGLNE12).FGLCIBKKKFF(kBINBLGGLNE20, kBINBLGGLNE3.JEACJNAKLDJ(kBINBLGGLNE4));
			kBINBLGGLNE17 = kBINBLGGLNE20;
			if (!flag)
			{
				kBINBLGGLNE17 = kBINBLGGLNE17.IBJBIGNPNEM(kBINBLGGLNE4);
			}
		}
		return new LFPIKIBPFBB(bHPIABAGAPB, kBINBLGGLNE15, cNLILOEEBOJ, new KBINBLGGLNE[1] { kBINBLGGLNE17 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
		bool flag = kBINBLGGLNE3.EOJCHPEGABD;
		KBINBLGGLNE kBINBLGGLNE4 = ((!flag) ? kBINBLGGLNE2.IBJBIGNPNEM(kBINBLGGLNE3) : kBINBLGGLNE2);
		KBINBLGGLNE bCIHLCMFAEK = ((!flag) ? kBINBLGGLNE3.MIOEHGDPGAG() : kBINBLGGLNE3);
		KBINBLGGLNE kBINBLGGLNE5 = bHPIABAGAPB.JEHECJGFJEB;
		KBINBLGGLNE bCIHLCMFAEK2 = ((!flag) ? kBINBLGGLNE5.IBJBIGNPNEM(bCIHLCMFAEK) : kBINBLGGLNE5);
		KBINBLGGLNE kBINBLGGLNE6 = kBINBLGGLNE2.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE4).JEACJNAKLDJ(bCIHLCMFAEK2);
		if (kBINBLGGLNE6.EJJHHCOFAAI)
		{
			return new LFPIKIBPFBB(bHPIABAGAPB, kBINBLGGLNE6, bHPIABAGAPB.FPKDKHJKEEF.PAEDNKEIDOM(), base.BPGGHHMMCCB);
		}
		KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE6.MIOEHGDPGAG();
		KBINBLGGLNE kBINBLGGLNE8 = ((!flag) ? kBINBLGGLNE6.IBJBIGNPNEM(bCIHLCMFAEK) : kBINBLGGLNE6);
		KBINBLGGLNE kBINBLGGLNE9 = ((!flag) ? kBINBLGGLNE.IBJBIGNPNEM(kBINBLGGLNE3) : kBINBLGGLNE);
		KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE9.FGLCIBKKKFF(kBINBLGGLNE6, kBINBLGGLNE4).JEACJNAKLDJ(kBINBLGGLNE7).JEACJNAKLDJ(kBINBLGGLNE8);
		return new LFPIKIBPFBB(bHPIABAGAPB, kBINBLGGLNE7, cNLILOEEBOJ, new KBINBLGGLNE[1] { kBINBLGGLNE8 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		KBINBLGGLNE kBINBLGGLNE2 = BCIHLCMFAEK.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE3 = BCIHLCMFAEK.LAMGGDKLPJH[0];
		if (kBINBLGGLNE2.EJJHHCOFAAI || !kBINBLGGLNE3.EOJCHPEGABD)
		{
			return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
		}
		KBINBLGGLNE kBINBLGGLNE4 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE5 = base.LAMGGDKLPJH[0];
		KBINBLGGLNE kBINBLGGLNE6 = BCIHLCMFAEK.FIJLKLCHMGH;
		KBINBLGGLNE aMFCENFNAJJ = kBINBLGGLNE.MIOEHGDPGAG();
		KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE4.MIOEHGDPGAG();
		KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE5.MIOEHGDPGAG();
		KBINBLGGLNE bCIHLCMFAEK2 = kBINBLGGLNE4.IBJBIGNPNEM(kBINBLGGLNE5);
		KBINBLGGLNE bCIHLCMFAEK3 = bHPIABAGAPB.JEHECJGFJEB.IBJBIGNPNEM(kBINBLGGLNE7).JEACJNAKLDJ(bCIHLCMFAEK).JEACJNAKLDJ(bCIHLCMFAEK2);
		KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE6.AOAINNMNBHC();
		KBINBLGGLNE kBINBLGGLNE9 = bHPIABAGAPB.JEHECJGFJEB.JEACJNAKLDJ(kBINBLGGLNE8).IBJBIGNPNEM(kBINBLGGLNE7).JEACJNAKLDJ(bCIHLCMFAEK)
			.CIDGMJAFLHM(bCIHLCMFAEK3, aMFCENFNAJJ, kBINBLGGLNE7);
		KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE2.IBJBIGNPNEM(kBINBLGGLNE7);
		KBINBLGGLNE kBINBLGGLNE11 = kBINBLGGLNE10.JEACJNAKLDJ(bCIHLCMFAEK3).MIOEHGDPGAG();
		if (kBINBLGGLNE11.EJJHHCOFAAI)
		{
			if (kBINBLGGLNE9.EJJHHCOFAAI)
			{
				return BCIHLCMFAEK.LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		if (kBINBLGGLNE9.EJJHHCOFAAI)
		{
			return new LFPIKIBPFBB(bHPIABAGAPB, kBINBLGGLNE9, bHPIABAGAPB.FPKDKHJKEEF.PAEDNKEIDOM(), base.BPGGHHMMCCB);
		}
		KBINBLGGLNE aMFCENFNAJJ2 = kBINBLGGLNE9.MIOEHGDPGAG().IBJBIGNPNEM(kBINBLGGLNE10);
		KBINBLGGLNE kBINBLGGLNE12 = kBINBLGGLNE9.IBJBIGNPNEM(kBINBLGGLNE11).IBJBIGNPNEM(kBINBLGGLNE7);
		KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE9.JEACJNAKLDJ(kBINBLGGLNE11).MIOEHGDPGAG().CIDGMJAFLHM(bCIHLCMFAEK3, kBINBLGGLNE8, kBINBLGGLNE12);
		return new LFPIKIBPFBB(bHPIABAGAPB, aMFCENFNAJJ2, cNLILOEEBOJ, new KBINBLGGLNE[1] { kBINBLGGLNE12 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return this;
		}
		KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
		return new LFPIKIBPFBB(ECFGFKNLLGH, kBINBLGGLNE, kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE3), new KBINBLGGLNE[1] { kBINBLGGLNE3 }, base.BPGGHHMMCCB);
	}
}
