using Org.BouncyCastle.Math;

public class LGEGKLHIPBH : CFMMJCMIGNM
{
	private DJBJCHEAMKF BOFHHECPKNF;

	public virtual void DIOELAHNLKJ(HPBPDALECOG IJJHBEECMBP)
	{
		BOFHHECPKNF = (DJBJCHEAMKF)IJJHBEECMBP;
	}

	public virtual HOHJPJDGOLF LOFCKPBODIJ()
	{
		GFNHMNLOOBB gABGKBAKHDP = GFNHMNLOOBB.GABGKBAKHDP;
		CLBPDHGBHML cLBPDHGBHML = BOFHHECPKNF.KPJHHAAOFOH;
		BigInteger aMFCENFNAJJ = gABGKBAKHDP.ILJLFKLPKKM(cLBPDHGBHML, BOFHHECPKNF.IPFKDIJBGIM);
		BigInteger cNLILOEEBOJ = gABGKBAKHDP.LEGMJIGOKFE(cLBPDHGBHML, aMFCENFNAJJ);
		return new HOHJPJDGOLF(new GBBNCENGABI(cNLILOEEBOJ, cLBPDHGBHML), new AEIKMJPPOMN(aMFCENFNAJJ, cLBPDHGBHML));
	}
}
