using System;

public class LHAMCHLCIFH
{
	protected readonly CGDEGBGOKJO MBEMNOCDDBC;

	protected readonly byte[] JPCIJINDHIH;

	protected readonly PHFBFDEAHMD LGMMFPHDIMH;

	protected readonly int NKDFLEAKEPK;

	protected readonly int DAGAEMBHDOD;

	protected readonly int OHLDCPAOAGK;

	public virtual byte[] BKKEPGBKEPD
	{
		get
		{
			return JPCIJINDHIH;
		}
	}

	public virtual int PNBDAGKFOBN
	{
		get
		{
			return OHLDCPAOAGK;
		}
	}

	public LHAMCHLCIFH(CGDEGBGOKJO MBEMNOCDDBC, BJLAMONNNDD HABFKBCEIBN, byte[] IKNCPEPOKGJ, int EDKGBLMGFOO, int JJBNFEJMIPJ)
	{
		this.MBEMNOCDDBC = MBEMNOCDDBC;
		JEMNCGMEABF jEMNCGMEABF = new JEMNCGMEABF(IKNCPEPOKGJ, EDKGBLMGFOO, JJBNFEJMIPJ);
		JPCIJINDHIH = NOGCEBKPPJE.IKBFGGABMKP(jEMNCGMEABF.MEGBFHFMBFI());
		if (HABFKBCEIBN is AENDLCMHDKL)
		{
			NKDFLEAKEPK = 128;
			DAGAEMBHDOD = 16;
		}
		else
		{
			NKDFLEAKEPK = 64;
			DAGAEMBHDOD = 8;
		}
		if (KINEBFNENMB.NFEADLBGDGE(MBEMNOCDDBC))
		{
			LGMMFPHDIMH = new EBIOFEGJMGL(HABFKBCEIBN);
			if (HABFKBCEIBN.EEMLLAMENHO() == 20)
			{
				DAGAEMBHDOD = 4;
			}
		}
		else
		{
			LGMMFPHDIMH = new PGNLPNFKAPJ(HABFKBCEIBN);
		}
		LGMMFPHDIMH.DIOELAHNLKJ(jEMNCGMEABF);
		OHLDCPAOAGK = LGMMFPHDIMH.BKGLOJPPBIG();
		if (MBEMNOCDDBC.HFMNBFOAPOP.LDOIKDBKMNN)
		{
			OHLDCPAOAGK = Math.Min(OHLDCPAOAGK, 10);
		}
	}

	public virtual byte[] OFLKIODCBJJ(long MHCDKMMAMKP, byte NBFBPNNEKMN, byte[] OEFCOJLNCKP, int IBNDGNOIEEF, int EOFAGACBNFP)
	{
		OBDIBELBBEO oBDIBELBBEO = MBEMNOCDDBC.PJJKOIEAGJN;
		bool flag = oBDIBELBBEO.NFEADLBGDGE;
		byte[] array = new byte[(!flag) ? 13 : 11];
		KINEBFNENMB.JCMFNDAOIPC(MHCDKMMAMKP, array, 0);
		KINEBFNENMB.JBOHOOBEPAM(NBFBPNNEKMN, array, 8);
		if (!flag)
		{
			KINEBFNENMB.PPCDKILMGFD(oBDIBELBBEO, array, 9);
		}
		KINEBFNENMB.PGBAOHFKNHN(EOFAGACBNFP, array, array.Length - 2);
		LGMMFPHDIMH.GONEEEFEDGF(array, 0, array.Length);
		LGMMFPHDIMH.GONEEEFEDGF(OEFCOJLNCKP, IBNDGNOIEEF, EOFAGACBNFP);
		return JLAPBNJPEDO(DEOKPGHGOPK.LCNOFBMOHHM(LGMMFPHDIMH));
	}

	public virtual byte[] CHCPEFHOCJE(long MHCDKMMAMKP, byte NBFBPNNEKMN, byte[] OEFCOJLNCKP, int IBNDGNOIEEF, int EOFAGACBNFP, int FICAICECHAL, byte[] OGMLDODOLAE)
	{
		byte[] result = OFLKIODCBJJ(MHCDKMMAMKP, NBFBPNNEKMN, OEFCOJLNCKP, IBNDGNOIEEF, EOFAGACBNFP);
		int num = ((!KINEBFNENMB.NFEADLBGDGE(MBEMNOCDDBC)) ? 13 : 11);
		int num2 = CFCDAFFKFBK(num + FICAICECHAL) - CFCDAFFKFBK(num + EOFAGACBNFP);
		while (--num2 >= 0)
		{
			LGMMFPHDIMH.GONEEEFEDGF(OGMLDODOLAE, 0, NKDFLEAKEPK);
		}
		LGMMFPHDIMH.BPAJGOINFNL(OGMLDODOLAE[0]);
		LGMMFPHDIMH.OMOKOKFNBKI();
		return result;
	}

	protected virtual int CFCDAFFKFBK(int BFINPHAFPKJ)
	{
		return (BFINPHAFPKJ + DAGAEMBHDOD) / NKDFLEAKEPK;
	}

	protected virtual byte[] JLAPBNJPEDO(byte[] FAPGOCDNGIB)
	{
		if (FAPGOCDNGIB.Length <= OHLDCPAOAGK)
		{
			return FAPGOCDNGIB;
		}
		return NOGCEBKPPJE.OICFAJBLHEA(FAPGOCDNGIB, OHLDCPAOAGK);
	}
}
