using System;

public class LHCALAMFAOK : LNKPCJLANAO
{
	private COCECKPDIKC JMCLOFPGGNN;

	private COCECKPDIKC PNJAGJLLOPF;

	private GLFDIPNOLKN OIOHIKMNMDI;

	private GLFDIPNOLKN NLHNGDCKJCC;

	public static readonly COCECKPDIKC GHKGMKFDJEM = new COCECKPDIKC(POLLKACILDK.MEBPJCLMCDA, HLAKNNHGPNP.GABGKBAKHDP);

	public static readonly COCECKPDIKC BCGPEBDIJBA = new COCECKPDIKC(NLPPJKFFBON.NKBNJIMIGJP, GHKGMKFDJEM);

	public static readonly GLFDIPNOLKN EJGALDLJEII = new GLFDIPNOLKN(20);

	public static readonly GLFDIPNOLKN HOAGBCIJFAI = new GLFDIPNOLKN(1);

	public COCECKPDIKC FDOJDCLKKIP
	{
		get
		{
			return JMCLOFPGGNN;
		}
	}

	public COCECKPDIKC CIGBPOLPOFL
	{
		get
		{
			return PNJAGJLLOPF;
		}
	}

	public GLFDIPNOLKN BKMCBIDKCCL
	{
		get
		{
			return OIOHIKMNMDI;
		}
	}

	public GLFDIPNOLKN HCPAPLMJKNM
	{
		get
		{
			return NLHNGDCKJCC;
		}
	}

	public LHCALAMFAOK()
	{
		JMCLOFPGGNN = GHKGMKFDJEM;
		PNJAGJLLOPF = BCGPEBDIJBA;
		OIOHIKMNMDI = EJGALDLJEII;
		NLHNGDCKJCC = HOAGBCIJFAI;
	}

	public LHCALAMFAOK(COCECKPDIKC JMCLOFPGGNN, COCECKPDIKC PNJAGJLLOPF, GLFDIPNOLKN OIOHIKMNMDI, GLFDIPNOLKN NLHNGDCKJCC)
	{
		this.JMCLOFPGGNN = JMCLOFPGGNN;
		this.PNJAGJLLOPF = PNJAGJLLOPF;
		this.OIOHIKMNMDI = OIOHIKMNMDI;
		this.NLHNGDCKJCC = NLHNGDCKJCC;
	}

	public LHCALAMFAOK(ALLINHNNNJN MIABODPHOIP)
	{
		JMCLOFPGGNN = GHKGMKFDJEM;
		PNJAGJLLOPF = BCGPEBDIJBA;
		OIOHIKMNMDI = EJGALDLJEII;
		NLHNGDCKJCC = HOAGBCIJFAI;
		for (int i = 0; i != MIABODPHOIP.GMCGMPEEHJP; i++)
		{
			PAANMJLACEF pAANMJLACEF = (PAANMJLACEF)MIABODPHOIP.ECNCPJGHBIG(i);
			switch (pAANMJLACEF.JPBIKBDCEKC)
			{
			case 0:
				JMCLOFPGGNN = COCECKPDIKC.BJLJCGFMFOO(pAANMJLACEF, true);
				break;
			case 1:
				PNJAGJLLOPF = COCECKPDIKC.BJLJCGFMFOO(pAANMJLACEF, true);
				break;
			case 2:
				OIOHIKMNMDI = GLFDIPNOLKN.BJLJCGFMFOO(pAANMJLACEF, true);
				break;
			case 3:
				NLHNGDCKJCC = GLFDIPNOLKN.BJLJCGFMFOO(pAANMJLACEF, true);
				break;
			default:
				throw new ArgumentException("unknown tag");
			}
		}
	}

	public static LHCALAMFAOK BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC == null || NEMEKIOEOLC is LHCALAMFAOK)
		{
			return (LHCALAMFAOK)NEMEKIOEOLC;
		}
		if (NEMEKIOEOLC is ALLINHNNNJN)
		{
			return new LHCALAMFAOK((ALLINHNNNJN)NEMEKIOEOLC);
		}
		throw new ArgumentException("Unknown object in factory: " + LHFGHNFJIKM.JKHOEKAOLPM(NEMEKIOEOLC), "obj");
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		DLDBGGDLOOO dLDBGGDLOOO = new DLDBGGDLOOO();
		if (!JMCLOFPGGNN.Equals(GHKGMKFDJEM))
		{
			dLDBGGDLOOO.JEACJNAKLDJ(new JIHIOOKBBLB(true, 0, JMCLOFPGGNN));
		}
		if (!PNJAGJLLOPF.Equals(BCGPEBDIJBA))
		{
			dLDBGGDLOOO.JEACJNAKLDJ(new JIHIOOKBBLB(true, 1, PNJAGJLLOPF));
		}
		if (!OIOHIKMNMDI.Equals(EJGALDLJEII))
		{
			dLDBGGDLOOO.JEACJNAKLDJ(new JIHIOOKBBLB(true, 2, OIOHIKMNMDI));
		}
		if (!NLHNGDCKJCC.Equals(HOAGBCIJFAI))
		{
			dLDBGGDLOOO.JEACJNAKLDJ(new JIHIOOKBBLB(true, 3, NLHNGDCKJCC));
		}
		return new KOGPLMALOEH(dLDBGGDLOOO);
	}
}
