using System;

internal class LIHNOJIAMLF : OMOBJNLGOBO
{
	public LIHNOJIAMLF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public LIHNOJIAMLF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal LIHNOJIAMLF(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new LIHNOJIAMLF(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		CKDMEPGJMAC cKDMEPGJMAC = (CKDMEPGJMAC)base.NBPANDNEJGI;
		CKDMEPGJMAC cKDMEPGJMAC2 = (CKDMEPGJMAC)base.FIJLKLCHMGH;
		CKDMEPGJMAC cKDMEPGJMAC3 = (CKDMEPGJMAC)BCIHLCMFAEK.NBPANDNEJGI;
		CKDMEPGJMAC cKDMEPGJMAC4 = (CKDMEPGJMAC)BCIHLCMFAEK.FIJLKLCHMGH;
		CKDMEPGJMAC cKDMEPGJMAC5 = (CKDMEPGJMAC)base.LAMGGDKLPJH[0];
		CKDMEPGJMAC cKDMEPGJMAC6 = (CKDMEPGJMAC)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = LAFMGEKEGBF.DCPJKFEDHOJ();
		uint[] array2 = LAFMGEKEGBF.PLIFFMMBNPM();
		uint[] array3 = LAFMGEKEGBF.PLIFFMMBNPM();
		uint[] array4 = LAFMGEKEGBF.PLIFFMMBNPM();
		bool flag = cKDMEPGJMAC5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = cKDMEPGJMAC3.AMFCENFNAJJ;
			array6 = cKDMEPGJMAC4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			BOKPIHHFBKJ.MIOEHGDPGAG(cKDMEPGJMAC5.AMFCENFNAJJ, array6);
			array5 = array2;
			BOKPIHHFBKJ.IBJBIGNPNEM(array6, cKDMEPGJMAC3.AMFCENFNAJJ, array5);
			BOKPIHHFBKJ.IBJBIGNPNEM(array6, cKDMEPGJMAC5.AMFCENFNAJJ, array6);
			BOKPIHHFBKJ.IBJBIGNPNEM(array6, cKDMEPGJMAC4.AMFCENFNAJJ, array6);
		}
		bool flag2 = cKDMEPGJMAC6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = cKDMEPGJMAC.AMFCENFNAJJ;
			array8 = cKDMEPGJMAC2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			BOKPIHHFBKJ.MIOEHGDPGAG(cKDMEPGJMAC6.AMFCENFNAJJ, array8);
			array7 = array;
			BOKPIHHFBKJ.IBJBIGNPNEM(array8, cKDMEPGJMAC.AMFCENFNAJJ, array7);
			BOKPIHHFBKJ.IBJBIGNPNEM(array8, cKDMEPGJMAC6.AMFCENFNAJJ, array8);
			BOKPIHHFBKJ.IBJBIGNPNEM(array8, cKDMEPGJMAC2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = LAFMGEKEGBF.PLIFFMMBNPM();
		BOKPIHHFBKJ.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		BOKPIHHFBKJ.FBGIHKPECCO(array8, array6, array10);
		if (LAFMGEKEGBF.EJJHHCOFAAI(array9))
		{
			if (LAFMGEKEGBF.EJJHHCOFAAI(array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		BOKPIHHFBKJ.MIOEHGDPGAG(array9, array11);
		uint[] array12 = LAFMGEKEGBF.PLIFFMMBNPM();
		BOKPIHHFBKJ.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		BOKPIHHFBKJ.IBJBIGNPNEM(array11, array7, array13);
		BOKPIHHFBKJ.BHKOFHMDACN(array12, array12);
		LAFMGEKEGBF.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = LAFMGEKEGBF.FIBDFFPCDGC(array13, array13, array12);
		BOKPIHHFBKJ.KKIGIOINLCI(aMFCENFNAJJ, array12);
		CKDMEPGJMAC cKDMEPGJMAC7 = new CKDMEPGJMAC(array4);
		BOKPIHHFBKJ.MIOEHGDPGAG(array10, cKDMEPGJMAC7.AMFCENFNAJJ);
		BOKPIHHFBKJ.FBGIHKPECCO(cKDMEPGJMAC7.AMFCENFNAJJ, array12, cKDMEPGJMAC7.AMFCENFNAJJ);
		CKDMEPGJMAC cKDMEPGJMAC8 = new CKDMEPGJMAC(array12);
		BOKPIHHFBKJ.FBGIHKPECCO(array13, cKDMEPGJMAC7.AMFCENFNAJJ, cKDMEPGJMAC8.AMFCENFNAJJ);
		BOKPIHHFBKJ.OMJFFHEIEFH(cKDMEPGJMAC8.AMFCENFNAJJ, array10, array);
		BOKPIHHFBKJ.BKCHMGKFECM(array, cKDMEPGJMAC8.AMFCENFNAJJ);
		CKDMEPGJMAC cKDMEPGJMAC9 = new CKDMEPGJMAC(array9);
		if (!flag)
		{
			BOKPIHHFBKJ.IBJBIGNPNEM(cKDMEPGJMAC9.AMFCENFNAJJ, cKDMEPGJMAC5.AMFCENFNAJJ, cKDMEPGJMAC9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			BOKPIHHFBKJ.IBJBIGNPNEM(cKDMEPGJMAC9.AMFCENFNAJJ, cKDMEPGJMAC6.AMFCENFNAJJ, cKDMEPGJMAC9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { cKDMEPGJMAC9 };
		return new LIHNOJIAMLF(bHPIABAGAPB, cKDMEPGJMAC7, cKDMEPGJMAC8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		CKDMEPGJMAC cKDMEPGJMAC = (CKDMEPGJMAC)base.FIJLKLCHMGH;
		if (cKDMEPGJMAC.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		CKDMEPGJMAC cKDMEPGJMAC2 = (CKDMEPGJMAC)base.NBPANDNEJGI;
		CKDMEPGJMAC cKDMEPGJMAC3 = (CKDMEPGJMAC)base.LAMGGDKLPJH[0];
		uint[] array = LAFMGEKEGBF.PLIFFMMBNPM();
		uint[] array2 = LAFMGEKEGBF.PLIFFMMBNPM();
		uint[] array3 = LAFMGEKEGBF.PLIFFMMBNPM();
		BOKPIHHFBKJ.MIOEHGDPGAG(cKDMEPGJMAC.AMFCENFNAJJ, array3);
		uint[] array4 = LAFMGEKEGBF.PLIFFMMBNPM();
		BOKPIHHFBKJ.MIOEHGDPGAG(array3, array4);
		bool flag = cKDMEPGJMAC3.EOJCHPEGABD;
		uint[] array5 = cKDMEPGJMAC3.AMFCENFNAJJ;
		if (!flag)
		{
			array5 = array2;
			BOKPIHHFBKJ.MIOEHGDPGAG(cKDMEPGJMAC3.AMFCENFNAJJ, array5);
		}
		BOKPIHHFBKJ.FBGIHKPECCO(cKDMEPGJMAC2.AMFCENFNAJJ, array5, array);
		uint[] array6 = array2;
		BOKPIHHFBKJ.JEACJNAKLDJ(cKDMEPGJMAC2.AMFCENFNAJJ, array5, array6);
		BOKPIHHFBKJ.IBJBIGNPNEM(array6, array, array6);
		uint aMFCENFNAJJ = LAFMGEKEGBF.FIBDFFPCDGC(array6, array6, array6);
		BOKPIHHFBKJ.KKIGIOINLCI(aMFCENFNAJJ, array6);
		uint[] array7 = array3;
		BOKPIHHFBKJ.IBJBIGNPNEM(array3, cKDMEPGJMAC2.AMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(4, array7, 2, 0u);
		BOKPIHHFBKJ.KKIGIOINLCI(aMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(4, array4, 3, 0u, array);
		BOKPIHHFBKJ.KKIGIOINLCI(aMFCENFNAJJ, array);
		CKDMEPGJMAC cKDMEPGJMAC4 = new CKDMEPGJMAC(array4);
		BOKPIHHFBKJ.MIOEHGDPGAG(array6, cKDMEPGJMAC4.AMFCENFNAJJ);
		BOKPIHHFBKJ.FBGIHKPECCO(cKDMEPGJMAC4.AMFCENFNAJJ, array7, cKDMEPGJMAC4.AMFCENFNAJJ);
		BOKPIHHFBKJ.FBGIHKPECCO(cKDMEPGJMAC4.AMFCENFNAJJ, array7, cKDMEPGJMAC4.AMFCENFNAJJ);
		CKDMEPGJMAC cKDMEPGJMAC5 = new CKDMEPGJMAC(array7);
		BOKPIHHFBKJ.FBGIHKPECCO(array7, cKDMEPGJMAC4.AMFCENFNAJJ, cKDMEPGJMAC5.AMFCENFNAJJ);
		BOKPIHHFBKJ.IBJBIGNPNEM(cKDMEPGJMAC5.AMFCENFNAJJ, array6, cKDMEPGJMAC5.AMFCENFNAJJ);
		BOKPIHHFBKJ.FBGIHKPECCO(cKDMEPGJMAC5.AMFCENFNAJJ, array, cKDMEPGJMAC5.AMFCENFNAJJ);
		CKDMEPGJMAC cKDMEPGJMAC6 = new CKDMEPGJMAC(array6);
		BOKPIHHFBKJ.LLGLJBDLBOP(cKDMEPGJMAC.AMFCENFNAJJ, cKDMEPGJMAC6.AMFCENFNAJJ);
		if (!flag)
		{
			BOKPIHHFBKJ.IBJBIGNPNEM(cKDMEPGJMAC6.AMFCENFNAJJ, cKDMEPGJMAC3.AMFCENFNAJJ, cKDMEPGJMAC6.AMFCENFNAJJ);
		}
		return new LIHNOJIAMLF(bHPIABAGAPB, cKDMEPGJMAC4, cKDMEPGJMAC5, new KBINBLGGLNE[1] { cKDMEPGJMAC6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new LIHNOJIAMLF(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
