using System;

internal class LKAHFJPBMHD : OMOBJNLGOBO
{
	public LKAHFJPBMHD(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public LKAHFJPBMHD(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal LKAHFJPBMHD(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new LKAHFJPBMHD(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		JOCDNFCLFEB jOCDNFCLFEB = (JOCDNFCLFEB)base.NBPANDNEJGI;
		JOCDNFCLFEB jOCDNFCLFEB2 = (JOCDNFCLFEB)base.FIJLKLCHMGH;
		JOCDNFCLFEB jOCDNFCLFEB3 = (JOCDNFCLFEB)BCIHLCMFAEK.NBPANDNEJGI;
		JOCDNFCLFEB jOCDNFCLFEB4 = (JOCDNFCLFEB)BCIHLCMFAEK.FIJLKLCHMGH;
		JOCDNFCLFEB jOCDNFCLFEB5 = (JOCDNFCLFEB)base.LAMGGDKLPJH[0];
		JOCDNFCLFEB jOCDNFCLFEB6 = (JOCDNFCLFEB)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = EJJGNFBFKIJ.DCPJKFEDHOJ();
		uint[] array2 = EJJGNFBFKIJ.PLIFFMMBNPM();
		uint[] array3 = EJJGNFBFKIJ.PLIFFMMBNPM();
		uint[] array4 = EJJGNFBFKIJ.PLIFFMMBNPM();
		bool flag = jOCDNFCLFEB5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = jOCDNFCLFEB3.AMFCENFNAJJ;
			array6 = jOCDNFCLFEB4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			JMFGKMOMPKE.MIOEHGDPGAG(jOCDNFCLFEB5.AMFCENFNAJJ, array6);
			array5 = array2;
			JMFGKMOMPKE.IBJBIGNPNEM(array6, jOCDNFCLFEB3.AMFCENFNAJJ, array5);
			JMFGKMOMPKE.IBJBIGNPNEM(array6, jOCDNFCLFEB5.AMFCENFNAJJ, array6);
			JMFGKMOMPKE.IBJBIGNPNEM(array6, jOCDNFCLFEB4.AMFCENFNAJJ, array6);
		}
		bool flag2 = jOCDNFCLFEB6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = jOCDNFCLFEB.AMFCENFNAJJ;
			array8 = jOCDNFCLFEB2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			JMFGKMOMPKE.MIOEHGDPGAG(jOCDNFCLFEB6.AMFCENFNAJJ, array8);
			array7 = array;
			JMFGKMOMPKE.IBJBIGNPNEM(array8, jOCDNFCLFEB.AMFCENFNAJJ, array7);
			JMFGKMOMPKE.IBJBIGNPNEM(array8, jOCDNFCLFEB6.AMFCENFNAJJ, array8);
			JMFGKMOMPKE.IBJBIGNPNEM(array8, jOCDNFCLFEB2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = EJJGNFBFKIJ.PLIFFMMBNPM();
		JMFGKMOMPKE.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		JMFGKMOMPKE.FBGIHKPECCO(array8, array6, array10);
		if (EJJGNFBFKIJ.EJJHHCOFAAI(array9))
		{
			if (EJJGNFBFKIJ.EJJHHCOFAAI(array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		JMFGKMOMPKE.MIOEHGDPGAG(array9, array11);
		uint[] array12 = EJJGNFBFKIJ.PLIFFMMBNPM();
		JMFGKMOMPKE.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		JMFGKMOMPKE.IBJBIGNPNEM(array11, array7, array13);
		JMFGKMOMPKE.BHKOFHMDACN(array12, array12);
		EJJGNFBFKIJ.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = EJJGNFBFKIJ.FIBDFFPCDGC(array13, array13, array12);
		JMFGKMOMPKE.KKIGIOINLCI(aMFCENFNAJJ, array12);
		JOCDNFCLFEB jOCDNFCLFEB7 = new JOCDNFCLFEB(array4);
		JMFGKMOMPKE.MIOEHGDPGAG(array10, jOCDNFCLFEB7.AMFCENFNAJJ);
		JMFGKMOMPKE.FBGIHKPECCO(jOCDNFCLFEB7.AMFCENFNAJJ, array12, jOCDNFCLFEB7.AMFCENFNAJJ);
		JOCDNFCLFEB jOCDNFCLFEB8 = new JOCDNFCLFEB(array12);
		JMFGKMOMPKE.FBGIHKPECCO(array13, jOCDNFCLFEB7.AMFCENFNAJJ, jOCDNFCLFEB8.AMFCENFNAJJ);
		JMFGKMOMPKE.OMJFFHEIEFH(jOCDNFCLFEB8.AMFCENFNAJJ, array10, array);
		JMFGKMOMPKE.BKCHMGKFECM(array, jOCDNFCLFEB8.AMFCENFNAJJ);
		JOCDNFCLFEB jOCDNFCLFEB9 = new JOCDNFCLFEB(array9);
		if (!flag)
		{
			JMFGKMOMPKE.IBJBIGNPNEM(jOCDNFCLFEB9.AMFCENFNAJJ, jOCDNFCLFEB5.AMFCENFNAJJ, jOCDNFCLFEB9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			JMFGKMOMPKE.IBJBIGNPNEM(jOCDNFCLFEB9.AMFCENFNAJJ, jOCDNFCLFEB6.AMFCENFNAJJ, jOCDNFCLFEB9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { jOCDNFCLFEB9 };
		return new LKAHFJPBMHD(bHPIABAGAPB, jOCDNFCLFEB7, jOCDNFCLFEB8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		JOCDNFCLFEB jOCDNFCLFEB = (JOCDNFCLFEB)base.FIJLKLCHMGH;
		if (jOCDNFCLFEB.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		JOCDNFCLFEB jOCDNFCLFEB2 = (JOCDNFCLFEB)base.NBPANDNEJGI;
		JOCDNFCLFEB jOCDNFCLFEB3 = (JOCDNFCLFEB)base.LAMGGDKLPJH[0];
		uint[] array = EJJGNFBFKIJ.PLIFFMMBNPM();
		uint[] array2 = EJJGNFBFKIJ.PLIFFMMBNPM();
		uint[] array3 = EJJGNFBFKIJ.PLIFFMMBNPM();
		JMFGKMOMPKE.MIOEHGDPGAG(jOCDNFCLFEB.AMFCENFNAJJ, array3);
		uint[] array4 = EJJGNFBFKIJ.PLIFFMMBNPM();
		JMFGKMOMPKE.MIOEHGDPGAG(array3, array4);
		bool flag = jOCDNFCLFEB3.EOJCHPEGABD;
		uint[] array5 = jOCDNFCLFEB3.AMFCENFNAJJ;
		if (!flag)
		{
			array5 = array2;
			JMFGKMOMPKE.MIOEHGDPGAG(jOCDNFCLFEB3.AMFCENFNAJJ, array5);
		}
		JMFGKMOMPKE.FBGIHKPECCO(jOCDNFCLFEB2.AMFCENFNAJJ, array5, array);
		uint[] array6 = array2;
		JMFGKMOMPKE.JEACJNAKLDJ(jOCDNFCLFEB2.AMFCENFNAJJ, array5, array6);
		JMFGKMOMPKE.IBJBIGNPNEM(array6, array, array6);
		uint aMFCENFNAJJ = EJJGNFBFKIJ.FIBDFFPCDGC(array6, array6, array6);
		JMFGKMOMPKE.KKIGIOINLCI(aMFCENFNAJJ, array6);
		uint[] array7 = array3;
		JMFGKMOMPKE.IBJBIGNPNEM(array3, jOCDNFCLFEB2.AMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(5, array7, 2, 0u);
		JMFGKMOMPKE.KKIGIOINLCI(aMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(5, array4, 3, 0u, array);
		JMFGKMOMPKE.KKIGIOINLCI(aMFCENFNAJJ, array);
		JOCDNFCLFEB jOCDNFCLFEB4 = new JOCDNFCLFEB(array4);
		JMFGKMOMPKE.MIOEHGDPGAG(array6, jOCDNFCLFEB4.AMFCENFNAJJ);
		JMFGKMOMPKE.FBGIHKPECCO(jOCDNFCLFEB4.AMFCENFNAJJ, array7, jOCDNFCLFEB4.AMFCENFNAJJ);
		JMFGKMOMPKE.FBGIHKPECCO(jOCDNFCLFEB4.AMFCENFNAJJ, array7, jOCDNFCLFEB4.AMFCENFNAJJ);
		JOCDNFCLFEB jOCDNFCLFEB5 = new JOCDNFCLFEB(array7);
		JMFGKMOMPKE.FBGIHKPECCO(array7, jOCDNFCLFEB4.AMFCENFNAJJ, jOCDNFCLFEB5.AMFCENFNAJJ);
		JMFGKMOMPKE.IBJBIGNPNEM(jOCDNFCLFEB5.AMFCENFNAJJ, array6, jOCDNFCLFEB5.AMFCENFNAJJ);
		JMFGKMOMPKE.FBGIHKPECCO(jOCDNFCLFEB5.AMFCENFNAJJ, array, jOCDNFCLFEB5.AMFCENFNAJJ);
		JOCDNFCLFEB jOCDNFCLFEB6 = new JOCDNFCLFEB(array6);
		JMFGKMOMPKE.LLGLJBDLBOP(jOCDNFCLFEB.AMFCENFNAJJ, jOCDNFCLFEB6.AMFCENFNAJJ);
		if (!flag)
		{
			JMFGKMOMPKE.IBJBIGNPNEM(jOCDNFCLFEB6.AMFCENFNAJJ, jOCDNFCLFEB3.AMFCENFNAJJ, jOCDNFCLFEB6.AMFCENFNAJJ);
		}
		return new LKAHFJPBMHD(bHPIABAGAPB, jOCDNFCLFEB4, jOCDNFCLFEB5, new KBINBLGGLNE[1] { jOCDNFCLFEB6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new LKAHFJPBMHD(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
