using Spine.Unity;

public class LKNNBABNCFC : ACDPFOPPPOP
{
	public LKNNBABNCFC(string MLNCFCEEFLL = "", string NDGJHCMKDON = "", bool DHPCLHLMCPG = true, bool JICOEKBHOFE = false)
	{
		base.MLNCFCEEFLL = MLNCFCEEFLL;
		base.NDGJHCMKDON = NDGJHCMKDON;
		base.DHPCLHLMCPG = DHPCLHLMCPG;
		base.JICOEKBHOFE = JICOEKBHOFE;
	}

	public static NBKCFDOMAPI CKAGENAKODN(string KELMMDNAGGK, SkeletonRenderer GGOAIKFJJEI)
	{
		return (GGOAIKFJJEI.skeleton != null) ? GGOAIKFJJEI.skeleton.NMLBCOPEEDC(KELMMDNAGGK) : null;
	}

	public static GPJIPDIEIIL GLLLNHPMGAG(string KELMMDNAGGK, SkeletonDataAsset KAFMHICMBHN)
	{
		KGMHJGFNPFC kGMHJGFNPFC = KAFMHICMBHN.CPILINNBJLL(true);
		return kGMHJGFNPFC.NMLBCOPEEDC(KELMMDNAGGK);
	}
}
