public class LMIJMHPEHJJ : BEKINJKCAJB
{
	public override ECBKNMOGLEG NBOGEPALJBP(CGDEGBGOKJO MBEMNOCDDBC, int EELDCJOKNOM, int OELMNFIJNEJ)
	{
		switch (EELDCJOKNOM)
		{
		case 7:
			return DIECGECPPDM(MBEMNOCDDBC, OELMNFIJNEJ);
		case 8:
			return EPINNMOOHJJ(MBEMNOCDDBC, 16, OELMNFIJNEJ);
		case 15:
			return NHIDPICFACJ(MBEMNOCDDBC, 16, 16);
		case 16:
			return NHIDPICFACJ(MBEMNOCDDBC, 16, 8);
		case 10:
			return HCDIKGLDLPF(MBEMNOCDDBC, 16, 16);
		case 103:
			return MIEJONMHACP(MBEMNOCDDBC, 16, 12);
		case 9:
			return EPINNMOOHJJ(MBEMNOCDDBC, 32, OELMNFIJNEJ);
		case 17:
			return NHIDPICFACJ(MBEMNOCDDBC, 32, 16);
		case 18:
			return NHIDPICFACJ(MBEMNOCDDBC, 32, 8);
		case 11:
			return HCDIKGLDLPF(MBEMNOCDDBC, 32, 16);
		case 104:
			return MIEJONMHACP(MBEMNOCDDBC, 32, 12);
		case 12:
			return PGNGNIKIPKG(MBEMNOCDDBC, 16, OELMNFIJNEJ);
		case 19:
			return FABPGGKBEMH(MBEMNOCDDBC, 16, 16);
		case 13:
			return PGNGNIKIPKG(MBEMNOCDDBC, 32, OELMNFIJNEJ);
		case 20:
			return FABPGGKBEMH(MBEMNOCDDBC, 32, 16);
		case 102:
			return BLNHPLNMPHN(MBEMNOCDDBC);
		case 0:
			return PPDJGMPPJPJ(MBEMNOCDDBC, OELMNFIJNEJ);
		case 2:
			return FEIFELAOCLH(MBEMNOCDDBC, 16, OELMNFIJNEJ);
		case 14:
			return KGCJGKPGPJD(MBEMNOCDDBC, OELMNFIJNEJ);
		default:
			throw new DEIDBCPPCMB(80);
		}
	}

	protected virtual AEFLFOFIBCC EPINNMOOHJJ(CGDEGBGOKJO MBEMNOCDDBC, int NAJNLOODBFL, int OELMNFIJNEJ)
	{
		return new AEFLFOFIBCC(MBEMNOCDDBC, FNHBPMKCHLK(), FNHBPMKCHLK(), JAMJNHEJMPF(OELMNFIJNEJ), JAMJNHEJMPF(OELMNFIJNEJ), NAJNLOODBFL);
	}

	protected virtual AEFLFOFIBCC PGNGNIKIPKG(CGDEGBGOKJO MBEMNOCDDBC, int NAJNLOODBFL, int OELMNFIJNEJ)
	{
		return new AEFLFOFIBCC(MBEMNOCDDBC, BPCMHANNAOK(), BPCMHANNAOK(), JAMJNHEJMPF(OELMNFIJNEJ), JAMJNHEJMPF(OELMNFIJNEJ), NAJNLOODBFL);
	}

	protected virtual ECBKNMOGLEG BLNHPLNMPHN(CGDEGBGOKJO MBEMNOCDDBC)
	{
		return new MAJELBICLDD(MBEMNOCDDBC);
	}

	protected virtual ELBFPPEBMNH NHIDPICFACJ(CGDEGBGOKJO MBEMNOCDDBC, int NAJNLOODBFL, int DLFPGGOCGNE)
	{
		return new ELBFPPEBMNH(MBEMNOCDDBC, ONBAOKJIEPM(), ONBAOKJIEPM(), NAJNLOODBFL, DLFPGGOCGNE);
	}

	protected virtual ELBFPPEBMNH HCDIKGLDLPF(CGDEGBGOKJO MBEMNOCDDBC, int NAJNLOODBFL, int DLFPGGOCGNE)
	{
		return new ELBFPPEBMNH(MBEMNOCDDBC, MJGHOHFNGKA(), MJGHOHFNGKA(), NAJNLOODBFL, DLFPGGOCGNE);
	}

	protected virtual ELBFPPEBMNH MIEJONMHACP(CGDEGBGOKJO MBEMNOCDDBC, int NAJNLOODBFL, int DLFPGGOCGNE)
	{
		return new ELBFPPEBMNH(MBEMNOCDDBC, EMAIHGKNCCF(), EMAIHGKNCCF(), NAJNLOODBFL, DLFPGGOCGNE, 2);
	}

	protected virtual ELBFPPEBMNH FABPGGKBEMH(CGDEGBGOKJO MBEMNOCDDBC, int NAJNLOODBFL, int DLFPGGOCGNE)
	{
		return new ELBFPPEBMNH(MBEMNOCDDBC, CFLOOEDFBPH(), CFLOOEDFBPH(), NAJNLOODBFL, DLFPGGOCGNE);
	}

	protected virtual AEFLFOFIBCC DIECGECPPDM(CGDEGBGOKJO MBEMNOCDDBC, int OELMNFIJNEJ)
	{
		return new AEFLFOFIBCC(MBEMNOCDDBC, ILHFFCLJDIO(), ILHFFCLJDIO(), JAMJNHEJMPF(OELMNFIJNEJ), JAMJNHEJMPF(OELMNFIJNEJ), 24);
	}

	protected virtual HIKKGKGPJII PPDJGMPPJPJ(CGDEGBGOKJO MBEMNOCDDBC, int OELMNFIJNEJ)
	{
		return new HIKKGKGPJII(MBEMNOCDDBC, JAMJNHEJMPF(OELMNFIJNEJ), JAMJNHEJMPF(OELMNFIJNEJ));
	}

	protected virtual MIDPALCBHJE FEIFELAOCLH(CGDEGBGOKJO MBEMNOCDDBC, int NAJNLOODBFL, int OELMNFIJNEJ)
	{
		return new MIDPALCBHJE(MBEMNOCDDBC, DIGMKDKNKKJ(), DIGMKDKNKKJ(), JAMJNHEJMPF(OELMNFIJNEJ), JAMJNHEJMPF(OELMNFIJNEJ), NAJNLOODBFL, false);
	}

	protected virtual AEFLFOFIBCC KGCJGKPGPJD(CGDEGBGOKJO MBEMNOCDDBC, int OELMNFIJNEJ)
	{
		return new AEFLFOFIBCC(MBEMNOCDDBC, DNMFENNCEGD(), DNMFENNCEGD(), JAMJNHEJMPF(OELMNFIJNEJ), JAMJNHEJMPF(OELMNFIJNEJ), 16);
	}

	protected virtual JMPFLJGHAIM GPJLIMCIFLA()
	{
		return new ACHFNMAJJOK();
	}

	protected virtual JMPFLJGHAIM FALJKDEPPHE()
	{
		return new EONJLOEDDIL();
	}

	protected virtual JMPFLJGHAIM FNHBPMKCHLK()
	{
		return new OJGBFLKAPOB(GPJLIMCIFLA());
	}

	protected virtual KJLBDGGBCCF ONBAOKJIEPM()
	{
		return new DHAFOFMKGGG(GPJLIMCIFLA());
	}

	protected virtual KJLBDGGBCCF MJGHOHFNGKA()
	{
		return new LIPBIBIDEDF(GPJLIMCIFLA());
	}

	protected virtual KJLBDGGBCCF EMAIHGKNCCF()
	{
		return new HJNLHLHBNGF(GPJLIMCIFLA(), GPJLIMCIFLA());
	}

	protected virtual KJLBDGGBCCF CFLOOEDFBPH()
	{
		return new LIPBIBIDEDF(FALJKDEPPHE());
	}

	protected virtual JMPFLJGHAIM BPCMHANNAOK()
	{
		return new OJGBFLKAPOB(FALJKDEPPHE());
	}

	protected virtual JMPFLJGHAIM ILHFFCLJDIO()
	{
		return new OJGBFLKAPOB(new KAMMIHKEGPK());
	}

	protected virtual KPMKFMEEJCJ DIGMKDKNKKJ()
	{
		return new DCEMOGMJCDG();
	}

	protected virtual JMPFLJGHAIM DNMFENNCEGD()
	{
		return new OJGBFLKAPOB(new LKNEIIOFGPC());
	}

	protected virtual BJLAMONNNDD JAMJNHEJMPF(int OELMNFIJNEJ)
	{
		switch (OELMNFIJNEJ)
		{
		case 0:
			return null;
		case 1:
			return KINEBFNENMB.KNADNPDKLGD(1);
		case 2:
			return KINEBFNENMB.KNADNPDKLGD(2);
		case 3:
			return KINEBFNENMB.KNADNPDKLGD(4);
		case 4:
			return KINEBFNENMB.KNADNPDKLGD(5);
		case 5:
			return KINEBFNENMB.KNADNPDKLGD(6);
		default:
			throw new DEIDBCPPCMB(80);
		}
	}
}
