using System;
using System.Collections.Generic;

public class LOHACGBPPIN
{
	public string NKKEKBHCFFF { get; set; }

	public string HKCNCCIAMEL { get; set; }

	public string BCJMJBCPCML { get; set; }

	public bool APGADMJLPNI { get; set; }

	public Dictionary<string, object> GGBPDOGFIJM { get; set; }

	public LOHACGBPPIN()
	{
	}

	public LOHACGBPPIN(Dictionary<string, string> MJMFIMLGGDO)
	{
		if (MJMFIMLGGDO != null)
		{
			NKKEKBHCFFF = FMKNBJCOMGF.NMLBPNNMFLP(MJMFIMLGGDO, FMKNBJCOMGF.IKIHDNHNJMH);
			HKCNCCIAMEL = FMKNBJCOMGF.NMLBPNNMFLP(MJMFIMLGGDO, FMKNBJCOMGF.LIDJAANKHHG);
			BCJMJBCPCML = FMKNBJCOMGF.NMLBPNNMFLP(MJMFIMLGGDO, FMKNBJCOMGF.NMCEFJHKBMH);
			APGADMJLPNI = bool.Parse(FMKNBJCOMGF.NMLBPNNMFLP(MJMFIMLGGDO, FMKNBJCOMGF.KAMLHHLKLFA));
			bool result;
			if (bool.TryParse(FMKNBJCOMGF.NMLBPNNMFLP(MJMFIMLGGDO, FMKNBJCOMGF.KAMLHHLKLFA), out result))
			{
				APGADMJLPNI = result;
			}
			string lGMNAIAFHAH = FMKNBJCOMGF.NMLBPNNMFLP(MJMFIMLGGDO, FMKNBJCOMGF.GLHPCCFHMGA);
			DPKJGBCDECA dPKJGBCDECA = EDFILMGHHDD.DHCLOMIANOE(lGMNAIAFHAH);
			if (DPKJGBCDECA.BLPPLFIKFPN(dPKJGBCDECA, null) && DPKJGBCDECA.BLPPLFIKFPN(dPKJGBCDECA.JPIHKOGIKHA, null))
			{
				GGBPDOGFIJM = new Dictionary<string, object>();
				FMKNBJCOMGF.LMHFPJICNLH(dPKJGBCDECA.JPIHKOGIKHA, GGBPDOGFIJM);
			}
		}
	}

	public LOHACGBPPIN(string HDGFMHEHJBG)
	{
		DPKJGBCDECA dPKJGBCDECA = EDFILMGHHDD.DHCLOMIANOE(HDGFMHEHJBG);
		if (!DPKJGBCDECA.OCAFFLHPIMM(dPKJGBCDECA, null))
		{
			NKKEKBHCFFF = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.IKIHDNHNJMH);
			HKCNCCIAMEL = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.LIDJAANKHHG);
			BCJMJBCPCML = FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.NMCEFJHKBMH);
			APGADMJLPNI = Convert.ToBoolean(FMKNBJCOMGF.FNFGIMGMIEM(dPKJGBCDECA, FMKNBJCOMGF.KAMLHHLKLFA));
			DPKJGBCDECA dPKJGBCDECA2 = dPKJGBCDECA.ECNCPJGHBIG(FMKNBJCOMGF.GLHPCCFHMGA);
			if (!DPKJGBCDECA.OCAFFLHPIMM(dPKJGBCDECA2, null) && !DPKJGBCDECA.OCAFFLHPIMM(dPKJGBCDECA2.JPIHKOGIKHA, null))
			{
				GGBPDOGFIJM = new Dictionary<string, object>();
				FMKNBJCOMGF.LMHFPJICNLH(dPKJGBCDECA2.JPIHKOGIKHA, GGBPDOGFIJM);
			}
		}
	}

	public void IMMACHKDLEC(string IPBFAAFEJBC)
	{
		DPKJGBCDECA dPKJGBCDECA = EDFILMGHHDD.DHCLOMIANOE(IPBFAAFEJBC);
		if (!DPKJGBCDECA.OCAFFLHPIMM(dPKJGBCDECA, null))
		{
			GGBPDOGFIJM = new Dictionary<string, object>();
			FMKNBJCOMGF.LMHFPJICNLH(dPKJGBCDECA.JPIHKOGIKHA, GGBPDOGFIJM);
		}
	}

	public string ACGHBPBADDG()
	{
		return FMKNBJCOMGF.DPJGPBJKFJA(GGBPDOGFIJM);
	}
}
