using System;
using Org.BouncyCastle.Math;

public class LPKAACGCLJA : EJLHHPBLEMF
{
	public override KBINBLGGLNE LGFGMGPDEIB
	{
		get
		{
			int num = FMBBJLCHHDI;
			if (num == 5 || num == 6)
			{
				KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
				KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
				if (base.IFCDKFANPBO || kBINBLGGLNE.EJJHHCOFAAI)
				{
					return kBINBLGGLNE2;
				}
				KBINBLGGLNE kBINBLGGLNE3 = kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE).IBJBIGNPNEM(kBINBLGGLNE);
				if (num == 6)
				{
					KBINBLGGLNE kBINBLGGLNE4 = base.LAMGGDKLPJH[0];
					if (!kBINBLGGLNE4.EOJCHPEGABD)
					{
						kBINBLGGLNE3 = kBINBLGGLNE3.MCPDGENJCDB(kBINBLGGLNE4);
					}
				}
				return kBINBLGGLNE3;
			}
			return base.FIJLKLCHMGH;
		}
	}

	protected internal override bool NLPBPDPOOAK
	{
		get
		{
			KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
			if (kBINBLGGLNE.EJJHHCOFAAI)
			{
				return false;
			}
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			int num = FMBBJLCHHDI;
			if (num == 5 || num == 6)
			{
				return kBINBLGGLNE2.OFGNPBCCHAA() != kBINBLGGLNE.OFGNPBCCHAA();
			}
			return kBINBLGGLNE2.MCPDGENJCDB(kBINBLGGLNE).OFGNPBCCHAA();
		}
	}

	public LPKAACGCLJA(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public LPKAACGCLJA(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
		if (AMFCENFNAJJ != null)
		{
			HMFDKDDBGPO.FOAIMOICGCC(AMFCENFNAJJ, CNLILOEEBOJ);
			if (NINILENHPHE != null)
			{
				HMFDKDDBGPO.FOAIMOICGCC(AMFCENFNAJJ, NINILENHPHE.JEHECJGFJEB);
			}
		}
	}

	internal LPKAACGCLJA(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	[Obsolete("Use ECCurve.Infinity property")]
	public LPKAACGCLJA(BHPIABAGAPB NINILENHPHE)
		: this(NINILENHPHE, null, null)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new LPKAACGCLJA(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		int num = bHPIABAGAPB.DHBHKHGFIKI;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE2 = BCIHLCMFAEK.NBPANDNEJGI;
		switch (num)
		{
		case 0:
		{
			KBINBLGGLNE kBINBLGGLNE36 = base.FIJLKLCHMGH;
			KBINBLGGLNE bCIHLCMFAEK4 = BCIHLCMFAEK.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE37 = kBINBLGGLNE.JEACJNAKLDJ(kBINBLGGLNE2);
			KBINBLGGLNE kBINBLGGLNE38 = kBINBLGGLNE36.JEACJNAKLDJ(bCIHLCMFAEK4);
			if (kBINBLGGLNE37.EJJHHCOFAAI)
			{
				if (kBINBLGGLNE38.EJJHHCOFAAI)
				{
					return LLGLJBDLBOP();
				}
				return bHPIABAGAPB.EFOLNCNGADB;
			}
			KBINBLGGLNE kBINBLGGLNE39 = kBINBLGGLNE38.MCPDGENJCDB(kBINBLGGLNE37);
			KBINBLGGLNE kBINBLGGLNE40 = kBINBLGGLNE39.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE39).JEACJNAKLDJ(kBINBLGGLNE37)
				.JEACJNAKLDJ(bHPIABAGAPB.JEHECJGFJEB);
			KBINBLGGLNE cNLILOEEBOJ3 = kBINBLGGLNE39.IBJBIGNPNEM(kBINBLGGLNE.JEACJNAKLDJ(kBINBLGGLNE40)).JEACJNAKLDJ(kBINBLGGLNE40).JEACJNAKLDJ(kBINBLGGLNE36);
			return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE40, cNLILOEEBOJ3, base.BPGGHHMMCCB);
		}
		case 1:
		{
			KBINBLGGLNE kBINBLGGLNE21 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE22 = base.LAMGGDKLPJH[0];
			KBINBLGGLNE kBINBLGGLNE23 = BCIHLCMFAEK.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE24 = BCIHLCMFAEK.LAMGGDKLPJH[0];
			bool flag3 = kBINBLGGLNE22.EOJCHPEGABD;
			KBINBLGGLNE kBINBLGGLNE25 = kBINBLGGLNE23;
			KBINBLGGLNE kBINBLGGLNE26 = kBINBLGGLNE2;
			if (!flag3)
			{
				kBINBLGGLNE25 = kBINBLGGLNE25.IBJBIGNPNEM(kBINBLGGLNE22);
				kBINBLGGLNE26 = kBINBLGGLNE26.IBJBIGNPNEM(kBINBLGGLNE22);
			}
			bool flag4 = kBINBLGGLNE24.EOJCHPEGABD;
			KBINBLGGLNE kBINBLGGLNE27 = kBINBLGGLNE21;
			KBINBLGGLNE kBINBLGGLNE28 = kBINBLGGLNE;
			if (!flag4)
			{
				kBINBLGGLNE27 = kBINBLGGLNE27.IBJBIGNPNEM(kBINBLGGLNE24);
				kBINBLGGLNE28 = kBINBLGGLNE28.IBJBIGNPNEM(kBINBLGGLNE24);
			}
			KBINBLGGLNE kBINBLGGLNE29 = kBINBLGGLNE25.JEACJNAKLDJ(kBINBLGGLNE27);
			KBINBLGGLNE kBINBLGGLNE30 = kBINBLGGLNE26.JEACJNAKLDJ(kBINBLGGLNE28);
			if (kBINBLGGLNE30.EJJHHCOFAAI)
			{
				if (kBINBLGGLNE29.EJJHHCOFAAI)
				{
					return LLGLJBDLBOP();
				}
				return bHPIABAGAPB.EFOLNCNGADB;
			}
			KBINBLGGLNE kBINBLGGLNE31 = kBINBLGGLNE30.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE32 = kBINBLGGLNE31.IBJBIGNPNEM(kBINBLGGLNE30);
			KBINBLGGLNE bCIHLCMFAEK2 = (flag3 ? kBINBLGGLNE24 : ((!flag4) ? kBINBLGGLNE22.IBJBIGNPNEM(kBINBLGGLNE24) : kBINBLGGLNE22));
			KBINBLGGLNE kBINBLGGLNE33 = kBINBLGGLNE29.JEACJNAKLDJ(kBINBLGGLNE30);
			KBINBLGGLNE kBINBLGGLNE34 = kBINBLGGLNE33.CIDGMJAFLHM(kBINBLGGLNE29, kBINBLGGLNE31, bHPIABAGAPB.JEHECJGFJEB).IBJBIGNPNEM(bCIHLCMFAEK2).JEACJNAKLDJ(kBINBLGGLNE32);
			KBINBLGGLNE aMFCENFNAJJ = kBINBLGGLNE30.IBJBIGNPNEM(kBINBLGGLNE34);
			KBINBLGGLNE bCIHLCMFAEK3 = ((!flag4) ? kBINBLGGLNE31.IBJBIGNPNEM(kBINBLGGLNE24) : kBINBLGGLNE31);
			KBINBLGGLNE cNLILOEEBOJ2 = kBINBLGGLNE29.CIDGMJAFLHM(kBINBLGGLNE, kBINBLGGLNE30, kBINBLGGLNE21).CIDGMJAFLHM(bCIHLCMFAEK3, kBINBLGGLNE33, kBINBLGGLNE34);
			KBINBLGGLNE kBINBLGGLNE35 = kBINBLGGLNE32.IBJBIGNPNEM(bCIHLCMFAEK2);
			return new LPKAACGCLJA(bHPIABAGAPB, aMFCENFNAJJ, cNLILOEEBOJ2, new KBINBLGGLNE[1] { kBINBLGGLNE35 }, base.BPGGHHMMCCB);
		}
		case 6:
		{
			if (kBINBLGGLNE.EJJHHCOFAAI)
			{
				if (kBINBLGGLNE2.EJJHHCOFAAI)
				{
					return bHPIABAGAPB.EFOLNCNGADB;
				}
				return BCIHLCMFAEK.JEACJNAKLDJ(this);
			}
			KBINBLGGLNE kBINBLGGLNE3 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE4 = base.LAMGGDKLPJH[0];
			KBINBLGGLNE kBINBLGGLNE5 = BCIHLCMFAEK.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE6 = BCIHLCMFAEK.LAMGGDKLPJH[0];
			bool flag = kBINBLGGLNE4.EOJCHPEGABD;
			KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE2;
			KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE5;
			if (!flag)
			{
				kBINBLGGLNE7 = kBINBLGGLNE7.IBJBIGNPNEM(kBINBLGGLNE4);
				kBINBLGGLNE8 = kBINBLGGLNE8.IBJBIGNPNEM(kBINBLGGLNE4);
			}
			bool flag2 = kBINBLGGLNE6.EOJCHPEGABD;
			KBINBLGGLNE kBINBLGGLNE9 = kBINBLGGLNE;
			KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE3;
			if (!flag2)
			{
				kBINBLGGLNE9 = kBINBLGGLNE9.IBJBIGNPNEM(kBINBLGGLNE6);
				kBINBLGGLNE10 = kBINBLGGLNE10.IBJBIGNPNEM(kBINBLGGLNE6);
			}
			KBINBLGGLNE kBINBLGGLNE11 = kBINBLGGLNE10.JEACJNAKLDJ(kBINBLGGLNE8);
			KBINBLGGLNE kBINBLGGLNE12 = kBINBLGGLNE9.JEACJNAKLDJ(kBINBLGGLNE7);
			if (kBINBLGGLNE12.EJJHHCOFAAI)
			{
				if (kBINBLGGLNE11.EJJHHCOFAAI)
				{
					return LLGLJBDLBOP();
				}
				return bHPIABAGAPB.EFOLNCNGADB;
			}
			KBINBLGGLNE kBINBLGGLNE15;
			KBINBLGGLNE cNLILOEEBOJ;
			KBINBLGGLNE kBINBLGGLNE17;
			if (kBINBLGGLNE2.EJJHHCOFAAI)
			{
				JGAFKLGGBGF jGAFKLGGBGF = MIHJHLFLHNA();
				kBINBLGGLNE = jGAFKLGGBGF.NBPANDNEJGI;
				KBINBLGGLNE kBINBLGGLNE13 = jGAFKLGGBGF.LGFGMGPDEIB;
				KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE5;
				KBINBLGGLNE kBINBLGGLNE14 = kBINBLGGLNE13.JEACJNAKLDJ(bCIHLCMFAEK).MCPDGENJCDB(kBINBLGGLNE);
				kBINBLGGLNE15 = kBINBLGGLNE14.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE14).JEACJNAKLDJ(kBINBLGGLNE)
					.JEACJNAKLDJ(bHPIABAGAPB.JEHECJGFJEB);
				if (kBINBLGGLNE15.EJJHHCOFAAI)
				{
					return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE15, bHPIABAGAPB.FPKDKHJKEEF.PAEDNKEIDOM(), base.BPGGHHMMCCB);
				}
				KBINBLGGLNE kBINBLGGLNE16 = kBINBLGGLNE14.IBJBIGNPNEM(kBINBLGGLNE.JEACJNAKLDJ(kBINBLGGLNE15)).JEACJNAKLDJ(kBINBLGGLNE15).JEACJNAKLDJ(kBINBLGGLNE13);
				cNLILOEEBOJ = kBINBLGGLNE16.MCPDGENJCDB(kBINBLGGLNE15).JEACJNAKLDJ(kBINBLGGLNE15);
				kBINBLGGLNE17 = bHPIABAGAPB.HFENNGHNFLF(BigInteger.One);
			}
			else
			{
				kBINBLGGLNE12 = kBINBLGGLNE12.MIOEHGDPGAG();
				KBINBLGGLNE kBINBLGGLNE18 = kBINBLGGLNE11.IBJBIGNPNEM(kBINBLGGLNE9);
				KBINBLGGLNE kBINBLGGLNE19 = kBINBLGGLNE11.IBJBIGNPNEM(kBINBLGGLNE7);
				kBINBLGGLNE15 = kBINBLGGLNE18.IBJBIGNPNEM(kBINBLGGLNE19);
				if (kBINBLGGLNE15.EJJHHCOFAAI)
				{
					return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE15, bHPIABAGAPB.FPKDKHJKEEF.PAEDNKEIDOM(), base.BPGGHHMMCCB);
				}
				KBINBLGGLNE kBINBLGGLNE20 = kBINBLGGLNE11.IBJBIGNPNEM(kBINBLGGLNE12);
				if (!flag2)
				{
					kBINBLGGLNE20 = kBINBLGGLNE20.IBJBIGNPNEM(kBINBLGGLNE6);
				}
				cNLILOEEBOJ = kBINBLGGLNE19.JEACJNAKLDJ(kBINBLGGLNE12).FGLCIBKKKFF(kBINBLGGLNE20, kBINBLGGLNE3.JEACJNAKLDJ(kBINBLGGLNE4));
				kBINBLGGLNE17 = kBINBLGGLNE20;
				if (!flag)
				{
					kBINBLGGLNE17 = kBINBLGGLNE17.IBJBIGNPNEM(kBINBLGGLNE4);
				}
			}
			return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE15, cNLILOEEBOJ, new KBINBLGGLNE[1] { kBINBLGGLNE17 }, base.BPGGHHMMCCB);
		}
		default:
			throw new InvalidOperationException("unsupported coordinate system");
		}
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		switch (bHPIABAGAPB.DHBHKHGFIKI)
		{
		case 0:
		{
			KBINBLGGLNE kBINBLGGLNE15 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE16 = kBINBLGGLNE15.MCPDGENJCDB(kBINBLGGLNE).JEACJNAKLDJ(kBINBLGGLNE);
			KBINBLGGLNE aMFCENFNAJJ = kBINBLGGLNE16.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE16).JEACJNAKLDJ(bHPIABAGAPB.JEHECJGFJEB);
			KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE.FGLCIBKKKFF(aMFCENFNAJJ, kBINBLGGLNE16.AOAINNMNBHC());
			return new LPKAACGCLJA(bHPIABAGAPB, aMFCENFNAJJ, cNLILOEEBOJ, base.BPGGHHMMCCB);
		}
		case 1:
		{
			KBINBLGGLNE kBINBLGGLNE17 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE18 = base.LAMGGDKLPJH[0];
			bool flag2 = kBINBLGGLNE18.EOJCHPEGABD;
			KBINBLGGLNE kBINBLGGLNE19 = ((!flag2) ? kBINBLGGLNE.IBJBIGNPNEM(kBINBLGGLNE18) : kBINBLGGLNE);
			KBINBLGGLNE bCIHLCMFAEK2 = ((!flag2) ? kBINBLGGLNE17.IBJBIGNPNEM(kBINBLGGLNE18) : kBINBLGGLNE17);
			KBINBLGGLNE kBINBLGGLNE20 = kBINBLGGLNE.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE21 = kBINBLGGLNE20.JEACJNAKLDJ(bCIHLCMFAEK2);
			KBINBLGGLNE kBINBLGGLNE22 = kBINBLGGLNE19;
			KBINBLGGLNE kBINBLGGLNE23 = kBINBLGGLNE22.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE24 = kBINBLGGLNE21.JEACJNAKLDJ(kBINBLGGLNE22);
			KBINBLGGLNE kBINBLGGLNE25 = kBINBLGGLNE24.CIDGMJAFLHM(kBINBLGGLNE21, kBINBLGGLNE23, bHPIABAGAPB.JEHECJGFJEB);
			KBINBLGGLNE aMFCENFNAJJ2 = kBINBLGGLNE22.IBJBIGNPNEM(kBINBLGGLNE25);
			KBINBLGGLNE cNLILOEEBOJ2 = kBINBLGGLNE20.MIOEHGDPGAG().CIDGMJAFLHM(kBINBLGGLNE22, kBINBLGGLNE25, kBINBLGGLNE24);
			KBINBLGGLNE kBINBLGGLNE26 = kBINBLGGLNE22.IBJBIGNPNEM(kBINBLGGLNE23);
			return new LPKAACGCLJA(bHPIABAGAPB, aMFCENFNAJJ2, cNLILOEEBOJ2, new KBINBLGGLNE[1] { kBINBLGGLNE26 }, base.BPGGHHMMCCB);
		}
		case 6:
		{
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
			bool flag = kBINBLGGLNE3.EOJCHPEGABD;
			KBINBLGGLNE kBINBLGGLNE4 = ((!flag) ? kBINBLGGLNE2.IBJBIGNPNEM(kBINBLGGLNE3) : kBINBLGGLNE2);
			KBINBLGGLNE kBINBLGGLNE5 = ((!flag) ? kBINBLGGLNE3.MIOEHGDPGAG() : kBINBLGGLNE3);
			KBINBLGGLNE kBINBLGGLNE6 = bHPIABAGAPB.JEHECJGFJEB;
			KBINBLGGLNE kBINBLGGLNE7 = ((!flag) ? kBINBLGGLNE6.IBJBIGNPNEM(kBINBLGGLNE5) : kBINBLGGLNE6);
			KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE2.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE4).JEACJNAKLDJ(kBINBLGGLNE7);
			if (kBINBLGGLNE8.EJJHHCOFAAI)
			{
				return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE8, bHPIABAGAPB.FPKDKHJKEEF.PAEDNKEIDOM(), base.BPGGHHMMCCB);
			}
			KBINBLGGLNE kBINBLGGLNE9 = kBINBLGGLNE8.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE10 = ((!flag) ? kBINBLGGLNE8.IBJBIGNPNEM(kBINBLGGLNE5) : kBINBLGGLNE8);
			KBINBLGGLNE kBINBLGGLNE11 = bHPIABAGAPB.FPKDKHJKEEF;
			KBINBLGGLNE kBINBLGGLNE13;
			if (kBINBLGGLNE11.LBAGICKMJNP < bHPIABAGAPB.PJNLBAHOKGC >> 1)
			{
				KBINBLGGLNE kBINBLGGLNE12 = kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE).MIOEHGDPGAG();
				KBINBLGGLNE bCIHLCMFAEK = ((!kBINBLGGLNE11.EOJCHPEGABD) ? kBINBLGGLNE7.FGLCIBKKKFF(kBINBLGGLNE11, kBINBLGGLNE5.MIOEHGDPGAG()) : kBINBLGGLNE7.JEACJNAKLDJ(kBINBLGGLNE5).MIOEHGDPGAG());
				kBINBLGGLNE13 = kBINBLGGLNE12.JEACJNAKLDJ(kBINBLGGLNE8).JEACJNAKLDJ(kBINBLGGLNE5).IBJBIGNPNEM(kBINBLGGLNE12)
					.JEACJNAKLDJ(bCIHLCMFAEK)
					.JEACJNAKLDJ(kBINBLGGLNE9);
				if (kBINBLGGLNE6.EJJHHCOFAAI)
				{
					kBINBLGGLNE13 = kBINBLGGLNE13.JEACJNAKLDJ(kBINBLGGLNE10);
				}
				else if (!kBINBLGGLNE6.EOJCHPEGABD)
				{
					kBINBLGGLNE13 = kBINBLGGLNE13.JEACJNAKLDJ(kBINBLGGLNE6.AOAINNMNBHC().IBJBIGNPNEM(kBINBLGGLNE10));
				}
			}
			else
			{
				KBINBLGGLNE kBINBLGGLNE14 = ((!flag) ? kBINBLGGLNE.IBJBIGNPNEM(kBINBLGGLNE3) : kBINBLGGLNE);
				kBINBLGGLNE13 = kBINBLGGLNE14.FGLCIBKKKFF(kBINBLGGLNE8, kBINBLGGLNE4).JEACJNAKLDJ(kBINBLGGLNE9).JEACJNAKLDJ(kBINBLGGLNE10);
			}
			return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE9, kBINBLGGLNE13, new KBINBLGGLNE[1] { kBINBLGGLNE10 }, base.BPGGHHMMCCB);
		}
		default:
			throw new InvalidOperationException("unsupported coordinate system");
		}
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		int num = bHPIABAGAPB.DHBHKHGFIKI;
		if (num == 6)
		{
			KBINBLGGLNE kBINBLGGLNE2 = BCIHLCMFAEK.NBPANDNEJGI;
			KBINBLGGLNE kBINBLGGLNE3 = BCIHLCMFAEK.LAMGGDKLPJH[0];
			if (kBINBLGGLNE2.EJJHHCOFAAI || !kBINBLGGLNE3.EOJCHPEGABD)
			{
				return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
			}
			KBINBLGGLNE kBINBLGGLNE4 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE5 = base.LAMGGDKLPJH[0];
			KBINBLGGLNE kBINBLGGLNE6 = BCIHLCMFAEK.FIJLKLCHMGH;
			KBINBLGGLNE aMFCENFNAJJ = kBINBLGGLNE.MIOEHGDPGAG();
			KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE4.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE5.MIOEHGDPGAG();
			KBINBLGGLNE bCIHLCMFAEK2 = kBINBLGGLNE4.IBJBIGNPNEM(kBINBLGGLNE5);
			KBINBLGGLNE bCIHLCMFAEK3 = bHPIABAGAPB.JEHECJGFJEB.IBJBIGNPNEM(kBINBLGGLNE7).JEACJNAKLDJ(bCIHLCMFAEK).JEACJNAKLDJ(bCIHLCMFAEK2);
			KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE6.AOAINNMNBHC();
			KBINBLGGLNE kBINBLGGLNE9 = bHPIABAGAPB.JEHECJGFJEB.JEACJNAKLDJ(kBINBLGGLNE8).IBJBIGNPNEM(kBINBLGGLNE7).JEACJNAKLDJ(bCIHLCMFAEK)
				.CIDGMJAFLHM(bCIHLCMFAEK3, aMFCENFNAJJ, kBINBLGGLNE7);
			KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE2.IBJBIGNPNEM(kBINBLGGLNE7);
			KBINBLGGLNE kBINBLGGLNE11 = kBINBLGGLNE10.JEACJNAKLDJ(bCIHLCMFAEK3).MIOEHGDPGAG();
			if (kBINBLGGLNE11.EJJHHCOFAAI)
			{
				if (kBINBLGGLNE9.EJJHHCOFAAI)
				{
					return BCIHLCMFAEK.LLGLJBDLBOP();
				}
				return bHPIABAGAPB.EFOLNCNGADB;
			}
			if (kBINBLGGLNE9.EJJHHCOFAAI)
			{
				return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE9, bHPIABAGAPB.FPKDKHJKEEF.PAEDNKEIDOM(), base.BPGGHHMMCCB);
			}
			KBINBLGGLNE aMFCENFNAJJ2 = kBINBLGGLNE9.MIOEHGDPGAG().IBJBIGNPNEM(kBINBLGGLNE10);
			KBINBLGGLNE kBINBLGGLNE12 = kBINBLGGLNE9.IBJBIGNPNEM(kBINBLGGLNE11).IBJBIGNPNEM(kBINBLGGLNE7);
			KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE9.JEACJNAKLDJ(kBINBLGGLNE11).MIOEHGDPGAG().CIDGMJAFLHM(bCIHLCMFAEK3, kBINBLGGLNE8, kBINBLGGLNE12);
			return new LPKAACGCLJA(bHPIABAGAPB, aMFCENFNAJJ2, cNLILOEEBOJ, new KBINBLGGLNE[1] { kBINBLGGLNE12 }, base.BPGGHHMMCCB);
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		switch (bHPIABAGAPB.DHBHKHGFIKI)
		{
		case 0:
		{
			KBINBLGGLNE kBINBLGGLNE7 = base.FIJLKLCHMGH;
			return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE, kBINBLGGLNE7.JEACJNAKLDJ(kBINBLGGLNE), base.BPGGHHMMCCB);
		}
		case 1:
		{
			KBINBLGGLNE kBINBLGGLNE5 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE6 = base.LAMGGDKLPJH[0];
			return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE, kBINBLGGLNE5.JEACJNAKLDJ(kBINBLGGLNE), new KBINBLGGLNE[1] { kBINBLGGLNE6 }, base.BPGGHHMMCCB);
		}
		case 5:
		{
			KBINBLGGLNE kBINBLGGLNE4 = base.FIJLKLCHMGH;
			return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE, kBINBLGGLNE4.AOAINNMNBHC(), base.BPGGHHMMCCB);
		}
		case 6:
		{
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
			return new LPKAACGCLJA(bHPIABAGAPB, kBINBLGGLNE, kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE3), new KBINBLGGLNE[1] { kBINBLGGLNE3 }, base.BPGGHHMMCCB);
		}
		default:
			throw new InvalidOperationException("unsupported coordinate system");
		}
	}
}
