using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

public class MADFPPJCOIM : DLDDFKDFKEF
{
	private readonly APPIMCFMFNG NJCPCACOCGB;

	private int JHMBNAOHDAN;

	private static MADFPPJCOIM KNPOFJNFLJB;

	[CompilerGenerated]
	private static Comparison<NIGFCEFLHML> EBCOMJBLIPP;

	public static MADFPPJCOIM GABGKBAKHDP
	{
		get
		{
			if (KNPOFJNFLJB == null)
			{
				KNPOFJNFLJB = new MADFPPJCOIM();
			}
			return KNPOFJNFLJB;
		}
	}

	private MADFPPJCOIM()
	{
		NJCPCACOCGB = new APPIMCFMFNG();
	}

	public void OMOKOKFNBKI()
	{
		JHMBNAOHDAN = 0;
		NJCPCACOCGB.BBGLCADIONK();
	}

	public NIGFCEFLHML ACDBBJACJOE(int KIGOGMKCDKN)
	{
		return NJCPCACOCGB.ACDBBJACJOE(KIGOGMKCDKN);
	}

	public int NAJIPFBGLLC()
	{
		if (JHMBNAOHDAN == 0)
		{
			JHMBNAOHDAN = NJCPCACOCGB.NAJIPFBGLLC();
		}
		return JHMBNAOHDAN;
	}

	public void BELCBGIMFJK(NIGFCEFLHML MEHIELGIEBI)
	{
		JHMBNAOHDAN = 0;
		NJCPCACOCGB.BJNFGAFBCGJ(MEHIELGIEBI);
	}

	public List<NIGFCEFLHML> NJHNMKHFJMB()
	{
		return NJCPCACOCGB.NJHNMKHFJMB();
	}

	public bool IHIKJJMGNPJ()
	{
		return NJCPCACOCGB.IHIKJJMGNPJ();
	}

	public void CGINNGBOKAP(int KIGOGMKCDKN, int MGCMMJPNJPH, int HCCBDFMKLHN)
	{
		if (KIGOGMKCDKN <= NAJIPFBGLLC())
		{
			GBFAPADEBEC.PFGLLCEKCGI(PBIIDJOKNEK.LevelHelper, "Highest level will not be updated. Old Highest Level: {0}, New Highest Level: {1}", NAJIPFBGLLC(), KIGOGMKCDKN);
			return;
		}
		JHMBNAOHDAN = 0;
		NIGFCEFLHML nIGFCEFLHML = ACDBBJACJOE(KIGOGMKCDKN);
		int num = 1;
		if (MGCMMJPNJPH > nIGFCEFLHML.DJADMBLKBKJ)
		{
			nIGFCEFLHML.DJADMBLKBKJ = MGCMMJPNJPH;
			num = 0;
		}
		if (HCCBDFMKLHN > nIGFCEFLHML.EMNDJNDGANP)
		{
			nIGFCEFLHML.EMNDJNDGANP = HCCBDFMKLHN;
			num = 0;
		}
		nIGFCEFLHML.FOJDLLGGJID = num;
		if (num == 0)
		{
			BELCBGIMFJK(nIGFCEFLHML);
		}
	}

	public void CNGDJEHLCBA(List<NIGFCEFLHML> HAANBKOOOIP)
	{
		if (HAANBKOOOIP != null)
		{
			LNDHDLFFFBM(HAANBKOOOIP);
			HAANBKOOOIP.Sort((NIGFCEFLHML MNIMEAMHNMI, NIGFCEFLHML BCIHLCMFAEK) => (MNIMEAMHNMI.PDGLECFDLJJ > BCIHLCMFAEK.PDGLECFDLJJ) ? (-1) : ((MNIMEAMHNMI.PDGLECFDLJJ != BCIHLCMFAEK.PDGLECFDLJJ) ? 1 : 0));
			NIGFCEFLHML nIGFCEFLHML = HAANBKOOOIP[0];
			nIGFCEFLHML.FOJDLLGGJID = 1;
			JHMBNAOHDAN = 0;
			NJCPCACOCGB.BJNFGAFBCGJ(nIGFCEFLHML);
		}
	}

	private void LNDHDLFFFBM(List<NIGFCEFLHML> HAANBKOOOIP)
	{
		int i = 0;
		for (int count = HAANBKOOOIP.Count; i < count; i++)
		{
			NIGFCEFLHML nIGFCEFLHML = HAANBKOOOIP[i];
			if (nIGFCEFLHML != null)
			{
				nIGFCEFLHML.FOJDLLGGJID = 1;
				NJCPCACOCGB.GDFHLDAKIOM(nIGFCEFLHML);
			}
		}
		NJCPCACOCGB.LNDHDLFFFBM();
	}

	public void HPIALFCEIND(NIGFCEFLHML MEHIELGIEBI)
	{
		JHMBNAOHDAN = 0;
		NJCPCACOCGB.IKIOFOOBHDM(MEHIELGIEBI);
	}

	[CompilerGenerated]
	private static int HNOMFJLECGA(NIGFCEFLHML MNIMEAMHNMI, NIGFCEFLHML BCIHLCMFAEK)
	{
		return (MNIMEAMHNMI.PDGLECFDLJJ > BCIHLCMFAEK.PDGLECFDLJJ) ? (-1) : ((MNIMEAMHNMI.PDGLECFDLJJ != BCIHLCMFAEK.PDGLECFDLJJ) ? 1 : 0);
	}
}
