using System;

public class MAJELBICLDD : ECBKNMOGLEG
{
	private static readonly byte[] DIIELANKELL = new byte[15];

	protected readonly CGDEGBGOKJO MBEMNOCDDBC;

	protected readonly JGKHBDNEHOG OEOENDBGPLC;

	protected readonly JGKHBDNEHOG MHBEDFNGKOD;

	protected readonly byte[] JACMCHDDJGA;

	protected readonly byte[] KGAJACPLOPO;

	public MAJELBICLDD(CGDEGBGOKJO MBEMNOCDDBC)
	{
		if (!KINEBFNENMB.OHGCLELCPMD(MBEMNOCDDBC))
		{
			throw new DEIDBCPPCMB(80);
		}
		this.MBEMNOCDDBC = MBEMNOCDDBC;
		int num = 32;
		int num2 = 12;
		int num3 = 2 * num + 2 * num2;
		byte[] array = KINEBFNENMB.IJLFLBPLJHD(MBEMNOCDDBC, num3);
		int num4 = 0;
		JEMNCGMEABF jEMNCGMEABF = new JEMNCGMEABF(array, num4, num);
		num4 += num;
		JEMNCGMEABF jEMNCGMEABF2 = new JEMNCGMEABF(array, num4, num);
		num4 += num;
		byte[] array2 = NOGCEBKPPJE.EHLHBAMJLNI(array, num4, num4 + num2);
		num4 += num2;
		byte[] array3 = NOGCEBKPPJE.EHLHBAMJLNI(array, num4, num4 + num2);
		num4 += num2;
		if (num4 != num3)
		{
			throw new DEIDBCPPCMB(80);
		}
		OEOENDBGPLC = new JGKHBDNEHOG();
		MHBEDFNGKOD = new JGKHBDNEHOG();
		JEMNCGMEABF iJJHBEECMBP;
		JEMNCGMEABF iJJHBEECMBP2;
		if (MBEMNOCDDBC.DLHCCNKGKJP)
		{
			iJJHBEECMBP = jEMNCGMEABF2;
			iJJHBEECMBP2 = jEMNCGMEABF;
			JACMCHDDJGA = array3;
			KGAJACPLOPO = array2;
		}
		else
		{
			iJJHBEECMBP = jEMNCGMEABF;
			iJJHBEECMBP2 = jEMNCGMEABF2;
			JACMCHDDJGA = array2;
			KGAJACPLOPO = array3;
		}
		OEOENDBGPLC.DIOELAHNLKJ(true, new CHCELGDKEJG(iJJHBEECMBP, JACMCHDDJGA));
		MHBEDFNGKOD.DIOELAHNLKJ(false, new CHCELGDKEJG(iJJHBEECMBP2, KGAJACPLOPO));
	}

	public virtual int LBEOGHDBCJM(int DOILBJKOFDG)
	{
		return DOILBJKOFDG - 16;
	}

	public virtual byte[] BIIKEIOAPCJ(long MHCDKMMAMKP, byte NBFBPNNEKMN, byte[] NEOIPBBDIMB, int IBNDGNOIEEF, int NBEDPKHALCN)
	{
		JEMNCGMEABF pEOANNDPNFC = FGEIHMDDMFE(OEOENDBGPLC, true, MHCDKMMAMKP, JACMCHDDJGA);
		byte[] array = new byte[NBEDPKHALCN + 16];
		OEOENDBGPLC.POCAGALIPAI(NEOIPBBDIMB, IBNDGNOIEEF, NBEDPKHALCN, array, 0);
		byte[] iBCOLBMIDPG = ELIMFJJGAMN(MHCDKMMAMKP, NBFBPNNEKMN, NBEDPKHALCN);
		byte[] array2 = FLMLEAOGAJN(pEOANNDPNFC, iBCOLBMIDPG, array, 0, NBEDPKHALCN);
		Array.Copy(array2, 0, array, NBEDPKHALCN, array2.Length);
		return array;
	}

	public virtual byte[] OBMCLFEIPBL(long MHCDKMMAMKP, byte NBFBPNNEKMN, byte[] JNGDHEECGIG, int IBNDGNOIEEF, int NBEDPKHALCN)
	{
		if (LBEOGHDBCJM(NBEDPKHALCN) < 0)
		{
			throw new DEIDBCPPCMB(50);
		}
		JEMNCGMEABF pEOANNDPNFC = FGEIHMDDMFE(MHBEDFNGKOD, false, MHCDKMMAMKP, KGAJACPLOPO);
		int num = NBEDPKHALCN - 16;
		byte[] iBCOLBMIDPG = ELIMFJJGAMN(MHCDKMMAMKP, NBFBPNNEKMN, num);
		byte[] mNIMEAMHNMI = FLMLEAOGAJN(pEOANNDPNFC, iBCOLBMIDPG, JNGDHEECGIG, IBNDGNOIEEF, num);
		byte[] bCIHLCMFAEK = NOGCEBKPPJE.EHLHBAMJLNI(JNGDHEECGIG, IBNDGNOIEEF + num, IBNDGNOIEEF + NBEDPKHALCN);
		if (!NOGCEBKPPJE.PBBFCJBKJEN(mNIMEAMHNMI, bCIHLCMFAEK))
		{
			throw new DEIDBCPPCMB(20);
		}
		byte[] array = new byte[num];
		MHBEDFNGKOD.POCAGALIPAI(JNGDHEECGIG, IBNDGNOIEEF, num, array, 0);
		return array;
	}

	protected virtual JEMNCGMEABF FGEIHMDDMFE(KPMKFMEEJCJ IEDPBFAFGGJ, bool MAEALKEJALK, long MHCDKMMAMKP, byte[] NDEFBOJOALL)
	{
		byte[] nDEFBOJOALL = KFDAKEINBBI(MHCDKMMAMKP, NDEFBOJOALL);
		IEDPBFAFGGJ.DIOELAHNLKJ(MAEALKEJALK, new CHCELGDKEJG(null, nDEFBOJOALL));
		return GNEIGCEFFJL(IEDPBFAFGGJ);
	}

	protected virtual byte[] KFDAKEINBBI(long MHCDKMMAMKP, byte[] NDEFBOJOALL)
	{
		byte[] array = new byte[12];
		KINEBFNENMB.JCMFNDAOIPC(MHCDKMMAMKP, array, 4);
		for (int i = 0; i < 12; i++)
		{
			array[i] ^= NDEFBOJOALL[i];
		}
		return array;
	}

	protected virtual JEMNCGMEABF GNEIGCEFFJL(KPMKFMEEJCJ IEDPBFAFGGJ)
	{
		byte[] array = new byte[64];
		IEDPBFAFGGJ.POCAGALIPAI(array, 0, array.Length, array, 0);
		JEMNCGMEABF result = new JEMNCGMEABF(array, 0, 32);
		NOGCEBKPPJE.MEBLOMPDLEJ(array, 0);
		return result;
	}

	protected virtual byte[] FLMLEAOGAJN(JEMNCGMEABF PEOANNDPNFC, byte[] IBCOLBMIDPG, byte[] GHPCHPOHELF, int JBAJPGIAPFF, int NBEDPKHALCN)
	{
		PHFBFDEAHMD pHFBFDEAHMD = new INPJACNELFB();
		pHFBFDEAHMD.DIOELAHNLKJ(PEOANNDPNFC);
		PLLOIFKGPGM(pHFBFDEAHMD, IBCOLBMIDPG, 0, IBCOLBMIDPG.Length);
		PLLOIFKGPGM(pHFBFDEAHMD, GHPCHPOHELF, JBAJPGIAPFF, NBEDPKHALCN);
		BJKJNJMNKNC(pHFBFDEAHMD, IBCOLBMIDPG.Length);
		BJKJNJMNKNC(pHFBFDEAHMD, NBEDPKHALCN);
		return DEOKPGHGOPK.LCNOFBMOHHM(pHFBFDEAHMD);
	}

	protected virtual void BJKJNJMNKNC(PHFBFDEAHMD LGMMFPHDIMH, int NBEDPKHALCN)
	{
		byte[] array = PGOKFBKEOAB.ICLMPOAFJKJ((ulong)NBEDPKHALCN);
		LGMMFPHDIMH.GONEEEFEDGF(array, 0, array.Length);
	}

	protected virtual void PLLOIFKGPGM(PHFBFDEAHMD LGMMFPHDIMH, byte[] GHPCHPOHELF, int JBAJPGIAPFF, int NBEDPKHALCN)
	{
		LGMMFPHDIMH.GONEEEFEDGF(GHPCHPOHELF, JBAJPGIAPFF, NBEDPKHALCN);
		int num = NBEDPKHALCN % 16;
		if (num != 0)
		{
			LGMMFPHDIMH.GONEEEFEDGF(DIIELANKELL, 0, 16 - num);
		}
	}

	protected virtual byte[] ELIMFJJGAMN(long MHCDKMMAMKP, byte NBFBPNNEKMN, int NBEDPKHALCN)
	{
		byte[] array = new byte[13];
		KINEBFNENMB.JCMFNDAOIPC(MHCDKMMAMKP, array, 0);
		KINEBFNENMB.JBOHOOBEPAM(NBFBPNNEKMN, array, 8);
		KINEBFNENMB.PPCDKILMGFD(MBEMNOCDDBC.PJJKOIEAGJN, array, 9);
		KINEBFNENMB.PGBAOHFKNHN(NBEDPKHALCN, array, 11);
		return array;
	}
}
