using System;

internal class MBNKDPDFKMO : OMOBJNLGOBO
{
	public MBNKDPDFKMO(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public MBNKDPDFKMO(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal MBNKDPDFKMO(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new MBNKDPDFKMO(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		BHADNAKAJHP bHADNAKAJHP = (BHADNAKAJHP)base.NBPANDNEJGI;
		BHADNAKAJHP bHADNAKAJHP2 = (BHADNAKAJHP)base.FIJLKLCHMGH;
		BHADNAKAJHP bHADNAKAJHP3 = (BHADNAKAJHP)BCIHLCMFAEK.NBPANDNEJGI;
		BHADNAKAJHP bHADNAKAJHP4 = (BHADNAKAJHP)BCIHLCMFAEK.FIJLKLCHMGH;
		BHADNAKAJHP bHADNAKAJHP5 = (BHADNAKAJHP)base.LAMGGDKLPJH[0];
		BHADNAKAJHP bHADNAKAJHP6 = (BHADNAKAJHP)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = BCMDHIIJKJE.PLIFFMMBNPM(24);
		uint[] array2 = BCMDHIIJKJE.PLIFFMMBNPM(24);
		uint[] array3 = BCMDHIIJKJE.PLIFFMMBNPM(12);
		uint[] array4 = BCMDHIIJKJE.PLIFFMMBNPM(12);
		bool flag = bHADNAKAJHP5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = bHADNAKAJHP3.AMFCENFNAJJ;
			array6 = bHADNAKAJHP4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			ANDMCOGOAAD.MIOEHGDPGAG(bHADNAKAJHP5.AMFCENFNAJJ, array6);
			array5 = array2;
			ANDMCOGOAAD.IBJBIGNPNEM(array6, bHADNAKAJHP3.AMFCENFNAJJ, array5);
			ANDMCOGOAAD.IBJBIGNPNEM(array6, bHADNAKAJHP5.AMFCENFNAJJ, array6);
			ANDMCOGOAAD.IBJBIGNPNEM(array6, bHADNAKAJHP4.AMFCENFNAJJ, array6);
		}
		bool flag2 = bHADNAKAJHP6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = bHADNAKAJHP.AMFCENFNAJJ;
			array8 = bHADNAKAJHP2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			ANDMCOGOAAD.MIOEHGDPGAG(bHADNAKAJHP6.AMFCENFNAJJ, array8);
			array7 = array;
			ANDMCOGOAAD.IBJBIGNPNEM(array8, bHADNAKAJHP.AMFCENFNAJJ, array7);
			ANDMCOGOAAD.IBJBIGNPNEM(array8, bHADNAKAJHP6.AMFCENFNAJJ, array8);
			ANDMCOGOAAD.IBJBIGNPNEM(array8, bHADNAKAJHP2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = BCMDHIIJKJE.PLIFFMMBNPM(12);
		ANDMCOGOAAD.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = BCMDHIIJKJE.PLIFFMMBNPM(12);
		ANDMCOGOAAD.FBGIHKPECCO(array8, array6, array10);
		if (BCMDHIIJKJE.EJJHHCOFAAI(12, array9))
		{
			if (BCMDHIIJKJE.EJJHHCOFAAI(12, array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		ANDMCOGOAAD.MIOEHGDPGAG(array9, array11);
		uint[] array12 = BCMDHIIJKJE.PLIFFMMBNPM(12);
		ANDMCOGOAAD.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		ANDMCOGOAAD.IBJBIGNPNEM(array11, array7, array13);
		ANDMCOGOAAD.BHKOFHMDACN(array12, array12);
		JACKOMDKHEF.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = BCMDHIIJKJE.FIBDFFPCDGC(12, array13, array13, array12);
		ANDMCOGOAAD.KKIGIOINLCI(aMFCENFNAJJ, array12);
		BHADNAKAJHP bHADNAKAJHP7 = new BHADNAKAJHP(array4);
		ANDMCOGOAAD.MIOEHGDPGAG(array10, bHADNAKAJHP7.AMFCENFNAJJ);
		ANDMCOGOAAD.FBGIHKPECCO(bHADNAKAJHP7.AMFCENFNAJJ, array12, bHADNAKAJHP7.AMFCENFNAJJ);
		BHADNAKAJHP bHADNAKAJHP8 = new BHADNAKAJHP(array12);
		ANDMCOGOAAD.FBGIHKPECCO(array13, bHADNAKAJHP7.AMFCENFNAJJ, bHADNAKAJHP8.AMFCENFNAJJ);
		JACKOMDKHEF.BMEIFJDODCF(bHADNAKAJHP8.AMFCENFNAJJ, array10, array2);
		ANDMCOGOAAD.KGBEKKMEBCN(array, array2, array);
		ANDMCOGOAAD.BKCHMGKFECM(array, bHADNAKAJHP8.AMFCENFNAJJ);
		BHADNAKAJHP bHADNAKAJHP9 = new BHADNAKAJHP(array9);
		if (!flag)
		{
			ANDMCOGOAAD.IBJBIGNPNEM(bHADNAKAJHP9.AMFCENFNAJJ, bHADNAKAJHP5.AMFCENFNAJJ, bHADNAKAJHP9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			ANDMCOGOAAD.IBJBIGNPNEM(bHADNAKAJHP9.AMFCENFNAJJ, bHADNAKAJHP6.AMFCENFNAJJ, bHADNAKAJHP9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { bHADNAKAJHP9 };
		return new MBNKDPDFKMO(bHPIABAGAPB, bHADNAKAJHP7, bHADNAKAJHP8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		BHADNAKAJHP bHADNAKAJHP = (BHADNAKAJHP)base.FIJLKLCHMGH;
		if (bHADNAKAJHP.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		BHADNAKAJHP bHADNAKAJHP2 = (BHADNAKAJHP)base.NBPANDNEJGI;
		BHADNAKAJHP bHADNAKAJHP3 = (BHADNAKAJHP)base.LAMGGDKLPJH[0];
		uint[] array = BCMDHIIJKJE.PLIFFMMBNPM(12);
		uint[] array2 = BCMDHIIJKJE.PLIFFMMBNPM(12);
		uint[] array3 = BCMDHIIJKJE.PLIFFMMBNPM(12);
		ANDMCOGOAAD.MIOEHGDPGAG(bHADNAKAJHP.AMFCENFNAJJ, array3);
		uint[] array4 = BCMDHIIJKJE.PLIFFMMBNPM(12);
		ANDMCOGOAAD.MIOEHGDPGAG(array3, array4);
		bool flag = bHADNAKAJHP3.EOJCHPEGABD;
		uint[] array5 = bHADNAKAJHP3.AMFCENFNAJJ;
		if (!flag)
		{
			array5 = array2;
			ANDMCOGOAAD.MIOEHGDPGAG(bHADNAKAJHP3.AMFCENFNAJJ, array5);
		}
		ANDMCOGOAAD.FBGIHKPECCO(bHADNAKAJHP2.AMFCENFNAJJ, array5, array);
		uint[] array6 = array2;
		ANDMCOGOAAD.JEACJNAKLDJ(bHADNAKAJHP2.AMFCENFNAJJ, array5, array6);
		ANDMCOGOAAD.IBJBIGNPNEM(array6, array, array6);
		uint aMFCENFNAJJ = BCMDHIIJKJE.FIBDFFPCDGC(12, array6, array6, array6);
		ANDMCOGOAAD.KKIGIOINLCI(aMFCENFNAJJ, array6);
		uint[] array7 = array3;
		ANDMCOGOAAD.IBJBIGNPNEM(array3, bHADNAKAJHP2.AMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(12, array7, 2, 0u);
		ANDMCOGOAAD.KKIGIOINLCI(aMFCENFNAJJ, array7);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(12, array4, 3, 0u, array);
		ANDMCOGOAAD.KKIGIOINLCI(aMFCENFNAJJ, array);
		BHADNAKAJHP bHADNAKAJHP4 = new BHADNAKAJHP(array4);
		ANDMCOGOAAD.MIOEHGDPGAG(array6, bHADNAKAJHP4.AMFCENFNAJJ);
		ANDMCOGOAAD.FBGIHKPECCO(bHADNAKAJHP4.AMFCENFNAJJ, array7, bHADNAKAJHP4.AMFCENFNAJJ);
		ANDMCOGOAAD.FBGIHKPECCO(bHADNAKAJHP4.AMFCENFNAJJ, array7, bHADNAKAJHP4.AMFCENFNAJJ);
		BHADNAKAJHP bHADNAKAJHP5 = new BHADNAKAJHP(array7);
		ANDMCOGOAAD.FBGIHKPECCO(array7, bHADNAKAJHP4.AMFCENFNAJJ, bHADNAKAJHP5.AMFCENFNAJJ);
		ANDMCOGOAAD.IBJBIGNPNEM(bHADNAKAJHP5.AMFCENFNAJJ, array6, bHADNAKAJHP5.AMFCENFNAJJ);
		ANDMCOGOAAD.FBGIHKPECCO(bHADNAKAJHP5.AMFCENFNAJJ, array, bHADNAKAJHP5.AMFCENFNAJJ);
		BHADNAKAJHP bHADNAKAJHP6 = new BHADNAKAJHP(array6);
		ANDMCOGOAAD.LLGLJBDLBOP(bHADNAKAJHP.AMFCENFNAJJ, bHADNAKAJHP6.AMFCENFNAJJ);
		if (!flag)
		{
			ANDMCOGOAAD.IBJBIGNPNEM(bHADNAKAJHP6.AMFCENFNAJJ, bHADNAKAJHP3.AMFCENFNAJJ, bHADNAKAJHP6.AMFCENFNAJJ);
		}
		return new MBNKDPDFKMO(bHPIABAGAPB, bHADNAKAJHP4, bHADNAKAJHP5, new KBINBLGGLNE[1] { bHADNAKAJHP6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new MBNKDPDFKMO(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
