using System;
using Org.BouncyCastle.Math;

public class MCONFEBHMDC : KLOGJEJCNNM
{
	internal static readonly string MIBNLJLILLI = "bc_wtnaf";

	protected override JGAFKLGGBGF OJGDKAJCDJK(JGAFKLGGBGF KJPPPBMDJKG, BigInteger BENKLGPHLGI)
	{
		if (!(KJPPPBMDJKG is EJLHHPBLEMF))
		{
			throw new ArgumentException("Only AbstractF2mPoint can be used in WTauNafMultiplier");
		}
		EJLHHPBLEMF eJLHHPBLEMF = (EJLHHPBLEMF)KJPPPBMDJKG;
		DJABAMMOHPF dJABAMMOHPF = (DJABAMMOHPF)eJLHHPBLEMF.ECFGFKNLLGH;
		int cEKMAJAHNAG = dJABAMMOHPF.PJNLBAHOKGC;
		sbyte b = (sbyte)dJABAMMOHPF.JEHECJGFJEB.DOJBPIFPALJ().IntValue;
		sbyte pPFMEPBJCJC = NNAJFEGEGMI.GFBKMOHINEI(b);
		BigInteger[] iBBBMACIBGK = dJABAMMOHPF.GIFOICAMFFP();
		CNFFFHILNNA iLPILGOPJLI = NNAJFEGEGMI.JICLJHPHGHI(BENKLGPHLGI, cEKMAJAHNAG, b, iBBBMACIBGK, pPFMEPBJCJC, 10);
		return EOIAOELEJPF(eJLHHPBLEMF, iLPILGOPJLI, dJABAMMOHPF.IBLDMGPNNBD(eJLHHPBLEMF, MIBNLJLILLI), b, pPFMEPBJCJC);
	}

	private EJLHHPBLEMF EOIAOELEJPF(EJLHHPBLEMF HPHBDNBJPHB, CNFFFHILNNA ILPILGOPJLI, LJCCHFLFGJG DAPLBLGNCPK, sbyte MNIMEAMHNMI, sbyte PPFMEPBJCJC)
	{
		CNFFFHILNNA[] kBKMPEOMABI = ((MNIMEAMHNMI != 0) ? NNAJFEGEGMI.PHCIMMNBODL : NNAJFEGEGMI.BNMKGLHKIKK);
		BigInteger oFODBIAOKEP = NNAJFEGEGMI.MCPAMPKHMCI(PPFMEPBJCJC, 4);
		sbyte[] oJOAGEHFPNP = NNAJFEGEGMI.IHFIFLFJGEK(PPFMEPBJCJC, ILPILGOPJLI, 4, BigInteger.AGLOJCOAJIK(16L), oFODBIAOKEP, kBKMPEOMABI);
		return NELPFDKLPCD(HPHBDNBJPHB, oJOAGEHFPNP, DAPLBLGNCPK);
	}

	private static EJLHHPBLEMF NELPFDKLPCD(EJLHHPBLEMF HPHBDNBJPHB, sbyte[] OJOAGEHFPNP, LJCCHFLFGJG DAPLBLGNCPK)
	{
		DJABAMMOHPF dJABAMMOHPF = (DJABAMMOHPF)HPHBDNBJPHB.ECFGFKNLLGH;
		sbyte mNIMEAMHNMI = (sbyte)dJABAMMOHPF.JEHECJGFJEB.DOJBPIFPALJ().IntValue;
		EJLHHPBLEMF[] array;
		if (DAPLBLGNCPK == null || !(DAPLBLGNCPK is NFKJNIMBJNC))
		{
			array = NNAJFEGEGMI.GACNJDOFGMG(HPHBDNBJPHB, mNIMEAMHNMI);
			NFKJNIMBJNC nFKJNIMBJNC = new NFKJNIMBJNC();
			nFKJNIMBJNC.JJFOMCAIJPO = array;
			dJABAMMOHPF.OOGGMOCFMHH(HPHBDNBJPHB, MIBNLJLILLI, nFKJNIMBJNC);
		}
		else
		{
			array = ((NFKJNIMBJNC)DAPLBLGNCPK).JJFOMCAIJPO;
		}
		EJLHHPBLEMF[] array2 = new EJLHHPBLEMF[array.Length];
		for (int i = 0; i < array.Length; i++)
		{
			array2[i] = (EJLHHPBLEMF)array[i].BHKOFHMDACN();
		}
		EJLHHPBLEMF eJLHHPBLEMF = (EJLHHPBLEMF)HPHBDNBJPHB.ECFGFKNLLGH.EFOLNCNGADB;
		int num = 0;
		for (int num2 = OJOAGEHFPNP.Length - 1; num2 >= 0; num2--)
		{
			num++;
			int num3 = OJOAGEHFPNP[num2];
			if (num3 != 0)
			{
				eJLHHPBLEMF = eJLHHPBLEMF.HHBAGDLPLMK(num);
				num = 0;
				JGAFKLGGBGF bCIHLCMFAEK = ((num3 <= 0) ? array2[-num3 >> 1] : array[num3 >> 1]);
				eJLHHPBLEMF = (EJLHHPBLEMF)eJLHHPBLEMF.JEACJNAKLDJ(bCIHLCMFAEK);
			}
		}
		if (num > 0)
		{
			eJLHHPBLEMF = eJLHHPBLEMF.HHBAGDLPLMK(num);
		}
		return eJLHHPBLEMF;
	}
}
