using System.Collections.Generic;

public interface MFCJIFNNIHI
{
	void PEDGBHJOOHK(OneSignal.IGBMNDNCLPK PDGNEDBOGLE, OneSignal.IGBMNDNCLPK IMIGIBOPIGO);

	void CGPGIHFFLLI();

	void KINGLACPPID();

	void EFMGJJAMOLL(string MELLKFCHLCG, string MNCFEDGGAJM);

	void FFHDGIBPADH(IDictionary<string, string> NIJLMBACDIN);

	void MGKBPJLBNLA();

	void GJMCAGHFOAO(string IKNCPEPOKGJ);

	void ENHDPFKMALA(IList<string> JFPPHGPOOAA);

	void ILOJEBPJOBD();

	void NNNGBMJPBDG(bool DOKMPEOLBGO);

	void DHJLPDPDNEB(Dictionary<string, object> MBBPBGHKLJM);

	void FFEJJJNDGDH(string HCMFNNPEKDN);

	void HBHFHKNLPEN();

	void EHAGACDCKFK(bool DIHAHEPGCLB);

	void MABLPNJIOMF(string HCMFNNPEKDN);

	void MABLPNJIOMF(string HCMFNNPEKDN, string LNLGEFGDJAM);

	void NFGIGGCADPP();

	void AIJCJPAPNCP(OneSignal.NDNHJFICCIA KACNEFJPIPK);

	void GBJHBBFCFHG(bool JCDGKPPFIMO);

	bool CDPNAOABJOF();

	void DDJHDBCEMLC(bool HBEHEELHKLP);

	void COEAOFJJANM();

	void IJKJFPJHFHD();

	void BFFJKLFFKBF();

	void PFCFFFLDMDE();

	void CDFIEJNIDEA();

	void JJBOHMCEBPH();

	AMLCGIGPHEJ IIDINNBDNLD();

	OCFGDKAAKAM EFHCBOFFHGG(object NDPDAGBHBMI);

	ANEMLFEAJAP LFODGFFOCOP(object NDPDAGBHBMI);

	DPEOGFEJGPI BPMPMJAFDMC(object NDPDAGBHBMI);

	MIKPOELFDIL GMBFGDFNDHL(string CMECJOGHCCJ);

	OAEFFLGOHEC HBJBJGILCLI(string CMECJOGHCCJ);

	EJJOFNDGMNL HILMODDJFFC(string CMECJOGHCCJ);
}
