using System;

public class MFHLBDKHOAM : PHFBFDEAHMD
{
	private byte[] LGMMFPHDIMH;

	private byte[] GHPCHPOHELF;

	private int MNIGMJPFNDA;

	private JMPFLJGHAIM IEDPBFAFGGJ;

	private ELGNLPAGPNI HFHKPBBFDFD;

	private int DLFPGGOCGNE;

	private JEMNCGMEABF FDFHHGCCHJL;

	private JEMNCGMEABF EBGDDOLHBAC;

	public string KFKMEPMEBND
	{
		get
		{
			return "ISO9797Alg3";
		}
	}

	public MFHLBDKHOAM(JMPFLJGHAIM IEDPBFAFGGJ)
		: this(IEDPBFAFGGJ, IEDPBFAFGGJ.BDIGGHEPIIP() * 8, null)
	{
	}

	public MFHLBDKHOAM(JMPFLJGHAIM IEDPBFAFGGJ, ELGNLPAGPNI HFHKPBBFDFD)
		: this(IEDPBFAFGGJ, IEDPBFAFGGJ.BDIGGHEPIIP() * 8, HFHKPBBFDFD)
	{
	}

	public MFHLBDKHOAM(JMPFLJGHAIM IEDPBFAFGGJ, int DOPHJMLEJPG)
		: this(IEDPBFAFGGJ, DOPHJMLEJPG, null)
	{
	}

	public MFHLBDKHOAM(JMPFLJGHAIM IEDPBFAFGGJ, int DOPHJMLEJPG, ELGNLPAGPNI HFHKPBBFDFD)
	{
		if (DOPHJMLEJPG % 8 != 0)
		{
			throw new ArgumentException("MAC size must be multiple of 8");
		}
		if (!(IEDPBFAFGGJ is HDNPEKKELBE))
		{
			throw new ArgumentException("cipher must be instance of DesEngine");
		}
		this.IEDPBFAFGGJ = new OJGBFLKAPOB(IEDPBFAFGGJ);
		this.HFHKPBBFDFD = HFHKPBBFDFD;
		DLFPGGOCGNE = DOPHJMLEJPG / 8;
		LGMMFPHDIMH = new byte[IEDPBFAFGGJ.BDIGGHEPIIP()];
		GHPCHPOHELF = new byte[IEDPBFAFGGJ.BDIGGHEPIIP()];
		MNIGMJPFNDA = 0;
	}

	public void DIOELAHNLKJ(IGMAJHKIIPK IJJHBEECMBP)
	{
		OMOKOKFNBKI();
		if (!(IJJHBEECMBP is JEMNCGMEABF) && !(IJJHBEECMBP is CHCELGDKEJG))
		{
			throw new ArgumentException("parameters must be an instance of KeyParameter or ParametersWithIV");
		}
		JEMNCGMEABF jEMNCGMEABF = ((!(IJJHBEECMBP is JEMNCGMEABF)) ? ((JEMNCGMEABF)((CHCELGDKEJG)IJJHBEECMBP).KPJHHAAOFOH) : ((JEMNCGMEABF)IJJHBEECMBP));
		byte[] array = jEMNCGMEABF.MEGBFHFMBFI();
		JEMNCGMEABF jEMNCGMEABF2;
		if (array.Length == 16)
		{
			jEMNCGMEABF2 = new JEMNCGMEABF(array, 0, 8);
			FDFHHGCCHJL = new JEMNCGMEABF(array, 8, 8);
			EBGDDOLHBAC = jEMNCGMEABF2;
		}
		else
		{
			if (array.Length != 24)
			{
				throw new ArgumentException("Key must be either 112 or 168 bit long");
			}
			jEMNCGMEABF2 = new JEMNCGMEABF(array, 0, 8);
			FDFHHGCCHJL = new JEMNCGMEABF(array, 8, 8);
			EBGDDOLHBAC = new JEMNCGMEABF(array, 16, 8);
		}
		if (IJJHBEECMBP is CHCELGDKEJG)
		{
			IEDPBFAFGGJ.DIOELAHNLKJ(true, new CHCELGDKEJG(jEMNCGMEABF2, ((CHCELGDKEJG)IJJHBEECMBP).OLAEDCABKDH()));
		}
		else
		{
			IEDPBFAFGGJ.DIOELAHNLKJ(true, jEMNCGMEABF2);
		}
	}

	public int BKGLOJPPBIG()
	{
		return DLFPGGOCGNE;
	}

	public void BPAJGOINFNL(byte MOPCLEEGDFB)
	{
		if (MNIGMJPFNDA == GHPCHPOHELF.Length)
		{
			IEDPBFAFGGJ.DPACJDFHLKB(GHPCHPOHELF, 0, LGMMFPHDIMH, 0);
			MNIGMJPFNDA = 0;
		}
		GHPCHPOHELF[MNIGMJPFNDA++] = MOPCLEEGDFB;
	}

	public void GONEEEFEDGF(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int NBEDPKHALCN)
	{
		if (NBEDPKHALCN < 0)
		{
			throw new ArgumentException("Can't have a negative input length!");
		}
		int num = IEDPBFAFGGJ.BDIGGHEPIIP();
		int num2 = 0;
		int num3 = num - MNIGMJPFNDA;
		if (NBEDPKHALCN > num3)
		{
			Array.Copy(MOPCLEEGDFB, ELICNEDIBGB, GHPCHPOHELF, MNIGMJPFNDA, num3);
			num2 += IEDPBFAFGGJ.DPACJDFHLKB(GHPCHPOHELF, 0, LGMMFPHDIMH, 0);
			MNIGMJPFNDA = 0;
			NBEDPKHALCN -= num3;
			ELICNEDIBGB += num3;
			while (NBEDPKHALCN > num)
			{
				num2 += IEDPBFAFGGJ.DPACJDFHLKB(MOPCLEEGDFB, ELICNEDIBGB, LGMMFPHDIMH, 0);
				NBEDPKHALCN -= num;
				ELICNEDIBGB += num;
			}
		}
		Array.Copy(MOPCLEEGDFB, ELICNEDIBGB, GHPCHPOHELF, MNIGMJPFNDA, NBEDPKHALCN);
		MNIGMJPFNDA += NBEDPKHALCN;
	}

	public int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		int num = IEDPBFAFGGJ.BDIGGHEPIIP();
		if (HFHKPBBFDFD == null)
		{
			while (MNIGMJPFNDA < num)
			{
				GHPCHPOHELF[MNIGMJPFNDA++] = 0;
			}
		}
		else
		{
			if (MNIGMJPFNDA == num)
			{
				IEDPBFAFGGJ.DPACJDFHLKB(GHPCHPOHELF, 0, LGMMFPHDIMH, 0);
				MNIGMJPFNDA = 0;
			}
			HFHKPBBFDFD.MDNFIGPPOFC(GHPCHPOHELF, MNIGMJPFNDA);
		}
		IEDPBFAFGGJ.DPACJDFHLKB(GHPCHPOHELF, 0, LGMMFPHDIMH, 0);
		HDNPEKKELBE hDNPEKKELBE = new HDNPEKKELBE();
		hDNPEKKELBE.DIOELAHNLKJ(false, FDFHHGCCHJL);
		hDNPEKKELBE.DPACJDFHLKB(LGMMFPHDIMH, 0, LGMMFPHDIMH, 0);
		hDNPEKKELBE.DIOELAHNLKJ(true, EBGDDOLHBAC);
		hDNPEKKELBE.DPACJDFHLKB(LGMMFPHDIMH, 0, LGMMFPHDIMH, 0);
		Array.Copy(LGMMFPHDIMH, 0, BILGCJNPJGJ, EMAKNGBIFDC, DLFPGGOCGNE);
		OMOKOKFNBKI();
		return DLFPGGOCGNE;
	}

	public void OMOKOKFNBKI()
	{
		Array.Clear(GHPCHPOHELF, 0, GHPCHPOHELF.Length);
		MNIGMJPFNDA = 0;
		IEDPBFAFGGJ.OMOKOKFNBKI();
	}
}
