using Spine;

public class MGCNHAGJEIE : FPOBLOBNHGG
{
	public const int JMPDFJHAGOA = 3;

	private const int AMJGBMFEPLB = -3;

	private const int JEOJDOEJECN = -2;

	private const int AOPAJBOMLBH = -1;

	private const int KAMNJJMIEII = 1;

	private const int MCLOMIBLHCO = 2;

	internal int GOPEKHCFFGB;

	internal float[] ENBKHCNKHCC;

	public int HOIDEGAIPMK
	{
		get
		{
			return GOPEKHCFFGB;
		}
		set
		{
			GOPEKHCFFGB = value;
		}
	}

	public float[] IKOJIGLMFNG
	{
		get
		{
			return ENBKHCNKHCC;
		}
		set
		{
			ENBKHCNKHCC = value;
		}
	}

	public override int ODHLEJHEBGD
	{
		get
		{
			return 150994944 + GOPEKHCFFGB;
		}
	}

	public MGCNHAGJEIE(int IJKENLLBMOJ)
		: base(IJKENLLBMOJ)
	{
		ENBKHCNKHCC = new float[IJKENLLBMOJ * 3];
	}

	public void BCEFHMIKFDC(int JHFDIBIBCPH, float HFLODNLEGFL, float MIIHPKNIPAB, int IEFNLGDAINN)
	{
		JHFDIBIBCPH *= 3;
		ENBKHCNKHCC[JHFDIBIBCPH] = HFLODNLEGFL;
		ENBKHCNKHCC[JHFDIBIBCPH + 1] = MIIHPKNIPAB;
		ENBKHCNKHCC[JHFDIBIBCPH + 2] = IEFNLGDAINN;
	}

	public override void FCHLOGCODOA(GCJKICAPOFL GDNININLMFD, float CGICCPOKJHB, float HFLODNLEGFL, ExposedList<DCBJAMHBAJB> ELMIMIMBNHP, float KBKMPEOMABI, BFCFMFBHBCH IFKBABBBDJM, ODPDBCNBOAK AJLDJAHHGOJ)
	{
		JICANJGGKNH jICANJGGKNH = GDNININLMFD.EFIPDNFLFND.Items[GOPEKHCFFGB];
		float[] eNBKHCNKHCC = ENBKHCNKHCC;
		if (HFLODNLEGFL < eNBKHCNKHCC[0])
		{
			switch (IFKBABBBDJM)
			{
			case BFCFMFBHBCH.Setup:
				jICANJGGKNH.MIIHPKNIPAB = jICANJGGKNH.MBBPBGHKLJM.MIIHPKNIPAB;
				jICANJGGKNH.IEFNLGDAINN = jICANJGGKNH.MBBPBGHKLJM.IEFNLGDAINN;
				break;
			case BFCFMFBHBCH.Current:
				jICANJGGKNH.MIIHPKNIPAB += (jICANJGGKNH.MBBPBGHKLJM.MIIHPKNIPAB - jICANJGGKNH.MIIHPKNIPAB) * KBKMPEOMABI;
				jICANJGGKNH.IEFNLGDAINN = jICANJGGKNH.MBBPBGHKLJM.IEFNLGDAINN;
				break;
			}
			return;
		}
		if (HFLODNLEGFL >= eNBKHCNKHCC[eNBKHCNKHCC.Length - 3])
		{
			if (IFKBABBBDJM == BFCFMFBHBCH.Setup)
			{
				jICANJGGKNH.MIIHPKNIPAB = jICANJGGKNH.MBBPBGHKLJM.MIIHPKNIPAB + (eNBKHCNKHCC[eNBKHCNKHCC.Length + -2] - jICANJGGKNH.MBBPBGHKLJM.MIIHPKNIPAB) * KBKMPEOMABI;
				jICANJGGKNH.IEFNLGDAINN = ((AJLDJAHHGOJ != ODPDBCNBOAK.Out) ? ((int)eNBKHCNKHCC[eNBKHCNKHCC.Length + -1]) : jICANJGGKNH.MBBPBGHKLJM.IEFNLGDAINN);
				return;
			}
			jICANJGGKNH.MIIHPKNIPAB += (eNBKHCNKHCC[eNBKHCNKHCC.Length + -2] - jICANJGGKNH.MIIHPKNIPAB) * KBKMPEOMABI;
			if (AJLDJAHHGOJ == ODPDBCNBOAK.In)
			{
				jICANJGGKNH.IEFNLGDAINN = (int)eNBKHCNKHCC[eNBKHCNKHCC.Length + -1];
			}
			return;
		}
		int num = GNGKKPOGGGM.EIAMMDBFDFO(eNBKHCNKHCC, HFLODNLEGFL, 3);
		float num2 = eNBKHCNKHCC[num + -2];
		float num3 = eNBKHCNKHCC[num];
		float num4 = IFMKHGLKEMB(num / 3 - 1, 1f - (HFLODNLEGFL - num3) / (eNBKHCNKHCC[num + -3] - num3));
		if (IFKBABBBDJM == BFCFMFBHBCH.Setup)
		{
			jICANJGGKNH.MIIHPKNIPAB = jICANJGGKNH.MBBPBGHKLJM.MIIHPKNIPAB + (num2 + (eNBKHCNKHCC[num + 1] - num2) * num4 - jICANJGGKNH.MBBPBGHKLJM.MIIHPKNIPAB) * KBKMPEOMABI;
			jICANJGGKNH.IEFNLGDAINN = ((AJLDJAHHGOJ != ODPDBCNBOAK.Out) ? ((int)eNBKHCNKHCC[num + -1]) : jICANJGGKNH.MBBPBGHKLJM.IEFNLGDAINN);
			return;
		}
		jICANJGGKNH.MIIHPKNIPAB += (num2 + (eNBKHCNKHCC[num + 1] - num2) * num4 - jICANJGGKNH.MIIHPKNIPAB) * KBKMPEOMABI;
		if (AJLDJAHHGOJ == ODPDBCNBOAK.In)
		{
			jICANJGGKNH.IEFNLGDAINN = (int)eNBKHCNKHCC[num + -1];
		}
	}
}
