using System;

public class MHBCFNELGOJ : LNKPCJLANAO
{
	private readonly COCECKPDIKC LGAAPLFEPMG;

	private readonly FJMKMKNJKOI ENGOHJOMMKJ;

	public COCECKPDIKC ABHPJEPGJGI
	{
		get
		{
			return LGAAPLFEPMG;
		}
	}

	public FJMKMKNJKOI FEJGHPNBLMJ
	{
		get
		{
			return ENGOHJOMMKJ;
		}
	}

	public MHBCFNELGOJ(COCECKPDIKC LGAAPLFEPMG, LNKPCJLANAO ECPKCNOAOAJ)
	{
		ENGOHJOMMKJ = new FJMKMKNJKOI(ECPKCNOAOAJ);
		this.LGAAPLFEPMG = LGAAPLFEPMG;
	}

	public MHBCFNELGOJ(COCECKPDIKC LGAAPLFEPMG, byte[] ECPKCNOAOAJ)
	{
		ENGOHJOMMKJ = new FJMKMKNJKOI(ECPKCNOAOAJ);
		this.LGAAPLFEPMG = LGAAPLFEPMG;
	}

	private MHBCFNELGOJ(ALLINHNNNJN MIABODPHOIP)
	{
		if (MIABODPHOIP.GMCGMPEEHJP != 2)
		{
			throw new ArgumentException("Bad sequence size: " + MIABODPHOIP.GMCGMPEEHJP, "seq");
		}
		LGAAPLFEPMG = COCECKPDIKC.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(0));
		ENGOHJOMMKJ = FJMKMKNJKOI.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(1));
	}

	public static MHBCFNELGOJ BJLJCGFMFOO(PAANMJLACEF NEMEKIOEOLC, bool DHGLJHFEJFL)
	{
		return BJLJCGFMFOO(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC, DHGLJHFEJFL));
	}

	public static MHBCFNELGOJ BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC is MHBCFNELGOJ)
		{
			return (MHBCFNELGOJ)NEMEKIOEOLC;
		}
		if (NEMEKIOEOLC != null)
		{
			return new MHBCFNELGOJ(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC));
		}
		return null;
	}

	public EDOEBJJFOBM DGEOLGIDGFE()
	{
		return EDOEBJJFOBM.HPDCKMOPEMM(ENGOHJOMMKJ.KLHNEKMCKKI());
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		return new KOGPLMALOEH(LGAAPLFEPMG, ENGOHJOMMKJ);
	}
}
