internal class MICLEIODIAH
{
	private static readonly OIONBALGCNP COABPJMBBDI = HLAKNNHGPNP.GABGKBAKHDP;

	internal static void PBOCMJBJGPK(OHPHNNNHCOO PINNJBGMGOA, LNKPCJLANAO IJJHBEECMBP)
	{
		if (IJJHBEECMBP != null && COABPJMBBDI.Equals(IJJHBEECMBP))
		{
		}
	}

	internal static string PPPAACNJBIC(COCECKPDIKC COJGMAHIJHF)
	{
		LNKPCJLANAO lNKPCJLANAO = COJGMAHIJHF.KPJHHAAOFOH;
		if (lNKPCJLANAO != null && !COABPJMBBDI.Equals(lNKPCJLANAO))
		{
			if (COJGMAHIJHF.GOFDFGBGLFC.Equals(NLPPJKFFBON.NLKEIILLMGF))
			{
				LHCALAMFAOK lHCALAMFAOK = LHCALAMFAOK.BJLJCGFMFOO(lNKPCJLANAO);
				return OMINPDECNNB(lHCALAMFAOK.FDOJDCLKKIP.GOFDFGBGLFC) + "withRSAandMGF1";
			}
			if (COJGMAHIJHF.GOFDFGBGLFC.Equals(JJFMEBLGJEP.GOEPMLIFLFH))
			{
				ALLINHNNNJN aLLINHNNNJN = ALLINHNNNJN.BJLJCGFMFOO(lNKPCJLANAO);
				return OMINPDECNNB((KLKJHFKJLEM)aLLINHNNNJN.ECNCPJGHBIG(0)) + "withECDSA";
			}
		}
		return COJGMAHIJHF.GOFDFGBGLFC.EEFMIHDPJPG;
	}

	private static string OMINPDECNNB(KLKJHFKJLEM FANIKGJBMBA)
	{
		if (NLPPJKFFBON.HCEBKEDMKGI.Equals(FANIKGJBMBA))
		{
			return "MD5";
		}
		if (POLLKACILDK.MEBPJCLMCDA.Equals(FANIKGJBMBA))
		{
			return "SHA1";
		}
		if (HHKLFIFJNFO.NGAKIGLLNMJ.Equals(FANIKGJBMBA))
		{
			return "SHA224";
		}
		if (HHKLFIFJNFO.OKLEKJJIGME.Equals(FANIKGJBMBA))
		{
			return "SHA256";
		}
		if (HHKLFIFJNFO.EJIHFCHFMLO.Equals(FANIKGJBMBA))
		{
			return "SHA384";
		}
		if (HHKLFIFJNFO.HBLLHCKNOKB.Equals(FANIKGJBMBA))
		{
			return "SHA512";
		}
		if (HECJIGBIHCA.KCPONBGBCIG.Equals(FANIKGJBMBA))
		{
			return "RIPEMD128";
		}
		if (HECJIGBIHCA.LNJCFFFDBMO.Equals(FANIKGJBMBA))
		{
			return "RIPEMD160";
		}
		if (HECJIGBIHCA.AEIDPDDECDO.Equals(FANIKGJBMBA))
		{
			return "RIPEMD256";
		}
		if (FNOHIHFMAMN.EPDBPJHHJIP.Equals(FANIKGJBMBA))
		{
			return "GOST3411";
		}
		return FANIKGJBMBA.EEFMIHDPJPG;
	}
}
