public class MIDPALCBHJE : ECBKNMOGLEG
{
	protected readonly CGDEGBGOKJO MBEMNOCDDBC;

	protected readonly KPMKFMEEJCJ OEOENDBGPLC;

	protected readonly KPMKFMEEJCJ MHBEDFNGKOD;

	protected readonly LHAMCHLCIFH EGFFINOBDFH;

	protected readonly LHAMCHLCIFH CKDGLMGBEAL;

	protected readonly bool EDDFNJMPLKH;

	public MIDPALCBHJE(CGDEGBGOKJO MBEMNOCDDBC, KPMKFMEEJCJ OGICPKHDAGA, KPMKFMEEJCJ FBACJKBJPPI, BJLAMONNNDD FPIFEGNLIEG, BJLAMONNNDD LLJMCJPMGHL, int NAJNLOODBFL, bool EDDFNJMPLKH)
	{
		bool flag = MBEMNOCDDBC.DLHCCNKGKJP;
		this.MBEMNOCDDBC = MBEMNOCDDBC;
		this.EDDFNJMPLKH = EDDFNJMPLKH;
		OEOENDBGPLC = OGICPKHDAGA;
		MHBEDFNGKOD = FBACJKBJPPI;
		int num = 2 * NAJNLOODBFL + FPIFEGNLIEG.EEMLLAMENHO() + LLJMCJPMGHL.EEMLLAMENHO();
		byte[] iKNCPEPOKGJ = KINEBFNENMB.IJLFLBPLJHD(MBEMNOCDDBC, num);
		int num2 = 0;
		LHAMCHLCIFH lHAMCHLCIFH = new LHAMCHLCIFH(MBEMNOCDDBC, FPIFEGNLIEG, iKNCPEPOKGJ, num2, FPIFEGNLIEG.EEMLLAMENHO());
		num2 += FPIFEGNLIEG.EEMLLAMENHO();
		LHAMCHLCIFH lHAMCHLCIFH2 = new LHAMCHLCIFH(MBEMNOCDDBC, LLJMCJPMGHL, iKNCPEPOKGJ, num2, LLJMCJPMGHL.EEMLLAMENHO());
		num2 += LLJMCJPMGHL.EEMLLAMENHO();
		JEMNCGMEABF jEMNCGMEABF = new JEMNCGMEABF(iKNCPEPOKGJ, num2, NAJNLOODBFL);
		num2 += NAJNLOODBFL;
		JEMNCGMEABF jEMNCGMEABF2 = new JEMNCGMEABF(iKNCPEPOKGJ, num2, NAJNLOODBFL);
		num2 += NAJNLOODBFL;
		if (num2 != num)
		{
			throw new DEIDBCPPCMB(80);
		}
		IGMAJHKIIPK iJJHBEECMBP;
		IGMAJHKIIPK iJJHBEECMBP2;
		if (flag)
		{
			EGFFINOBDFH = lHAMCHLCIFH2;
			CKDGLMGBEAL = lHAMCHLCIFH;
			OEOENDBGPLC = FBACJKBJPPI;
			MHBEDFNGKOD = OGICPKHDAGA;
			iJJHBEECMBP = jEMNCGMEABF2;
			iJJHBEECMBP2 = jEMNCGMEABF;
		}
		else
		{
			EGFFINOBDFH = lHAMCHLCIFH;
			CKDGLMGBEAL = lHAMCHLCIFH2;
			OEOENDBGPLC = OGICPKHDAGA;
			MHBEDFNGKOD = FBACJKBJPPI;
			iJJHBEECMBP = jEMNCGMEABF;
			iJJHBEECMBP2 = jEMNCGMEABF2;
		}
		if (EDDFNJMPLKH)
		{
			byte[] nDEFBOJOALL = new byte[8];
			iJJHBEECMBP = new CHCELGDKEJG(iJJHBEECMBP, nDEFBOJOALL);
			iJJHBEECMBP2 = new CHCELGDKEJG(iJJHBEECMBP2, nDEFBOJOALL);
		}
		OEOENDBGPLC.DIOELAHNLKJ(true, iJJHBEECMBP);
		MHBEDFNGKOD.DIOELAHNLKJ(false, iJJHBEECMBP2);
	}

	public virtual int LBEOGHDBCJM(int DOILBJKOFDG)
	{
		return DOILBJKOFDG - EGFFINOBDFH.PNBDAGKFOBN;
	}

	public virtual byte[] BIIKEIOAPCJ(long MHCDKMMAMKP, byte NBFBPNNEKMN, byte[] NEOIPBBDIMB, int IBNDGNOIEEF, int NBEDPKHALCN)
	{
		if (EDDFNJMPLKH)
		{
			MDFILDMJBFD(OEOENDBGPLC, true, MHCDKMMAMKP);
		}
		byte[] array = new byte[NBEDPKHALCN + EGFFINOBDFH.PNBDAGKFOBN];
		OEOENDBGPLC.POCAGALIPAI(NEOIPBBDIMB, IBNDGNOIEEF, NBEDPKHALCN, array, 0);
		byte[] array2 = EGFFINOBDFH.OFLKIODCBJJ(MHCDKMMAMKP, NBFBPNNEKMN, NEOIPBBDIMB, IBNDGNOIEEF, NBEDPKHALCN);
		OEOENDBGPLC.POCAGALIPAI(array2, 0, array2.Length, array, NBEDPKHALCN);
		return array;
	}

	public virtual byte[] OBMCLFEIPBL(long MHCDKMMAMKP, byte NBFBPNNEKMN, byte[] JNGDHEECGIG, int IBNDGNOIEEF, int NBEDPKHALCN)
	{
		if (EDDFNJMPLKH)
		{
			MDFILDMJBFD(MHBEDFNGKOD, false, MHCDKMMAMKP);
		}
		int num = CKDGLMGBEAL.PNBDAGKFOBN;
		if (NBEDPKHALCN < num)
		{
			throw new DEIDBCPPCMB(50);
		}
		int num2 = NBEDPKHALCN - num;
		byte[] array = new byte[NBEDPKHALCN];
		MHBEDFNGKOD.POCAGALIPAI(JNGDHEECGIG, IBNDGNOIEEF, NBEDPKHALCN, array, 0);
		MOMLJKADKHD(MHCDKMMAMKP, NBFBPNNEKMN, array, num2, NBEDPKHALCN, array, 0, num2);
		return NOGCEBKPPJE.EHLHBAMJLNI(array, 0, num2);
	}

	protected virtual void MOMLJKADKHD(long MHCDKMMAMKP, byte NBFBPNNEKMN, byte[] FANMAKPILOA, int NDGFMIOIGPF, int BNAIHLHECBK, byte[] DEMMKFAEELN, int EFEIOIKGMGE, int FKCHMJFIPDJ)
	{
		byte[] mNIMEAMHNMI = NOGCEBKPPJE.EHLHBAMJLNI(FANMAKPILOA, NDGFMIOIGPF, BNAIHLHECBK);
		byte[] bCIHLCMFAEK = CKDGLMGBEAL.OFLKIODCBJJ(MHCDKMMAMKP, NBFBPNNEKMN, DEMMKFAEELN, EFEIOIKGMGE, FKCHMJFIPDJ);
		if (!NOGCEBKPPJE.PBBFCJBKJEN(mNIMEAMHNMI, bCIHLCMFAEK))
		{
			throw new DEIDBCPPCMB(20);
		}
	}

	protected virtual void MDFILDMJBFD(KPMKFMEEJCJ IEDPBFAFGGJ, bool MAEALKEJALK, long MHCDKMMAMKP)
	{
		byte[] array = new byte[8];
		KINEBFNENMB.JCMFNDAOIPC(MHCDKMMAMKP, array, 0);
		IEDPBFAFGGJ.DIOELAHNLKJ(MAEALKEJALK, new CHCELGDKEJG(null, array));
	}
}
