using System;
using Org.BouncyCastle.Math;

internal class MIHGBJGOPKP : EJLHHPBLEMF
{
	public override KBINBLGGLNE LGFGMGPDEIB
	{
		get
		{
			KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			if (base.IFCDKFANPBO || kBINBLGGLNE.EJJHHCOFAAI)
			{
				return kBINBLGGLNE2;
			}
			KBINBLGGLNE kBINBLGGLNE3 = kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE).IBJBIGNPNEM(kBINBLGGLNE);
			KBINBLGGLNE kBINBLGGLNE4 = base.LAMGGDKLPJH[0];
			if (!kBINBLGGLNE4.EOJCHPEGABD)
			{
				kBINBLGGLNE3 = kBINBLGGLNE3.MCPDGENJCDB(kBINBLGGLNE4);
			}
			return kBINBLGGLNE3;
		}
	}

	protected internal override bool NLPBPDPOOAK
	{
		get
		{
			KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
			if (kBINBLGGLNE.EJJHHCOFAAI)
			{
				return false;
			}
			KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
			return kBINBLGGLNE2.OFGNPBCCHAA() != kBINBLGGLNE.OFGNPBCCHAA();
		}
	}

	public MIHGBJGOPKP(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public MIHGBJGOPKP(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal MIHGBJGOPKP(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new MIHGBJGOPKP(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE2 = BCIHLCMFAEK.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			if (kBINBLGGLNE2.EJJHHCOFAAI)
			{
				return bHPIABAGAPB.EFOLNCNGADB;
			}
			return BCIHLCMFAEK.JEACJNAKLDJ(this);
		}
		KBINBLGGLNE kBINBLGGLNE3 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE4 = base.LAMGGDKLPJH[0];
		KBINBLGGLNE kBINBLGGLNE5 = BCIHLCMFAEK.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE6 = BCIHLCMFAEK.LAMGGDKLPJH[0];
		bool flag = kBINBLGGLNE4.EOJCHPEGABD;
		KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE2;
		KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE5;
		if (!flag)
		{
			kBINBLGGLNE7 = kBINBLGGLNE7.IBJBIGNPNEM(kBINBLGGLNE4);
			kBINBLGGLNE8 = kBINBLGGLNE8.IBJBIGNPNEM(kBINBLGGLNE4);
		}
		bool flag2 = kBINBLGGLNE6.EOJCHPEGABD;
		KBINBLGGLNE kBINBLGGLNE9 = kBINBLGGLNE;
		KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE3;
		if (!flag2)
		{
			kBINBLGGLNE9 = kBINBLGGLNE9.IBJBIGNPNEM(kBINBLGGLNE6);
			kBINBLGGLNE10 = kBINBLGGLNE10.IBJBIGNPNEM(kBINBLGGLNE6);
		}
		KBINBLGGLNE kBINBLGGLNE11 = kBINBLGGLNE10.JEACJNAKLDJ(kBINBLGGLNE8);
		KBINBLGGLNE kBINBLGGLNE12 = kBINBLGGLNE9.JEACJNAKLDJ(kBINBLGGLNE7);
		if (kBINBLGGLNE12.EJJHHCOFAAI)
		{
			if (kBINBLGGLNE11.EJJHHCOFAAI)
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		KBINBLGGLNE kBINBLGGLNE15;
		KBINBLGGLNE cNLILOEEBOJ;
		KBINBLGGLNE kBINBLGGLNE17;
		if (kBINBLGGLNE2.EJJHHCOFAAI)
		{
			JGAFKLGGBGF jGAFKLGGBGF = MIHJHLFLHNA();
			kBINBLGGLNE = jGAFKLGGBGF.OBCJFNBLIPG;
			KBINBLGGLNE kBINBLGGLNE13 = jGAFKLGGBGF.LGFGMGPDEIB;
			KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE5;
			KBINBLGGLNE kBINBLGGLNE14 = kBINBLGGLNE13.JEACJNAKLDJ(bCIHLCMFAEK).MCPDGENJCDB(kBINBLGGLNE);
			kBINBLGGLNE15 = kBINBLGGLNE14.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE14).JEACJNAKLDJ(kBINBLGGLNE);
			if (kBINBLGGLNE15.EJJHHCOFAAI)
			{
				return new MIHGBJGOPKP(bHPIABAGAPB, kBINBLGGLNE15, bHPIABAGAPB.FPKDKHJKEEF, base.BPGGHHMMCCB);
			}
			KBINBLGGLNE kBINBLGGLNE16 = kBINBLGGLNE14.IBJBIGNPNEM(kBINBLGGLNE.JEACJNAKLDJ(kBINBLGGLNE15)).JEACJNAKLDJ(kBINBLGGLNE15).JEACJNAKLDJ(kBINBLGGLNE13);
			cNLILOEEBOJ = kBINBLGGLNE16.MCPDGENJCDB(kBINBLGGLNE15).JEACJNAKLDJ(kBINBLGGLNE15);
			kBINBLGGLNE17 = bHPIABAGAPB.HFENNGHNFLF(BigInteger.One);
		}
		else
		{
			kBINBLGGLNE12 = kBINBLGGLNE12.MIOEHGDPGAG();
			KBINBLGGLNE kBINBLGGLNE18 = kBINBLGGLNE11.IBJBIGNPNEM(kBINBLGGLNE9);
			KBINBLGGLNE kBINBLGGLNE19 = kBINBLGGLNE11.IBJBIGNPNEM(kBINBLGGLNE7);
			kBINBLGGLNE15 = kBINBLGGLNE18.IBJBIGNPNEM(kBINBLGGLNE19);
			if (kBINBLGGLNE15.EJJHHCOFAAI)
			{
				return new MIHGBJGOPKP(bHPIABAGAPB, kBINBLGGLNE15, bHPIABAGAPB.FPKDKHJKEEF, base.BPGGHHMMCCB);
			}
			KBINBLGGLNE kBINBLGGLNE20 = kBINBLGGLNE11.IBJBIGNPNEM(kBINBLGGLNE12);
			if (!flag2)
			{
				kBINBLGGLNE20 = kBINBLGGLNE20.IBJBIGNPNEM(kBINBLGGLNE6);
			}
			cNLILOEEBOJ = kBINBLGGLNE19.JEACJNAKLDJ(kBINBLGGLNE12).FGLCIBKKKFF(kBINBLGGLNE20, kBINBLGGLNE3.JEACJNAKLDJ(kBINBLGGLNE4));
			kBINBLGGLNE17 = kBINBLGGLNE20;
			if (!flag)
			{
				kBINBLGGLNE17 = kBINBLGGLNE17.IBJBIGNPNEM(kBINBLGGLNE4);
			}
		}
		return new MIHGBJGOPKP(bHPIABAGAPB, kBINBLGGLNE15, cNLILOEEBOJ, new KBINBLGGLNE[1] { kBINBLGGLNE17 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
		bool flag = kBINBLGGLNE3.EOJCHPEGABD;
		KBINBLGGLNE kBINBLGGLNE4 = ((!flag) ? kBINBLGGLNE3.MIOEHGDPGAG() : kBINBLGGLNE3);
		KBINBLGGLNE kBINBLGGLNE5 = ((!flag) ? kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE3).IBJBIGNPNEM(kBINBLGGLNE2) : kBINBLGGLNE2.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE2));
		if (kBINBLGGLNE5.EJJHHCOFAAI)
		{
			return new MIHGBJGOPKP(bHPIABAGAPB, kBINBLGGLNE5, bHPIABAGAPB.FPKDKHJKEEF, base.BPGGHHMMCCB);
		}
		KBINBLGGLNE kBINBLGGLNE6 = kBINBLGGLNE5.MIOEHGDPGAG();
		KBINBLGGLNE kBINBLGGLNE7 = ((!flag) ? kBINBLGGLNE5.IBJBIGNPNEM(kBINBLGGLNE4) : kBINBLGGLNE5);
		KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE).MIOEHGDPGAG();
		KBINBLGGLNE bCIHLCMFAEK = ((!flag) ? kBINBLGGLNE4.MIOEHGDPGAG() : kBINBLGGLNE3);
		KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE8.JEACJNAKLDJ(kBINBLGGLNE5).JEACJNAKLDJ(kBINBLGGLNE4).IBJBIGNPNEM(kBINBLGGLNE8)
			.JEACJNAKLDJ(bCIHLCMFAEK)
			.JEACJNAKLDJ(kBINBLGGLNE6)
			.JEACJNAKLDJ(kBINBLGGLNE7);
		return new MIHGBJGOPKP(bHPIABAGAPB, kBINBLGGLNE6, cNLILOEEBOJ, new KBINBLGGLNE[1] { kBINBLGGLNE7 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		KBINBLGGLNE kBINBLGGLNE2 = BCIHLCMFAEK.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE3 = BCIHLCMFAEK.LAMGGDKLPJH[0];
		if (kBINBLGGLNE2.EJJHHCOFAAI || !kBINBLGGLNE3.EOJCHPEGABD)
		{
			return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
		}
		KBINBLGGLNE kBINBLGGLNE4 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE5 = base.LAMGGDKLPJH[0];
		KBINBLGGLNE kBINBLGGLNE6 = BCIHLCMFAEK.FIJLKLCHMGH;
		KBINBLGGLNE aMFCENFNAJJ = kBINBLGGLNE.MIOEHGDPGAG();
		KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE4.MIOEHGDPGAG();
		KBINBLGGLNE kBINBLGGLNE8 = kBINBLGGLNE5.MIOEHGDPGAG();
		KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE4.IBJBIGNPNEM(kBINBLGGLNE5);
		KBINBLGGLNE bCIHLCMFAEK2 = kBINBLGGLNE7.JEACJNAKLDJ(bCIHLCMFAEK);
		KBINBLGGLNE kBINBLGGLNE9 = kBINBLGGLNE6.AOAINNMNBHC();
		KBINBLGGLNE kBINBLGGLNE10 = kBINBLGGLNE9.IBJBIGNPNEM(kBINBLGGLNE8).JEACJNAKLDJ(kBINBLGGLNE7).CIDGMJAFLHM(bCIHLCMFAEK2, aMFCENFNAJJ, kBINBLGGLNE8);
		KBINBLGGLNE kBINBLGGLNE11 = kBINBLGGLNE2.IBJBIGNPNEM(kBINBLGGLNE8);
		KBINBLGGLNE kBINBLGGLNE12 = kBINBLGGLNE11.JEACJNAKLDJ(bCIHLCMFAEK2).MIOEHGDPGAG();
		if (kBINBLGGLNE12.EJJHHCOFAAI)
		{
			if (kBINBLGGLNE10.EJJHHCOFAAI)
			{
				return BCIHLCMFAEK.LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		if (kBINBLGGLNE10.EJJHHCOFAAI)
		{
			return new MIHGBJGOPKP(bHPIABAGAPB, kBINBLGGLNE10, bHPIABAGAPB.FPKDKHJKEEF, base.BPGGHHMMCCB);
		}
		KBINBLGGLNE aMFCENFNAJJ2 = kBINBLGGLNE10.MIOEHGDPGAG().IBJBIGNPNEM(kBINBLGGLNE11);
		KBINBLGGLNE kBINBLGGLNE13 = kBINBLGGLNE10.IBJBIGNPNEM(kBINBLGGLNE12).IBJBIGNPNEM(kBINBLGGLNE8);
		KBINBLGGLNE cNLILOEEBOJ = kBINBLGGLNE10.JEACJNAKLDJ(kBINBLGGLNE12).MIOEHGDPGAG().CIDGMJAFLHM(bCIHLCMFAEK2, kBINBLGGLNE9, kBINBLGGLNE13);
		return new MIHGBJGOPKP(bHPIABAGAPB, aMFCENFNAJJ2, cNLILOEEBOJ, new KBINBLGGLNE[1] { kBINBLGGLNE13 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return this;
		}
		KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE3 = base.LAMGGDKLPJH[0];
		return new MIHGBJGOPKP(ECFGFKNLLGH, kBINBLGGLNE, kBINBLGGLNE2.JEACJNAKLDJ(kBINBLGGLNE3), new KBINBLGGLNE[1] { kBINBLGGLNE3 }, base.BPGGHHMMCCB);
	}
}
