using System;

public class MIKBJEJODHC : NHIFILGGAOG
{
	public override byte[] MKEBGONJHED(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ JMNLHNOGILL, byte[] AIELCDIFLFB)
	{
		OHPHNNNHCOO oHPHNNNHCOO = LBBGKELCIGD(ADLMOHOLCGL, true, true, new MDAKJDOFCEP(JMNLHNOGILL, COOBIGONLDK.KMLKPFPCFLA));
		oHPHNNNHCOO.GONEEEFEDGF(AIELCDIFLFB, 0, AIELCDIFLFB.Length);
		return oHPHNNNHCOO.HMJHAKCMGHC();
	}

	public override bool JNKONIDOPKE(FBMKOGABPFL ADLMOHOLCGL, byte[] DIJNMJINHIL, COEMJAGOFJJ ECPKCNOAOAJ, byte[] AIELCDIFLFB)
	{
		OHPHNNNHCOO oHPHNNNHCOO = LBBGKELCIGD(ADLMOHOLCGL, true, false, ECPKCNOAOAJ);
		oHPHNNNHCOO.GONEEEFEDGF(AIELCDIFLFB, 0, AIELCDIFLFB.Length);
		return oHPHNNNHCOO.HLJBBONKPDG(DIJNMJINHIL);
	}

	public override OHPHNNNHCOO GBJMMNPHHNN(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ JMNLHNOGILL)
	{
		return LBBGKELCIGD(ADLMOHOLCGL, false, true, new MDAKJDOFCEP(JMNLHNOGILL, COOBIGONLDK.KMLKPFPCFLA));
	}

	public override OHPHNNNHCOO OPKHBIHFBMM(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ ECPKCNOAOAJ)
	{
		return LBBGKELCIGD(ADLMOHOLCGL, false, false, ECPKCNOAOAJ);
	}

	public override bool GNODDNDEEMI(COEMJAGOFJJ ECPKCNOAOAJ)
	{
		return ECPKCNOAOAJ is PLGGNEJEIIP && !ECPKCNOAOAJ.CCLHEKOIIKM;
	}

	protected virtual OHPHNNNHCOO LBBGKELCIGD(FBMKOGABPFL ADLMOHOLCGL, bool HEBAGGBJBMC, bool KGPBDABMHKH, IGMAJHKIIPK CILGMABNHOH)
	{
		if (ADLMOHOLCGL != null != KINEBFNENMB.OHGCLELCPMD(COOBIGONLDK))
		{
			throw new InvalidOperationException();
		}
		if (ADLMOHOLCGL != null && ADLMOHOLCGL.ACMDKLDPDLB != 1)
		{
			throw new InvalidOperationException();
		}
		BJLAMONNNDD hABFKBCEIBN = (HEBAGGBJBMC ? new OHAOIPKCMFC() : ((ADLMOHOLCGL != null) ? KINEBFNENMB.KNADNPDKLGD(ADLMOHOLCGL.GHMJJKMGKKB) : new JDNANIIIFGM()));
		OHPHNNNHCOO oHPHNNNHCOO = ((ADLMOHOLCGL == null) ? ((OHPHNNNHCOO)new NFONJENKCCJ(EHIPOEHPMNK(), hABFKBCEIBN)) : ((OHPHNNNHCOO)new MEHKHDBEJDF(hABFKBCEIBN, KINEBFNENMB.FKPJBANDKKF(ADLMOHOLCGL.GHMJJKMGKKB))));
		oHPHNNNHCOO.DIOELAHNLKJ(KGPBDABMHKH, CILGMABNHOH);
		return oHPHNNNHCOO;
	}

	protected virtual DGCIOOEELCP EHIPOEHPMNK()
	{
		return new ODMDKFPOHIL(new EPDGODLEJEF());
	}
}
