public struct MOLCIIAPCMN
{
	public int APLNHKHHMEL;

	public int DLDHNNCGIPI;

	public MOLCIIAPCMN(int CENFCBHJGJP, int FBBFACEKBLC)
	{
		APLNHKHHMEL = CENFCBHJGJP;
		DLDHNNCGIPI = FBBFACEKBLC;
	}
}
