public class NADPOFCHCON
{
	private readonly IKDMCJPBBIH LAEGBFBBEBA;

	public readonly GBJNCLLOCJB JBJJMKONACJ;

	public NADPOFCHCON(IKDMCJPBBIH KAGBOIDKAED, GBJNCLLOCJB KFNJHBPIHOI)
	{
		JBJJMKONACJ = KFNJHBPIHOI;
		LAEGBFBBEBA = KAGBOIDKAED;
	}

	public virtual void JLECFJEAFCD()
	{
	}

	public virtual void AIGOFKAJFBM()
	{
		LAEGBFBBEBA.HOBMBHFKMJI(true);
	}

	protected virtual GBJNCLLOCJB BMMMAFJBJMD()
	{
		return GBJNCLLOCJB.ResultSuccess;
	}

	public GBJNCLLOCJB EFIMKKLBHPM()
	{
		return (LAEGBFBBEBA.GDMECFECCOM == LECPGNKOABP.GABGKBAKHDP.GDMECFECCOM) ? BMMMAFJBJMD() : GBJNCLLOCJB.ClientNotInSameUser;
	}
}
