using System.Collections.Generic;

public class NCGNBHMMFKN : MGAOAPKCDHP
{
	public string EALJKKBHDHK;

	public long CALJBGILMOL;

	public long KEMNAAPNAPA;

	public long KFBCFDALGBB;

	public long EEFMIHDPJPG;

	public NCGNBHMMFKN(Dictionary<string, object> JLKANDLHAOM)
	{
		EALJKKBHDHK = MGAOAPKCDHP.JDANMONKNGD("nick", JLKANDLHAOM);
		KEMNAAPNAPA = MGAOAPKCDHP.EICLJDHEHHP("helpWeek", JLKANDLHAOM, 0L);
		KFBCFDALGBB = MGAOAPKCDHP.EICLJDHEHHP("helpCount", JLKANDLHAOM, 0L);
		CALJBGILMOL = MGAOAPKCDHP.EICLJDHEHHP("maxLevelReached", JLKANDLHAOM, 0L);
		EEFMIHDPJPG = MGAOAPKCDHP.EICLJDHEHHP("id", JLKANDLHAOM, 0L);
	}
}
