public struct NEEADKLBGMM
{
	public int NKFABJFEJDC;

	public float LODNPDJEBAM;

	public float OHCIOPOEIGE;

	public NEEADKLBGMM(int OIAGIOLCHMO, float ECDDKMHIILE, float HCHKENDHADG)
	{
		NKFABJFEJDC = OIAGIOLCHMO;
		LODNPDJEBAM = ECDDKMHIILE;
		OHCIOPOEIGE = HCHKENDHADG;
	}
}
