using System;

public interface NGBFPFEHHNG
{
	bool BFNMEODGEDL();

	void BBHEHNNILKN(bool AMJIBFENMIF);

	EIMOMMNKKEG MCBOEBCAGAN();

	ECBKNMOGLEG FKNFDDEJJFO();

	void NGJJJECDDIG(byte CBJOEMMBAOJ, byte LHIDNPKMPPJ, string OEFCOJLNCKP, Exception DGPFJIEAMIG);

	void EEFFPKOOHJM(byte CBJOEMMBAOJ, byte LHIDNPKMPPJ);

	void FKGPFELMJKH();
}
