using System.Collections.Generic;

public class NGNNENBAMFM
{
	private static NGNNENBAMFM IACLMEKOOJO;

	private static JFNKCAPCADG DHMJKKHHMAJ;

	private NGNNENBAMFM()
	{
	}

	public static NGNNENBAMFM FFKACBMBNNP()
	{
		if (IACLMEKOOJO == null)
		{
			IACLMEKOOJO = new NGNNENBAMFM();
			DHMJKKHHMAJ = new JFNKCAPCADG();
		}
		return IACLMEKOOJO;
	}

	public List<FMFLAPIFIED> MILMOKINMPE()
	{
		return DHMJKKHHMAJ.MILMOKINMPE();
	}

	public FMFLAPIFIED MJDAOLKIAMP(string KHAHOPFFEJO)
	{
		return DHMJKKHHMAJ.MJDAOLKIAMP(KHAHOPFFEJO);
	}

	public void JAGPIDJLDIL(string KHAHOPFFEJO)
	{
		DHMJKKHHMAJ.JAGPIDJLDIL(KHAHOPFFEJO);
	}

	public void LPGMEJLDNIP(string KHAHOPFFEJO)
	{
		DHMJKKHHMAJ.LPGMEJLDNIP(KHAHOPFFEJO);
	}

	public void CICIHDPNKOM(string KHAHOPFFEJO)
	{
		DHMJKKHHMAJ.CICIHDPNKOM(KHAHOPFFEJO);
	}

	public void GHHGOALODBF(DGEFIMEIGKH NBFMBJCKJKO)
	{
		DHMJKKHHMAJ.GHHGOALODBF(NBFMBJCKJKO);
	}

	public void EGKBOHFBBMC(IKHKOODFGMO NBFMBJCKJKO)
	{
		DHMJKKHHMAJ.EGKBOHFBBMC(NBFMBJCKJKO);
	}
}
