public abstract class NHIFILGGAOG : EKFAMINKCJP
{
	protected CGDEGBGOKJO COOBIGONLDK;

	public virtual void DIOELAHNLKJ(CGDEGBGOKJO MBEMNOCDDBC)
	{
		COOBIGONLDK = MBEMNOCDDBC;
	}

	public virtual byte[] MKEBGONJHED(COEMJAGOFJJ JMNLHNOGILL, byte[] DCJNMBCPFFL)
	{
		return MKEBGONJHED(null, JMNLHNOGILL, DCJNMBCPFFL);
	}

	public abstract byte[] MKEBGONJHED(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ JMNLHNOGILL, byte[] AIELCDIFLFB);

	public virtual bool JNKONIDOPKE(byte[] DIJNMJINHIL, COEMJAGOFJJ ECPKCNOAOAJ, byte[] DCJNMBCPFFL)
	{
		return JNKONIDOPKE(null, DIJNMJINHIL, ECPKCNOAOAJ, DCJNMBCPFFL);
	}

	public abstract bool JNKONIDOPKE(FBMKOGABPFL ADLMOHOLCGL, byte[] DIJNMJINHIL, COEMJAGOFJJ ECPKCNOAOAJ, byte[] AIELCDIFLFB);

	public virtual OHPHNNNHCOO GBJMMNPHHNN(COEMJAGOFJJ JMNLHNOGILL)
	{
		return GBJMMNPHHNN(null, JMNLHNOGILL);
	}

	public abstract OHPHNNNHCOO GBJMMNPHHNN(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ JMNLHNOGILL);

	public virtual OHPHNNNHCOO OPKHBIHFBMM(COEMJAGOFJJ ECPKCNOAOAJ)
	{
		return OPKHBIHFBMM(null, ECPKCNOAOAJ);
	}

	public abstract OHPHNNNHCOO OPKHBIHFBMM(FBMKOGABPFL ADLMOHOLCGL, COEMJAGOFJJ ECPKCNOAOAJ);

	public abstract bool GNODDNDEEMI(COEMJAGOFJJ ECPKCNOAOAJ);
}
