using Spine;

public class NHPAKKGJBBI : BLIEJOGKBBN
{
	public override int ODHLEJHEBGD
	{
		get
		{
			return 201326592 + CFOGCDKFLIH;
		}
	}

	public NHPAKKGJBBI(int IJKENLLBMOJ)
		: base(IJKENLLBMOJ)
	{
	}

	public override void FCHLOGCODOA(GCJKICAPOFL GDNININLMFD, float CGICCPOKJHB, float HFLODNLEGFL, ExposedList<DCBJAMHBAJB> ELMIMIMBNHP, float KBKMPEOMABI, BFCFMFBHBCH IFKBABBBDJM, ODPDBCNBOAK AJLDJAHHGOJ)
	{
		KNKKDGIBGLM kNKKDGIBGLM = GDNININLMFD.NDOOCKKIMHO.Items[CFOGCDKFLIH];
		float[] eNBKHCNKHCC = ENBKHCNKHCC;
		if (HFLODNLEGFL < eNBKHCNKHCC[0])
		{
			switch (IFKBABBBDJM)
			{
			case BFCFMFBHBCH.Setup:
				kNKKDGIBGLM.ILNOGLMCFMC = kNKKDGIBGLM.MBBPBGHKLJM.ILNOGLMCFMC;
				break;
			case BFCFMFBHBCH.Current:
				kNKKDGIBGLM.ILNOGLMCFMC += (kNKKDGIBGLM.MBBPBGHKLJM.ILNOGLMCFMC - kNKKDGIBGLM.ILNOGLMCFMC) * KBKMPEOMABI;
				break;
			}
			return;
		}
		float num;
		if (HFLODNLEGFL >= eNBKHCNKHCC[eNBKHCNKHCC.Length - 2])
		{
			num = eNBKHCNKHCC[eNBKHCNKHCC.Length + -1];
		}
		else
		{
			int num2 = GNGKKPOGGGM.EIAMMDBFDFO(eNBKHCNKHCC, HFLODNLEGFL, 2);
			num = eNBKHCNKHCC[num2 + -1];
			float num3 = eNBKHCNKHCC[num2];
			float num4 = IFMKHGLKEMB(num2 / 2 - 1, 1f - (HFLODNLEGFL - num3) / (eNBKHCNKHCC[num2 + -2] - num3));
			num += (eNBKHCNKHCC[num2 + 1] - num) * num4;
		}
		if (IFKBABBBDJM == BFCFMFBHBCH.Setup)
		{
			kNKKDGIBGLM.ILNOGLMCFMC = kNKKDGIBGLM.MBBPBGHKLJM.ILNOGLMCFMC + (num - kNKKDGIBGLM.MBBPBGHKLJM.ILNOGLMCFMC) * KBKMPEOMABI;
		}
		else
		{
			kNKKDGIBGLM.ILNOGLMCFMC += (num - kNKKDGIBGLM.ILNOGLMCFMC) * KBKMPEOMABI;
		}
	}
}
