public class NIGAIKMDMOD : NADPOFCHCON
{
	public NIGAIKMDMOD(IKDMCJPBBIH KAGBOIDKAED, GBJNCLLOCJB KFNJHBPIHOI)
		: base(KAGBOIDKAED, KFNJHBPIHOI)
	{
	}

	public override void JLECFJEAFCD()
	{
		IDFPAFEJPPH.GABGKBAKHDP.BHABBFGFPFB();
	}
}
