using Assets.Scripts.CasualTools.Common.DB;

public class NIGFCEFLHML : Entity
{
	public int PDGLECFDLJJ;

	public int DJADMBLKBKJ;

	public int EMNDJNDGANP;

	public int FOJDLLGGJID;

	public NIGFCEFLHML(int? BDKFNEDHAOJ, int KIGOGMKCDKN, int MGCMMJPNJPH, int HCCBDFMKLHN, int POKMOKOPEKI)
	{
		PNLKNJNILDD(BDKFNEDHAOJ);
		PDGLECFDLJJ = KIGOGMKCDKN;
		DJADMBLKBKJ = MGCMMJPNJPH;
		EMNDJNDGANP = HCCBDFMKLHN;
		FOJDLLGGJID = POKMOKOPEKI;
	}
}
