using UnityEngine;

public class NIKKFHKOCMP
{
	public KBDNLHABLDE HAEACLJJOIH;

	public float OKJKFEPEHGP;

	public Color[] LFMALEPBIAE;

	public NIKKFHKOCMP(KBDNLHABLDE NBFBPNNEKMN, float KHJFCFLFCCN)
	{
		HAEACLJJOIH = NBFBPNNEKMN;
		OKJKFEPEHGP = KHJFCFLFCCN;
	}

	public NIKKFHKOCMP(KBDNLHABLDE NBFBPNNEKMN, Color[] MABENDNHDPI)
	{
		HAEACLJJOIH = NBFBPNNEKMN;
		LFMALEPBIAE = MABENDNHDPI;
	}
}
