using Org.BouncyCastle.Math;

internal class NINLMCBGMII : HAEJCOAFOIJ
{
	public static readonly BigInteger OKDPJHOEPBJ = AKOICJCJNFB.DOJBPIFPALJ(ACMDHOEGCJN.MBIJHANOCOC);

	private const int MHKCMGBLANG = 4;

	protected readonly EPGHIOHIPIF IAALHPOGFAN;

	public virtual BigInteger FNPELDEHJKL
	{
		get
		{
			return OKDPJHOEPBJ;
		}
	}

	public override JGAFKLGGBGF EFOLNCNGADB
	{
		get
		{
			return IAALHPOGFAN;
		}
	}

	public override int PJNLBAHOKGC
	{
		get
		{
			return OKDPJHOEPBJ.BitLength;
		}
	}

	public NINLMCBGMII()
		: base(OKDPJHOEPBJ)
	{
		IAALHPOGFAN = new EPGHIOHIPIF(this, null, null);
		CFJANGMBPML = HFENNGHNFLF(new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA984914A144")));
		MPDGCILOEML = HFENNGHNFLF(new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("7B425ED097B425ED097B425ED097B425ED097B425ED097B4260B5E9C7710C864")));
		NNGLKCDBIBE = new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("1000000000000000000000000000000014DEF9DEA2F79CD65812631A5CF5D3ED"));
		LDKJJAOPAAP = BigInteger.AGLOJCOAJIK(8L);
		NHKGIJJFPEK = 4;
	}

	protected override BHPIABAGAPB LNLMICLEEPK()
	{
		return new NINLMCBGMII();
	}

	public override bool ELIMDCKLHCJ(int FOOJPIGHMKH)
	{
		if (FOOJPIGHMKH == 4)
		{
			return true;
		}
		return false;
	}

	public override KBINBLGGLNE HFENNGHNFLF(BigInteger AMFCENFNAJJ)
	{
		return new NOHBGLDOCHE(AMFCENFNAJJ);
	}

	protected internal override JGAFKLGGBGF IMOPAOHAOAN(KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
	{
		return new EPGHIOHIPIF(this, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG);
	}

	protected internal override JGAFKLGGBGF IMOPAOHAOAN(KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
	{
		return new EPGHIOHIPIF(this, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG);
	}
}
