public static class NKILHODNBDE
{
	public static string GHBGCADFLFB(string ONHHAFBOPFG)
	{
		return GHBGCADFLFB(ONHHAFBOPFG, PNAJOCHGJFO.MNHBNGFDIPC, 0);
	}

	public static string GHBGCADFLFB(string ONHHAFBOPFG, bool JBPBIOHLLKP)
	{
		return GHBGCADFLFB(ONHHAFBOPFG, JBPBIOHLLKP, 0);
	}

	public static string GHBGCADFLFB(string ONHHAFBOPFG, bool JBPBIOHLLKP, int KOOENHBOKPL)
	{
		return PNAJOCHGJFO.PCGLGBPCBFP(ONHHAFBOPFG, JBPBIOHLLKP, KOOENHBOKPL);
	}
}
