using System;
using System.Collections.Generic;
using Spine;

public static class NPAEEOGIEEA
{
	public static bool NNKJOPGIGDB(this LJPHFIKMDHN JIHFFGPOGJL)
	{
		return JIHFFGPOGJL.LIKIOBHLHHF != null && JIHFFGPOGJL.LIKIOBHLHHF.Length > 0;
	}

	public static bool CJMIFJDBPFB(this OAMNGFLKEFI MNIMEAMHNMI)
	{
		return MNIMEAMHNMI is MKEALIMJCFJ || MNIMEAMHNMI is MGCLDKAFCIB;
	}

	public static bool OFACEBKFLOC(this NGPCELMDKGK LJCPOAOKFOE)
	{
		return ((ulong)LJCPOAOKFOE & 1uL) == 0;
	}

	public static bool KHKNHEPEKNE(this NGPCELMDKGK LJCPOAOKFOE)
	{
		return ((ulong)LJCPOAOKFOE & 2uL) == 0;
	}

	internal static void MPMPPDLEOMG(this GCJKICAPOFL GDNININLMFD, int BHOCDAJDHDK)
	{
		int num = BHOCDAJDHDK >> 24;
		KFAEGFBKGKF kFAEGFBKGKF = (KFAEGFBKGKF)num;
		int num2 = BHOCDAJDHDK - (num << 24);
		switch (kFAEGFBKGKF)
		{
		case KFAEGFBKGKF.Rotate:
		{
			NBKCFDOMAPI nBKCFDOMAPI = GDNININLMFD.LIKIOBHLHHF.Items[num2];
			nBKCFDOMAPI.ODLHFMOPCHL = nBKCFDOMAPI.MBBPBGHKLJM.ODLHFMOPCHL;
			break;
		}
		case KFAEGFBKGKF.Translate:
		{
			NBKCFDOMAPI nBKCFDOMAPI = GDNININLMFD.LIKIOBHLHHF.Items[num2];
			nBKCFDOMAPI.AMFCENFNAJJ = nBKCFDOMAPI.MBBPBGHKLJM.AMFCENFNAJJ;
			nBKCFDOMAPI.CNLILOEEBOJ = nBKCFDOMAPI.MBBPBGHKLJM.CNLILOEEBOJ;
			break;
		}
		case KFAEGFBKGKF.Scale:
		{
			NBKCFDOMAPI nBKCFDOMAPI = GDNININLMFD.LIKIOBHLHHF.Items[num2];
			nBKCFDOMAPI.IAFNPOKEFMB = nBKCFDOMAPI.MBBPBGHKLJM.IAFNPOKEFMB;
			nBKCFDOMAPI.GFMCPIJHIGD = nBKCFDOMAPI.MBBPBGHKLJM.GFMCPIJHIGD;
			break;
		}
		case KFAEGFBKGKF.Shear:
		{
			NBKCFDOMAPI nBKCFDOMAPI = GDNININLMFD.LIKIOBHLHHF.Items[num2];
			nBKCFDOMAPI.BALNAGONJDA = nBKCFDOMAPI.MBBPBGHKLJM.BALNAGONJDA;
			nBKCFDOMAPI.DADFBNMBFCD = nBKCFDOMAPI.MBBPBGHKLJM.DADFBNMBFCD;
			break;
		}
		case KFAEGFBKGKF.Attachment:
			GDNININLMFD.COKEGFHLLCM(num2);
			break;
		case KFAEGFBKGKF.Color:
			GDNININLMFD.MAKCMFCFDLP.Items[num2].ANMMFIPHBKH();
			break;
		case KFAEGFBKGKF.TwoColor:
			GDNININLMFD.MAKCMFCFDLP.Items[num2].ANMMFIPHBKH();
			break;
		case KFAEGFBKGKF.Deform:
			GDNININLMFD.MAKCMFCFDLP.Items[num2].ADAMNKAAPII.BOPEPLONIFL();
			break;
		case KFAEGFBKGKF.DrawOrder:
			GDNININLMFD.FOLJDMGJBKO();
			break;
		case KFAEGFBKGKF.IkConstraint:
		{
			JICANJGGKNH jICANJGGKNH = GDNININLMFD.EFIPDNFLFND.Items[num2];
			jICANJGGKNH.MIIHPKNIPAB = jICANJGGKNH.MBBPBGHKLJM.MIIHPKNIPAB;
			jICANJGGKNH.IEFNLGDAINN = jICANJGGKNH.MBBPBGHKLJM.IEFNLGDAINN;
			break;
		}
		case KFAEGFBKGKF.TransformConstraint:
		{
			DLKMEPPLCGM dLKMEPPLCGM = GDNININLMFD.FOANDHFONAA.Items[num2];
			MNNBOEPCJGP mBBPBGHKLJM = dLKMEPPLCGM.MBBPBGHKLJM;
			dLKMEPPLCGM.OIBAIJIPGOM = mBBPBGHKLJM.OIBAIJIPGOM;
			dLKMEPPLCGM.DHNKOEMONHP = mBBPBGHKLJM.DHNKOEMONHP;
			dLKMEPPLCGM.DLEIMBNDMOF = mBBPBGHKLJM.DLEIMBNDMOF;
			dLKMEPPLCGM.OKJBKNEPKPN = mBBPBGHKLJM.OKJBKNEPKPN;
			break;
		}
		case KFAEGFBKGKF.PathConstraintPosition:
		{
			KNKKDGIBGLM kNKKDGIBGLM = GDNININLMFD.NDOOCKKIMHO.Items[num2];
			kNKKDGIBGLM.LDMDBPLADGD = kNKKDGIBGLM.MBBPBGHKLJM.LDMDBPLADGD;
			break;
		}
		case KFAEGFBKGKF.PathConstraintSpacing:
		{
			KNKKDGIBGLM kNKKDGIBGLM = GDNININLMFD.NDOOCKKIMHO.Items[num2];
			kNKKDGIBGLM.ILNOGLMCFMC = kNKKDGIBGLM.MBBPBGHKLJM.ILNOGLMCFMC;
			break;
		}
		case KFAEGFBKGKF.PathConstraintMix:
		{
			KNKKDGIBGLM kNKKDGIBGLM = GDNININLMFD.NDOOCKKIMHO.Items[num2];
			kNKKDGIBGLM.OIBAIJIPGOM = kNKKDGIBGLM.MBBPBGHKLJM.OIBAIJIPGOM;
			kNKKDGIBGLM.DHNKOEMONHP = kNKKDGIBGLM.MBBPBGHKLJM.DHNKOEMONHP;
			break;
		}
		case KFAEGFBKGKF.Event:
			break;
		}
	}

	public static void FOLJDMGJBKO(this GCJKICAPOFL GDNININLMFD)
	{
		LBBAMMPJKDA[] items = GDNININLMFD.MAKCMFCFDLP.Items;
		int count = GDNININLMFD.MAKCMFCFDLP.Count;
		ExposedList<LBBAMMPJKDA> cOACJAFIPEI = GDNININLMFD.COACJAFIPEI;
		cOACJAFIPEI.BOPEPLONIFL(false);
		cOACJAFIPEI.JGGCKJABGHP(count);
		Array.Copy(items, cOACJAFIPEI.Items, count);
	}

	public static void ANMMFIPHBKH(this LBBAMMPJKDA DFKJODFHCJB)
	{
		DFKJODFHCJB.GPGDCCMECGF = DFKJODFHCJB.MBBPBGHKLJM.GPGDCCMECGF;
		DFKJODFHCJB.HJMBDGKAOBP = DFKJODFHCJB.MBBPBGHKLJM.HJMBDGKAOBP;
		DFKJODFHCJB.BCIHLCMFAEK = DFKJODFHCJB.MBBPBGHKLJM.BCIHLCMFAEK;
		DFKJODFHCJB.MNIMEAMHNMI = DFKJODFHCJB.MBBPBGHKLJM.MNIMEAMHNMI;
		DFKJODFHCJB.FHPFAEDHEGG = DFKJODFHCJB.MBBPBGHKLJM.FHPFAEDHEGG;
		DFKJODFHCJB.AONHFIBNFLD = DFKJODFHCJB.MBBPBGHKLJM.AONHFIBNFLD;
		DFKJODFHCJB.DLGDBCBCIED = DFKJODFHCJB.MBBPBGHKLJM.DLGDBCBCIED;
	}

	public static void NFKFLEKDLGP(this LBBAMMPJKDA DFKJODFHCJB)
	{
		HMGLMNHOBHA mBBPBGHKLJM = DFKJODFHCJB.MBBPBGHKLJM;
		DFKJODFHCJB.AIKFOHCPLKG = DFKJODFHCJB.JEBEPBEGCCF.GDNININLMFD.JGHJDGIANDD(mBBPBGHKLJM.IOCMOCCFALN, mBBPBGHKLJM.FKAJNAAKEFH);
	}

	public static void COKEGFHLLCM(this GCJKICAPOFL GDNININLMFD, int PBPEMFGPGFC)
	{
		LBBAMMPJKDA lBBAMMPJKDA = GDNININLMFD.MAKCMFCFDLP.Items[PBPEMFGPGFC];
		string fKAJNAAKEFH = lBBAMMPJKDA.MBBPBGHKLJM.FKAJNAAKEFH;
		if (string.IsNullOrEmpty(fKAJNAAKEFH))
		{
			lBBAMMPJKDA.AIKFOHCPLKG = null;
			return;
		}
		OAMNGFLKEFI eDDNOJDPMCF = GDNININLMFD.JGHJDGIANDD(PBPEMFGPGFC, fKAJNAAKEFH);
		lBBAMMPJKDA.AIKFOHCPLKG = eDDNOJDPMCF;
	}

	public static void CACPDNAGKBO(this GCJKICAPOFL GDNININLMFD, string PEKKCDPEBGL, float HFLODNLEGFL, bool IKGIEEMCFDK = false)
	{
		GNGKKPOGGGM gNGKKPOGGGM = GDNININLMFD.MBBPBGHKLJM.NELKDOOJCCD(PEKKCDPEBGL);
		if (gNGKKPOGGGM != null)
		{
			gNGKKPOGGGM.FCHLOGCODOA(GDNININLMFD, 0f, HFLODNLEGFL, IKGIEEMCFDK, null, 1f, BFCFMFBHBCH.Setup, ODPDBCNBOAK.In);
		}
	}

	public static void IOAOJAHHNOB(this GNGKKPOGGGM MGGNDAKIKII, GCJKICAPOFL GDNININLMFD, float HFLODNLEGFL, bool IKGIEEMCFDK = false)
	{
		MGGNDAKIKII.FCHLOGCODOA(GDNININLMFD, 0f, HFLODNLEGFL, IKGIEEMCFDK, null, 1f, BFCFMFBHBCH.Setup, ODPDBCNBOAK.In);
	}

	public static void ILEACEGENOB(this GNGKKPOGGGM MGGNDAKIKII, GCJKICAPOFL GDNININLMFD)
	{
		MGGNDAKIKII.FCHLOGCODOA(GDNININLMFD, 0f, 0f, false, null, 0f, BFCFMFBHBCH.Setup, ODPDBCNBOAK.Out);
	}

	public static void IDPNBGBLJGL(this JPAALKCPGNB HLCFGIFLPPE, string NFKHLLDFHKO, KGMHJGFNPFC DCMDAJJBNAI, List<string> IMAMEFOKGFM)
	{
		int pBPEMFGPGFC = DCMDAJJBNAI.IBOGMECEHLD(NFKHLLDFHKO);
		HLCFGIFLPPE.IDPNBGBLJGL(pBPEMFGPGFC, IMAMEFOKGFM);
	}

	public static void ELMEPCJAHJN(this JPAALKCPGNB HLCFGIFLPPE, string NFKHLLDFHKO, KGMHJGFNPFC DCMDAJJBNAI, List<OAMNGFLKEFI> IMAMEFOKGFM)
	{
		int pBPEMFGPGFC = DCMDAJJBNAI.IBOGMECEHLD(NFKHLLDFHKO);
		HLCFGIFLPPE.ELMEPCJAHJN(pBPEMFGPGFC, IMAMEFOKGFM);
	}
}
