using System.Collections;
using Org.BouncyCastle.Math;

public class OAGIJKBMDEP
{
	internal class ILDDALOMPKL : NEICIJLPHLA
	{
		internal static readonly NEICIJLPHLA GABGKBAKHDP = new ILDDALOMPKL();

		private ILDDALOMPKL()
		{
		}

		protected override JMLDNPGFBDA HCBKBOFPBMC()
		{
			BigInteger oKDPJHOEPBJ = CGHDJLLJDGE("F1FD178C0B3AD58F10126DE8CE42435B3961ADBCABC8CA6DE8FCF353D86E9C03");
			BigInteger mNIMEAMHNMI = CGHDJLLJDGE("F1FD178C0B3AD58F10126DE8CE42435B3961ADBCABC8CA6DE8FCF353D86E9C00");
			BigInteger bCIHLCMFAEK = CGHDJLLJDGE("EE353FCA5428A9300D4ABA754A44C00FDFEC0C9AE4B1A1803075ED967B7BB73F");
			byte[] hJBOEOOLOOE = null;
			BigInteger bigInteger = CGHDJLLJDGE("F1FD178C0B3AD58F10126DE8CE42435B53DC67E140D2BF941FFDD459C6D655E1");
			BigInteger one = BigInteger.One;
			BHPIABAGAPB bHPIABAGAPB = LEFIAJHMAML(new BMIMOOLAJAL(oKDPJHOEPBJ, mNIMEAMHNMI, bCIHLCMFAEK, bigInteger, one));
			EPOKPEIHHJG hJMBDGKAOBP = new EPOKPEIHHJG(bHPIABAGAPB, DCDJMDOEKHC.ILOALOLANOL("04B6B3D4C356C139EB31183D4749D423958C27D2DCAF98B70164C97A2DD98F5CFF6142E0F7C8B204911F9271F0F3ECEF8C2701C307E8E4C9E183115A1554062CFB"));
			return new JMLDNPGFBDA(bHPIABAGAPB, hJMBDGKAOBP, bigInteger, one, hJBOEOOLOOE);
		}
	}

	private static readonly IDictionary JHHPAIKDGHF;

	private static readonly IDictionary BFCKICBPMJM;

	private static readonly IDictionary ANNGLDLKCBL;

	public static IEnumerable IBDKONGLAHK
	{
		get
		{
			return new FLJIAKGGJBO(ANNGLDLKCBL.Values);
		}
	}

	static OAGIJKBMDEP()
	{
		JHHPAIKDGHF = LHFGHNFJIKM.JBEOCJEMGCE();
		BFCKICBPMJM = LHFGHNFJIKM.JBEOCJEMGCE();
		ANNGLDLKCBL = LHFGHNFJIKM.JBEOCJEMGCE();
		PCHKFJJIDPO("FRP256v1", EICDABKGAGJ.JOHADEEAELF, ILDDALOMPKL.GABGKBAKHDP);
	}

	private static BHPIABAGAPB LEFIAJHMAML(BHPIABAGAPB NINILENHPHE)
	{
		return NINILENHPHE;
	}

	private static BigInteger CGHDJLLJDGE(string PEGNALIKDPB)
	{
		return new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL(PEGNALIKDPB));
	}

	private static void PCHKFJJIDPO(string IOCMOCCFALN, KLKJHFKJLEM GDFLIKNMBCL, NEICIJLPHLA EAMLGFKCICO)
	{
		JHHPAIKDGHF.Add(LHFGHNFJIKM.OGLCLCODHJI(IOCMOCCFALN), GDFLIKNMBCL);
		ANNGLDLKCBL.Add(GDFLIKNMBCL, IOCMOCCFALN);
		BFCKICBPMJM.Add(GDFLIKNMBCL, EAMLGFKCICO);
	}

	public static JMLDNPGFBDA KJOGHMPFOHL(string IOCMOCCFALN)
	{
		KLKJHFKJLEM kLKJHFKJLEM = MAKKKJHMAHH(IOCMOCCFALN);
		return (kLKJHFKJLEM != null) ? BHLONOMMIGE(kLKJHFKJLEM) : null;
	}

	public static JMLDNPGFBDA BHLONOMMIGE(KLKJHFKJLEM GDFLIKNMBCL)
	{
		NEICIJLPHLA nEICIJLPHLA = (NEICIJLPHLA)BFCKICBPMJM[GDFLIKNMBCL];
		return (nEICIJLPHLA != null) ? nEICIJLPHLA.KPJHHAAOFOH : null;
	}

	public static KLKJHFKJLEM MAKKKJHMAHH(string IOCMOCCFALN)
	{
		return (KLKJHFKJLEM)JHHPAIKDGHF[LHFGHNFJIKM.OGLCLCODHJI(IOCMOCCFALN)];
	}

	public static string CILJKDELPFP(KLKJHFKJLEM GDFLIKNMBCL)
	{
		return (string)ANNGLDLKCBL[GDFLIKNMBCL];
	}
}
