using System;
using System.Collections;
using System.IO;

public class OCLDHIDJHBP : KKHDKCFMKNN
{
	protected COEMJAGOFJJ CAACNJEGLIP;

	protected PLGGNEJEIIP LOKLICAJPBN;

	protected MFDKIKBICOJ AIFOKDNIJLN;

	protected byte[] PDALCJHNKGE;

	public OCLDHIDJHBP(IList GMLLEBDADDP)
		: base(1, GMLLEBDADDP)
	{
	}

	public override void PHFBGHEJBHM()
	{
		throw new DEIDBCPPCMB(10);
	}

	public override void OPECIECMFCD(OPCLIKBOHJP BGFNAKMFCHD)
	{
		if (!(BGFNAKMFCHD is MFDKIKBICOJ))
		{
			throw new DEIDBCPPCMB(80);
		}
		BGLKKBMEEEK(BGFNAKMFCHD.BIBHHNBEJJM);
		AIFOKDNIJLN = (MFDKIKBICOJ)BGFNAKMFCHD;
	}

	public override void BGLKKBMEEEK(PAJJBHMEFKE EIMEPDCAJLE)
	{
		if (EIMEPDCAJLE.DHIKCKFGKID)
		{
			throw new DEIDBCPPCMB(42);
		}
		NGNPCPDMGBC nGNPCPDMGBC = EIMEPDCAJLE.IGGCPKOFOMP(0);
		MHBCFNELGOJ mJHHKCCPFEE = nGNPCPDMGBC.KBGJHCMPCGH;
		try
		{
			CAACNJEGLIP = JHGHHFDFJEG.HCBKCKKDGCP(mJHHKCCPFEE);
		}
		catch (Exception cEDNDOAMNOC)
		{
			throw new DEIDBCPPCMB(43, cEDNDOAMNOC);
		}
		if (CAACNJEGLIP.CCLHEKOIIKM)
		{
			throw new DEIDBCPPCMB(80);
		}
		LOKLICAJPBN = GPOGLBCLDIB((PLGGNEJEIIP)CAACNJEGLIP);
		KINEBFNENMB.EPMGOMGGBIE(nGNPCPDMGBC, 32);
		base.BGLKKBMEEEK(EIMEPDCAJLE);
	}

	public override void JNMIHCPINHE(OOKLBMMBONO FJLPCHOBGAM)
	{
		byte[] array = FJLPCHOBGAM.JBMMCGPHNBP;
		foreach (byte b in array)
		{
			if (b != 1 && b != 2 && b != 64)
			{
				throw new DEIDBCPPCMB(47);
			}
		}
	}

	public override void FBGFHDOCEOO(OPCLIKBOHJP CLBMIAJGDMO)
	{
		if (!(CLBMIAJGDMO is IAJODODPMMG))
		{
			throw new DEIDBCPPCMB(80);
		}
	}

	public override void BAILJOPLLNN(Stream BILGCJNPJGJ)
	{
		PDALCJHNKGE = HFGFAOLJPHF.AANGBKGHEJJ(COOBIGONLDK, LOKLICAJPBN, BILGCJNPJGJ);
	}

	public override void DHMEHGEGGCB(Stream MOPCLEEGDFB)
	{
		byte[] hLIAONOOKAD = ((!KINEBFNENMB.NFEADLBGDGE(COOBIGONLDK)) ? KINEBFNENMB.HDGCNMILKAA(MOPCLEEGDFB) : NPBFDBCHIGL.FOJKFJEEFJN(MOPCLEEGDFB));
		PDALCJHNKGE = AIFOKDNIJLN.JIKCAFDHLND(hLIAONOOKAD);
	}

	public override byte[] CGMFKLNEDAP()
	{
		if (PDALCJHNKGE == null)
		{
			throw new DEIDBCPPCMB(80);
		}
		byte[] pDALCJHNKGE = PDALCJHNKGE;
		PDALCJHNKGE = null;
		return pDALCJHNKGE;
	}

	protected virtual PLGGNEJEIIP GPOGLBCLDIB(PLGGNEJEIIP IKNCPEPOKGJ)
	{
		if (!IKNCPEPOKGJ.MFIHJHFAEFB.LKECIHLDEIP(2))
		{
			throw new DEIDBCPPCMB(47);
		}
		return IKNCPEPOKGJ;
	}
}
