using Assets.Scripts.CasualTools.Common.DB;

public class OFGGFEJGABH : Entity
{
	public string KJACEODCOHN;

	public int OADDPGNIINO;

	public string EFHEIFMEJCN;

	public string FGPGOGEKDAM;

	public int DJADMBLKBKJ;

	public int GGBEMNJNAEE;

	public long GHBJBDACBAH;

	public long GDMECFECCOM;

	public int AMKMOFAHFOC;

	public OFGGFEJGABH(int? BDKFNEDHAOJ, string FBKDKPCDMMK, int EMNOJOHFMEH, string GKNCJMICJEL, string PMKHOPIMKNH, int MGCMMJPNJPH, int OLFDKEDGHHF, long MMOMIFJEHLN, long BPKJLGJDFKG, int OMOCHOLJCIL)
	{
		PNLKNJNILDD(BDKFNEDHAOJ);
		KJACEODCOHN = FBKDKPCDMMK;
		OADDPGNIINO = EMNOJOHFMEH;
		EFHEIFMEJCN = GKNCJMICJEL;
		FGPGOGEKDAM = PMKHOPIMKNH;
		DJADMBLKBKJ = MGCMMJPNJPH;
		GGBEMNJNAEE = OLFDKEDGHHF;
		GHBJBDACBAH = MMOMIFJEHLN;
		GDMECFECCOM = BPKJLGJDFKG;
		AMKMOFAHFOC = OMOCHOLJCIL;
	}
}
