using System;

internal class OGEPGLJFBEH : OMOBJNLGOBO
{
	public OGEPGLJFBEH(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public OGEPGLJFBEH(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal OGEPGLJFBEH(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new OGEPGLJFBEH(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		DEHIGCEHECB dEHIGCEHECB = (DEHIGCEHECB)base.NBPANDNEJGI;
		DEHIGCEHECB dEHIGCEHECB2 = (DEHIGCEHECB)base.FIJLKLCHMGH;
		DEHIGCEHECB dEHIGCEHECB3 = (DEHIGCEHECB)BCIHLCMFAEK.NBPANDNEJGI;
		DEHIGCEHECB dEHIGCEHECB4 = (DEHIGCEHECB)BCIHLCMFAEK.FIJLKLCHMGH;
		DEHIGCEHECB dEHIGCEHECB5 = (DEHIGCEHECB)base.LAMGGDKLPJH[0];
		DEHIGCEHECB dEHIGCEHECB6 = (DEHIGCEHECB)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = PHEKPHCPKLA.DCPJKFEDHOJ();
		uint[] array2 = PHEKPHCPKLA.PLIFFMMBNPM();
		uint[] array3 = PHEKPHCPKLA.PLIFFMMBNPM();
		uint[] array4 = PHEKPHCPKLA.PLIFFMMBNPM();
		bool flag = dEHIGCEHECB5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = dEHIGCEHECB3.AMFCENFNAJJ;
			array6 = dEHIGCEHECB4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			AJGCHNBEMAE.MIOEHGDPGAG(dEHIGCEHECB5.AMFCENFNAJJ, array6);
			array5 = array2;
			AJGCHNBEMAE.IBJBIGNPNEM(array6, dEHIGCEHECB3.AMFCENFNAJJ, array5);
			AJGCHNBEMAE.IBJBIGNPNEM(array6, dEHIGCEHECB5.AMFCENFNAJJ, array6);
			AJGCHNBEMAE.IBJBIGNPNEM(array6, dEHIGCEHECB4.AMFCENFNAJJ, array6);
		}
		bool flag2 = dEHIGCEHECB6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = dEHIGCEHECB.AMFCENFNAJJ;
			array8 = dEHIGCEHECB2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			AJGCHNBEMAE.MIOEHGDPGAG(dEHIGCEHECB6.AMFCENFNAJJ, array8);
			array7 = array;
			AJGCHNBEMAE.IBJBIGNPNEM(array8, dEHIGCEHECB.AMFCENFNAJJ, array7);
			AJGCHNBEMAE.IBJBIGNPNEM(array8, dEHIGCEHECB6.AMFCENFNAJJ, array8);
			AJGCHNBEMAE.IBJBIGNPNEM(array8, dEHIGCEHECB2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = PHEKPHCPKLA.PLIFFMMBNPM();
		AJGCHNBEMAE.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		AJGCHNBEMAE.FBGIHKPECCO(array8, array6, array10);
		if (PHEKPHCPKLA.EJJHHCOFAAI(array9))
		{
			if (PHEKPHCPKLA.EJJHHCOFAAI(array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		AJGCHNBEMAE.MIOEHGDPGAG(array9, array11);
		uint[] array12 = PHEKPHCPKLA.PLIFFMMBNPM();
		AJGCHNBEMAE.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		AJGCHNBEMAE.IBJBIGNPNEM(array11, array7, array13);
		AJGCHNBEMAE.BHKOFHMDACN(array12, array12);
		PHEKPHCPKLA.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = PHEKPHCPKLA.FIBDFFPCDGC(array13, array13, array12);
		AJGCHNBEMAE.KKIGIOINLCI(aMFCENFNAJJ, array12);
		DEHIGCEHECB dEHIGCEHECB7 = new DEHIGCEHECB(array4);
		AJGCHNBEMAE.MIOEHGDPGAG(array10, dEHIGCEHECB7.AMFCENFNAJJ);
		AJGCHNBEMAE.FBGIHKPECCO(dEHIGCEHECB7.AMFCENFNAJJ, array12, dEHIGCEHECB7.AMFCENFNAJJ);
		DEHIGCEHECB dEHIGCEHECB8 = new DEHIGCEHECB(array12);
		AJGCHNBEMAE.FBGIHKPECCO(array13, dEHIGCEHECB7.AMFCENFNAJJ, dEHIGCEHECB8.AMFCENFNAJJ);
		AJGCHNBEMAE.OMJFFHEIEFH(dEHIGCEHECB8.AMFCENFNAJJ, array10, array);
		AJGCHNBEMAE.BKCHMGKFECM(array, dEHIGCEHECB8.AMFCENFNAJJ);
		DEHIGCEHECB dEHIGCEHECB9 = new DEHIGCEHECB(array9);
		if (!flag)
		{
			AJGCHNBEMAE.IBJBIGNPNEM(dEHIGCEHECB9.AMFCENFNAJJ, dEHIGCEHECB5.AMFCENFNAJJ, dEHIGCEHECB9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			AJGCHNBEMAE.IBJBIGNPNEM(dEHIGCEHECB9.AMFCENFNAJJ, dEHIGCEHECB6.AMFCENFNAJJ, dEHIGCEHECB9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { dEHIGCEHECB9 };
		return new OGEPGLJFBEH(bHPIABAGAPB, dEHIGCEHECB7, dEHIGCEHECB8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		DEHIGCEHECB dEHIGCEHECB = (DEHIGCEHECB)base.FIJLKLCHMGH;
		if (dEHIGCEHECB.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		DEHIGCEHECB dEHIGCEHECB2 = (DEHIGCEHECB)base.NBPANDNEJGI;
		DEHIGCEHECB dEHIGCEHECB3 = (DEHIGCEHECB)base.LAMGGDKLPJH[0];
		uint[] array = PHEKPHCPKLA.PLIFFMMBNPM();
		AJGCHNBEMAE.MIOEHGDPGAG(dEHIGCEHECB.AMFCENFNAJJ, array);
		uint[] array2 = PHEKPHCPKLA.PLIFFMMBNPM();
		AJGCHNBEMAE.MIOEHGDPGAG(array, array2);
		uint[] array3 = PHEKPHCPKLA.PLIFFMMBNPM();
		AJGCHNBEMAE.MIOEHGDPGAG(dEHIGCEHECB2.AMFCENFNAJJ, array3);
		uint aMFCENFNAJJ = PHEKPHCPKLA.FIBDFFPCDGC(array3, array3, array3);
		AJGCHNBEMAE.KKIGIOINLCI(aMFCENFNAJJ, array3);
		uint[] array4 = array;
		AJGCHNBEMAE.IBJBIGNPNEM(array, dEHIGCEHECB2.AMFCENFNAJJ, array4);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(6, array4, 2, 0u);
		AJGCHNBEMAE.KKIGIOINLCI(aMFCENFNAJJ, array4);
		uint[] array5 = PHEKPHCPKLA.PLIFFMMBNPM();
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(6, array2, 3, 0u, array5);
		AJGCHNBEMAE.KKIGIOINLCI(aMFCENFNAJJ, array5);
		DEHIGCEHECB dEHIGCEHECB4 = new DEHIGCEHECB(array2);
		AJGCHNBEMAE.MIOEHGDPGAG(array3, dEHIGCEHECB4.AMFCENFNAJJ);
		AJGCHNBEMAE.FBGIHKPECCO(dEHIGCEHECB4.AMFCENFNAJJ, array4, dEHIGCEHECB4.AMFCENFNAJJ);
		AJGCHNBEMAE.FBGIHKPECCO(dEHIGCEHECB4.AMFCENFNAJJ, array4, dEHIGCEHECB4.AMFCENFNAJJ);
		DEHIGCEHECB dEHIGCEHECB5 = new DEHIGCEHECB(array4);
		AJGCHNBEMAE.FBGIHKPECCO(array4, dEHIGCEHECB4.AMFCENFNAJJ, dEHIGCEHECB5.AMFCENFNAJJ);
		AJGCHNBEMAE.IBJBIGNPNEM(dEHIGCEHECB5.AMFCENFNAJJ, array3, dEHIGCEHECB5.AMFCENFNAJJ);
		AJGCHNBEMAE.FBGIHKPECCO(dEHIGCEHECB5.AMFCENFNAJJ, array5, dEHIGCEHECB5.AMFCENFNAJJ);
		DEHIGCEHECB dEHIGCEHECB6 = new DEHIGCEHECB(array3);
		AJGCHNBEMAE.LLGLJBDLBOP(dEHIGCEHECB.AMFCENFNAJJ, dEHIGCEHECB6.AMFCENFNAJJ);
		if (!dEHIGCEHECB3.EOJCHPEGABD)
		{
			AJGCHNBEMAE.IBJBIGNPNEM(dEHIGCEHECB6.AMFCENFNAJJ, dEHIGCEHECB3.AMFCENFNAJJ, dEHIGCEHECB6.AMFCENFNAJJ);
		}
		return new OGEPGLJFBEH(bHPIABAGAPB, dEHIGCEHECB4, dEHIGCEHECB5, new KBINBLGGLNE[1] { dEHIGCEHECB6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new OGEPGLJFBEH(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
