using System;
using UnityEngine;

public static class OGMNDNMEKCK
{
	private const float DOGGBEAAOPG = 0.003921569f;

	public static Color OCJJFABLAGB(this GCJKICAPOFL IBBBMACIBGK)
	{
		return new Color(IBBBMACIBGK.GPGDCCMECGF, IBBBMACIBGK.HJMBDGKAOBP, IBBBMACIBGK.BCIHLCMFAEK, IBBBMACIBGK.MNIMEAMHNMI);
	}

	public static Color OCJJFABLAGB(this MKEALIMJCFJ MNIMEAMHNMI)
	{
		return new Color(MNIMEAMHNMI.GPGDCCMECGF, MNIMEAMHNMI.HJMBDGKAOBP, MNIMEAMHNMI.BCIHLCMFAEK, MNIMEAMHNMI.MNIMEAMHNMI);
	}

	public static Color OCJJFABLAGB(this MGCLDKAFCIB MNIMEAMHNMI)
	{
		return new Color(MNIMEAMHNMI.GPGDCCMECGF, MNIMEAMHNMI.HJMBDGKAOBP, MNIMEAMHNMI.BCIHLCMFAEK, MNIMEAMHNMI.MNIMEAMHNMI);
	}

	public static void FHGEHEFAHKO(this GCJKICAPOFL GDNININLMFD, Color MFODILBOMGD)
	{
		GDNININLMFD.JEHECJGFJEB = MFODILBOMGD.a;
		GDNININLMFD.GOEFJMNOBHA = MFODILBOMGD.r;
		GDNININLMFD.HBGOKILMBJG = MFODILBOMGD.g;
		GDNININLMFD.FPKDKHJKEEF = MFODILBOMGD.b;
	}

	public static void FHGEHEFAHKO(this GCJKICAPOFL GDNININLMFD, Color32 MFODILBOMGD)
	{
		GDNININLMFD.JEHECJGFJEB = (float)(int)MFODILBOMGD.a * 0.003921569f;
		GDNININLMFD.GOEFJMNOBHA = (float)(int)MFODILBOMGD.r * 0.003921569f;
		GDNININLMFD.HBGOKILMBJG = (float)(int)MFODILBOMGD.g * 0.003921569f;
		GDNININLMFD.FPKDKHJKEEF = (float)(int)MFODILBOMGD.b * 0.003921569f;
	}

	public static void FHGEHEFAHKO(this LBBAMMPJKDA DFKJODFHCJB, Color MFODILBOMGD)
	{
		DFKJODFHCJB.JEHECJGFJEB = MFODILBOMGD.a;
		DFKJODFHCJB.GOEFJMNOBHA = MFODILBOMGD.r;
		DFKJODFHCJB.HBGOKILMBJG = MFODILBOMGD.g;
		DFKJODFHCJB.FPKDKHJKEEF = MFODILBOMGD.b;
	}

	public static void FHGEHEFAHKO(this LBBAMMPJKDA DFKJODFHCJB, Color32 MFODILBOMGD)
	{
		DFKJODFHCJB.JEHECJGFJEB = (float)(int)MFODILBOMGD.a * 0.003921569f;
		DFKJODFHCJB.GOEFJMNOBHA = (float)(int)MFODILBOMGD.r * 0.003921569f;
		DFKJODFHCJB.HBGOKILMBJG = (float)(int)MFODILBOMGD.g * 0.003921569f;
		DFKJODFHCJB.FPKDKHJKEEF = (float)(int)MFODILBOMGD.b * 0.003921569f;
	}

	public static void FHGEHEFAHKO(this MKEALIMJCFJ DFHHMKMLCFF, Color MFODILBOMGD)
	{
		DFHHMKMLCFF.JEHECJGFJEB = MFODILBOMGD.a;
		DFHHMKMLCFF.GOEFJMNOBHA = MFODILBOMGD.r;
		DFHHMKMLCFF.HBGOKILMBJG = MFODILBOMGD.g;
		DFHHMKMLCFF.FPKDKHJKEEF = MFODILBOMGD.b;
	}

	public static void FHGEHEFAHKO(this MKEALIMJCFJ DFHHMKMLCFF, Color32 MFODILBOMGD)
	{
		DFHHMKMLCFF.JEHECJGFJEB = (float)(int)MFODILBOMGD.a * 0.003921569f;
		DFHHMKMLCFF.GOEFJMNOBHA = (float)(int)MFODILBOMGD.r * 0.003921569f;
		DFHHMKMLCFF.HBGOKILMBJG = (float)(int)MFODILBOMGD.g * 0.003921569f;
		DFHHMKMLCFF.FPKDKHJKEEF = (float)(int)MFODILBOMGD.b * 0.003921569f;
	}

	public static void FHGEHEFAHKO(this MGCLDKAFCIB DFHHMKMLCFF, Color MFODILBOMGD)
	{
		DFHHMKMLCFF.JEHECJGFJEB = MFODILBOMGD.a;
		DFHHMKMLCFF.GOEFJMNOBHA = MFODILBOMGD.r;
		DFHHMKMLCFF.HBGOKILMBJG = MFODILBOMGD.g;
		DFHHMKMLCFF.FPKDKHJKEEF = MFODILBOMGD.b;
	}

	public static void FHGEHEFAHKO(this MGCLDKAFCIB DFHHMKMLCFF, Color32 MFODILBOMGD)
	{
		DFHHMKMLCFF.JEHECJGFJEB = (float)(int)MFODILBOMGD.a * 0.003921569f;
		DFHHMKMLCFF.GOEFJMNOBHA = (float)(int)MFODILBOMGD.r * 0.003921569f;
		DFHHMKMLCFF.HBGOKILMBJG = (float)(int)MFODILBOMGD.g * 0.003921569f;
		DFHHMKMLCFF.FPKDKHJKEEF = (float)(int)MFODILBOMGD.b * 0.003921569f;
	}

	public static void BKFKLBADLEJ(this NBKCFDOMAPI JEBEPBEGCCF, Vector2 LDMDBPLADGD)
	{
		JEBEPBEGCCF.CBPFFIBINEH = LDMDBPLADGD.x;
		JEBEPBEGCCF.MOAGLBJDKKL = LDMDBPLADGD.y;
	}

	public static void BKFKLBADLEJ(this NBKCFDOMAPI JEBEPBEGCCF, Vector3 LDMDBPLADGD)
	{
		JEBEPBEGCCF.CBPFFIBINEH = LDMDBPLADGD.x;
		JEBEPBEGCCF.MOAGLBJDKKL = LDMDBPLADGD.y;
	}

	public static Vector2 KCOPJPHPCDA(this NBKCFDOMAPI JEBEPBEGCCF)
	{
		return new Vector2(JEBEPBEGCCF.AMFCENFNAJJ, JEBEPBEGCCF.CNLILOEEBOJ);
	}

	public static Vector2 IFGMHFLEMPL(this NBKCFDOMAPI JEBEPBEGCCF)
	{
		return new Vector2(JEBEPBEGCCF.POFLEELFBPH, JEBEPBEGCCF.MLMBGGJGOBP);
	}

	public static Vector2 IFGMHFLEMPL(this NBKCFDOMAPI JEBEPBEGCCF, Vector2 NPLANAPFBKB)
	{
		Vector2 result = default(Vector2);
		JEBEPBEGCCF.EMLJIFGGEJI(NPLANAPFBKB.x, NPLANAPFBKB.y, out result.x, out result.y);
		return result;
	}

	public static Vector3 CILLOIFLALH(this NBKCFDOMAPI JEBEPBEGCCF, Transform LPKDDMKGKAC)
	{
		return LPKDDMKGKAC.TransformPoint(new Vector3(JEBEPBEGCCF.POFLEELFBPH, JEBEPBEGCCF.MLMBGGJGOBP));
	}

	public static Vector3 CILLOIFLALH(this NBKCFDOMAPI JEBEPBEGCCF, Transform LPKDDMKGKAC, float BDKCMFMEIEN)
	{
		return LPKDDMKGKAC.TransformPoint(new Vector3(JEBEPBEGCCF.POFLEELFBPH * BDKCMFMEIEN, JEBEPBEGCCF.MLMBGGJGOBP * BDKCMFMEIEN));
	}

	public static Quaternion LFBAECLADMJ(this NBKCFDOMAPI JEBEPBEGCCF)
	{
		float f = Mathf.Atan2(JEBEPBEGCCF.FMFABAKPMLB, JEBEPBEGCCF.MNIMEAMHNMI) * 0.5f;
		return new Quaternion(0f, 0f, Mathf.Sin(f), Mathf.Cos(f));
	}

	public static Quaternion GEHJEONNANI(this NBKCFDOMAPI JEBEPBEGCCF)
	{
		float f = JEBEPBEGCCF.ODLHFMOPCHL * ((float)Math.PI / 180f) * 0.5f;
		return new Quaternion(0f, 0f, Mathf.Sin(f), Mathf.Cos(f));
	}

	public static Vector3 CILLOIFLALH(this ENIPPOEKJPA DFHHMKMLCFF, LBBAMMPJKDA DFKJODFHCJB, Transform LPKDDMKGKAC)
	{
		Vector3 position = default(Vector3);
		position.z = 0f;
		DFHHMKMLCFF.MPNHFIOIEAK(DFKJODFHCJB.JEBEPBEGCCF, out position.x, out position.y);
		return LPKDDMKGKAC.TransformPoint(position);
	}

	public static Vector3 CILLOIFLALH(this ENIPPOEKJPA DFHHMKMLCFF, NBKCFDOMAPI JEBEPBEGCCF, Transform LPKDDMKGKAC)
	{
		Vector3 position = default(Vector3);
		position.z = 0f;
		DFHHMKMLCFF.MPNHFIOIEAK(JEBEPBEGCCF, out position.x, out position.y);
		return LPKDDMKGKAC.TransformPoint(position);
	}

	public static Matrix4x4 HBDIOEEBKAO(this NBKCFDOMAPI JEBEPBEGCCF)
	{
		Matrix4x4 result = default(Matrix4x4);
		result.m00 = JEBEPBEGCCF.MNIMEAMHNMI;
		result.m01 = JEBEPBEGCCF.BCIHLCMFAEK;
		result.m03 = JEBEPBEGCCF.POFLEELFBPH;
		result.m10 = JEBEPBEGCCF.FMFABAKPMLB;
		result.m11 = JEBEPBEGCCF.ELNCCDELMMH;
		result.m13 = JEBEPBEGCCF.MLMBGGJGOBP;
		result.m33 = 1f;
		return result;
	}

	public static void CEPKHJACGCP(this NBKCFDOMAPI JEBEPBEGCCF, out float CLAHNODNHIC, out float MOIFELPADDI, out float APHHMOJNABE, out float BDKFNEDHAOJ)
	{
		float mNIMEAMHNMI = JEBEPBEGCCF.MNIMEAMHNMI;
		float bCIHLCMFAEK = JEBEPBEGCCF.BCIHLCMFAEK;
		float fMFABAKPMLB = JEBEPBEGCCF.FMFABAKPMLB;
		float eLNCCDELMMH = JEBEPBEGCCF.ELNCCDELMMH;
		float num = 1f / (mNIMEAMHNMI * eLNCCDELMMH - bCIHLCMFAEK * fMFABAKPMLB);
		CLAHNODNHIC = num * eLNCCDELMMH;
		MOIFELPADDI = num * (0f - bCIHLCMFAEK);
		APHHMOJNABE = num * (0f - fMFABAKPMLB);
		BDKFNEDHAOJ = num * mNIMEAMHNMI;
	}

	public static Vector2 CHJAOIEALAC(this NBKCFDOMAPI JEBEPBEGCCF, Vector2 ANAPEELIOJJ)
	{
		Vector2 result = default(Vector2);
		JEBEPBEGCCF.CHJAOIEALAC(ANAPEELIOJJ.x, ANAPEELIOJJ.y, out result.x, out result.y);
		return result;
	}

	public static Vector2 KOBLMNKJOIC(this NBKCFDOMAPI JEBEPBEGCCF, Vector2 HBLJJIGMGNF)
	{
		if (JEBEPBEGCCF.LIMMFGDCLAB == null)
		{
			JEBEPBEGCCF.BKFKLBADLEJ(HBLJJIGMGNF);
			return HBLJJIGMGNF;
		}
		NBKCFDOMAPI lIMMFGDCLAB = JEBEPBEGCCF.LIMMFGDCLAB;
		Vector2 vector = lIMMFGDCLAB.CHJAOIEALAC(HBLJJIGMGNF);
		JEBEPBEGCCF.BKFKLBADLEJ(vector);
		return vector;
	}

	public static Material JNMHGFLJDKP(this OAMNGFLKEFI MNIMEAMHNMI)
	{
		object obj = null;
		MKEALIMJCFJ mKEALIMJCFJ = MNIMEAMHNMI as MKEALIMJCFJ;
		if (mKEALIMJCFJ != null)
		{
			obj = mKEALIMJCFJ.HIPOEPNPBPO;
		}
		MGCLDKAFCIB mGCLDKAFCIB = MNIMEAMHNMI as MGCLDKAFCIB;
		if (mGCLDKAFCIB != null)
		{
			obj = mGCLDKAFCIB.HIPOEPNPBPO;
		}
		if (obj == null)
		{
			return null;
		}
		return (Material)((FCPKAKFLFEG)obj).CPIKPMLODAK.FDCGLBIAFPB;
	}

	public static Vector2[] PLNHJCIEKHM(this LJPHFIKMDHN JIHFFGPOGJL, LBBAMMPJKDA DFKJODFHCJB, Vector2[] DJDKLOJBJCO)
	{
		int mCCBDCEJDBC = JIHFFGPOGJL.MCCBDCEJDBC;
		int num = mCCBDCEJDBC >> 1;
		DJDKLOJBJCO = DJDKLOJBJCO ?? new Vector2[num];
		if (DJDKLOJBJCO.Length < num)
		{
			throw new ArgumentException(string.Format("Vector2 buffer too small. {0} requires an array of size {1}. Use the attachment's .WorldVerticesLength to get the correct size.", JIHFFGPOGJL.PNGPLGHKFDI, mCCBDCEJDBC), "buffer");
		}
		if (JIHFFGPOGJL.LIKIOBHLHHF == null)
		{
			float[] fHBFCAEGPOH = JIHFFGPOGJL.FHBFCAEGPOH;
			for (int i = 0; i < num; i++)
			{
				int num2 = i * 2;
				DJDKLOJBJCO[i] = new Vector2(fHBFCAEGPOH[num2], fHBFCAEGPOH[num2 + 1]);
			}
		}
		else
		{
			float[] array = new float[mCCBDCEJDBC];
			JIHFFGPOGJL.EPLAHNOCDIB(DFKJODFHCJB, array);
			NBKCFDOMAPI jEBEPBEGCCF = DFKJODFHCJB.JEBEPBEGCCF;
			float pOFLEELFBPH = jEBEPBEGCCF.POFLEELFBPH;
			float mLMBGGJGOBP = jEBEPBEGCCF.MLMBGGJGOBP;
			float CLAHNODNHIC;
			float MOIFELPADDI;
			float APHHMOJNABE;
			float BDKFNEDHAOJ;
			jEBEPBEGCCF.CEPKHJACGCP(out CLAHNODNHIC, out MOIFELPADDI, out APHHMOJNABE, out BDKFNEDHAOJ);
			for (int j = 0; j < num; j++)
			{
				int num3 = j * 2;
				float num4 = array[num3] - pOFLEELFBPH;
				float num5 = array[num3 + 1] - mLMBGGJGOBP;
				DJDKLOJBJCO[j] = new Vector2(num4 * CLAHNODNHIC + num5 * MOIFELPADDI, num4 * APHHMOJNABE + num5 * BDKFNEDHAOJ);
			}
		}
		return DJDKLOJBJCO;
	}

	public static Vector2[] IJCLJKIOKEH(this LJPHFIKMDHN MNIMEAMHNMI, LBBAMMPJKDA DFKJODFHCJB, Vector2[] DJDKLOJBJCO)
	{
		int mCCBDCEJDBC = MNIMEAMHNMI.MCCBDCEJDBC;
		int num = mCCBDCEJDBC >> 1;
		DJDKLOJBJCO = DJDKLOJBJCO ?? new Vector2[num];
		if (DJDKLOJBJCO.Length < num)
		{
			throw new ArgumentException(string.Format("Vector2 buffer too small. {0} requires an array of size {1}. Use the attachment's .WorldVerticesLength to get the correct size.", MNIMEAMHNMI.PNGPLGHKFDI, mCCBDCEJDBC), "buffer");
		}
		float[] array = new float[mCCBDCEJDBC];
		MNIMEAMHNMI.EPLAHNOCDIB(DFKJODFHCJB, array);
		int i = 0;
		for (int num2 = mCCBDCEJDBC >> 1; i < num2; i++)
		{
			int num3 = i * 2;
			DJDKLOJBJCO[i] = new Vector2(array[num3], array[num3 + 1]);
		}
		return DJDKLOJBJCO;
	}
}
