using System;

public class OHELNPHIELD : AENDLCMHDKL
{
	private const ulong CONFBEJFNKL = 11936128518282651045uL;

	private readonly int IAFLPIAHMHA;

	private ulong JEHOIPCKGDO;

	private ulong BHPLNLNHMJP;

	private ulong GBODGGOBCCE;

	private ulong CDHGGLMPBII;

	private ulong JAHEHFCCLCN;

	private ulong MABENEBEHKD;

	private ulong PJMDDGGOGBF;

	private ulong DMEEAAAOJHF;

	public override string KFKMEPMEBND
	{
		get
		{
			return "SHA-512/" + IAFLPIAHMHA * 8;
		}
	}

	public OHELNPHIELD(int EAJFCEBGGIG)
	{
		if (EAJFCEBGGIG >= 512)
		{
			throw new ArgumentException("cannot be >= 512", "bitLength");
		}
		if (EAJFCEBGGIG % 8 != 0)
		{
			throw new ArgumentException("needs to be a multiple of 8", "bitLength");
		}
		if (EAJFCEBGGIG == 384)
		{
			throw new ArgumentException("cannot be 384 use SHA384 instead", "bitLength");
		}
		IAFLPIAHMHA = EAJFCEBGGIG / 8;
		DCIDJIMEGHC(IAFLPIAHMHA * 8);
		OMOKOKFNBKI();
	}

	public OHELNPHIELD(OHELNPHIELD LLIEHCKNJEM)
		: base(LLIEHCKNJEM)
	{
		IAFLPIAHMHA = LLIEHCKNJEM.IAFLPIAHMHA;
		OMOKOKFNBKI(LLIEHCKNJEM);
	}

	public override int EEMLLAMENHO()
	{
		return IAFLPIAHMHA;
	}

	public override int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		OJILOEAPDCL();
		LHKOONEHKNH(NAHACOBOKIM, BILGCJNPJGJ, EMAKNGBIFDC, IAFLPIAHMHA);
		LHKOONEHKNH(MPNNHCHGEGL, BILGCJNPJGJ, EMAKNGBIFDC + 8, IAFLPIAHMHA - 8);
		LHKOONEHKNH(AJBHIPPAFIJ, BILGCJNPJGJ, EMAKNGBIFDC + 16, IAFLPIAHMHA - 16);
		LHKOONEHKNH(GCLNAIGNJJN, BILGCJNPJGJ, EMAKNGBIFDC + 24, IAFLPIAHMHA - 24);
		LHKOONEHKNH(CCFJELJJBPD, BILGCJNPJGJ, EMAKNGBIFDC + 32, IAFLPIAHMHA - 32);
		LHKOONEHKNH(OCNHMOBFIKJ, BILGCJNPJGJ, EMAKNGBIFDC + 40, IAFLPIAHMHA - 40);
		LHKOONEHKNH(HKHGOKHCEGC, BILGCJNPJGJ, EMAKNGBIFDC + 48, IAFLPIAHMHA - 48);
		LHKOONEHKNH(LGOHKGGPEBO, BILGCJNPJGJ, EMAKNGBIFDC + 56, IAFLPIAHMHA - 56);
		OMOKOKFNBKI();
		return IAFLPIAHMHA;
	}

	public override void OMOKOKFNBKI()
	{
		base.OMOKOKFNBKI();
		NAHACOBOKIM = JEHOIPCKGDO;
		MPNNHCHGEGL = BHPLNLNHMJP;
		AJBHIPPAFIJ = GBODGGOBCCE;
		GCLNAIGNJJN = CDHGGLMPBII;
		CCFJELJJBPD = JAHEHFCCLCN;
		OCNHMOBFIKJ = MABENEBEHKD;
		HKHGOKHCEGC = PJMDDGGOGBF;
		LGOHKGGPEBO = DMEEAAAOJHF;
	}

	private void DCIDJIMEGHC(int EAJFCEBGGIG)
	{
		NAHACOBOKIM = 14964410163792538797uL;
		MPNNHCHGEGL = 2216346199247487646uL;
		AJBHIPPAFIJ = 11082046791023156622uL;
		GCLNAIGNJJN = 65953792586715988uL;
		CCFJELJJBPD = 17630457682085488500uL;
		OCNHMOBFIKJ = 4512832404995164602uL;
		HKHGOKHCEGC = 13413544941332994254uL;
		LGOHKGGPEBO = 18322165818757711068uL;
		BPAJGOINFNL(83);
		BPAJGOINFNL(72);
		BPAJGOINFNL(65);
		BPAJGOINFNL(45);
		BPAJGOINFNL(53);
		BPAJGOINFNL(49);
		BPAJGOINFNL(50);
		BPAJGOINFNL(47);
		if (EAJFCEBGGIG > 100)
		{
			BPAJGOINFNL((byte)(EAJFCEBGGIG / 100 + 48));
			EAJFCEBGGIG %= 100;
			BPAJGOINFNL((byte)(EAJFCEBGGIG / 10 + 48));
			EAJFCEBGGIG %= 10;
			BPAJGOINFNL((byte)(EAJFCEBGGIG + 48));
		}
		else if (EAJFCEBGGIG > 10)
		{
			BPAJGOINFNL((byte)(EAJFCEBGGIG / 10 + 48));
			EAJFCEBGGIG %= 10;
			BPAJGOINFNL((byte)(EAJFCEBGGIG + 48));
		}
		else
		{
			BPAJGOINFNL((byte)(EAJFCEBGGIG + 48));
		}
		OJILOEAPDCL();
		JEHOIPCKGDO = NAHACOBOKIM;
		BHPLNLNHMJP = MPNNHCHGEGL;
		GBODGGOBCCE = AJBHIPPAFIJ;
		CDHGGLMPBII = GCLNAIGNJJN;
		JAHEHFCCLCN = CCFJELJJBPD;
		MABENEBEHKD = OCNHMOBFIKJ;
		PJMDDGGOGBF = HKHGOKHCEGC;
		DMEEAAAOJHF = LGOHKGGPEBO;
	}

	private static void LHKOONEHKNH(ulong IDHLPOFDLKJ, byte[] FAPGOCDNGIB, int JBAJPGIAPFF, int NHLJFKPLKLI)
	{
		if (NHLJFKPLKLI > 0)
		{
			MPMAFPANDLC((uint)(IDHLPOFDLKJ >> 32), FAPGOCDNGIB, JBAJPGIAPFF, NHLJFKPLKLI);
			if (NHLJFKPLKLI > 4)
			{
				MPMAFPANDLC((uint)IDHLPOFDLKJ, FAPGOCDNGIB, JBAJPGIAPFF + 4, NHLJFKPLKLI - 4);
			}
		}
	}

	private static void MPMAFPANDLC(uint IDHLPOFDLKJ, byte[] FAPGOCDNGIB, int JBAJPGIAPFF, int NHLJFKPLKLI)
	{
		int num = Math.Min(4, NHLJFKPLKLI);
		while (--num >= 0)
		{
			int num2 = 8 * (3 - num);
			FAPGOCDNGIB[JBAJPGIAPFF + num] = (byte)(IDHLPOFDLKJ >> num2);
		}
	}

	public override MIPBJNJHNGA FDCFKGAEJFF()
	{
		return new OHELNPHIELD(this);
	}

	public override void OMOKOKFNBKI(MIPBJNJHNGA CJHEIBNHNNE)
	{
		OHELNPHIELD oHELNPHIELD = (OHELNPHIELD)CJHEIBNHNNE;
		if (IAFLPIAHMHA != oHELNPHIELD.IAFLPIAHMHA)
		{
			throw new IDFIKGFDIFG("digestLength inappropriate in other");
		}
		AKBPCECABIO(oHELNPHIELD);
		JEHOIPCKGDO = oHELNPHIELD.JEHOIPCKGDO;
		BHPLNLNHMJP = oHELNPHIELD.BHPLNLNHMJP;
		GBODGGOBCCE = oHELNPHIELD.GBODGGOBCCE;
		CDHGGLMPBII = oHELNPHIELD.CDHGGLMPBII;
		JAHEHFCCLCN = oHELNPHIELD.JAHEHFCCLCN;
		MABENEBEHKD = oHELNPHIELD.MABENEBEHKD;
		PJMDDGGOGBF = oHELNPHIELD.PJMDDGGOGBF;
		DMEEAAAOJHF = oHELNPHIELD.DMEEAAAOJHF;
	}
}
