public interface OHPHNNNHCOO
{
	string KFKMEPMEBND { get; }

	void DIOELAHNLKJ(bool KGPBDABMHKH, IGMAJHKIIPK IJJHBEECMBP);

	void BPAJGOINFNL(byte MOPCLEEGDFB);

	void GONEEEFEDGF(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int EOFAGACBNFP);

	byte[] HMJHAKCMGHC();

	bool HLJBBONKPDG(byte[] PINNJBGMGOA);

	void OMOKOKFNBKI();
}
