public struct OIMKDKKJDIK
{
	public int MNBEJMDMOOP;

	public int JGHOCLKHMDA;

	public int IKNCPEPOKGJ;

	public OIMKDKKJDIK(int EPDOPDONCLE, int HKJFIIIGHMB)
	{
		MNBEJMDMOOP = EPDOPDONCLE;
		JGHOCLKHMDA = HKJFIIIGHMB;
		IKNCPEPOKGJ = (HKJFIIIGHMB << 16) + EPDOPDONCLE;
	}
}
