using System.Collections;

public interface OJCLOGGKCCI : NGBFPFEHHNG
{
	void DIOELAHNLKJ(GLNLDNCNFAM MBEMNOCDDBC);

	void LDPCFJGKJJJ(OBDIBELBBEO ANFOFLFNDAK);

	void DGCMNPJKJKG(bool BFFCBKGILHP);

	void BJOELOGEAGI(int[] KEFIFGPCLFN);

	void MHMJICMPEPB(byte[] ABENGDDJMMJ);

	void DAILJBKDCFJ(IDictionary IIBBHNCCBCA);

	OBDIBELBBEO EFCAAEGGBGA();

	int IPCMBJECLAL();

	byte COFIPAAOOAH();

	IDictionary FHPHBEGKHDJ();

	IList MDDAFEPFKNP();

	OPCLIKBOHJP NFMDCNMGECF();

	HMAHNPODDAN GIMKILBAPBB();

	HMPLNBAPPNE CNJBDCLEKNL();

	OOKLBMMBONO EMMBHHGOCKA();

	void FPEDHDHHFKF(IList GHIFLIAKNEC);

	void JGONAHEFOPO(PAJJBHMEFKE HDJIOCGDIKM);

	GDAIELDPMAD MMEHNGIOOGG();
}
