public class OJFANPHGCBK : GDHBILADCFG, HGIAHEKANFO
{
	private readonly MKNDIEHOMOI IGCEJBIEACI;

	internal OJFANPHGCBK(MKNDIEHOMOI BKOBLIALKKC)
	{
		IGCEJBIEACI = BKOBLIALKKC;
	}

	public HGIAHEKANFO DMHLIGLGJGI()
	{
		return IGCEJBIEACI.DMHLIGLGJGI();
	}

	public EDOEBJJFOBM IIHKEACDNID()
	{
		return new KBOHOKHJFBA(IGCEJBIEACI.IFPAJCFNKGJ());
	}
}
