using System;

public class OJKCDPFDMIL : IGMAJHKIIPK
{
	private byte[] FPPIFEACFOK;

	private IGMAJHKIIPK IJJHBEECMBP;

	public IGMAJHKIIPK KPJHHAAOFOH
	{
		get
		{
			return IJJHBEECMBP;
		}
	}

	public OJKCDPFDMIL(IGMAJHKIIPK IJJHBEECMBP, byte[] FPPIFEACFOK)
		: this(IJJHBEECMBP, FPPIFEACFOK, 0, FPPIFEACFOK.Length)
	{
	}

	public OJKCDPFDMIL(IGMAJHKIIPK IJJHBEECMBP, byte[] FPPIFEACFOK, int NOBCMDNELGN, int OGPGBDAMJPJ)
	{
		this.FPPIFEACFOK = new byte[OGPGBDAMJPJ];
		this.IJJHBEECMBP = IJJHBEECMBP;
		Array.Copy(FPPIFEACFOK, NOBCMDNELGN, this.FPPIFEACFOK, 0, OGPGBDAMJPJ);
	}

	public byte[] MPEAIEBOCPI()
	{
		return FPPIFEACFOK;
	}
}
