using System;
using System.Collections;
using System.IO;

public class OKHIDLGBFLD : HEMGBKNMOKB
{
	protected AFKEOGBFCBE LPEBBNDIJEK;

	internal FMFDDEKPADH JDCKGBHGMJC;

	protected byte[] DEJDDNAMLDD;

	protected HMPLNBAPPNE MOCPBMMDBBD;

	protected HFLDELFJCEE DNMPKEIGPNK;

	protected HMAHNPODDAN LHJDFNEOLMO;

	protected OOKLBMMBONO IJAFLLHFFCP;

	protected override CGDEGBGOKJO GMHPAPJFFNC
	{
		get
		{
			return JDCKGBHGMJC;
		}
	}

	internal override KPKGCNEJIAM EMKADIHPAHJ
	{
		get
		{
			return JDCKGBHGMJC;
		}
	}

	protected override NGBFPFEHHNG AHPIDFAOOPF
	{
		get
		{
			return LPEBBNDIJEK;
		}
	}

	public OKHIDLGBFLD(Stream JKKFADEOBOG, FBIJJFGLKMK ENKGBJPFHAO)
		: base(JKKFADEOBOG, ENKGBJPFHAO)
	{
	}

	public OKHIDLGBFLD(Stream MOPCLEEGDFB, Stream BILGCJNPJGJ, FBIJJFGLKMK ENKGBJPFHAO)
		: base(MOPCLEEGDFB, BILGCJNPJGJ, ENKGBJPFHAO)
	{
	}

	public OKHIDLGBFLD(FBIJJFGLKMK ENKGBJPFHAO)
		: base(ENKGBJPFHAO)
	{
	}

	public virtual void HIJKJHKCFIB(AFKEOGBFCBE PPIKJCJAFIA)
	{
		if (PPIKJCJAFIA == null)
		{
			throw new ArgumentNullException("tlsClient");
		}
		if (LPEBBNDIJEK != null)
		{
			throw new InvalidOperationException("'Connect' can only be called once");
		}
		LPEBBNDIJEK = PPIKJCJAFIA;
		CGEBPLCBCCP = new PDCALMCFKGD();
		CGEBPLCBCCP.PICPDNMCHFM = 1;
		JDCKGBHGMJC = new FMFDDEKPADH(BECLOCCFICG, CGEBPLCBCCP);
		CGEBPLCBCCP.NIMMIFGHCAF = HEMGBKNMOKB.NLKGEDCFIGA(PPIKJCJAFIA.BFNMEODGEDL(), JDCKGBHGMJC.EMBMHGPGOIP);
		LPEBBNDIJEK.DIOELAHNLKJ(JDCKGBHGMJC);
		LHNFFJBDNBG.DIOELAHNLKJ(JDCKGBHGMJC);
		POBPBLILLLP pOBPBLILLLP = PPIKJCJAFIA.LACFMMKMGIO();
		if (pOBPBLILLLP != null && pOBPBLILLLP.JLHAIGPFGAL)
		{
			CBKKCJFENJM cBKKCJFENJM = pOBPBLILLLP.BBELHFEBKHO();
			if (cBKKCJFENJM != null)
			{
				FMIPBLFOKFG = pOBPBLILLLP;
				KBNPIGOEJEE = cBKKCJFENJM;
			}
		}
		IHBIDLEKDGM();
		LNHCCIAMIMK = 1;
		PNLFKFJGJAG();
	}

	protected override void JCDEHOJAGIM()
	{
		base.JCDEHOJAGIM();
		DEJDDNAMLDD = null;
		MOCPBMMDBBD = null;
		DNMPKEIGPNK = null;
		LHJDFNEOLMO = null;
		IJAFLLHFFCP = null;
	}

	protected override void JOBBGIDBDLD(byte NBFBPNNEKMN, byte[] MBBPBGHKLJM)
	{
		MemoryStream memoryStream = new MemoryStream(MBBPBGHKLJM, false);
		if (EEBLPIHKADI)
		{
			if (NBFBPNNEKMN != 20 || LNHCCIAMIMK != 2)
			{
				throw new DEIDBCPPCMB(10);
			}
			LPENIPIFLKN(memoryStream);
			LNHCCIAMIMK = 15;
			GDCOIGLDHPP();
			LNHCCIAMIMK = 13;
			LNHCCIAMIMK = 16;
			GGGEFIHCFHI();
			return;
		}
		switch (NBFBPNNEKMN)
		{
		case 11:
		{
			short lNHCCIAMIMK3 = LNHCCIAMIMK;
			if (lNHCCIAMIMK3 == 2 || lNHCCIAMIMK3 == 3)
			{
				if (LNHCCIAMIMK == 2)
				{
					MOEPEBNJCNL(null);
				}
				HOFDFNMIALD = PAJJBHMEFKE.DHCLOMIANOE(memoryStream);
				HEMGBKNMOKB.JILHFDBGNGE(memoryStream);
				if (HOFDFNMIALD == null || HOFDFNMIALD.DHIKCKFGKID)
				{
					AGDDELNONDJ = false;
				}
				MOCPBMMDBBD.BGLKKBMEEEK(HOFDFNMIALD);
				DNMPKEIGPNK = LPEBBNDIJEK.DNHBFEBDMPF();
				DNMPKEIGPNK.NGHHKPODNBG(HOFDFNMIALD);
				LNHCCIAMIMK = 4;
				break;
			}
			throw new DEIDBCPPCMB(10);
		}
		case 22:
		{
			short lNHCCIAMIMK6 = LNHCCIAMIMK;
			if (lNHCCIAMIMK6 == 4)
			{
				if (!AGDDELNONDJ)
				{
					throw new DEIDBCPPCMB(10);
				}
				LHJDFNEOLMO = HMAHNPODDAN.DHCLOMIANOE(memoryStream);
				HEMGBKNMOKB.JILHFDBGNGE(memoryStream);
				LNHCCIAMIMK = 5;
				break;
			}
			throw new DEIDBCPPCMB(10);
		}
		case 20:
		{
			short lNHCCIAMIMK4 = LNHCCIAMIMK;
			if (lNHCCIAMIMK4 == 13 || lNHCCIAMIMK4 == 14)
			{
				if (LNHCCIAMIMK == 13 && MKHIKOCPNPA)
				{
					throw new DEIDBCPPCMB(10);
				}
				LPENIPIFLKN(memoryStream);
				LNHCCIAMIMK = 15;
				LNHCCIAMIMK = 16;
				GGGEFIHCFHI();
				break;
			}
			throw new DEIDBCPPCMB(10);
		}
		case 2:
		{
			short lNHCCIAMIMK5 = LNHCCIAMIMK;
			if (lNHCCIAMIMK5 == 1)
			{
				ADIOMEKKHGB(memoryStream);
				LNHCCIAMIMK = 2;
				LHNFFJBDNBG.HIDDHBFMDNF();
				EJLNOELJHMP();
				if (EEBLPIHKADI)
				{
					CGEBPLCBCCP.IENFDPCIFNJ = NOGCEBKPPJE.IKBFGGABMKP(KBNPIGOEJEE.EFKBHGKOMBB);
					LHNFFJBDNBG.MDHHAEHPIGF(AHPIDFAOOPF.MCBOEBCAGAN(), AHPIDFAOOPF.FKNFDDEJJFO());
					DEKFADHFKIB();
					break;
				}
				GDHEECDEMPM();
				if (DEJDDNAMLDD.Length > 0)
				{
					FMIPBLFOKFG = new IIFHCHFCCDK(DEJDDNAMLDD, null);
				}
				break;
			}
			throw new DEIDBCPPCMB(10);
		}
		case 23:
		{
			short lNHCCIAMIMK = LNHCCIAMIMK;
			if (lNHCCIAMIMK == 2)
			{
				MOEPEBNJCNL(HEMGBKNMOKB.MDHJKJEAHOE(memoryStream));
				break;
			}
			throw new DEIDBCPPCMB(10);
		}
		case 14:
			switch (LNHCCIAMIMK)
			{
			case 2:
			case 3:
			case 4:
			case 5:
			case 6:
			case 7:
			{
				if (LNHCCIAMIMK < 3)
				{
					MOEPEBNJCNL(null);
				}
				if (LNHCCIAMIMK < 4)
				{
					MOCPBMMDBBD.PHFBGHEJBHM();
					DNMPKEIGPNK = null;
				}
				if (LNHCCIAMIMK < 6)
				{
					MOCPBMMDBBD.EDBOAAHOOMB();
				}
				HEMGBKNMOKB.JILHFDBGNGE(memoryStream);
				LNHCCIAMIMK = 8;
				LHNFFJBDNBG.OPLLOBGPFNO.OLDLMNLPAMN();
				IList list = LPEBBNDIJEK.BBJOJOFIFCO();
				if (list != null)
				{
					ECJAMAOIAIN(list);
				}
				LNHCCIAMIMK = 9;
				OPCLIKBOHJP oPCLIKBOHJP = null;
				if (IJAFLLHFFCP == null)
				{
					MOCPBMMDBBD.IPDLGANAAKE();
				}
				else
				{
					oPCLIKBOHJP = DNMPKEIGPNK.BOMAEPDBKLF(GMHPAPJFFNC, IJAFLLHFFCP);
					if (oPCLIKBOHJP == null)
					{
						MOCPBMMDBBD.IPDLGANAAKE();
						HICANOOKJEN(PAJJBHMEFKE.PGOFIDPLOAA);
					}
					else
					{
						MOCPBMMDBBD.FBGFHDOCEOO(oPCLIKBOHJP);
						HICANOOKJEN(oPCLIKBOHJP.BIBHHNBEJJM);
					}
				}
				LNHCCIAMIMK = 10;
				FDHKKKCBJHK();
				LNHCCIAMIMK = 11;
				KKMFHDBDNLF kKMFHDBDNLF = LHNFFJBDNBG.JNFCHMHNLEB();
				CGEBPLCBCCP.BHBIFAOIDDN = HEMGBKNMOKB.EBJDALPFDKD(GMHPAPJFFNC, kKMFHDBDNLF, null);
				HEMGBKNMOKB.AIOOLPKCFFJ(GMHPAPJFFNC, MOCPBMMDBBD);
				LHNFFJBDNBG.MDHHAEHPIGF(AHPIDFAOOPF.MCBOEBCAGAN(), AHPIDFAOOPF.FKNFDDEJJFO());
				if (oPCLIKBOHJP != null && oPCLIKBOHJP is IAJODODPMMG)
				{
					IAJODODPMMG iAJODODPMMG = (IAJODODPMMG)oPCLIKBOHJP;
					FBMKOGABPFL fBMKOGABPFL = KINEBFNENMB.CBMIGMCGDJL(GMHPAPJFFNC, iAJODODPMMG);
					byte[] aIELCDIFLFB = ((fBMKOGABPFL != null) ? kKMFHDBDNLF.LGOMGMANPHC(fBMKOGABPFL.GHMJJKMGKKB) : CGEBPLCBCCP.EPLFAIDNFEH);
					byte[] pINNJBGMGOA = iAJODODPMMG.NPDKOKDCPAF(aIELCDIFLFB);
					NKOAICPNEJH kNLHGCKFLPA = new NKOAICPNEJH(fBMKOGABPFL, pINNJBGMGOA);
					AHBOMENFDON(kNLHGCKFLPA);
					LNHCCIAMIMK = 12;
				}
				DEKFADHFKIB();
				GDCOIGLDHPP();
				LNHCCIAMIMK = 13;
				break;
			}
			default:
				throw new DEIDBCPPCMB(40);
			}
			break;
		case 12:
			switch (LNHCCIAMIMK)
			{
			case 2:
			case 3:
			case 4:
			case 5:
				if (LNHCCIAMIMK < 3)
				{
					MOEPEBNJCNL(null);
				}
				if (LNHCCIAMIMK < 4)
				{
					MOCPBMMDBBD.PHFBGHEJBHM();
					DNMPKEIGPNK = null;
				}
				MOCPBMMDBBD.OJGCPPFDPBN(memoryStream);
				HEMGBKNMOKB.JILHFDBGNGE(memoryStream);
				LNHCCIAMIMK = 6;
				break;
			default:
				throw new DEIDBCPPCMB(10);
			}
			break;
		case 13:
			switch (LNHCCIAMIMK)
			{
			case 4:
			case 5:
			case 6:
				if (LNHCCIAMIMK != 6)
				{
					MOCPBMMDBBD.EDBOAAHOOMB();
				}
				if (DNMPKEIGPNK == null)
				{
					throw new DEIDBCPPCMB(40);
				}
				IJAFLLHFFCP = OOKLBMMBONO.DHCLOMIANOE(GMHPAPJFFNC, memoryStream);
				HEMGBKNMOKB.JILHFDBGNGE(memoryStream);
				MOCPBMMDBBD.JNMIHCPINHE(IJAFLLHFFCP);
				KINEBFNENMB.NBKEFELHCFK(LHNFFJBDNBG.OPLLOBGPFNO, IJAFLLHFFCP.BGMFIEMDPBF);
				LNHCCIAMIMK = 7;
				break;
			default:
				throw new DEIDBCPPCMB(10);
			}
			break;
		case 4:
		{
			short lNHCCIAMIMK2 = LNHCCIAMIMK;
			if (lNHCCIAMIMK2 == 13)
			{
				if (!MKHIKOCPNPA)
				{
					throw new DEIDBCPPCMB(10);
				}
				GDHEECDEMPM();
				CFPPPLBBBJF(memoryStream);
				LNHCCIAMIMK = 14;
				break;
			}
			throw new DEIDBCPPCMB(10);
		}
		case 0:
			HEMGBKNMOKB.JILHFDBGNGE(memoryStream);
			if (LNHCCIAMIMK == 16)
			{
				ACDFNEMNAHP();
			}
			break;
		default:
			throw new DEIDBCPPCMB(10);
		}
	}

	protected virtual void MOEPEBNJCNL(IList FNAIBLIAKCB)
	{
		LPEBBNDIJEK.BIMLMGADCAL(FNAIBLIAKCB);
		LNHCCIAMIMK = 3;
		MOCPBMMDBBD = LPEBBNDIJEK.CNJBDCLEKNL();
		MOCPBMMDBBD.DIOELAHNLKJ(GMHPAPJFFNC);
	}

	protected virtual void CFPPPLBBBJF(MemoryStream GHPCHPOHELF)
	{
		GDAIELDPMAD pIPDHBFKMLP = GDAIELDPMAD.DHCLOMIANOE(GHPCHPOHELF);
		HEMGBKNMOKB.JILHFDBGNGE(GHPCHPOHELF);
		LPEBBNDIJEK.COOBDCPKGBF(pIPDHBFKMLP);
	}

	protected virtual void ADIOMEKKHGB(MemoryStream GHPCHPOHELF)
	{
		OBDIBELBBEO oBDIBELBBEO = KINEBFNENMB.NGLBPHAOKHO(GHPCHPOHELF);
		if (oBDIBELBBEO.KEDPJOBAJBA)
		{
			throw new DEIDBCPPCMB(47);
		}
		if (!oBDIBELBBEO.KIFDKLPDKMD(LHNFFJBDNBG.NGLBPHAOKHO))
		{
			throw new DEIDBCPPCMB(47);
		}
		OBDIBELBBEO dFCJKBHFPMG = GMHPAPJFFNC.BEHNDIMGDKM;
		if (!oBDIBELBBEO.BMJPEMBKPII(dFCJKBHFPMG))
		{
			throw new DEIDBCPPCMB(47);
		}
		LHNFFJBDNBG.PLIGEMIADFP(oBDIBELBBEO);
		EMKADIHPAHJ.JBFNLEHOPGK(oBDIBELBBEO);
		LPEBBNDIJEK.OFBJOJNMMKO(oBDIBELBBEO);
		CGEBPLCBCCP.BKHHFBJJBAB = KINEBFNENMB.PCNDKGFHPJN(32, GHPCHPOHELF);
		DEJDDNAMLDD = KINEBFNENMB.IEIMBOADGLL(GHPCHPOHELF);
		if (DEJDDNAMLDD.Length > 32)
		{
			throw new DEIDBCPPCMB(47);
		}
		LPEBBNDIJEK.AGBLBIICBDC(DEJDDNAMLDD);
		EEBLPIHKADI = DEJDDNAMLDD.Length > 0 && FMIPBLFOKFG != null && NOGCEBKPPJE.ICKLINNFHKK(DEJDDNAMLDD, FMIPBLFOKFG.GLPODMDPMAK);
		int num = KINEBFNENMB.DMHJEBHACNN(GHPCHPOHELF);
		if (!NOGCEBKPPJE.KMDACNACKII(GPDCOOCEGJH, num) || num == 0 || FANICOIIFHE.GICKLEEKGIN(num) || !KINEBFNENMB.JCCJBBOLIDE(num, GMHPAPJFFNC.PJJKOIEAGJN))
		{
			throw new DEIDBCPPCMB(47);
		}
		LPEBBNDIJEK.GHMPCEPDDAB(num);
		byte b = KINEBFNENMB.HEEOKPLLJMG(GHPCHPOHELF);
		if (!NOGCEBKPPJE.KMDACNACKII(FFJFJNKMGNE, b))
		{
			throw new DEIDBCPPCMB(47);
		}
		LPEBBNDIJEK.NMBKKHBCEKJ(b);
		PENJPGNIDJC = HEMGBKNMOKB.JAOKJFGCGBB(GHPCHPOHELF);
		if (PENJPGNIDJC != null)
		{
			foreach (int key in PENJPGNIDJC.Keys)
			{
				if (key != 65281)
				{
					if (KINEBFNENMB.MHMMGPFEAJM(LCAFLJDMMPB, key) == null)
					{
						throw new DEIDBCPPCMB(110);
					}
					if (!EEBLPIHKADI)
					{
					}
				}
			}
		}
		byte[] array = KINEBFNENMB.MHMMGPFEAJM(PENJPGNIDJC, 65281);
		if (array != null)
		{
			DPJCPMCFAEJ = true;
			if (!NOGCEBKPPJE.PBBFCJBKJEN(array, HEMGBKNMOKB.EKBFPCMCPNF(KINEBFNENMB.JBCONIFELBM)))
			{
				throw new DEIDBCPPCMB(40);
			}
		}
		LPEBBNDIJEK.BBHEHNNILKN(DPJCPMCFAEJ);
		IDictionary dictionary = LCAFLJDMMPB;
		IDictionary dictionary2 = PENJPGNIDJC;
		if (EEBLPIHKADI)
		{
			if (num != KBNPIGOEJEE.LKCGPEEINAA || b != KBNPIGOEJEE.OEFPAPDGGKJ)
			{
				throw new DEIDBCPPCMB(47);
			}
			dictionary = null;
			dictionary2 = KBNPIGOEJEE.IFGJJEBBBMJ();
		}
		CGEBPLCBCCP.DHDNFGLNBGJ = num;
		CGEBPLCBCCP.KFCOFBMPANP = b;
		if (dictionary2 != null)
		{
			bool flag = APHMHGMCEML.DINFPLKCLDM(dictionary2);
			if (flag && !KINEBFNENMB.IGJPPGFHMJG(num))
			{
				throw new DEIDBCPPCMB(47);
			}
			CGEBPLCBCCP.DHHNHJLANEO = flag;
			CGEBPLCBCCP.EFPCMNGHEHF = APHMHGMCEML.EBNICMCJKPK(dictionary2);
			CGEBPLCBCCP.GBGOFJPGDJM = HOFFPDHNKCK(dictionary, dictionary2, 47);
			CGEBPLCBCCP.LDOIKDBKMNN = APHMHGMCEML.FAFAJFGALEB(dictionary2);
			AGDDELNONDJ = !EEBLPIHKADI && KINEBFNENMB.NJLIKBLEEFJ(dictionary2, 5, 47);
			MKHIKOCPNPA = !EEBLPIHKADI && KINEBFNENMB.NJLIKBLEEFJ(dictionary2, 35, 47);
		}
		if (dictionary != null)
		{
			LPEBBNDIJEK.BEAKIHMNDJG(dictionary2);
		}
		CGEBPLCBCCP.BCEHFMJLEFK = HEMGBKNMOKB.NGLLOCHMBIP(GMHPAPJFFNC, CGEBPLCBCCP.LKCGPEEINAA);
		CGEBPLCBCCP.NIPNODCEPIH = 12;
	}

	protected virtual void AHBOMENFDON(NKOAICPNEJH KNLHGCKFLPA)
	{
		OLCIAJEPOLP oLCIAJEPOLP = new OLCIAJEPOLP(15);
		KNLHGCKFLPA.LMDBBPLCJDM(oLCIAJEPOLP);
		oLCIAJEPOLP.PGOHFLKIFHM(this);
	}

	protected virtual void IHBIDLEKDGM()
	{
		LHNFFJBDNBG.PLIGEMIADFP(LPEBBNDIJEK.ONMBHGAEFAP);
		OBDIBELBBEO oBDIBELBBEO = LPEBBNDIJEK.BEHNDIMGDKM;
		if (oBDIBELBBEO.KEDPJOBAJBA)
		{
			throw new DEIDBCPPCMB(80);
		}
		EMKADIHPAHJ.MJFGAIIBHKB(oBDIBELBBEO);
		byte[] array = KINEBFNENMB.JBCONIFELBM;
		if (FMIPBLFOKFG != null)
		{
			array = FMIPBLFOKFG.GLPODMDPMAK;
			if (array == null || array.Length > 32)
			{
				array = KINEBFNENMB.JBCONIFELBM;
			}
		}
		bool flag = LPEBBNDIJEK.NABMKHFPEJE;
		GPDCOOCEGJH = LPEBBNDIJEK.JJABFAMPIIB();
		FFJFJNKMGNE = LPEBBNDIJEK.CPIOFBAJBGI();
		if (array.Length > 0 && KBNPIGOEJEE != null && (!NOGCEBKPPJE.KMDACNACKII(GPDCOOCEGJH, KBNPIGOEJEE.LKCGPEEINAA) || !NOGCEBKPPJE.KMDACNACKII(FFJFJNKMGNE, KBNPIGOEJEE.OEFPAPDGGKJ)))
		{
			array = KINEBFNENMB.JBCONIFELBM;
		}
		LCAFLJDMMPB = LPEBBNDIJEK.BHNEJODLNJI();
		OLCIAJEPOLP oLCIAJEPOLP = new OLCIAJEPOLP(1);
		KINEBFNENMB.PPCDKILMGFD(oBDIBELBBEO, oLCIAJEPOLP);
		oLCIAJEPOLP.KBMOJGCCCEN(CGEBPLCBCCP.BABNEJKEAHH);
		KINEBFNENMB.GECPGLGLIBE(array, oLCIAJEPOLP);
		byte[] array2 = KINEBFNENMB.MHMMGPFEAJM(LCAFLJDMMPB, 65281);
		bool flag2 = null == array2;
		bool flag3 = !NOGCEBKPPJE.KMDACNACKII(GPDCOOCEGJH, 255);
		if (flag2 && flag3)
		{
			GPDCOOCEGJH = NOGCEBKPPJE.GBKNDKCPBEH(GPDCOOCEGJH, 255);
		}
		if (flag && !NOGCEBKPPJE.KMDACNACKII(GPDCOOCEGJH, 22016))
		{
			GPDCOOCEGJH = NOGCEBKPPJE.GBKNDKCPBEH(GPDCOOCEGJH, 22016);
		}
		KINEBFNENMB.KGADCPCFKIN(GPDCOOCEGJH, oLCIAJEPOLP);
		KINEBFNENMB.NKEAKKGFPGB(FFJFJNKMGNE, oLCIAJEPOLP);
		if (LCAFLJDMMPB != null)
		{
			HEMGBKNMOKB.OIOOGHNFDII(oLCIAJEPOLP, LCAFLJDMMPB);
		}
		oLCIAJEPOLP.PGOHFLKIFHM(this);
	}

	protected virtual void FDHKKKCBJHK()
	{
		OLCIAJEPOLP oLCIAJEPOLP = new OLCIAJEPOLP(16);
		MOCPBMMDBBD.BAILJOPLLNN(oLCIAJEPOLP);
		oLCIAJEPOLP.PGOHFLKIFHM(this);
	}
}
