using System.Collections;

public class OKKGCHDCHNP : GHJHPFDBKNA
{
	private readonly COCECKPDIKC LGAAPLFEPMG;

	private readonly string ADLMOHOLCGL;

	private readonly COEMJAGOFJJ JMNLHNOGILL;

	private readonly FBIJJFGLKMK GECCLOFELEC;

	public object IDLLMGBMDGB
	{
		get
		{
			return LGAAPLFEPMG;
		}
	}

	public static IEnumerable HEMABMGMAEB
	{
		get
		{
			return BJMIIIEBPNP.DCELAAHMIKB();
		}
	}

	public OKKGCHDCHNP(string ADLMOHOLCGL, COEMJAGOFJJ JMNLHNOGILL)
		: this(ADLMOHOLCGL, JMNLHNOGILL, null)
	{
	}

	public OKKGCHDCHNP(string ADLMOHOLCGL, COEMJAGOFJJ JMNLHNOGILL, FBIJJFGLKMK GECCLOFELEC)
	{
		KLKJHFKJLEM pGJDDDOKOJO = BJMIIIEBPNP.ANENONPLLFP(ADLMOHOLCGL);
		this.ADLMOHOLCGL = ADLMOHOLCGL;
		this.JMNLHNOGILL = JMNLHNOGILL;
		this.GECCLOFELEC = GECCLOFELEC;
		LGAAPLFEPMG = BJMIIIEBPNP.KCFCOMCMHOE(pGJDDDOKOJO, ADLMOHOLCGL);
	}

	public DPGEGPIMHCH GBNGIELMFLJ()
	{
		OHPHNNNHCOO oHPHNNNHCOO = FLMLLBCHPNI.OOLDLJODJGM(ADLMOHOLCGL);
		if (GECCLOFELEC != null)
		{
			oHPHNNNHCOO.DIOELAHNLKJ(true, new MDAKJDOFCEP(JMNLHNOGILL, GECCLOFELEC));
		}
		else
		{
			oHPHNNNHCOO.DIOELAHNLKJ(true, JMNLHNOGILL);
		}
		return new NNNFOJFLIPP(oHPHNNNHCOO);
	}
}
