public class OLMGBCMLIKI : JBMFHKBENEK, HGIAHEKANFO
{
	private readonly MKNDIEHOMOI IGCEJBIEACI;

	internal OLMGBCMLIKI(MKNDIEHOMOI BKOBLIALKKC)
	{
		IGCEJBIEACI = BKOBLIALKKC;
	}

	public HGIAHEKANFO DMHLIGLGJGI()
	{
		return IGCEJBIEACI.DMHLIGLGJGI();
	}

	public EDOEBJJFOBM IIHKEACDNID()
	{
		return new CDHAHIDPGBP(IGCEJBIEACI.IFPAJCFNKGJ(), false);
	}
}
