using System;

public abstract class OMOBJNLGOBO : JDPBBBGMMMP
{
	protected internal override bool NLPBPDPOOAK
	{
		get
		{
			return CEFLFJNJILP.OFGNPBCCHAA();
		}
	}

	protected OMOBJNLGOBO(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
	}

	protected OMOBJNLGOBO(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override bool MMFMOOHIGNJ()
	{
		KBINBLGGLNE kBINBLGGLNE = base.NBPANDNEJGI;
		KBINBLGGLNE kBINBLGGLNE2 = base.FIJLKLCHMGH;
		KBINBLGGLNE kBINBLGGLNE3 = ECFGFKNLLGH.JEHECJGFJEB;
		KBINBLGGLNE kBINBLGGLNE4 = ECFGFKNLLGH.FPKDKHJKEEF;
		KBINBLGGLNE kBINBLGGLNE5 = kBINBLGGLNE2.MIOEHGDPGAG();
		switch (FMBBJLCHHDI)
		{
		case 1:
		{
			KBINBLGGLNE kBINBLGGLNE8 = base.LAMGGDKLPJH[0];
			if (!kBINBLGGLNE8.EOJCHPEGABD)
			{
				KBINBLGGLNE bCIHLCMFAEK3 = kBINBLGGLNE8.MIOEHGDPGAG();
				KBINBLGGLNE bCIHLCMFAEK4 = kBINBLGGLNE8.IBJBIGNPNEM(bCIHLCMFAEK3);
				kBINBLGGLNE5 = kBINBLGGLNE5.IBJBIGNPNEM(kBINBLGGLNE8);
				kBINBLGGLNE3 = kBINBLGGLNE3.IBJBIGNPNEM(bCIHLCMFAEK3);
				kBINBLGGLNE4 = kBINBLGGLNE4.IBJBIGNPNEM(bCIHLCMFAEK4);
			}
			break;
		}
		case 2:
		case 3:
		case 4:
		{
			KBINBLGGLNE kBINBLGGLNE6 = base.LAMGGDKLPJH[0];
			if (!kBINBLGGLNE6.EOJCHPEGABD)
			{
				KBINBLGGLNE kBINBLGGLNE7 = kBINBLGGLNE6.MIOEHGDPGAG();
				KBINBLGGLNE bCIHLCMFAEK = kBINBLGGLNE7.MIOEHGDPGAG();
				KBINBLGGLNE bCIHLCMFAEK2 = kBINBLGGLNE7.IBJBIGNPNEM(bCIHLCMFAEK);
				kBINBLGGLNE3 = kBINBLGGLNE3.IBJBIGNPNEM(bCIHLCMFAEK);
				kBINBLGGLNE4 = kBINBLGGLNE4.IBJBIGNPNEM(bCIHLCMFAEK2);
			}
			break;
		}
		default:
			throw new InvalidOperationException("unsupported coordinate system");
		case 0:
			break;
		}
		KBINBLGGLNE cJHEIBNHNNE = kBINBLGGLNE.MIOEHGDPGAG().JEACJNAKLDJ(kBINBLGGLNE3).IBJBIGNPNEM(kBINBLGGLNE)
			.JEACJNAKLDJ(kBINBLGGLNE4);
		return kBINBLGGLNE5.KIFDKLPDKMD(cJHEIBNHNNE);
	}

	public override JGAFKLGGBGF FBGIHKPECCO(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		return JEACJNAKLDJ(BCIHLCMFAEK.BHKOFHMDACN());
	}
}
