using Spine;

public class OOBEMJJCEGO
{
	public bool LMDPKPHCMOD;

	public readonly ExposedList<OFMBOEDKGMI> DJBCCKODCLK = new ExposedList<OFMBOEDKGMI>();

	public bool GHPJDHGHJNO;

	public int KCDEGJNOLPL = -1;

	public readonly ExposedList<OAMNGFLKEFI> MLPNEHCDBOD = new ExposedList<OAMNGFLKEFI>();

	public void BOPEPLONIFL()
	{
		MLPNEHCDBOD.BOPEPLONIFL(false);
		KCDEGJNOLPL = -1;
		GHPJDHGHJNO = false;
		DJBCCKODCLK.BOPEPLONIFL(false);
	}

	public void PCHCAFHEJJM()
	{
		MLPNEHCDBOD.BOPEPLONIFL();
	}

	public void OLPLFILLDNC(ExposedList<OFMBOEDKGMI> NFGCPEEIEJN, int KMDMNBKBMCH, int HJLDJNLOPBB)
	{
		int num = 0;
		ExposedList<OFMBOEDKGMI> dJBCCKODCLK = DJBCCKODCLK;
		dJBCCKODCLK.BOPEPLONIFL(false);
		int num2 = HJLDJNLOPBB - KMDMNBKBMCH;
		dJBCCKODCLK.NKMKBLFBOFC(num2);
		OFMBOEDKGMI[] items = dJBCCKODCLK.Items;
		OFMBOEDKGMI[] items2 = NFGCPEEIEJN.Items;
		for (int i = 0; i < num2; i++)
		{
			OFMBOEDKGMI oFMBOEDKGMI = items2[KMDMNBKBMCH + i];
			items[i] = oFMBOEDKGMI;
			GHPJDHGHJNO = oFMBOEDKGMI.JIBMAOPFGEO;
			items[i].NCCOCLMPNIK = num;
			num += oFMBOEDKGMI.KCDEGJNOLPL;
		}
		KCDEGJNOLPL = num;
		int iNMKEHEAHNO = items2[KMDMNBKBMCH].INMKEHEAHNO;
		int bGKHIDKDGAC = items2[HJLDJNLOPBB - 1].BGKHIDKDGAC;
		MLPNEHCDBOD.BOPEPLONIFL(false);
		int num3 = bGKHIDKDGAC - iNMKEHEAHNO;
		MLPNEHCDBOD.NKMKBLFBOFC(num3);
		OAMNGFLKEFI[] items3 = MLPNEHCDBOD.Items;
		LBBAMMPJKDA[] items4 = items2[0].GDNININLMFD.COACJAFIPEI.Items;
		for (int j = 0; j < num3; j++)
		{
			items3[j] = items4[iNMKEHEAHNO + j].DFHHMKMLCFF;
		}
	}

	public void EPKMIBEOIJJ(OOBEMJJCEGO CJHEIBNHNNE)
	{
		LMDPKPHCMOD = CJHEIBNHNNE.LMDPKPHCMOD;
		GHPJDHGHJNO = CJHEIBNHNNE.GHPJDHGHJNO;
		KCDEGJNOLPL = CJHEIBNHNNE.KCDEGJNOLPL;
		MLPNEHCDBOD.BOPEPLONIFL(false);
		MLPNEHCDBOD.JGGCKJABGHP(CJHEIBNHNNE.MLPNEHCDBOD.Capacity);
		MLPNEHCDBOD.Count = CJHEIBNHNNE.MLPNEHCDBOD.Count;
		CJHEIBNHNNE.MLPNEHCDBOD.BACJEDDPKIJ(MLPNEHCDBOD.Items);
		DJBCCKODCLK.BOPEPLONIFL(false);
		DJBCCKODCLK.JGGCKJABGHP(CJHEIBNHNNE.DJBCCKODCLK.Capacity);
		DJBCCKODCLK.Count = CJHEIBNHNNE.DJBCCKODCLK.Count;
		CJHEIBNHNNE.DJBCCKODCLK.BACJEDDPKIJ(DJBCCKODCLK.Items);
	}

	public static bool EMENOEPELNK(OOBEMJJCEGO MNIMEAMHNMI, OOBEMJJCEGO BCIHLCMFAEK)
	{
		if (MNIMEAMHNMI.GHPJDHGHJNO || BCIHLCMFAEK.GHPJDHGHJNO)
		{
			return true;
		}
		if (MNIMEAMHNMI.KCDEGJNOLPL != BCIHLCMFAEK.KCDEGJNOLPL)
		{
			return true;
		}
		if (MNIMEAMHNMI.LMDPKPHCMOD != BCIHLCMFAEK.LMDPKPHCMOD)
		{
			return true;
		}
		int count = BCIHLCMFAEK.MLPNEHCDBOD.Count;
		if (MNIMEAMHNMI.MLPNEHCDBOD.Count != count)
		{
			return true;
		}
		int count2 = MNIMEAMHNMI.DJBCCKODCLK.Count;
		int count3 = BCIHLCMFAEK.DJBCCKODCLK.Count;
		if (count2 != count3)
		{
			return true;
		}
		OFMBOEDKGMI[] items = MNIMEAMHNMI.DJBCCKODCLK.Items;
		OFMBOEDKGMI[] items2 = BCIHLCMFAEK.DJBCCKODCLK.Items;
		OAMNGFLKEFI[] items3 = MNIMEAMHNMI.MLPNEHCDBOD.Items;
		OAMNGFLKEFI[] items4 = BCIHLCMFAEK.MLPNEHCDBOD.Items;
		for (int i = 0; i < count; i++)
		{
			if (!object.ReferenceEquals(items3[i], items4[i]))
			{
				return true;
			}
		}
		for (int j = 0; j < count3; j++)
		{
			OFMBOEDKGMI oFMBOEDKGMI = items[j];
			OFMBOEDKGMI oFMBOEDKGMI2 = items2[j];
			if (oFMBOEDKGMI.KCDEGJNOLPL != oFMBOEDKGMI2.KCDEGJNOLPL || oFMBOEDKGMI.INMKEHEAHNO != oFMBOEDKGMI2.INMKEHEAHNO || oFMBOEDKGMI.BGKHIDKDGAC != oFMBOEDKGMI2.BGKHIDKDGAC || oFMBOEDKGMI.GHOLJENMENP != oFMBOEDKGMI2.GHOLJENMENP || oFMBOEDKGMI.NCCOCLMPNIK != oFMBOEDKGMI2.NCCOCLMPNIK)
			{
				return true;
			}
		}
		return false;
	}
}
