public static class OOBMFBFBAGN
{
	public static LEDBLDKJBAI OFBMGJCGHFE(this NOALGNJECAD PLCFEOMGCFK)
	{
		switch (PLCFEOMGCFK)
		{
		case NOALGNJECAD.SolidColor1:
			return LEDBLDKJBAI.Yellow;
		case NOALGNJECAD.SolidColor2:
			return LEDBLDKJBAI.Red;
		case NOALGNJECAD.SolidColor3:
			return LEDBLDKJBAI.Blue;
		case NOALGNJECAD.SolidColor4:
			return LEDBLDKJBAI.Green;
		case NOALGNJECAD.SolidColor5:
			return LEDBLDKJBAI.Purple;
		case NOALGNJECAD.SolidColor6:
			return LEDBLDKJBAI.Orange;
		default:
			return LEDBLDKJBAI.None;
		}
	}

	public static NOALGNJECAD AMLEHGPGGIC(this ALIFCLNJKPH BDKFNEDHAOJ)
	{
		switch (BDKFNEDHAOJ)
		{
		case ALIFCLNJKPH.SolidColor1:
			return NOALGNJECAD.SolidColor1;
		case ALIFCLNJKPH.SolidColor2:
			return NOALGNJECAD.SolidColor2;
		case ALIFCLNJKPH.SolidColor3:
			return NOALGNJECAD.SolidColor3;
		case ALIFCLNJKPH.SolidColor4:
			return NOALGNJECAD.SolidColor4;
		case ALIFCLNJKPH.SolidColor5:
			return NOALGNJECAD.SolidColor5;
		case ALIFCLNJKPH.SolidColor6:
			return NOALGNJECAD.SolidColor6;
		case ALIFCLNJKPH.ColoredBallon1:
		case ALIFCLNJKPH.ColoredBallon2:
		case ALIFCLNJKPH.ColoredBallon3:
		case ALIFCLNJKPH.ColoredBallon4:
		case ALIFCLNJKPH.ColoredBallon5:
		case ALIFCLNJKPH.ColoredBallon6:
			return NOALGNJECAD.ColoredBalloon;
		case ALIFCLNJKPH.Duck1:
		case ALIFCLNJKPH.Duck2:
		case ALIFCLNJKPH.Duck3:
		case ALIFCLNJKPH.Duck4:
		case ALIFCLNJKPH.Duck5:
			return NOALGNJECAD.Duck;
		case ALIFCLNJKPH.GiantDuck:
			return NOALGNJECAD.GiantDuck;
		case ALIFCLNJKPH.GiantPinata:
			return NOALGNJECAD.GiantPinata;
		case ALIFCLNJKPH.CanToss:
			return NOALGNJECAD.CanToss;
		case ALIFCLNJKPH.Soda4:
		case ALIFCLNJKPH.Soda5:
			return NOALGNJECAD.Soda;
		case ALIFCLNJKPH.MagicHat:
			return NOALGNJECAD.MagicHat;
		case ALIFCLNJKPH.Crate:
		case ALIFCLNJKPH.CrateLayer1:
		case ALIFCLNJKPH.CrateLayer2:
			return NOALGNJECAD.Crate;
		case ALIFCLNJKPH.ColorCrateYellow0:
		case ALIFCLNJKPH.ColorCrateYellow1:
		case ALIFCLNJKPH.ColorCrateYellow2:
		case ALIFCLNJKPH.ColorCrateRed0:
		case ALIFCLNJKPH.ColorCrateRed1:
		case ALIFCLNJKPH.ColorCrateRed2:
		case ALIFCLNJKPH.ColorCrateBlue0:
		case ALIFCLNJKPH.ColorCrateBlue1:
		case ALIFCLNJKPH.ColorCrateBlue2:
		case ALIFCLNJKPH.ColorCrateGreen0:
		case ALIFCLNJKPH.ColorCrateGreen1:
		case ALIFCLNJKPH.ColorCrateGreen2:
		case ALIFCLNJKPH.ColorCratePurple0:
		case ALIFCLNJKPH.ColorCratePurple1:
		case ALIFCLNJKPH.ColorCratePurple2:
		case ALIFCLNJKPH.ColorCrateOrange0:
		case ALIFCLNJKPH.ColorCrateOrange1:
		case ALIFCLNJKPH.ColorCrateOrange2:
			return NOALGNJECAD.ColoredCrate;
		case ALIFCLNJKPH.Balloon:
			return NOALGNJECAD.Balloon;
		case ALIFCLNJKPH.WaterMelon:
			return NOALGNJECAD.WaterMelon;
		case ALIFCLNJKPH.EasterEgg:
			return NOALGNJECAD.EasterEgg;
		case ALIFCLNJKPH.Pinata:
			return NOALGNJECAD.Pinata;
		case ALIFCLNJKPH.Jelly:
			return NOALGNJECAD.Jelly;
		case ALIFCLNJKPH.LightBulb:
			return NOALGNJECAD.LightBulb;
		case ALIFCLNJKPH.DiscoBallColor1:
		case ALIFCLNJKPH.DiscoBallColor2:
		case ALIFCLNJKPH.DiscoBallColor3:
		case ALIFCLNJKPH.DiscoBallColor4:
		case ALIFCLNJKPH.DiscoBallColor5:
		case ALIFCLNJKPH.DiscoBallColor6:
			return NOALGNJECAD.DiscoBall;
		case ALIFCLNJKPH.RocketHorizantal:
		case ALIFCLNJKPH.RocketVertical:
			return NOALGNJECAD.Rocket;
		case ALIFCLNJKPH.Bomb:
			return NOALGNJECAD.Bomb;
		case ALIFCLNJKPH.None:
		case ALIFCLNJKPH.Empty:
			return NOALGNJECAD.None;
		case ALIFCLNJKPH.Frame:
			return NOALGNJECAD.Cage;
		case ALIFCLNJKPH.Oyster:
			return NOALGNJECAD.Oyster;
		case ALIFCLNJKPH.MetalCrate:
			return NOALGNJECAD.MetalCrate;
		case ALIFCLNJKPH.Fish1:
		case ALIFCLNJKPH.Fish2:
			return NOALGNJECAD.Fish;
		case ALIFCLNJKPH.BalloonGenerator1:
		case ALIFCLNJKPH.BalloonGenerator2:
			return NOALGNJECAD.BalloonGenerator;
		case ALIFCLNJKPH.Honey:
			return NOALGNJECAD.Honey;
		case ALIFCLNJKPH.DiamondOpen:
		case ALIFCLNJKPH.DiamondClose:
			return NOALGNJECAD.Diamond;
		case ALIFCLNJKPH.Billboard:
			return NOALGNJECAD.Billboard;
		case ALIFCLNJKPH.Stone:
			return NOALGNJECAD.Stone;
		case ALIFCLNJKPH.ColoredSodaYellow:
		case ALIFCLNJKPH.ColoredSodaRed:
		case ALIFCLNJKPH.ColoredSodaBlue:
		case ALIFCLNJKPH.ColoredSodaGreen:
		case ALIFCLNJKPH.ColoredSodaPurple:
			return NOALGNJECAD.ColoredSoda;
		case ALIFCLNJKPH.BlasterYellowRight:
		case ALIFCLNJKPH.BlasterRedRight:
		case ALIFCLNJKPH.BlasterYellowUp:
		case ALIFCLNJKPH.BlasterYellowDown:
		case ALIFCLNJKPH.BlasterYellowLeft:
		case ALIFCLNJKPH.BlasterRedUp:
		case ALIFCLNJKPH.BlasterRedDown:
		case ALIFCLNJKPH.BlasterRedLeft:
		case ALIFCLNJKPH.BlasterBlueRight:
		case ALIFCLNJKPH.BlasterGreenRight:
		case ALIFCLNJKPH.BlasterPurpleRight:
		case ALIFCLNJKPH.BlasterBlueUp:
		case ALIFCLNJKPH.BlasterBlueDown:
		case ALIFCLNJKPH.BlasterBlueLeft:
		case ALIFCLNJKPH.BlasterGreenUp:
		case ALIFCLNJKPH.BlasterGreenDown:
		case ALIFCLNJKPH.BlasterGreenLeft:
		case ALIFCLNJKPH.BlasterPurpleUp:
		case ALIFCLNJKPH.BlasterPurpleDown:
		case ALIFCLNJKPH.BlasterPurpleLeft:
		case ALIFCLNJKPH.BlasterOrangeRight:
		case ALIFCLNJKPH.BlasterOrangeUp:
		case ALIFCLNJKPH.BlasterOrangeDown:
		case ALIFCLNJKPH.BlasterOrangeLeft:
			return NOALGNJECAD.Blaster;
		case ALIFCLNJKPH.Soap:
			return NOALGNJECAD.Soap;
		case ALIFCLNJKPH.MoleItem:
			return NOALGNJECAD.Mole;
		case ALIFCLNJKPH.PenguinItem:
			return NOALGNJECAD.Penguin;
		case ALIFCLNJKPH.BirdHouse:
			return NOALGNJECAD.BirdHouse;
		case ALIFCLNJKPH.PotionYellow:
		case ALIFCLNJKPH.PotionRed:
		case ALIFCLNJKPH.PotionBlue:
		case ALIFCLNJKPH.PotionGreen:
		case ALIFCLNJKPH.PotionPurple:
		case ALIFCLNJKPH.PotionOrange:
			return NOALGNJECAD.Potion;
		case ALIFCLNJKPH.BarrelItem:
			return NOALGNJECAD.Barrel;
		case ALIFCLNJKPH.UfoItem:
			return NOALGNJECAD.Ufo;
		case ALIFCLNJKPH.HanoiItem:
			return NOALGNJECAD.Hanoi;
		case ALIFCLNJKPH.GiftItem:
			return NOALGNJECAD.Gift;
		case ALIFCLNJKPH.CoconutItem:
			return NOALGNJECAD.Coconut;
		case ALIFCLNJKPH.CrateLayer3:
			return NOALGNJECAD.Ivy;
		case ALIFCLNJKPH.FireworksItem:
			return NOALGNJECAD.Fireworks;
		case ALIFCLNJKPH.VaseYellow:
		case ALIFCLNJKPH.VaseRed:
		case ALIFCLNJKPH.VaseBlue:
		case ALIFCLNJKPH.VaseGreen:
		case ALIFCLNJKPH.VasePurple:
		case ALIFCLNJKPH.VaseOrange:
			return NOALGNJECAD.Vase;
		case ALIFCLNJKPH.ChainItem:
			return NOALGNJECAD.Chain;
		case ALIFCLNJKPH.WasherItem:
			return NOALGNJECAD.Washer;
		case ALIFCLNJKPH.TubeYellow:
		case ALIFCLNJKPH.TubeRed:
		case ALIFCLNJKPH.TubeBlue:
		case ALIFCLNJKPH.TubeGreen:
		case ALIFCLNJKPH.TubePurple:
			return NOALGNJECAD.Tube;
		case ALIFCLNJKPH.Log:
			return NOALGNJECAD.Log;
		case ALIFCLNJKPH.LogRight:
		case ALIFCLNJKPH.LogLeft:
		case ALIFCLNJKPH.LogDown:
		case ALIFCLNJKPH.LogUp:
			return NOALGNJECAD.LogFake;
		case ALIFCLNJKPH.Pot:
			return NOALGNJECAD.Pot;
		case ALIFCLNJKPH.WallYellow:
		case ALIFCLNJKPH.WallRed:
		case ALIFCLNJKPH.WallBlue:
		case ALIFCLNJKPH.WallGreen:
		case ALIFCLNJKPH.WallPurple:
		case ALIFCLNJKPH.WallOrange:
			return NOALGNJECAD.Wall;
		case ALIFCLNJKPH.Safe:
			return NOALGNJECAD.Safe;
		case ALIFCLNJKPH.Tomb:
			return NOALGNJECAD.Tomb;
		default:
			GBFAPADEBEC.LCNJJMBLOHE(PBIIDJOKNEK.TiledToItemType, "Don't know how to convert: " + BDKFNEDHAOJ);
			return NOALGNJECAD.None;
		}
	}
}
