using System;
using System.Collections.Generic;

public sealed class OOFCOABLNKA : NJDFMFJGDDJ
{
	private readonly Uri BBNDBGDBCDI;

	private readonly NHLBHJOEAMB MILMGDHGDHG;

	private readonly GFDALMJEJKF PNDPJNCMJEL;

	public OOFCOABLNKA(Uri FCPBJKBJNOJ, NHLBHJOEAMB MILMGDHGDHG, GFDALMJEJKF FIMGCDAHGGH, List<string> PDNCIAJCJBB)
	{
		BBNDBGDBCDI = FCPBJKBJNOJ;
		this.MILMGDHGDHG = MILMGDHGDHG;
		PNDPJNCMJEL = FIMGCDAHGGH;
		base.KCGKBOHNIPE = PDNCIAJCJBB;
	}

	public override HFLDELFJCEE DNHBFEBDMPF()
	{
		return new HEOPEFDAHFI(BBNDBGDBCDI, MILMGDHGDHG, PNDPJNCMJEL);
	}
}
