using Org.BouncyCastle.Math;

internal class OPHAAHGOFJL : HAEJCOAFOIJ
{
	public static readonly BigInteger OKDPJHOEPBJ = new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFF"));

	private const int MCCBMEABHPH = 2;

	protected readonly EBPDFEFDDIN IAALHPOGFAN;

	public virtual BigInteger FNPELDEHJKL
	{
		get
		{
			return OKDPJHOEPBJ;
		}
	}

	public override JGAFKLGGBGF EFOLNCNGADB
	{
		get
		{
			return IAALHPOGFAN;
		}
	}

	public override int PJNLBAHOKGC
	{
		get
		{
			return OKDPJHOEPBJ.BitLength;
		}
	}

	public OPHAAHGOFJL()
		: base(OKDPJHOEPBJ)
	{
		IAALHPOGFAN = new EBPDFEFDDIN(this, null, null);
		CFJANGMBPML = HFENNGHNFLF(new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFC")));
		MPDGCILOEML = HFENNGHNFLF(new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("64210519E59C80E70FA7E9AB72243049FEB8DEECC146B9B1")));
		NNGLKCDBIBE = new BigInteger(1, DCDJMDOEKHC.ILOALOLANOL("FFFFFFFFFFFFFFFFFFFFFFFF99DEF836146BC9B1B4D22831"));
		LDKJJAOPAAP = BigInteger.One;
		NHKGIJJFPEK = 2;
	}

	protected override BHPIABAGAPB LNLMICLEEPK()
	{
		return new OPHAAHGOFJL();
	}

	public override bool ELIMDCKLHCJ(int FOOJPIGHMKH)
	{
		if (FOOJPIGHMKH == 2)
		{
			return true;
		}
		return false;
	}

	public override KBINBLGGLNE HFENNGHNFLF(BigInteger AMFCENFNAJJ)
	{
		return new OHEGFFKFNFP(AMFCENFNAJJ);
	}

	protected internal override JGAFKLGGBGF IMOPAOHAOAN(KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
	{
		return new EBPDFEFDDIN(this, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG);
	}

	protected internal override JGAFKLGGBGF IMOPAOHAOAN(KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
	{
		return new EBPDFEFDDIN(this, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG);
	}
}
