public class PEJMGGHJHCI
{
	public static int AAIEJDNAODP(string MOKLDCMGFFB, string DBONNDOKLCF)
	{
		return AIEKHPFNBHG.AAIEJDNAODP(MOKLDCMGFFB, DBONNDOKLCF);
	}

	public static int ELNCCDELMMH(string MOKLDCMGFFB, string DBONNDOKLCF)
	{
		return AIEKHPFNBHG.ELNCCDELMMH(MOKLDCMGFFB, DBONNDOKLCF);
	}

	public static int PLCFEOMGCFK(string MOKLDCMGFFB, string DBONNDOKLCF)
	{
		return AIEKHPFNBHG.PLCFEOMGCFK(MOKLDCMGFFB, DBONNDOKLCF);
	}

	public static int PHFLBLJJMLI(string MOKLDCMGFFB, string DBONNDOKLCF)
	{
		return AIEKHPFNBHG.PHFLBLJJMLI(MOKLDCMGFFB, DBONNDOKLCF);
	}

	public static int EKFOKNPODBK(string MOKLDCMGFFB, string DBONNDOKLCF)
	{
		return AIEKHPFNBHG.EKFOKNPODBK(MOKLDCMGFFB, DBONNDOKLCF);
	}
}
