using System;

public class PGNLPNFKAPJ : PHFBFDEAHMD
{
	private const byte HDBEHGHJLCE = 54;

	private const byte NBKPLNHFBOH = 92;

	private readonly BJLAMONNNDD HABFKBCEIBN;

	private readonly int KDNAHCEJEHD;

	private readonly int AMOPJBEKODF;

	private MIPBJNJHNGA MDGKIGLIAEO;

	private MIPBJNJHNGA ENHEKECFNHP;

	private readonly byte[] HGPKBNLJOJN;

	private readonly byte[] AFFGBHMAGNN;

	public virtual string KFKMEPMEBND
	{
		get
		{
			return HABFKBCEIBN.KFKMEPMEBND + "/HMAC";
		}
	}

	public PGNLPNFKAPJ(BJLAMONNNDD HABFKBCEIBN)
	{
		this.HABFKBCEIBN = HABFKBCEIBN;
		KDNAHCEJEHD = HABFKBCEIBN.EEMLLAMENHO();
		AMOPJBEKODF = HABFKBCEIBN.MNAIJEEKPCP();
		HGPKBNLJOJN = new byte[AMOPJBEKODF];
		AFFGBHMAGNN = new byte[AMOPJBEKODF + KDNAHCEJEHD];
	}

	public virtual BJLAMONNNDD NMJFLONEKNM()
	{
		return HABFKBCEIBN;
	}

	public virtual void DIOELAHNLKJ(IGMAJHKIIPK IJJHBEECMBP)
	{
		HABFKBCEIBN.OMOKOKFNBKI();
		byte[] array = ((JEMNCGMEABF)IJJHBEECMBP).MEGBFHFMBFI();
		int num = array.Length;
		if (num > AMOPJBEKODF)
		{
			HABFKBCEIBN.GONEEEFEDGF(array, 0, num);
			HABFKBCEIBN.LCNOFBMOHHM(HGPKBNLJOJN, 0);
			num = KDNAHCEJEHD;
		}
		else
		{
			Array.Copy(array, 0, HGPKBNLJOJN, 0, num);
		}
		Array.Clear(HGPKBNLJOJN, num, AMOPJBEKODF - num);
		Array.Copy(HGPKBNLJOJN, 0, AFFGBHMAGNN, 0, AMOPJBEKODF);
		JGIMPGPBOLC(HGPKBNLJOJN, AMOPJBEKODF, 54);
		JGIMPGPBOLC(AFFGBHMAGNN, AMOPJBEKODF, 92);
		if (HABFKBCEIBN is MIPBJNJHNGA)
		{
			ENHEKECFNHP = ((MIPBJNJHNGA)HABFKBCEIBN).FDCFKGAEJFF();
			((BJLAMONNNDD)ENHEKECFNHP).GONEEEFEDGF(AFFGBHMAGNN, 0, AMOPJBEKODF);
		}
		HABFKBCEIBN.GONEEEFEDGF(HGPKBNLJOJN, 0, HGPKBNLJOJN.Length);
		if (HABFKBCEIBN is MIPBJNJHNGA)
		{
			MDGKIGLIAEO = ((MIPBJNJHNGA)HABFKBCEIBN).FDCFKGAEJFF();
		}
	}

	public virtual int BKGLOJPPBIG()
	{
		return KDNAHCEJEHD;
	}

	public virtual void BPAJGOINFNL(byte MOPCLEEGDFB)
	{
		HABFKBCEIBN.BPAJGOINFNL(MOPCLEEGDFB);
	}

	public virtual void GONEEEFEDGF(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int NBEDPKHALCN)
	{
		HABFKBCEIBN.GONEEEFEDGF(MOPCLEEGDFB, ELICNEDIBGB, NBEDPKHALCN);
	}

	public virtual int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC)
	{
		HABFKBCEIBN.LCNOFBMOHHM(AFFGBHMAGNN, AMOPJBEKODF);
		if (ENHEKECFNHP != null)
		{
			((MIPBJNJHNGA)HABFKBCEIBN).OMOKOKFNBKI(ENHEKECFNHP);
			HABFKBCEIBN.GONEEEFEDGF(AFFGBHMAGNN, AMOPJBEKODF, HABFKBCEIBN.EEMLLAMENHO());
		}
		else
		{
			HABFKBCEIBN.GONEEEFEDGF(AFFGBHMAGNN, 0, AFFGBHMAGNN.Length);
		}
		int result = HABFKBCEIBN.LCNOFBMOHHM(BILGCJNPJGJ, EMAKNGBIFDC);
		Array.Clear(AFFGBHMAGNN, AMOPJBEKODF, KDNAHCEJEHD);
		if (MDGKIGLIAEO != null)
		{
			((MIPBJNJHNGA)HABFKBCEIBN).OMOKOKFNBKI(MDGKIGLIAEO);
		}
		else
		{
			HABFKBCEIBN.GONEEEFEDGF(HGPKBNLJOJN, 0, HGPKBNLJOJN.Length);
		}
		return result;
	}

	public virtual void OMOKOKFNBKI()
	{
		HABFKBCEIBN.OMOKOKFNBKI();
		HABFKBCEIBN.GONEEEFEDGF(HGPKBNLJOJN, 0, HGPKBNLJOJN.Length);
	}

	private static void JGIMPGPBOLC(byte[] MJNBAIFMLKJ, int NBEDPKHALCN, byte IDHLPOFDLKJ)
	{
		for (int i = 0; i < NBEDPKHALCN; i++)
		{
			MJNBAIFMLKJ[i] ^= IDHLPOFDLKJ;
		}
	}
}
