public interface PHFBFDEAHMD
{
	string KFKMEPMEBND { get; }

	void DIOELAHNLKJ(IGMAJHKIIPK IJJHBEECMBP);

	int BKGLOJPPBIG();

	void BPAJGOINFNL(byte MOPCLEEGDFB);

	void GONEEEFEDGF(byte[] MOPCLEEGDFB, int ELICNEDIBGB, int NBEDPKHALCN);

	int LCNOFBMOHHM(byte[] BILGCJNPJGJ, int EMAKNGBIFDC);

	void OMOKOKFNBKI();
}
