using System;
using Org.BouncyCastle.Math;

public class PHKAEJGHJOF : LNKPCJLANAO
{
	private readonly int FICGFLDDPBO;

	private readonly GLFDIPNOLKN HPHBDNBJPHB;

	private readonly GLFDIPNOLKN OKDPJHOEPBJ;

	private readonly GLFDIPNOLKN MNIMEAMHNMI;

	public int DFIFNOEOFLE
	{
		get
		{
			return FICGFLDDPBO;
		}
	}

	public BigInteger MBIJHANOCOC
	{
		get
		{
			return HPHBDNBJPHB.DMPHAJNKNKB;
		}
	}

	public BigInteger FNPELDEHJKL
	{
		get
		{
			return OKDPJHOEPBJ.DMPHAJNKNKB;
		}
	}

	public BigInteger JEHECJGFJEB
	{
		get
		{
			return MNIMEAMHNMI.DMPHAJNKNKB;
		}
	}

	public PHKAEJGHJOF(int FICGFLDDPBO, BigInteger HPHBDNBJPHB, BigInteger OKDPJHOEPBJ, BigInteger MNIMEAMHNMI)
	{
		this.FICGFLDDPBO = FICGFLDDPBO;
		this.HPHBDNBJPHB = new GLFDIPNOLKN(HPHBDNBJPHB);
		this.OKDPJHOEPBJ = new GLFDIPNOLKN(OKDPJHOEPBJ);
		this.MNIMEAMHNMI = new GLFDIPNOLKN(MNIMEAMHNMI);
	}

	private PHKAEJGHJOF(ALLINHNNNJN MIABODPHOIP)
	{
		if (MIABODPHOIP.GMCGMPEEHJP != 4)
		{
			throw new ArgumentException("Wrong number of elements in sequence", "seq");
		}
		FICGFLDDPBO = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(0)).JBGOANMLBFA.IntValue;
		HPHBDNBJPHB = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(1));
		OKDPJHOEPBJ = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(2));
		MNIMEAMHNMI = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(3));
	}

	public static PHKAEJGHJOF BJLJCGFMFOO(PAANMJLACEF NEMEKIOEOLC, bool DHGLJHFEJFL)
	{
		return BJLJCGFMFOO(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC, DHGLJHFEJFL));
	}

	public static PHKAEJGHJOF BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC == null || NEMEKIOEOLC is PHKAEJGHJOF)
		{
			return (PHKAEJGHJOF)NEMEKIOEOLC;
		}
		if (NEMEKIOEOLC is ALLINHNNNJN)
		{
			return new PHKAEJGHJOF((ALLINHNNNJN)NEMEKIOEOLC);
		}
		throw new ArgumentException("Invalid GOST3410Parameter: " + LHFGHNFJIKM.JKHOEKAOLPM(NEMEKIOEOLC));
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		return new KOGPLMALOEH(new GLFDIPNOLKN(FICGFLDDPBO), HPHBDNBJPHB, OKDPJHOEPBJ, MNIMEAMHNMI);
	}
}
