using System;

internal class PHLJACKOHJK : OMOBJNLGOBO
{
	public PHLJACKOHJK(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ)
		: this(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, false)
	{
	}

	public PHLJACKOHJK(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, HPGABKNMEAG)
	{
		if (AMFCENFNAJJ == null != (CNLILOEEBOJ == null))
		{
			throw new ArgumentException("Exactly one of the field elements is null");
		}
	}

	internal PHLJACKOHJK(BHPIABAGAPB NINILENHPHE, KBINBLGGLNE AMFCENFNAJJ, KBINBLGGLNE CNLILOEEBOJ, KBINBLGGLNE[] IJGNIJAMCML, bool HPGABKNMEAG)
		: base(NINILENHPHE, AMFCENFNAJJ, CNLILOEEBOJ, IJGNIJAMCML, HPGABKNMEAG)
	{
	}

	protected override JGAFKLGGBGF NCFIMIMOGDF()
	{
		return new PHLJACKOHJK(null, HBEBMBOOIMD, CEFLFJNJILP);
	}

	public override JGAFKLGGBGF JEACJNAKLDJ(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return this;
		}
		if (this == BCIHLCMFAEK)
		{
			return LLGLJBDLBOP();
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		GHEOOMLCOCI gHEOOMLCOCI = (GHEOOMLCOCI)base.NBPANDNEJGI;
		GHEOOMLCOCI gHEOOMLCOCI2 = (GHEOOMLCOCI)base.FIJLKLCHMGH;
		GHEOOMLCOCI gHEOOMLCOCI3 = (GHEOOMLCOCI)BCIHLCMFAEK.NBPANDNEJGI;
		GHEOOMLCOCI gHEOOMLCOCI4 = (GHEOOMLCOCI)BCIHLCMFAEK.FIJLKLCHMGH;
		GHEOOMLCOCI gHEOOMLCOCI5 = (GHEOOMLCOCI)base.LAMGGDKLPJH[0];
		GHEOOMLCOCI gHEOOMLCOCI6 = (GHEOOMLCOCI)BCIHLCMFAEK.LAMGGDKLPJH[0];
		uint[] array = MADOAPNPCCB.DCPJKFEDHOJ();
		uint[] array2 = MADOAPNPCCB.PLIFFMMBNPM();
		uint[] array3 = MADOAPNPCCB.PLIFFMMBNPM();
		uint[] array4 = MADOAPNPCCB.PLIFFMMBNPM();
		bool flag = gHEOOMLCOCI5.EOJCHPEGABD;
		uint[] array5;
		uint[] array6;
		if (flag)
		{
			array5 = gHEOOMLCOCI3.AMFCENFNAJJ;
			array6 = gHEOOMLCOCI4.AMFCENFNAJJ;
		}
		else
		{
			array6 = array3;
			DILDIHBGDAG.MIOEHGDPGAG(gHEOOMLCOCI5.AMFCENFNAJJ, array6);
			array5 = array2;
			DILDIHBGDAG.IBJBIGNPNEM(array6, gHEOOMLCOCI3.AMFCENFNAJJ, array5);
			DILDIHBGDAG.IBJBIGNPNEM(array6, gHEOOMLCOCI5.AMFCENFNAJJ, array6);
			DILDIHBGDAG.IBJBIGNPNEM(array6, gHEOOMLCOCI4.AMFCENFNAJJ, array6);
		}
		bool flag2 = gHEOOMLCOCI6.EOJCHPEGABD;
		uint[] array7;
		uint[] array8;
		if (flag2)
		{
			array7 = gHEOOMLCOCI.AMFCENFNAJJ;
			array8 = gHEOOMLCOCI2.AMFCENFNAJJ;
		}
		else
		{
			array8 = array4;
			DILDIHBGDAG.MIOEHGDPGAG(gHEOOMLCOCI6.AMFCENFNAJJ, array8);
			array7 = array;
			DILDIHBGDAG.IBJBIGNPNEM(array8, gHEOOMLCOCI.AMFCENFNAJJ, array7);
			DILDIHBGDAG.IBJBIGNPNEM(array8, gHEOOMLCOCI6.AMFCENFNAJJ, array8);
			DILDIHBGDAG.IBJBIGNPNEM(array8, gHEOOMLCOCI2.AMFCENFNAJJ, array8);
		}
		uint[] array9 = MADOAPNPCCB.PLIFFMMBNPM();
		DILDIHBGDAG.FBGIHKPECCO(array7, array5, array9);
		uint[] array10 = array2;
		DILDIHBGDAG.FBGIHKPECCO(array8, array6, array10);
		if (MADOAPNPCCB.EJJHHCOFAAI(array9))
		{
			if (MADOAPNPCCB.EJJHHCOFAAI(array10))
			{
				return LLGLJBDLBOP();
			}
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		uint[] array11 = array3;
		DILDIHBGDAG.MIOEHGDPGAG(array9, array11);
		uint[] array12 = MADOAPNPCCB.PLIFFMMBNPM();
		DILDIHBGDAG.IBJBIGNPNEM(array11, array9, array12);
		uint[] array13 = array3;
		DILDIHBGDAG.IBJBIGNPNEM(array11, array7, array13);
		DILDIHBGDAG.BHKOFHMDACN(array12, array12);
		MADOAPNPCCB.BMEIFJDODCF(array8, array12, array);
		uint aMFCENFNAJJ = MADOAPNPCCB.FIBDFFPCDGC(array13, array13, array12);
		DILDIHBGDAG.KKIGIOINLCI(aMFCENFNAJJ, array12);
		GHEOOMLCOCI gHEOOMLCOCI7 = new GHEOOMLCOCI(array4);
		DILDIHBGDAG.MIOEHGDPGAG(array10, gHEOOMLCOCI7.AMFCENFNAJJ);
		DILDIHBGDAG.FBGIHKPECCO(gHEOOMLCOCI7.AMFCENFNAJJ, array12, gHEOOMLCOCI7.AMFCENFNAJJ);
		GHEOOMLCOCI gHEOOMLCOCI8 = new GHEOOMLCOCI(array12);
		DILDIHBGDAG.FBGIHKPECCO(array13, gHEOOMLCOCI7.AMFCENFNAJJ, gHEOOMLCOCI8.AMFCENFNAJJ);
		DILDIHBGDAG.OMJFFHEIEFH(gHEOOMLCOCI8.AMFCENFNAJJ, array10, array);
		DILDIHBGDAG.BKCHMGKFECM(array, gHEOOMLCOCI8.AMFCENFNAJJ);
		GHEOOMLCOCI gHEOOMLCOCI9 = new GHEOOMLCOCI(array9);
		if (!flag)
		{
			DILDIHBGDAG.IBJBIGNPNEM(gHEOOMLCOCI9.AMFCENFNAJJ, gHEOOMLCOCI5.AMFCENFNAJJ, gHEOOMLCOCI9.AMFCENFNAJJ);
		}
		if (!flag2)
		{
			DILDIHBGDAG.IBJBIGNPNEM(gHEOOMLCOCI9.AMFCENFNAJJ, gHEOOMLCOCI6.AMFCENFNAJJ, gHEOOMLCOCI9.AMFCENFNAJJ);
		}
		KBINBLGGLNE[] iJGNIJAMCML = new KBINBLGGLNE[1] { gHEOOMLCOCI9 };
		return new PHLJACKOHJK(bHPIABAGAPB, gHEOOMLCOCI7, gHEOOMLCOCI8, iJGNIJAMCML, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF LLGLJBDLBOP()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		BHPIABAGAPB bHPIABAGAPB = ECFGFKNLLGH;
		GHEOOMLCOCI gHEOOMLCOCI = (GHEOOMLCOCI)base.FIJLKLCHMGH;
		if (gHEOOMLCOCI.EJJHHCOFAAI)
		{
			return bHPIABAGAPB.EFOLNCNGADB;
		}
		GHEOOMLCOCI gHEOOMLCOCI2 = (GHEOOMLCOCI)base.NBPANDNEJGI;
		GHEOOMLCOCI gHEOOMLCOCI3 = (GHEOOMLCOCI)base.LAMGGDKLPJH[0];
		uint[] array = MADOAPNPCCB.PLIFFMMBNPM();
		DILDIHBGDAG.MIOEHGDPGAG(gHEOOMLCOCI.AMFCENFNAJJ, array);
		uint[] array2 = MADOAPNPCCB.PLIFFMMBNPM();
		DILDIHBGDAG.MIOEHGDPGAG(array, array2);
		uint[] array3 = MADOAPNPCCB.PLIFFMMBNPM();
		DILDIHBGDAG.MIOEHGDPGAG(gHEOOMLCOCI2.AMFCENFNAJJ, array3);
		uint aMFCENFNAJJ = MADOAPNPCCB.FIBDFFPCDGC(array3, array3, array3);
		DILDIHBGDAG.KKIGIOINLCI(aMFCENFNAJJ, array3);
		uint[] array4 = array;
		DILDIHBGDAG.IBJBIGNPNEM(array, gHEOOMLCOCI2.AMFCENFNAJJ, array4);
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(7, array4, 2, 0u);
		DILDIHBGDAG.KKIGIOINLCI(aMFCENFNAJJ, array4);
		uint[] array5 = MADOAPNPCCB.PLIFFMMBNPM();
		aMFCENFNAJJ = BCMDHIIJKJE.BJPLEKMGBJA(7, array2, 3, 0u, array5);
		DILDIHBGDAG.KKIGIOINLCI(aMFCENFNAJJ, array5);
		GHEOOMLCOCI gHEOOMLCOCI4 = new GHEOOMLCOCI(array2);
		DILDIHBGDAG.MIOEHGDPGAG(array3, gHEOOMLCOCI4.AMFCENFNAJJ);
		DILDIHBGDAG.FBGIHKPECCO(gHEOOMLCOCI4.AMFCENFNAJJ, array4, gHEOOMLCOCI4.AMFCENFNAJJ);
		DILDIHBGDAG.FBGIHKPECCO(gHEOOMLCOCI4.AMFCENFNAJJ, array4, gHEOOMLCOCI4.AMFCENFNAJJ);
		GHEOOMLCOCI gHEOOMLCOCI5 = new GHEOOMLCOCI(array4);
		DILDIHBGDAG.FBGIHKPECCO(array4, gHEOOMLCOCI4.AMFCENFNAJJ, gHEOOMLCOCI5.AMFCENFNAJJ);
		DILDIHBGDAG.IBJBIGNPNEM(gHEOOMLCOCI5.AMFCENFNAJJ, array3, gHEOOMLCOCI5.AMFCENFNAJJ);
		DILDIHBGDAG.FBGIHKPECCO(gHEOOMLCOCI5.AMFCENFNAJJ, array5, gHEOOMLCOCI5.AMFCENFNAJJ);
		GHEOOMLCOCI gHEOOMLCOCI6 = new GHEOOMLCOCI(array3);
		DILDIHBGDAG.LLGLJBDLBOP(gHEOOMLCOCI.AMFCENFNAJJ, gHEOOMLCOCI6.AMFCENFNAJJ);
		if (!gHEOOMLCOCI3.EOJCHPEGABD)
		{
			DILDIHBGDAG.IBJBIGNPNEM(gHEOOMLCOCI6.AMFCENFNAJJ, gHEOOMLCOCI3.AMFCENFNAJJ, gHEOOMLCOCI6.AMFCENFNAJJ);
		}
		return new PHLJACKOHJK(bHPIABAGAPB, gHEOOMLCOCI4, gHEOOMLCOCI5, new KBINBLGGLNE[1] { gHEOOMLCOCI6 }, base.BPGGHHMMCCB);
	}

	public override JGAFKLGGBGF GFLGEFHLIGE(JGAFKLGGBGF BCIHLCMFAEK)
	{
		if (this == BCIHLCMFAEK)
		{
			return LFFNDDCHCMH();
		}
		if (base.IFCDKFANPBO)
		{
			return BCIHLCMFAEK;
		}
		if (BCIHLCMFAEK.IFCDKFANPBO)
		{
			return LLGLJBDLBOP();
		}
		KBINBLGGLNE kBINBLGGLNE = base.FIJLKLCHMGH;
		if (kBINBLGGLNE.EJJHHCOFAAI)
		{
			return BCIHLCMFAEK;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(BCIHLCMFAEK);
	}

	public override JGAFKLGGBGF LFFNDDCHCMH()
	{
		if (base.IFCDKFANPBO || base.FIJLKLCHMGH.EJJHHCOFAAI)
		{
			return this;
		}
		return LLGLJBDLBOP().JEACJNAKLDJ(this);
	}

	public override JGAFKLGGBGF BHKOFHMDACN()
	{
		if (base.IFCDKFANPBO)
		{
			return this;
		}
		return new PHLJACKOHJK(ECFGFKNLLGH, base.NBPANDNEJGI, base.FIJLKLCHMGH.BHKOFHMDACN(), base.LAMGGDKLPJH, base.BPGGHHMMCCB);
	}
}
