using System;
using Org.BouncyCastle.Math;

public class PJCJFHDICDD : CFMMJCMIGNM
{
	private static readonly BigInteger LEAKKKAONKD = BigInteger.One;

	private FHJAHPNDEOK BOFHHECPKNF;

	public void DIOELAHNLKJ(HPBPDALECOG IJJHBEECMBP)
	{
		if (IJJHBEECMBP == null)
		{
			throw new ArgumentNullException("parameters");
		}
		BOFHHECPKNF = (FHJAHPNDEOK)IJJHBEECMBP;
	}

	public HOHJPJDGOLF LOFCKPBODIJ()
	{
		JEHNKJOKBGF jEHNKJOKBGF = BOFHHECPKNF.KPJHHAAOFOH;
		BigInteger aMFCENFNAJJ = NBECELHFBHL(jEHNKJOKBGF.FNPELDEHJKL, BOFHHECPKNF.IPFKDIJBGIM);
		BigInteger cNLILOEEBOJ = AGLFJKEAFDE(jEHNKJOKBGF.MBIJHANOCOC, jEHNKJOKBGF.HBGOKILMBJG, aMFCENFNAJJ);
		return new HOHJPJDGOLF(new NFJLHCNCCHB(cNLILOEEBOJ, jEHNKJOKBGF), new OMGLOKJCNKO(aMFCENFNAJJ, jEHNKJOKBGF));
	}

	private static BigInteger NBECELHFBHL(BigInteger OKDPJHOEPBJ, FBIJJFGLKMK GECCLOFELEC)
	{
		int num = OKDPJHOEPBJ.BitLength >> 2;
		BigInteger bigInteger;
		do
		{
			bigInteger = ODBELJAHGIG.LJJCFCFGOCK(LEAKKKAONKD, OKDPJHOEPBJ.FBGIHKPECCO(LEAKKKAONKD), GECCLOFELEC);
		}
		while (ABHJGAELGKM.BKBGONMOPKI(bigInteger) < num);
		return bigInteger;
	}

	private static BigInteger AGLFJKEAFDE(BigInteger HPHBDNBJPHB, BigInteger HJMBDGKAOBP, BigInteger AMFCENFNAJJ)
	{
		return HJMBDGKAOBP.ICEOCBALAGC(AMFCENFNAJJ, HPHBDNBJPHB);
	}
}
