using System.IO;

public class PJIFHLLNOKB : KIGEMNPNCBN
{
	public PJIFHLLNOKB(Stream OMCALCLJPOD)
		: base(OMCALCLJPOD)
	{
		HICECABJALK(49);
	}

	public PJIFHLLNOKB(Stream OMCALCLJPOD, int LGPKPEMILHA, bool DNBCBHLACCP)
		: base(OMCALCLJPOD, LGPKPEMILHA, DNBCBHLACCP)
	{
		HICECABJALK(49);
	}
}
