public class PLDHHNEGEBN : LNKPCJLANAO
{
	internal ALLINHNNNJN MIABODPHOIP;

	internal GLFDIPNOLKN DFCJKBHFPMG;

	internal GLFDIPNOLKN JPGILNKJPDN;

	internal COCECKPDIKC PINNJBGMGOA;

	internal HMMHEPKCKCP MFNPCJDPPLP;

	internal KAGLNJGDIPD PNHIILIHAMN;

	internal KAGLNJGDIPD MONJJDFLIHN;

	internal HMMHEPKCKCP GMABLJAFDIG;

	internal MHBCFNELGOJ FIJOHFPFBNF;

	internal FJMKMKNJKOI ELMIODLBBLM;

	internal FJMKMKNJKOI DHAHGJGFKKI;

	internal HLAHBGANIKK GPFBAMMMLIA;

	public int AMEDMLOCCBG
	{
		get
		{
			return DFCJKBHFPMG.JBGOANMLBFA.IntValue + 1;
		}
	}

	public GLFDIPNOLKN MDFIDPLLJFA
	{
		get
		{
			return DFCJKBHFPMG;
		}
	}

	public GLFDIPNOLKN LELIDHBEDHP
	{
		get
		{
			return JPGILNKJPDN;
		}
	}

	public COCECKPDIKC ACMDKLDPDLB
	{
		get
		{
			return PINNJBGMGOA;
		}
	}

	public HMMHEPKCKCP HDLJKFNEDDK
	{
		get
		{
			return MFNPCJDPPLP;
		}
	}

	public KAGLNJGDIPD MMNIBJHEOKC
	{
		get
		{
			return PNHIILIHAMN;
		}
	}

	public KAGLNJGDIPD CANALEFHNCI
	{
		get
		{
			return MONJJDFLIHN;
		}
	}

	public HMMHEPKCKCP LNJLMJPFGNK
	{
		get
		{
			return GMABLJAFDIG;
		}
	}

	public MHBCFNELGOJ KBGJHCMPCGH
	{
		get
		{
			return FIJOHFPFBNF;
		}
	}

	public FJMKMKNJKOI LHMACLHPHPJ
	{
		get
		{
			return ELMIODLBBLM;
		}
	}

	public FJMKMKNJKOI PJFJJPCOFDB
	{
		get
		{
			return DHAHGJGFKKI;
		}
	}

	public HLAHBGANIKK GBGIDCHPICA
	{
		get
		{
			return GPFBAMMMLIA;
		}
	}

	internal PLDHHNEGEBN(ALLINHNNNJN MIABODPHOIP)
	{
		int num = 0;
		this.MIABODPHOIP = MIABODPHOIP;
		if (MIABODPHOIP.ECNCPJGHBIG(0) is JIHIOOKBBLB)
		{
			DFCJKBHFPMG = GLFDIPNOLKN.BJLJCGFMFOO((PAANMJLACEF)MIABODPHOIP.ECNCPJGHBIG(0), true);
		}
		else
		{
			num = -1;
			DFCJKBHFPMG = new GLFDIPNOLKN(0);
		}
		JPGILNKJPDN = GLFDIPNOLKN.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(num + 1));
		PINNJBGMGOA = COCECKPDIKC.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(num + 2));
		MFNPCJDPPLP = HMMHEPKCKCP.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(num + 3));
		ALLINHNNNJN aLLINHNNNJN = (ALLINHNNNJN)MIABODPHOIP.ECNCPJGHBIG(num + 4);
		PNHIILIHAMN = KAGLNJGDIPD.BJLJCGFMFOO(aLLINHNNNJN.ECNCPJGHBIG(0));
		MONJJDFLIHN = KAGLNJGDIPD.BJLJCGFMFOO(aLLINHNNNJN.ECNCPJGHBIG(1));
		GMABLJAFDIG = HMMHEPKCKCP.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(num + 5));
		FIJOHFPFBNF = MHBCFNELGOJ.BJLJCGFMFOO(MIABODPHOIP.ECNCPJGHBIG(num + 6));
		for (int num2 = MIABODPHOIP.GMCGMPEEHJP - (num + 6) - 1; num2 > 0; num2--)
		{
			JIHIOOKBBLB jIHIOOKBBLB = (JIHIOOKBBLB)MIABODPHOIP.ECNCPJGHBIG(num + 6 + num2);
			switch (jIHIOOKBBLB.JPBIKBDCEKC)
			{
			case 1:
				ELMIODLBBLM = FJMKMKNJKOI.BJLJCGFMFOO(jIHIOOKBBLB, false);
				break;
			case 2:
				DHAHGJGFKKI = FJMKMKNJKOI.BJLJCGFMFOO(jIHIOOKBBLB, false);
				break;
			case 3:
				GPFBAMMMLIA = HLAHBGANIKK.BJLJCGFMFOO(jIHIOOKBBLB);
				break;
			}
		}
	}

	public static PLDHHNEGEBN BJLJCGFMFOO(PAANMJLACEF NEMEKIOEOLC, bool DHGLJHFEJFL)
	{
		return BJLJCGFMFOO(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC, DHGLJHFEJFL));
	}

	public static PLDHHNEGEBN BJLJCGFMFOO(object NEMEKIOEOLC)
	{
		if (NEMEKIOEOLC is PLDHHNEGEBN)
		{
			return (PLDHHNEGEBN)NEMEKIOEOLC;
		}
		if (NEMEKIOEOLC != null)
		{
			return new PLDHHNEGEBN(ALLINHNNNJN.BJLJCGFMFOO(NEMEKIOEOLC));
		}
		return null;
	}

	public override EDOEBJJFOBM IIHKEACDNID()
	{
		return MIABODPHOIP;
	}
}
