using Org.BouncyCastle.Math;

internal class PNKPNHLPKNF
{
	internal static readonly uint[] MBIJHANOCOC = new uint[8] { 4294966319u, 4294967294u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u };

	internal static readonly uint[] PKABKFGEMBB = new uint[16]
	{
		954529u, 1954u, 1u, 0u, 0u, 0u, 0u, 0u, 4294965342u, 4294967293u,
		4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u
	};

	private static readonly uint[] BPGLGHCLMCD = new uint[10] { 4294012767u, 4294965341u, 4294967294u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 4294967295u, 1953u, 2u };

	private const uint IIHHAHBGDFC = uint.MaxValue;

	private const uint LDNLCGGHMJE = uint.MaxValue;

	private const uint BIFDMIEAMDM = 977u;

	public static void JEACJNAKLDJ(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		if (AKOICJCJNFB.JEACJNAKLDJ(AMFCENFNAJJ, CNLILOEEBOJ, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[7] == uint.MaxValue && AKOICJCJNFB.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(8, 977u, IGNEOOOFEMO);
		}
	}

	public static void KGBEKKMEBCN(uint[] HGHHJPDIMCI, uint[] IKEIELCEKPD, uint[] JMNJPLAGDDJ)
	{
		if ((BCMDHIIJKJE.JEACJNAKLDJ(16, HGHHJPDIMCI, IKEIELCEKPD, JMNJPLAGDDJ) != 0 || (JMNJPLAGDDJ[15] == uint.MaxValue && BCMDHIIJKJE.CHCGDEIGIIA(16, JMNJPLAGDDJ, PKABKFGEMBB))) && BCMDHIIJKJE.MAALDEFJPJA(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.DKCBNAFCCMF(16, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void AOAINNMNBHC(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (BCMDHIIJKJE.CKIHMFAAHLM(8, AMFCENFNAJJ, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[7] == uint.MaxValue && AKOICJCJNFB.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(8, 977u, IGNEOOOFEMO);
		}
	}

	public static uint[] HFENNGHNFLF(BigInteger AMFCENFNAJJ)
	{
		uint[] array = AKOICJCJNFB.HFENNGHNFLF(AMFCENFNAJJ);
		if (array[7] == uint.MaxValue && AKOICJCJNFB.CHCGDEIGIIA(array, MBIJHANOCOC))
		{
			AKOICJCJNFB.DKAMAFLMHEJ(MBIJHANOCOC, array);
		}
		return array;
	}

	public static void CBGFKBFBIFD(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if ((AMFCENFNAJJ[0] & 1) == 0)
		{
			BCMDHIIJKJE.POFAGJIFAIH(8, AMFCENFNAJJ, 0u, IGNEOOOFEMO);
			return;
		}
		uint fMFABAKPMLB = AKOICJCJNFB.JEACJNAKLDJ(AMFCENFNAJJ, MBIJHANOCOC, IGNEOOOFEMO);
		BCMDHIIJKJE.POFAGJIFAIH(8, IGNEOOOFEMO, fMFABAKPMLB);
	}

	public static void IBJBIGNPNEM(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = AKOICJCJNFB.DCPJKFEDHOJ();
		AKOICJCJNFB.BMEIFJDODCF(AMFCENFNAJJ, CNLILOEEBOJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
	}

	public static void OMJFFHEIEFH(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] JMNJPLAGDDJ)
	{
		if ((AKOICJCJNFB.HHMEIAJHDJM(AMFCENFNAJJ, CNLILOEEBOJ, JMNJPLAGDDJ) != 0 || (JMNJPLAGDDJ[15] == uint.MaxValue && BCMDHIIJKJE.CHCGDEIGIIA(16, JMNJPLAGDDJ, PKABKFGEMBB))) && BCMDHIIJKJE.MAALDEFJPJA(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.DKCBNAFCCMF(16, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void BHKOFHMDACN(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (AKOICJCJNFB.EJJHHCOFAAI(AMFCENFNAJJ))
		{
			AKOICJCJNFB.KEOKCFDNHPP(IGNEOOOFEMO);
		}
		else
		{
			AKOICJCJNFB.EAEONHFLEEN(MBIJHANOCOC, AMFCENFNAJJ, IGNEOOOFEMO);
		}
	}

	public static void BKCHMGKFECM(uint[] HGHHJPDIMCI, uint[] IGNEOOOFEMO)
	{
		ulong cNLILOEEBOJ = AKOICJCJNFB.FGMIACGNJLN(977u, HGHHJPDIMCI, 8, HGHHJPDIMCI, 0, IGNEOOOFEMO, 0);
		if (AKOICJCJNFB.CDNAAKLGHLD(977u, cNLILOEEBOJ, IGNEOOOFEMO, 0) != 0 || (IGNEOOOFEMO[7] == uint.MaxValue && AKOICJCJNFB.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(8, 977u, IGNEOOOFEMO);
		}
	}

	public static void KKIGIOINLCI(uint AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if ((AMFCENFNAJJ != 0 && AKOICJCJNFB.KDGIJAIDNND(977u, AMFCENFNAJJ, IGNEOOOFEMO, 0) != 0) || (IGNEOOOFEMO[7] == uint.MaxValue && AKOICJCJNFB.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(8, 977u, IGNEOOOFEMO);
		}
	}

	public static void MIOEHGDPGAG(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = AKOICJCJNFB.DCPJKFEDHOJ();
		AKOICJCJNFB.MIOEHGDPGAG(AMFCENFNAJJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
	}

	public static void OIEFGPHNOFN(uint[] AMFCENFNAJJ, int IDHLPOFDLKJ, uint[] IGNEOOOFEMO)
	{
		uint[] array = AKOICJCJNFB.DCPJKFEDHOJ();
		AKOICJCJNFB.MIOEHGDPGAG(AMFCENFNAJJ, array);
		BKCHMGKFECM(array, IGNEOOOFEMO);
		while (--IDHLPOFDLKJ > 0)
		{
			AKOICJCJNFB.MIOEHGDPGAG(IGNEOOOFEMO, array);
			BKCHMGKFECM(array, IGNEOOOFEMO);
		}
	}

	public static void FBGIHKPECCO(uint[] AMFCENFNAJJ, uint[] CNLILOEEBOJ, uint[] IGNEOOOFEMO)
	{
		if (AKOICJCJNFB.EAEONHFLEEN(AMFCENFNAJJ, CNLILOEEBOJ, IGNEOOOFEMO) != 0)
		{
			BCMDHIIJKJE.KGIMHKMDCKA(8, 977u, IGNEOOOFEMO);
		}
	}

	public static void OIKFFIIOCPO(uint[] HGHHJPDIMCI, uint[] IKEIELCEKPD, uint[] JMNJPLAGDDJ)
	{
		if (BCMDHIIJKJE.EAEONHFLEEN(16, HGHHJPDIMCI, IKEIELCEKPD, JMNJPLAGDDJ) != 0 && BCMDHIIJKJE.DKAMAFLMHEJ(BPGLGHCLMCD.Length, BPGLGHCLMCD, JMNJPLAGDDJ) != 0)
		{
			BCMDHIIJKJE.MEJBLKJLLNK(16, JMNJPLAGDDJ, BPGLGHCLMCD.Length);
		}
	}

	public static void LLGLJBDLBOP(uint[] AMFCENFNAJJ, uint[] IGNEOOOFEMO)
	{
		if (BCMDHIIJKJE.FKEFFJALNJM(8, AMFCENFNAJJ, 0u, IGNEOOOFEMO) != 0 || (IGNEOOOFEMO[7] == uint.MaxValue && AKOICJCJNFB.CHCGDEIGIIA(IGNEOOOFEMO, MBIJHANOCOC)))
		{
			BCMDHIIJKJE.BJPICMNLAOG(8, 977u, IGNEOOOFEMO);
		}
	}
}
