using Assets.Scripts.GamePlayScene.Mechanics;
using Assets.Scripts.Utils.Analytics;

internal static class PPGOIFOCOAK
{
	public static void FBANJNDJEOG()
	{
		GBFAPADEBEC.PFGLLCEKCGI(PBIIDJOKNEK.ResetManager, "Removing all old data.");
		CAGBGIHKHEJ.GABGKBAKHDP.APNJAPLPHMB(LECPGNKOABP.GABGKBAKHDP.GDMECFECCOM.ToString());
		OMOKOKFNBKI();
	}

	public static void JOCMJBFJGON()
	{
		OMOKOKFNBKI();
		OLPDHHJNCFE();
		CKOMJCFADMM.BBGLCADIONK();
		PHHKFLHAFHG.PEDBOELHCPG();
		PeakAnalytics.ClearData();
		GBFAPADEBEC.OMOKOKFNBKI();
	}

	private static void OMOKOKFNBKI()
	{
		GFHPEDILAJG.GABGKBAKHDP.OMOKOKFNBKI();
		GEBAAFFGKJG.GABGKBAKHDP.OMOKOKFNBKI();
		MADFPPJCOIM.GABGKBAKHDP.OMOKOKFNBKI();
		MDGKDGMGGCL.GABGKBAKHDP.OMOKOKFNBKI();
		LECPGNKOABP.GABGKBAKHDP.OMOKOKFNBKI();
		MKINMKEMBPL.GABGKBAKHDP.OMOKOKFNBKI();
		EKGLBJJKNBG.GABGKBAKHDP.OMOKOKFNBKI();
		AGLOLLABINO.GABGKBAKHDP.OMOKOKFNBKI();
		JCGLFEMHECF.GABGKBAKHDP.OMOKOKFNBKI();
		NDGOJGLPIJF.GABGKBAKHDP.OMOKOKFNBKI();
		LevelBuilder.Reset();
		IDFPAFEJPPH.GABGKBAKHDP.OMOKOKFNBKI();
		CAGBGIHKHEJ.GABGKBAKHDP.OMOKOKFNBKI();
		DGOMNDMPMBG.GABGKBAKHDP.OMOKOKFNBKI();
		DIGGBGADIGJ.GABGKBAKHDP.OMOKOKFNBKI();
		DJFEHCGIDGC.GABGKBAKHDP.OMOKOKFNBKI();
		BPPNANHCLJI.GABGKBAKHDP.OMOKOKFNBKI();
	}

	private static void OLPDHHJNCFE()
	{
		FIFPLICICKP.GABGKBAKHDP.BBGLCADIONK();
		HLFNMNPLJCP.GABGKBAKHDP.BBGLCADIONK();
		IONAGMPHNPM.GABGKBAKHDP.BBGLCADIONK();
		MGNLLDDOHKN.GABGKBAKHDP.BBGLCADIONK();
		HJBLKNBHMFJ.GABGKBAKHDP.BBGLCADIONK();
	}
}
